              0x1ea4
#define mmDCP3_REGAMMA_CNTLA_START_CNTL                                         0x40a4
#define mmDCP4_REGAMMA_CNTLA_START_CNTL                                         0x42a4
#define mmDCP5_REGAMMA_CNTLA_START_CNTL                                         0x44a4
#define mmREGAMMA_CNTLA_SLOPE_CNTL                                              0x1aa5
#define mmDCP0_REGAMMA_CNTLA_SLOPE_CNTL                                         0x1aa5
#define mmDCP1_REGAMMA_CNTLA_SLOPE_CNTL                                         0x1ca5
#define mmDCP2_REGAMMA_CNTLA_SLOPE_CNTL                                         0x1ea5
#define mmDCP3_REGAMMA_CNTLA_SLOPE_CNTL                                         0x40a5
#define mmDCP4_REGAMMA_CNTLA_SLOPE_CNTL                                         0x42a5
#define mmDCP5_REGAMMA_CNTLA_SLOPE_CNTL                                         0x44a5
#define mmREGAMMA_CNTLA_END_CNTL1                                               0x1aa6
#define mmDCP0_REGAMMA_CNTLA_END_CNTL1                                          0x1aa6
#define mmDCP1_REGAMMA_CNTLA_END_CNTL1                                          0x1ca6
#define mmDCP2_REGAMMA_CNTLA_END_CNTL1                                          0x1ea6
#define mmDCP3_REGAMMA_CNTLA_END_CNTL1                                          0x40a6
#define mmDCP4_REGAMMA_CNTLA_END_CNTL1                                          0x42a6
#define mmDCP5_REGAMMA_CNTLA_END_CNTL1                                          0x44a6
#define mmREGAMMA_CNTLA_END_CNTL2                                               0x1aa7
#define mmDCP0_REGAMMA_CNTLA_END_CNTL2                                          0x1aa7
#define mmDCP1_REGAMMA_CNTLA_END_CNTL2                                          0x1ca7
#define mmDCP2_REGAMMA_CNTLA_END_CNTL2                                          0x1ea7
#define mmDCP3_REGAMMA_CNTLA_END_CNTL2                                          0x40a7
#define mmDCP4_REGAMMA_CNTLA_END_CNTL2                                          0x42a7
#define mmDCP5_REGAMMA_CNTLA_END_CNTL2                                          0x44a7
#define mmREGAMMA_CNTLA_REGION_0_1                                              0x1aa8
#define mmDCP0_REGAMMA_CNTLA_REGION_0_1                                         0x1aa8
#define mmDCP1_REGAMMA_CNTLA_REGION_0_1                                         0x1ca8
#define mmDCP2_REGAMMA_CNTLA_REGION_0_1                                         0x1ea8
#define mmDCP3_REGAMMA_CNTLA_REGION_0_1                                         0x40a8
#define mmDCP4_REGAMMA_CNTLA_REGION_0_1                                         0x42a8
#define mmDCP5_REGAMMA_CNTLA_REGION_0_1                                         0x44a8
#define mmREGAMMA_CNTLA_REGION_2_3                                              0x1aa9
#define mmDCP0_REGAMMA_CNTLA_REGION_2_3                                         0x1aa9
#define mmDCP1_REGAMMA_CNTLA_REGION_2_3                                         0x1ca9
#define mmDCP2_REGAMMA_CNTLA_REGION_2_3                                         0x1ea9
#define mmDCP3_REGAMMA_CNTLA_REGION_2_3                                         0x40a9
#define mmDCP4_REGAMMA_CNTLA_REGION_2_3                                         0x42a9
#define mmDCP5_REGAMMA_CNTLA_REGION_2_3                                         0x44a9
#define mmREGAMMA_CNTLA_REGION_4_5                                              0x1aaa
#define mmDCP0_REGAMMA_CNTLA_REGION_4_5                                         0x1aaa
#define mmDCP1_REGAMMA_CNTLA_REGION_4_5                                         0x1caa
#define mmDCP2_REGAMMA_CNTLA_REGION_4_5                                         0x1eaa
#define mmDCP3_REGAMMA_CNTLA_REGION_4_5                                         0x40aa
#define mmDCP4_REGAMMA_CNTLA_REGION_4_5                                         0x42aa
#define mmDCP5_REGAMMA_CNTLA_REGION_4_5                                         0x44aa
#define mmREGAMMA_CNTLA_REGION_6_7                                              0x1aab
#define mmDCP0_REGAMMA_CNTLA_REGION_6_7                                         0x1aab
#define mmDCP1_REGAMMA_CNTLA_REGION_6_7                                         0x1cab
#define mmDCP2_REGAMMA_CNTLA_REGION_6_7                                         0x1eab
#define mmDCP3_REGAMMA_CNTLA_REGION_6_7                                         0x40ab
#define mmDCP4_REGAMMA_CNTLA_REGION_6_7                                         0x42ab
#define mmDCP5_REGAMMA_CNTLA_REGION_6_7                                         0x44ab
#define mmREGAMMA_CNTLA_REGION_8_9                                              0x1aac
#define mmDCP0_REGAMMA_CNTLA_REGION_8_9                                         0x1aac
#define mmDCP1_REGAMMA_CNTLA_REGION_8_9                                         0x1cac
#define mmDCP2_REGAMMA_CNTLA_REGION_8_9                                         0x1eac
#define mmDCP3_REGAMMA_CNTLA_REGION_8_9                                         0x40ac
#define mmDCP4_REGAMMA_CNTLA_REGION_8_9                                         0x42ac
#define mmDCP5_REGAMMA_CNTLA_REGION_8_9                                         0x44ac
#define mmREGAMMA_CNTLA_REGION_10_11                                            0x1aad
#define mmDCP0_REGAMMA_CNTLA_REGION_10_11                                       0x1aad
#define mmDCP1_REGAMMA_CNTLA_REGION_10_11                                       0x1cad
#define mmDCP2_REGAMMA_CNTLA_REGION_10_11                                       0x1ead
#define mmDCP3_REGAMMA_CNTLA_REGION_10_11                                       0x40ad
#define mmDCP4_REGAMMA_CNTLA_REGION_10_11                                       0x42ad
#define mmDCP5_REGAMMA_CNTLA_REGION_10_11                                       0x44ad
#define mmREGAMMA_CNTLA_REGION_12_13                                            0x1aae
#define mmDCP0_REGAMMA_CNTLA_REGION_12_13                                       0x1aae
#define mmDCP1_REGAMMA_CNTLA_REGION_12_13                                       0x1cae
#define mmDCP2_REGAMMA_CNTLA_REGION_12_13                                       0x1eae
#define mmDCP3_REGAMMA_CNTLA_REGION_12_13                                       0x40ae
#define mmDCP4_REGAMMA_CNTLA_REGION_12_13                                       0x42ae
#define mmDCP5_REGAMMA_CNTLA_REGION_12_13                                       0x44ae
#define mmREGAMMA_CNTLA_REGION_14_15                                            0x1aaf
#define mmDCP0_REGAMMA_CNTLA_REGION_14_15                                       0x1aaf
#define mmDCP1_REGAMMA_CNTLA_REGION_14_15                                       0x1caf
#define mmDCP2_REGAMMA_CNTLA_REGION_14_15                                       0x1eaf
#define mmDCP3_REGAMMA_CNTLA_REGION_14_15                                       0x40af
#define mmDCP4_REGAMMA_CNTLA_REGION_14_15                                       0x42af
#define mmDCP5_REGAMMA_CNTLA_REGION_14_15                                       0x44af
#define mmREGAMMA_CNTLB_START_CNTL                                              0x1ab0
#define mmDCP0_REGAMMA_CNTLB_START_CNTL                                         0x1ab0
#define mmDCP1_REGAMMA_CNTLB_START_CNTL                                         0x1cb0
#define mmDCP2_REGAMMA_CNTLB_START_CNTL                                         0x1eb0
#define mmDCP3_REGAMMA_CNTLB_START_CNTL                                         0x40b0
#define mmDCP4_REGAMMA_CNTLB_START_CNTL                                         0x42b0
#define mmDCP5_REGAMMA_CNTLB_START_CNTL                                         0x44b0
#define mmREGAMMA_CNTLB_SLOPE_CNTL                                              0x1ab1
#define mmDCP0_REGAMMA_CNTLB_SLOPE_CNTL                                         0x1ab1
#define mmDCP1_REGAMMA_CNTLB_SLOPE_CNTL                                         0x1cb1
#define mmDCP2_REGAMMA_CNTLB_SLOPE_CNTL                                         0x1eb1
#define mmDCP3_REGAMMA_CNTLB_SLOPE_CNTL                                         0x40b1
#define mmDCP4_REGAMMA_CNTLB_SLOPE_CNTL                                         0x42b1
#define mmDCP5_REGAMMA_CNTLB_SLOPE_CNTL                                         0x44b1
#define mmREGAMMA_CNTLB_END_CNTL1                                               0x1ab2
#define mmDCP0_REGAMMA_CNTLB_END_CNTL1                                          0x1ab2
#define mmDCP1_REGAMMA_CNTLB_END_CNTL1                                          0x1cb2
#define mmDCP2_REGAMMA_CNTLB_END_CNTL1                                          0x1eb2
#define mmDCP3_REGAMMA_CNTLB_END_CNTL1                                          0x40b2
#define mmDCP4_REGAMMA_CNTLB_END_CNTL1                                          0x42b2
#define mmDCP5_REGAMMA_CNTLB_END_CNTL1                                          0x44b2
#define mmREGAMMA_CNTLB_END_CNTL2                                               0x1ab3
#define mmDCP0_REGAMMA_CNTLB_END_CNTL2                                          0x1ab3
#define mmDCP1_REGAMMA_CNTLB_END_CNTL2                                          0x1cb3
#define mmDCP2_REGAMMA_CNTLB_END_CNTL2                                          0x1eb3
#define mmDCP3_REGAMMA_CNTLB_END_CNTL2                                          0x40b3
#define mmDCP4_REGAMMA_CNTLB_END_CNTL2                                          0x42b3
#define mmDCP5_REGAMMA_CNTLB_END_CNTL2                                          0x44b3
#define mmREGAMMA_CNTLB_REGION_0_1                                              0x1ab4
#define mmDCP0_REGAMMA_CNTLB_REGION_0_1                                         0x1ab4
#define mmDCP1_REGAMMA_CNTLB_REGION_0_1                                         0x1cb4
#define mmDCP2_REGAMMA_CNTLB_REGION_0_1                                         0x1eb4
#define mmDCP3_REGAMMA_CNTLB_REGION_0_1                                         0x40b4
#define mmDCP4_REGAMMA_CNTLB_REGION_0_1                                         0x42b4
#define mmDCP5_REGAMMA_CNTLB_REGION_0_1                                         0x44b4
#define mmREGAMMA_CNTLB_REGION_2_3                                              0x1ab5
#define mmDCP0_REGAMMA_CNTLB_REGION_2_3                                         0x1ab5
#define mmDCP1_REGAMMA_CNTLB_REGION_2_3                                         0x1cb5
#define mmDCP2_REGAMMA_CNTLB_REGION_2_3                                         0x1eb5
#define mmDCP3_REGAMMA_CNTLB_REGION_2_3                                         0x40b5
#define mmDCP4_REGAMMA_CNTLB_REGION_2_3                                         0x42b5
#define mmDCP5_REGAMMA_CNTLB_REGION_2_3                                         0x44b5
#define mmREGAMMA_CNTLB_REGION_4_5                                              0x1ab6
#define mmDCP0_REGAMMA_CNTLB_REGION_4_5                                         0x1ab6
#define mmDCP1_REGAMMA_CNTLB_REGION_4_5                                         0x1cb6
#define mmDCP2_REGAMMA_CNTLB_REGION_4_5                                         0x1eb6
#define mmDCP3_REGAMMA_CNTLB_REGION_4_5                                         0x40b6
#define mmDCP4_REGAMMA_CNTLB_REGION_4_5                                         0x42b6
#define mmDCP5_REGAMMA_CNTLB_REGION_4_5                                         0x44b6
#define mmREGAMMA_CNTLB_REGION_6_7                                              0x1ab7
#define mmDCP0_REGAMMA_CNTLB_REGION_6_7                                         0x1ab7
#define mmDCP1_REGAMMA_CNTLB_REGION_6_7                                         0x1cb7
#define mmDCP2_REGAMMA_CNTLB_REGION_6_7                                         0x1eb7
#define mmDCP3_REGAMMA_CNTLB_REGION_6_7                                         0x40b7
#define mmDCP4_REGAMMA_CNTLB_REGION_6_7                                         0x42b7
#define mmDCP5_REGAMMA_CNTLB_REGION_6_7                                         0x44b7
#define mmREGAMMA_CNTLB_REGION_8_9                                              0x1ab8
#define mmDCP0_REGAMMA_CNTLB_REGION_8_9                                         0x1ab8
#define mmDCP1_REGAMMA_CNTLB_REGION_8_9                                         0x1cb8
#define mmDCP2_REGAMMA_CNTLB_REGION_8_9                                         0x1eb8
#define mmDCP3_REGAMMA_CNTLB_REGION_8_9                                         0x40b8
#define mmDCP4_REGAMMA_CNTLB_REGION_8_9                                         0x42b8
#define mmDCP5_REGAMMA_CNTLB_REGION_8_9                                         0x44b8
#define mmREGAMMA_CNTLB_REGION_10_11                                            0x1ab9
#define mmDCP0_REGAMMA_CNTLB_REGION_10_11                                       0x1ab9
#define mmDCP1_REGAMMA_CNTLB_REGION_10_11                                       0x1cb9
#define mmDCP2_REGAMMA_CNTLB_REGION_10_11                                       0x1eb9
#define mmDCP3_REGAMMA_CNTLB_REGION_10_11                                       0x40b9
#define mmDCP4_REGAMMA_CNTLB_REGION_10_11                                       0x42b9
#define mmDCP5_REGAMMA_CNTLB_REGION_10_11                                       0x44b9
#define mmREGAMMA_CNTLB_REGION_12_13                                            0x1aba
#define mmDCP0_REGAMMA_CNTLB_REGION_12_13                                       0x1aba
#define mmDCP1_REGAMMA_CNTLB_REGION_12_13                                       0x1cba
#define mmDCP2_REGAMMA_CNTLB_REGION_12_13                                       0x1eba
#define mmDCP3_REGAMMA_CNTLB_REGION_12_13                                       0x40ba
#define mmDCP4_REGAMMA_CNTLB_REGION_12_13                                       0x42ba
#define mmDCP5_REGAMMA_CNTLB_REGION_12_13                                       0x44ba
#define mmREGAMMA_CNTLB_REGION_14_15                                            0x1abb
#define mmDCP0_REGAMMA_CNTLB_REGION_14_15                                       0x1abb
#define mmDCP1_REGAMMA_CNTLB_REGION_14_15                                       0x1cbb
#define mmDCP2_REGAMMA_CNTLB_REGION_14_15                                       0x1ebb
#define mmDCP3_REGAMMA_CNTLB_REGION_14_15                                       0x40bb
#define mmDCP4_REGAMMA_CNTLB_REGION_14_15                                       0x42bb
#define mmDCP5_REGAMMA_CNTLB_REGION_14_15                                       0x44bb
#define mmALPHA_CONTROL                                                         0x1abc
#define mmDCP0_ALPHA_CONTROL                                                    0x1abc
#define mmDCP1_ALPHA_CONTROL                                                    0x1cbc
#define mmDCP2_ALPHA_CONTROL                                                    0x1ebc
#define mmDCP3_ALPHA_CONTROL                                                    0x40bc
#define mmDCP4_ALPHA_CONTROL                                                    0x42bc
#