efine mmCRTC4_CRTC_STATUS_FRAME_COUNT                                         0x43a6
#define mmCRTC5_CRTC_STATUS_FRAME_COUNT                                         0x45a6
#define mmCRTC_STATUS_VF_COUNT                                                  0x1ba7
#define mmCRTC0_CRTC_STATUS_VF_COUNT                                            0x1ba7
#define mmCRTC1_CRTC_STATUS_VF_COUNT                                            0x1da7
#define mmCRTC2_CRTC_STATUS_VF_COUNT                                            0x1fa7
#define mmCRTC3_CRTC_STATUS_VF_COUNT                                            0x41a7
#define mmCRTC4_CRTC_STATUS_VF_COUNT                                            0x43a7
#define mmCRTC5_CRTC_STATUS_VF_COUNT                                            0x45a7
#define mmCRTC_STATUS_HV_COUNT                                                  0x1ba8
#define mmCRTC0_CRTC_STATUS_HV_COUNT                                            0x1ba8
#define mmCRTC1_CRTC_STATUS_HV_COUNT                                            0x1da8
#define mmCRTC2_CRTC_STATUS_HV_COUNT                                            0x1fa8
#define mmCRTC3_CRTC_STATUS_HV_COUNT                                            0x41a8
#define mmCRTC4_CRTC_STATUS_HV_COUNT                                            0x43a8
#define mmCRTC5_CRTC_STATUS_HV_COUNT                                            0x45a8
#define mmCRTC_COUNT_CONTROL                                                    0x1ba9
#define mmCRTC0_CRTC_COUNT_CONTROL                                              0x1ba9
#define mmCRTC1_CRTC_COUNT_CONTROL                                              0x1da9
#define mmCRTC2_CRTC_COUNT_CONTROL                                              0x1fa9
#define mmCRTC3_CRTC_COUNT_CONTROL                                              0x41a9
#define mmCRTC4_CRTC_COUNT_CONTROL                                              0x43a9
#define mmCRTC5_CRTC_COUNT_CONTROL                                              0x45a9
#define mmCRTC_COUNT_RESET                                                      0x1baa
#define mmCRTC0_CRTC_COUNT_RESET                                                0x1baa
#define mmCRTC1_CRTC_COUNT_RESET                                                0x1daa
#define mmCRTC2_CRTC_COUNT_RESET                                                0x1faa
#define mmCRTC3_CRTC_COUNT_RESET                                                0x41aa
#define mmCRTC4_CRTC_COUNT_RESET                                                0x43aa
#define mmCRTC5_CRTC_COUNT_RESET                                                0x45aa
#define mmCRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                                     0x1bab
#define mmCRTC0_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x1bab
#define mmCRTC1_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x1dab
#define mmCRTC2_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x1fab
#define mmCRTC3_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x41ab
#define mmCRTC4_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x43ab
#define mmCRTC5_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x45ab
#define mmCRTC_VERT_SYNC_CONTROL                                                0x1bac
#define mmCRTC0_CRTC_VERT_SYNC_CONTROL                                          0x1bac
#define mmCRTC1_CRTC_VERT_SYNC_CONTROL                                          0x1dac
#define mmCRTC2_CRTC_VERT_SYNC_CONTROL                                          0x1fac
#define mmCRTC3_CRTC_VERT_SYNC_CONTROL                                          0x41ac
#define mmCRTC4_CRTC_VERT_SYNC_CONTROL                                          0x43ac
#define mmCRTC5_CRTC_VERT_SYNC_CONTROL                                          0x45ac
#define mmCRTC_STEREO_STATUS                                                    0x1bad
#define mmCRTC0_CRTC_STEREO_STATUS                                              0x1bad
#define mmCRTC1_CRTC_STEREO_STATUS                                              0x1dad
#define mmCRTC2_CRTC_STEREO_STATUS                                              0x1fad
#define mmCRTC3_CRTC_STEREO_STATUS                                              0x41ad
#define mmCRTC4_CRTC_STEREO_STATUS                                              0x43ad
#define mmCRTC5_CRTC_STEREO_STATUS                                              0x45ad
#define mmCRTC_STEREO_CONTROL                                                   0x1bae
#define mmCRTC0_CRTC_STEREO_CONTROL                                             0x1bae
#define mmCRTC1_CRTC_STEREO_CONTROL                                             0x1dae
#define mmCRTC2_CRTC_STEREO_CONTROL                                             0x1fae
#define mmCRTC3_CRTC_STEREO_CONTROL                                             0x41ae
#define mmCRTC4_CRTC_STEREO_CONTROL                                             0x43ae
#define mmCRTC5_CRTC_STEREO_CONTROL                                             0x45ae
#define mmCRTC_SNAPSHOT_STATUS                                                  0x1baf
#define mmCRTC0_CRTC_SNAPSHOT_STATUS                                            0x1baf
#define mmCRTC1_CRTC_SNAPSHOT_STATUS                                            0x1daf
#define mmCRTC2_CRTC_SNAPSHOT_STATUS                                            0x1faf
#define mmCRTC3_CRTC_SNAPSHOT_STATUS                                            0x41af
#define mmCRTC4_CRTC_SNAPSHOT_STATUS                                            0x43af
#define mmCRTC5_CRTC_SNAPSHOT_STATUS                                            0x45af
#define mmCRTC_SNAPSHOT_CONTROL                                                 0x1bb0
#define mmCRTC0_CRTC_SNAPSHOT_CONTROL                                           0x1bb0
#define mmCRTC1_CRTC_SNAPSHOT_CONTROL                                           0x1db0
#define mmCRTC2_CRTC_SNAPSHOT_CONTROL                                           0x1fb0
#define mmCRTC3_CRTC_SNAPSHOT_CONTROL                                           0x41b0
#define mmCRTC4_CRTC_SNAPSHOT_CONTROL                                           0x43b0
#define mmCRTC5_CRTC_SNAPSHOT_CONTROL                                           0x45b0
#define mmCRTC_SNAPSHOT_POSITION                                                0x1bb1
#define mmCRTC0_CRTC_SNAPSHOT_POSITION                                          0x1bb1
#define mmCRTC1_CRTC_SNAPSHOT_POSITION                                          0x1db1
#define mmCRTC2_CRTC_SNAPSHOT_POSITION                                          0x1fb1
#define mmCRTC3_CRTC_SNAPSHOT_POSITION                                          0x41b1
#define mmCRTC4_CRTC_SNAPSHOT_POSITION                                          0x43b1
#define mmCRTC5_CRTC_SNAPSHOT_POSITION                                          0x45b1
#define mmCRTC_SNAPSHOT_FRAME                                                   0x1bb2
#define mmCRTC0_CRTC_SNAPSHOT_FRAME                                             0x1bb2
#define mmCRTC1_CRTC_SNAPSHOT_FRAME                                             0x1db2
#define mmCRTC2_CRTC_SNAPSHOT_FRAME                                             0x1fb2
#define mmCRTC3_CRTC_SNAPSHOT_FRAME                                             0x41b2
#define mmCRTC4_CRTC_SNAPSHOT_FRAME                                             0x43b2
#define mmCRTC5_CRTC_SNAPSHOT_FRAME                                             0x45b2
#define mmCRTC_START_LINE_CONTROL                                               0x1bb3
#define mmCRTC0_CRTC_START_LINE_CONTROL                                         0x1bb3
#define mmCRTC1_CRTC_START_LINE_CONTROL                                         0x1db3
#define mmCRTC2_CRTC_START_LINE_CONTROL                                         0x1fb3
#define mmCRTC3_CRTC_START_LINE_CONTROL                                         0x41b3
#define mmCRTC4_CRTC_START_LINE_CONTROL                                         0x43b3
#define mmCRTC5_CRTC_START_LINE_CONTROL                                         0x45b3
#define mmCRTC_INTERRUPT_CONTROL                                                0x1bb4
#define mmCRTC0_CRTC_INTERRUPT_CONTROL                                          0x1bb4
#define mmCRTC1_CRTC_INTERRUPT_CONTROL                                          0x1db4
#define mmCRTC2_CRTC_INTERRUPT_CONTROL                                          0x1fb4
#define mmCRTC3_CRTC_INTERRUPT_CONTROL                                          0x41b4
#define mmCRTC4_CRTC_INTERRUPT_CONTROL                                          0x43b4
#define mmCRTC5_CRTC_INTERRUPT_CONTROL                                          0x45b4
#define mmCRTC_UPDATE_LOCK                                                      0x1bb5
#define mmCRTC0_CRTC_UPDATE_LOCK                                                0x1bb5
#define mmCRTC1_CRTC_UPDATE_LOCK                                                0x1db5
#define mmCRTC2_CRTC_UPDATE_LOCK                                                0x1fb5
#define mmCRTC3_CRTC_UPDATE_LOCK                                                0x41b5
#define mmCRTC4_CRTC_UPDATE_LOCK                                                0x43b5
#define mmCRTC5_CRTC_UPDATE_LOCK                                                0x45b5
#define mmCRTC_DOUBLE_BUFFER_CONTROL                                            0x1bb6
#define mmCRTC0_CRTC_DOUBLE_BUFFER_CONTROL                                      0x1bb6
#define mmCRTC1_CRTC_DOUBLE_BUFFER_CONTROL                                      0x1db6
#define mmCRTC2_CRTC_DOUBLE_BUFFER_CONTROL                                      0x1fb6
#define mmCRTC3_CRTC_DOUBLE_BUFFER_CONTROL                                      0x41b6
#define mmCRTC4_CRTC_DOUBLE_BUFFER_CONTROL                                      0x43b6
#define mmCRTC5_CRTC_DOUBLE_BUFFER_CONTROL                                      0x45b6
#define mmCRTC_VGA_PARAMETER_CAPTURE_MODE                                       0x1bb7
#define mmCRTC0_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x1bb7
#define mmCRTC1_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x1db7
#define mmCRTC2_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x1fb7
#define mmCRTC3_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x41b7
#define mmCRTC4_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x43b7
#define mmCRTC5_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x45b7
#define mmCRTC_TEST_PATTERN_CONTROL                                             0x1bba
#define mmCRTC0_CRTC_TEST_PATTERN_CONTROL                                       0x1bba
#define mmCRTC1_CRTC_TEST_PATTERN_CONTROL                                       0x1dba
#define mmCRTC2_CRTC_TEST_PATTERN_CONTROL                                       0x1fba
#define mmCRTC3_CRTC_TEST_PATTERN_CONTROL                                       0x41ba
#define mmCRTC4_CRTC_TEST_PATTERN_CONTROL                                       0x43ba
#define mmCRTC5_CRTC_TEST_PATTERN_CONTROL                                       0x45ba
#define mmCRTC_TEST_PATTERN_PARAMETERS                                          0x1bbb
#define mmCRTC0_CRTC_TEST_PATTERN_PARAMETERS                                    0x1bbb
#define mmCRTC1_CRTC_TEST_PATTERN_PARAMETERS                                    0x1dbb
#define mmCRTC2_CRTC_TEST_PATTERN_PARAMETERS                                    0x1fbb
#define mmCRTC3_CRTC_TEST_PATTERN_PARAMETERS                                    0x41bb
#define mmCRTC4_CRTC_TEST_PATTERN_PARAMETERS                                    0x43bb
#define mmCRTC5_CRTC_TEST_PATTERN_PARAMETERS                                    0x45bb
#define mmCRTC_TEST_PATTERN_COLOR                                          