  0x4525
#define mmDC_PERFMON9_PERFCOUNTER_STATE                                         0x4725
#define mmDC_PERFMON10_PERFCOUNTER_STATE                                        0x59a1
#define mmDC_PERFMON11_PERFCOUNTER_STATE                                        0x5f69
#define mmPERFMON_CNTL                                                          0x173
#define mmDC_PERFMON0_PERFMON_CNTL                                              0x173
#define mmDC_PERFMON1_PERFMON_CNTL                                              0x367
#define mmDC_PERFMON2_PERFMON_CNTL                                              0x18cb
#define mmDC_PERFMON3_PERFMON_CNTL                                              0x1b27
#define mmDC_PERFMON4_PERFMON_CNTL                                              0x1d27
#define mmDC_PERFMON5_PERFMON_CNTL                                              0x1f27
#define mmDC_PERFMON6_PERFMON_CNTL                                              0x4127
#define mmDC_PERFMON7_PERFMON_CNTL                                              0x4327
#define mmDC_PERFMON8_PERFMON_CNTL                                              0x4527
#define mmDC_PERFMON9_PERFMON_CNTL                                              0x4727
#define mmDC_PERFMON10_PERFMON_CNTL                                             0x59a3
#define mmDC_PERFMON11_PERFMON_CNTL                                             0x5f6b
#define mmPERFMON_CNTL2                                                         0x17a
#define mmDC_PERFMON0_PERFMON_CNTL2                                             0x17a
#define mmDC_PERFMON1_PERFMON_CNTL2                                             0x36e
#define mmDC_PERFMON2_PERFMON_CNTL2                                             0x18d2
#define mmDC_PERFMON3_PERFMON_CNTL2                                             0x1b2e
#define mmDC_PERFMON4_PERFMON_CNTL2                                             0x1d2e
#define mmDC_PERFMON5_PERFMON_CNTL2                                             0x1f2e
#define mmDC_PERFMON6_PERFMON_CNTL2                                             0x412e
#define mmDC_PERFMON7_PERFMON_CNTL2                                             0x432e
#define mmDC_PERFMON8_PERFMON_CNTL2                                             0x452e
#define mmDC_PERFMON9_PERFMON_CNTL2                                             0x472e
#define mmDC_PERFMON10_PERFMON_CNTL2                                            0x59aa
#define mmDC_PERFMON11_PERFMON_CNTL2                                            0x5f72
#define mmPERFMON_CVALUE_INT_MISC                                               0x172
#define mmDC_PERFMON0_PERFMON_CVALUE_INT_MISC                                   0x172
#define mmDC_PERFMON1_PERFMON_CVALUE_INT_MISC                                   0x366
#define mmDC_PERFMON2_PERFMON_CVALUE_INT_MISC                                   0x18ca
#define mmDC_PERFMON3_PERFMON_CVALUE_INT_MISC                                   0x1b26
#define mmDC_PERFMON4_PERFMON_CVALUE_INT_MISC                                   0x1d26
#define mmDC_PERFMON5_PERFMON_CVALUE_INT_MISC                                   0x1f26
#define mmDC_PERFMON6_PERFMON_CVALUE_INT_MISC                                   0x4126
#define mmDC_PERFMON7_PERFMON_CVALUE_INT_MISC                                   0x4326
#define mmDC_PERFMON8_PERFMON_CVALUE_INT_MISC                                   0x4526
#define mmDC_PERFMON9_PERFMON_CVALUE_INT_MISC                                   0x4726
#define mmDC_PERFMON10_PERFMON_CVALUE_INT_MISC                                  0x59a2
#define mmDC_PERFMON11_PERFMON_CVALUE_INT_MISC                                  0x5f6a
#define mmPERFMON_CVALUE_LOW                                                    0x174
#define mmDC_PERFMON0_PERFMON_CVALUE_LOW                                        0x174
#define mmDC_PERFMON1_PERFMON_CVALUE_LOW                                        0x368
#define mmDC_PERFMON2_PERFMON_CVALUE_LOW                                        0x18cc
#define mmDC_PERFMON3_PERFMON_CVALUE_LOW                                        0x1b28
#define mmDC_PERFMON4_PERFMON_CVALUE_LOW                                        0x1d28
#define mmDC_PERFMON5_PERFMON_CVALUE_LOW                                        0x1f28
#define mmDC_PERFMON6_PERFMON_CVALUE_LOW                                        0x4128
#define mmDC_PERFMON7_PERFMON_CVALUE_LOW                                        0x4328
#define mmDC_PERFMON8_PERFMON_CVALUE_LOW                                        0x4528
#define mmDC_PERFMON9_PERFMON_CVALUE_LOW                                        0x4728
#define mmDC_PERFMON10_PERFMON_CVALUE_LOW                                       0x59a4
#define mmDC_PERFMON11_PERFMON_CVALUE_LOW                                       0x5f6c
#define mmPERFMON_HI                                                            0x175
#define mmDC_PERFMON0_PERFMON_HI                                                0x175
#define mmDC_PERFMON1_PERFMON_HI                                                0x369
#define mmDC_PERFMON2_PERFMON_HI                                                0x18cd
#define mmDC_PERFMON3_PERFMON_HI                                                0x1b29
#define mmDC_PERFMON4_PERFMON_HI                                                0x1d29
#define mmDC_PERFMON5_PERFMON_HI                                                0x1f29
#define mmDC_PERFMON6_PERFMON_HI                                                0x4129
#define mmDC_PERFMON7_PERFMON_HI                                                0x4329
#define mmDC_PERFMON8_PERFMON_HI                                                0x4529
#define mmDC_PERFMON9_PERFMON_HI                                                0x4729
#define mmDC_PERFMON10_PERFMON_HI                                               0x59a5
#define mmDC_PERFMON11_PERFMON_HI                                               0x5f6d
#define mmPERFMON_LOW                                                           0x176
#define mmDC_PERFMON0_PERFMON_LOW                                               0x176
#define mmDC_PERFMON1_PERFMON_LOW                                               0x36a
#define mmDC_PERFMON2_PERFMON_LOW                                               0x18ce
#define mmDC_PERFMON3_PERFMON_LOW                                               0x1b2a
#define mmDC_PERFMON4_PERFMON_LOW                                               0x1d2a
#define mmDC_PERFMON5_PERFMON_LOW                                               0x1f2a
#define mmDC_PERFMON6_PERFMON_LOW                                               0x412a
#define mmDC_PERFMON7_PERFMON_LOW                                               0x432a
#define mmDC_PERFMON8_PERFMON_LOW                                               0x452a
#define mmDC_PERFMON9_PERFMON_LOW                                               0x472a
#define mmDC_PERFMON10_PERFMON_LOW                                              0x59a6
#define mmDC_PERFMON11_PERFMON_LOW                                              0x5f6e
#define mmPERFMON_TEST_DEBUG_INDEX                                              0x177
#define mmDC_PERFMON0_PERFMON_TEST_DEBUG_INDEX                                  0x177
#define mmDC_PERFMON1_PERFMON_TEST_DEBUG_INDEX                                  0x36b
#define mmDC_PERFMON2_PERFMON_TEST_DEBUG_INDEX                                  0x18cf
#define mmDC_PERFMON3_PERFMON_TEST_DEBUG_INDEX                                  0x1b2b
#define mmDC_PERFMON4_PERFMON_TEST_DEBUG_INDEX                                  0x1d2b
#define mmDC_PERFMON5_PERFMON_TEST_DEBUG_INDEX                                  0x1f2b
#define mmDC_PERFMON6_PERFMON_TEST_DEBUG_INDEX                                  0x412b
#define mmDC_PERFMON7_PERFMON_TEST_DEBUG_INDEX                                  0x432b
#define mmDC_PERFMON8_PERFMON_TEST_DEBUG_INDEX                                  0x452b
#define mmDC_PERFMON9_PERFMON_TEST_DEBUG_INDEX                                  0x472b
#define mmDC_PERFMON10_PERFMON_TEST_DEBUG_INDEX                                 0x59a7
#define mmDC_PERFMON11_PERFMON_TEST_DEBUG_INDEX                                 0x5f6f
#define mmPERFMON_TEST_DEBUG_DATA                                               0x178
#define mmDC_PERFMON0_PERFMON_TEST_DEBUG_DATA                                   0x178
#define mmDC_PERFMON1_PERFMON_TEST_DEBUG_DATA                                   0x36c
#define mmDC_PERFMON2_PERFMON_TEST_DEBUG_DATA                                   0x18d0
#define mmDC_PERFMON3_PERFMON_TEST_DEBUG_DATA                                   0x1b2c
#define mmDC_PERFMON4_PERFMON_TEST_DEBUG_DATA                                   0x1d2c
#define mmDC_PERFMON5_PERFMON_TEST_DEBUG_DATA                                   0x1f2c
#define mmDC_PERFMON6_PERFMON_TEST_DEBUG_DATA                                   0x412c
#define mmDC_PERFMON7_PERFMON_TEST_DEBUG_DATA                                   0x432c
#define mmDC_PERFMON8_PERFMON_TEST_DEBUG_DATA                                   0x452c
#define mmDC_PERFMON9_PERFMON_TEST_DEBUG_DATA                                   0x472c
#define mmDC_PERFMON10_PERFMON_TEST_DEBUG_DATA                                  0x59a8
#define mmDC_PERFMON11_PERFMON_TEST_DEBUG_DATA                                  0x5f70
#define mmREFCLK_CNTL                                                           0x109
#define mmDCCG_CBUS_WRCMD_DELAY                                                 0x110
#define mmDPREFCLK_CNTL                                                         0x118
#define mmDCE_VERSION                                                           0x11e
#define mmAVSYNC_COUNTER_WRITE                                                  0x12a
#define mmAVSYNC_COUNTER_CONTROL                                                0x12b
#define mmAVSYNC_COUNTER_READ                                                   0x12f
#define mmDCCG_GTC_CNTL                                                         0x120
#define mmDCCG_GTC_DTO_INCR                                                     0x121
#define mmDCCG_GTC_DTO_MODULO                                                   0x122
#define mmDCCG_GTC_CURRENT                                                      0x123
#define mmDCCG_DS_DTO_INCR                                                      0x113
#define mmDCCG_DS_DTO_MODULO                                                    0x114
#define mmDCCG_DS_CNTL                                                          0x115
#define mmDCCG_DS_HW_CAL_INTERVAL                                               0x116
#define mmDCCG_DS_DEBUG_CNTL                                                    0x112
#define mmDMCU_SMU_INTERRUPT_CNTL                                               0x12c
#define mmSMU_CONTROL                                                           0x12d
#define mmSMU_INTERRUPT_CONTROL                                                 0x12e
#define mmDAC_CLK_ENABLE                                                        0x128
#define mmDVO_CLK_ENABLE                                                        0x129
#define mmDCCG_GATE_DISABLE_CNTL                                                0x134
#define mmDCCG_GATE_DISABLE_CNTL2                                               0x13c
#define mmDISPCLK_CGTT_BLK_CTRL_REG                                             0x135
#define mmSCLK_CGTT_BLK_CTRL_REG                                                0x136
#define mmDPREFCLK_CGTT_BLK_CTRL_REG                                            0x108
#define mmREFCLK_CGTT_BLK_CTRL_REG                                              0x10b
#define mmSYMCLK_CGTT_BLK_CTRL_REG                                              0x13d
#define mmDCCG_CAC_STATUS                                                       0x137
#define mmPIXCLK1_RESYNC_CNTL                                                   0x138
#define mmPIXCLK2_RESYNC_CNTL                                                   0x139
#define mmPIXCLK0_RESYNC_CNTL                                                   0x13a
#define mmPHYPLL_PIXCLK_CNTL                                                    0x13e
#define mmMICROSECOND_TIME_BASE_DIV                                             0x13b
#define mmDCCG_DISP_CNTL_REG                                                    0x13f
#define mmMILLISECOND_TIME_BASE_DIV                                             0x130
#define mmDISPCLK_FREQ_CHANGE_CNTL                                              0x131
#define mmDC_MEM_GLOBAL_PWR_REQ_CNTL                                            0x132
#define mmDCCG_PERFMON_CNTL                                                     0x133
#define mmDCCG_PERFMON_CNTL2                                                    0x10e
#define mmCRTC0_PIXEL_RATE_CNTL                                                 0x140
#define mmDP_DTO0_PHASE                                                         0x141
#define mmDP_DTO0_MODULO                                                        0x142
#define mmCRTC1_PIXEL_RATE_CNTL                                                 0x144
#define mmDP_DTO1_PHASE                                                         0x145
#define mmDP_DTO1_MODULO                                                        0x146
#define mmCRTC2_PIXEL_RATE_CNTL                                                 0x148
#define mmDP_DTO2_PHASE                                                         0x149
#define mmDP_DTO2_MODULO                                                        0x14a
#define mmCRTC3_PIXEL_RATE_CNTL                                                 0x14c
#define mmDP_DTO3_PHASE                                                         0x14d
#define mmDP_DTO3_MODULO                                                        0x14e
#define mmCRTC4_PIXEL_RATE_CNTL                                                 0x150
#define mmDP_DTO4_PHASE                                                         0x151
#define mmDP_DTO4_MODULO                                                        0x152
#define mmCRTC5_PIXEL_RATE_CNTL                                                 0x154
#define mmDP_DTO5_PHASE                                                         0x155
#define mmDP_DTO5_MODULO                                                        0x156
#define mmDCFEV0_CRTC_PIXEL_RATE_CNTL                                           0x104
#define mmDCCG_SOFT_RESET                                                       0x15f
#define mmSYMCLKA_CLOCK_ENABLE                                                  0x160
#define mmSYMCLKB_CLOCK_ENABLE                                                  0x161
#define mmSYMCLKC_CLOCK_ENABLE                                                  0x162
#define mmSYMCLKD_CLOCK_ENABLE                                                  0x163
#define mmSYMCLKE_CLOCK_ENABLE                                                  0x164
#define mmSYMCLKF_CLOCK_ENABLE                                                  0x165
#define mmSYMCLKG_CLOCK_ENABLE                                                  0x117
#define mmDPDBG_CLK_FORCE_CONTROL                                               0x10d
#define mmDCCG_AUDIO_DTO_SOURCE                                                 0x16b
#define mmDCCG_AUDIO_DTO0_PHASE                                                 0x16c
#define mmDCCG_AUDIO_DTO0_MODULE                                                0x16d
#define mmDCCG_AUDIO_DTO1_PHASE                                                 0x16e
#define mmDCCG_AUDIO_DTO1_MODULE                                                0x16f
#define mmDCCG_TEST_DEBUG_INDEX                                                 0x17c
#define mmDCCG_TEST_DEBUG_DATA                                                  0x17d
#define mmDCCG_TEST_CLK_SEL                                                     0x17e
#define mmCPLL_MACRO_CNTL_RESERVED0                                             0x5fd0
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED0                                  0x5fd0
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED0                                  0x5fdc
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED0                                  0x5fe8
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED0                                  0x5ff4
#define mmCPLL_MACRO_CNTL_RESERVED1                                             0x5fd1
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED1                                  0x5fd1
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED1                                  0x5fdd
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED1                                  0x5fe9
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED1                                  0x5ff5
#define mmCPLL_MACRO_CNTL_RESERVED2                                             0x5fd2
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED2                                  0x5fd2
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED2                                  0x5fde
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED2                                  0x5fea
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED2                                  0x5ff6
#define mmCPLL_MACRO_CNTL_RESERVED3                                             0x5fd3
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED3                                  0x5fd3
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED3                                  0x5fdf
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED3                                  0x5feb
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED3                                  0x5ff7
#define mmCPLL_MACRO_CNTL_RESERVED4                                             0x5fd4
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED4                                  0x5fd4
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED4                                  0x5fe0
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED4                                  0x5fec
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED4                                  0x5ff8
#define mmCPLL_MACRO_CNTL_RESERVED5                                             0x5fd5
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED5                                  0x5fd5
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED5                                  0x5fe1
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED5                                  0x5fed
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED5                                  0x5ff9
#define mmCPLL_MACRO_CNTL_RESERVED6                                             0x5fd6
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED6                                  0x5fd6
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED6                                  0x5fe2
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED6                                  0x5fee
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED6                                  0x5ffa
#define mmCPLL_MACRO_CNTL_RESERVED7                                             0x5fd7
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED7                                  0x5fd7
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED7                                  0x5fe3
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED7                                  0x5fef
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED7                                  0x5ffb
#define mmCPLL_MACRO_CNTL_RESERVED8                                             0x5fd8
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED8                                  0x5fd8
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED8                                  0x5fe4
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED8                                  0x5ff0
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED8                                  0x5ffc
#define mmCPLL_MACRO_CNTL_RESERVED9                                             0x5fd9
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED9                                  0x5fd9
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED9                                  0x5fe5
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED9                                  0x5ff1
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED9                                  0x5ffd
#define mmCPLL_MACRO_CNTL_RESERVED10                                            0x5fda
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED10                                 0x5fda
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED10                                 0x5fe6
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED10                                 0x5ff2
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED10                                 0x5ffe
#define mmCPLL_MACRO_CNTL_RESERVED11                                            0x5fdb
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED11                                 0x5fdb
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED11                                 0x5fe7
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED11                                 0x5ff3
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED11                                 0x5fff
#define mmPLL_MACRO_CNTL_RESERVED0                                              0x1700
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED0                                    0x1700
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED0                                    0x172a
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED0                                    0x1754
#define mmPLL_MACRO_CNTL_RESERVED1                                              0x1701
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED1                                    0x1701
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED1                                    0x172b
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED1                                    0x1755
#define mmPLL_MACRO_CNTL_RESERVED2                                              0x1702
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED2                                    0x1702
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED2                                    0x172c
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED2                                    0x1756
#define mmPLL_MACRO_CNTL_RESERVED3                                              0x1703
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED3                                    0x1703
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED3                                    0x172d
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED3                                    0x1757
#define mmPLL_MACRO_CNTL_RESERVED4                                              0x1704
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED4                                    0x1704
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED4                                    0x172e
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED4                                    0x1758
#define mmPLL_MACRO_CNTL_RESERVED5                                              0x1705
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED5                                    0x1705
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED5                                    0x172f
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED5                                    0x1759
#define mmPLL_MACRO_CNTL_RESERVED6                                              0x1706
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED6                                    0x1706
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED6                                    0x1730
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED6                                    0x175a
#define mmPLL_MACRO_CNTL_RESERVED7                                              0x1707
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED7                                    0x1707
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED7                                    0x1731
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED7                                    0x175b
#define mmPLL_MACRO_CNTL_RESERVED8                                              0x1708
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED8                                    0x1708
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED8                                    0x1732
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED8                                    0x175c
#define mmPLL_MACRO_CNTL_RESERVED9                                              0x1709
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED9                                    0x1709
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED9                                    0x1733
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED9                                    0x175d
#define mmPLL_MACRO_CNTL_RESERVED10                                             0x170a
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED10                                   0x170a
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED10                                   0x1734
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED10                                   0x175e
#define mmPLL_MACRO_CNTL_RESERVED11                                             0x170b
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED11                                   0x170b
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED11                                   0x1735
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED11                                   0x175f
#define mmPLL_MACRO_CNTL_RESERVED12                                             0x170c
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED12                                   0x170c
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED12                                   0x1736
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED12                                   0x1760
#define mmPLL_MACRO_CNTL_RESERVED13                                             0x170d
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED13                                   0x170d
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED13                                   0x1737
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED13                                   0x1761
#define mmPLL_MACRO_CNTL_RESERVED14                                             0x170e
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED14                                   0x170e
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED14                                   0x1738
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED14                                   0x1762
#define mmPLL_MACRO_CNTL_RESERVED15                                             0x170f
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED15                                   0x170f
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED15                                   0x1739
#defi