ST_PATTERN_COLOR                                         0x45bc
#define mmCRTC_MASTER_UPDATE_LOCK                                               0x1bbd
#define mmCRTC0_CRTC_MASTER_UPDATE_LOCK                                         0x1bbd
#define mmCRTC1_CRTC_MASTER_UPDATE_LOCK                                         0x1dbd
#define mmCRTC2_CRTC_MASTER_UPDATE_LOCK                                         0x1fbd
#define mmCRTC3_CRTC_MASTER_UPDATE_LOCK                                         0x41bd
#define mmCRTC4_CRTC_MASTER_UPDATE_LOCK                                         0x43bd
#define mmCRTC5_CRTC_MASTER_UPDATE_LOCK                                         0x45bd
#define mmCRTC_MASTER_UPDATE_MODE                                               0x1bbe
#define mmCRTC0_CRTC_MASTER_UPDATE_MODE                                         0x1bbe
#define mmCRTC1_CRTC_MASTER_UPDATE_MODE                                         0x1dbe
#define mmCRTC2_CRTC_MASTER_UPDATE_MODE                                         0x1fbe
#define mmCRTC3_CRTC_MASTER_UPDATE_MODE                                         0x41be
#define mmCRTC4_CRTC_MASTER_UPDATE_MODE               