f000000
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_contents__SHIFT 0x18
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_full_MASK 0x20000000
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_full__SHIFT 0x1d
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_advanceread_MASK 0x40000000
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_advanceread__SHIFT 0x1e
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_write_MASK 0x80000000
#define CLIPPER_DEBUG_REG13__outsm_clr_fifo_write__SHIFT 0x1f
#define CLIPPER_DEBUG_REG14__clprim_in_back_vertex_store_indx_2_MASK 0x3f
#define CLIPPER_DEBUG_REG14__clprim_in_back_vertex_store_indx_2__SHIFT 0x0
#define CLIPPER_DEBUG_REG14__clprim_in_back_vertex_store_indx_1_MASK 0xfc0
#define CLIPPER_DEBUG_REG14__clprim_in_back_vertex_store_indx_1__SHI