                                                  0x200001d
#define ixD2F1_ROOT_STATUS                                                      0x200001e
#define ixD2F1_DEVICE_CAP2                                                      0x200001f
#define ixD2F1_DEVICE_CNTL2                                                     0x2000020
#define ixD2F1_DEVICE_STATUS2                                                   0x2000020
#define ixD2F1_LINK_CAP2                                                        0x2000021
#define ixD2F1_LINK_CNTL2                                                       0x2000022
#define ixD2F1_LINK_STATUS2                                                     0x2000022
#define ixD2F1_SLOT_CAP2                                                        0x2000023
#define ixD2F1_SLOT_CNTL2                                                       0x2000024
#define ixD2F1_SLOT_STATUS2                                                     0x2000024
#define ixD2F1_MSI_CAP_LIST                                                     0x2000028
#define ixD2F1_MSI_MSG_CNTL                                                     0x2000028
#define ixD2F1_MSI_MSG_ADDR_LO                                                  0x2000029
#define ixD2F1_MSI_MSG_ADDR_HI                                                  0x200002a
#define ixD2F1_MSI_MSG_DATA_64                                                  0x200002b
#define ixD2F1_MSI_MSG_DATA                                                     0x200002a
#define ixD2F1_SSID_CAP_LIST                                                    0x2000030
#define ixD2F1_SSID_CAP                                                         0x2000031
#define ixD2F1_MSI_MAP_CAP_LIST                                                 0x2000032
#define ixD2F1_MSI_MAP_CAP                                                      0x2000032
#define ixD2F1_MSI_MAP_ADDR_LO                                                  0x2000033
#define ixD2F1_MSI_MAP_ADDR_HI                                                  0x2000034
#define ixD2F1_PCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                0x2000040
#define ixD2F1_PCIE_VENDOR_SPECIFIC_HDR                                         0x2000041
#define ixD2F1_PCIE_VENDOR_SPECIFIC1                                            0x2000042
#define ixD2F1_PCIE_VENDOR_SPECIFIC2                                            0x2000043
#define ixD2F1_PCIE_VC_ENH_CAP_LIST                                             0x2000044
#define ixD2F1_PCIE_PORT_VC_CAP_REG1                                            0x2000045
#define ixD2F1_PCIE_PORT_VC_CAP_REG2                                            0x2000046
#define ixD2F1_PCIE_PORT_VC_CNTL                                                0x2000047
#define ixD2F1_PCIE_PORT_VC_STATUS                                              0x2000047
#define ixD2F1_PCIE_VC0_RESOURCE_CAP                                            0x2000048
#define ixD2F1_PCIE_VC0_RESOURCE_CNTL                                           0x2000049
#define ixD2F1_PCIE_VC0_RESOURCE_STATUS                                         0x200004a
#define ixD2F1_PCIE_VC1_RESOURCE_CAP                                            0x200004b
#define ixD2F1_PCIE_VC1_RESOURCE_CNTL                                           0x200004c
#define ixD2F1_PCIE_VC1_RESOURCE_STATUS                                         0x200004d
#define ixD2F1_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0x2000050
#define ixD2F1_PCIE_DEV_SERIAL_NUM_DW1                                          0x2000051
#define ixD2F1_PCIE_DEV_SERIAL_NUM_DW2                                          0x2000052
#define ixD2F1_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0x2000054
#define ixD2F1_PCIE_UNCORR_ERR_STATUS                                           0x2000055
#define ixD2F1_PCIE_UNCORR_ERR_MASK                                             0x2000056
#define ixD2F1_PCIE_UNCORR_ERR_SEVERITY                                         0x2000057
#define ixD2F1_PCIE_CORR_ERR_STATUS                                             0x2000058
#define ixD2F1_PCIE_CORR_ERR_MASK                                               0x2000059
#define ixD2F1_PCIE_ADV_ERR_CAP_CNTL                                            0x200005a
#define ixD2F1_PCIE_HDR_LOG0                                                    0x200005b
#define ixD2F1_PCIE_HDR_LOG1                                                    0x200005c
#define ixD2F1_PCIE_HDR_LOG2                                                    0x200005d
#define ixD2F1_PCIE_HDR_LOG3                                                    0x200005e
#define ixD2F1_PCIE_ROOT_ERR_CMD                                                0x200005f
#define ixD2F1_PCIE_ROOT_ERR_STATUS                                             0x2000060
#define ixD2F1_PCIE_ERR_SRC_ID                                                  0x2000061
#define ixD2F1_PCIE_TLP_PREFIX_LOG0                                             0x2000062
#define ixD2F1_PCIE_TLP_PREFIX_LOG1                                             0x2000063
#define ixD2F1_PCIE_TLP_PREFIX_LOG2                                             0x2000064
#define ixD2F1_PCIE_TLP_PREFIX_LOG3                                             0x2000065
#define ixD2F1_PCIE_SECONDARY_ENH_CAP_LIST                                      0x200009c
#define ixD2F1_PCIE_LINK_CNTL3                                                  0x200009d
#define ixD2F1_PCIE_LANE_ERROR_STATUS                                           0x200009e
#define ixD2F1_PCIE_LANE_0_EQUALIZATION_CNTL                                    0x200009f
#define ixD2F1_PCIE_LANE_1_EQUALIZATION_CNTL                                    0x200009f
#define ixD2F1_PCIE_LANE_2_EQUALIZATION_CNTL                                    0x20000a0
#define ixD2F1_PCIE_LANE_3_EQUALIZATION_CNTL                                    0x20000a0
#define ixD2F1_PCIE_LANE_4_EQUALIZATION_CNTL                                    0x20000a1
#define ixD2F1_PCIE_LANE_5_EQUALIZATION_CNTL                                    0x20000a1
#define ixD2F1_PCIE_LANE_6_EQUALIZATION_CNTL                                    0x20000a2
#define ixD2F1_PCIE_LANE_7_EQUALIZATION_CNTL                                    0x20000a2
#define ixD2F1_PCIE_LANE_8_EQUALIZATION_CNTL                                    0x20000a3
#define ixD2F1_PCIE_LANE_9_EQUALIZATION_CNTL                                    0x20000a3
#define ixD2F1_PCIE_LANE_10_EQUALIZATION_CNTL                                   0x20000a4
#define ixD2F1_PCIE_LANE_11_EQUALIZATION_CNTL                                   0x20000a4
#define ixD2F1_PCIE_LANE_12_EQUALIZATION_CNTL                                   0x20000a5
#define ixD2F1_PCIE_LANE_13_EQUALIZATION_CNTL                                   0x20000a5
#define ixD2F1_PCIE_LANE_14_EQUALIZATION_CNTL                                   0x20000a6
#define ixD2F1_PCIE_LANE_15_EQUALIZATION_CNTL                                   0x20000a6
#define ixD2F1_PCIE_ACS_ENH_CAP_LIST                                            0x20000a8
#define ixD2F1_PCIE_ACS_CAP                                                     0x20000a9
#define ixD2F1_PCIE_ACS_CNTL                                                    0x20000a9
#define ixD2F1_PCIE_MC_ENH_CAP_LIST                                             0x20000bc
#define ixD2F1_PCIE_MC_CAP                                                      0x20000bd
#define ixD2F1_PCIE_MC_CNTL                                                     0x20000bd
#define ixD2F1_PCIE_MC_ADDR0                                                    0x20000be
#define ixD2F1_PCIE_MC_ADDR1                                                    0x20000bf
#define ixD2F1_PCIE_MC_RCV0                                                     0x20000c0
#define ixD2F1_PCIE_MC_RCV1                                                     0x20000c1
#define ixD2F1_PCIE_MC_BLOCK_ALL0                                               0x20000c2
#define ixD2F1_PCIE_MC_BLOCK_ALL1                                               0x20000c3
#define ixD2F1_PCIE_MC_BLOCK_UNTRANSLATED_0                                     0x20000c4
#define ixD2F1_PCIE_MC_BLOCK_UNTRANSLATED_1                                     0x20000c5
#define ixD2F1_PCIE_MC_OVERLAY_BAR0                                             0x20000c6
#define ixD2F1_PCIE_MC_OVERLAY_BAR1                                             0x20000c7
#define ixD2F2_PCIE_PORT_INDEX                                                  0x3000038
#define ixD2F2_PCIE_PORT_DATA                                                   0x3000039
#define ixD2F2_PCIEP_RESERVED                                                   0x0
#define ixD2F2_PCIEP_SCRATCH                                                    0x1
#define ixD2F2_PCIEP_HW_DEBUG                                                   0x2
#define ixD2F2_PCIEP_PORT_CNTL                                                  0x10
#define ixD2F2_PCIE_TX_CNTL                                                     0x20
#define ixD2F2_PCIE_TX_REQUESTER_ID                                             0x21
#define ixD2F2_PCIE_TX_VENDOR_SPECIFIC                                          0x22
#define ixD2F2_PCIE_TX_REQUEST_NUM_CNTL                                         0x23
#define ixD2F2_PCIE_TX_SEQ                                                      0x24
#define ixD2F2_PCIE_TX_REPLAY                                                   0x25
#define ixD2F2_PCIE_TX_ACK_LATENCY_LIMIT                                        0x26
#define ixD2F2_PCIE_TX_CREDITS_ADVT_P                                           0x30
#define ixD2F2_PCIE_TX_CREDITS_ADVT_NP                                          0x31
#define ixD2F2_PCIE_TX_CREDITS_ADVT_CPL                                         0x32
#define ixD2F2_PCIE_TX_CREDITS_INIT_P                                           0x33
#define ixD2F2_PCIE_TX_CREDITS_INIT_NP                                          0x34
#define ixD2F2_PCIE_TX_CREDITS_INIT_CPL                                         0x35
#define ixD2F2_PCIE_TX_CREDITS_STATUS                                           0x36
#define ixD2F2_PCIE_TX_CREDITS_FCU_THRESHOLD                                    0x37
#define ixD2F2_PCIE_P_PORT_LANE_STATUS                                          0x50
#define ixD2F2_PCIE_FC_P                                                        0x60
#define ixD2F2_PCIE_FC_NP                                                       0x61
#define ixD2F2_PCIE_FC_CPL                                                      0x62
#define ixD2F2_PCIE_ERR_CNTL                                                    0x6a
#define ixD2F2_PCIE_RX_CNTL                                                     0x70
#define ixD2F2_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD2F2_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD2F2_PCIE_RX_CNTL3                                                    0x74
#define ixD2F2_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD2F2_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD2F2_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD2F2_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD2F2_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD2F2_PCIE_LC_CNTL                                                     0xa0
#define ixD2F2_PCIE_LC_CNTL2                                                    0xb1
#define ixD2F2_PCIE_LC_CNTL3                                                    0xb5
#define ixD2F2_PCIE_LC_CNTL4                                                    0xb6
#define ixD2F2_PCIE_LC_CNTL5                                                    0xb7
#define ixD2F2_PCIE_LC_CNTL6                                                    0xbb
#define ixD2F2_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD2F2_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD2F2_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD2F2_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD2F2_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD2F2_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD2F2_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD2F2_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD2F2_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD2F2_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD2F2_PCIE_LC_STATE0                                                   0xa5
#define ixD2F2_PCIE_LC_STATE1                                                   0xa6
#define ixD2F2_PCIE_LC_STATE2                                                   0xa7
#define ixD2F2_PCIE_LC_STATE3                                                   0xa8
#define ixD2F2_PCIE_LC_STATE4                                                   0xa9
#define ixD2F2_PCIE_LC_STATE5                                                   0xaa
#define ixD2F2_PCIEP_STRAP_LC                                                   0xc0
#define ixD2F2_PCIEP_STRAP_MISC                                                 0xc1
#define ixD2F2_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD2F2_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD2F2_PCIEP_HPGI                                                       0xda
#define ixD2F2_VENDOR_ID                                                        0x3000000
#define ixD2F2_DEVICE_ID                                                        0x3000000
#define ixD2F2_COMMAND                                                          0x3000001
#define ixD2F2_STATUS                                                           0x3000001
#define ixD2F2_REVISION_ID                                                      0x3000002
#define ixD2F2_PROG_INTERFACE                                                   0x3000002
#define ixD2F2_SUB_CLASS                                                        0x3000002
#define ixD2F2_BASE_CLASS                                                       0x3000002
#define ixD2F2_CACHE_LINE                                                       0x3000003
#define ixD2F2_LATENCY                                                          0x3000003
#define ixD2F2_HEADER                                                           0x3000003
#define ixD2F2_BIST                                                             0x3000003
#define ixD2F2_SUB_BUS_NUMBER_LATENCY                                           0x3000006
#define ixD2F2_IO_BASE_LIMIT                                                    0x3000007
#define ixD2F2_SECONDARY_STATUS                                                 0x3000007
#define ixD2F2_MEM_BASE_LIMIT                                                   0x3000008
#define ixD2F2_PREF_BASE_LIMIT                                                  0x3000009
#define ixD2F2_PREF_BASE_UPPER                                                  0x300000a
#define ixD2F2_PREF_LIMIT_UPPER                                                 0x300000b
#define ixD2F2_IO_BASE_LIMIT_HI                                                 0x300000c
#define ixD2F2_IRQ_BRIDGE_CNTL                                                  0x300000f
#define ixD2F2_CAP_PTR                                                          0x300000d
#define ixD2F2_INTERRUPT_LINE                                                   0x300000f
#define ixD2F2_INTERRUPT_PIN                                                    0x300000f
#define ixD2F2_EXT_BRIDGE_CNTL                                                  0x3000010
#define ixD2F2_PMI_CAP_LIST                                                     0x3000014
#define ixD2F2_PMI_CAP                                                          0x3000014
#define ixD2F2_PMI_STATUS_CNTL                                                  0x3000015
#define ixD2F2_PCIE_CAP_LIST                                                    0x3000016
#define ixD2F2_PCIE_CAP                                                         0x3000016
#define ixD2F2_DEVICE_CAP                                                       0x3000017
#define ixD2F2_DEVICE_CNTL                                                      0x3000018
#define ixD2F2_DEVICE_STATUS                                                    0x3000018
#define ixD2F2_LINK_CAP                                                         0x3000019
#define ixD2F2_LINK_CNTL                                                        0x300001a
#define ixD2F2_LINK_STATUS                                                      0x300001a
#define ixD2F2_SLOT_CAP                                                         0x300001b
#define ixD2F2_SLOT_CNTL                                                        0x300001c
#define ixD2F2_SLOT_STATUS                                                      0x300001c
#define ixD2F2_ROOT_CNTL                                                        0x300001d
#define ixD2F2_ROOT_CAP                                                         0x300001d
#define ixD2F2_ROOT_STATUS                                                      0x300001e
#define ixD2F2_DEVICE_CAP2                                                      0x300001f
#define ixD2F2_DEVICE_CNTL2                                                     0x3000020
#define ixD2F2_DEVICE_STATUS2                                                   0x3000020
#define ixD2F2_LINK_CAP2                                                        0x3000021
#define ixD2F2_LINK_CNTL2                                                       0x300