_RESOURCE_CAP                                            0x300004b
#define ixD2F2_PCIE_VC1_RESOURCE_CNTL                                           0x300004c
#define ixD2F2_PCIE_VC1_RESOURCE_STATUS                                         0x300004d
#define ixD2F2_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0x3000050
#define ixD2F2_PCIE_DEV_SERIAL_NUM_DW1                                          0x3000051
#define ixD2F2_PCIE_DEV_SERIAL_NUM_DW2                                          0x3000052
#define ixD2F2_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0x3000054
#define ixD2F2_PCIE_UNCORR_ERR_STATUS                                           0x3000055
#define ixD2F2_PCIE_UNCORR_ERR_MASK                                             0x3000056
#define ixD2F2_PCIE_UNCORR_ERR_SEVERITY                                         0x3000057
#define ixD2F2_PCIE_CORR_ERR_STATUS                                             0x3000058
#define ixD2F2_PCIE_CORR_ERR_MASK                                               0x3000059
#define ixD2F2_PCIE_ADV_ERR_CAP_CNTL                                            0x300005a
#define ixD2F2_PCIE_HDR_LOG0                                                    0x300005b
#define ixD2F2_PCIE_HDR_LOG1                                                    0x300005c
#define ixD2F2_PCIE_HDR_LOG2                                                    0x300005d
#define ixD2F2_PCIE_HDR_LOG3                                                    0x300005e
#define ixD2F2_PCIE_ROOT_ERR_CMD                                                0x300005f
#define ixD2F2_PCIE_ROOT_ERR_STATUS                                             0x3000060
#define ixD2F2_PCIE_ERR_SRC_ID                                                  0x3000061
#define ixD2F2_PCIE_TLP_PREFIX_LOG0                                             0x3000062
#define ixD2F2_PCIE_TLP_PREFIX_LOG1                                             0x3000063
#define ixD2F2_PCIE_TLP_PREFIX_LOG2                                             0x3000064
#define ixD2F2_PCIE_TLP_PREFIX_LOG3                                             0x3000065
#define ixD2F2_PCIE_SECONDARY_ENH_CAP_LIST                                      0x300009c
#define ixD2F2_PCIE_LINK_CNTL3                                                  0x300009d
#define ixD2F2_PCIE_LANE_ERROR_STATUS                                           0x300009e
#define ixD2F2_PCIE_LANE_0_EQUALIZATION_CNTL                                    0x300009f
#define ixD2F2_PCIE_LANE_1_EQUALIZATION_CNTL                                    0x300009f
#define ixD2F2_PCIE_LANE_2_EQUALIZATION_CNTL                                    0x30000a0
#define ixD2F2_PCIE_LANE_3_EQUALIZATION_CNTL                                    0x30000a0
#define ixD2F2_PCIE_LANE_4_EQUALIZATION_CNTL                                    0x30000a1
#define ixD2F2_PCIE_LANE_5_EQUALIZATION_CNTL                                    0x30000a1
#define ixD2F2_PCIE_LANE_6_EQUALIZATION_CNTL                                    0x30000a2
#define ixD2F2_PCIE_LANE_7_EQUALIZATION_CNTL                                    0x30000a2
#define ixD2F2_PCIE_LANE_8_EQUALIZATION_CNTL                                    0x30000a3
#define ixD2F2_PCIE_LANE_9_EQUALIZATION_CNTL                                    0x30000a3
#define ixD2F2_PCIE_LANE_10_EQUALIZATION_CNTL                                   0x30000a4
#define ixD2F2_PCIE_LANE_11_EQUALIZATION_CNTL                                   0x30000a4
#define ixD2F2_PCIE_LANE_12_EQUALIZATION_CNTL                                   0x30000a5
#define ixD2F2_PCIE_LANE_13_EQUALIZATION_CNTL                                   0x30000a5
#define ixD2F2_PCIE_LANE_14_EQUALIZATION_CNTL                                   0x30000a6
#define ixD2F2_PCIE_LANE_15_EQUALIZATION_CNTL                                   0x30000a6
#define ixD2F2_PCIE_ACS_ENH_CAP_LIST                                            0x30000a8
#define ixD2F2_PCIE_ACS_CAP                                                     0x30000a9
#define ixD2F2_PCIE_ACS_CNTL                                                    0x30000a9
#define ixD2F2_PCIE_MC_ENH_CAP_LIST                                             0x30000bc
#define ixD2F2_PCIE_MC_CAP                                                      0x30000bd
#define ixD2F2_PCIE_MC_CNTL                                                     0x30000bd
#define ixD2F2_PCIE_MC_ADDR0                                                    0x30000be
#define ixD2F2_PCIE_MC_ADDR1                                                    0x30000bf
#define ixD2F2_PCIE_MC_RCV0                                                     0x30000c0
#define ixD2F2_PCIE_MC_RCV1                                                     0x30000c1
#define ixD2F2_PCIE_MC_BLOCK_ALL0                                               0x30000c2
#define ixD2F2_PCIE_MC_BLOCK_ALL1                                               0x30000c3
#define ixD2F2_PCIE_MC_BLOCK_UNTRANSLATED_0                                     0x30000c4
#define ixD2F2_PCIE_MC_BLOCK_UNTRANSLATED_1                                     0x30000c5
#define ixD2F2_PCIE_MC_OVERLAY_BAR0                                             0x30000c6
#define ixD2F2_PCIE_MC_OVERLAY_BAR1                                             0x30000c7
#define ixD2F3_PCIE_PORT_INDEX                                                  0x4000038
#define ixD2F3_PCIE_PORT_DATA                                                   0x4000039
#define ixD2F3_PCIEP_RESERVED                                                   0x0
#define ixD2F3_PCIEP_SCRATCH                                                    0x1
#define ixD2F3_PCIEP_HW_DEBUG                                                   0x2
#define ixD2F3_PCIEP_PORT_CNTL                                                  0x10
#define ixD2F3_PCIE_TX_CNTL                                                     0x20
#define ixD2F3_PCIE_TX_REQUESTER_ID                                             0x21
#define ixD2F3_PCIE_TX_VENDOR_SPECIFIC                                          0x22
#define ixD2F3_PCIE_TX_REQUEST_NUM_CNTL                                         0x23
#define ixD2F3_PCIE_TX_SEQ                                                      0x24
#define ixD2F3_PCIE_TX_REPLAY                                                   0x25
#define ixD2F3_PCIE_TX_ACK_LATENCY_LIMIT                                        0x26
#define ixD2F3_PCIE_TX_CREDITS_ADVT_P                                           0x30
#define ixD2F3_PCIE_TX_CREDITS_ADVT_NP                                          0x31
#define ixD2F3_PCIE_TX_CREDITS_ADVT_CPL                                         0x32
#define ixD2F3_PCIE_TX_CREDITS_INIT_P                                           0x33
#define ixD2F3_PCIE_TX_CREDITS_INIT_NP                                          0x34
#define ixD2F3_PCIE_TX_CREDITS_INIT_CPL                                         0x35
#define ixD2F3_PCIE_TX_CREDITS_STATUS                                           0x36
#define ixD2F3_PCIE_TX_CREDITS_FCU_THRESHOLD                                    0x37
#define ixD2F3_PCIE_P_PORT_LANE_STATUS                                          0x50
#define ixD2F3_PCIE_FC_P                                                        0x60
#define ixD2F3_PCIE_FC_NP                                                       0x61
#define ixD2F3_PCIE_FC_CPL                                                      0x62
#define ixD2F3_PCIE_ERR_CNTL                                                    0x6a
#define ixD2F3_PCIE_RX_CNTL                                                     0x70
#define ixD2F3_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD2F3_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD2F3_PCIE_RX_CNTL3                                                    0x74
#define ixD2F3_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD2F3_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD2F3_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD2F3_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD2F3_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD2F3_PCIE_LC_CNTL                                                     0xa0
#define ixD2F3_PCIE_LC_CNTL2                                                    0xb1
#define ixD2F3_PCIE_LC_CNTL3                                                    0xb5
#define ixD2F3_PCIE_LC_CNTL4                                                    0xb6
#define ixD2F3_PCIE_LC_CNTL5                                                    0xb7
#define ixD2F3_PCIE_LC_CNTL6                                                    0xbb
#define ixD2F3_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD2F3_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD2F3_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD2F3_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD2F3_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD2F3_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD2F3_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD2F3_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD2F3_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD2F3_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD2F3_PCIE_LC_STATE0                                                   0xa5
#define ixD2F3_PCIE_LC_STATE1                                                   0xa6
#define ixD2F3_PCIE_LC_STATE2                                                   0xa7
#define ixD2F3_PCIE_LC_STATE3                                                   0xa8
#define ixD2F3_PCIE_LC_STATE4                                                   0xa9
#define ixD2F3_PCIE_LC_STATE5                                                   0xaa
#define ixD2F3_PCIEP_STRAP_LC                                                   0xc0
#define ixD2F3_PCIEP_STRAP_MISC                                                 0xc1
#define ixD2F3_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD2F3_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD2F3_PCIEP_HPGI                                                       0xda
#define ixD2F3_VENDOR_ID                                                        0x4000000
#define ixD2F3_DEVICE_ID                                                        0x4000000
#define ixD2F3_COMMAND                                                          0x4000001
#define ixD2F3_STATUS                                                           0x4000001
#define ixD2F3_REVISION_ID                                                      0x4000002
#define ixD2F3_PROG_INTERFACE                                                   0x4000002
#define ixD2F3_SUB_CLASS                                                        0x4000002
#define ixD2F3_BASE_CLASS                                                       0x4000002
#define ixD2F3_CACHE_LINE                                                       0x4000003
#define ixD2F3_LATENCY                                                          0x4000003
#define ixD2F3_HEADER                                                           0x4000003
#define ixD2F3_BIST                                                             0x4000003
#define ixD2F3_SUB_BUS_NUMBER_LATENCY                                           0x4000006
#define ixD2F3_IO_BASE_LIMIT                                                    0x4000007
#define ixD2F3_SECONDARY_STATUS                                                 0x4000007
#define ixD2F3_MEM_BASE_LIMIT                                                   0x4000008
#define ixD2F3_PREF_BASE_LIMIT                                                  0x4000009
#define ixD2F3_PREF_BASE_UPPER                                                  0x400000a
#define ixD2F3_PREF_LIMIT_UPPER                                                 0x400000b
#define ixD2F3_IO_BASE_LIMIT_HI                                                 0x400000c
#define ixD2F3_IRQ_BRIDGE_CNTL                                                  0x400000f
#define ixD2F3_CAP_PTR                                                          0x400000d
#define ixD2F3_INTERRUPT_LINE                                                   0x400000f
#define ixD2F3_INTERRUPT_PIN                                                    0x400000f
#define ixD2F3_EXT_BRIDGE_CNTL                                                  0x4000010
#define ixD2F3_PMI_CAP_LIST                                                     0x4000014
#define ixD2F3_PMI_CAP                                                          0x4000014
#define ixD2F3_PMI_STATUS_CNTL                                                  0x4000015
#define ixD2F3_PCIE_CAP_LIST                                                    0x4000016
#define ixD2F3_PCIE_CAP                                                         0x4000016
#define ixD2F3_DEVICE_CAP                                                       0x4000017
#define ixD2F3_DEVICE_CNTL                                                      0x4000018
#define ixD2F3_DEVICE_STATUS                                                    0x4000018
#define ixD2F3_LINK_CAP                                                         0x4000019
#define ixD2F3_LINK_CNTL                                                        0x400001a
#define ixD2F3_LINK_STATUS                                                      0x400001a
#define ixD2F3_SLOT_CAP                                                         0x400001b
#define ixD2F3_SLOT_CNTL                                                        0x400001c
#define ixD2F3_SLOT_STATUS                                                      0x400001c
#define ixD2F3_ROOT_CNTL                                                        0x400001d
#define ixD2F3_ROOT_CAP                                                         0x400001d
#define ixD2F3_ROOT_STATUS                                                      0x400001e
#define ixD2F3_DEVICE_CAP2                                                      0x400001f
#define ixD2F3_DEVICE_CNTL2                                                     0x4000020
#define ixD2F3_DEVICE_STATUS2                                                   0x4000020
#define ixD2F3_LINK_CAP2                                                        0x4000021
#define ixD2F3_LINK_CNTL2                                                       0x4000022
#define ixD2F3_LINK_STATUS2                                                     0x4000022
#define ixD2F3_SLOT_CAP2                                                        0x4000023
#define ixD2F3_SLOT_CNTL2                                                       0x4000024
#define ixD2F3_SLOT_STATUS2                                                     0x4000024
#define ixD2F3_MSI_CAP_LIST                                                     0x4000028
#define ixD2F3_MSI_MSG_CNTL                                                     0x4000028
#define ixD2F3_MSI_MSG_ADDR_LO                                                  0x4000029
#define ixD2F3_MSI_MSG_ADDR_HI                                                  0x400002a
#define ixD2F3_MSI_MSG_DATA_64                                                  0x400002b
#define ixD2F3_MSI_MSG_DATA                                                     0x400002a
#define ixD2F3_SSID_CAP_LIST                                                    0x4000030
#define ixD2F3_SSID_CAP                                                         0x4000031
#define ixD2F3_MSI_MAP_CAP_LIST                                