/*
 * ia64 implementation of the mutex fastpath.
 *
 * Copyright (C) 2006 Ken Chen <kenneth.w.chen@intel.com>
 *
 */

#ifndef _ASM_MUTEX_H
#define _ASM_MUTEX_H

/**
 *  __mutex_fastpath_lock - try to take the lock by moving the count
 *     