                                                         0x3f4b8
#define ixDPM_TABLE_304                                                         0x3f4bc
#define ixDPM_TABLE_305                                                         0x3f4c0
#define ixDPM_TABLE_306                                                         0x3f4c4
#define ixDPM_TABLE_307                                                         0x3f4c8
#define ixDPM_TABLE_308                                                         0x3f4cc
#define ixDPM_TABLE_309                                                         0x3f4d0
#define ixDPM_TABLE_310                                                         0x3f4d4
#define ixDPM_TABLE_311                                                         0x3f4d8
#define ixDPM_TABLE_312                                                         0x3f4dc
#define ixDPM_TABLE_313                                                         0x3f4e0
#define ixDPM_TABLE_314                                                         0x3f4e4
#define ixDPM_TABLE_315                                                         0x3f4e8
#define ixDPM_TABLE_316                                                         0x3f4ec
#define ixDPM_TABLE_317                                                         0x3f4f0
#define ixDPM_TABLE_318                                                         0x3f4f4
#define ixDPM_TABLE_319                                                         0x3f4f8
#define ixDPM_TABLE_320                                                         0x3f4fc
#define ixDPM_TABLE_321                                                         0x3f500
#define ixDPM_TABLE_322                                                         0x3f504
#define ixDPM_TABLE_323                                                         0x3f508
#define ixDPM_TABLE_324                                                         0x3f50c
#define ixDPM_TABLE_325                                                         0x3f510
#define ixDPM_TABLE_326                                                         0x3f514
#define ixDPM_TABLE_327                                                         0x3f518
#define ixDPM_TABLE_328                                                         0x3f51c
#define ixDPM_TABLE_329                                                         0x3f520
#define ixDPM_TABLE_330                                                         0x3f524
#define ixDPM_TABLE_331                                                         0x3f528
#define ixDPM_TABLE_332                                                         0x3f52c
#define ixDPM_TABLE_333                                                         0x3f530
#define ixDPM_TABLE_334                                                         0x3f534
#define ixDPM_TABLE_335                                                         0x3f538
#define ixDPM_TABLE_336                                                         0x3f53c
#define ixDPM_TABLE_337                                                         0x3f540
#define ixDPM_TABLE_338                                                         0x3f544
#define ixDPM_TABLE_339                                                         0x3f548
#define ixDPM_TABLE_340                                                         0x3f54c
#define ixDPM_TABLE_341                                                         0x3f550
#define ixDPM_TABLE_342                                                         0x3f554
#define ixDPM_TABLE_343                                                         0x3f558
#define ixDPM_TABLE_344                                                         0x3f55c
#define ixDPM_TABLE_345                                                         0x3f560
#define ixDPM_TABLE_346                                                         0x3f564
#define ixDPM_TABLE_347                                                         0x3f568
#define ixDPM_TABLE_348                                                         0x3f56c
#define ixDPM_TABLE_349                                                         0x3f570
#define ixDPM_TABLE_350                                                         0x3f574
#define ixDPM_TABLE_351                                                         0x3f578
#define ixDPM_TABLE_352                                                         0x3f57c
#define ixDPM_TABLE_353                                                         0x3f580
#define ixDPM_TABLE_354                                                         0x3f584
#define ixDPM_TABLE_355                                                         0x3f588
#define ixDPM_TABLE_356                                                         0x3f58c
#define ixDPM_TABLE_357                                                         0x3f590
#define ixDPM_TABLE_358                                                         0x3f594
#define ixDPM_TABLE_359                                                         0x3f598
#define ixDPM_TABLE_360                                                         0x3f59c
#define ixDPM_TABLE_361                                                         0x3f5a0
#define ixDPM_TABLE_362                                                         0x3f5a4
#define ixDPM_TABLE_363                                                         0x3f5a8
#define ixDPM_TABLE_364                                                         0x3f5ac
#define ixDPM_TABLE_365                                                         0x3f5b0
#define ixDPM_TABLE_366                                                         0x3f5b4
#define ixDPM_TABLE_367                                                         0x3f5b8
#define ixDPM_TABLE_368                                                         0x3f5bc
#define ixDPM_TABLE_369                                                         0x3f5c0
#define ixDPM_TABLE_370                                                         0x3f5c4
#define ixDPM_TABLE_371                                                         0x3f5c8
#define ixDPM_TABLE_372                                                         0x3f5cc
#define ixDPM_TABLE_373                                                         0x3f5d0
#define ixDPM_TABLE_374                                                         0x3f5d4
#define ixDPM_TABLE_375                                                         0x3f5d8
#define ixDPM_TABLE_376                                                         0x3f5dc
#define ixDPM_TABLE_377                                                         0x3f5e0
#define ixDPM_TABLE_378                                                         0x3f5e4
#define ixDPM_TABLE_379                                                         0x3f5e8
#define ixDPM_TABLE_380                                                         0x3f5ec
#define ixDPM_TABLE_381                                                         0x3f5f0
#define ixDPM_TABLE_382                                                         0x3f5f4
#define ixDPM_TABLE_383                                                         0x3f5f8
#define ixDPM_TABLE_384                                                         0x3f5fc
#define ixDPM_TABLE_385                                                         0x3f600
#define ixDPM_TABLE_386                                                         0x3f604
#define ixDPM_TABLE_387                                                         0x3f608
#define ixDPM_TABLE_388                                                         0x3f60c
#define ixDPM_TABLE_389                                                         0x3f610
#define ixDPM_TABLE_390                                                         0x3f614
#define ixDPM_TABLE_391                                                         0x3f618
#define ixDPM_TABLE_392                                                         0x3f61c
#define ixDPM_TABLE_393                                                         0x3f620
#define ixDPM_TABLE_394                                                         0x3f624
#define ixDPM_TABLE_395                                                         0x3f628
#define ixDPM_TABLE_396                                                         0x3f62c
#define ixDPM_TABLE_397                                                         0x3f630
#define ixDPM_TABLE_398                                                         0x3f634
#define ixDPM_TABLE_399                                                         0x3f638
#define ixDPM_TABLE_400                                                         0x3f63c
#define ixDPM_TABLE_401                                                         0x3f640
#define ixDPM_TABLE_402                                                         0x3f644
#define ixDPM_TABLE_403                                                         0x3f648
#define ixDPM_TABLE_404                                                         0x3f64c
#define ixDPM_TABLE_405                                                         0x3f650
#define ixDPM_TABLE_406                                                         0x3f654
#define ixDPM_TABLE_407                                                         0x3f658
#define ixDPM_TABLE_408                                                         0x3f65c
#define ixDPM_TABLE_409                                                         0x3f660
#define ixDPM_TABLE_410                                                         0x3f664
#define ixDPM_TABLE_411                                                         0x3f668
#define ixDPM_TABLE_412                                                         0x3f66c
#define ixDPM_TABLE_413                                                         0x3f670
#define ixDPM_TABLE_414                                                         0x3f674
#define ixDPM_TABLE_415                                                         0x3f678
#define ixDPM_TABLE_416                                                         0x3f67c
#define ixDPM_TABLE_417                                                         0x3f680
#define ixDPM_TABLE_418                                                         0x3f684
#define ixDPM_TABLE_419                                                         0x3f688
#define ixDPM_TABLE_420                                                         0x3f68c
#define ixDPM_TABLE_421                                                         0x3f690
#define ixDPM_TABLE_422                                                         0x3f694
#define ixDPM_TABLE_423                                                         0x3f698
#define ixDPM_TABLE_424                                                         0x3f69c
#define ixDPM_TABLE_425                                                         0x3f6a0
#define ixDPM_TABLE_426                                                         0x3f6a4
#define ixDPM_TABLE_427                                                         0x3f6a8
#define ixDPM_TABLE_428                                                         0x3f6ac
#define ixDPM_TABLE_429                                                         0x3f6b0
#define ixDPM_TABLE_430                                                         0x3f6b4
#define ixDPM_TABLE_431                                                         0x3f6b8
#define ixDPM_TABLE_432                                                         0x3f6bc
#define ixDPM_TABLE_433                                                         0x3f6c0
#define ixDPM_TABLE_434                                                         0x3f6c4
#define ixDPM_TABLE_435                                                         0x3f6c8
#define ixDPM_TABLE_436                                                         0x3f6cc
#define ixDPM_TABLE_437                                                         0x3f6d0
#define ixDPM_TABLE_438                                                         0x3f6d4
#define ixDPM_TABLE_439                                                         0x3f6d8
#define ixDPM_TABLE_440                                                         0x3f6dc
#define ixDPM_TABLE_441                                                         0x3f6e0
#define ixDPM_TABLE_442                                                         0x3f6e4
#define ixDPM_TABLE_443                                                         0x3f6e8
#define ixDPM_TABLE_444                                                         0x3f6ec
#define ixDPM_TABLE_445                                                         0x3f6f0
#define ixDPM_TABLE_446                                                         0x3f6f4
#define ixDPM_TABLE_447                                                         0x3f6f8
#define ixDPM_TABLE_448                                                         0x3f6fc
#define ixDPM_TABLE_449                                                         0x3f700
#define ixDPM_TABLE_450                                                         0x3f704
#define ixDPM_TABLE_451                                                         0x3f708
#define ixDPM_TABLE_452                                                         0x3f70c
#define ixDPM_TABLE_453                                                         0x3f710
#define ixDPM_TABLE_454                                                         0x3f714
#define ixDPM_TABLE_455                                                         0x3f718
#define ixDPM_TABLE_456                                                         0x3f71c
#define ixDPM_TABLE_457                                                         0x3f720
#define ixDPM_TABLE_458                                                         0x3f724
#define ixDPM_TABLE_459                                                         0x3f728
#define ixDPM_TABLE_460                                                         0x3f72c
#define ixDPM_TABLE_461                                                         0x3f730
#define ixDPM_TABLE_462                                                         0x3f734
#define ixDPM_TABLE_463                                                         0x3f738
#define ixDPM_TABLE_464                                                         0x3f73c
#define ixDPM_TABLE_465                                                         0x3f740
#define ixDPM_TABLE_466                                                         0x3f744
#define ixDPM_TABLE_467                                                         0x3f748
#define ixDPM_TABLE_468                                                         0x3f74c
#define ixDPM_TABLE_469                                                         0x3f750
#define ixDPM_TABLE_470                                                         0x3f754
#define ixDPM_TABLE_471                                                         0x3f758
#define ixDPM_TABLE_472                                                         0x3f75c
#define ixDPM_TABLE_473                                                         0x3f760
#define ixDPM_TABLE_474                                                         0x3f764
#define ixDPM_TABLE_475                                                         0x3f768
#define ixDPM_TABLE_476                                                         0x3f76c
#define ixDPM_TABLE_477                                                         0x3f770
#define ixDPM_TABLE_478                                                         0x3f774
#define ixDPM_TABLE_479                                                         0x3f778
#define ixDPM_TABLE_480                                                         0x3f77c
#define ixDPM_TABLE_481                                                         0x3f780
#define ixDPM_TABLE_482                                                         0x3f784
#define ixDPM_TABLE_483                                                         0x3f788
#define ixDPM_TABLE_484                                                         0x3f78c
#define ixDPM_TABLE_485                                                         0x3f790
#define ixDPM_TABLE_486                                                         0x3f794
#define ixDPM_TABLE_487                                                         0x3f798
#define ixDPM_TABLE_488                                                         0x3f79c
#define ixDPM_TABLE_489                                                         0x3f7a0
#define ixDPM_TABLE_490                                                         0x3f7a4
#define ixDPM_TABLE_491                                                         0x3f7a8
#define ixDPM_TABLE_492                                                         0x3f7ac
#define ixDPM_TABLE_493                                                         0x3f7b0
#define ixDPM_TABLE_494                                                         0x3f7b4
#define ixDPM_TABLE_495                                                         0x3f7b8
#define ixDPM_TABLE_496                                                         0x3f7bc
#define ixDPM_TABLE_497                                                         0x3f7c0
#define ixDPM_TABLE_498                                                         0x3f7c4
#define ixDPM_TABLE_499                                                         0x3f7c8
#define ixDPM_TABLE_500                                                         0x3f7cc
#define ixDPM_TABLE_501                                                         0x3f7d0
#define ixDPM_TABLE_502                                                         0x3f7d4
#define ixDPM_TABLE_503                                                         0x3f7d8
#define ixDPM_TABLE_504                                                         0x3f7dc
#define ixDPM_TABLE_505                                                         0x3f7e0
#define ixDPM_TABLE_506                                                         0x3f7e4
#define ixFIRMWARE_FLAGS                                                        0x3f800
#define ixTDC_STATUS                                                            0x3f808
#define ixTDC_MV_AVERAGE                                                        0x3f80c
#define ixTDC_VRM_LIMIT                                                         0x3f810
#define ixFEATURE_STATUS                                                        0x3f818
#define ixENTITY_TEMPERATURES_1                                                 0x3f81c
#define ixMCARB_DRAM_TIMING_TABLE_1                                             0x3f900
#define ixMCARB_DRAM_TIMING_TABLE_2                                             0x3f904
#define ixMCARB_DRAM_TIMING_TABLE_3                                             0x3f908
#define ixMCARB_DRAM_TIMING_TABLE_4                                             0x3f90c
#define ixMCARB_DRAM_TIMING_TABLE_5                                             0x3f910
#define ixMCARB_DRAM_TIMING_TABLE_6                                             0x3f914
#define ixMCARB_DRAM_TIMING_TABLE_7                                             0x3f918
#define ixMCARB_DRAM_TIMING_TABLE_8                                             0x3f91c
#define ixMCARB_DRAM_TIMING_TABLE_9                                             0x3f920
#define ixMCARB_DRAM_TIMING_TABLE_10                                            0x3f924
#define ixMCARB_DRAM_TIMING_TABLE_11                                            0x3f928
#define ixMCARB_DRAM_TIMING_TABLE_12                                            0x3f92c
#define ixMCARB_DRAM_TIMING_TABLE_13                                            0x3f930
#define ixMCARB_DRAM_TIMING_TABLE_14                                            0x3f934
#define ixMCARB_DRAM_TIMING_TABLE_15                                            0x3f938
#define ixMCARB_DRAM_TIMING_TABLE_16                                            0x3f93c
#define ixMCARB_DRAM_TIMING_TABLE_17                                            0x3f940
#define ixMCARB_DRAM_TIMING_TABLE_18                                            0x3f944
#define ixMCARB_DRAM_TIMING_TABLE_19                                            0x3f948
#define ixMCARB_DRAM_TIMING_TABLE_20                                            0x3f94c
#define ixMCARB_DRAM_TIMING_TABLE_21                                            0x3f950
#define ixMCARB_DRAM_TIMING_TABLE_22                                            0x3f954
#define ixMCARB_DRAM_TIMING_TABLE_23                                            0x3f958
#define ixMCARB_DRAM_TIMING_TABLE_24                                            0x3f95c
#define ixMCARB_DRAM_TIMING_TABLE_25                                            0x3f960
#define ixMCARB_DRAM_TIMING_TABLE_26                                            0x3f964
#define ixMCARB_DRAM_TIMING_TABLE_27                                            0x3f968
#define ixMCARB_DRAM_TIMING_TABLE_28                                            0x3f96c
#define ixMCARB_DRAM_TIMING_TABLE_29                                            0x3f970
#define ixMCARB_DRAM_TIMING_TABLE_30                                            0x3f974
#define ixMCARB_DRAM_TIMING_TABLE_31                                            0x3f978
#define ixMCARB_DRAM_TIMING_TABLE_32                                            0x3f97c
#define ixMCARB_DRAM_TIMING_TABLE_33                                            0x3f980
#define ixMCARB_DRAM_TIMING_TABLE_34                                            0x3f984
#define ixMCARB_DRAM_TIMING_TABLE_35                                            0x3f988
#define ixMCARB_DRAM_TIMING_TABLE_36                                            0x3f98c
#define ixMCARB_DRAM_TIMING_TABLE_37                                            0x3f990
#define ixMCARB_DRAM_TIMING_TABLE_38                                            0x3f994
#define ixMCARB_DRAM_TIMING_TABLE_39                                            0x3f998
#define ixMCARB_DRAM_TIMING_TABLE_40                                            0x3f99c
#define ixMCARB_DRAM_TIMING_TABLE_41                                            0x3f9a0
#define ixMCARB_DRAM_TIMING_TABLE_42                                            0x3f9a4
#define ixMCARB_DRAM_TIMING_TABLE_43                                            0x3f9a8
#define ixMCARB_DRAM_TIMING_TABLE_44                                            0x3f9ac
#define ixMCARB_DRAM_TIMING_TABLE_45                                            0x3f9b0
#define ixMCARB_DRAM_TIMING_TABLE_46                                            0x3f9b4
#define ixMCARB_DRAM_TIMING_TABLE_47                                            0x3f9b8
#define ixMCARB_DRAM_TIMING_TABLE_48                                            0x3f9bc
#define ixMCARB_DRAM_TIMING_TABLE_49                                            0x3f9c0
#define ixMCARB_DRAM_TIMING_TABLE_50                                            0x3f9c4
#define ixMCARB_DRAM_TIMING_TABLE_51                                            0x3f9c8
#define ixMCARB_DRAM_TIMING_TABLE_52                                            0x3f9cc
#define ixMCARB_DRAM_TIMING_TABLE_53                                            0x3f9d0
#define ixMCARB_DRAM_TIMING_TABLE_54                                            0x3f9d4
#define ixMCARB_DRAM_TIMING_TABLE_55                                            0x3f9d8
#define ixMCARB_DRAM_TIMING_TABLE_56                                            0x3f9dc
#define ixMCARB_DRAM_TIMING_TABLE_57                                            0x3f9e0
#define ixMCARB_DRAM_TIMING_TABLE_58                                            0x3f9e4
#define ixMCARB_DRAM_TIMING_TABLE_59                                            0x3f9e8
#define ixMCARB_DRAM_TIMING_TABLE_60                                            0x3f9ec
#define ixMCARB_DRAM_TIMING_TABLE_61                                            0x3f9f0
#define ixMCARB_DRAM_TIMING_TABLE_62                                            0x3f9f4
#define ixMCARB_DRAM_TIMING_TABLE_63                                            0x3f9f8
#define ixMCARB_DRAM_TIMING_TABLE_64                                            0x3f9fc
#define ixMCARB_DRAM_TIMING_TABLE_65                                            0x3fa00
#define ixMCARB_DRAM_TIMING_TABLE_66                                            0x3fa04
#define ixMCARB_DRAM_TIMING_TABLE_67                                            0x3fa08
#define ixMCARB_DRAM_TIMING_TABLE_68                                            0x3fa0c
#define ixMCARB_DRAM_TIMING_TABLE_69                                            0x3fa10
#define ixMCARB_DRAM_TIMING_TABLE_70                                            0x3fa14
#define ixMCARB_DRAM_TIMING_TABLE_71                                            0x3fa18
#define ixMCARB_DRAM_TIMING_TABLE_72                                            0x3fa1c
#define ixMCARB_DRAM_TIMING_TABLE_73                                            0x3fa20
#define ixMCARB_DRAM_TIMING_TABLE_74                                            0x3fa24
#define ixMCARB_DRAM_TIMING_TABLE_75                                            0x3fa28
#define ixMCARB_DRAM_TIMING_TABLE_76                                            0x3fa2c
#define ixMCARB_DRAM_TIMING_TABLE_77                                            0x3fa30
#define ixMCARB_DRAM_TIMING_TABLE_78                                            0x3fa34
#define ixMCARB_DRAM_TIMING_TABLE_79                                            0x3fa38
#define ixMCARB_DRAM_TIMING_TABLE_80                                            0x3fa3c
#define ixMCARB_DRAM_TIMING_TABLE_81                                            0x3fa40
#define ixMCARB_DRAM_TIMING_TABLE_82                                            0x3fa44
#define ixMCARB_DRAM_TIMING_TABLE_83                                            0x3fa48
#define ixMCARB_DRAM_TIMING_TABLE_84                                            0x3fa4c
#define ixMCARB_DRAM_TIMING_TABLE_85                                            0x3fa50
#define ixMCARB_DRAM_TIMING_TABLE_86                                            0x3fa54
#define ixMCARB_DRAM_TIMING_TABLE_87                                            0x3fa58
#define ixMCARB_DRAM_TIMING_TABLE_88                                            0x3fa5c
#define ixMCARB_DRAM_TIMING_TABLE_89                                            0x3fa60
#define ixMCARB_DRAM_TIMING_TABLE_90                                            0x3fa64
#define ixMCARB_DRAM_TIMING_TABLE_91                                            0x3fa68
#define ixMCARB_DRAM_TIMING_TABLE_92                                            0x3fa6c
#define ixMCARB_DRAM_TIMING_TABLE_93                                            0x3fa70
#define ixMCARB_DRAM_TIMING_TABLE_94                                            0x3fa74
#define ixMCARB_DRAM_TIMING_TABLE_95                                            0x3fa78
#define ixMCARB_DRAM_TIMING_TABLE_96                                            0x3fa7c
#define ixMCARB_DRAM_TIMING_TABLE_97                                            0x3fa80
#define ixMCARB_DRAM_TIMING_TABLE_98                                            0x3fa84
#define ixMCARB_DRAM_TIMING_TABLE_99                                            0x3fa88
#define ixMCARB_DRAM_TIMING_TABLE_100                                           0x3fa8c
#define ixMCARB_DRAM_TIMING_TABLE_101                                           0x3fa90
#define ixMCARB_DRAM_TIMING_TABLE_102                                           0x3fa94
#define ixMCARB_DRAM_TIMING_TABLE_103                                           0x3fa98
#define ixMCARB_DRAM_TIMING_TABLE_104                                           0x3fa9c
#define ixMCARB_DRAM_TIMING_TABLE_105                                           0x3faa0
#define ixMCARB_DRAM_TIMING_TABLE_106                                           0x3faa4
#define ixMCARB_DRAM_TIMING_TABLE_107                                           0x3faa8
#define ixMCARB_DRAM_TIMING_TABLE_108                                           0x3faac
#define ixMCARB_DRAM_TIMING_TABLE_109                                           0x3fab0
#define ixMCARB_DRAM_TIMING_TABLE_110                                           0x3fab4
#define ixMCARB_DRAM_TIMING_TABLE_111                                           0x3fab8
#define ixMCARB_DRAM_TIMING_TABLE_112                                           0x3fabc
#define ixMCARB_DRAM_TIMING_TABLE_113                                           0x3fac0
#define ixMCARB_DRAM_TIMING_TABLE_114                                           0x3fac4
#define ixMCARB_DRAM_TIMING_TABLE_115                                           0x3fac8
#define ixMCARB_DRAM_TIMING_TABLE_116                                           0x3facc
#define ixMCARB_DRAM_TIMING_TABLE_117                                           0x3fad0
#define ixMCARB_DRAM_TIMING_TABLE_118                                           0x3fad4
#define ixMCARB_DRAM_TIMING_TABLE_119                                        