                 0x3fcfc
#define ixMC_REGISTERS_TABLE_113                                                0x3fd00
#define ixFAN_TABLE_1                                                           0x3fd04
#define ixFAN_TABLE_2                                                           0x3fd08
#define ixFAN_TABLE_3                                                           0x3fd0c
#define ixFAN_TABLE_4                                                           0x3fd10
#define ixFAN_TABLE_5                                                           0x3fd14
#define ixFAN_TABLE_6                                                           0x3fd18
#define ixFAN_TABLE_7                                                           0x3fd1c
#define ixFAN_TABLE_8                                                           0x3fd20
#define ixFAN_TABLE_9                                                           0x3fd24
#define ixSOFT_REGISTERS_TABLE_1                                                0x3fd28
#define ixSOFT_REGISTERS_TABLE_2                                                0x3fd2c
#define ixSOFT_REGISTERS_TABLE_3                                                0x3fd30
#define ixSOFT_REGISTERS_TABLE_4                                                0x3fd34
#define ixSOFT_REGISTERS_TABLE_5                                                0x3fd38
#define ixSOFT_REGISTERS_TABLE_6                                                0x3fd3c
#define ixSOFT_REGISTERS_TABLE_7                                                0x3fd40
#define ixSOFT_REGISTERS_TABLE_8                                                0x3fd44
#define ixSOFT_REGISTERS_TABLE_9                                                0x3fd48
#define ixSOFT_REGISTERS_TABLE_10                                               0x3fd4c
#define ixSOFT_REGISTERS_TABLE_11                                               0x3fd50
#define ixSOFT_REGISTERS_TABLE_12                                               0x3fd54
#define ixSOFT_REGISTERS_TABLE_13                                               0x3fd58
#define ixSOFT_REGISTERS_TABLE_14                                               0x3fd5c
#define ixSOFT_REGISTERS_TABLE_15                                               0x3fd60
#define ixSOFT_REGISTERS_TABLE_16                                               0x3fd64
#define ixSOFT_REGISTERS_TABLE_17                                               0x3fd68
#define ixSOFT_REGISTERS_TABLE_18                                               0x3fd6c
#define ixSOFT_REGISTERS_TABLE_19                                               0x3fd70
#define ixSOFT_REGISTERS_TABLE_20                                               0x3fd74
#define ixSOFT_REGISTERS_TABLE_21                                               0x3fd78
#define ixSOFT_REGISTERS_TABLE_22                                               0x3fd7c
#define ixSOFT_REGISTERS_TABLE_23                                               0x3fd80
#define ixSOFT_REGISTERS_TABLE_24                                               0x3fd84
#define ixSOFT_REGISTERS_TABLE_25                                               0x3fd88
#define ixSOFT_REGISTERS_TABLE_26                                               0x3fd8c
#define ixSOFT_REGISTERS_TABLE_27                                               0x3fd90
#define ixSOFT_REGISTERS_TABLE_28                                               0x3fd94
#define ixSOFT_REGISTERS_TABLE_29                                               0x3fd98
#define ixSOFT_REGISTERS_TABLE_30                                               0x3fd9c
#define ixPM_FUSES_1                                                            0x3fda0
#define ixPM_FUSES_2                                                            0x3fda4
#define ixPM_FUSES_3                                                            0x3fda8
#define ixPM_FUSES_4                                                            0x3fdac
#define ixPM_FUSES_5                                                            0x3fdb0
#define ixPM_FUSES_6                                                            0x3fdb4
#define ixPM_FUSES_7                                                            0x3fdb8
#define ixPM_FUSES_8                                                            0x3fdbc
#define ixPM_FUSES_9                                                            0x3fdc0
#define ixPM_FUSES_10                                                           0x3fdc4
#define ixPM_FUSES_11                                                           0x3fdc8
#define ixPM_FUSES_12                                                           0x3fdcc
#define ixPM_FUSES_13                                                           0x3fdd0
#define ixPM_FUSES_14                                                           0x3fdd4
#define ixPM_FUSES_15                                                           0x3fdd8
#define ixPM_FUSES_16                                                           0x3fddc
#define ixPM_FUSES_17                                                           0x3fde0
#define ixPM_FUSES_18                                                           0x3fde4
#define ixPM_FUSES_19                                                           0x3fde8
#define ixSMU_PM_STATUS_0                                                       0x3fe00
#define ixSMU_PM_STATUS_1                                                       0x3fe04
#define ixSMU_PM_STATUS_2                                                       0x3fe08
#define ixSMU_PM_STATUS_3                                                       0x3fe0c
#define ixSMU_PM_STATUS_4                                                       0x3fe10
#define ixSMU_PM_STATUS_5                                                       0x3fe14
#define ixSMU_PM_STATUS_6                                                       0x3fe18
#define ixSMU_PM_STATUS_7                                                       0x3fe1c
#define ixSMU_PM_STATUS_8                                                       0x3fe20
#define ixSMU_PM_STATUS_9                                                       0x3fe24
#define ixSMU_PM_STATUS_10                                                      0x3fe28
#define ixSMU_PM_STATUS_11                                                      0x3fe2c
#define ixSMU_PM_STATUS_12                                                      0x3fe30
#define ixSMU_