ine mmSMC_RESP_6                                                            0xa1
#define mmSMC_MESSAGE_7                                                         0xa2
#define mmSMC_RESP_7                                                            0xa3
#define mmSMC_MSG_ARG_0                                                         0xa4
#define mmSMC_MSG_ARG_1                                                         0xa5
#define mmSMC_MSG_ARG_2                                                         0xa6
#define mmSMC_MSG_ARG_3                                                         0xa7
#define mmSMC_MSG_ARG_4                                                         0xa8
#define mmSMC_MSG_ARG_5                                                         0xa9
#define mmSMC_MSG_ARG_6                                                         0xaa
#define mmSMC_MSG_ARG_7                                                         0xab
#define mmSMC_MESSAGE_8                                                         0xb5
#define mmSMC_RESP_8                                                            0xb6
#define mmSMC_MESSAGE_9                                                         0xb7
#define mmSMC_RESP_9                                                            0xb8
#define mmSMC_MESSAGE_10                                                        0xb9
#define mmSMC_RESP_10                                                           0xba
#define mmSMC_MESSAGE_11                                                        0xbb
#define mmSMC_RESP_11                                                           0xbc
#define mmSMC_MSG_ARG_8                                                         0xbd
#define mmSMC_MSG_ARG_9                                                         0xbe
#define mmSMC_MSG_ARG_10                                                        0xbf
#define mmSMC_MSG_ARG_11                                                        0x93
#define ixSMC_SYSCON_RESET_CNTL                                            0x80000000
#define ixSMC_SYSCON_CLOCK_CNTL_0                                          0x80000004
#define ixSMC_SYSCON_CLOCK_CNTL_1                                          0x80000008
#define ixSMC_SYSCON_CLOCK_CNTL_2                                          0x8000000c
#define ixSMC_SYSCON_MISC_CNTL                                                  0x80000010
#define ixSMC_SYSCON_MSG_ARG_0                                                  0x80000068
#define ixSMC_PC_C                                                              0x80000370
#define ixSMC_SCRATCH9                                                          0x80000424
#define mmGPIOPAD_SW_INT_STAT                                                   0x180
#define mmGPIOPAD_STRENGTH                                                      0x181
#define mmGPIOPAD_MASK                                                          0x182
#define mmGPIOPAD_A                                                             0x183
#define mmGPIOPAD_EN                                                            0x184
#define mmGPIOPAD_Y                                                             0x185
#define mmGPIOPAD_PINSTRAPS                                                     0x186
#define mmGPIOPAD_INT_STAT_EN                                                   0x187
#define mmGPIOPAD_INT_STAT                                                      0x188
#define mmGPIOPAD_INT_STAT_AK                                                   0x189
#define mmGPIOPAD_INT_EN                                                        0x18a
#define mmGPIOPAD_INT_TYPE                                                      0x18b
#define mmGPIOPAD_INT_POLARITY                                                  0x18c
#define mmGPIOPAD_EXTERN_TRIG_CNTL                                              0x18d
#define mmGPIOPAD_RCVR_SEL                                                      0x191
#define mmGPIOPAD_PU_EN                                                         0x192
#define mmGPIOPAD_PD_EN                                                         0x193
#define mmCG_FPS_CNT                                                            0x1b6
#define mmSMU_IND_INDEX_0                                                       0x1a6
#define mmSMU_IND_DATA_0                                                        0x1a7
#define mmSMU_IND_INDEX_1                                                       0x1a8
#define mmSMU_IND_DATA_1                                                        0x1a9
#define mmSMU_IND_INDEX_2                                                       0x1aa
#define mmSMU_IND_DATA_2                                                        0x1ab
#define mmSMU_IND_INDEX_3                                                       0x1ac
#define mmSMU_IND_DATA_3                                                        0x1ad
#define mmSMU_IND_INDEX_4                                                       0x1ae
#define mmSMU_IND_DATA_4                                                        0x1af
#define mmSMU_IND_INDEX_5                                                       0x1b0
#define mmSMU_IND_DATA_5                                                        0x1b1
#define mmSMU_IND_INDEX_6                                                       0x1b2
#define mmSMU_IND_DATA_6                                                        0x1b3
#define mmSMU_IND_INDEX_7                                                       0x1b4
#define mmSMU_IND_DATA_7                                                        0x1b5
#define mmSMU_SMC_IND_INDEX                                                     0x80
#define mmSMU0_SMU_SMC_IND_INDEX                                                0x80
#define mmSMU1_SMU_SMC_IND_INDEX                                                0x82
#define mmSMU2_SMU_SMC_IND_INDEX                                                0x84
#define mmSMU3_SMU_SMC_IND_INDEX                                                0x86
#define mmSMU_SMC_IND_DATA                                                      0x81
#define mmSMU0_SMU_SMC_IND_DATA                                                 0x81
#define mmSMU1_SMU_SMC_IND_DATA                                                 0x83
#define mmSMU2_SMU_SMC_IND_DATA                                                 0x85
#define mmSMU3_SMU_SMC_IND_DATA                                                 0x87
#define ixRCU_UC_EVENTS                                                         0xc0000004
#define ixRCU_MISC_CTRL                                                         0xc0000010
#define ixRCU_VIRT_RESET_REQ                                                    0xc0000024
#define ixCC_RCU_FUSES                                                          0xc00c0000
#define ixCC_SMU_MISC_FUSES                                                     0xc00c0004
#define ixCC_SCLK_VID_FUSES                                                     0xc00c0008
#define ixCC_GIO_IOCCFG_FUSES                                                   0xc00c000c
#define ixCC_GIO_IOC_FUSES                                                      0xc00c0010
#define ixCC_SMU_TST_EFUSE1_MISC                                                0xc00c001c
#define ixCC_TST_ID_STRAPS                                                      0xc00c0020
#define ixCC_FCTRL_FUSES                                                        0xc00c0024
#define ixCC_HARVEST_FUSES                                                      0xc00c0028
#define ixSMU_MAIN_PLL_OP_FREQ                                                  0xe0003020
#define ixSMU_STATUS                                                       0xe0003088
#define ixSMU_FIRMWARE                                                     0xe00030a4
#define ixSMU_INPUT_DATA                                                   0xe00030b8
#define ixSMU_EFUSE_0                                                           0xc0100000
#define ixFIRMWARE_FLAGS                                                        0x3f000
#define ixTDC_STATUS                                                            0x3f004
#define ixTDC_MV_AVERAGE                                                        0x3f008
#define ixTDC_VRM_LIMIT                                                         0x3f00c
#define ixFEATURE_STATUS                                                        0x3f010
#define ixENTITY_TEMPERATURES_1                                                 0x3f014
#define ixMCARB_DRAM_TIMING_TABLE_1                                             0x3f018
#define ixMCARB_DRAM_TIMING_TABLE_2                                             0x3f01c
#define ixMCARB_DRAM_TIMING_TABLE_3                                             0x3f020
#define ixMCARB_DRAM_TIMING_TABLE_4                                             0x3f024
#define ixMCARB_DRAM_TIMING_TABLE_5                                             0x3f028
#define ixMCARB_DRAM_TIMING_TABLE_6                                             0x3f02c
#define ixMCARB_DRAM_TIMING_TABLE_7                                             0x3f030
#define ixMCARB_DRAM_TIMING_TABLE_8                                             0x3f034
#define ixMCARB_DRAM_TIMING_TABLE_9                                             0x3f038
#define ixMCARB_DRAM_TIMING_TABLE_10                                            0x3f03c
#define ixMCARB_DRAM_TIMING_TABLE_11                                            0x3f040
#define ixMCARB_DRAM_TIMING_TABLE_12                                            0x3f044
#define ixMCARB_DRAM_TIMING_TABLE_13                                            0x3f048
#define ixMCARB_DRAM_TIMING_TABLE_14                                            0x3f04c
#define ixMCARB_DRAM_TIMING_TABLE_15                                            0x3f050
#define ixMCARB_DRAM_TIMING_TABLE_16                                            0x3f054
#define ixMCARB_DRAM_TIMING_TABLE_17                                            0x3f058
#define ixMCARB_DRAM_TIMING_TABLE_18                                            0x3f05c
#define ixMCARB_DRAM_TIMING_TABLE_19                                            0x3f060
#define ixMCARB_DRAM_TIMING_TABLE_20                                            0x3f064
#define ixMCARB_DRAM_TIMING_TABLE_21                                            0x3f068
#define ixMCARB_DRAM_TIMING_TABLE_22                                            0x3f06c
#define ixMCARB_DRAM_TIMING_TABLE_23                                            0x3f070
#define ixMCARB_DRAM_TIMING_TABLE_24                                            0x3f074
#define ixMCARB_DRAM_TIMING_TABLE_25                                            0x3f078
#define ixMCARB_DRAM_TIMING_TABLE_26                                            0x3f07c
#define ixMCARB_DRAM_TIMING_TABLE_27                                            0x3f080
#define ixMCARB_DRAM_TIMING_TABLE_28                                            0x3f084
#define ixMCARB_DRAM_TIMING_TABLE_29                                            0x3f088
#define ixMCARB_DRAM_TIMING_TABLE_30                                            0x3f08c
#define ixMCARB_DRAM_TIMING_TABLE_31                                            0x3f090
#define ixMCARB_DRAM_TIMING_TABLE_32                                            0x3f094
#define ixMCARB_DRAM_TIMING_TABLE_33                                            0x3f098
#define ixMCARB_DRAM_TIMING_TABLE_34                                            0x3f09c
#define ixMCARB_DRAM_TIMING_TABLE_35                                            0x3f0a0
#define ixMCARB_DRAM_TIMING_TABLE_36                                            0x3f0a4
#define ixMCARB_DRAM_TIMING_TABLE_37                                            0x3f0a8
#define ixMCARB_DRAM_TIMING_TABLE_38                                            0x3f0ac
#define ixMCARB_DRAM_TIMING_TABLE_39                                            0x3f0b0
#define ixMCARB_DRAM_TIMING_TABLE_40                                            0x3f0b4
#define ixMCARB_DRAM_TIMING_TABLE_41                                            0x3f0b8
#define ixMCARB_DRAM_TIMING_TABLE_42                                            0x3f0bc
#define ixMCARB_DRAM_TIMING_TABLE_43                                            0x3f0c0
#define ixMCARB_DRAM_TIMING_TABLE_44                                            0x3f0c4
#define ixMCARB_DRAM_TIMING_TABLE_45                                            0x3f0c8
#define ixMCARB_DRAM_TIMING_TABLE_46                                            0x3f0cc
#define ixMCARB_DRAM_TIMING_TABLE_47                                            0x3f0d0
#define ixMCARB_DRAM_TIMING_TABLE_48                                            0x3f0d4
#define ixMCARB_DRAM_TIMING_TABLE_49                                            0x3f0d8
#define ixMCARB_DRAM_TIMING_TABLE_50                                            0x3f0dc
#define ixMCARB_DRAM_TIMING_TABLE_51                                            0x3f0e0
#define ixMCARB_DRAM_TIMING_TABLE_52                                            0x3f0e4
#define ixMCARB_DRAM_TIMING_TABLE_53                                            0x3f0e8
#define ixMCARB_DRAM_TIMING_TABLE_54                                            0x3f0ec
#define ixMCARB_DRAM_TIMING_TABLE_55                                            0x3f0f0
#define ixMCARB_DRAM_TIMING_TABLE_56                                            0x3f0f4
#define ixMCARB_DRAM_TIMING_TABLE_57                                            0x3f0f8
#define ixMCARB_DRAM_TIMING_TABLE_58                                            0x3f0fc
#define ixMCARB_DRAM_TIMING_TABLE_59                                            0x3f100
#define ixMCARB_DRAM_TIMING_TABLE_60                                            0x3f104
#define ixMCARB_DRAM_TIMING_TABLE_61                                            0x3f108
#define ixMCARB_DRAM_TIMING_TABLE_62                                            0x3f10c
#define ixMCARB_DRAM_TIMING_TABLE_63                                            0x3f110
#define ixMCARB_DRAM_TIMING_TABLE_64                                            0x3f114
#define ixMCARB_DRAM_TIMING_TABLE_65                                            0x3f118
#define ixMCARB_DRAM_TIMING_TABLE_66                                            0x3f11c
#define ixMCARB_DRAM_TIMING_TABLE_67                                            0x3f120
#define ixMCARB_DRAM_TIMING_TABLE_68                                            0x3f124
#define ixMCARB_DRAM_TIMING_TABLE_69                                            0x3f128
#define ixMCARB_DRAM_TIMING_TABLE_70                                            0x3f12c
#define ixMCARB_DRAM_TIMING_TABLE_71                                            0x3f130
#define ixMCARB_DRAM_TIMING_TABLE_72                                            0x3f134
#define ixMCARB_DRAM_TIMING_TABLE_73                                            0x3f138
#define ixMCARB_DRAM_TIMING_TABLE_74                                            0x3f13c
#define ixMCARB_DRAM_TIMING_TABLE_75                                            0x3f140
#define ixMCARB_DRAM_TIMING_TABLE_76                                            0x3f144
#define ixMCARB_DRAM_TIMING_TABLE_77                                            0x3f148
#define ixMCARB_DRAM_TIMING_TABLE_78                                            0x3f14c
#define ixMCARB_DRAM_TIMING_TABLE_79                                            0x3f150
#define ixMCARB_DRAM_TIMING_TABLE_80                                            0x3f154
#define ixMCARB_DRAM_TIMING_TABLE_81                                            0x3f158
#define ixMCARB_DRAM_TIMING_TABLE_82                                            0x3f15c
#define ixMCARB_DRAM_TIMING_TABLE_83                                            0x3f160
#define ixMCARB_DRAM_TIMING_TABLE_84                                            0x3f164
#define ixMCARB_DRAM_TIMING_TABLE_85                                            0x3f168
#define ixMCARB_DRAM_TIMING_TABLE_86                                            0x3f16c
#define ixMCARB_DRAM_TIMING_TABLE_87                                            0x3f170
#define ixMCARB_DRAM_TIMING_TABLE_88                                            0x3f174
#define ixMCARB_DRAM_TIMING_TABLE_89                                            0x3f178
#define ixMCARB_DRAM_TIMING_TABLE_90                                            0x3f17c
#define ixMCARB_DRAM_TIMING_TABLE_91                                            0x3f180
#define ixMCARB_DRAM_TIMING_TABLE_92                                            0x3f184
#define ixMCARB_DRAM_TIMING_TABLE_93                                            0x3f188
#define ixMCARB_DRAM_TIMING_TABLE_94                                            0x3f18c
#define ixMCARB_DRAM_TIMING_TABLE_95                                            0x3f190
#define ixMCARB_DRAM_TIMING_TABLE_96                                            0x3f194
#define ixDPM_TABLE_1                                                           0x3f198
#define ixDPM_TABLE_2                                                           0x3f19c
#define ixDPM_TABLE_3                                                           0x3f1a0
#define ixDPM_TABLE_4                                                           0x3f1a4
#define ixDPM_TABLE_5                                                           0x3f1a8
#define ixDPM_TABLE_6                                                           0x3f1ac
#define ixDPM_TABLE_7                                                           0x3f1b0
#define ixDPM_TABLE_8                                                           0x3f1b4
#define ixDPM_TABLE_9                                                           0x3f1b8
#define ixDPM_TABLE_10                                                          0x3f1bc
#define ixDPM_TABLE_11                                                          0x3f1c0
#define ixDPM_TABLE_12                                                          0x3f1c4
#define ixDPM_TABLE_13                                                          0x3f1c8
#define ixDPM_TABLE_14                                                          0x3f1cc
#define ixDPM_TABLE_15                                                          0x3f1d0
#define ixDPM_TABLE_16                                                          0x3f1d4
#define ixDPM_TABLE_17                                                          0x3f1d8
#define ixDPM_TABLE_18                                                          0x3f1dc
#define ixDPM_TABLE_19                                                          0x3f1e0
#define ixDPM_TABLE_20                                                          0x3f1e4
#define ixDPM_TABLE_21                                                          0x3f1e8
#define ixDPM_TABLE_22                                                          0x3f1ec
#define ixDPM_TABLE_23                                                          0x3f1f0
#define ixDPM_TABLE_24                                                          0x3f1f4
#define ixDPM_TABLE_25                                                          0x3f1f8
#define ixDPM_TABLE_26                                                          0x3f1fc
#define ixDPM_TABLE_27                                                          0x3f200
#define ixDPM_TABLE_28                                                          0x3f204
#define ixDPM_TABLE_29                                                          0x3f208
#define ixDPM_TABLE_30                                                          0x3f20c
#define ixDPM_TABLE_31                                                          0x3f210
#define ixDPM_TABLE_32                                                          0x3f214
#define ixDPM_TABLE_33                                                          0x3f218
#define ixDPM_TABLE_34                                                          0x3f21c
#define ixDPM_TABLE_35                                                          0x3f220
#define ixDPM_TABLE_36                                                          0x3f224
#define ixDPM_TABLE_37                                                          0x3f228
#define ixDPM_TABLE_38                                                          0x3f22c
#define ixDPM_TABLE_39                                                          0x3f230
#define ixDPM_TABLE_40                                                          0x3f234
#define ixDPM_TABLE_41                                                          0x3f238
#define ixDPM_TABLE_42                                                          0x3f23c
#define ixDPM_TABLE_43                                                          0x3f240
#define ixDPM_TABLE_44                                                          0x3f244
#define ixDPM_TABLE_45                                                          0x3f248
#define ixDPM_TABLE_46                                                          0x3f24c
#define ixDPM_TABLE_47                                                          0x3f250
#define ixDPM_TABLE_48                                                          0x3f254
#define ixDPM_TABLE_49                                                          0x3f258
#define ixDPM_TABLE_50                                                          0x3f25c
#define ixDPM_TABLE_51                                                          0x3f260
#define ixDPM_TABLE_52                                                          0x3f264
#define ixDPM_TABLE_53                                                          0x3f268
#define ixDPM_TABLE_54                                                          0x3f26c
#define ixDPM_TABLE_55                                                          0x3f270
#define ixDPM_TABLE_56                                                          0x3f274
#define ixDPM_TABLE_57                                                          0x3f278
#define ixDPM_TABLE_58                                                          0x3f27c
#define ixDPM_TABLE_59                                                          0x3f280
#define ixDPM_TABLE_60                                                          0x3f284
#define ixDPM_TABLE_61                                                          0x3f288
#define ixDPM_TABLE_62                                                          0x3f28c
#define ixDPM_TABLE_63                                                          0x3f290
#define ixDPM_TABLE_64                                                          0x3f294
#define ixDPM_TABLE_65                                                          0x3f298
#define ixDPM_TABLE_66                                                          0x3f29c
#define ixDPM_TABLE_67                                                          0x3f2a0
#define ixDPM_TABLE_68                                                          0x3f2a4
#define ixDPM_TABLE_69                                                          0x3f2a8
#define ixDPM_TABLE_70                                                          0x3f2ac
#define ixDPM_TABLE_71                                                          0x3f2b0
#define ixDPM_TABLE_72                                                          0x3f2b4
#define ixDPM_TABLE_73                                                          0x3f2b8
#define ixDPM_TABLE_74                                                          0x3f2bc
#define ixDPM_TABLE_75                                                          0x3f2c0
#define ixDPM_TABLE_76                                                          0x3f2c4
#define ixDPM_TABLE_77                                                          0x3f2c8
#define ixDPM_TABLE_78                                                          0x3f2cc
#define ixDPM_TABLE_79                                                          0x3f2d0
#define ixDPM_TABLE_80                                                          0x3f2d4
#define ixDPM_TABLE_81                                                          0x3f2d8
#define ixDPM_TABLE_82                                                          0x3f2dc
#define ixDPM_TABLE_83                                                          0x3f2e0
#define ixDPM_TABLE_84                                                          0x3f2e4
#define ixDPM_TABLE_85                                                          0x3f2e8
#define ixDPM_TABLE_86                                                          0x3f2ec
#define ixDPM_TABLE_87                                                          0x3f2f0
#define ixDPM_TABLE_88                                                          0x3f2f4
#define ixDPM_TABLE_89                                                          0x3f2f8
#define ixDPM_TABLE_90                                                          0x3f2fc
#define ixDPM_TABLE_91                                                          0x3f300
#define ixDPM_TABLE_92                                                          0x3f304
#define ixDPM_TABLE_93                                                          0x3f308
#define ixDPM_TABLE_94                                                          0x3f30c
#define ixDPM_TABLE_95                                                          0x3f310
#define ixDPM_TABLE_96                                                          0x3f314
#define ixDPM_TABLE_97                                                          0x3f318
#define ixDPM_TABLE_98                                                          0x3f31c
#define ixDPM_TABLE_99                                                          0x3f320
#define ixDPM_TABLE_100                                                         0x3f324
#define ixDPM_TABLE_101                                                         0x3f328
#define ixDPM_TABLE_102                                                         0x3f32c
#define ixDPM_TABLE_103                                                         0x3f330
#define ixDPM_TABLE_104                                                         0x3f334
#define ixDPM_TABLE_105                                                         0x3f338
#define ixDPM_TABLE_106                                                         0x3f33c
#define ixDPM_TABLE_107                                                         0x3f340
#define ixDPM_TABLE_108                                                         0x3f344
#define ixDPM_TABLE_109                                                         0x3f348
#define ixDPM_TABLE_110                                                         0x3f34c
#define ixDPM_TABLE_111                                                         0x3f350
#define ixDPM_TABLE_112                                                         0x3f354
#define ixDPM_TABLE_113                                                         0x3f358
#define ixDPM_TABLE_114                                                         0x3f35c
#define ixDPM_TABLE_115                                                         0x3f360
#define ixDPM_TABLE_116                                                         0x3f364
#define ixDPM_TABLE_117                                                         0x3f368
#define ixDPM_TABLE_118                                                         0x3f36c
#define ixDPM_TABLE_119                                                         0x3f370
#define ixDPM_TABLE_120                                                         0x3f374
#define ixDPM_TABLE_121                                                         0x3f378
#define ixDPM_TABLE_122                                                         0x3f37c
#define ixDPM_TABLE_123                                                         0x3f380
#define ixDPM_TABLE_124                                                         0x3f384
#define ixDPM_TABLE_125                                                         0x3f388
#define ixDPM_TABLE_126                                                         0x3f38c
#define ixDPM_TABLE_127                                                         0x3f390
#define ixDPM_TABLE_128                                                         0x3f394
#define ixDPM_TABLE_129                                                         0x3f398
#define ixDPM_TABLE_130                                                         0x3f39c
#define ixDPM_TABLE_131                                                         0x3f3a0
#define ixDPM_TABLE_132                                                         0x3f3a4
#define ixDPM_TABLE_133                                                         0x3f3a8
#define ixDPM_TABLE_134                                                         0x3f3ac
#define ixDPM_TABLE_135                                                         0x3f3b0
#define ixDPM_TABLE_136                                                         0x3f3b4
#define ixDPM_TABLE_137                                                         0x3f3b8
#define ixDPM_TABLE_138                                                         0x3f3bc
#define ixDPM_TABLE_139                                                         0x3f3c0
#define ixDPM_TABLE_140                                                         0x3f3c4
#define ixDPM_TABLE_141                                                         0x3f3c8
#define ixDPM_TABLE_142                                                         0x3f3cc
#define ixDPM_TABLE_143                                                         0x3f3d0
#define ixDPM_TABLE_144                                                         0x3f3d4
#define ixDPM_TABLE_145                                                         0x3f3d8
#define ixDPM_TABLE_146                                                         0x3f3dc
#define ixDPM_TABLE_147                                                         0x3f3e0
#define ixDPM_TABLE_148                                                         0x3f3e4
#define ixDPM_TABLE_149                                                         0x3f3e8
#define ixDPM_TABLE_150                                                         0x3f3ec
#define ixDPM_TABLE_151                                                         0x3f3f0
#define ixDPM_TABLE_152                                                         0x3f3f4
#define ixDPM_TABLE_153                                                         0x3f3f8
#define ixDPM_TABLE_154                                                         0x3f3fc
#define ixDPM_TABLE_155                                                         0x3f400
#define ixDPM_TABLE_156                                                         0x3f404
#define ixDPM_TABLE_157                                                         0x3f408
#define ixDPM_TABLE_158                                                         0x3f40c
#define ixDPM_TABLE_159                                                         0x3f410
#define ixDPM_TABLE_160                                                         0x3f414
#define ixDPM_TABLE_161                                                         0x3f418
#define ixDPM_TABLE_162                                                         0x3f41c
#define ixDPM_TABLE_163                                                         0x3f420
#define ixDPM_TABLE_164                                                         0x3f424
#define ixDPM_TABLE_165                                                         0x3f428
#define ixDPM_TABLE_166                                                         0x3f42c
#define ixDPM_TABLE_167                                                         0x3f430
#define ixDPM_TABLE_168                                                         0x3f434
#define ixDPM_TABLE_169                                                         0x3f438
#define ixDPM_TABLE_170                                                         0x3f43c
#define ixDPM_TABLE_171                                                         0x3f440
#define ixDPM_TABLE_172                                                         0x3f444
#define ixDPM_TABLE_173                                                         0x3f448
#define ixDPM_TABLE_174                                                         0x3f44c
#define ixDPM_TABLE_175                                                         0x3f450
#define ixDPM_TABLE_176                                                         0x3f454
#define ixDPM_TABLE_177                                                         0x3f458
#define ixDPM_TABLE_178                                                         0x3f45c
#define ixDPM_TABLE_179                                                         0x3f460
#define ixDPM_TABLE_180                                                         0x3f464
#define ixDPM_TABLE_181                                                         0x3f468
#define ixDPM_TABLE_182                                                         0x3f46c
#define ixDPM_TABLE_183                                                         0x3f470
#define ixDPM_TABLE_184                                                         0x3f474
#define ixDPM_TABLE_185                                                         0x3f478
#define ixDPM_TABLE_186                                                         0x3f47c
#define ixDPM_TABLE_187                                                         0x3f480
#define ixDPM_TABLE_188                                                         0x3f484
#define ixDPM_TABLE_189                                                         0x3f488
#define ixDPM_TABLE_190                                                         0x3f48c
#define ixDPM_TABLE_191                                                         0x3f490
#define ixDPM_TABLE_192                                                         0x3f494
#define ixDPM_TABLE_193                                                         0x3f498
#define ixDPM_TABLE_194                                                         0x3f49c
#define ixDPM_TABLE_195                                                         0x3f4a0
#define ixDPM_TABLE_196                                                         0x3f4a4
#define ixDPM_TABLE_197                                                         0x3f4a8
#define ixDPM_TABLE_198                                                         0x3f4ac
#define ixDPM_TABLE_199                                                         0x3f4b0
#define ixDPM_TABLE_200                                                         0x3f4b4
#define ixDPM_TABLE_201                                                         0x3f4b8
#define ixDPM_TABLE_202                                                         0x3f4bc
#define ixDPM_TABLE_203                                                         0x3f4c0
#define ixDPM_TABLE_204                                                         0x3f4c4
#define ixDPM_TABLE_205                                                         0x3f4c8
#define ixDPM_TABLE_206                                                         0x3f4cc
#define ixDPM_TABLE_207                                                         0x3f4d0
#define ixDPM_TABLE_208                                                         0x3f4d4
#define ixDPM_TABLE_209                                                         0x3f4d8
#define ixDPM_TABLE_210                                                         0x3f4dc
#define ixDPM_TABLE_211                                                         0x3f4e0
#define ixDPM_TABLE_212                                                         0x3f4e4
#define ixDPM_TABLE_213                                                         0x3f4e8
#define ixDPM_TABLE_214                                                         0x3f4ec
#define ixDPM_TABLE_215                                                         0x3f4f0
#define ixDPM_TABLE_216                                                         0x3f4f4
#define ixDPM_TABLE_217                                                         0x3f4f8
#define ixDPM_TABLE_218                                                         0x3f4fc
#define ixDPM_TABLE_219                                                         0x3f500
#define ixDPM_TABLE_220                                                         0x3f504
#define ixDPM_TABLE_221                                                         0x3f508
#define ixDPM_TABLE_222                                                         0x3f50c
#define ixDPM_TABLE_223                                                      