ST_FILTER_CNTL                                          0x1a99
#define mmDCP1_CUR_REQUEST_FILTER_CNTL                                          0x1c99
#define mmDCP2_CUR_REQUEST_FILTER_CNTL              