                             0x1ed7
#define mmLB3_LB_BUFFER_LEVEL_STATUS                                            0x40d7
#define mmLB4_LB_BUFFER_LEVEL_STATUS                                            0x42d7
#define mmLB5_LB_BUFFER_LEVEL_STATUS                                            0x44d7
#define mmLB_BUFFER_URGENCY_CTRL                                                0x1ad8
#define mmLB0_LB_BUFFER_URGENCY_CTRL                                            0x1ad8
#define mmLB1_LB_BUFFER_URGENCY_CTRL                                            0x1cd8
#define mmLB2_LB_BUFFER_URGENCY_CTRL                                            0x1ed8
#define mmLB3_LB_BUFFER_URGENCY_CTRL                                            0x40d8
#define mmLB4_LB_BUFFER_URGENCY_CTRL                                            0x42d8
#define mmLB5_LB_BUFFER_URGENCY_CTRL                                            0x44d8
#define mmLB_BUFFER_URGENCY_STATUS                                              0x1ad9
#define mmLB0_LB_BUFFER_URGENCY_STATUS                                          0x1ad9
#define mmLB1_LB_BUFFER_URGENCY_STATUS                                          0x1cd9
#define mmLB2_LB_BUFFER_URGENCY_STATUS                                          0x1ed9
#define mmLB3_LB_BUFFER_URGENCY_STATUS                                          0x40d9
#define mmLB4_LB_BUFFER_URGENCY_STATUS                                          0x42d9
#define mmLB5_LB_BUFFER_URGENCY_STATUS                                          0x44d9
#define mmLB_BUFFER_STATUS                                                      0x1ada
#define mmLB0_LB_BUFFER_STATUS                                                  0x1ada
#define mmLB1_LB_BUFFER_STATUS                                                  0x1cda
#define mmLB2_LB_BUFFER_STATUS                                                  0x1eda
#define mmLB3_LB_BUFFER_STATUS                                                  0x40da
#define mmLB4_LB_BUFFER_STATUS                                                  0x42da
#define mmLB5_LB_BUFFER_STATUS                                                  0x44da
#define mmLB_NO_OUTSTANDING_REQ_STATUS                                          0x1adc
#define mmLB0_LB_NO_OUTSTANDING_REQ_STATUS                                      0x1adc
#define mmLB1_LB_NO_OUTSTANDING_REQ_STATUS                                      0x1cdc
#define mmLB2_LB_NO_OUTSTANDING_REQ_STATUS                                      0x1edc
#define mmLB3_LB_NO_OUTSTANDING_REQ_STATUS                                      0x40dc
#define mmLB4_LB_NO_OUTSTANDING_REQ_STATUS                                      0x42dc
#define mmLB5_LB_NO_OUTSTANDING_REQ_STATUS                                      0x44dc
#define mmMVP_AFR_FLIP_MODE                                                     0x1ae0
#define mmLB0_MVP_AFR_FLIP_MODE                                                 0x1ae0
#define mmLB1_MVP_AFR_FLIP_MODE                                                 0x1ce0
#define mmLB2_MVP_AFR_FLIP_MODE                                                 0x1ee0
#define mmLB3_MVP_AFR_FLIP_MODE                                                 0x40e0
#define mmLB4_MVP_AFR_FLIP_MODE                                                 0x42e0
#define mmLB5_MVP_AFR_FLIP_MODE                                                 0x44e0
#define mmMVP_AFR_FLIP_FIFO_CNTL                                                0x1ae1
#define mmLB0_MVP_AFR_FLIP_FIFO_CNTL                                            0x1ae1
#define mmLB1_MVP_AFR_FLIP_FIFO_CNTL                                            0x1ce1
#define mmLB2_MVP_AFR_FLIP_FIFO_CNTL                                            0x1ee1
#define mmLB3_MVP_AFR_FLIP_FIFO_CNTL                                            0x40e1
#define mmLB4_MVP_AFR_FLIP_FIFO_CNTL                                            0x42e1
#define mmLB5_MVP_AFR_FLIP_FIFO_CNTL                                            0x44e1
#define mmMVP_FLIP_LINE_NUM_INSERT                                              0x1ae2
#define mmLB0_MVP_FLIP_LINE_NUM_INSERT                                          0x1ae2
#define mmLB1_MVP_FLIP_LINE_NUM_INSERT                                          0x1ce2
#define mmLB2_MVP_FLIP_LINE_NUM_INSERT                                          0x1ee2
#define mmLB3_MVP_FLIP_LINE_NUM_INSERT                                          0x40e2
#define mmLB4_MVP_FLIP_LINE_NUM_INSERT                                          0x42e2
#define mmLB5_MVP_FLIP_LINE_NUM_INSERT                                          0x44e2
#define mmDC_MVP_LB_CONTROL                                                     0x1ae3
#define mmLB0_DC_MVP_LB_CONTROL                                                 0x1ae3
#define mmLB1_DC_MVP_LB_CONTROL                                                 0x1ce3
#define mmLB2_DC_MVP_LB_CONTROL                                                 0x1ee3
#define mmLB3_DC_MVP_LB_CONTROL                                                 0x40e3
#define mmLB4_DC_MVP_LB_CONTROL                                                 0x42e3
#define mmLB5_DC_MVP_LB_CONTROL                                                 0x44e3
#define mmLB_DEBUG                                                              0x1ae4
#define mmLB0_LB_DEBUG                                                          0x1ae4
#define mmLB1_LB_DEBUG                                                          0x1ce4
#define mmLB2_LB_DEBUG                                                          0x1ee4
#define mmLB3_LB_DEBUG                                                          0x40e4
#define mmLB4_LB_DEBUG                                                          0x42e4
#define mmLB5_LB_DEBUG                                                          0x44e4
#define mmLB_DEBUG2                                                             0x1ae5
#define mmLB0_LB_DEBUG2                                                         0x1ae5
#define mmLB1_LB_DEBUG2                                                         0x1ce5
#define mmLB2_LB_DEBUG2                                                         0x1ee5
#define mmLB3_LB_DEBUG2                                                         0x40e5
#define mmLB4_LB_DEBUG2                                                         0x42e5
#define mmLB5_LB_DEBUG2                                                         0x44e5
#define mmLB_DEBUG3                                                             0x1ae6
#define mmLB0_LB_DEBUG3                                                         0x1ae6
#define mmLB1_LB_DEBUG3                                                         0x1ce6
#define mmLB2_LB_DEBUG3                                                         0x1ee6
#define mmLB3_LB_DEBUG3                                                         0x40e6
#define mmLB4_LB_DEBUG3                                                         0x42e6
#define mmLB5_LB_DEBUG3                                                         0x44e6
#define mmLB_TEST_DEBUG_INDEX                                                   0x1afe
#define mmLB0_LB_TEST_DEBUG_INDEX                                               0x1afe
#define mmLB1_LB_TEST_DEBUG_INDEX                                               0x1cfe
#define mmLB2_LB_TEST_DEBUG_INDEX                                               0x1efe
#define mmLB3_LB_TEST_DEBUG_INDEX                                               0x40fe
#define mmLB4_LB_TEST_DEBUG_INDEX                                               0x42fe
#define mmLB5_LB_TEST_DEBUG_INDEX                                               0x44fe
#define mmLB_TEST_DEBUG_DATA                                                    0x1aff
#define mmLB0_LB_TEST_DEBUG_DATA                                                0x1aff
#define mmLB1_LB_TEST_DEBUG_DATA                                                0x1cff
#define mmLB2_LB_TEST_DEBUG_DATA                                                0x1eff
#define mmLB3_LB_TEST_DEBUG_DATA                                                0x40ff
#define mmLB4_LB_TEST_DEBUG_DATA                                                0x42ff
#define mmLB5_LB_TEST_DEBUG_DATA                                                0x44ff
#define mmLBV_DATA_FORMAT                                                       0x463c
#define mmLBV_MEMORY_CTRL                                                       0x463d
#define mmLBV_MEMORY_SIZE_STATUS                                                0x463e
#define mmLBV_DESKTOP_HEIGHT                                                    0x463f
#define mmLBV_VLINE_START_END                                                   0x4640
#define mmLBV_VLINE2_START_END                                                  0x4641
#define mmLBV_V_COUNTER                                                         0x4642
#define mmLBV_SNAPSHOT_V_COUNTER                                                0x4643
#define mmLBV_V_COUNTER_CHROMA                                                  0x4644
#define mmLBV_SNAPSHOT_V_COUNTER_CHROMA                                         0x4645
#define mmLBV_INTERRUPT_MASK                                                    0x4646
#define mmLBV_VLINE_STATUS                                                      0x4647
#define mmLBV_VLINE2_STATUS                                                     0x4648
#define mmLBV_VBLANK_STATUS                                                     0x4649
#define mmLBV_SYNC_RESET_SEL                                                    0x464a
#define mmLBV_BLACK_KEYER_R_CR                                                  0x464b
#define mmLBV_BLACK_KEYER_G_Y                                                   0x464c
#define mmLBV_BLACK_KEYER_B_CB                                                  0x464d
#define mmLBV_KEYER_COLOR_CTRL                                                  0x464e
#define mmLBV_KEYER_COLOR_R_CR                                                  0x464f
#define mmLBV_KEYER_COLOR_G_Y                                                   0x4650
#define mmLBV_KEYER_COLOR_B_CB                                                  0x4651
#define mmLBV_KEYER_COLOR_REP_R_CR                                              0x4652
#define mmLBV_KEYER_COLOR_REP_G_Y                                               0x4653
#define mmLBV_KEYER_COLOR_REP_B_CB                                              0x4654
#define mmLBV_BUFFER_LEVEL_STATUS                                               0x4655
#define mmLBV_BUFFER_URGENCY_CTRL                                               0x4656
#define mmLBV_BUFFER_URGENCY_STATUS                                             0x4657
#define mmLBV_BUFFER_STATUS                                                     0x4658
#define mmLBV_NO_OUTSTANDING_REQ_STATUS                                         0x4659
#define mmLBV_DEBUG                                                             0x465a
#define mmLBV_DEBUG2                                                            0x465b
#define mmLBV_DEBUG3                                                            0x465c
#define mmLBV_TEST_DEBUG_INDEX                                                  0x4666
#define mmLBV_TEST_DEBUG_DATA                                                   0x4667
#define mmMVP_CONTROL1                                                          0x2ac
#define mmMVP_CONTROL2                                                          0x2ad
#define mmMVP_FIFO_CONTROL                                                      0x2ae
#define mmMVP_FIFO_STATUS                                                       0x2af
#define mmMVP_SLAVE_STATUS                                                      0x2b0
#define mmMVP_INBAND_CNTL_CAP                                                   0x2b1
#define mmMVP_BLACK_KEYER                                                       0x2b2
#define mmMVP_CRC_CNTL                                                          0x2b3
#define mmMVP_CRC_RESULT_BLUE_GREEN                                             0x2b4
#define mmMVP_CRC_RESULT_RED                                                    0x2b5
#define mmMVP_CONTROL3                                                          0x2b6
#define mmMVP_RECEIVE_CNT_CNTL1                                                 0x2b7
#define mmMVP_RECEIVE_CNT_CNTL2                                                 0x2b8
#define mmMVP_DEBUG                                                             0x2bb
#define mmMVP_TEST_DEBUG_INDEX                                                  0x2b9
#define mmMVP_TEST_DEBUG_DATA                                                   0x2ba
#define ixMVP_DEBUG_12                                                          0xc
#define ixMVP_DEBUG_13                                                          0xd
#define ixMVP_DEBUG_14                                                          0xe
#define ixMVP_DEBUG_15                                                          0xf
#define ixMVP_DEBUG_16                                                          0x10
#define ixMVP_DEBUG_17                                                          0x11
#define mmSCL_COEF_RAM_SELECT                                                   0x1b40
#define mmSCL0_SCL_COEF_RAM_SELECT                                              0x1b40
#define mmSCL1_SCL_COEF_RAM_SELECT                                              0x1d40
#define mmSCL2_SCL_COEF_RAM_SELECT                                              0x1f40
#define mmSCL3_SCL_COEF_RAM_SELECT                                              0x4140
#define mmSCL4_SCL_COEF_RAM_SELECT                                              0x4340
#define mmSCL5_SCL_COEF_RAM_SELECT                                              0x4540
#define mmSCL_COEF_RAM_TAP_DATA                                                 0x1b41
#define mmSCL0_SCL_COEF_RAM_TAP_DATA                                            0x1b41
#define mmSCL1_SCL_COEF_RAM_TAP_DATA                                            0x1d41
#define mmSCL2_SCL_COEF_RAM_TAP_DATA                                            0x1f41
#define mmSCL3_SCL_COEF_RAM_TAP_DATA                                            0x4141
#define mmSCL4_SCL_COEF_RAM_TAP_DATA                                            0x4341
#define mmSCL5_SCL_COEF_RAM_TAP_DATA                                            0x4541
#define mmSCL_MODE                                                              0x1b42
#define mmSCL0_SCL_MODE                                                         0x1b42
#define mmSCL1_SCL_MODE                                                         0x1d42
#define mmSCL2_SCL_MODE                                                         0x1f42
#define mmSCL3_SCL_MODE                                                         0x4142
#define mmSCL4_SCL_MODE                                                         0x4342
#define mmSCL5_SCL_MODE                                                         0x4542
#define mmSCL_TAP_CONTROL                                                       0x1b43
#define mmSCL0_SCL_TAP_CONTROL                                                  0x1b43
#define mmSCL1_SCL_TAP_CONTROL                                                  0x1d43
#define mmSCL2_SCL_TAP_CONTROL                                                  0x1f43
#define mmSCL3_SCL_TAP_CONTROL                                                  0x4143
#define mmSCL4_SCL_TAP_CONTROL                                                  0x4343
#define mmSCL5_SCL_TAP_CONTROL                                                  0x4543
#define mmSCL_CONTROL                                                           0x1b44
#define mmSCL0_SCL_CONTROL                                                      0x1b44
#define mmSCL1_SCL_CONTROL                                                      0x1d44
#define mmSCL2_SCL_CONTROL                                                      0x1f44
#define mmSCL3_SCL_CONTROL                                                      0x4144
#define mmSCL4_SCL_CONTROL                                                      0x4344
#define mmSCL5_SCL_CONTROL                                                      0x4544
#define mmSCL_BYPASS_CONTROL                                                    0x1b45
#define mmSCL0_SCL_BYPASS_CONTROL                                               0x1b45
#define mmSCL1_SCL_BYPASS_CONTROL                                               0x1d45
#define mmSCL2_SCL_BYPASS_CONTROL                                               0x1f45
#define mmSCL3_SCL_BYPASS_CONTROL                                               0x4145
#define mmSCL4_SCL_BYPASS_CONTROL                                               0x4345
#define mmSCL5_SCL_BYPASS_CONTROL                                               0x4545
#define mmSCL_MANUAL_REPLICATE_CONTROL                                          0x1b46
#define mmSCL0_SCL_MANUAL_REPLICATE_CONTROL                                     0x1b46
#define mmSCL1_SCL_MANUAL_REPLICATE_CONTROL                                     0x1d46
#define mmSCL2_SCL_MANUAL_REPLICATE_CONTROL                                     0x1f46
#define mmSCL3_SCL_MANUAL_REPLICATE_CONTROL                                     0x4146
#define mmSCL4_SCL_MANUAL_REPLICATE_CONTROL                                     0x4346
#define mmSCL5_SCL_MANUAL_REPLICATE_CONTROL                                     0x4546
#define mmSCL_AUTOMATIC_MODE_CONTROL                                            0x1b47
#define mmSCL0_SCL_AUTOMATIC_MODE_CONTROL                                       0x1b47
#define mmSCL1_SCL_AUTOMATIC_MODE_CONTROL                                       0x1d47
#define mmSCL2_SCL_AUTOMATIC_MODE_CONTROL                                       0x1f47
#define mmSCL3_SCL_AUTOMATIC_MODE_CONTROL                                       0x4147
#define mmSCL4_SCL_AUTOMATIC_MODE_CONTROL                                       0x4347
#define mmSCL5_SCL_AUTOMATIC_MODE_CONTROL                                       0x4547
#define mmSCL_HORZ_FILTER_CONTROL                                               0x1b48
#define mmSCL0_SCL_HORZ_FILTER_CONTROL                                          0x1b48
#define mmSCL1_SCL_HORZ_FILTER_CONTROL                                          0x1d48
#define mmSCL2_SCL_HORZ_FILTER_CONTROL                                          0x1f48
#define mmSCL3_SCL_HORZ_FILTER_CONTROL                                          0x4148
#define mmSCL4_SCL_HORZ_FILTER_CONTROL                                          0x4348
#define mmSCL5_SCL_HORZ_FILTER_CONTROL                                          0x4548
#define mmSCL_HORZ_FILTER_SCALE_RATIO                                           0x1b49
#define mmSCL0_SCL_HORZ_FILTER_SCALE_RATIO                                      0x1b49
#define mmSCL1_SCL_HORZ_FILTER_SCALE_RATIO                                      0x1d49
#define mmSCL2_SCL_HORZ_FILTER_SCALE_RATIO                                      0x1f49
#define mmSCL3_SCL_HORZ_FILTER_SCALE_RATIO                                      0x4149
#define mmSCL4_SCL_HORZ_FILTER_SCALE_RATIO                                      0x4349
#define mmSCL5_SCL_HORZ_FILTER_SCALE_RATIO                                      0x4549
#define mmSCL_HORZ_FILTER_INIT                                                  0x1b4a
#define mmSCL0_SCL_HORZ_FILTER_INIT                                             0x1b4a
#define mmSCL1_SCL_HORZ_FILTER_INIT                                             0x1d4a
#define mmSCL2_SCL_HORZ_FILTER_INIT                                             0x1f4a
#define mmSCL3_SCL_HORZ_FILTER_INIT                                             0x414a
#define mmSCL4_SCL_HORZ_FILTER_INIT                                             0x434a
#define mmSCL5_SCL_HORZ_FILTER_INIT                                             0x454a
#define mmSCL_VERT_FILTER_CONTROL                                               0x1b4b
#define mmSCL0_SCL_VERT_FILTER_CONTROL                                          0x1b4b
#define mmSCL1_SCL_VERT_FILTER_CONTROL                                          0x1d4b
#define mmSCL2_SCL_VERT_FILTER_CONTROL                                          0x1f4b
#define mmSCL3_SCL_VERT_FILTER_CONTROL                                          0x414b
#define mmSCL4_SCL_VERT_FILTER_CONTROL                                          0x434b
#define mmSCL5_SCL_VERT_FILTER_CONTROL                                          0x454b
#define mmSCL_VERT_FILTER_SCALE_RATIO                                           0x1b4c
#define mmSCL0_SCL_VERT_FILTER_SCALE_RATIO                                      0x1b4c
#define mmSCL1_SCL_VERT_FILTER_SCALE_RATIO                                      0x1d4c
#define mmSCL2_SCL_VERT_FILTER_SCALE_RATIO                                      0x1f4c
#define mmSCL3_SCL_VERT_FILTER_SCALE_RATIO                                      0x414c
#define mmSCL4_SCL_VERT_FILTER_SCALE_RATIO                                      0x434c
#define mmSCL5_SCL_VERT_FILTER_SCALE_RATIO                                      0x454c
#define mmSCL_VERT_FILTER_INIT                      