ee
#define mmFMT4_FMT_CONTROL                                                      0x43ee
#define mmFMT5_FMT_CONTROL                                                      0x45ee
#define mmFMT_BIT_DEPTH_CONTROL                                                 0x1bf2
#define mmFMT0_FMT_BIT_DEPTH_CONTROL                                            0x1bf2
#define mmFMT1_FMT_BIT_DEPTH_CONTROL                                            0x1df2
#define mmFMT2_FMT_BIT_DEPTH_CONTROL                                            0x1ff2
#define mmFMT3_FMT_BIT_DEPTH_CONTROL                                            0x41f2
#define mmFMT4_FMT_BIT_DEPTH_CONTROL                                            0x43f2
#define mmFMT5_FMT_BIT_DEPTH_CONTROL                                            0x45f2
#define mmFMT_DITHER_RAND_R_SEED                                                0x1bf3
#define mmFMT0_FMT_DITHER_RAND_R_SEED                                           0x1bf3
#define mmFMT1_FMT_DITHER_RAND_R_SEED                                           0x1df3
#define mmFMT2_FMT_DITHER_RAND_R_SEED                                           0x1ff3
#define mmFMT3_FMT_DITHER_RAND_R_SEED                                           0x41f3
#define mmFMT4_FMT_DITHER_RAND_R_SEED                                           0x43f3
#define mmFMT5_FMT_DITHER_RAND_R_SEED                                           0x45f3
#define mmFMT_DITHER_RAND_G_SEED                                                0x1bf4
#define mmFMT0_FMT_DITHER_RAND_G_SEED                                           0x1bf4
#define mmFMT1_FMT_DITHER_RAND_G_SEED                                           0x1df4
#define mmFMT2_FMT_DITHER_RAND_G_SEED                                           0x1ff4
#define mmFMT3_FMT_DITHER_RAND_G_SEED                                           0x41f4
#define mmFMT4_FMT_DITHER_RAND_G_SEED                                           0x43f4
#define mmFMT5_FMT_DITHER_RAND_G_SEED                                           0x45f4
#define mmFMT_DITHER_RAND_B_SEED                                                0x1bf5
#define mmFMT0_FMT_DITHER_RAND_B_SEED                                           0x1bf5
#define mmFMT1_FMT_DITHER_RAND_B_SEED                                           0x1df5
#define mmFMT2_FMT_DITHER_RAND_B_SEED                                           0x1ff5
#define mmFMT3_FMT_DITHER_RAND_B_SEED                                           0x41f5
#define mmFMT4_FMT_DITHER_RAND_B_SEED                                           0x43f5
#define mmFMT5_FMT_DITHER_RAND_B_SEED                                           0x45f5
#define mmFMT_TEMPORAL_DITHER_PATTERN_CONTROL                                   0x1bf6
#define mmFMT0_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x1bf6
#define mmFMT1_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x1df6
#define mmFMT2_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x1ff6
#define mmFMT3_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x41f6
#define mmFMT4_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x43f6
#define mmFMT5_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x45f6
#define mmFMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                     0x1bf7
#define mmFMT0_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x1bf7
#define mmFMT1_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x1df7
#define mmFMT2_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x1ff7
#define mmFMT3_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x41f7
#define mmFMT4_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x43f7
#define mmFMT5_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x45f7
#define mmFMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                     0x1bf8
#define mmFMT0_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                0x1bf8
#define mmFMT1_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                0x1df8
#define mmFMT2_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                0x1ff8
#define mmFMT3_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                0x41f8
#define mmFMT4_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                0x43f8
#define mmFMT5_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_T_MATRIX                0x45f8
#define mmFMT_CLAMP_CNTL                                                        0x1bf9
#define mmFMT0_FMT_CLAMP_CNTL                                                   0x1bf9
#define mmFMT1_FMT_CLAMP_CNTL                                                   0x1df9
#define mmFMT2_FMT_CLAMP_CNTL                                                   0x1ff9
#define mmFMT3_FMT_CLAMP_CNTL                                                   0x41f9
#define mmFMT4_FMT_CLAMP_CNTL                                                   0x43f9
#define mmFMT5_FMT_CLAMP_CNTL                                                   0x45f9
#define mmFMT_CRC_CNTL                                                          0x1bfa
#define mmFMT0_FMT_CRC_CNTL                                                     0x1bfa
#define mmFMT1_FMT_CRC_CNTL                                                     0x1dfa
#define mmFMT2_FMT_CRC_CNTL                                                     0x1ffa
#define mmFMT3_FMT_CRC_CNTL                                                     0x41fa
#define mmFMT4_FMT_CRC_CNTL                                                     0x43fa
#define mmFMT5_FMT_CRC_CNTL                                                     0x45fa
#define mmFMT_CRC_SIG_RED_GREEN_MASK                                            0x1bfb
#define mmFMT0_FMT_CRC_SIG_RED_GREEN_MASK                                       0x1bfb
#define mmFMT1_FMT_CRC_SIG_RED_GREEN_MASK                                       0x1dfb
#define mmFMT2_FMT_CRC_SIG_RED_GREEN_MASK                                       0x1ffb
#define mmFMT3_FMT_CRC_SIG_RED_GREEN_MASK                                       0x41fb
#define mmFMT4_FMT_CRC_SIG_RED_GREEN_MASK                                      