MT0_FMT_DEBUG_CNTL                                                   0x1bff
#define mmFMT1_FMT_DEBUG_CNTL                                                   0x1dff
#define mmFMT2_FMT_DEBUG_CNTL                                                   0x1fff
#define mmFMT3_FMT_DEBUG_CNTL                                                   0x41ff
#define mmFMT4_FMT_DEBUG_CNTL                                                   0x43ff
#define mmFMT5_FMT_DEBUG_CNTL                                                   0x45ff
#define mmFMT_TEST_DEBUG_INDEX                                                  0x1beb
#define mmFMT0_FMT_TEST_DEBUG_INDEX                                             0x1beb
#define mmFMT1_FMT_TEST_DEBUG_INDEX                                             0x1deb
#define mmFMT2_FMT_TEST_DEBUG_INDEX                                             0x1feb
#define mmFMT3_FMT_TEST_DEBUG_INDEX                                             0x41eb
#define mmFMT4_FMT_TEST_DEBUG_INDE