                           0x4f7b
#define mmDIG6_DIG_TEST_DEBUG_DATA                                              0x547b
#define mmDIG7_DIG_TEST_DEBUG_DATA                                              0x567b
#define mmDIG8_DIG_TEST_DEBUG_DATA                                              0x577b
#define mmDIG_FE_TEST_DEBUG_INDEX                                               0x4a7c
#define mmDIG0_DIG_FE_TEST_DEBUG_INDEX                                          0x4a7c
#define mmDIG1_DIG_FE_TEST_DEBUG_INDEX                                          0x4b7c
#define mmDIG2_DIG_FE_TEST_DEBUG_INDEX                                          0x4c7c
#define mmDIG3_DIG_FE_TEST_DEBUG_INDEX                                          0x4d7c
#define mmDIG4_DIG_FE_TEST_DEBUG_INDEX                                          0x4e7c
#define mmDIG5_DIG_FE_TEST_DEBUG_INDEX                                          0x4f7c
#define mmDIG6_DIG_FE_TEST_DEBUG_INDEX                                          0x547c
#define mmDIG7_DIG_FE_TEST_DEBUG_INDEX                                          0x567c
#define mmDIG8_DIG_FE_TEST_DEBUG_INDEX                                          0x577c
#define mmDIG_FE_TEST_DEBUG_DATA                                                0x4a7d
#define mmDIG0_DIG_FE_TEST_DEBUG_DATA                                           0x4a7d
#define mmDIG1_DIG_FE_TEST_DEBUG_DATA                                           0x4b7d
#define mmDIG2_DIG_FE_TEST_DEBUG_DATA                                           0x4c7d
#define mmDIG3_DIG_FE_TEST_DEBUG_DATA                                           0x4d7d
#define mmDIG4_DIG_FE_TEST_DEBUG_DATA                                           0x4e7d
#define mmDIG5_DIG_FE_TEST_DEBUG_DATA                                           0x4f7d
#define mmDIG6_DIG_FE_TEST_DEBUG_DATA                                           0x547d
#define mmDIG7_DIG_FE_TEST_DEBUG_DATA                                           0x567d
#define mmDIG8_DIG_FE_TEST_DEBUG_DATA                                           0x577d
#define mmDMCU_CTRL                                                             0x1600
#define mmDMCU_STATUS                                                           0x1601
#define mmDMCU_PC_START_ADDR                                                    0x1602
#define mmDMCU_FW_START_ADDR                                                    0x1603
#define mmDMCU_FW_END_ADDR                                                      0x1604
#define mmDMCU_FW_ISR_START_ADDR                                                0x1605
#define mmDMCU_FW_CS_HI                                                         0x1606
#define mmDMCU_FW_CS_LO                                                         0x1607
#define mmDMCU_RAM_ACCESS_CTRL                                                  0x1608
#define mmDMCU_ERAM_WR_CTRL                                                     0x1609
#define mmDMCU_ERAM_WR_DATA                                                     0x160a
#define mmDMCU_ERAM_RD_CTRL                                                     0x160b
#define mmDMCU_ERAM_RD_DATA                                                     0x160c
#define mmDMCU_IRAM_WR_CTRL                                                     0x160d
#define mmDMCU_IRAM_WR_DATA                                                     0x160e
#define mmDMCU_IRAM_RD_CTRL                                                     0x160f
#define mmDMCU_IRAM_RD_DATA                                                     0x1610
#define mmDMCU_EVENT_TRIGGER                                                    0x1611
#define mmDMCU_UC_INTERNAL_INT_STATUS                                           0x1612
#define mmDMCU_SS_INTERRUPT_CNTL_STATUS                                         0x1613
#define mmDMCU_INTERRUPT_STATUS                                                 0x1614
#define mmDMCU_INTERRUPT_TO_HOST_EN_MASK                                        0x1615
#define mmDMCU_INTERRUPT_TO_UC_EN_MASK                                          0x1616
#define mmDMCU_INTERRUPT_TO_UC_EN_MASK_1                                        0x1631
#define mmDMCU_INTERRUPT_TO_UC_XIRQ_IRQ_SEL                                     0x1617
#define mmDMCU_INTERRUPT_TO_UC_XIRQ_IRQ_SEL_1                                   0x1632
#define mmDC_DMCU_SCRATCH                                                       0x1618
#define mmDMCU_INT_CNT                                                          0x1619
#define mmDMCU_FW_CHECKSUM_SMPL_BYTE_POS                                        0x161a
#define mmDMCU_UC_CLK_GATING_CNTL                                               0x161b
#define mmMASTER_COMM_DATA_REG1                                                 0x161c
#define mmMASTER_COMM_DATA_REG2                                                 0x161d
#define mmMASTER_COMM_DATA_REG3                                                 0x161e
#define mmMASTER_COMM_CMD_REG                                                   0x161f
#define mmMASTER_COMM_CNTL_REG                                                  0x1620
#define mmSLAVE_COMM_DATA_REG1                                                  0x1621
#define mmSLAVE_COMM_DATA_REG2                                                  0x1622
#define mmSLAVE_COMM_DATA_REG3                                                  0x1623
#define mmSLAVE_COMM_CMD_REG                                                    0x1624
#define mmSLAVE_COMM_CNTL_REG                                                   0x1625
#define mmDMCU_TEST_DEBUG_INDEX                                                 0x1626
#define mmDMCU_TEST_DEBUG_DATA                                                  0x1627
#define mmDMCU_PERFMON_INTERRUPT_STATUS1                                        0x1644
#define mmDMCU_PERFMON_INTERRUPT_STATUS2                                        0x1645
#define mmDMCU_PERFMON_INTERRUPT_STATUS3                                        0x1646
#define mmDMCU_PERFMON_INTERRUPT_STATUS4                                        0x1647
#define mmDMCU_PERFMON_INTERRUPT_STATUS5                                        0x1642
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK1                                 0x1674
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK2                                 0x1675
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK3                                 0x1676
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK4                                 0x1677
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK5                                 0x1643
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL1                            0x1678
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL2                            0x1679
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL3                            0x167a
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL4                            0x167b
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL5                            0x1673
#define mmDMCU_DPRX_INTERRUPT_STATUS1                                           0x1634
#define mmDMCU_DPRX_INTERRUPT_TO_UC_EN_MASK1                                    0x1635
#define mmDMCU_DPRX_INTERRUPT_TO_UC_XIRQ_IRQ_SEL1                               0x1636
#define mmDP_LINK_CNTL                                                          0x4aa0
#define mmDP0_DP_LINK_CNTL                                                      0x4aa0
#define mmDP1_DP_LINK_CNTL                                                      0x4ba0
#define mmDP2_DP_LINK_CNTL                                                      0x4ca0
#define mmDP3_DP_LINK_CNTL                                                      0x4da0
#define mmDP4_DP_LINK_CNTL                                                      0x4ea0
#define mmDP5_DP_LINK_CNTL                                                      0x4fa0
#define mmDP6_DP_LINK_CNTL                                                      0x54a0
#define mmDP7_DP_LINK_CNTL                                                      0x56a0
#define mmDP8_DP_LINK_CNTL                                                      0x57a0
#define mmDP_PIXEL_FORMAT                                                       0x4aa1
#define mmDP0_DP_PIXEL_FORMAT                                                   0x4aa1
#define mmDP1_DP_PIXEL_FORMAT                                                   0x4ba1
#define mmDP2_DP_PIXEL_FORMAT                                                   0x4ca1
#define mmDP3_DP_PIXEL_FORMAT                                                   0x4da1
#define mmDP4_DP_PIXEL_FORMAT                                                   0x4ea1
#define mmDP5_DP_PIXEL_FORMAT                                                   0x4fa1
#define mmDP6_DP_PIXEL_FORMAT                                                   0x54a1
#define mmDP7_DP_PIXEL_FORMAT                                                   0x56a1
#define mmDP8_DP_PIXEL_FORMAT                                                   0x57a1
#define mmDP_MSA_COLORIMETRY                                                    0x4aa2
#define mmDP0_DP_MSA_COLORIMETRY                                                0x4aa2
#define mmDP1_DP_MSA_COLORIMETRY                                                0x4ba2
#define mmDP2_DP_MSA_COLORIMETRY                                                0x4ca2
#define mmDP3_DP_MSA_COLORIMETRY                                                0x4da2
#define mmDP4_DP_MSA_COLORIMETRY                                                0x4ea2
#define mmDP5_DP_MSA_COLORIMETRY                                                0x4fa2
#define mmDP6_DP_MSA_COLORIMETRY                                                0x54a2
#define mmDP7_DP_MSA_COLORIMETRY                                                0x56a2
#define mmDP8_DP_MSA_COLORIMETRY                                                0x57a2
#define mmDP_CONFIG                                                             0x4aa3
#define mmDP0_DP_CONFIG                                                         0x4aa3
#define mmDP1_DP_CONFIG                                                         0x4b