x4dab
#define mmDP4_DP_LINK_FRAMING_CNTL                                              0x4eab
#define mmDP5_DP_LINK_FRAMING_CNTL                                              0x4fab
#define mmDP6_DP_LINK_FRAMING_CNTL                                              0x54ab
#define mmDP7_DP_LINK_FRAMING_CNTL                                              0x56ab
#define mmDP8_DP_LINK_FRAMING_CNTL                                              0x57ab
#define mmDP_HBR2_EYE_PATTERN                                                   0x4aac
#define mmDP0_DP_HBR2_EYE_PATTERN                                               0x4aac
#define mmDP1_DP_HBR2_EYE_PATTERN                                               0x4bac
#define mmDP2_DP_HBR2_EYE_PATTERN                                               0x4cac
#define mmDP3_DP_HBR2_EYE_PATTERN                                               0x4dac
#define mmDP4_DP_HBR2_EYE_PATTERN                                               0x4eac
#define mmDP5_DP_HBR2_EYE_PATTERN                                               0x4fac
#define mmDP6_DP_HBR2_EYE_PATTERN                                               0x54ac
#define mmDP7_DP_HBR2_EYE_PATTERN                                               0x56ac
#define mmDP8_DP_HBR2_EYE_PATTERN                                               0x57ac
#define mmDP_VID_MSA_VBID                                                       0x4aad
#define mmDP0_DP_VID_MSA_VBID                                                   0x4aad
#define mmDP1_DP_VID_MSA_VBID                                                   0x4bad
#define mmDP2_DP_VID_MSA_VBID                                                   0x4cad
#define mmDP3_DP_VID_MSA_VBID                                                   0x4dad
#define mmDP4_DP_VID_MSA_VBID                                                   0x4ead
#define mmDP5_DP_VID_MSA_VBID                                                   0x4fad
#define mmDP6_DP_VID_MSA_VBID                                                   0x54ad
#define mmDP7_DP_VID_MSA_VBID                                                   0x56ad
#define mmDP8_DP_VID_MSA_VBID                                                   0x57ad
#define mmDP_VID_INTERRUPT_CNTL                                                 0x4aae
#define mmDP0_DP_VID_INTERRUPT_CNTL                                             0x4aae
#define mmDP1_DP_VID_INTERRUPT_CNTL                                             0x4bae
#define mmDP2_DP_VID_INTERRUPT_CNTL                                             0x4cae
#define mmDP3_DP_VID_INTERRUPT_CNTL                                             0x4dae
#define mmDP4_DP_VID_INTERRUPT_CNTL                                             0x4eae
#define mmDP5_DP_VID_INTERRUPT_CNTL                                             0x4fae
#define mmDP6_DP_VID_INTERRUPT_CNTL                                             0x54ae
#define mmDP7_DP_VID_INTERRUPT_CNTL                                             0x56ae
#define mmDP8_DP_VID_INTERRUPT_CNTL                                             0x57ae
#define mmDP_DPHY_CNTL                                                          0x4aaf
#define mmDP0_DP_DPHY_CNTL                                                      0x4aaf
#define mmDP1_DP_DPHY_CNTL                                                      0x4baf
#define mmDP2_DP_DPHY_CNTL                                                      0x4caf
#define mmDP3_DP_DPHY_CNTL                                                      0x4daf
#define mmDP4_DP_DPHY_CNTL                                                      0x4eaf
#define mmDP5_DP_DPHY_CNTL                                                      0x4faf
#define mmDP6_DP_DPHY_CNTL                                                      0x54af
#define mmDP7_DP_DPHY_CNTL                                                      0x56af
#define mmDP8_DP_DPHY_CNTL                                                      0x57af
#define mmDP_DPHY_TRAINING_PATTERN_SEL                                          0x4ab0
#define mmDP0_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4ab0
#define mmDP1_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4bb0
#define mmDP2_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4cb0
#define mmDP3_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4db0
#define mmDP4_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4eb0
#define mmDP5_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4fb0
#define mmDP6_DP_DPHY_TRAINING_PATTERN_SEL                                      0x54b0
#define mmDP7_DP_DPHY_TRAINING_PATTERN_SEL                                      0x56b0
#define mmDP8_DP_DPHY_TRAINING_PATTERN_SEL                                      0x57b0
#define mmDP_DPHY_SYM0                                                          0x4ab1
#define mmDP0_DP_DPHY_SYM0                                                      0x4ab1
#define mmDP1_DP_DPHY_SYM0                                                      0x4bb1
#define mmDP2_DP_DPHY_SYM0                                                      0x4cb1
#define mmDP3_DP_DPHY_SYM0                                                      0x4db1
#define mmDP4_DP_DPHY_SYM0                                                      0x4eb1
#define mmDP5_DP_DPHY_SYM0                                                      0x4fb1
#define mmDP6_DP_DPHY_SYM0                                                      0x54b1
#define mmDP7_DP_DPHY_SYM0                                                      0x56b1
#define mmDP8_DP_DPHY_SYM0                                                      0x57b1
#define mmDP_DPHY_SYM1                                                          0x4ab2
#define mmDP0_DP_DPHY_SYM1                                                      0x4ab2
#define mmDP1_DP_DPHY_SYM1                                                      0x4bb2
#define mmDP2_DP_DPHY_SYM1                                                      0x4cb2
#define mmDP3_DP_DPHY_SYM1                                                      0x4db2
#define mmDP4_DP_DPHY_SYM1                                                      0x4eb2
#define mmDP5_DP_DPHY_SYM1                                                      0x4fb2
#define mmDP6_DP_DPHY_SYM1                                                      0x54b2
#define mmDP7_DP_DPHY_SYM1                                                      0x56b2
#define mmDP8_DP_DPHY_SYM1                                                      0x57b2
#define mmDP_DPHY_SYM2                                                          0x4ab3
#define mmDP0_DP_DPHY_SYM2                                                      0x4ab3
#define mmDP1_DP_DPHY_SYM2                                                      0x4bb3
#define mmDP2_DP_DPHY_SYM2                                                      0x4cb3
#define mmDP3_DP_DPHY_SYM2                                                      0x4db3
#define mmDP4_DP_DPHY_SYM2                                                      0x4eb3
#define mmDP5_DP_DPHY_SYM2                                                      0x4fb3
#define mmDP6_DP_DPHY_SYM2                                                      0x54b3
#define mmDP7_DP_DPHY_SYM2                                                      0x56b3
#define mmDP8_DP_DPHY_SYM2                                                      0x57b3
#define mmDP_DPHY_8B10B_CNTL                                                    0x4ab4
#define mmDP0_DP_DPHY_8B10B_CNTL                                                0x4ab4
#define mmDP1_DP_DPHY_8B10B_CNTL                                                0x4bb4
#define mmDP2_DP_DPHY_8B10B_CNTL                                                0x4cb4
#define mmDP3_DP_DPHY_8B10B_CNTL                                                0x4db4
#define mmDP4_DP_DPHY_8B10B_CNTL                                                0x4eb4
#define mmDP5_DP_DPHY_8B10B_CNTL                                                0x4fb4
#define mmDP6_DP_DPHY_8B10B_CNTL                                                0x54b4
#define mmDP7_DP_DPHY_8B10B_CNTL                                                0x56b4
#define mmDP8_DP_DPHY_8B10B_CNTL                                                0x57b4
#define mmDP_DPHY_PRBS_CNTL                                                     0x4ab5
#define mmDP0_DP_DPHY_PRBS_CNTL                                                 0x4ab5
#define mmDP1_DP_DPHY_PRBS_CNTL                                                 0x4bb5
#define mmDP2_DP_DPHY_PRBS_CNTL                                                 0x4cb5
#define mmDP3_DP_DPHY_PRBS_CNTL                                                 0x4db5
#define mmDP4_DP_DPHY_PRBS_CNTL                                                 0x4eb5
#define mmDP5_DP_DPHY_PRBS_CNTL                                                 0x4fb5
#define mmDP6_DP_DPHY_PRBS_CNTL                                                 0x54b5
#define mmDP7_DP_DPHY_PRBS_CNTL                                                 0x56b5
#define mmDP8_DP_DPHY_PRBS_CNTL                                                 0x57b5
#define mmDP_DPHY_BS_SR_SWAP_CNTL                                               0x4adc
#define mmDP0_DP_DPHY_BS_SR_SWAP_CNTL                                           0x4adc
#define mmDP1_DP_DPHY_BS_SR_SWAP_CNTL                                           0x4bdc
#define mmDP2_DP_DPHY_BS_SR_SWAP_CNTL                                           0x4cdc
#define mmDP3_DP_DPHY_BS_SR_SWAP_CNTL                                           0x4ddc
#define mmDP4_DP_DPHY_BS_SR_SWAP_CNTL                                           0x4edc
#define mmDP5_DP_DPHY_BS_SR_SWAP_CNTL                                           0x4fdc
#define mmDP6_DP_DPHY_BS_SR_SWAP_CNTL                                           0x54dc
#define mmDP7_DP_DPHY_BS_SR_SWAP_CNTL                                           0x56dc
#define mmDP8_DP_DPHY_BS_SR_SWAP_CNTL                                           0x57dc
#define mmDP_DPHY_CRC_EN                                                        0x4ab7
#define mmDP0_DP_DPHY_CRC_EN                                                    0x4ab7
#define mmDP1_DP_DPHY_CRC_EN                                                    0x4bb7
#define mmDP2_DP_DPHY_CRC_EN                                                    0x4cb7
#define mmDP3_DP_DPHY_CRC_EN                                                    0x4db7
#define mmDP4_DP_DPHY_CRC_EN                                                    0x4eb7
#define mmDP5_DP_DPHY_CRC_EN                                                    0x4fb7
#define mmDP6_DP_DPHY_CRC_EN                                                    0x54b7
#define mmDP7_DP_DPHY_CRC_EN                                                    0x56b7
#define mmDP8_DP_DPHY_CRC_EN                                                    0x57b7
#define mmDP_DPHY_CRC_CNTL                                                      0x4ab8
#define mmDP0_DP_DPHY_CRC_CNTL                                                  0x4ab8
#define mmDP1_DP_DPHY_CRC_CNTL                                                  0x4bb8
#define mmDP2_DP_DPHY_CRC_CNTL                                                  0x4cb8
#define mmDP3_DP_DPHY_CRC_CNTL                                                  0x4db8
#define mmDP4_DP_DPHY_CRC_CNTL                                                  0x4eb8
#define mmDP5_DP_DPHY_CRC_CNTL                                                  0x4fb8
#define mmDP6_DP_DPHY_CRC_CNTL                                                  0x54b8
#define mmDP7_DP_DPHY_CRC_CNTL                                                  0x56b8
#define mmDP8_DP_DPHY_CRC_CNTL                                                  0x57b8
#define mmDP_DPHY_CRC_RESULT                                                    0x4ab9
#define mmDP0_DP_DPHY_CRC_RESULT                                                0x4ab9
#define mmDP1_DP_DPHY_CRC_RESULT                                                0x4bb9
#define mmDP2_DP_DPHY_CRC_RESULT                                                0x4cb9
#define mmDP3_DP_DPHY_CRC_RESULT                                                0x4db9
#define mmDP4_DP_DPHY_CRC_RESULT                                                0x4eb9
#define mmDP5_DP_DPHY_CRC_RESULT                                                0x4fb9
#define mmDP6_DP_DPHY_CRC_RESULT                                                0x54b9
#define mmDP7_DP_DPHY_CRC_RESULT                                                0x56b9
#define mmDP8_DP_DPHY_CRC_RESULT                                                0x57b9
#define mmDP_DPHY_CRC_MST_CNTL                                                  0x4aba
#define mmDP0_DP_DPHY_CRC_MST_CNTL                                              0x4aba
#define mmDP1_DP_DPHY_CRC_MST_CNTL                                              0x4bba
#define mmDP2_DP_DPHY_CRC_MST_CNTL                                              0x4cba
#define mmDP3_DP_DPHY_CRC_MST_CNTL                                              0x4dba
#define mmDP4_DP_DPHY_CRC_MST_CNTL                                              0x4eba
#define mmDP5_DP_DPHY_CRC_MST_CNTL                                              0x4fba
#define mmDP6_DP_DPHY_CRC_MST_CNTL                                              0x54ba
#define mmDP7_DP_DPHY_CRC_MST_CNTL                                              0x56ba
#define mmDP8_DP_DPHY_CRC_MST_CNTL                                              0x57ba
#define mmDP_DPHY_CRC_MST_STATUS                                                0x4abb
#define mmDP0_DP_DPHY_CRC_MST_STATUS                                            0x4abb
#define mmDP1_DP_DPHY_CRC_MST_STATUS                                            0x4bbb
#define mmDP2_DP_DPHY_CRC_MST_STATUS                                            0x4cbb
#define mmDP3_DP_DPHY_CRC_MST_STATUS                                            0x4dbb
#define mmDP4_DP_DPHY_CRC_MST_STATUS                                            0x4ebb
#define mmDP5_DP_DPHY_CRC_MST_STATUS                                            0x4fbb
#define mmDP6_DP_DPHY_CRC_MST_STATUS                                            0x54bb
#define mmDP7_DP_DPHY_CRC_MST_STATUS                                            0x56bb
#define mmDP8_DP_DPHY_CRC_MST_STATUS                                            0x57bb
#define mmDP_DPHY_FAST_TRAINING                                                 0x4abc
#define mmDP0_DP_DPHY_FAST_TRAINING                                             0x4abc
#define mmDP1_DP_DPHY_FAST_TRAINING                                             0x4bbc
#define mmDP2_DP_DPHY_FAST_TRAINING                                             0x4cbc
#define mmDP3_DP_DPHY_FAST_TRAINING                                             0x4dbc
#define mmDP4_DP_DPHY_FAST_TRAINING                                             0x4ebc
#define mmDP5_DP_DPHY_FAST_TRAINING                                             0x4fbc
#define mmDP6_DP_DPHY_FAST_TRAINING                                             0x54bc
#define mmDP7_DP_DPHY_FAST_TRAINING                                             0x56bc
#define mmDP8_DP_DPHY_FAST_TRAINING                                             0x57bc
#define mmDP_DPHY_FAST_TRAINING_STATUS                                          0x4abd
#define mmDP0_DP_DPHY_FAST_TRAINING_STATUS                                      0x4abd
#define mmDP1_DP_DPHY_FAST_TRAINING_STATUS                                      0x4bbd
#define mmDP2_DP_DPHY_FAST_TRAINING_STATUS                                      0x4cbd
#define mmDP3_DP_DPHY_FAST_TRAINING_STATUS                                      0x4dbd
#define mmDP4_DP_DPHY_FAST_TRAINING_STATUS                                      0x4ebd
#define mmDP5_DP_DPHY_FAST_TRAINING_STATUS                                      0x4fbd
#define mmDP6_DP_DPHY_FAST_TRAINING_STATUS                                      0x54bd
#define mmDP7_DP_DPHY_FAST_TRAINING_STATUS                                      0x56bd
#define mmDP8_DP_DPHY_FAST_TRAINING_STATUS                                      0x57bd
#define mmDP_DPHY_HBR2_PATTERN_CONTROL                                          0x4add
#define mmDP0_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x4add
#define mmDP1_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x4bdd
#define mmDP2_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x4cdd
#define mmDP3_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x4ddd
#define mmDP4_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x4edd
#define mmDP5_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x4fdd
#define mmDP6_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x54dd
#define mmDP7_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x56dd
#define mmDP8_DP_DPHY_HBR2_PATTERN_CONTROL                                      0x57dd
#define mmDP_MSA_V_TIMING_OVERRIDE1                                             0x4abe
#define mmDP0_DP_MSA_V_TIMING_OVERRIDE1                                         0x4abe
#define mmDP1_DP_MSA_V_TIMING_OVERRIDE1                                         0x4bbe
#define mmDP2_DP_MSA_V_TIMING_OVERRIDE1                                         0x4cbe
#define mmDP3_DP_MSA_V_TIMING_OVERRIDE1                                         0x4dbe
#define mmDP4_DP_MSA_V_TIMING_OVERRIDE1                                         0x4ebe
#define mmDP5_DP_MSA_V_TIMING_OVERRIDE1                                         0x4fbe
#define mmDP6_DP_MSA_V_TIMING_OVERRIDE1                                         0x54be
#define mmDP7_DP_MSA_V_TIMING_OVERRIDE1                                         0x56be
#define mmDP8_DP_MSA_V_TIMING_OVERRIDE1                                         0x57be
#define mmDP_MSA_V_TIMING_OVERRIDE2                                             0x4abf
#define mmDP0_DP_MSA_V_TIMING_OVERRIDE2                                         0x4abf
#define mmDP1_DP_MSA_V_TIMING_OVERRIDE2                                         0x4bbf
#define mmDP2_DP_MSA_V_TIMING_OVERRIDE2                                         0x4cbf
#define mmDP3_DP_MSA_V_TIMING_OVERRIDE2                                         0x4dbf
#define mmDP4_DP_MSA_V_TIMING_OVERRIDE2                                         0x4ebf
#define mmDP5_DP_MSA_V_TIMING_OVERRIDE2                                         0x4fbf
#define mmDP6_DP_MSA_V_TIMING_OVERRIDE2                                         0x54bf
#define mmDP7_DP_MSA_V_TIMING_OVERRIDE2                                         0x56bf
#define mmDP8_DP_MSA_V_TIMING_OVERRIDE2                                         0x57bf
#define mmDP_SEC_CNTL                                                           0x4ac3
#define mmDP0_DP_SEC_CNTL                                                       0x4ac3
#define mmDP1_DP_SEC_CNTL                                                       0x4bc3
#define mmDP2_DP_SEC_CNTL                                                       0x4cc3
#define mmDP3_DP_SEC_CNTL                                                       0x4dc3
#define mmDP4_DP_SEC_CNTL                                                       0x4ec3
#define mmDP5_DP_SEC_CNTL                                                       0x4fc3
#define mmDP6_DP_SEC_CNTL                                                       0x54c3
#define mmDP7_DP_SEC_CNTL                                                       0x56c3
#define mmDP8_DP_SEC_CNTL                                                       0x57c3
#define mmDP_SEC_CNTL1                                                          0x4ac4
#define mmDP0_DP_SEC_CNTL1                                                      0x4ac4
#define mmDP1_DP_SEC_CNTL1                                                      0x4bc4
#define mmDP2_DP_SEC_CNTL1                                                      0x4cc4
#define mmDP3_DP_SEC_CNTL1                                                      0x4dc4
#define mmDP4_DP_SEC_CNTL1                                                      0x4ec4
#define mmDP5_DP_SEC_CNTL1                                                      0x4fc4
#define mmDP6_DP_SEC_CNTL1                                                      0x54c4
#define mmDP7_DP_SEC_CNTL1                                                      0x56c4
#define mmDP8_DP_SEC_CNTL1                                                      0x57c4
#define mmDP_SEC_FRAMING1                                                       0x4ac5
#define mmDP0_DP_SEC_FRAMING1                                                   0x4ac5
#define mmDP1_DP_SEC_FRAMING1                                                   0x4bc5
#define mmDP2_DP_SEC_FRAMING1                                                   0x4cc5
#define mmDP3_DP_SEC_FRAMING1                                                   0x4dc5
#define mmDP4_DP_SEC_FRAMING1                                                   0x4ec5
#define mmDP5_DP_SEC_FRAMING1                                                   0x4fc5
#define mmDP6_DP_SEC_FRAMING1                                                   0x54c5
#define mmDP7_DP_SEC_FRAMING1                                                   0x56c5
#define mmDP8_DP_SEC_FRAMING1                                                   0x57c5
#define mmDP_SEC_FRAMING2                                                       0x4ac6
#define mmDP0_DP_SEC_FRAMING2                                                   0x4ac6
#define mmDP1_DP_SEC_FRAMING2                                                   0x4bc6
#define mmDP2_DP_SEC_FRAMING2                                                   0x4cc6
#define mmDP3_DP_SEC_FRAMING2                                                   0x4dc6
#define mmDP4_DP_SEC_FRAMING2                                                   0x4ec6
#define mmDP5_DP_SEC_FRAMING2                                                   0x4fc6
#define mmDP6_DP_SEC_FRAMING2                                                   0x54c6
#define mmDP7_DP_SEC_FRAMING2                                                   0x56c6
#define mmDP8_DP_SEC_FRAMING2                                                   0x57c6
#define mmDP_SEC_FRAMING3                                                       0x4ac7
#define mmDP0_DP_SEC_FRAMING3                                                   0x4ac7
#define mmDP1_DP_SEC_FRAMING3                                                   0x4bc7
#define mmDP2_DP_SEC_FRAMING3                                                   0x4cc7
#define mmDP3_DP_SEC_FRAMING3                                                   0x4dc7
#define mmDP4_DP_SEC_FRAMING3                                                   0x4ec7
#define mmDP5_DP_SEC_FRAMING3                                                   0x4fc7
#define mmDP6_DP_SEC_FRAMING3                                                   0x54c7
#define mmDP7_DP_SEC_FRAMING3                                                   0x56c7
#define mmDP8_DP_SEC_FRAMING3                                                   0x57c7
#define mmDP_SEC_FRAMING4                                                       0x4ac8
#define mmDP0_DP_SEC_FRAMING4                                                   0x4ac8
#define mmDP1_DP_SEC_FRAMING4                                                   0x4bc8
#define mmDP2_DP_SEC_FRAMING4                                                   0x4cc8
#define mmDP3_DP_SEC_FRAMING4                                                   0x4dc8
#define mmDP4_DP_SEC_FRAMING4                                                   0x4ec8
#define mmDP5_DP_SEC_FRAMING4                                                   0x4fc8
#define mmDP6_DP_SEC_FRAMING4                                                   0x54c8
#define mmDP7_DP_SEC_FRAMING4                                                   0x56c8
#define mmDP8_DP_SEC_FRAMING4                                                   0x57c8
#define mmDP_SEC_AUD_N                                                          0x4ac9
#define mmDP0_DP_SEC_AUD_N                                                      0x4ac9
#define mmDP1_DP_SEC_AUD_N                                                      0x4bc9
#define mmDP2_DP_SEC_AUD_N                                                      0x4cc9
#define mmDP3_DP_SEC_AUD_N                                                      0x4dc9
#define mmDP4_DP_SEC_AUD_N                                                      0x4ec9
#define mmDP5_DP_SEC_AUD_N                                                      0x4fc9
#define mmDP6_DP_SEC_AUD_N                                                      0x54c9
#define mmDP7_DP_SEC_AUD_N                                                      0x56c9
#define mmDP8_DP_SEC_AUD_N                                                      0x57c9
#define mmDP_SEC_AUD_N_READBACK                                                 0x4aca
#define mmDP0_DP_SEC_AUD_N_READBACK                                             0x4aca
#define mmDP1_DP_SEC_AUD_N_READBACK                                             0x4bca
#define mmDP2_DP_SEC_AUD_N_READBACK                                             0x4cca
#define mmDP3_DP_SEC_AUD_N_READBACK                                             0x4dca
#define mmDP4_DP_SEC_AUD_N_READBACK                                             0x4eca
#define mmDP5_DP_SEC_AUD_N_READBACK                                             0x4fca
#define mmDP6_DP_SEC_AUD_N_READBACK                                             0x54ca
#define mmDP7_DP_SEC_AUD_N_READBACK                                             0x56ca
#define mmDP8_DP_SEC_AUD_N_READBACK                                             0x57ca
#define mmDP_SEC_AUD_M                                                          0x4acb
#define mmDP0_DP_SEC_AUD_M                                                      0x4acb
#define mmDP1_DP_SEC_AUD_M                                                      0x4bcb
#define mmDP2_DP_SEC_AUD_M                                                      0x4ccb
#define mmDP3_DP_SEC_AUD_M                                                      0x4dcb
#define mmDP4_DP_SEC_AUD_M                                                      0x4ecb
#define mmDP5_DP_SEC_AUD_M                                                      0x4fcb
#define mmDP6_DP_SEC_AUD_M                                                      0x54cb
#define mmDP7_DP_SEC_AUD_M                                                      0x56cb
#define mmDP8_DP_SEC_AUD_M                                                      0x57cb
#define mmDP_SEC_AUD_M_READBACK                                                 0x4acc
#define mmDP0_DP_SEC_AUD_M_READBACK                                             0x4acc
#define mmDP1_DP_SEC_AUD_M_READBACK                                             0x4bcc
#define mmDP2_DP_SEC_AUD_M_READBACK                                             0x4ccc
#define mmDP3_DP_SEC_AUD_M_READBACK                                             0x4dcc
#define mmDP4_DP_SEC_AUD_M_READBACK                                             0x4ecc
#define mmDP5_DP_SEC_AUD_M_READBACK                                             0x4fcc
#define mmDP6_DP_SEC_AUD_M_READBACK                                             0x54cc
#define mmDP7_DP_SEC_AUD_M_READBACK                                             0x56cc
#define mmDP8_DP_SEC_AUD_M_READBACK                                             0x57cc
#define mmDP_SEC_TIMESTAMP                                                      0x4acd
#define mmDP0_DP_SEC_TIMESTAMP                                                  0x4acd
#define mmDP1_DP_SEC_TIMESTAMP                                                  0x4bcd
#define mmDP2_DP_SEC_TIMESTAMP                                                  0x4ccd
#define mmDP3_DP_SEC_TIMESTAMP                                                  0x4dcd
#define mmDP4_DP_SEC_TIMESTAMP                                                  0x4ecd
#define mmDP5_DP_SEC_TIMESTAMP                                                  0x4fcd
#define mmDP6_DP_SEC_TIMESTAMP                                                  0x54cd
#define mmDP7_DP_SEC_TIMESTAMP                                                  0x56cd
#define mmDP8_DP_SEC_TIMESTAMP                                                  0x57cd
#define mmDP_SEC_PACKET_CNTL                                                    0x4ace
#define mmDP0_DP_SEC_PACKET_CNTL                                                0x4ace
#define mmDP1_DP_SEC_PACKET_CNTL                                                0x4bce
#define mmDP2_DP_SEC_PACKET_CNTL                                                0x4cce
#define mmDP3_DP_SEC_PACKET_CNTL                                                0x4dce
#define mmDP4_DP_SEC_PACKET_CNTL                                                0x4ece
#define mmDP5_DP_SEC_PACKET_CNTL                                                0x4fce
#define mmDP6_DP_SEC_PACKET_CNTL                                                0x54ce
#define mmDP7_DP_SEC_PACKET_CNTL                                                0x56ce
#define mmDP8_DP_SEC_PACKET_CNTL                                                0x57ce
#define mmDP_MSE_RATE_CNTL                                                      0x4acf
#define mmDP0_DP_MSE_RATE_CNTL                                                  0x4acf
#define mmDP1_DP_MSE_RATE_CNTL                                                  0x4bcf
#define mmDP2_DP_MSE_RATE_CNTL                                                  0x4ccf
#define mmDP3_DP_MSE_RATE_CNTL                                                  0x4dcf
#define mmDP4_DP_MSE_RATE_CNTL                                                  0x4ecf
#define mmDP5_DP_MSE_RATE_CNTL                                                  0x4fcf
#define mmDP6_DP_MSE_RATE_CNTL                                                  0x54cf
#define mmDP7_DP_MSE_RATE_CNTL                                                  0x56cf
#define mmDP8_DP_MSE_RATE_CNTL                                                  0x57cf
#define mmDP_MSE_RATE_UPDATE                                                    0x4ad1
#define mmDP0_DP_MSE_RATE_UPDATE                                                0x4ad1
#define mmDP1_DP_MSE_RATE_UPDATE                                                0x4bd1
#define mmDP2_DP_MSE_RATE_UPDATE                                                0x4cd1
#define mmDP3_DP_MSE_RATE_UPDATE                                                0x4dd1
#define mmDP4_DP_MSE_RATE_UPDATE                                                0x4ed1
#define mmDP5_DP_MSE_RATE_UPDATE                                                0x4fd1
#define mmDP6_DP_MSE_RATE_UPDATE                                                0x54d1
#define mmDP7_DP_MSE_RATE_UPDATE                                                0x56d1
#define mmDP8_DP_MSE_RATE_UPDATE                                                0x57d1
#define mmDP_MSE_SAT0                                                           0x4ad2
#define mmDP0_DP_MSE_SAT0                                                       0x4ad2
#define mmDP1_DP_MSE_SAT0                                                       0x4bd2
#define mmDP2_DP_MSE_SAT0                                                       0x4cd2
#define mmDP3_DP_MSE_SAT0                                                       0x4dd2
#define mmDP4_DP_MSE_SAT0                                                       0x4ed2
#define mmDP5_DP_MSE_SAT0                                                       0x4fd2
#define mmDP6_DP_MSE_SAT0                                                       0x54d2
#define mmDP7_DP_MSE_SAT0                                                       0x56d2
#define mmDP8_DP_MSE_SAT0                                                       0x57d2
#define mmDP_MSE_SAT1                                                           0x4ad3
#define mmDP0_DP_MSE_SAT1                                                       0x4ad3
#define mmDP1_DP_MSE_SAT1                                                       0x4bd3
#define mmDP2_DP_MSE_SAT1                                                       0x4cd3
#define mmDP3_DP_MSE_SAT1                                                       0x4dd3
#define mmDP4_DP_MSE_SAT1                                                       0x4ed3
#define mmDP5_DP_MSE_SAT1                                                       0x4fd3
#define mmDP6_DP_MSE_SAT1                                                       0x54d3
#define mmDP7_DP_MSE_SAT1                                                       0x56d3
#define mmDP8_DP_MSE_SAT1                                                       0x57d3
#define mmDP_MSE_SAT2                                                           0x4ad4
#define mmDP0_DP_MSE_SAT2                                                       0x4ad4
#define mmDP1_DP_MSE_SAT2                                                       0x4bd4
#define mmDP2_DP_MSE_SAT2                                                       0x4cd4
#define mmDP3_DP_MSE_SAT2                                                       0x4dd4
#define mmDP4_DP_MSE_SAT2                                                       0x4ed4
#define mmDP5_DP_MSE_SAT2                                                       0x4fd4
#define mmDP6_DP_MSE_SAT2                                                       0x54d4
#define mmDP7_DP_MSE_SAT2                                                       0x56d4
#define mmDP8_DP_MSE_SAT2                                                       0x57d4
#define mmDP_MSE_SAT_UPDATE                                                     0x4ad5
#define mmDP0_DP_MSE_SAT_UPDATE                                                 0x4ad5
#define mmDP1_DP_MSE_SAT_UPDATE                                                 0x4bd5
#define mmDP2_DP_MSE_SAT_UPDATE                                                 0x4cd5
#define mmDP3_DP_MSE_SAT_UPDATE                                                 0x4dd5
#define mmDP4_DP_MSE_SAT_UPDATE                                                 0x4ed5
#define mmDP5_DP_MSE_SAT_UPDATE                                                 0x4fd5
#define mmDP6_DP_MSE_SAT_UPDATE                                                 0x54d5
#define mmDP7_DP_MSE_SAT_UPDATE                                                 0x56d5
#define mmDP8_DP_MSE_SAT_UPDATE                                                 0x57d5
#define mmDP_MSE_LINK_TIMING                                                    0x4ad6
#define mmDP0_DP_MSE_LINK_TIMING                                                0x4ad6
#define mmDP1_DP_MSE_LINK_TIMING                                                0x4bd6
#define mmDP2_DP_MSE_LINK_TIMING                                                0x4cd6
#define mmDP3_DP_MSE_LINK_TIMING                                                0x4dd6
#define mmDP4_DP_MSE_LINK_TIMING                                                0x4ed6
#define mmDP5_DP_MSE_LINK_TIMING                                                0x4fd6
#define mmDP6_DP_MSE_LINK_TIMING                                                0x54d6
#define mmDP7_DP_MSE_LINK_TIMING                                                0x56d6
#define mmDP8_DP_MSE_LINK_TIMING                                                0x57d6
#define mmDP_MSE_MISC_CNTL                                                      0x4ad7
#define mmDP0_DP_MSE_MISC_CNTL                                                  0x4ad7
#define mmDP1_DP_MSE_MISC_CNTL                                                  0x4bd7
#define mmDP2_DP_MSE_MISC_CNTL                                                  0x4cd7
#define mmDP3_DP_MSE_MISC_CNTL                                                  0x4dd7
#define mmDP4_DP_MSE_MISC_CNTL                                                  0x4ed7
#define mmDP5_DP_MSE_MISC_CNTL                                                  0x4fd7
#define mmDP6_DP_MSE_MISC_CNTL                                                  0x54d7
#define mmDP7_DP_MSE_MISC_CNTL                                                  0x56d7
#define mmDP8_DP_MSE_MISC_CNTL                                                  0x57d7
#define mmDP_TEST_DEBUG_INDEX                                                   0x4ad8
#define mmDP0_DP_TEST_DEBUG_INDEX                                               0x4ad8
#define mmDP1_DP_TEST_DEBUG_INDEX                                               0x4bd8
#define mmDP2_DP_TEST_DEBUG_INDEX                                               0x4cd8
#define mmDP3_DP_TEST_DEBUG_INDEX                                               0x4dd8
#define mmDP4_DP_TEST_DEBUG_INDEX                                               0x4ed8
#define mmDP5_DP_TEST_DEBUG_INDEX                                               0x4fd8
#define mmDP6_DP_TEST_DEBUG_INDEX                                               0x54d8
#define mmDP7_DP_TEST_DEBUG_INDEX                                               0x56d8
#define mmDP8_DP_TEST_DEBUG_INDEX                                               0x57d8
#define mmDP_TEST_DEBUG_DATA                                                    0x4ad9
#define mmDP0_DP_TEST_DEBUG_DATA                                                0x4ad9
#define mmDP1_DP_TEST_DEBUG_DATA                                                0x4bd9
#define mmDP2_DP_TEST_DEBUG_DATA                                                0x4cd9
#define mmDP3_DP_TEST_DEBUG_DATA                                                0x4dd9
#define mmDP4_DP_TEST_DEBUG_DATA                                                0x4ed9
#define mmDP5_DP_TEST_DEBUG_DATA                                                0x4fd9
#define mmDP6_DP_TEST_DEBUG_DATA                                                0x54d9
#define mmDP7_DP_TEST_DEBUG_DATA                                                0x56d9
#define mmDP8_DP_TEST_DEBUG_DATA                                                0x57d9
#define mmDP_FE_TEST_DEBUG_INDEX                                                0x4ada
#define mmDP0_DP_FE_TEST_DEBUG_INDEX                                            0x4ada
#define mmDP1_DP_FE_TEST_DEBUG_INDEX                                            0x4bda
#define mmDP2_DP_FE_TEST_DEBUG_INDEX                                            0x4cda
#define mmDP3_DP_FE_TEST_DEBUG_INDEX                                            0x4dda
#define mmDP4_DP_FE_TEST_DEBUG_INDEX                                            0x4eda
#define mmDP5_DP_FE_TEST_DEBUG_INDEX                                            0x4fda
#define mmDP6_DP_FE_TEST_DEBUG_INDEX                                            0x54da
#define mmDP7_DP_FE_TEST_DEBUG_INDEX                                            0x56da
#define mmDP8_DP_FE_TEST_DEBUG_INDEX                                            0x57da
#define mmDP_FE_TEST_DEBUG_DATA                                                 0x4adb
#define mmDP0_DP_FE_TEST_DEBUG_DATA                                             0x4adb
#define mmDP1_DP_FE_TEST_DEBUG_DATA                                             0x4bdb
#define mmDP2_DP_FE_TEST_DEBUG_DATA                                             0x4cdb
#define mmDP3_DP_FE_TEST_DEBUG_DATA                                             0x4ddb
#define mmDP4_DP_FE_TEST_DEBUG_DATA                                             0x4edb
#define mmDP5_DP_FE_TEST_DEBUG_DATA                                             0x4fdb
#define mmDP6_DP_FE_TEST_DEBUG_DATA                                             0x54db
#define mmDP7_DP_FE_TEST_DEBUG_DATA                                             0x56db
#define mmDP8_DP_FE_TEST_DEBUG_DATA                                             0x57db
#define mmAUX_CONTROL                                                           0x5c00
#define mmDP_AUX0_AUX_CONTROL                                                   0x5c00
#define mmDP_AUX1_AUX_CONTROL                                                   0x5c1c
#define mmDP_AUX2_AUX_CONTROL                                                   0x5c38
#define mmDP_AUX3_AUX_CONTROL                                                   0x5c54
#define mmDP_AUX4_AUX_CONTROL                                                   0x5c70
#define mmDP_AUX5_AUX_CONTROL                                                   0x5c8c
#define mmAUX_SW_CONTROL                                                        0x5c01
#define mmDP_AUX0_AUX_SW_CONTROL                                                0x5c01
#define mmDP_AUX1_AUX_SW_CONTROL                                                0x5c1d
#define mmDP_AUX2_AUX_SW_CONTROL                                                0x5c39
#define mmDP_AUX3_AUX_SW_CONTROL                                                0x5c55
#define mmDP_AUX4_AUX_SW_CONTROL                                                0x5c71
#define mmDP_AUX5_AUX_SW_CONTROL                                                0x5c8d
#define mmAUX_ARB_CONTROL                                                       0x5c02
#define mmDP_AUX0_AUX_ARB_CONTROL                                               0x5c02
#define mmDP_AUX1_AUX_ARB_CONTROL                                               0x5c1e
#define mmDP_AUX2_AUX_ARB_CONTROL                                               0x5c3a
#define mmDP_AUX3_AUX_ARB_CONTROL                                               0x5c56
#define mmDP_AUX4_AUX_ARB_CONTROL                                               0x5c72
#define mmDP_AUX5_AUX_ARB_CONTROL                                               0x5c8e
#define mmAUX_INTERRUPT_CONTROL                                                 0x5c03
#define mmDP_AUX0_AUX_INTERRUPT_CONTROL                                         0x5c03
#define mmDP_AUX1_AUX_INTERRUPT_CONTROL                                         0x5c1f
#define mmDP_AUX2_AUX_INTERRUPT_CONTROL                                         0x5c3b
#define mmDP_AUX3_AUX_INTERRUPT_CONTROL                                         0x5c57
#define mmDP_AUX4_AUX_INTERRUPT_CONTROL                                         0x5c73
#define mmDP_AUX5_AUX_INTERRUPT_CONTROL                                         0x5c8f
#define mmAUX_SW_STATUS                                                         0x5c04
#define mmDP_AUX0_AUX_SW_STATUS                                                 0x5c04
#define mmDP_AUX1_AUX_SW_STATUS                                                 0x5c20
#define mmDP_AUX2_AUX_SW_STATUS                                                 0x5c3c
#define mmDP_AUX3_AUX_SW_STATUS                                                 0x5c58
#define mmDP_AUX4_AUX_SW_STATUS                                                 0x5c74
#define mmDP_AUX5_AUX_SW_STATUS                                                 0x5c90
#define mmAUX_LS_STATUS                                                         0x5c05
#define mmDP_AUX0_AUX_LS_STATUS                                                 0x5c05
#define mmDP_AUX1_AUX_LS_STATUS                                                 0x5c21
#define mmDP_AUX2_AUX_LS_STATUS                                                 0x5c3d
#define mmDP_AUX3_AUX_LS_STATUS                                                 0x5c59
#define mmDP_AUX4_AUX_LS_STATUS                                                 0x5c75
#define mmDP_AUX5_AUX_LS_STATUS                                                 0x5c91
#define mmAUX_SW_DATA                                                           0x5c06
#define mmDP_AUX0_AUX_SW_DATA                                                   0x5c06
#define mmDP_AUX1_AUX_SW_DATA                                                   0x5c22
#define mmDP_AUX2_AUX_SW_DATA                                                   0x5c3e
#define mmDP_AUX3_AUX_SW_DATA                                                   0x5c5a
#define mmDP_AUX4_AUX_SW_DATA                                                   0x5c76
#define mmDP_AUX5_AUX_SW_DATA                                                   0x5c92
#define mmAUX_LS_DATA                                                           0x5c07
#define mmDP_AUX0_AUX_LS_DATA                                                   0x5c07
#define mmDP_AUX1_AUX_LS_DATA                                                   0x5c23
#define mmDP_AUX2_AUX_LS_DATA                                                   0x5c3f
#define mmDP_AUX3_AUX_LS_DATA              