  0x5c63
#define mmDP_AUX4_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c7f
#define mmDP_AUX5_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c9b
#define mmAUX_GTC_SYNC_CONTROLLER_STATUS                                        0x5c10
#define mmDP_AUX0_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c10
#define mmDP_AUX1_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c2c
#define mmDP_AUX2_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c48
#define mmDP_AUX3_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c64
#define mmDP_AUX4_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c80
#define mmDP_AUX5_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c9c
#define mmAUX_GTC_SYNC_STATUS                                                   0x5c11
#define mmDP_AUX0_AUX_GTC_SYNC_STATUS                                           0x5c11
#define mmDP_AUX1_AUX_GTC_SYNC_STATUS                                           0x5c2d
#define mmDP_AUX2_AUX_GTC_SYNC_STATUS                                           0x5c49
#define mmDP_AUX3_AUX_GTC_SYNC_STATUS                                           0x5c65
#define mmDP_AUX4_AUX_GTC_SYNC_STATUS                                           0x5c81
#define mmDP_AUX5_AUX_GTC_SYNC_STATUS                                           0x5c9d
#define mmAUX_GTC_SYNC_DATA                                                     0x5c12
#define mmDP_AUX0_AUX_GTC_SYNC_DATA                                             0x5c12
#define mmDP_AUX1_AUX_GTC_SYNC_DATA                                             0x5c2e
#define mmDP_AUX2_AUX_GTC_SYNC_DATA                                             0x5c4a
#define mmDP_AUX3_AUX_GTC_SYNC_DATA                                             0x5c66
#define mmDP_AUX4_AUX_GTC_SYNC_DATA                                             0x5c82
#define mmDP_AUX5_AUX_GTC_SYNC_DATA                                             0x5c9e
#define mmAUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                                    0x5c13
#define mmDP_AUX0_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c13
#define mmDP_AUX1_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c2f
#define mmDP_AUX2_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c4b
#define mmDP_AUX3_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c67
#define mmDP_AUX4_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c83
#define mmDP_AUX5_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c9f
#define mmAUX_TEST_DEBUG_INDEX                                                  0x5c14
#define mmDP_AUX0_AUX_TEST_DEBUG_INDEX                                          0x5c14
#define mmDP_AUX1_AUX_TEST_DEBUG_INDEX                                          0x5c30
#define mmDP_AUX2_AUX_TEST_DEBUG_INDEX                                          0x5c4c
#define mmDP_AUX3_AUX_TEST_DEBUG_INDEX                                          0x5c68
#define mmDP_AUX4_AUX_TEST_DEBUG_INDEX                                          0x5c84
#define mmDP_AUX5_AUX_TEST_DEBUG_INDEX                                          0x5ca0
#define mmAUX_TEST_DEBUG_DATA                                                   0x5c15
#define mmDP_AUX0_AUX_TEST_DEBUG_DATA                                           0x5c15
#define mmDP_AUX1_AUX_TEST_DEBUG_DATA                                           0x5c31
#define mmDP_AUX2_AUX_TEST_DEBUG_DATA                                           0x5c4d
#define mmDP_AUX3_AUX_TEST_DEBUG_DATA                                           0x5c69
#define mmDP_AUX4_AUX_TEST_DEBUG_DATA                                           0x5c85
#define mmDP_AUX5_AUX_TEST_DEBUG_DATA                                           0x5ca1
#define ixDP_AUX_DEBUG_A                                                        0x10
#define ixDP_AUX_DEBUG_B                                                        0x11
#define ixDP_AUX_DEBUG_C                                                        0x12
#define ixDP_AUX_DEBUG_D                                                        0x13
#define ixDP_AUX_DEBUG_E                                                        0x14
#define ixDP_AUX_DEBUG_F                                                        0x15
#define ixDP_AUX_DEBUG_G                                                        0x16
#define ixDP_AUX_DEBUG_H                                                        0x17
#define ixDP_AUX_DEBUG_I                                                        0x18
#define ixDP_AUX_DEBUG_J                                                        0x19
#define ixDP_AUX_DEBUG_K                                                        0x1a
#define ixDP_AUX_DEBUG_L                                                        0x1b
#define ixDP_AUX_DEBUG_M                                                        0x1c
#define ixDP_AUX_DEBUG_N                                                        0x1d
#define ixDP_AUX_DEBUG_O                                                        0x1e
#define ixDP_AUX_DEBUG_P                                                        0x1f
#define ixDP_AUX_DEBUG_Q                                                        0x20
#define mmDVO_ENABLE                                                            0x16a0
#define mmDVO_SOURCE_SELECT                                                     0x16a1
#define mmDVO_OUTPUT                                                            0x16a2
#define mmDVO_CONTROL                                                           0x16a3
#define mmDVO_CRC_EN                                                            0x16a4
#define mmDVO_CRC2_SIG_MASK                                                     0x16a5
#define mmDVO_CRC2_SIG_RESULT                                                   0x16a6
#define mmDVO_FIFO_ERROR_STATUS                                                 0x16a7
#define mmDVO_TEST_DEBUG_INDEX                                                  0x16a8
#define mmDVO_TEST_DEBUG_DATA                                                   0x16a9
#define mmFBC_CNTL                                                              0x280
#define mmFBC_IDLE_MASK                                                         0x281
#define mmFBC_IDLE_FORCE_CLEAR_MASK                                             0x282
#define mmFBC_START_STOP_DELAY                                                  0x283
#define mmFBC_COMP_CNTL                                                         0x284
#define mmFBC_COMP_MODE                                                         0x285
#define mmFBC_DEBUG0                                                            0x286
#define mmFBC_DEBUG1                                                            0x287
#define mmFBC_DEBUG2                                                            0x288
#define mmFBC_IND_LUT0                                                          0x289
#define mmFBC_IND_LUT1                                                          0x28a
#define mmFBC_IND_LUT2                                                          0x28b
#define mmFBC_IND_LUT3                                                          0x28c
#define mmFBC_IND_LUT4                                                          0x28d
#define mmFBC_IND_LUT5                                                          0x28e
#define mmFBC_IND_LUT6                                                          0x28f
#define mmFBC_IND_LUT7                                                          0x290
#define mmFBC_IND_LUT8                                                          0x291
#define mmFBC_IND_LUT9                                                          0x292
#define mmFBC_IND_LUT10                                                         0x293
#define mmFBC_IND_LUT11                                                         0x294
#define mmFBC_IND_LUT12                                                         0x295
#define mmFBC_IND_LUT13                                                         0x296
#define mmFBC_IND_LUT14                                                         0x297
#define mmFBC_IND_LUT15                                                         0x298
#define mmFBC_CSM_REGION_OFFSET_01                                              0x299
#define mmFBC_CSM_REGION_OFFSET_23                                              0x29a
#define mmFBC_CLIENT_REGION_MASK                                                0x29b
#define mmFBC_DEBUG_COMP                                                        0x29c
#define mmFBC_DEBUG_CSR                                                         0x29d
#define mmFBC_DEBUG_CSR_RDATA                                                   0x29e
#define mmFBC_DEBUG_CSR_WDATA                                                   0x29f
#define mmFBC_DEBUG_CSR_RDATA_HI                                                0x2a0
#define mmFBC_DEBUG_CSR_WDATA_HI                                                0x2a1
#define mmFBC_MISC                                                              0x2a2
#define mmFBC_STATUS                                                            0x2a3
#define mmFBC_TEST_DEBUG_INDEX                                                  0x2a4
#define mmFBC_TEST_DEBUG_DATA                                                   0x2a5
#define mmFMT_CLAMP_COMPONENT_R                                                 0x1be8
#define mmFMT0_FMT_CLAMP_COMPONENT_R                                            0x1be8
#define mmFMT1_FMT_CLAMP_COMPONENT_R                                            0x1de8
#define mmFMT2_FMT_CLAMP_COMPONENT_R                                            0x1fe8
#define mmFMT3_FMT_CLAMP_COMPONENT_R                                            0x41e8
#define mmFMT4_FMT_CLAMP_COMPONENT_R                                            0x43e8
#define mmFMT5_FMT_CLAMP_COMPONENT_R                                            0x45e8
#define mmFMT_CLAMP_COMPONENT_G                                                 0x1be9
#define mmFMT0_FMT_CLAMP_COMPONENT_G                                            0x1be9
#define mmFMT1_FMT_CLAMP_COMPONENT_G                                            0x1de9
#define mmFMT2_FMT_CLAMP_COMPONENT_G                                            0x1fe9
#define mmFMT3_FMT_CLAMP_COMPONENT_G                                            0x41e9
#define mmFMT4_FMT_CLAMP_COMPONENT_G                                            0x43e9
#define mmFMT5_FMT_CLAMP_COMPONENT_G                                            0x45e9
#define mmFMT_CLAMP_COMPONENT_B                                                 0x1bea
#define mmFMT0_FMT_CLAMP_COMPONENT_B                                            0x1bea
#define mmFMT1_FMT_CLAMP_COMPONENT_B                                            0x1dea
#define mmFMT2_FMT_CLAMP_COMPONENT_B                                            0x1fea
#define mmFMT3_FMT_CLAMP_COMPONENT_B                                            0x41ea
#define mmFMT4_FMT_CLAMP_COMPONENT_B                                            0x43ea
#define mmFMT5_FMT_CLAMP_COMPONENT_B                                            0x45ea
#define mmFMT_DYNAMIC_EXP_CNTL       