         0x5c94
#define mmAUX_DPHY_TX_CONTROL                                                   0x5c09
#define mmDP_AUX0_AUX_DPHY_TX_CONTROL                                           0x5c09
#define mmDP_AUX1_AUX_DPHY_TX_CONTROL                                           0x5c25
#define mmDP_AUX2_AUX_DPHY_TX_CONTROL                                           0x5c41
#define mmDP_AUX3_AUX_DPHY_TX_CONTROL                                           0x5c5d
#define mmDP_AUX4_AUX_DPHY_TX_CONTROL                                           0x5c79
#define mmDP_AUX5_AUX_DPHY_TX_CONTROL                                           0x5c95
#define mmAUX_DPHY_RX_CONTROL0                                                  0x5c0a
#define mmDP_AUX0_AUX_DPHY_RX_CONTROL0                                          0x5c0a
#define mmDP_AUX1_AUX_DPHY_RX_CONTROL0                                          0x5c26
#define mmDP_AUX2_AUX_DPHY_RX_CONTROL0                                          0x5c42
#define mmDP_AUX3_AUX_DPHY_RX_CONTROL0                                          0x5c5e
#define mmDP_AUX4_AUX_DPHY_RX_CONTROL0                                          0x5c7a
#define mmDP_AUX5_AUX_DPHY_RX_CONTROL0                                          0x5c96
#define mmAUX_DPHY_RX_CONTROL1                                                  0x5c0b
#define mmDP_AUX0_AUX_DPHY_RX_CONTROL1                                          0x5c0b
#define mmDP_AUX1_AUX_DPHY_RX_CONTROL1                                          0x5c27
#define mmDP_AUX2_AUX_DPHY_RX_CONTROL1                                          0x5c43
#define mmDP_AUX3_AUX_DPHY_RX_CONTROL1                                          0x5c5f
#define mmDP_AUX4_AUX_DPHY_RX_CONTROL1                                          0x5c7b
#define mmDP_AUX5_AUX_DPHY_RX_CONTROL1                                          0x5c97
#define mmAUX_DPHY_TX_STATUS                                                    0x5c0c
#define mmDP_AUX0_AUX_DPHY_TX_STATUS                                            0x5c0c
#define mmDP_AUX1_AUX_DPHY_TX_STATUS                                            0x5c28
#define mmDP_AUX2_AUX_DPHY_TX_STATUS                                            0x5c44
#define mmDP_AUX3_AUX_DPHY_TX_STATUS                                            0x5c60
#define mmDP_AUX4_AUX_DPHY_TX_STATUS                                            0x5c7c
#define mmDP_AUX5_AUX_DPHY_TX_STATUS                                            0x5c98
#define mmAUX_DPHY_RX_STATUS                                                    0x5c0d
#define mmDP_AUX0_AUX_DPHY_RX_STATUS                                            0x5c0d
#define mmDP_AUX1_AUX_DPHY_RX_STATUS                                            0x5c29
#define mmDP_AUX2_AUX_DPHY_RX_STATUS                                            0x5c45
#define mmDP_AUX3_AUX_DPHY_RX_STATUS                                            0x5c61
#define mmDP_AUX4_AUX_DPHY_RX_STATUS                                            0x5c7d
#define mmDP_AUX5_AUX_DPHY_RX_STATUS                                            0x5c99
#define mmAUX_GTC_SYNC_CONTROL                                             