T                                                 0x1cc3
#define mmLB2_LB_DESKTOP_HEIGHT                                                 0x1ec3
#define mmLB3_LB_DESKTOP_HEIGHT                                                 0x40c3
#define mmLB4_LB_DESKTOP_HEIGHT                                                 0x42c3
#define mmLB5_LB_DESKTOP_HEIGHT                                                 0x44c3
#define mmLB_VLINE_START_END                                                    0x1ac4
#define mmLB0_LB_VLINE_START_END                                                0x1ac4
#define mmLB1_LB_VLINE_START_END                                                0x1cc4
#define mmLB2_LB_VLINE_START_END                                                0x1ec4
#define mmLB3_LB_VLINE_START_END                                                0x40c4
#define mmLB4_LB_VLINE_START_END                                                0x42c4
#define mmLB5_LB_VLINE_START_END                                                0x44c4
#define mmLB_VLINE2_START_END                                                   0x1ac5
#define mmLB0_LB_VLINE2_START_END                                               0x1ac5
#define mmLB1_LB_VLINE2_START_END                                               0x1cc5
#define mmLB2_LB_VLINE2_START_END                                               0x1ec5
#define mmLB3_LB_VLINE2_START_END                                               0x40c5
#define mmLB4_LB_VLINE2_START_END                                               0x42c5
#define mmLB5_LB_VLINE2_START_END                                               0x44c5
#define mmLB_V_COUNTER                                                          0x1ac6
#define mmLB0_LB_V_COUNTER                                                      0x1ac6
#define mmLB1_LB_V_COUNTER                                                      0x1cc6
#define mmLB2_LB_V_COUNTER                                                      0x1ec6
#define mmLB3_LB_V_COUNTER                                                      0x40c6
#define mmLB4_LB_V_COUNTER                                                      0x42c6
#define mmLB5_LB_V_COUNTER                                                      0x44c6
#define mmLB_SNAPSHOT_V_COUNTER                                                 0x1ac7
#define mmLB0_LB_SNAPSHOT_V_COUNTER                                             0x1ac7
#define mmLB1_LB_SNAPSHOT_V_COUNTER                                             0x1cc7
#define mmLB2_LB_SNAPSHOT_V_COUNTER                                             0x1ec7
#define mmLB3_LB_SNAPSHOT_V_COUNTER                                             0x40c7
#define mmLB4_LB_SNAPSHOT_V_COUNTER                                             0x42c7
#define mmLB5_LB_SNAPSHOT_V_COUNTER                                             0x44c7
#define mmLB_INTERRUPT_MASK                                                     0x1ac8
#define mmLB0_LB_INTERRUPT_MASK                                                 0x1ac8
#define mmLB1_LB_INTERRUPT_MASK                                                 0x1cc8
#define mmLB2_LB_INTERRUPT_MASK                                                 0x1ec8
#define mmLB3_LB_INTERRUPT_MASK                                                 0x40c8
#define mmLB4_LB_INTERRUPT_MASK                                                 0x42c8
#define mmLB5_LB_INTERRUPT_MASK                                                 0x44c8
#define mmLB_VLINE_STATUS                                                       0x1ac9
#define mmLB0_LB_VLINE_STATUS                                                   0x1ac9
#define mmLB1_LB_VLINE_STATUS                                                   0x1cc9
#define mmLB2_LB_VLINE_STATUS                                                   0x1ec9
#define mmLB3_LB_VLINE_STATUS                                                   0x40c9
#define mmLB4_LB_VLINE_STATUS                                                   0x42c9
#define mmLB5_LB_VLINE_STATUS                                                   0x44c9
#define mmLB_VLINE2_STATUS                                                      0x1aca
#define mmLB0_LB_VLINE2_STATUS                                                  0x1aca
#define mmLB1_LB_VLINE2_STATUS                                                  0x1cca
#define mmLB2_LB_VLINE2_STATUS                                                  0x1eca
#define mmLB3_LB_VLINE2_STATUS                                                  0x40ca
#define mmLB4_LB_VLINE2_STATUS                                                  0x42ca
#define mmLB5_LB_VLINE2_STATUS                                                  0x44ca
#define mmLB_VBLANK_STATUS                                                      0x1acb
#define mmLB0_LB_VBLANK_STATUS                                                  0x1acb
#define mmLB1_LB_VBLANK_STATUS                                                  0x1ccb
#define mmLB2_LB_VBLANK_STATUS                                                  0x1ecb
#define mmLB3_LB_VBLANK_STATUS                                                  0x40cb
#define mmLB4_LB_VBLANK_STATUS                                                  0x42cb
#define mmLB5_LB_VBLANK_STATUS                                                  0x44cb
#define mmLB_SYNC_RESET_SEL                                                     0x1acc
#define mmLB0_LB_SYNC_RESET_SEL                                                 0x1acc
#define mmLB1_LB_SYNC_RESET_SEL                                                 0x1ccc
#define mmLB2_LB_SYNC_RESET_SEL                                                 0x1ecc
#define mmLB3_LB_SYNC_RESET_SEL                                                 0x40cc
#define mmLB4_LB_SYNC_RESET_SEL                                                 0x42cc
#define mmLB5_LB_SYNC_RESET_SEL                                                 0x44cc
#define mmLB_BLACK_KEYER_R_CR                                                   0x1acd
#define mmLB0_LB_BLACK_KEYER_R_CR                                               0x1acd
#define mmLB1_LB_BLACK_KEYER_R_CR                                               0x1ccd
#define mmLB2_LB_BLACK_KEYER_R_CR                                               0x1ecd
#define mmLB3_LB_BLACK_KEYER_R_CR                                               0x40cd
#define mmLB4_LB_BLACK_KEYER_R_CR                                               0x42cd
#define mmLB5_LB_BLACK_KEYER_R_CR                                               0x44cd
#define mmLB_BLACK_KEYER_G_Y                                                    0x1ace
#define mmLB0_LB_BLACK_KEYER_G_Y                                                0x1ace
#define mmLB1_LB_BLACK_KEYER_G_Y                                                0x1cce
#define mmLB2_LB_BLACK_KEYER_G_Y                                                0x1ece
#define mmLB3_LB_BLACK_KEYER_G_Y                                                0x40ce
#define mmLB4_LB_BLACK_KEYER_G_Y                                                0x42ce
#define mmLB5_LB_BLACK_KEYER_G_Y                                                0x44ce
#define mmLB_BLACK_KEYER_B_CB                                                   0x1acf
#define mmLB0_LB_BLACK_KEYER_B_CB                                               0x1acf
#define mmLB1_LB_BLACK_KEYER_B_CB                                               0x1ccf
#define mmLB2_LB_BLACK_KEYER_B_CB                                               0x1ecf
#define mmLB3_LB_BLACK_KEYER_B_CB                                               0x40cf
#define mmLB4_LB_BLACK_KEYER_B_CB                                               0x42cf
#define mmLB5_LB_BLACK_KEYER_B_CB                                               0x44cf
#define mmLB_KEYER_COLOR_CTRL                                                   0x1ad0
#define mmLB0_LB_KEYER_COLOR_CTRL                                               0x1ad0
#define mmLB1_LB_KEYER_COLOR_CTRL                                               0x1cd0
#define mmLB2_LB_KEYER_COLOR_CTRL                                               0x1ed0
#define mmLB3_LB_KEYER_COLOR_CTRL                                               0x40d0
#define mmLB4_LB_KEYER_COLOR_CTRL                                               0x42d0
#define mmLB5_LB_KEYER_COLOR_CTRL                                               0x44d0
#define mmLB_KEYER_COLOR_R_CR                                                   0x1ad1
#define mmLB0_LB_KEYER_COLOR_R_CR                                               0x1ad1
#define mmLB1_LB_KEYER_COLOR_R_CR                                               0x1cd1
#define mmLB2_LB_KEYER_COLOR_R_CR                                               0x1ed1
#define mmLB3_LB_KEYER_COLOR_R_CR                                               0x40d1
#define mmLB4_LB_KEYER_COLOR_R_CR                                               0x42d1
#define mmLB5_LB_KEYER_COLOR_R_CR                              