   0x4b2e
#define mmDIG2_HDMI_ACR_32_0                                                    0x4c2e
#define mmDIG3_HDMI_ACR_32_0                                                    0x4d2e
#define mmDIG4_HDMI_ACR_32_0                                                    0x4e2e
#define mmDIG5_HDMI_ACR_32_0                                                    0x4f2e
#define mmDIG6_HDMI_ACR_32_0                                                    0x542e
#define mmDIG7_HDMI_ACR_32_0                                                    0x562e
#define mmDIG8_HDMI_ACR_32_0                                                    0x572e
#define mmHDMI_ACR_32_1                                                         0x4a2f
#define mmDIG0_HDMI_ACR_32_1                                                    0x4a2f
#define mmDIG1_HDMI_ACR_32_1                                                    0x4b2f
#define mmDIG2_HDMI_ACR_32_1                                                    0x4c2f
#define mmDIG3_HDMI_ACR_32_1                                                    0x4d2f
#define mmDIG4_HDMI_ACR_32_1                                                    0x4e2f
#define mmDIG5_HDMI_ACR_32_1                                                    0x4f2f
#define mmDIG6_HDMI_ACR_32_1                                                    0x542f
#define mmDIG7_HDMI_ACR_32_1                                                    0x562f
#define mmDIG8_HDMI_ACR_32_1                                                    0x572f
#define mmHDMI_ACR_44_0                                                         0x4a30
#define mmDIG0_HDMI_ACR_44_0                                                    0x4a30
#define mmDIG1_HDMI_ACR_44_0                                                    0x4b30
#define mmDIG2_HDMI_ACR_44_0                                                    0x4c30
#define mmDIG3_HDMI_ACR_44_0                                                    0x4d30
#define mmDIG4_HDMI_ACR_44_0                                                    0x4e30
#define mmDIG5_HDMI_ACR_44_0                                                    0x4f30
#define mmDIG6_HDMI_ACR_44_0                                                    0x5430
#define mmDIG7_HDMI_ACR_44_0                                                    0x5630
#define mmDIG8_HDMI_ACR_44_0                                                    0x5730
#define mmHDMI_ACR_44_1                                                         0x4a31
#define mmDIG0_HDMI_ACR_44_1                                                    0x4a31
#define mmDIG1_HDMI_ACR_44_1                                                    0x4b31
#define mmDIG2_HDMI_ACR_44_1                                                    0x4c31
#define mmDIG3_HDMI_ACR_44_1                                                    0x4d31
#define mmDIG4_HDMI_ACR_44_1                                                    0x4e31
#define mmDIG5_HDMI_ACR_44_1                                                    0x4f31
#define mmDIG6_HDMI_ACR_44_1                                                    0x5431
#define mmDIG7_HDMI_ACR_44_1                                                    0x5631
#define mmDIG8_HDMI_ACR_44_1                                                    0x5731
#define mmHDMI_ACR_48_0                                                         0x4a32
#define mmDIG0_HDMI_ACR_48_0                                                    0x4a32
#define mmDIG1_HDMI_ACR_48_0                                                    0x4b32
#define mmDIG2_HDMI_ACR_48_0                                                    0x4c32
#define mmDIG3_HDMI_ACR_48_0                                                    0x4d32
#define mmDIG4_HDMI_ACR_48_0                                                    0x4e32
#define mmDIG5_HDMI_ACR_48_0                                                    0x4f32
#define mmDIG6_HDMI_ACR_48_0                                                    0x5432
#define mmDIG7_HDMI_ACR_48_0                                                    0x5632
#define mmDIG8_HDMI_ACR_48_0                                                    0x5732
#define mmHDMI_ACR_48_1                                                         0x4a33
#define mmDIG0_HDMI_ACR_48_1                                                    0x4a33
#define mmDIG1_HDMI_ACR_48_1                                                    0x4b33
#define mmDIG2_HDMI_ACR_48_1                                                    0x4c33
#define mmDIG3_HDMI_ACR_48_1                                                    0x4d33
#define mmDIG4_HDMI_ACR_48_1                                                    0x4e33
#define mmDIG5_HDMI_ACR_48_1                                                    0x4f33
#define mmDIG6_HDMI_ACR_48_1                                                    0x5433
#define mmDIG7_HDMI_ACR_48_1                                                    0x5633
#define mmDIG8_HDMI_ACR_48_1                                                    0x5733
#define mmHDMI_ACR_STATUS_0                                                     0x4a34
#define mmDIG0_HDMI_ACR_STATUS_0                                                0x4a34
#define mmDIG1_HDMI_ACR_STATUS_0                                                0x4b34
#define mmDIG2_HDMI_ACR_STATUS_0                                                0x4c34
#define mmDIG3_HDMI_ACR_STATUS_0                                                0x4d34
#define mmDIG4_HDMI_ACR_STATUS_0                                                0x4e34
#define mmDIG5_HDMI_ACR_STATUS_0                                                0x4f34
#define mmDIG6_HDMI_ACR_STATUS_0                                                0x5434
#define mmDIG7_HDMI_ACR_STATUS_0                                                0x5634
#define mmDIG8_HDMI_ACR_STATUS_0                                                0x5734
#define mmHDMI_ACR_STATUS_1                                                     0x4a35
#define mmDIG0_HDMI_ACR_STATUS_1                                                0x4a35
#define mmDIG1_HDMI_ACR_STATUS_1                                                0x4b35
#define mmDIG2_HDMI_ACR_STATUS_1                                                0x4c35
#define mmDIG3_HDMI_ACR_STATUS_1                                                0x4d35
#define mmDIG4_HDMI_ACR_STATUS_1                                                0x4e35
#define mmDIG5_HDMI_ACR_STATUS_1                                                0x4f35
#define mmDIG6_HDMI_ACR_STATUS_1                                                0x5435
#define mmDIG7_HDMI_ACR_STATUS_1                                                0x5635
#define mmDIG8_HDMI_ACR_STATUS_1                                                0x5735
#define mmAFMT_AUDIO_INFO0                                                      0x4a36
#define mmDIG0_AFMT_AUDIO_INFO0                                                 0x4a36
#define mmDIG1_AFMT_AUDIO_INFO0                                                 0x4b36
#define mmDIG2_AFMT_AUDIO_INFO0                                                 0x4c36
#define mmDIG3_AFMT_AUDIO_INFO0                                                 0x4d36
#define mmDIG4_AFMT_AUDIO_INFO0                                                 0x4e36
#define mmDIG5_AFMT_AUDIO_INFO0                                                 0x4f36
#define mmDIG6_AFMT_AUDIO_INFO0                                                 0x5436
#define mmDIG7_AFMT_AUDIO_INFO0                                                 0x5636
#define mmDIG8_AFMT_AUDIO_INFO0                                                 0x5736
#define mmAFMT_AUDIO_INFO1                                                      0x4a37
#define mmDIG0_AFMT_AUDIO_INFO1                                                 0x4a37
#define mmDIG1_AFMT_AUDIO_INFO1                                                 0x4b37
#define mmDIG2_AFMT_AUDIO_INFO1                                                 0x4c37
#define mmDIG3_AFMT_AUDIO_INFO1                                                 0x4d37
#define mmDIG4_AFMT_AUDIO_INFO1                                                 0x4e37
#define mmDIG5_AFMT_AUDIO_INFO1                                                 0x4f37
#define mmDIG6_AFMT_AUDIO_INFO1                                                 0x5437
#define mmDIG7_AFMT_AUDIO_INFO1                                                 0x5637
#define mmDIG8_AFMT_AUDIO_INFO1                                                 0x5737
#define mmAFMT_60958_0                                                          0x4a38
#define mmDIG0_AFMT_60958_0                                                     0x4a38
#define mmDIG1_AFMT_60958_0                                                     0x4b38
#define mmDIG2_AFMT_60958_0                                                     0x4c38
#define mmDIG3_AFMT_60958_0                                                     0x4d38
#define mmDIG4_AFMT_60958_0                                                     0x4e38
#define mmDIG5_AFMT_60958_0                                                     0x4f38
#define mmDIG6_AFMT_60958_0                                                     0x5438
#define mmDIG7_AFMT_60958_0                                                     0x5638
#define mmDIG8_AFMT_60958_0                                                     0x5738
#define mmAFMT_60958_1                                                          0x4a39
#define mmDIG0_AFMT_60958_1                                                     0x4a39
#define mmDIG1_AFMT_60958_1                                                     0x4b39
#define mmDIG2_AFMT_60958_1                                                     0x4c39
#define mmDIG3_AFMT_60958_1                                                     0x4d39
#define mmDIG4_AFMT_60958_1                                                     0x4e39
#define mmDIG5_AFMT_60958_1                                                     0x4f39
#define mmDIG6_AFMT_60958_1                                                     0x5439
#define mmDIG7_AFMT_60958_1                                                     0x5639
#define mmDIG8_AFMT_60958_1                                                     0x5739
#define mmAFMT_AUDIO_CRC_CONTROL                                                0x4a3a
#define mmDIG0_AFMT_AUDIO_CRC_CONTROL                                           0x4a3a
#define mmDIG1_AFMT_AUDIO_CRC_CONTROL                                           0x4b3a
#define mmDIG2_AFMT_AUDIO_CRC_CONTROL                                           0x4c3a
#define mmDIG3_AFMT_AUDIO_CRC_CONTROL                                           0x4d3a
#define mmDIG4_AFMT_AUDIO_CRC_CONTROL                                           0x4e3a
#define mmDIG5_AFMT_AUDIO_CRC_CONTROL                                           0x4f3a
#define mmDIG6_AFMT_AUDIO_CRC_CONTROL                                           0x543a
#define mmDIG7_AFMT_AUDIO_CRC_CONTROL                                           0x563a
#define mmDIG8_AFMT_AUDIO_CRC_CONTROL                                           0x573a
#define mmAFMT_RAMP_CONTROL0                                                    0x4a3b
#define mmDIG0_AFMT_RAMP_CONTROL0                                               0x4a3b
#define mmDIG1_AFMT_RAMP_CONTROL0                                               0x4b3b
#define mmDIG2_AFMT_RAMP_CONTROL0                                               0x4c3b
#define mmDIG3_AFMT_RAMP_CONTROL0                                               0x4d3b
#define mmDIG4_AFMT_RAMP_CONTROL0                                               0x4e3b
#define mmDIG5_AFMT_RAMP_CONTROL0                                               0x4f3b
#define mmDIG6_AFMT_RAMP_CONTROL0                                               0x543b
#define mmDIG7_AFMT_RAMP_CONTROL0                                               0x563b
#define mmDIG8_AFMT_RAMP_CONTROL0                                               0x573b
#define mmAFMT_RAMP_CONTROL1                                                    0x4a3c
#define mmDIG0_AFMT_RAMP_CONTROL1                                               0x4a3c
#define mmDIG1_AFMT_RAMP_CONTROL1                                               0x4b3c
#define mmDIG2_AFMT_RAMP_CONTROL1                                               0x4c3c
#define mmDIG3_AFMT_RAMP_CONTROL1                                               0x4d3c
#define mmDIG4_AFMT_RAMP_CONTROL1                                               0x4e3c
#define mmDIG5_AFMT_RAMP_CONTROL1                                               0x4f3c
#define mmDIG6_AFMT_RAMP_CONTROL1                                               0x543c
#define mmDIG7_AFMT_RAMP_CONTROL1                                               0x563c
#define mmDIG8_AFMT_RAMP_CONTROL1                                               0x573c
#define mmAFMT_RAMP_CONTROL2                                                    0x4a3d
#define mmDIG0_AFMT_RAMP_CONTROL2                                               0x4a3d
#define mmDIG1_AFMT_RAMP_CONTROL2                                               0x4b3d
#define mmDIG2_AFMT_RAMP_CONTROL2                                               0x4c3d
#define mmDIG3_AFMT_RAMP_CONTROL2                                               0x4d3d
#define mmDIG4_AFMT_RAMP_CONTROL2                                               0x4e3d
#define mmDIG5_AFMT_RAMP_CONTROL2                                               0x4f3d
#define mmDIG6_AFMT_RAMP_CONTROL2                                               0x543d
#define mmDIG7_AFMT_RAMP_CONTROL2                                               0x563d
#define mmDIG8_AFMT_RAMP_CONTROL2                                               0x573d
#define mmAFMT_RAMP_CONTROL3                                                    0x4a3e
#define mmDIG0_AFMT_RAMP_CONTROL3                                               0x4a3e
#define mmDIG1_AFMT_RAMP_CONTROL3                                               0x4b3e
#define mmDIG2_AFMT_RAMP_CONTROL3                                               0x4c3e
#define mmDIG3_AFMT_RAMP_CONTROL3                                               0x4d3e
#define mmDIG4_AFMT_RAMP_CONTROL3                                               0x4e3e
#define mmDIG5_AFMT_RAMP_CONTROL3                                               0x4f3e
#define mmDIG6_AFMT_RAMP_CONTROL3                                               0x543e
#define mmDIG7_AFMT_RAMP_CONTROL3                                               0x563e
#define mmDIG8_AFMT_RAMP_CONTROL3                                               0x573e
#define mmAFMT_60958_2                                                          0x4a3f
#define mmDIG0_AFMT_60958_2                                                     0x4a3f
#define mmDIG1_AFMT_60958_2                                                     0x4b3f
#define mmDIG2_AFMT_60958_2                                                     0x4c3f
#define mmDIG3_AFMT_60958_2                                                     0x4d3f
#define mmDIG4_AFMT_60958_2                                                     0x4e3f
#define mmDIG5_AFMT_60958_2                                                     0x4f3f
#define mmDIG6_AFMT_60958_2                                                     0x543f
#define mmDIG7_AFMT_60958_2                                                     0x563f
#define mmDIG8_AFMT_60958_2                                                     0x573f
#define mmAFMT_AUDIO_CRC_RESULT                                                 0x4a40
#define mmDIG0_AFMT_AUDIO_CRC_RESULT                                            0x4a40
#define mmDIG1_AFMT_AUDIO_CRC_RESULT                                            0x4b40
#define mmDIG2_AFMT_AUDIO_CRC_RESULT                                            0x4c40
#define mmDIG3_AFMT_AUDIO_CRC_RESULT                                            0x4d40
#define mmDIG4_AFMT_AUDIO_CRC_RESULT                                            0x4e40
#define mmDIG5_AFMT_AUDIO_CRC_RESULT                                            0x4f40
#define mmDIG6_AFMT_AUDIO_CRC_RESULT                                            0x5440
#define mmDIG7_AFMT_AUDIO_CRC_RESULT                                            0x5640
#define mmDIG8_AFMT_AUDIO_CRC_RESULT                                            0x5740
#define mmAFMT_STATUS                                                           0x4a41
#define mmDIG0_AFMT_STATUS                                                      0x4a41
#define mmDIG1_AFMT_STATUS                                                      0x4b41
#define mmDIG2_AFMT_STATUS                                                      0x4c41
#define mmDIG3_AFMT_STATUS                                                      0x4d41
#define mmDIG4_AFMT_STATUS                                                      0x4e41
#define mmDIG5_AFMT_STATUS                                                      0x4f41
#define mmDIG6_AFMT_STATUS                                                      0x5441
#define mmDIG7_AFMT_STATUS                                                      0x5641
#define mmDIG8_AFMT_STATUS                                                      0x5741
#define mmAFMT_AUDIO_PACKET_CONTROL                                             0x4a42
#define mmDIG0_AFMT_AUDIO_PACKET_CONTROL                                        0x4a42
#define mmDIG1_AFMT_AUDIO_PACKET_CONTROL                                        0x4b42
#define mmDIG2_AFMT_AUDIO_PACKET_CONTROL                                        0x4c42
#define mmDIG3_AFMT_AUDIO_PACKET_CONTROL                                        0x4d42
#define mmDIG4_AFMT_AUDIO_PACKET_CONTROL                                        0x4e42
#define mmDIG5_AFMT_AUDIO_PACKET_CONTROL                                        0x4f42
#define mmDIG6_AFMT_AUDIO_PACKET_CONTROL                                        0x5442
#define mmDIG7_AFMT_AUDIO_PACKET_CONTROL                                        0x5642
#define mmDIG8_AFMT_AUDIO_PACKET_CONTROL                                        0x5742
#define mmAFMT_VBI_PACKET_CONTROL                                               0x4a43
#define mmDIG0_AFMT_VBI_PACKET_CONTROL                                          0x4a43
#define mmDIG1_AFMT_VBI_PACKET_CONTROL                                          0x4b43
#define mmDIG2_AFMT_VBI_PACKET_CONTROL                                          0x4c43
#define mmDIG3_AFMT_VBI_PACKET_CONTROL                                          0x4d43
#define mmDIG4_AFMT_VBI_PACKET_CONTROL                                          0x4e43
#define mmDIG5_AFMT_VBI_PACKET_CONTROL                                          0x4f43
#define mmDIG6_AFMT_VBI_PACKET_CONTROL                                          0x5443
#define mmDIG7_AFMT_VBI_PACKET_CONTROL                                          0x5643
#define mmDIG8_AFMT_VBI_PACKET_CONTROL                                          0x5743
#define mmAFMT_INFOFRAME_CONTROL0                                               0x4a44
#define mmDIG0_AFMT_INFOFRAME_CONTROL0                                          0x4a44
#define mmDIG1_AFMT_INFOFRAME_CONTROL0                                          0x4b44
#define mmDIG2_AFMT_INFOFRAME_CONTROL0                                          0x4c44
#define mmDIG3_AFMT_INFOFRAME_CONTROL0                                          0x4d44
#define mmDIG4_AFMT_INFOFRAME_CONTROL0                                          0x4e44
#define mmDIG5_AFMT_INFOFRAME_CONTROL0                                          0x4f44
#define mmDIG6_AFMT_INFOFRAME_CONTROL0                                          0x5444
#define mmDIG7_AFMT_INFOFRAME_CONTROL0                                          0x5644
#define mmDIG8_AFMT_INFOFRAME_CONTROL0                                          0x5744
#define mmAFMT_AUDIO_SRC_CONTROL                                                0x4a45
#define mmDIG0_AFMT_AUDIO_SRC_CONTROL                                           0x4a45
#define mmDIG1_AFMT_AUDIO_SRC_CONTROL                                           0x4b45
#define mmDIG2_AFMT_AUDIO_SRC_CONTROL                                           0x4c45
#define mmDIG3_AFMT_AUDIO_SRC_CONTROL                                           0x4d45
#define mmDIG4_AFMT_AUDIO_SRC_CONTROL                                           0x4e45
#define mmDIG5_AFMT_AUDIO_SRC_CONTROL                                           0x4f45
#define mmDIG6_AFMT_AUDIO_SRC_CONTROL                                           0x5445
#define mmDIG7_AFMT_AUDIO_SRC_CONTROL                                           0x5645
#define mmDIG8_AFMT_AUDIO_SRC_CONTROL                                           0x5745
#define mmAFMT_AUDIO_DBG_DTO_CNTL                                               0x4a46
#define mmDIG0_AFMT_AUDIO_DBG_DTO_CNTL                                          0x4a46
#define mmDIG1_AFMT_AUDIO_DBG_DTO_CNTL                                          0x4b46
#define mmDIG2_AFMT_AUDIO_DBG_DTO_CNTL                                          0x4c46
#define mmDIG3_AFMT_AUDIO_DBG_DTO_CNTL                                          0x4d46
#define mmDIG4_AFMT_AUDIO_DBG_DTO_CNTL                                          0x4e46
#define mmDIG5_AFMT_AUDIO_DBG_DTO_CNTL                                          0x4f46
#define mmDIG6_AFMT_AUDIO_DBG_DTO_CNTL                                          0x5446
#define mmDIG7_AFMT_AUDIO_DBG_DTO_CNTL                                          0x5646
#define mmDIG8_AFMT_AUDIO_DBG_DTO_CNTL                                          0x5746
#define mmAFMT_CNTL                                                             0x4a7e
#define mmDIG0_AFMT_CNTL                                                        0x4a7e
#define mmDIG1_AFMT_CNTL                                                        0x4b7e
#define mmDIG2_AFMT_CNTL                                                        0x4c7e
#define mmDIG3_AFMT_CNTL                                                        0x4d7e
#define mmDIG4_AFMT_CNTL                                                        0x4e7e
#define mmDIG5_AFMT_CNTL                                                        0x4f7e
#define mmDIG6_AFMT_CNTL                                                        0x547e
#define mmDIG7_AFMT_CNTL                                                        0x567e
#define mmDIG8_AFMT_CNTL                                                        0x577e
#define mmDIG_BE_CNTL                                                           0x4a47
#define mmDIG0_DIG_BE_CNTL                                                      0x4a47
#define mmDIG1_DIG_BE_CNTL                                                      0x4b47
#define mmDIG2_DIG_BE_CNTL                                                      0x4c47
#define mmDIG3_DIG_BE_CNTL                                                      0x4d47
#define mmDIG4_DIG_BE_CNTL                                                      0x4e47
#define mmDIG5_DIG_BE_CNTL                                                      0x4f47
#define mmDIG6_DIG_BE_CNTL                                                      0x5447
#define mmDIG7_DIG_BE_CNTL                                                      0x5647
#define mmDIG8_DIG_BE_CNTL                                                      0x5747
#define mmDIG_BE_EN_CNTL                                                        0x4a48
#define mmDIG0_DIG_BE_EN_CNTL                                                   0x4a48
#define mmDIG1_DIG_BE_EN_CNTL                                                   0x4b48
#define mmDIG2_DIG_BE_EN_CNTL                                                   0x4c48
#define mmDIG3_DIG_BE_EN_CNTL                                                   0x4d48
#define mmDIG4_DIG_BE_EN_CNTL                                                   0x4e48
#define mmDIG5_DIG_BE_EN_CNTL                                                   0x4f48
#define mmDIG6_DIG_BE_EN_CNTL                                                   0x5448
#define mmDIG7_DIG_BE_EN_CNTL                                                   0x5648
#define mmDIG8_DIG_BE_EN_CNTL                                                   0x5748
#define mmTMDS_CNTL                                                             0x4a6b
#define mmDIG0_TMDS_CNTL                                                        0x4a6b
#define mmDIG1_TMDS_CNTL                                                        0x4b6b
#define mmDIG2_TMDS_CNTL                                                        0x4c6b
#define mmDIG3_TMDS_CNTL                                                        0x4d6b
#define mmDIG4_TMDS_CNTL                                                        0x4e6b
#define mmDIG5_TMDS_CNTL                                                        0x4f6b
#define mmDIG6_TMDS_CNTL                                                        0x546b
#define mmDIG7_TMDS_CNTL                                                        0x566b
#define mmDIG8_TMDS_CNTL                                                        0x576b
#define mmTMDS_CONTROL_CHAR                                                     0x4a6c
#define mmDIG0_TMDS_CONTROL_CHAR                                                0x4a6c
#define mmDIG1_TMDS_CONTROL_CHAR                                                0x4b6c
#define mmDIG2_TMDS_CONTROL_CHAR                                                0x4c6c
#define mmDIG3_TMDS_CONTROL_CHAR                                                0x4d6c
#define mmDIG4_TMDS_CONTROL_CHAR                                                0x4e6c
#define mmDIG5_TMDS_CONTROL_CHAR                                                0x4f6c
#define mmDIG6_TMDS_CONTROL_CHAR                                                0x546c
#define mmDIG7_TMDS_CONTROL_CHAR                                                0x566c
#define mmDIG8_TMDS_CONTROL_CHAR                                                0x576c
#define mmTMDS_CONTROL0_FEEDBACK                                                0x4a6d
#define mmDIG0_TMDS_CONTROL0_FEEDBACK                                           0x4a6d
#define mmDIG1_TMDS_CONTROL0_FEEDBACK                                           0x4b6d
#define mmDIG2_TMDS_CONTROL0_FEEDBACK                                           0x4c6d
#define mmDIG3_TMDS_CONTROL0_FEEDBACK                                           0x4d6d
#define mmDIG4_TMDS_CONTROL0_FEEDBACK                                           0x4e6d
#define mmDIG5_TMDS_CONTROL0_FEEDBACK                                           0x4f6d
#define mmDIG6_TMDS_CONTROL0_FEEDBACK                                           0x546d
#define mmDIG7_TMDS_CONTROL0_FEEDBACK                                           0x566d
#define mmDIG8_TMDS_CONTROL0_FEEDBACK                                           0x576d
#define mmTMDS_STEREOSYNC_CTL_SEL                                               0x4a6e
#define mmDIG0_TMDS_STEREOSYNC_CTL_SEL                                          0x4a6e
#define mmDIG1_TMDS_STEREOSYNC_CTL_SEL                                          0x4b6e
#define mmDIG2_TMDS_STEREOSYNC_CTL_SEL                                          0x4c6e
#define mmDIG3_TMDS_STEREOSYNC_CTL_SEL                                          0x4d6e
#define mmDIG4_TMDS_STEREOSYNC_CTL_SEL                                          0x4e6e
#define mmDIG5_TMDS_STEREOSYNC_CTL_SEL                                          0x4f6e
#define mmDIG6_TMDS_STEREOSYNC_CTL_SEL                                          0x546e
#define mmDIG7_TMDS_STEREOSYNC_CTL_SEL                                          0x566e
#define mmDIG8_TMDS_STEREOSYNC_CTL_SEL                                          0x576e
#define mmTMDS_SYNC_CHAR_PATTERN_0_1                                            0x4a6f
#define mmDIG0_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x4a6f
#define mmDIG1_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x4b6f
#define mmDIG2_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x4c6f
#define mmDIG3_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x4d6f
#define mmDIG4_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x4e6f
#define mmDIG5_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x4f6f
#define mmDIG6_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x546f
#define mmDIG7_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x566f
#define mmDIG8_TMDS_SYNC_CHAR_PATTERN_0_1                                       0x576f
#define mmTMDS_SYNC_CHAR_PATTERN_2_3                                            0x4a70
#define mmDIG0_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x4a70
#define mmDIG1_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x4b70
#define mmDIG2_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x4c70
#define mmDIG3_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x4d70
#define mmDIG4_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x4e70
#define mmDIG5_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x4f70
#define mmDIG6_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x5470
#define mmDIG7_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x5670
#define mmDIG8_TMDS_SYNC_CHAR_PATTERN_2_3                                       0x5770
#define mmTMDS_DEBUG                                                            0x4a71
#define mmDIG0_TMDS_DEBUG                                                       0x4a71
#define mmDIG1_TMDS_DEBUG                                                       0x4b71
#define mmDIG2_TMDS_DEBUG                                                       0x4c71
#define mmDIG3_TMDS_DEBUG                                                       0x4d71
#define mmDIG4_TMDS_DEBUG                                                       0x4e71
#define mmDIG5_TMDS_DEBUG                                                       0x4f71
#define mmDIG6_TMDS_DEBUG                                                       0x5471
#define mmDIG7_TMDS_DEBUG                                                       0x5671
#define mmDIG8_TMDS_DEBUG                                                       0x5771
#define mmTMDS_CTL_BITS                                                         0x4a72
#define mmDIG0_TMDS_CTL_BITS                                                    0x4a72
#define mmDIG1_TMDS_CTL_BITS                                                    0x4b72
#define mmDIG2_TMDS_CTL_BITS                                                    0x4c72
#define mmDIG3_TMDS_CTL_BITS                                                    0x4d72
#define mmDIG4_TMDS_CTL_BITS                                                    0x4e72
#define mmDIG5_TMDS_CTL_BITS                                                    0x4f72
#define mmDIG6_TMDS_CTL_BITS                                                    0x5472
#define mmDIG7_TMDS_CTL_BITS                                                    0x5672
#define mmDIG8_TMDS_CTL_BITS                                                    0x5772
#define mmTMDS_DCBALANCER_CONTROL                                               0x4a73
#define mmDIG0_TMDS_DCBALANCER_CONTROL                                          0x4a73
#define mmDIG1_TMDS_DCBALANCER_CONTROL                                          0x4b73
#define mmDIG2_TMDS_DCBALANCER_CONTROL                                          0x4c73
#define mmDIG3_TMDS_DCBALANCER_CONTROL                                          0x4d73
#define mmDIG4_TMDS_DCBALANCER_CONTROL                                          0x4e73
#define mmDIG5_TMDS_DCBALANCER_CONTROL                                          0x4f73
#define mmDIG6_TMDS_DCBALANCER_CONTROL                                          0x5473
#define mmDIG7_TMDS_DCBALANCER_CONTROL                                          0x5673
#define mmDIG8_TMDS_DCBALANCER_CONTROL                                          0x5773
#define mmTMDS_CTL0_1_GEN_CNTL                                                  0x4a75
#define mmDIG0_TMDS_CTL0_1_GEN_CNTL                                             0x4a75
#define mmDIG1_TMDS_CTL0_1_GEN_CNTL                                             0x4b75
#define mmDIG2_TMDS_CTL0_1_GEN_CNTL                                             0x4c75
#define mmDIG3_TMDS_CTL0_1_GEN_CNTL                                             0x4d75
#define mmDIG4_TMDS_CTL0_1_GEN_CNTL                                             0x4e75
#define mmDIG5_TMDS_CTL0_1_GEN_CNTL                                             0x4f75
#define mmDIG6_TMDS_CTL0_1_GEN_CNTL                                             0x5475
#define mmDIG7_TMDS_CTL0_1_GEN_CNTL                                             0x5675
#define mmDIG8_TMDS_CTL0_1_GEN_CNTL                                             0x5775
#define mmTMDS_CTL2_3_GEN_CNTL                                                  0x4a76
#define mmDIG0_TMDS_CTL2_3_GEN_CNTL                                             0x4a76
#define mmDIG1_TMDS_CTL2_3_GEN_CNTL                                             0x4b76
#define mmDIG2_TMDS_CTL2_3_GEN_CNTL                                             0x4c76
#define mmDIG3_TMDS_CTL2_3_GEN_CNTL                                             0x4d76
#define mmDIG4_TMDS_CTL2_3_GEN_CNTL                                             0x4e76
#define mmDIG5_TMDS_CTL2_3_GEN_CNTL                                             0x4f76
#define mmDIG6_TMDS_CTL2_3_GEN_CNTL                                             0x5476
#define mmDIG7_TMDS_CTL2_3_GEN_CNTL                                             0x5676
#define mmDIG8_TMDS_CTL2_3_GEN_CNTL                                             0x5776
#define mmDIG_VERSION                                                           0x4a78
#define mmDIG0_DIG_VERSION                                                      0x4a78
#define mmDIG1_DIG_VERSION                                                      0x4b78
#define mmDIG2_DIG_VERSION                                                      0x4c78
#define mmDIG3_DIG_VERSION                                                      0x4d78
#define mmDIG4_DIG_VERSION                                                      0x4e78
#define mmDIG5_DIG_VERSION                                                      0x4f78
#define mmDIG6_DIG_VERSION                                                      0x5478
#define mmDIG7_DIG_VERSION                                                      0x5678
#define mmDIG8_DIG_VERSION                                                      0x577