 mmDCP2_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x1ebf
#define mmDCP3_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x40bf
#define mmDCP4_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x42bf
#define mmDCP5_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x44bf
#define mmGRPH_SURFACE_COUNTER_CONTROL                                          0x1a0f
#define mmDCP0_GRPH_SURFACE_COUNTER_CONTROL                                     0x1a0f
#define mmDCP1_GRPH_SURFACE_COUNTER_CONTROL                                     0x1c0f
#define mmDCP2_GRPH_SURFACE_COUNTER_CONTROL                                     0x1e0f
#define mmDCP3_GRPH_SURFACE_COUNTER_CONTROL                                     0x400f
#define mmDCP4_GRPH_SURFACE_COUNTER_CONTROL                                     0x420f
#define mmDCP5_GRPH_SURFACE_COUNTER_CONTROL                                     0x440f
#define mmGRPH_SURFACE_COUNTER_OUTPUT                                           0x1a1d
#define mmDCP0_GRPH_SURFACE_COUNTER_OUTPUT                                      0x1a1d
#define mmDCP1_GRPH_SURFACE_COUNTER_OUTPUT                                      0x1c1d
#define mmDCP2_GRPH_SURFACE_COUNTER_OUTPUT                                      0x1e1d
#define mmDCP3_GRPH_SURFACE_COUNTER_OUTPUT                                      0x401d
#define mmDCP4_GRPH_SURFACE_COUNTER_OUTPUT                                      0x421d
#define mmDCP5_GRPH_SURFACE_COUNTER_OUTPUT                                      0x441d
#define mmDIG_FE_CNTL                                                           0x4a00
#define mmDIG0_DIG_FE_CNTL                                                      0x4a00
#define mmDIG1_DIG_FE_CNTL                                                      0x4b00
#define mmDIG2_DIG_FE_CNTL                                                      0x4c00
#define mmDIG3_DIG_FE_CNTL                                                      0x4d00
#define mmDIG4_DIG_FE_CNTL                                                      0x4e00
#define mmDIG5_DIG_FE_CNTL                                                      0x4f00
#define mmDIG6_DIG_FE_CNTL                                                      0x5400
#define mmDIG7_DIG_FE_CNTL                                                      0x5600
#define mmDIG8_DIG_FE_CNTL                                                      0x5700
#define mmDIG_OUTPUT_CRC_CNTL                                                   0x4a01
#define mmDIG0_DIG_OUTPUT_CRC_CNTL                                              0x4a01
#define mmDIG1_DIG_OUTPUT_CRC_CNTL                                              0x4b01
#define mmDIG2_DIG_OUTPUT_CRC_CNTL                                              0x4c01
#define mmDIG3_DIG_OUTPUT_CRC_CNTL                                              0x4d01
#define mmDIG4_DIG_OUTPUT_CRC_CNTL                                              0x4e01
#define mmDIG5_DIG_OUTPUT_CRC_CNTL                                              0x4f01
#define mmDIG6_DIG_OUTPUT_CRC_CNTL                                              0x5401
#define mmDIG7_DIG_OUTPUT_CRC_CNTL                                              0x5601
#define mmDIG8_DIG_OUTPUT_CRC_CNTL                                              0x5701
#define mmDIG_OUTPUT_CRC_RESULT                                                 0x4a02
#define mmDIG0_DIG_OUTPUT_CRC_RESULT                                            0x4a02
#define mmDIG1_DIG_OUTPUT_CRC_RESULT                                            0x4b02
#define mmDIG2_DIG_OUTPUT_CRC_RESULT                                            0x4c02
#define mmDIG3_DIG_OUTPUT_CRC_RESULT                                            0x4d02
#define mmDIG4_DIG_OUTPUT_CRC_RESULT                                            0x4e02
#define mmDIG5_DIG_OUTPUT_CRC_RESULT                                            0x4f02
#define mmDIG6_DIG_OUTPUT_CRC_RESULT                                            0x5402
#define mmDIG7_DIG_OUTPUT_CRC_RESULT                                            0x5602
#define mmDIG8_DIG_OUTPUT_CRC_RESULT                                            0x5702
#define mmDIG_CLOCK_PATTERN                                                     0x4a03
#define mmDIG0_DIG_CLOCK_PATTERN                                                0x4a03
#define mmDIG1_DIG_CLOCK_PATTERN                                                0x4b03
#define mmDIG2_DIG_CLOCK_PATTERN                                                0x4c03
#define mmDIG3_DIG_CLOCK_PATTERN                                                0x4d03
#define mmDIG4_DIG_CLOCK_PATTERN                                                0x4e03
#define mmDIG5_DIG_CLOCK_PATTERN                                                0x4f03
#define mmDIG6_DIG_CLOCK_PATTERN                                                0x5403
#define mmDIG7_DIG_CLOCK_PATTERN                                                0x5603
#define mmDIG8_DIG_CLOCK_PATTERN                                                0x5703
#define mmDIG_TEST_PATTERN                                                      0x4a04
#define mmDIG0_DIG_TEST_PATTERN                                                 0x4a04
#define mmDIG1_DIG_TEST_PATTERN                                                 0x4b04
#define mmDIG2_DIG_TEST_PATTERN                                                 0x4c04
#define mmDIG3_DIG_TEST_PATTERN                                                 0x4d04
#define mmDIG4_DIG_TEST_PATTERN                                                 0x4e04
#define mmDIG5_DIG_TEST_PATTERN                                                 0x4f04
#define mmDIG6_DIG_TEST_PATTERN                                                 0x5404
#define mmDIG7_DIG_TEST_PATTERN                                                 0x5604
#define mmDIG8_DIG_TEST_PATTERN                                                 0x5704
#define mmDIG_RANDOM_PATTERN_SEED                                               0x4a05
#define mmDIG0_DIG_RANDOM_PATTERN_SEED                                          0x4a05
#define mmDIG1_DIG_RANDOM_PATTERN_SEED                                          0x4b05
#define mmDIG2_DIG_RANDOM_PATTERN_SEED                                          0x4c05
#define mmDIG3_DIG_RANDOM_PATTERN_SEED                                          0x4d05
#define mmDIG4_DIG_RANDOM_PATTERN_SEED                                          0x4e05
#define mmDIG5_DIG_RANDOM_PATTERN_SEED                                          0x4f05
#define mmDIG6_DIG_RANDOM_PATTERN_SEED                                          0x5405
#define mmDIG7_DIG_RANDOM_PATTERN_SEED                                          0x5605
#define mmDIG8_DIG_RANDOM_PATTERN_SEED                                          0x5705
#define mmDIG_FIFO_STATUS                                                       0x4a06
#define mmDIG0_DIG_FIFO_STATUS                                                  0x4a06
#define mmDIG1_DIG_FIFO_STATUS                                                  0x4b06
#define mmDIG2_DIG_FIFO_STATUS                                                  0x4c06
#define mmDIG3_DIG_FIFO_STATUS                                                  0x4d06
#define mmDIG4_DIG_FIFO_STATUS                                                  0x4e06
#define mmDIG5_DIG_FIFO_STATUS                                                  0x4f06
#define mmDIG6_DIG_FIFO_STATUS                                                  0x5406
#define mmDIG7_DIG_FIFO_STATUS                                                  0x5606
#define mmDIG8_DIG_FIFO_STATUS                                                  0x5706
#define mmDIG_DISPCLK_SWITCH_CNTL                                               0x4a07
#define mmDIG0_DIG_DISPCLK_SWITCH_CNTL                                          0x4a07
#define mmDIG1_DIG_DISPCLK_SWITCH_CNTL                                          0x4b07
#define mmDIG2_DIG_DISPCLK_SWITCH_CNTL                                          0x4c07
#define mmDIG3_DIG_DISPCLK_SWITCH_CNTL                                          0x4d07
#define mmDIG4_DIG_DISPCLK_SWITCH_CNTL                                          0x4e07
#define mmDIG5_DIG_DISPCLK_SWITCH_CNTL                                          0x4f07
#define mmDIG6_DIG_DISPCLK_SWITCH_CNTL                                          0x5407
#define mmDIG7_DIG_DISPCLK_SWITCH_CNTL                                          0x5607
#define mmDIG8_DIG_DISPCLK_SWITCH_CNTL                                          0x5707
#define mmDIG_DISPCLK_SWITCH_STATUS                                             0x4a08
#define mmDIG0_DIG_DISPCLK_SWITCH_STATUS                                        0x4a08
#define mmDIG1_DIG_DISPCLK_SWITCH_STATUS                                        0x4b08
#define mmDIG2_DIG_DISPCLK_SWITCH_STATUS                                        0x4c08
#define mmDIG3_DIG_DISPCLK_SWITCH_STATUS                                        0x4d08
#define mmDIG4_DIG_DISPCLK_SWITCH_STATUS                                        0x4e08
#define mmDIG5_DIG_DISPCLK_SWITCH_STATUS                                        0x4f08
#define mmDIG6_DIG_DISPCLK_SWITCH_STATUS                                        0x5408
#define mmDIG7_DIG_DISPCLK_SWITCH_STATUS                                        0x5608
#define mmDIG8_DIG_DISPCLK_SWITCH_STATUS                                        0x5708
#define mmHDMI_CONTROL                                                          0x4a09
#define mmDIG0_HDMI_CONTROL                                                     0x4a09
#define mmDIG1_HDMI_CONTROL                                                     0x4b09
#define mmDIG2_HDMI_CONTROL                                                     0x4c09
#define mmDIG3_HDMI_CONTROL                                                     0x4d09
#define mmDIG4_HDMI_CONTROL                                                     0x4e09
#define mmDIG5_HDMI_CONTROL                                                     0x4f09
#define mmDIG6_HDMI_CONTROL                                                     0x5409
#define mmDIG7_HDMI_CONTROL                                                     0x5609
#define mmDIG8_HDMI_CONTROL                                                     0x5709
#define mmHDMI_STATUS                                                           0x4a0a
#define mmDIG0_HDMI_STATUS                                                      0x4a0a
#define mmDIG1_HDMI_STATUS                                                      0x4b0a
#define mmDIG2_HDMI_STATUS                                                      0x4c0a
#define mmDIG3_HDMI_STATUS                                                      0x4d0a
#define mmDIG4_HDMI_STATUS                                                      0x4e0a
#define mmDIG5_HDMI_STATUS                                                      0x4f0a
#define mmDIG6_HDMI_STATUS                                                      0x540a
#define mmDIG7_HDMI_STATUS                                                      0x560a
#define mmDIG8_HDMI_STATUS                                                      0x570a
#define mmHDMI_AUDIO_PACKET_CONTROL                                             0x4a0b
#define mmDIG0_HDMI_AUDIO_PACKET_CONTROL                                        0x4a0b
#define mmDIG1_HDMI_AUDIO_PACKET_CONTROL                                        0x4b0b
#define mmDIG2_HDMI_AUDIO_PACKET_CONTROL                                        0x4c0b
#define mmDIG3_HDMI_AUDIO_PACKET_CONTROL                                        0x4d0b
#define mmDIG4_HDMI_AUDIO_PACKET_CONTROL                                        0x4e0b
#define mmDIG5_HDMI_AUDIO_PACKET_CONTROL                                        0x4f0b
#define mmDIG6_HDMI_AUDIO_PACKET_CONTROL                                        0x540b
#define mmDIG7_HDMI_AUDIO_PACKET_CONTROL                                        0x560b
#define mmDIG8_HDMI_AUDIO_PACKET_CONTROL                                        0x570b
#define mmHDMI_ACR_PACKET_CONTROL                                               0x4a0c
#define mmDIG0_HDMI_ACR_PACKET_CONTROL                                          0x4a0c
#define mmDIG1_HDMI_ACR_PACKET_CONTROL                                          0x4b0c
#define mmDIG2_HDMI_ACR_PACKET_CONTROL                                          0x4c0c
#define mmDIG3_HDMI_ACR_PACKET_CONTROL                                          0x4d0c
#define mmDIG4_HDMI_ACR_PACKET_CONTROL                                          0x4e0c
#define mmDIG5_HDMI_ACR_PACKET_CONTROL                                          0x4f0c
#define mmDIG6_HDMI_ACR_PACKET_CONTROL                                          0x540c
#define mmDIG7_HDMI_ACR_PACKET_CONTROL                                          0x560c
#define mmDIG8_HDMI_ACR_PACKET_CONTROL                                          0x570c
#define mmHDMI_VBI_PACKET_CONTROL                                               0x4a0d
#define mmDIG0_HDMI_VBI_PACKET_CONTROL                                          0x4a0d
#define mmDIG1_HDMI_VBI_PACKET_CONTROL                                          0x4b0d
#define mmDIG2_HDMI_VBI_PACKET_CONTROL                                          0x4c0d
#define mmDIG3_HDMI_VBI_PACKET_CONTROL                                          0x4d0d
#define mmDIG4_HDMI_VBI_PACKET_CONTROL                                          0x4e0d
#define mmDIG5_HDMI_VBI_PACKET_CONTROL                                          0x4f0d
#define mmDIG6_HDMI_VBI_PACKET_CONTROL                                          0x540d
#define mmDIG7_HDMI_VBI_PACKET_CONTROL                                          0x560d
#define mmDIG8_HDMI_VBI_PACKET_CONTROL                                          0x570d
#define mmHDMI_INFOFRAME_CONTROL0                                               0x4a0e
#define mmDIG0_HDMI_INFOFRAME_CONTROL0                                          0x4a0e
#define mmDIG1_HDMI_INFOFRAME_CONTROL0                                          0x4b0e
#define mmDIG2_HDMI_INFOFRAME_CONTROL0                                          0x4c0e
#define mmDIG3_HDMI_INFOFRAME_CONTROL0                                          0x4d0e
#define mmDIG4_HDMI_INFOFRAME_CONTROL0                                          0x4e0e
#define mmDIG5_HDMI_INFOFRAME_CONTROL0                                          0x4f0e
#define mmDIG6_HDMI_INFOFRAME_CONTROL0                                          0x540e
#define mmDIG7_HDMI_INFOFRAME_CONTROL0                                          0x560e
#define mmDIG8_HDMI_INFOFRAME_CONTROL0                                          0x570e
#define mmHDMI_INFOFRAME_CONTROL1                                               0x4a0f
#define mmDIG0_HDMI_INFOFRAME_CONTROL1                                          0x4a0f
#define mmDIG1_HDMI_INFOFRAME_CONTROL1                                          0x4b0f
#define mmDIG2_HDMI_INFOFRAME_CONTROL1                                          0x4c0f
#define mmDIG3_HDMI_INFOFRAME_CONTROL1                                          0x4d0f
#define mmDIG4_HDMI_INFOFRAME_CONTROL1                                          0x4e0f
#define mmDIG5_HDMI_INFOFRAME_CONTROL1                                          0x4f0f
#define mmDIG6_HDMI_INFOFRAME_CONTROL1                                          0x540f
#define mmDIG7_HDMI_INFOFRAME_CONTROL1                                          0x560f
#define mmDIG8_HDMI_INFOFRAME_CONTROL1                                          0x570f
#define mmHDMI_GENERIC_PACKET_CONTROL0                                          0x4a10
#define mmDIG0_HDMI_GENERIC_PACKET_CONTROL0                                     0x4a10
#define mmDIG1_HDMI_GENERIC_PACKET_CONTROL0                                     0x4b10
#define mmDIG2_HDMI_GENERIC_PACKET_CONTROL0                                     0x4c10
#define mmDIG3_HDMI_GENERIC_PACKET_CONTROL0                                     0x4d10
#define mmDIG4_HDMI_GENERIC_PACKET_CONTROL0                                     0x4e10
#define mmDIG5_HDMI_GENERIC_PACKET_CONTROL0                                     0x4f10
#define mmDIG6_HDMI_GENERIC_PACKET_CONTROL0                                     0x5410
#define mmDIG7_HDMI_GENERIC_PACKET_CONTROL0                                     0x5610
#define mmDIG8_HDMI_GENERIC_PACKET_CONTROL0                                     0x5710
#define mmAFMT_INTERRUPT_STATUS                                                 0x4a11
#define mmDIG0_AFMT_INTERRUPT_STATUS                                            0x4a11
#define mmDIG1_AFMT_INTERRUPT_STATUS                                            0x4b11
#define mmDIG2_AFMT_INTERRUPT_STATUS                                            0x4c11
#define mmDIG3_AFMT_INTERRUPT_STATUS                                            0x4d11
#define mmDIG4_AFMT_INTERRUPT_STATUS                                            0x4e11
#define mmDIG5_AFMT_INTERRUPT_STATUS                                            0x4f11
#define mmDIG6_AFMT_INTERRUPT_STATUS                                            0x5411
#define mmDIG7_AFMT_INTERRUPT_STATUS                                            0x5611
#define mmDIG8_AFMT_INTERRUPT_STATUS                                            0x5711
#define mmHDMI_GC                                                               0x4a13
#define mmDIG0_HDMI_GC                                                          0x4a13
#define mmDIG1_HDMI_GC                                                          0x4b13
#define mmDIG2_HDMI_GC                                                          0x4c13
#define mmDIG3_HDMI_GC                                                          0x4d13
#define mmDIG4_HDMI_GC                                                          0x4e13
#define mmDIG5_HDMI_GC                                                          0x4f13
#define mmDIG6_HDMI_GC                                                          0x5413
#define mmDIG7_HDMI_GC                                                          0x5613
#define mmDIG8_HDMI_GC                                                          0x5713
#define mmAFMT_AUDIO_PACKET_CONTROL2                                            0x4a14
#define mmDIG0_AFMT_AUDIO_PACKET_CONTROL2                                       0x4a14
#define mmDIG1_AFMT_AUDIO_PACKET_CONTROL2                                       0x4b14
#define mmDIG2_AFMT_AUDIO_PACKET_CONTROL2                                       0x4c14
#define mmDIG3_AFMT_AUDIO_PACKET_CONTROL2                                       0x4d14
#define mmDIG4_AFMT_AUDIO_PACKET_CONTROL2                                       0x4e14
#define mmDIG5_AFMT_AUDIO_PACKET_CONTROL2                                       0x4f14
#define mmDIG6_AFMT_AUDIO_PACKET_CONTROL2                                       0x5414
#define mmDIG7_AFMT_AUDIO_PACKET_CONTROL2                                       0x5614
#define mmDIG8_AFMT_AUDIO_PACKET_CONTROL2                                       0x5714
#define mmAFMT_ISRC1_0                                                          0x4a15
#define mmDIG0_AFMT_ISRC1_0                                                     0x4a15
#define mmDIG1_AFMT_ISRC1_0                                                     0x4b15
#define mmDIG2_AFMT_ISRC1_0                                                     0x4c15
#define mmDIG3_AFMT_ISRC1_0                                                     0x4d15
#define mmDIG4_AFMT_ISRC1_0                                                     0x4e15
#define mmDIG5_AFMT_ISRC1_0                                                     0x4f15
#define mmDIG6_AFMT_ISRC1_0                                                     0x5415
#define mmDIG7_AFMT_ISRC1_0                                                     0x5615
#define mmDIG8_AFMT_ISRC1_0                                                     0x5715
#define mmAFMT_ISRC1_1                                                          0x4a16
#define mmDIG0_AFMT_ISRC1_1                                                     0x4a16
#define mmDIG1_AFMT_ISRC1_1                                                     0x4b16
#define mmDIG2_AFMT_ISRC1_1                                                     0x4c16
#define mmDIG3_AFMT_ISRC1_1                                                     0x4d16
#define mmDIG4_AFMT_ISRC1_1                                                     0x4e16
#define mmDIG5_AFMT_ISRC1_1                                                     0x4f16
#define mmDIG6_AFMT_ISRC1_1                                                     0x5416
#define mmDIG7_AFMT_ISRC1_1                                                     0x5616
#define mmDIG8_AFMT_ISRC1_1                                                     0x5716
#define mmAFMT_ISRC1_2                                                          0x4a17
#define mmDIG0_AFMT_ISRC1_2                                                     0x4a17
#define mmDIG1_AFMT_ISRC1_2                                                     0x4b17
#define mmDIG2_AFMT_ISRC1_2                                                     0x4c17
#define mmDIG3_AFMT_ISRC1_2                                                     0x4d17
#define mmDIG4_AFMT_ISRC1_2                                                     0x4e17
#define mmDIG5_AFMT_ISRC1_2                                                     0x4f17
#define mmDIG6_AFMT_ISRC1_2                                                     0x5417
#define mmDIG7_AFMT_ISRC1_2                                                     0x5617
#define mmDIG8_AFMT_ISRC1_2                                                     0x5717
#define mmAFMT_ISRC1_3                                                          0x4a18
#define mmDIG0_AFMT_ISRC1_3                                                     0x4a18
#define mmDIG1_AFMT_ISRC1_3                                                     0x4b18
#define mmDIG2_AFMT_ISRC1_3                                                     0x4c18
#define mmDIG3_AFMT_ISRC1_3                                                     0x4d18
#define mmDIG4_AFMT_ISRC1_3                                                     0x4e18
#define mmDIG5_AFMT_ISRC1_3                                                     0x4f18
#define mmDIG6_AFMT_ISRC1_3                                                     0x5418
#define mmDIG7_AFMT_ISRC1_3                                                     0x5618
#define mmDIG8_AFMT_ISRC1_3                                                     0x5718
#define mmAFMT_ISRC1_4                                                          0x4a19
#define mmDIG0_AFMT_ISRC1_4                                                     0x4a19
#define mmDIG1_AFMT_ISRC1_4                                                     0x4b19
#define mmDIG2_AFMT_ISRC1_4                                                     0x4c19
#define mmDIG3_AFMT_ISRC1_4                                                     0x4d19
#define mmDIG4_AFMT_ISRC1_4                                                     0x4e19
#define mmDIG5_AFMT_ISRC1_4                                                     0x4f19
#define mmDIG6_AFMT_ISRC1_4                                                     0x5419
#define mmDIG7_AFMT_ISRC1_4                                                     0x5619
#define mmDIG8_AFMT_ISRC1_4                                                     0x5719
#define mmAFMT_ISRC2_0                                                          0x4a1a
#define mmDIG0_AFMT_ISRC2_0                                                     0x4a1a
#define mmDIG1_AFMT_ISRC2_0                                                     0x4b1a
#define mmDIG2_AFMT_ISRC2_0                                                     0x4c1a
#define mmDIG3_AFMT_ISRC2_0                                                     0x4d1a
#define mmDIG4_AFMT_ISRC2_0                                                     0x4e1a
#define mmDIG5_AFMT_ISRC2_0                                                     0x4f1a
#define mmDIG6_AFMT_ISRC2_0                                                     0x541a
#define mmDIG7_AFMT_ISRC2_0                                                     0x561a
#define mmDIG8_AFMT_ISRC2_0                                                     0x571a
#define mmAFMT_ISRC2_1                                                          0x4a1b
#define mmDIG0_AFMT_ISRC2_1                                                     0x4a1b
#define mmDIG1_AFMT_ISRC2_1                                                     0x4b1b
#define mmDIG2_AFMT_ISRC2_1                                                     0x4c1b
#define mmDIG3_AFMT_ISRC2_1                                                     0x4d1b
#define mmDIG4_AFMT_ISRC2_1                                                     0x4e1b
#define mmDIG5_AFMT_ISRC2_1                                                     0x4f1b
#define mmDIG6_AFMT_ISRC2_1                                                     0x541b
#define mmDIG7_AFMT_ISRC2_1                                                     0x561b
#define mmDIG8_AFMT_ISRC2_1                                                     0x571b
#define mmAFMT_ISRC2_2                                                          0x4a1c
#define mmDIG0_AFMT_ISRC2_2                                                     0x4a1c
#define mmDIG1_AFMT_ISRC2_2                                                     0x4b1c
#define mmDIG2_AFMT_ISRC2_2                                                     0x4c1c
#define mmDIG3_AFMT_ISRC2_2                                                     0x4d1c
#define mmDIG4_AFMT_ISRC2_2                                                     0x4e1c
#define mmDIG5_AFMT_ISRC2_2                                                     0x4f1c
#define mmDIG6_AFMT_ISRC2_2                                                     0x541c
#define mmDIG7_AFMT_ISRC2_2                                                     0x561c
#define mmDIG8_AFMT_ISRC2_2                                                     0x571c
#define mmAFMT_ISRC2_3                                                          0x4a1d
#define mmDIG0_AFMT_ISRC2_3                                                     0x4a1d
#define mmDIG1_AFMT_ISRC2_3                                                     0x4b1d
#define mmDIG2_AFMT_ISRC2_3                                                     0x4c1d
#define mmDIG3_AFMT_ISRC2_3                                                     0x4d1d
#define mmDIG4_AFMT_ISRC2_3                                                     0x4e1d
#define mmDIG5_AFMT_ISRC2_3                                                     0x4f1d
#define mmDIG6_AFMT_ISRC2_3                                                     0x541d
#define mmDIG7_AFMT_ISRC2_3                                                     0x561d
#define mmDIG8_AFMT_ISRC2_3                                                     0x571d
#define mmAFMT_AVI_INFO0                                                        0x4a1e
#define mmDIG0_AFMT_AVI_INFO0                                                   0x4a1e
#define mmDIG1_AFMT_AVI_INFO0                                                   0x4b1e
#define mmDIG2_AFMT_AVI_INFO0                                                   0x4c1e
#define mmDIG3_AFMT_AVI_INFO0                                                   0x4d1e
#define mmDIG4_AFMT_AVI_INFO0                                                   0x4e1e
#define mmDIG5_AFMT_AVI_INFO0                                                   0x4f1e
#define mmDIG6_AFMT_AVI_INFO0                                                   0x541e
#define mmDIG7_AFMT_AVI_INFO0                                                   0x561e
#define mmDIG8_AFMT_AVI_INFO0                                                   0x571e
#define mmAFMT_AVI_INFO1                                                        0x4a1f
#define mmDIG0_AFMT_AVI_INFO1                                                   0x4a1f
#define mmDIG1_AFMT_AVI_INFO1                                                   0x4b1f
#define mmDIG2_AFMT_AVI_INFO1                                                   0x4c1f
#define mmDIG3_AFMT_AVI_INFO1                                                   0x4d1f
#define mmDIG4_AFMT_AVI_INFO1                                                   0x4e1f
#define mmDIG5_AFMT_AVI_INFO1                                                   0x4f1f
#define mmDIG6_AFMT_AVI_INFO1                                                   0x541f
#define mmDIG7_AFMT_AVI_INFO1                                                   0x561f
#define mmDIG8_AFMT_AVI_INFO1                                                   0x571f
#define mmAFMT_AVI_INFO2                                                        0x4a20
#define mmDIG0_AFMT_AVI_INFO2                                                   0x4a20
#define mmDIG1_AFMT_AVI_INFO2                                                   0x4b20
#define mmDIG2_AFMT_AVI_INFO2                                                   0x4c20
#define mmDIG3_AFMT_AVI_INFO2                                                   0x4d20
#define mmDIG4_AFMT_AVI_INFO2                                                   0x4e20
#define mmDIG5_AFMT_AVI_INFO2                                                   0x4f20
#define mmDIG6_AFMT_AVI_INFO2                                                   0x5420
#define mmDIG7_AFMT_AVI_INFO2                                                   0x5620
#define mmDIG8_AFMT_AVI_INFO2                                                   0x5720
#define mmAFMT_AVI_INFO3                                                        0x4a21
#define mmDIG0_AFMT_AVI_INFO3                                                   0x4a21
#define mmDIG1_AFMT_AVI_INFO3                                                   0x4b21
#define mmDIG2_AFMT_AVI_INFO3                                                   0x4c21
#define mmDIG3_AFMT_AVI_INFO3                                                   0x4d21
#define mmDIG4_AFMT_AVI_INFO3                                                   0x4e21
#define mmDIG5_AFMT_AVI_INFO3                                                   0x4f21
#define mmDIG6_AFMT_AVI_INFO3                                                   0x5421
#define mmDIG7_AFMT_AVI_INFO3                                                   0x5621
#define mmDIG8_AFMT_AVI_INFO3                                                   0x5721
#define mmAFMT_MPEG_INFO0                                                       0x4a22
#define mmDIG0_AFMT_MPEG_INFO0                                                  0x4a22
#define mmDIG1_AFMT_MPEG_INFO0                                                  0x4b22
#define mmDIG2_AFMT_MPEG_INFO0                                                  0x4c22
#define mmDIG3_AFMT_MPEG_INFO0                                                  0x4d22
#define mmDIG4_AFMT_MPEG_INFO0                                                  0x4e22
#define mmDIG5_AFMT_MPEG_INFO0                                                  0x4f22
#define mmDIG6_AFMT_MPEG_INFO0                                                  0x5422
#define mmDIG7_AFMT_MPEG_INFO0                                                  0x5622
#define mmDIG8_AFMT_MPEG_INFO0                                                  0x5722
#define mmAFMT_MPEG_INFO1                                                       0x4a23
#define mmDIG0_AFMT_MPEG_INFO1                                                  0x4a23
#define mmDIG1_AFMT_MPEG_INFO1                                                  0x4b23
#define mmDIG2_AFMT_MPEG_INFO1                                                  0x4c23
#define mmDIG3_AFMT_MPEG_INFO1                                                  0x4d23
#define mmDIG4_AFMT_MPEG_INFO1                                                  0x4e23
#define mmDIG5_AFMT_MPEG_INFO1                                                  0x4f23
#define mmDIG6_AFMT_MPEG_INFO1                                                  0x5423
#define mmDIG7_AFMT_MPEG_INFO1                                                  0x5623
#define mmDIG8_AFMT_MPEG_INFO1                                                  0x5723
#define mmAFMT_GENERIC_HDR                                                      0x4a24
#define mmDIG0_AFMT_GENERIC_HDR                                                 0x4a24
#define mmDIG1_AFMT_GENERIC_HDR                                                 0x4b24
#define mmDIG2_AFMT_GENERIC_HDR                                                 0x4c24
#define mmDIG3_AFMT_GENERIC_HDR                                                 0x4d24
#define mmDIG4_AFMT_GENERIC_HDR                                                 0x4e24
#define mmDIG5_AFMT_GENERIC_HDR                                                 0x4f24
#define mmDIG6_AFMT_GENERIC_HDR                                                 0x5424
#define mmDIG7_AFMT_GENERIC_HDR                                                 0x5624
#define mmDIG8_AFMT_GENERIC_HDR                                                 0x5724
#define mmAFMT_GENERIC_0                                                        0x4a25
#define mmDIG0_AFMT_GENERIC_0                                                   0x4a25
#define mmDIG1_AFMT_GENERIC_0                                                   0x4b25
#define mmDIG2_AFMT_GENERIC_0                                                   0x4c25
#define mmDIG3_AFMT_GENERIC_0                                                   0x4d25
#define mmDIG4_AFMT_GENERIC_0                                                   0x4e25
#define mmDIG5_AFMT_GENERIC_0                                                   0x4f25
#define mmDIG6_AFMT_GENERIC_0                                                   0x5425
#define mmDIG7_AFMT_GENERIC_0                                                   0x5625
#define mmDIG8_AFMT_GENERIC_0                                                   0x5725
#define mmAFMT_GENERIC_1                                                        0x4a26
#define mmDIG0_AFMT_GENERIC_1                                                   0x4a26
#define mmDIG1_AFMT_GENERIC_1                                                   0x4b26
#define mmDIG2_AFMT_GENERIC_1                                                   0x4c26
#define mmDIG3_AFMT_GENERIC_1                                                   0x4d26
#define mmDIG4_AFMT_GENERIC_1                                                   0x4e26
#define mmDIG5_AFMT_GENERIC_1                                                   0x4f26
#define mmDIG6_AFMT_GENERIC_1                                                   0x5426
#define mmDIG7_AFMT_GENERIC_1                                                   0x5626
#define mmDIG8_AFMT_GENERIC_1                                                   0x5726
#define mmAFMT_GENERIC_2                                                        0x4a27
#define mmDIG0_AFMT_GENERIC_2                                                   0x4a27
#define mmDIG1_AFMT_GENERIC_2                                                   0x4b27
#define mmDIG2_AFMT_GENERIC_2                                                   0x4c27
#define mmDIG3_AFMT_GENERIC_2                                                   0x4d27
#define mmDIG4_AFMT_GENERIC_2                                                   0x4e27
#define mmDIG5_AFMT_GENERIC_2                                                   0x4f27
#define mmDIG6_AFMT_GENERIC_2                                                   0x5427
#define mmDIG7_AFMT_GENERIC_2                                                   0x5627
#define mmDIG8_AFMT_GENERIC_2                                                   0x5727
#define mmAFMT_GENERIC_3                                                        0x4a28
#define mmDIG0_AFMT_GENERIC_3                                                   0x4a28
#define mmDIG1_AFMT_GENERIC_3                                                   0x4b28
#define mmDIG2_AFMT_GENERIC_3                                                   0x4c28
#define mmDIG3_AFMT_GENERIC_3                                                   0x4d28
#define mmDIG4_AFMT_GENERIC_3                                                   0x4e28
#define mmDIG5_AFMT_GENERIC_3                                                   0x4f28
#define mmDIG6_AFMT_GENERIC_3                                                   0x5428
#define mmDIG7_AFMT_GENERIC_3                                                   0x5628
#define mmDIG8_AFMT_GENERIC_3                                                   0x5728
#define mmAFMT_GENERIC_4                                                        0x4a29
#define mmDIG0_AFMT_GENERIC_4                                                   0x4a29
#define mmDIG1_AFMT_GENERIC_4                                                   0x4b29
#define mmDIG2_AFMT_GENERIC_4                                                   0x4c29
#define mmDIG3_AFMT_GENERIC_4                                                   0x4d29
#define mmDIG4_AFMT_GENERIC_4                                                   0x4e29
#define mmDIG5_AFMT_GENERIC_4                                                   0x4f29
#define mmDIG6_AFMT_GENERIC_4                                                   0x5429
#define mmDIG7_AFMT_GENERIC_4                                                   0x5629
#define mmDIG8_AFMT_GENERIC_4                                                   0x5729
#define mmAFMT_GENERIC_5                                                        0x4a2a
#define mmDIG0_AFMT_GENERIC_5                                                   0x4a2a
#define mmDIG1_AFMT_GENERIC_5                                                   0x4b2a
#define mmDIG2_AFMT_GENERIC_5                                                   0x4c2a
#define mmDIG3_AFMT_GENERIC_5                                                   0x4d2a
#define mmDIG4_AFMT_GENERIC_5                                                   0x4e2a
#define mmDIG5_AFMT_GENERIC_5                                                   0x4f2a
#define mmDIG6_AFMT_GENERIC_5                                                   0x542a
#define mmDIG7_AFMT_GENERIC_5                                                   0x562a
#define mmDIG8_AFMT_GENERIC_5                                                   0x572a
#define mmAFMT_GENERIC_6                                                        0x4a2b
#define mmDIG0_AFMT_GENERIC_6                                                   0x4a2b
#define mmDIG1_AFMT_GENERIC_6                                                   0x4b2b
#define mmDIG2_AFMT_GENERIC_6                                                   0x4c2b
#define mmDIG3_AFMT_GENERIC_6                                                   0x4d2b
#define mmDIG4_AFMT_GENERIC_6                                                   0x4e2b
#define mmDIG5_AFMT_GENERIC_6                                                   0x4f2b
#define mmDIG6_AFMT_GENERIC_6                                                   0x542b
#define mmDIG7_AFMT_GENERIC_6                                                   0x562b
#define mmDIG8_AFMT_GENERIC_6                                                   0x572b
#define mmAFMT_GENERIC_7                                                        0x4a2c
#define mmDIG0_AFMT_GENERIC_7                                                   0x4a2c
#define mmDIG1_AFMT_GENERIC_7                                                   0x4b2c
#define mmDIG2_AFMT_GENERIC_7                                                   0x4c2c
#define mmDIG3_AFMT_GENERIC_7                                                   0x4d2c
#define mmDIG4_AFMT_GENERIC_7                                                   0x4e2c
#define mmDIG5_AFMT_GENERIC_7                                                   0x4f2c
#define mmDIG6_AFMT_GENERIC_7                                                   0x542c
#define mmDIG7_AFMT_GENERIC_7                                                   0x562c
#define mmDIG8_AFMT_GENERIC_7                                                   0x572c
#define mmHDMI_GENERIC_PACKET_CONTROL1                                          0x4a2d
#define mmDIG0_HDMI_GENERIC_PACKET_CONTROL1                                     0x4a2d
#define mmDIG1_HDMI_GENERIC_PACKET_CONTROL1                                     0x4b2d
#define mmDIG2_HDMI_GENERIC_PACKET_CONTROL1          