OFT_REGISTERS_TABLE_20                                               0x3f8e8
#define ixSOFT_REGISTERS_TABLE_21                                               0x3f8ec
#define ixSOFT_REGISTERS_TABLE_22                                               0x3f8f0
#define ixSOFT_REGISTERS_TABLE_23                                               0x3f8f4
#define ixSOFT_REGISTERS_TABLE_24                                               0x3f8f8
#define ixSOFT_REGISTERS_TABLE_25                                               0x3f8fc
#define ixSOFT_REGISTERS_TABLE_26                                               0x3f900
#define ixSOFT_REGISTERS_TABLE_27                                               0x3f904
#define ixSOFT_REGISTERS_TABLE_28                                               0x3f888
#define ixSOFT_REGISTERS_TABLE_29                                               0x3f90c
#define ixSOFT_REGISTERS_TABLE_30                                               0x3f910
#define ixPM_FUSES_1                                                            0x3f914
#define ixPM_FUSES_2                                                            0x3f918
#define ixPM_FUSES_3                                                            0x3f91c
#define ixPM_FUSES_4                                                            0x3f920
#define ixPM_FUSES_5                                                            0x3f924
#define ixPM_FUSES_6                                                            0x3f928
#define ixPM_FUSES_7                                                            0x3f92c
#define ixPM_FUSES_8                                                            0x3f930
#define ixPM_FUSES_9                                                            0x3f934
#define ixPM_FUSES_10                                                           0x3f938
#define ixPM_FUSES_11                                                           0x3f93c
#define ixPM_FUSES_12                                                           0x3f940
#define ixPM_FUSES_13                                                           0x3f944
#define ixPM_FUSES_14                                                           0x3f948
#define ixPM_FUSES_15                                                           0x3f94c
#define ixSMU_PM_STATUS_0                                                       0x3fe00
#define ixSMU_PM_STATUS_1                                                       0x3fe04
#define ixSMU_PM_STATUS_2                                                       0x3fe08
#define ixSMU_PM_STATUS_3                                                       0x3fe0c
#define ixSMU_PM_STATUS_4                                                       0x3fe10
#define ixSMU_PM_STATUS_5                                                       0x3fe14
#define ixSMU_PM_STATUS_6                                                       0x3fe18
#define ixSMU_PM_STATUS_7                                                       0x3fe1c
#define ixSMU_PM_STATUS_8                                                       0x3fe20
#define ixSMU_PM_STATUS_9                                                       0x3fe24
#define ixSMU_PM_STATUS_10                                                      0x3fe28
#define ixSMU_PM_STATUS_11                                                      0x3fe2c
#define ixSMU_PM_STATUS_12                                                      0x3fe30
#define ixSMU_PM_STATUS_13                                                      0x3fe34
#define ixSMU_PM_STATUS_14                                                      0x3fe38
#define ixSMU_PM_STATUS_15                                                      0x3fe3c
#define ixSMU_PM_STATUS_16                                                      0x3fe40
#define ixSMU_PM_STATUS_17                                                      0x3fe44
#define ixSMU_PM_STATUS_18                                                      0x3fe48
#define ixSMU_PM_STATUS_19                                                      0x3fe4c
#define ixSMU_PM_STATUS_20                                                      0x3fe50
#define ixSMU_PM_STATUS_21                                                      0x3fe54
#define ixSMU_PM_STATUS_22                                                      0x3fe58
#define ixSMU_PM_STATUS_23                                                      0x3fe5c
#define ixSMU_PM_STATUS_24                                                      0x3fe60
#define ixSMU_PM_STATUS_25                                                      0x3fe64
#define ixSMU_PM_STATUS_26                                                      0x3fe68
#define ixSMU_PM_STATUS_27                                                      0x3fe6c
#define ixSMU_PM_STATUS_28                                                      0x3fe70
#define ixSMU_PM_STATUS_29                                                      0x3fe74
#define ixSMU_PM_STATUS_30                                                      0x3fe78
#define ixSMU_PM_STATUS_31                                                      0x3fe7c
#define ixSMU_PM_STATUS_32                                                      0x3fe80
#define ixSMU_PM_STATUS_33                                                      0x3fe84
#define ixSMU_PM_STATUS_34                                                      0x3fe88
#define ixSMU_PM_STATUS_35                                                      0x3fe8c
#define ixSMU_PM_STATUS_36                                                      0x3fe90
#define ixSMU_PM_STATUS_37                                                      0x3fe94
#define ixSMU_PM_STATUS_38                                                      0x3fe98
#define ixSMU_PM_STATUS_39                                                      0x3fe9c
#define ixSMU_PM_STATUS_40                                                      0x3fea0
#define ixSMU_PM_STATUS_41                                                      0x3fea4
#define ixSMU_PM_STATUS_42                                                      0x3fea8
#define ixSMU_PM_STATUS_43                                                      0x3feac
#define ixSMU_PM_STATUS_44                                                      0x3feb0
#define ixSMU_PM_STATUS_45                                                      0x3feb4
#define ixSMU_PM_STATUS_46                                                      0x3feb8
#define ixSMU_PM_STATUS_47                                                      0x3febc
#define ixSMU_PM_STATUS_48                                                      0x3fec0
#define ixSMU_PM_STATUS_49                                                      0x3fec4
#define ixSMU_PM_STATUS_50                                                      0x3fec8
#define ixSMU_PM_STATUS_51                                                      0x3fecc
#define ixSMU_PM_STATUS_52                                                      0x3fed0
#define ixSMU_PM_STATUS_53                                                      0x3fed4
#define ixSMU_PM_STATUS_54                                                      0x3fed8
#define ixSMU_PM_STATUS_55                                                      0x3fedc
#define ixSMU_PM_STATUS_56                                                      0x3fee0
#define ixSMU_PM_STATUS_57                                                      0x3fee4
#define ixSMU_PM_STATUS_58                                                      0x3fee8
#define ixSMU_PM_STATUS_59                                                      0x3feec
#define ixSMU_PM_STATUS_60                                                      0x3fef0
#define ixSMU_PM_STATUS_61                                                      0x3fef4
#define ixSMU_PM_STATUS_62                                                      0x3fef8
#define ixSMU_PM_STATUS_63                                                      0x3fefc
#define ixSMU_PM_STATUS_64                                                      0x3ff00
#define ixSMU_PM_STATUS_65                                                      0x3ff04
#define ixSMU_PM_STATUS_66                                                      0x3ff08
#define ixSMU_PM_STATUS_67                                                      0x3ff0c
#define ixSMU_PM_STATUS_68                                                      0x3ff10
#define ixSMU_PM_STATUS_69                                                      0x3ff14
#define ixSMU_PM_STATUS_70                                                      0x3ff18
#define ixSMU_PM_STATUS_71                                                      0x3ff1c
#define ixSMU_PM_STATUS_72                                                      0x3ff20
#define ixSMU_PM_STATUS_73                                                      0x3ff24
#define ixSMU_PM_STATUS_74                                                      0x3ff28
#define ixSMU_PM_STATUS_75                                                      0x3ff2c
#define ixSMU_PM_STATUS_76                                                      0x3ff30
#define ixSMU_PM_STATUS_77                                                      0x3ff34
#define ixSMU_PM_STATUS_78                                                      0x3ff38
#define ixSMU_PM_STATUS_79                                                      0x3ff3c
#define ixSMU_PM_STATUS_80                                                      0x3ff40
#define ixSMU_PM_STATUS_81                                                      0x3ff44
#define ixSMU_PM_STATUS_82                                                      0x3ff48
#define ixSMU_PM_STATUS_83                                                      0x3ff4c
#define ixSMU_PM_STATUS_84                                                      0x3ff50
#define ixSMU_PM_STATUS_85                                                      0x3ff54
#define ixSMU_PM_STATUS_86                                                      0x3ff58
#define ixSMU_PM_STATUS_87                                                      0x3ff5c
#define ixSMU_PM_STATUS_88                                                      0x3ff60
#define ixSMU_PM_STATUS_89                                                      0x3ff64
#define ixSMU_PM_STATUS_90                                                      0x3ff68
#define ixSMU_PM_STATUS_91                                                      0x3ff6c
#define ixSMU_PM_STATUS_92                                                      0x3ff70
#define ixSMU_PM_STATUS_93                                                      0x3ff74
#define ixSMU_PM_STATUS_94                                                      0x3ff78
#define ixSMU_PM_STATUS_95                                                      0x3ff7c
#define ixSMU_PM_STATUS_96                                                      0x3ff80
#define ixSMU_PM_STATUS_97                                                      0x3ff84
#define ixSMU_PM_STATUS_98                                                      0x3ff88
#define ixSMU_PM_STATUS_99                                                      0x3ff8c
#define ixSMU_PM_STATUS_100                                                     0x3ff90
#define ixSMU_PM_STATUS_101                                                     0x3ff94
#define ixSMU_PM_STATUS_102                                                     0x3ff98
#define ixSMU_PM_STATUS_103                                                     0x3ff9c
#define ixSMU_PM_STATUS_104                                                     0x3ffa0
#define ixSMU_PM_STATUS_105                                                     0x3ffa4
#define ixSMU_PM_STATUS_106                                                     0x3ffa8
#define ixSMU_PM_STATUS_107                                                     0x3ffac
#define ixSMU_PM_STATUS_108                                                     0x3ffb0
#define ixSMU_PM_STATUS_109                                                     0x3ffb4
#define ixSMU_PM_STATUS_110                                                     0x3ffb8
#define ixSMU_PM_STATUS_111                                                     0x3ffbc
#define ixSMU_PM_STATUS_112                                                     0x3ffc0
#define ixSMU_PM_STATUS_113                                                     0x3ffc4
#define ixSMU_PM_STATUS_114                                                     0x3ffc8
#define ixSMU_PM_STATUS_115                                                     0x3ffcc
#define ixSMU_PM_STATUS_116                                                     0x3ffd0
#define ixSMU_PM_STATUS_117                                                     0x3ffd4
#define ixSMU_PM_STATUS_118                                                     0x3ffd8
#define ixSMU_PM_STATUS_119                                                     0x3ffdc
#define ixSMU_PM_STATUS_120                                                     0x3ffe0
#define ixSMU_PM_STATUS_121                                                     0x3ffe4
#define ixSMU_PM_STATUS_122                                                     0x3ffe8
#define ixSMU_PM_STATUS_123                                                     0x3ffec
#define ixSMU_PM_STATUS_124                                                     0x3fff0
#define ixSMU_PM_STATUS_125                                                     0x3fff4
#define ixSMU_PM_STATUS_126                                                     0x3fff8
#define ixSMU_PM_STATUS_127                                                     0x3fffc
#define ixCG_THERMAL_INT_ENA                                                    0xc2100024
#define ixCG_THERMAL_INT_CTRL                                                   0xc2100028
#define ixCG_THERMAL_INT_STATUS                                                 0xc210002c
#define ixCG_THERMAL_CTRL                                                       0xc0300004
#define ixCG_THERMAL_STATUS                                                     0xc0300008
#define ixCG_THERMAL_INT                                                        0xc030000c
#define ixCG_MULT_THERMAL_CTRL                                                  0xc0300010
#define ixCG_MULT_THERMAL_STATUS                                                0xc0300014
#define ixTHM_TMON2_CTRL                                                        0xc0300034
#define ixTHM_TMON2_CTRL2                                                       0xc0300038
#define ixTHM_TMON2_CSR_WR                                                      0xc0300054
#define ixTHM_TMON2_CSR_RD                                                      0xc0300058
#define ixCG_FDO_CTRL0                                                          0xc0300064
#define ixCG_FDO_CTRL1                                                          0xc0300068
#define ixCG_FDO_CTRL2                                                          0xc030006c
#define ixCG_TACH_CTRL                                                          0xc0300070
#define ixCG_TACH_STATUS                                                        0xc0300074
#define ixCC_THM_STRAPS0                                                        0xc0300080
#define ixTHM_TMON0_RDIL0_DATA                                                  0xc0300100
#define ixTHM_TMON0_RDIL1_DATA                                                  0xc0300104
#define ixTHM_TMON0_RDIL2_DATA                                                  0xc0300108
#define ixTHM_TMON0_RDIL3_DATA                                                  0xc030010c
#define ixTHM_TMON0_RDIL4_DATA                                                  0xc0300110
#define ixTHM_TMON0_RDIL5_DATA                                                  0xc0300114
#define ixTHM_TMON0_RDIL6_DATA                                                  0xc0300118
#define ixTHM_TMON0_RDIL7_DATA                                                  0xc030011c
#define ixTHM_TMON0_RDIL8_DATA                                                  0xc0300120
#define ixTHM_TMON0_RDIL9_DATA                                                  0xc0300124
#define ixTHM_TMON0_RDIL10_DATA                                                 0xc0300128
#define ixTHM_TMON0_RDIL11_DATA                                                 0xc030012c
#define ixTHM_TMON0_RDIL12_DATA                                                 0xc0300130
#define ixTHM_TMON0_RDIL13_DATA                                                 0xc0300134
#define ixTHM_TMON0_RDIL14_DATA                                                 0xc0300138
#define ixTHM_TMON0_RDIL15_DATA                                                 0xc030013c
#define ixTHM_TMON0_RDIR0_DATA                                                  0xc0300140
#define ixTHM_TMON0_RDIR1_DATA                                                  0xc0300144
#define ixTHM_TMON0_RDIR2_DATA                                                  0xc0300148
#define ixTHM_TMON0_RDIR3_DATA                                                  0xc030014c
#define ixTHM_TMON0_RDIR4_DATA                                                  0xc0300150
#define ixTHM_TMON0_RDIR5_DATA                                                  0xc0300154
#define ixTHM_TMON0_RDIR6_DATA                                                  0xc0300158
#define ixTHM_TMON0_RDIR7_DATA                                                  0xc030015c
#define ixTHM_TMON0_RDIR8_DATA                                                  0xc0300160
#define ixTHM_TMON0_RDIR9_DATA                                                  0xc0300164
#define ixTHM_TMON0_RDIR10_DATA                                                 0xc0300168
#define ixTHM_TMON0_RDIR11_DATA                                                 0xc030016c
#define ixTHM_TMON0_RDIR12_DATA                                                 0xc0300170
#define ixTHM_TMON0_RDIR13_DATA                                                 0xc0300174
#define ixTHM_TMON0_RDIR14_DATA                                                 0xc0300178
#define ixTHM_TMON0_RDIR15_DATA                                                 0xc030017c
#define ixTHM_TMON1_RDIL0_DATA                                                  0xc0300180
#define ixTHM_TMON1_RDIL1_DATA                                                  0xc0300184
#define ixTHM_TMON1_RDIL2_DATA                                                  0xc0300188
#define ixTHM_TMON1_RDIL3_DATA                                                  0xc030018c
#define ixTHM_TMON1_RDIL4_DATA                                                  0xc0300190
#define ixTHM_TMON1_RDIL5_DATA                                                  0xc0300194
#define ixTHM_TMON1_RDIL6_DATA                                                  0xc0300198
#define ixTHM_TMON1_RDIL7_DATA                                                  0xc030019c
#define ixTHM_TMON1_RDIL8_DATA                                                  0xc03001a0
#define ixTHM_TMON1_RDIL9_DATA                                                  0xc03001a4
#define ixTHM_TMON1_RDIL10_DATA                                                 0xc03001a8
#define ixTHM_TMON1_RDIL11_DATA                                                 0xc03001ac
#define ixTHM_TMON1_RDIL12_DATA                                                 0xc03001b0
#define ixTHM_TMON1_RDIL13_DATA                                                 0xc03001b4
#define ixTHM_TMON1_RDIL14_DATA                                                 0xc03001b8
#define ixTHM_TMON1_RDIL15_DATA                                                 0xc03001bc
#define ixTHM_TMON1_RDIR0_DATA                                                  0xc03001c0
#define ixTHM_TMON1_RDIR1_DATA                                                  0xc03001c4
#define ixTHM_TMON1_RDIR2_DATA                                                  0xc03001c8
#define ixTHM_TMON1_RDIR3_DATA                                                  0xc03001cc
#define ixTHM_TMON1_RDIR4_DATA                                                  0xc03001d0
#define ixTHM_TMON1_RDIR5_DATA                                                  0xc03001d4
#define ixTHM_TMON1_RDIR6_DATA                                                  0xc03001d8
#define ixTHM_TMON1_RDIR7_DATA                                                  0xc03001dc
#define ixTHM_TMON1_RDIR8_DATA                                                  0xc03001e0
#define ixTHM_TMON1_RDIR9_DATA                                                  0xc03001e4
#define ixTHM_TMON1_RDIR10_DATA                                                 0xc03001e8
#define ixTHM_TMON1_RDIR11_DATA                                                 0xc03001ec
#define ixTHM_TMON1_RDIR12_DATA                                                 0xc03001f0
#define ixTHM_TMON1_RDIR13_DATA                                                 0xc03001f4
#define ixTHM_TMON1_RDIR14_DATA                                                 0xc03001f8
#define ixTHM_TMON1_RDIR15_DATA                                                 0xc03001fc
#define ixTHM_TMON2_RDIL0_DATA                                                  0xc0300200
#define ixTHM_TMON2_RDIL1_DATA                                                  0xc0300204
#define ixTHM_TMON2_RDIL2_DATA                                                  0xc0300208
#define ixTHM_TMON2_RDIL3_DATA                                                  0xc030020c
#define ixTHM_TMON2_RDIL4_DATA                                                  0xc0300210
#define ixTHM_TMON2_RDIL5_DATA                                                  0xc0300214
#define ixTHM_TMON2_RDIL6_DATA                                                  0xc0300218
#define ixTHM_TMON2_RDIL7_DATA                                                  0xc030021c
#define ixTHM_TMON2_RDIL8_DATA                                                  0xc0300220
#define ixTHM_TMON2_RDIL9_DATA                                                  0xc0300224
#define ixTHM_TMON2_RDIL10_DATA                                                 0xc0300228
#define ixTHM_TMON2_RDIL11_DATA                                                 0xc030022c
#define ixTHM_TMON2_RDIL12_DATA                                                 0xc0300230
#define ixTHM_TMON2_RDIL13_DATA                                                 0xc0300234
#define ixTHM_TMON2_RDIL14_DATA                                                 0xc0300238
#define ixTHM_TMON2_RDIL15_DATA                                                 0xc030023c
#define ixTHM_TMON2_RDIR0_DATA                                                  0xc0300240
#define ixTHM_TMON2_RDIR1_DATA                                                  0xc0300244
#define ixTHM_TMON2_RDIR2_DATA                                                  0xc0300248
#define ixTHM_TMON2_RDIR3_DATA                                                  0xc030024c
#define ixTHM_TMON2_RDIR4_DATA                                                  0xc0300250
#define ixTHM_TMON2_RDIR5_DATA                                                  0xc0300254
#define ixTHM_TMON2_RDIR6_DATA                                                  0xc0300258
#define ixTHM_TMON2_RDIR7_DATA                                                  0xc030025c
#define ixTHM_TMON2_RDIR8_DATA                                                  0xc0300260
#define ixTHM_TMON2_RDIR9_DATA                                                  0xc0300264
#define ixTHM_TMON2_RDIR10_DATA                                                 0xc0300268
#define ixTHM_TMON2_RDIR11_DATA                                                 0xc030026c
#define ixTHM_TMON2_RDIR12_DATA                                                 0xc0300270
#define ixTHM_TMON2_RDIR13_DATA                                                 0xc0300274
#define ixTHM_TMON2_RDIR14_DATA                                                 0xc0300278
#define ixTHM_TMON2_RDIR15_DATA                                                 0xc030027c
#define ixTHM_TMON0_INT_DATA                                                    0xc0300300
#define ixTHM_TMON1_INT_DATA                                                    0xc0300304
#define ixTHM_TMON2_INT_DATA                                                    0xc0300308
#define ixTHM_TMON0_DEBUG                                                       0xc0300310
#define ixTHM_TMON1_DEBUG                                                       0xc0300314
#define ixTHM_TMON2_DEBUG                                                       0xc0300318
#define ixTHM_TMON0_STATUS                                                      0xc0300320
#define ixTHM_TMON1_STATUS                                                      0xc0300324
#define ixTHM_TMON2_STATUS                                                      0xc0300328
#define ixGENERAL_PWRMGT                                                        0xc0200000
#define ixCNB_PWRMGT_CNTL                                                       0xc0200004
#define ixSCLK_PWRMGT_CNTL                                                      0xc0200008
#define ixTARGET_AND_CURRENT_PROFILE_INDEX                                      0xc0200014
#define ixPWR_PCC_CONTROL                                                       0xc0200018
#define ixPWR_PCC_GPIO_SELECT                                                   0xc020001c
#define ixCG_FREQ_TRAN_VOTING_0                                                 0xc02001a8
#define ixCG_FREQ_TRAN_VOTING_1                                                 0xc02001ac
#define ixCG_FREQ_TRAN_VOTING_2                                                 0xc02001b0
#define ixCG_FREQ_TRAN_VOTING_3                                                 0xc02001b4
#define ixCG_FREQ_TRAN_VOTING_4                                                 0xc02001b8
#define ixCG_FREQ_TRAN_VOTING_5                                                 0xc02001bc
#define ixCG_FREQ_TRAN_VOTING_6                                                 0xc02001c0
#define ixCG_FREQ_TRAN_VOTING_7                                                 0xc02001c4
#define ixPLL_TEST_CNTL                                                         0xc020003c
#define ixCG_STATIC_SCREEN_PARAMETER                                            0xc0200044
#define ixCG_DISPLAY_GAP_CNTL                                                   0xc0200060
#define ixCG_DISPLAY_GAP_CNTL2                                                  0xc0200230
#define ixCG_ACPI_CNTL                                                          0xc0200064
#define ixSCLK_DEEP_SLEEP_CNTL                                                  0xc0200080
#define ixSCLK_DEEP_SLEEP_CNTL2                                                 0xc0200084
#define ixSCLK_DEEP_SLEEP_CNTL3                                                 0xc020009c
#define ixSCLK_DEEP_SLEEP_MISC_CNTL                                             0xc0200088
#define ixLCLK_DEEP_SLEEP_CNTL                                                  0xc020008c
#define ixLCLK_DEEP_SLEEP_CNTL2                                                 0xc0200310
#define ixTARGET_AND_CURRENT_PROFILE_INDEX_1                                    0xc02000f0
#define ixCG_ULV_PARAMETER                                                      0xc020015c
#define ixSCLK_MIN_DIV                                                          0xc02003ac
#define ixPWR_AVFS_SEL                                                          0xc0200384
#define ixPWR_AVFS_CNTL                                                         0xc0200388
#define ixPWR_AVFS0_CNTL_STATUS                                                 0xc0200400
#define ixPWR_AVFS1_CNTL_STATUS                                                 0xc0200404
#define ixPWR_AVFS2_CNTL_STATUS                                                 0xc0200408
#define ixPWR_AVFS3_CNTL_STATUS                                                 0xc020040c
#define ixPWR_AVFS4_CNTL_STATUS                                                 0xc0200410
#define ixPWR_AVFS5_CNTL_STATUS                                                 0xc0200414
#define ixPWR_AVFS6_CNTL_STATUS                                                 0xc0200418
#define ixPWR_AVFS7_CNTL_STATUS                                                 0xc020041c
#define ixPWR_AVFS8_CNTL_STATUS                                                 0xc0200420
#define ixPWR_AVFS9_CNTL_STATUS                                                 0xc0200424
#define ixPWR_AVFS10_CNTL_STATUS                                                0xc0200428
#define ixPWR_AVFS11_CNTL_STATUS                                                0xc020042c
#define ixPWR_AVFS12_CNTL_STATUS                                                0xc0200430
#define ixPWR_AVFS13_CNTL_STATUS                                                0xc0200434
#define ixPWR_AVFS14_CNTL_STATUS                                                0xc0200438
#define ixPWR_AVFS15_CNTL_STATUS                                                0xc020043c
#define ixPWR_AVFS16_CNTL_STATUS                                                0xc0200440
#define ixPWR_AVFS17_CNTL_STATUS                                                0xc0200444
#define ixPWR_AVFS18_CNTL_STATUS                                                0xc0200448
#define ixPWR_AVFS19_CNTL_STATUS                                                0xc020044c
#define ixPWR_AVFS20_CNTL_STATUS                                                0xc0200450
#define ixPWR_AVFS21_CNTL_STATUS                                                0xc0200454
#define ixPWR_AVFS22_CNTL_STATUS                                                0xc0200458
#define ixPWR_AVFS23_CNTL_STATUS                                                0xc020045c
#define ixPWR_AVFS24_CNTL_STATUS                                                0xc0200460
#define ixPWR_AVFS25_CNTL_STATUS                                                0xc0200464
#define ixPWR_AVFS26_CNTL_STATUS                                                0xc0200468
#define ixPWR_AVFS27_CNTL_STATUS                                                0xc020046c
#define ixPWR_CKS_ENABLE                                                        0xc020034c
#define ixPWR_CKS_CNTL                                                          0xc0200350
#define ixPWR_DISP_TIMER_CONTROL                                                0xc02003c0
#define ixPWR_DISP_TIMER_DEBUG                                                  0xc02003c4
#define ixPWR_DISP_TIMER2_CONTROL                                               0xc02003c8
#define ixPWR_DISP_TIMER2_DEBUG                                                 0xc02003cc
#define ixPWR_DISP_TIMER_CONTROL2                                               0xc0200378
#define ixVDDGFX_IDLE_PARAMETER                                                 0xc020036c
#define ixVDDGFX_IDLE_CONTROL                                                   0xc0200370
#define ixVDDGFX_IDLE_EXIT                                                      0xc0200374
#define ixLCAC_MC0_CNTL                                                         0xc0400130
#define ixLCAC_MC0_OVR_SEL                                                      0xc0400134
#define ixLCAC_MC0_OVR_VAL                                                      0xc0400138
#define ixLCAC_MC1_CNTL                                                         0xc040013c
#define ixLCAC_MC1_OVR_SEL                                                      0xc0400140
#define ixLCAC_MC1_OVR_VAL                                                      0xc0400144
#define ixLCAC_MC2_CNTL                                                         0xc0400148
#define ixLCAC_MC2_OVR_SEL                                                      0xc040014c
#define ixLCAC_MC2_OVR_VAL                                                      0xc0400150
#define ixLCAC_MC3_CNTL                                                         0xc0400154
#define ixLCAC_MC3_OVR_SEL                                                      0xc0400158
#define ixLCAC_MC3_OVR_VAL                                                      0xc040015c
#define ixLCAC_MC4_CNTL                                                         0xc0400d60
#define ixLCAC_MC4_OVR_SEL                                                      0xc0400d64
#define ixLCAC_MC4_OVR_VAL                                                      0xc0400d68
#define ixLCAC_MC5_CNTL                                                         0xc0400d6c
#define ixLCAC_MC5_OVR_SEL                                                      0xc0400d70
#define ixLCAC_MC5_OVR_VAL                                                      0xc0400d74
#define ixLCAC_MC6_CNTL                                                         0xc0400d78
#define ixLCAC_MC6_OVR_SEL                                                      0xc0400d7c
#define ixLCAC_MC6_OVR_VAL                                                      0xc0400d80
#define ixLCAC_MC7_CNTL                                                         0xc0400d84
#define ixLCAC_MC7_OVR_SEL                                                      0xc0400d88
#define ixLCAC_MC7_OVR_VAL                                                      0xc0400d8c
#define ixLCAC_CPL_CNTL                                                         0xc0400160
#define ixLCAC_CPL_OVR_SEL                                                      0xc0400164
#define ixLCAC_CPL_OVR_VAL                                                      0xc0400168
#define mmROM_SMC_IND_INDEX                                                     0x80
#define mmROM0_ROM_SMC_IND_INDEX                                                0x80
#define mmROM1_ROM_SMC_IND_INDEX                                                0x82
#define mmROM2_ROM_SMC_IND_INDEX                                                0x84
#define mmROM3_ROM_SMC_IND_INDEX                                                0x86
#define mmROM_SMC_IND_DATA                                                      0x81
#define mmROM0_ROM_SMC_IND_DATA                                                 0x81
#define mmROM1_ROM_SMC_IND_DATA                                                 0x83
#define mmROM2_ROM_SMC_IND_DATA                                                 0x85
#define mmROM3_ROM_SMC_IND_DATA                                                 0x87
#define ixROM_CNTL                                                              0xc0600000
#define ixPAGE_MIRROR_CNTL                                                      0xc0600004
#define ixROM_STATUS                                                            0xc0600008
#define ixCGTT_ROM_CLK_CTRL0                                                    0xc060000c
#define ixROM_INDEX                                                             0xc0600010
#define ixROM_DATA                                                              0xc0600014
#define ixROM_START                                                             0xc0600018
#define ixROM_SW_CNTL                                                           0xc060001c
#define ixROM_SW_STATUS                                                         0xc0600020
#define ixROM_SW_COMMAND                                                        0xc0600024
#define ixROM_SW_DATA_1                                                         0xc0600028
#define ixROM_SW_DATA_2                                                         0xc060002c
#define ixROM_SW_DATA_3                                                         0xc0600030
#define ixROM_SW_DATA_4                                                         0xc0600034
#define ixROM_SW_DATA_5                                                         0xc0600038
#define ixROM_SW_DATA_6                                                         0xc060003c
#define ixROM_SW_DATA_7                                                         0xc0600040
#define ixROM_SW_DATA_8                                                         0xc0600044
#define ixROM_SW_DATA_9                                                         0xc0600048
#define ixROM_SW_DATA_10                                                        0xc060004c
#define ixROM_SW_DATA_11                                                        0xc0600050
#define ixROM_SW_DATA_12                                                        0xc0600054
#define ixROM_SW_DATA_13                                                        0xc0600058
#define ixROM_SW_DATA_14                                                        0xc060005c
#define ixROM_SW_DATA_15                                                        0xc0600060
#define ixROM_SW_DATA_16                                                        0xc0600064
#define ixROM_SW_DATA_17                                                        0xc0600068
#define ixROM_SW_DATA_18                                                        0xc060006c
#define ixROM_SW_DATA_19                                                        0xc0600070
#define ixROM_SW_DATA_20                                                        0xc0600074
#define ixROM_SW_DATA_21                                                        0xc0600078
#define ixROM_SW_DATA_22                                                        0xc060007c
#define ixROM_SW_DATA_23                                                        0xc0600080
#define ixROM_SW_DATA_24                                                        0xc0600084
#define ixROM_SW_DATA_25                                                        0xc0600088
#define ixROM_SW_DATA_26                                                        0xc060008c
#define ixROM_SW_DATA_27                                                        0xc0600090
#define ixROM_SW_DATA_28                                                        0xc0600094
#define ixROM_SW_DATA_29                                                        0xc0600098
#define ixROM_SW_DATA_30                                                        0xc060009c
#define ixROM_SW_DATA_31                                                        0xc06000a0
#define ixROM_SW_DATA_32                                                        0xc06000a4
#define ixROM_SW_DATA_33                                                        0xc06000a8
#define ixROM_SW_DATA_34                                                        0xc06000ac
#define ixROM_SW_DATA_35                                                        0xc06000b0
#define ixROM_SW_DATA_36                                                        0xc06000b4
#define ixROM_SW_DATA_37                                                        0xc06000b8
#define ixROM_SW_DATA_38                                                        0xc06000bc
#define ixROM_SW_DATA_39                                                        0xc06000c0
#define ixROM_SW_DATA_40                                                        0xc06000c4
#define ixROM_SW_DATA_41                                                        0xc06000c8
#define ixROM_SW_DATA_42                                                        0xc06000cc
#define ixROM_SW_DATA_43                                                        0xc06000d0
#define ixROM_SW_DATA_44                                                        0xc06000d4
#define ixROM_SW_DATA_45                                                        0xc06000d8
#define ixROM_SW_DATA_46                                                        0xc06000dc
#define ixROM_SW_DATA_47                                                        0xc06000e0
#define ixROM_SW_DATA_48                                                        0xc06000e4
#define ixROM_SW_DATA_49                                                        0xc06000e8
#define ixROM_SW_DATA_50                                                        0xc06000ec
#define ixROM_SW_DATA_51                                                        0xc06000f0
#define ixROM_SW_DATA_52                                                        0xc06000f4
#define ixROM_SW_DATA_53                                                        0xc06000f8
#define ixROM_SW_DATA_54                                                        0xc06000fc
#define ixROM_SW_DATA_55                                                        0xc0600100
#define ixROM_SW_DATA_56                                                        0xc0600104
#define ixROM_SW_DATA_57                                                        0xc0600108
#define ixROM_SW_DATA_58                                                        0xc060010c
#define ixROM_SW_DATA_59                                                        0xc0600110
#define ixROM_SW_DATA_60                                                        0xc0600114
#define ixROM_SW_DATA_61                                                        0xc0600118
#define ixROM_SW_DATA_62                                                        0xc060011c
#define ixROM_SW_DATA_63                                                        0xc0600120
#define ixROM_SW_DATA_64                                                        0xc0600124
#define mmGC_CAC_CGTT_CLK_CTRL                                                  0x3292
#define mmSE_CAC_CGTT_CLK_CTRL                                                  0x3293
#define mmGC_CAC_LKG_AGGR_LOWER                                                 0x3296
#define mmGC_CAC_LKG_AGGR_UPPER                                                 0x3297
#define ixGC_CAC_WEIGHT_CU_0                                                    0x32
#define ixGC_CAC_WEIGHT_CU_1                                                    0x33
#define ixGC_CAC_WEIGHT_CU_2                                                    0x34
#define ixGC_CAC_WEIGHT_CU_3                                                    0x35
#define ixGC_CAC_WEIGHT_CU_4                                                    0x36
#define ixGC_CAC_WEIGHT_CU_5                                                    0x37
#define ixGC_CAC_WEIGHT_CU_6                                                    0x38
#define ixGC_CAC_WEIGHT_CU_7                                                    0x39
#define ixGC_CAC_ACC_CU0                                                        0xba
#define ixGC_CAC_ACC_CU1                                                        0xbb
#define ixGC_CAC_ACC_CU2                                                        0xbc
#define ixGC_CAC_ACC_CU3                                                        0xbd
#define ixGC_CAC_ACC_CU4                                                        0xbe
#define ixGC_CAC_ACC_CU5                                                        0xbf
#define ixGC_CAC_ACC_CU6                                                        0xc0
#define ixGC_CAC_ACC_CU7                                                        0xc1
#define ixGC_CAC_ACC_CU8                                                        0xc2
#define ixGC_CAC_ACC_CU9                                                        0xc3
#define ixGC_CAC_ACC_CU10                                                       0xc4
#define ixGC_CAC_ACC_CU11                                                       0xc5
#define ixGC_CAC_ACC_CU12                                                       0xc6
#define ixGC_CAC_ACC_CU13                                                       0xc7
#define ixGC_CAC_ACC_CU14                                                       0xc8
#define ixGC_CAC_ACC_CU15                                                       0xc9
#define ixGC_CAC_OVRD_CU                                                        0xe7

#endif /* SMU_7_1_3_D_H */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /*
 * SMU_7_1_3 Register documentation
 *
 * Copyright (C) 2014  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef SMU_7_1_3_SH_MASK_H
#define SMU_7_1_3_SH_MASK_H

#define GCK_SMC_IND_INDEX__SMC_IND_ADDR_MASK 0xffffffff
#define GCK_SMC_IND_INDEX__SMC_IND_ADDR__SHIFT 0x0
#define GCK_SMC_IND_DATA__SMC_IND_DATA_MASK 0xffffffff
#define GCK_SMC_IND_DATA__SMC_IND_DATA__SHIFT 0x0
#define GCK_MCLK_FUSES__StartupMClkDid_MASK 0x7f
#define GCK_MCLK_FUSES__StartupMClkDid__SHIFT 0x0
#define GCK_MCLK_FUSES__MClkADCA_MASK 0x780
#define GCK_MCLK_FUSES__MClkADCA__SHIFT 0x7
#define GCK_MCLK_FUSES__MClkDDCA_MASK 0x1800
#define GCK_MCLK_FUSES__MClkDDCA__SHIFT 0xb
#define GCK_MCLK_FUSES__MClkDiDtWait_MASK 0xe000
#define GCK_MCLK_FUSES__MClkDiDtWait__SHIFT 0xd
#define GCK_MCLK_FUSES__MClkDiDtFloor_MASK 0x30000
#define GCK_MCLK_FUSES__MClkDiDtFloor__SHIFT 0x10
#define CG_DCLK_CNTL__DCLK_DIVIDER_MASK 0x7f
#define CG_DCLK_CNTL__DCLK_DIVIDER__SHIFT 0x0
#define CG_DCLK_CNTL__DCLK_DIR_CNTL_EN_MASK 0x100
#define CG_DCLK_CNTL__DCLK_DIR_CNTL_EN__SHIFT 0x8
#define CG_DCLK_CNTL__DCLK_DIR_CNTL_TOG_MASK 0x200
#define CG_DCLK_CNTL__DCLK_DIR_CNTL_TOG__SHIFT 0x9
#define CG_DCLK_CNTL__DCLK_DIR_CNTL_DIVIDER_MASK 0x1fc00
#define CG_DCLK_CNTL__DCLK_DIR_CNTL_DIVIDER__SHIFT 0xa
#define CG_DCLK_STATUS__DCLK_STATUS_MASK 0x1
#define CG_DCLK_STATUS__DCLK_STATUS__SHIFT 0x0
#define CG_DCLK_STATUS__DCLK_DIR_CNTL_DONETOG_MASK 0x2
#define CG_DCLK_STATUS__DCLK_DIR_CNTL_DONETOG__SHIFT 0x1
#define CG_VCLK_CNTL__VCLK_DIVIDER_MASK 0x7f
#define CG_VCLK_CNTL__VCLK_DIVIDER__SHIFT 0x0
#define CG_VCLK_CNTL__VCLK_DIR_CNTL_EN_MASK 0x100
#define CG_VCLK_CNTL__VCLK_DIR_CNTL_EN__SHIFT 0x8
#define CG_VCLK_CNTL__VCLK_DIR_CNTL_TOG_MASK 0x200
#define CG_VCLK_CNTL__VCLK_DIR_CNTL_TOG__SHIFT 0x9
#define CG_VCLK_CNTL__VCLK_DIR_CNTL_DIVIDER_MASK 0x1fc00
#define CG_VCLK_CNTL__VCLK_DIR_CNTL_DIVIDER__SHIFT 0xa
#define CG_VCLK_STATUS__VCLK_STATUS_MASK 0x1
#define CG_VCLK_STATUS__VCLK_STATUS__SHIFT 0x0
#define CG_VCLK_STATUS__VCLK_DIR_CNTL_DONETOG_MASK 0x2
#define CG_VCLK_STATUS__VCLK_DIR_CNTL_DONETOG__SHIFT 0x1
#define CG_ECLK_CNTL__ECLK_DIVIDER_MASK 0x7f
#define CG_ECLK_CNTL__ECLK_DIVIDER__SHIFT 0x0
#define CG_ECLK_CNTL__ECLK_DIR_CNTL_EN_MASK 0x100
#define CG_ECLK_CNTL__ECLK_DIR_CNTL_EN__SHIFT 0x8
#define CG_ECLK_CNTL__ECLK_DIR_CNTL_TOG_MASK 0x200
#define CG_ECLK_CNTL__ECLK_DIR_CNTL_TOG__SHIFT 0x9
#define CG_ECLK_CNTL__ECLK_DIR_CNTL_DIVIDER_MASK 0x1fc00
#define CG_ECLK_CNTL__ECLK_DIR_CNTL_DIVIDER__SHIFT 0xa
#define CG_ECLK_STATUS__ECLK_STATUS_MASK 0x1
#define CG_ECLK_STATUS__ECLK_STATUS__SHIFT 0x0
#define CG_ECLK_STATUS__ECLK_DIR_CNTL_DONETOG_MASK 0x2
#define CG_ECLK_STATUS__ECLK_DIR_CNTL_DONETOG__SHIFT 0x1
#define CG_ACLK_CNTL__ACLK_DIVIDER_MASK 0x7f
#define CG_ACLK_CNTL__ACLK_DIVIDER__SHIFT 0x0
#define CG_ACLK_CNTL__ACLK_DIR_CNTL_EN_MASK 0x100
#define CG_ACLK_CNTL__ACLK_DIR_CNTL_EN__SHIFT 0x8
#define CG_ACLK_CNTL__ACLK_DIR_CNTL_TOG_MASK 0x200
#define CG_ACLK_CNTL__ACLK_DIR_CNTL_TOG__SHIFT 0x9
#define CG_ACLK_CNTL__ACLK_DIR_CNTL_DIVIDER_MASK 0x1fc00
#define CG_ACLK_CNTL__ACLK_DIR_CNTL_DIVIDER__SHIFT 0xa
#define CG_MCLK_CNTL__MCLK_DIVIDER_MASK 0x7f
#define CG_MCLK_CNTL__MCLK_DIVIDER__SHIFT 0x0
#define CG_MCLK_CNTL__MCLK_DIR_CNTL_EN_MASK 0x100
#define CG_MCLK_CNTL__MCLK_DIR_CNTL_EN__SHIFT 0x8
#define CG_MCLK_CNTL__MCLK_DIR_CNTL_TOG_MASK 0x200
#define CG_MCLK_CNTL__MCLK_DIR_CNTL_TOG__SH