1
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG3                                        0x48d1
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG3                                        0x48f1
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG3                                        0x4911
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG3                                        0x4931
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG3                                        0x4951
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG3                                        0x4971
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG3                                        0x4991
#define mmBPHYC_UNIPHY7_UNIPHY_TMDP_REG3                                        0x49d1
#define mmBPHYC_UNIPHY8_UNIPHY_TMDP_REG3                                        0x49f1
#define mmUNIPHY_TMDP_REG4                                                      0x48d2
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG4                                        0x48d2
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG4                                        0x48f2
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG4                                        0x4912
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG4                                        0x4932
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG4                                        0x4952
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG4                                        0x4972
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG4                                        0x4992
#define mmBPHYC_UNIPHY7_UNIPHY_TMDP_REG4                                        0x49d2
#define mmBPHYC_UNIPHY8_UNIPHY_TMDP_REG4                                        0x49f2
#define mmUNIPHY_TMDP_REG5                                                      0x48d3
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG5                                        0x48d3
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG5                                        0x48f3
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG5                                        0x4913
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG5                                        0x4933
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG5                                        0x4953
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG5                                        0x4973
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG5                                        0x4993
#define mmBPHYC_UNIPHY7_UNIPHY_TMDP_REG5                                        0x49d3
#define mmBPHYC_UNIPHY8_UNIPHY_TMDP_REG5                                        0x49f3
#define mmUNIPHY_TMDP_REG6                                                      0x48d4
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG6                                        0x48d4
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG6                                        0x48f4
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG6                                        0x4914
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG6                                        0x4934
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG6                                        0x4954
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG6                                        0x4974
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG6                                        0x4994
#define mmBPHYC_UNIPHY7_UNIPHY_TMDP_REG6                                        0x49d4
#define mmBPHYC_UNIPHY8_UNIPHY_TMDP_REG6                                        0x49f4
#define mmUNIPHY_TPG_CONTROL                                                    0x48d5
#define mmBPHYC_UNIPHY0_UNIPHY_TPG_CONTROL                                      0x48d5
#define mmBPHYC_UNIPHY1_UNIPHY_TPG_CONTROL                                      0x48f5
#define mmBPHYC_UNIPHY2_UNIPHY_TPG_CONTROL                                      0x4915
#define mmBPHYC_UNIPHY3_UNIPHY_TPG_CONTROL                                      0x4935
#define mmBPHYC_UNIPHY4_UNIPHY_TPG_CONTROL                                      0x4955
#define mmBPHYC_UNIPHY5_UNIPHY_TPG_CONTROL                                      0x4975
#define mmBPHYC_UNIPHY6_UNIPHY_TPG_CONTROL                                      0x4995
#define mmBPHYC_UNIPHY7_UNIPHY_TPG_CONTROL                                      0x49d5
#define mmBPHYC_UNIPHY8_UNIPHY_TPG_CONTROL                                      0x49f5
#define mmUNIPHY_TPG_SEED                                                       0x48d6
#define mmBPHYC_UNIPHY0_UNIPHY_TPG_SEED                                         0x48d6
#define mmBPHYC_UNIPHY1_UNIPHY_TPG_SEED                                         0x48f6
#define mmBPHYC_UNIPHY2_UNIPHY_TPG_SEED                                         0x4916
#define mmBPHYC_UNIPHY3_UNIPHY_TPG_SEED                                         0x4936
#define mmBPHYC_UNIPHY4_UNIPHY_TPG_SEED                                         0x4956
#define mmBPHYC_UNIPHY5_UNIPHY_TPG_SEED                                         0x4976
#define mmBPHYC_UNIPHY6_UNIPHY_TPG_SEED                                         0x4996
#define mmBPHYC_UNIPHY7_UNIPHY_TPG_SEED                                         0x49d6
#define mmBPHYC_UNIPHY8_UNIPHY_TPG_SEED                                         0x49f6
#define mmUNIPHY_DEBUG                                                          0x48d7
#define mmBPHYC_UNIPHY0_UNIPHY_DEBUG                                            0x48d7
#define mmBPHYC_UNIPHY1_UNIPHY_DEBUG                                            0x48f7
#define mmBPHYC_UNIPHY2_UNIPHY_DEBUG                                            0x4917
#define mmBPHYC_UNIPHY3_UNIPHY_DEBUG                                            0x4937
#define mmBPHYC_UNIPHY4_UNIPHY_DEBUG                                            0x4957
#define mmBPHYC_UNIPHY5_UNIPHY_DEBUG                                            0x4977
#define mmBPHYC_UNIPHY6_UNIPHY_DEBUG                                            0x4997
#define mmBPHYC_UNIPHY7_UNIPHY_DEBUG                                            0x49d7
#define mmBPHYC_UNIPHY8_UNIPHY_DEBUG                                            0x49f7
#define mmDPG_PIPE_ARBITRATION_CONTROL1                                         0x1b30
#define mmDMIF_PG0_DPG_PIPE_ARBITRATION_CONTROL1                                0x1b30
#define mmDMIF_PG1_DPG_PIPE_ARBITRATION_CONTROL1                                0x1d30
#define mmDMIF_PG2_DPG_PIPE_ARBITRATION_CONTROL1                                0x1f30
#define mmDMIF_PG3_DPG_PIPE_ARBITRATION_CONTROL1                                0x4130
#define mmDMIF_PG4_DPG_PIPE_ARBITRATION_CONTROL1                                0x4330
#define mmDMIF_PG5_DPG_PIPE_ARBITRATION_CONTROL1                                0x4530
#define mmDPG_PIPE_ARBITRATION_CONTROL2                                         0x1b31
#define mmDMIF_PG0_DPG_PIPE_ARBITRATION_CONTROL2                                0x1b31
#define mmDMIF_PG1_DPG_PIPE_ARBITRATION_CONTROL2                                0x1d31
#define mmDMIF_PG2_DPG_PIPE_ARBITRATION_CONTROL2                                0x1f31
#define mmDMIF_PG3_DPG_PIPE_ARBITRATION_CONTROL2                                0x4131
#define mmDMIF_PG4_DPG_PIPE_ARBITRATION_CONTROL2                                0x4331
#define mmDMIF_PG5_DPG_PIPE_ARBITRATION_CONTROL2                                0x4531
#define mmDPG_WATERMARK_MASK_CONTROL                                            0x1b32
#define mmDMIF_PG0_DPG_WATERMARK_MASK_CONTROL                                   0x1b32
#define mmDMIF_PG1_DPG_WATERMARK_MASK_CONTROL                                   0x1d32
#define mmDMIF_PG2_DPG_WATERMARK_MASK_CONTROL                                   0x1f32
#define mmDMIF_PG3_DPG_WATERMARK_MASK_CONTROL                                   0x4132
#define mmDMIF_PG4_DPG_WATERMARK_MASK_CONTROL                                   0x4332
#define mmDMIF_PG5_DPG_WATERMARK_MASK_CONTROL                                   0x4532
#define mmDPG_PIPE_URGENCY_CONTROL                                              0x1b33
#define mmDMIF_PG0_DPG_PIPE_URGENCY_CONTROL                                     0x1b33
#define mmDMIF_PG1_DPG_PIPE_URGENCY_CONTROL                                     0x1d33
#define mmDMIF_PG2_DPG_PIPE_URGENCY_CONTROL                                     0x1f33
#define mmDMIF_PG3_DPG_PIPE_URGENCY_CONTROL                                     0x4133
#define mmDMIF_PG4_DPG_PIPE_URGENCY_CONTROL                                     0x4333
#define mmDMIF_PG5_DPG_PIPE_URGENCY_CONTROL                                     0x4533
#define mmDPG_PIPE_DPM_CONTROL                                                  0x1b34
#define mmDMIF_PG0_DPG_PIPE_DPM_CONTROL                                         0x1b34
#define mmDMIF_PG1_DPG_PIPE_DPM_CONTROL                                         0x1d34
#define mmDMIF_PG2_DPG_PIPE_DPM_CONTROL                                         0x1f34
#define mmDMIF_PG3_DPG_PIPE_DPM_CONTROL                                         0x4134
#define mmDMIF_PG4_DPG_PIPE_DPM_CONTROL                                         0x4334
#define mmDMIF_PG5_DPG_PIPE_DPM_CONTROL                                         0x4534
#define mmDPG_PIPE_STUTTER_CONTROL                                              0x1b35
#define mmDMIF_PG0_DPG_PIPE_STUTTER_CONTROL                                     0x1b35
#define mmDMIF_PG1_DPG_PIPE_STUTTER_CONTROL                                     0x1d35
#define mmDMIF_PG2_DPG_PIPE_STUTTER_CONTROL                                     0x1f35
#define mmDMIF_PG3_DPG_PIPE_STUTTER_CONTROL                                     0x4135
#define mmDMIF_PG4_DPG_PIPE_STUTTER_CONTROL                                     0x4335
#define mmDMIF_PG5_DPG_PIPE_STUTTER_CONTROL                                     0x4535
#define mmDPG_PIPE_NB_PSTATE_CHANGE_CONTROL                                     0x1b36
#define mmDMIF_PG0_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x1b36
#define mmDMIF_PG1_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x1d36
#define mmDMIF_PG2_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x1f36
#define mmDMIF_PG3_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x4136
#define mmDMIF_PG4_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x4336
#define mmDMIF_PG5_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x4536
#define mmDPG_PIPE_STUTTER_CONTROL_NONLPTCH                                     0x1b37
#define mmDMIF_PG0_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x1b37
#define mmDMIF_PG1_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x1d37
#define mmDMIF_PG2_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x1f37
#define mmDMIF_PG3_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4137
#define mmDMIF_PG4_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4337
#define mmDMIF_PG5_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4537
#define mmDPG_REPEATER_PROGRAM                                                  0x1b3a
#define mmDMIF_PG0_DPG_REPEATER_PROGRAM                                         0x1b3a
#define mmDMIF_PG1_DPG_REPEATER_PROGRAM                                         0x1d3a
#define mmDMIF_PG2_DPG_REPEATER_PROGRAM                                         0x1f3a
#define mmDMIF_PG3_DPG_REPEATER_PROGRAM                                         0x413a
#define mmDMIF_PG4_DPG_REPEATER_PROGRAM                                         0x433a
#define mmDMIF_PG5_DPG_REPEATER_PROGRAM                                         0x453a
#define mmDPG_HW_DEBUG_A                                                        0x1b3b
#define mmDMIF_PG0_DPG_HW_DEBUG_A                                               0x1b3b
#define mmDMIF_PG1_DPG_HW_DEBUG_A                                               0x1d3b
#define mmDMIF_PG2_DPG_HW_DEBUG_A                                               0x1f3b
#define mmDMIF_PG3_DPG_HW_DEBUG_A                                               0x413b
#define mmDMIF_PG4_DPG_HW_DEBUG_A                                               0x433b
#define mmDMIF_PG5_DPG_HW_DEBUG_A                                               0x453b
#define mmDPG_HW_DEBUG_B                                                        0x1b3c
#define mmDMIF_PG0_DPG_HW_DEBUG_B                                               0x1b3c
#define mmDMIF_PG1_DPG_HW_DEBUG_B                                               0x1d3c
#define mmDMIF_PG2_DPG_HW_DEBUG_B                                               0x1f3c
#define mmDMIF_PG3_DPG_HW_DEBUG_B                                               0x413c
#define mmDMIF_PG4_DPG_HW_DEBUG_B                                               0x433c
#define mmDMIF_PG5_DPG_HW_DEBUG_B                                               0x453c
#define mmDPG_HW_DEBUG_11                                                       0x1b3d
#define mmDMIF_PG0_DPG_HW_DEBUG_11                                              0x1b3d
#define mmDMIF_PG1_DPG_HW_DEBUG_11                                              0x1d3d
#define mmDMIF_PG2_DPG_HW_DEBUG_11                                              0x1f3d
#define mmDMIF_PG3_DPG_HW_DEBUG_11                                              0x413d
#define mmDMIF_PG4_DPG_HW_DEBUG_11                                              0x433d
#define mmDMIF_PG5_DPG_HW_DEBUG_11                                              0x453d
#define mmDPG_CHK_PRE_PROC_CNTL                                                 0x1b3e
#define mmDMIF_PG0_DPG_CHK_PRE_PROC_CNTL                                        0x1b3e
#define mmDMIF_PG1_DPG_CHK_PRE_PROC_CNTL                                        0x1d3e
#define mmDMIF_PG2_DPG_CHK_PRE_PROC_CNTL                                        0x1f3e
#define mmDMIF_PG3_DPG_CHK_PRE_PROC_CNTL                                        0x413e
#define mmDMIF_PG4_DPG_CHK_PRE_PROC_CNTL                                        0x433e
#define mmDMIF_PG5_DPG_CHK_PRE_PROC_CNTL                                        0x453e
#define mmDPG_TEST_DEBUG_INDEX                                                  0x1b38
#define mmDMIF_PG0_DPG_TEST_DEBUG_INDEX                                         0x1b38
#define mmDMIF_PG1_DPG_TEST_DEBUG_INDEX                                         0x1d38
#define mmDMIF_PG2_DPG_TEST_DEBUG_INDEX                                         0x1f38
#define mmDMIF_PG3_DPG_TEST_DEBUG_INDEX                                         0x4138
#define mmDMIF_PG4_DPG_TEST_DEBUG_INDEX                                         0x4338
#define mmDMIF_PG5_DPG_TEST_DEBUG_INDEX                                         0x4538
#define mmDPG_TEST_DEBUG_DATA                                                   0x1b39
#define mmDMIF_PG0_DPG_TEST_DEBUG_DATA                                          0x1b39
#define mmDMIF_PG1_DPG_TEST_DEBUG_DATA                                          0x1d39
#define mmDMIF_PG2_DPG_TEST_DEBUG_DATA                                          0x1f39
#define mmDMIF_PG3_DPG_TEST_DEBUG_DATA                                          0x4139
#define mmDMIF_PG4_DPG_TEST_DEBUG_DATA                                          0x4339
#define mmDMIF_PG5_DPG_TEST_DEBUG_DATA                                          0x4539
#define mmDPGV0_PIPE_ARBITRATION_CONTROL1                                       0x4730
#define mmDPGV1_PIPE_ARBITRATION_CONTROL1                                       0x473d
#define mmDPGV0_PIPE_ARBITRATION_CONTROL2                                       0x4731
#define mmDPGV1_PIPE_ARBITRATION_CONTROL2                                       0x473e
#define mmDPGV0_WATERMARK_MASK_CONTROL                                          0x4732
#define mmDPGV1_WATERMARK_MASK_CONTROL                                          0x473f
#define mmDPGV0_PIPE_URGENCY_CONTROL                                            0x4733
#define mmDPGV1_PIPE_URGENCY_CONTROL                                            0x4740
#define mmDPGV0_PIPE_DPM_CONTROL                                                0x4734
#define mmDPGV1_PIPE_DPM_CONTROL                                                0x4741
#define mmDPGV0_PIPE_STUTTER_CONTROL                                            0x4735
#define mmDPGV1_PIPE_STUTTER_CONTROL                                            0x4742
#define mmDPGV0_PIPE_NB_PSTATE_CHANGE_CONTROL                                   0x4736
#define mmDPGV1_PIPE_NB_PSTATE_CHANGE_CONTROL                                   0x4743
#define mmDPGV0_PIPE_STUTTER_CONTROL_NONLPTCH                                   0x4737
#define mmDPGV1_PIPE_STUTTER_CONTROL_NONLPTCH                                   0x4744
#define mmDPGV0_REPEATER_PROGRAM                                                0x4738
#define mmDPGV1_REPEATER_PROGRAM                                                0x4745
#define mmDPGV0_HW_DEBUG_A                                                      0x4739
#define mmDPGV1_HW_DEBUG_A                                                      0x4746
#define mmDPGV0_HW_DEBUG_B                                                      0x473a
#define mmDPGV1_HW_DEBUG_B                                                      0x4747
#define mmDPGV0_HW_DEBUG_11                                                     0x473b
#define mmDPGV1_HW_DEBUG_11                                                     0x4748
#define mmDPGV0_CHK_PRE_PROC_CNTL                                               0x473c
#define mmDPGV1_CHK_PRE_PROC_CNTL                                               0x4749
#define mmDPGV_TEST_DEBUG_INDEX                                                 0x474e
#define mmDPGV_TEST_DEBUG_DATA                                                  0x474f
#define ixDPGV0_DEBUG00_DMIFARB                                                 0x1
#define ixDPGV1_DEBUG00_DMIFARB                                                 0x6a
#define ixDPGV0_DEBUG01_DMIFARB                                                 0x2
#define ixDPGV1_DEBUG01_DMIFARB                                                 0x6b
#define ixDPGV0_DEBUG02_DMIFARB                                                 0x3
#define ixDPGV1_DEBUG02_DMIFARB                                                 0x6c
#define ixDPGV0_DEBUG03_DMIFARB                                                 0x4
#define ixDPGV1_DEBUG03_DMIFARB                                                 0x6d
#define ixDPGV0_DEBUG04_DMIFARB                                                 0x5
#define ixDPGV1_DEBUG04_DMIFARB                                                 0x6e
#define ixDPGV0_DEBUG00                                                         0x6
#define ixDPGV1_DEBUG00                                                         0x6f
#define ixDPGV0_DEBUG01                                                         0x7
#define ixDPGV1_DEBUG01                                                         0x70
#define ixDPGV0_DEBUG02                                                         0x8
#define ixDPGV1_DEBUG02                                                         0x71
#define mmAZROOT_IMMEDIATE_COMMAND_OUTPUT_INTERFACE_INDEX                       0x18
#define mmAZROOT_IMMEDIATE_COMMAND_OUTPUT_INTERFACE_DATA                        0x18
#define ixAZALIA_F2_CODEC_ROOT_PARAMETER_VENDOR_AND_DEVICE_ID                   0xf00
#define ixAZALIA_F2_CODEC_ROOT_PARAMETER_REVISION_ID                            0xf02
#define ixAZALIA_F2_CODEC_ROOT_PARAMETER_SUBORDINATE_NODE_COUNT                 0xf04
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_SUBORDINATE_NODE_COUNT             0x1f04
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_GROUP_TYPE                         0x1f05
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_SUPPORTED_SIZE_RATES               0x1f0a
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_STREAM_FORMATS                     0x1f0b
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_POWER_STATES                       0x1f0f
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_POWER_STATE                          0x1705
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESET                                0x17ff
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID                0x1720
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID_2              0x1721
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID_3              0x1722
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID_4              0x1723
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_CONVERTER_SYNCHRONIZATION            0x1770
#define mmAZALIA_F0_CODEC_ROOT_PARAMETER_VENDOR_AND_DEVICE_ID                   0x1828
#define mmAZALIA_F0_CODEC_ROOT_PARAMETER_REVISION_ID                            0x1829
#define mmAZALIA_F0_CODEC_CHANNEL_COUNT_CONTROL                                 0x182a
#define mmAZALIA_F0_CODEC_RESYNC_FIFO_CONTROL                                   0x182b
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_GROUP_TYPE                         0x182c
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_SUPPORTED_SIZE_RATES               0x182d
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_STREAM_FORMATS                     0x182e
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_POWER_STATES                       0x182f
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_POWER_STATE                          0x1830
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_RESET                                0x1831
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID                0x1832
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_CONVERTER_SYNCHRONIZATION            0x1833
#define mmCC_RCU_DC_AUDIO_PORT_CONNECTIVITY                                     0x1834
#define mmCC_RCU_DC_AUDIO_INPUT_PORT_CONNECTIVITY                               0x1835
#define mmAZALIA_F0_CODEC_DEBUG                                                 0x1836
#define mmAZALIA_F0_GTC_GROUP_OFFSET0                                           0x1837
#define mmAZALIA_F0_GTC_GROUP_OFFSET1                                           0x1838
#define mmAZALIA_F0_GTC_GROUP_OFFSET2                                           0x1839
#define mmAZALIA_F0_GTC_GROUP_OFFSET3                                           0x183a
#define mmAZALIA_F0_GTC_GROUP_OFFSET4                                           0x183b
#define mmAZALIA_F0_GTC_GROUP_OFFSET5                                           0x183c
#define mmAZALIA_F0_GTC_GROUP_OFFSET6                                           0x183d
#define mmGLOBAL_CAPABILITIES                                                   0x0
#define mmMINOR_VERSION                                                         0x0
#define mmMAJOR_VERSION                                                         0x0
#define mmOUTPUT_PAYLOAD_CAPABILITY                                             0x1
#define mmINPUT_PAYLOAD_CAPABILITY                                              0x1
#define mmGLOBAL_CONTROL                                                        0x2
#define mmWAKE_ENABLE                                                           0x3
#define mmSTATE_CHANGE_STATUS                                                   0x3
#define mmGLOBAL_STATUS                                                         0x4
#define mmOUTPUT_STREAM_PAYLOAD_CAPABILITY                                      0x6
#define mmINPUT_STREAM_PAYLOAD_CAPABILITY                                       0x6
#define mmINTERRUPT_CONTROL                                                     0x8
#define mmINTERRUPT_STATUS                                                      0x9
#define mmWALL_CLOCK_COUNTER                                                    0xc
#define mmSTREAM_SYNCHRONIZATION                                                0xe
#define mmCORB_LOWER_BASE_ADDRESS                                               0x10
#define mmCORB_UPPER_BASE_ADDRESS                                               0x11
#define mmCORB_WRITE_POINTER                                                    0x12
#define mmCORB_READ_POINTER                                                     0x12
#define mmCORB_CONTROL                                                          0x13
#define mmCORB_STATUS                                                           0x13
#define mmCORB_SIZE                                                             0x13
#define mmRIRB_LOWER_BASE_ADDRESS                                               0x14
#define mmRIRB_UPPER_BASE_ADDRESS                                               0x15
#define mmRIRB_WRITE_POINTER                                                    0x16
#define mmRESPONSE_INTERRUPT_COUNT                                              0x16
#define mmRIRB_CONTROL                                                          0x17
#define mmRIRB_STATUS                                                           0x17
#define mmRIRB_SIZE                                                             0x17
#define mmIMMEDIATE_COMMAND_OUTPUT_INTERFACE                                    0x18
#define mmIMMEDIATE_COMMAND_OUTPUT_INTERFACE_INDEX                              0x18
#define mmIMMEDIATE_COMMAND_OUTPUT_INTERFACE_DATA                               0x18
#define mmIMMEDIATE_RESPONSE_INPUT_INTERFACE                                    0x19
#define mmIMMEDIATE_COMMAND_STATUS                                              0x1a
#define mmDMA_POSITION_LOWER_BASE_ADDRESS                                       0x1c
#define mmDMA_POSITION_UPPER_BASE_ADDRESS                                       0x1d
#define mmWALL_CLOCK_COUNTER_ALIAS                                              0x80c
#define mmOUTPUT_STREAM_DESCRIPTOR_CONTROL_AND_STATUS                           0x20
#define mmOUTPUT_STREAM_DESCRIPTOR_LINK_POSITION_IN_CURRENT_BUFFER              0x21
#define mmOUTPUT_STREAM_DESCRIPTOR_CYCLIC_BUFFER_LENGTH                         0x22
#define mmOUTPUT_STREAM_DESCRIPTOR_LAST_VALID_INDEX                             0x23
#define mmOUTPUT_STREAM_DESCRIPTOR_FIFO_SIZE                                    0x24
#define mmOUTPUT_STREAM_DESCRIPTOR_FORMAT                                       0x24
#define mmOUTPUT_STREAM_DESCRIPTOR_BDL_POINTER_LOWER_BASE_ADDRESS               0x26
#define mmOUTPUT_STREAM_DESCRIPTOR_BDL_POINTER_UPPER_BASE_ADDRESS               0x27
#define mmOUTPUT_STREAM_DESCRIPTOR_LINK_POSITION_IN_CURRENT_BUFFER_ALIAS        0x821
#define mmAZENDPOINT_IMMEDIATE_COMMAND_OUTPUT_INTERFACE_INDEX                   0x18
#define mmAZENDPOINT_IMMEDIATE_COMMAND_OUTPUT_INTERFACE_DATA                    0x18
#define ixAZALIA_F2_CODEC_CONVERTER_PARAMETER_AUDIO_WIDGET_CAPABILITIES         0x2f09
#define ixAZALIA_F2_CODEC_CONVERTER_PARAMETER_SUPPORTED_SIZE_RATES              0x2f0a
#define ixAZALIA_F2_CODEC_CONVERTER_PARAMETER_STREAM_FORMATS                    0x2f0b
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_CONVERTER_FORMAT                    0x2200
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_CHANNEL_STREAM_ID                   0x2706
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER                   0x270d
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_2                 0x270e
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_DIGITAL_CONVERTER_3                 0x273e
#define ixAZALIA_F2_CODEC_CONVERTER_STRIPE_CONTROL                              0x2724
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_RAMP_RATE                           0x2770
#define ixAZALIA_F2_CODEC_CONVERTER_CONTROL_GTC_EMBEDDING                       0x2771
#define ixAZALIA_F2_CODEC_PIN_PARAMETER_AUDIO_WIDGET_CAPABILITIES               0x3f09
#define ixAZALIA_F2_CODEC_PIN_PARAMETER_CAPABILITIES                            0x3f0c
#define ixAZALIA_F2_CODEC_PIN_PARAMETER_CONNECTION_LIST_LENGTH                  0x3f0e
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_CONNECTION_LIST_ENTRY            0x3702
#define ixAZALIA_F2_CODEC_PIN_CONTROL_WIDGET_CONTROL                            0x3707
#define ixAZALIA_F2_CODEC_PIN_CONTROL_UNSOLICITED_RESPONSE                      0x3708
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_PIN_SENSE                        0x3709
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_CONFIGURATION_DEFAULT            0x371c
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_CONFIGURATION_DEFAULT_2          0x371d
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_CONFIGURATION_DEFAULT_3          0x371e
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_CONFIGURATION_DEFAULT_4          0x371f
#define ixAZALIA_F2_CODEC_PIN_CONTROL_RESPONSE_SPEAKER_ALLOCATION               0x3770
#define ixAZALIA_F2_CODEC_PIN_CONTROL_CHANNEL_ALLOCATION                        0x3771
#define ixAZALIA_F2_CODEC_PIN_CONTROL_DOWN_MIX_INFO                             0x3772
#define ixAZALIA_F2_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR                          0x3776
#define ixAZALIA_F2_CODEC_PIN_CONTROL_AUDIO_DESCRIPTOR_DATA                     0x3776
#define ixAUDIO_DESCRIPTOR0                                                     0x1
#define ixAUDIO_DESCRIPTOR1                                                     0x2
#define ixAUDIO_DESCRIPTOR2                                                     0x3
#define ixAUDIO_DESCRIPTOR3                                                     0x4
#define ixAUDIO_DESCRIPTOR4                                                     0x5
#define ixAUDIO_DESCRIPTOR5                                                     0x6
#define ixAUDIO_DESCRIPTOR6                                                     0x7
#define ixAUDIO_DESCRIPTOR7                                                     0x8
#define ixAUDIO_DESCRIPTOR8                                                     0x9
#define ixAUDIO_DESCRIPTOR9                                                     0xa
#define ixAUDIO_DESCRIPTOR10                                                    0xb
#define ixAUDIO_DESCRIPTOR11                                                    0xc
#define ixAUDIO_DESCRIPTOR12                                                    0xd
#define ixAUDIO_DESCRIPTOR13                                                    0xe
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL01_ENABLE                     0x3777
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL23_ENABLE                     0x3778
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL45_ENABLE                     0x3779
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL67_ENABLE                     0x377a
#define ixAZALIA_F2_CODEC_PIN_CONTROL_LIPSYNC                                   0x377b
#define ixAZALIA_F2_CODEC_PIN_CONTROL_HBR                                       0x377c
#define ixAZALIA_F2_CODEC_PIN_CONTROL_AUDIO_SINK_INFO_INDEX                     0x3780
#define ixAZALIA_F2_CODEC_PIN_CONTROL_AUDIO_SINK_INFO_DATA                      0x3781
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MANUFACTURER_ID                           0x0
#define ixAZALIA_F2_CODEC_PIN_CONTROL_PRODUCT_ID                                0x1
#define ixAZALIA_F2_CODEC_PIN_CONTROL_SINK_DESCRIPTION_LEN                      0x2
#define ixAZALIA_F2_CODEC_PIN_CONTROL_PORTID0                                   0x3
#define ixAZALIA_F2_CODEC_PIN_CONTROL_PORTID1                                   0x4
#define ixSINK_DESCRIPTION0                                                     0x5
#define ixSINK_DESCRIPTION1                                                     0x6
#define ixSINK_DESCRIPTION2                                                     0x7
#define ixSINK_DESCRIPTION3                                                     0x8
#define ixSINK_DESCRIPTION4                                                     0x9
#define ixSINK_DESCRIPTION5                                                     0xa
#define ixSINK_DESCRIPTION6                                                     0xb
#define ixSINK_DESCRIPTION7                                                     0xc
#define ixSINK_DESCRIPTION8                                                     0xd
#define ixSINK_DESCRIPTION9                                                     0xe
#define ixSINK_DESCRIPTION10                                                    0xf
#define ixSINK_DESCRIPTION11                                                    0x10
#define ixSINK_DESCRIPTION12                                                    0x11
#define ixSINK_DESCRIPTION13                                                    0x12
#define ixSINK_DESCRIPTION14                                                    0x13
#define ixSINK_DESCRIPTION15                                                    0x14
#define ixSINK_DESCRIPTION16                                                    0x15
#define ixSINK_DESCRIPTION17                                                    0x16
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL1_ENABLE                      0x3785
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL3_ENABLE                      0x3786
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL5_ENABLE                      0x3787
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL7_ENABLE                      0x3788
#define ixAZALIA_F2_CODEC_PIN_CONTROL_MULTICHANNEL_MODE                         0x3789
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_0                             0x378a
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_1                             0x378b
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_2                             0x378c
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_3                             0x378d
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_4                             0x378e
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_5                             0x378f
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_6                             0x3790
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_7                             0x3791
#define ixAZALIA_F2_PIN_CONTROL_CODEC_CS_OVERRIDE_8                             0x3792
#define ixAZALIA_F2_CODEC_PIN_ASSOCIATION_INFO                                  0x3793
#define ixAZALIA_F2_CODEC_PIN_CONTROL_DIGITAL_OUTPUT_STATUS                     0x3797
#define ixAZALIA_F2_CODEC_PIN_CONTROL_LPIB_SNAPSHOT_CONTROL                     0x3798
#define ixAZALIA_F2_CODEC_PIN_CONTROL_LPIB                                      0x3799
#define ixAZALIA_F2_CODEC_PIN_CONTROL_LPIB_TIMER_SNAPSHOT                       0x379a
#define ixAZALIA_F2_CODEC_PIN_CONTROL_CODING_TYPE                               0x379b
#define ixAZALIA_F2_CODEC_PIN_CONTROL_FORMAT_CHANGED                            0x379c
#define ixAZALIA_F2_CODEC_PIN_CONTROL_WIRELESS_DISPLAY_IDENTIFICATION           0x379d
#define ixAZALIA_F2_CODEC_PIN_CONTROL_REMOTE_KEEPALIVE                          0x379e
#define mmAZALIA_CONTROLLER_CLOCK_GATING                                        0x17e4
#define mmAZALIA_AUDIO_DTO                                                      0x17e5
#define mmAZALIA_AUDIO_DTO_CONTROL                                              0x17e6
#define mmAZALIA_SCLK_CONTROL                                                   0x17e7
#define mmAZALIA_UNDERFLOW_FILLER_SAMPLE                                        0x17e8
#define mmAZALIA_DATA_DMA_CONTROL                                               0x17e9
#define mmAZALIA_BDL_DMA_CONTROL                                                0x17ea
#define mmAZALIA_RIRB_AND_DP_CONTROL                                            0x17eb
#define mmAZALIA_CORB_DMA_CONTROL                                               0x17ec
#define mmAZALIA_APPLICATION_POSITION_IN_CYCLIC_BUFFER                          0x17f3
#define mmAZALIA_CYCLIC_BUFFER_SYNC                                             0x17f4
#define mmAZALIA_GLOBAL_CAPABILITIES                                            0x17f5
#define mmAZALIA_OUTPUT_PAYLOAD_CAPABILITY                                      0x17f6
#define mmAZALIA_OUTPUT_STREAM_ARBITER_CONTROL                                  0x17f7
#define mmAZALIA_INPUT_PAYLOAD_CAPABILITY                                       0x17f8
#define mmAZALIA_CONTROLLER_DEBUG                                               0x17f9
#define mmAZALIA_MEM_PWR_CTRL                                                   0x1810
#define mmAZALIA_MEM_PWR_STATUS                                                 0x1811
#define mmDCI_PG_DEBUG_CONFIG                                                   0x1812
#define mmAZALIA_INPUT_CRC0_CONTROL0                                            0x17fb
#define mmAZALIA_INPUT_CRC0_CONTROL1                                            0x17fc
#define mmAZALIA_INPUT_CRC0_CONTROL2                                            0x17fd
#define mmAZALIA_INPUT_CRC0_CONTROL3                                            0x17fe
#define mmAZALIA_INPUT_CRC0_RESULT                                              0x17ff
#define ixAZALIA_INPUT_CRC0_CHANNEL0                                            0x0
#define ixAZALIA_INPUT_CRC0_CHANNEL1                                            0x1
#define ixAZALIA_INPUT_CRC0_CHANNEL2                                            0x2
#define ixAZALIA_INPUT_CRC0_CHANNEL3                                            0x3
#define ixAZALIA_INPUT_CRC0_CHANNEL4                                            0x4
#define ixAZALIA_INPUT_CRC0_CHANNEL5                                            0x5
#define ixAZALIA_INPUT_CRC0_CHANNEL6                                            0x6
#define ixAZALIA_INPUT_CRC0_CHANNEL7                                            0x7
#define mmAZALIA_INPUT_CRC1_CONTROL0                                            0x1800
#define mmAZALIA_INPUT_CRC1_CONTROL1                                            0x1801
#define mmAZALIA_INPUT_CRC1_CONTROL2                                            0x1802
#define mmAZALIA_INPUT_CRC1_CONTROL3             