BE_CNTL_MODE {
	DIG_BE_DP_SST_MODE                               = 0x0,
	DIG_BE_RESERVED1                                 = 0x1,
	DIG_BE_TMDS_DVI_MODE                             = 0x2,
	DIG_BE_TMDS_HDMI_MODE                            = 0x3,
	DIG_BE_SDVO_RESERVED                             = 0x4,
	DIG_BE_DP_MST_MODE                               = 0x5,
	DIG_BE_RESERVED2                                 = 0x6,
	DIG_BE_RESERVED3                                 = 0x7,
} DIG_BE_CNTL_MODE;
typedef enum DIG_BE_CNTL_HPD_SELECT {
	DIG_BE_CNTL_HPD1                                 = 0x0,
	DIG_BE_CNTL_HPD2                                 = 0x1,
	DIG_BE_CNTL_HPD3                                 = 0x2,
	DIG_BE_CNTL_HPD4                                 = 0x3,
	DIG_BE_CNTL_HPD5                                 = 0x4,
	DIG_BE_CNTL_HPD6                                 = 0x5,
} DIG_BE_CNTL_HPD_SELECT;
typedef enum LVTMA_RANDOM_PATTERN_SEED_RAN_PAT {
	LVTMA_RANDOM_PATTERN_SEED_ALL_PIXELS             = 0x0,
	LVTMA_RANDOM_PATTERN_SEED_ONLY_DE_HIGH           = 0x1,
} LVTMA_RANDOM_PATTERN_SEED_RAN_PAT;
typedef enum TMDS_SYNC_PHASE {
	TMDS_NOT_SYNC_PHASE_ON_FRAME_START               = 0x0,
	TMDS_SYNC_PHASE_ON_FRAME_START                   = 0x1,
} TMDS_SYNC_PHASE;
typedef enum TMDS_DATA_SYNCHRONIZATION_DSINTSEL {
	TMDS_DATA_SYNCHRONIZATION_DSINTSEL_PCLK_TMDS     = 0x0,
	TMDS_DATA_SYNCHRONIZATION_DSINTSEL_TMDS_PLL      = 0x1,
} TMDS_DATA_SYNCHRONIZATION_DSINTSEL;
typedef enum TMDS_TRANSMITTER_ENABLE_HPD_MASK {
	TMDS_TRANSMITTER_HPD_MASK_NOT_OVERRIDE           = 0x0,
	TMDS_TRANSMITTER_HPD_MASK_OVERRIDE               = 0x1,
} TMDS_TRANSMITTER_ENABLE_HPD_MASK;
typedef enum TMDS_TRANSMITTER_ENABLE_LNKCEN_HPD_MASK {
	TMDS_TRANSMITTER_LNKCEN_HPD_MASK_NOT_OVERRIDE    = 0x0,
	TMDS_TRANSMITTER_LNKCEN_HPD_MASK_OVERRIDE        = 0x1,
} TMDS_TRANSMITTER_ENABLE_LNKCEN_HPD_MASK;
typedef enum TMDS_TRANSMITTER_ENABLE_LNKDEN_HPD_MASK {
	TMDS_TRANSMITTER_LNKDEN_HPD_MASK_NOT_OVERRIDE    = 0x0,
	TMDS_TRANSMITTER_LNKDEN_HPD_MASK_OVERRIDE        = 0x1,
} TMDS_TRANSMITTER_ENABLE_LNKDEN_HPD_MASK;
typedef enum TMDS_TRANSMITTER_CONTROL_PLL_ENABLE_HPD_MASK {
	TMDS_TRANSMITTER_HPD_NOT_OVERRIDE_PLL_ENABLE     = 0x0,
	TMDS_TRANSMITTER_HPD_OVERRIDE_PLL_ENABLE_ON_DISCON= 0x1,
	TMDS_TRANSMITTER_HPD_OVERRIDE_PLL_ENABLE_ON_CON  = 0x2,
	TMDS_TRANSMITTER_HPD_OVERRIDE_PLL_ENABLE         = 0x3,
} TMDS_TRANSMITTER_CONTROL_PLL_ENABLE_HPD_MASK;
typedef enum TMDS_TRANSMITTER_CONTROL_IDSCKSELA {
	TMDS_TRANSMITTER_IDSCKSELA_USE_IPIXCLK           = 0x0,
	TMDS_TRANSMITTER_IDSCKSELA_USE_IDCLK             = 0x1,
} TMDS_TRANSMITTER_CONTROL_IDSCKSELA;
typedef enum TMDS_TRANSMITTER_CONTROL_IDSCKSELB {
	TMDS_TRANSMITTER_IDSCKSELB_USE_IPIXCLK           = 0x0,
	TMDS_TRANSMITTER_IDSCKSELB_USE_IDCLK             = 0x1,
} TMDS_TRANSMITTER_CONTROL_IDSCKSELB;
typedef enum TMDS_TRANSMITTER_CONTROL_PLL_PWRUP_SEQ_EN {
	TMDS_TRANSMITTER_PLL_PWRUP_SEQ_DISABLE           = 0x0,
	TMDS_TRANSMITTER_PLL_PWRUP_SEQ_ENABLE            = 0x1,
} TMDS_TRANSMITTER_CONTROL_PLL_PWRUP_SEQ_EN;
typedef enum TMDS_TRANSMITTER_CONTROL_PLL_RESET_HPD_MASK {
	TMDS_TRANSMITTER_PLL_NOT_RST_ON_HPD              = 0x0,
	TMDS_TRANSMITTER_PLL_RST_ON_HPD                  = 0x1,
} TMDS_TRANSMITTER_CONTROL_PLL_RESET_HPD_MASK;
typedef enum TMDS_TRANSMITTER_CONTROL_TMCLK_FROM_PADS {
	TMDS_TRANSMITTER_TMCLK_FROM_TMDS_TMCLK           = 0x0,
	TMDS_TRANSMITTER_TMCLK_FROM_PADS                 = 0x1,
} TMDS_TRANSMITTER_CONTROL_TMCLK_FROM_PADS;
typedef enum TMDS_TRANSMITTER_CONTROL_TDCLK_FROM_PADS {
	TMDS_TRANSMITTER_TDCLK_FROM_TMDS_TDCLK           = 0x0,
	TMDS_TRANSMITTER_TDCLK_FROM_PADS                 = 0x1,
} TMDS_TRANSMITTER_CONTROL_TDCLK_FROM_PADS;
typedef enum TMDS_TRANSMITTER_CONTROL_PLLSEL_OVERWRITE_EN {
	TMDS_TRANSMITTER_PLLSEL_BY_HW                    = 0x0,
	TMDS_TRANSMITTER_PLLSEL_OVERWRITE_BY_SW          = 0x1,
} TMDS_TRANSMITTER_CONTROL_PLLSEL_OVERWRITE_EN;
typedef enum TMDS_TRANSMITTER_CONTROL_BYPASS_PLLA {
	TMDS_TRANSMITTER_BYPASS_PLLA_COHERENT            = 0x0,
	TMDS_TRANSMITTER_BYPASS_PLLA_INCOHERENT          = 0x1,
} TMDS_TRANSMITTER_CONTROL_BYPASS_PLLA;
typedef enum TMDS_TRANSMITTER_CONTROL_BYPASS_PLLB {
	TMDS_TRANSMITTER_BYPASS_PLLB_COHERENT            = 0x0,
	TMDS_TRANSMITTER_BYPASS_PLLB_INCOHERENT          = 0x1,
} TMDS_TRANSMITTER_CONTROL_BYPASS_PLLB;
typedef enum TMDS_REG_TEST_OUTPUTA_CNTLA {
	TMDS_REG_TEST_OUTPUTA_CNTLA_OTDATA0              = 0x0,
	TMDS_REG_TEST_OUTPUTA_CNTLA_OTDATA1              = 0x1,
	TMDS_REG_TEST_OUTPUTA_CNTLA_OTDATA2              = 0x2,
	TMDS_REG_TEST_OUTPUTA_CNTLA_NA                   = 0x3,
} TMDS_REG_TEST_OUTPUTA_CNTLA;
typedef enum TMDS_REG_TEST_OUTPUTB_CNTLB {
	TMDS_REG_TEST_OUTPUTB_CNTLB_OTDATB0              = 0x0,
	TMDS_REG_TEST_OUTPUTB_CNTLB_OTDATB1              = 0x1,
	TMDS_REG_TEST_OUTPUTB_CNTLB_OTDATB2              = 0x2,
	TMDS_REG_TEST_OUTPUTB_CNTLB_NA                   = 0x3,
} TMDS_REG_TEST_OUTPUTB_CNTLB;
typedef enum DP_LINK_TRAINING_COMPLETE {
	DP_LINK_TRAINING_NOT_COMPLETE                    = 0x0,
	DP_LINK_TRAINING_ALREADY_COMPLETE                = 0x1,
} DP_LINK_TRAINING_COMPLETE;
typedef enum DP_EMBEDDED_PANEL_MODE {
	DP_EXTERNAL_PANEL                                = 0x0,
	DP_EMBEDDED_PANEL                                = 0x1,
} DP_EMBEDDED_PANEL_MODE;
typedef enum DP_PIXEL_ENCODING {
	DP_PIXEL_ENCODING_RGB444                         = 0x0,
	DP_PIXEL_ENCODING_YCBCR422                       = 0x1,
	DP_PIXEL_ENCODING_YCBCR444                       = 0x2,
	DP_PIXEL_ENCODING_RGB_WIDE_GAMUT                 = 0x3,
	DP_PIXEL_ENCODING_Y_ONLY                         = 0x4,
	DP_PIXEL_ENCODING_RESERVED                       = 0x5,
} DP_PIXEL_ENCODING;
typedef enum DP_DYN_RANGE {
	DP_DYN_VESA_RANGE                                = 0x0,
	DP_DYN_CEA_RANGE                                 = 0x1,
} DP_DYN_RANGE;
typedef enum DP_YCBCR_RANGE {
	DP_YCBCR_RANGE_BT601_5                           = 0x0,
	DP_YCBCR_RANGE_BT709_5                           = 0x1,
} DP_YCBCR_RANGE;
typedef enum DP_COMPONENT_DEPTH {
	DP_COMPONENT_DEPTH_6BPC                          = 0x0,
	DP_COMPONENT_DEPTH_8BPC                          = 0x1,
	DP_COMPONENT_DEPTH_10BPC                         = 0x2,
	DP_COMPONENT_DEPTH_12BPC                         = 0x3,
	DP_COMPONENT_DEPTH_16BPC                         = 0x4,
	DP_COMPONENT_DEPTH_RESERVED                      = 0x5,
} DP_COMPONENT_DEPTH;
typedef enum DP_MSA_MISC0_OVERRIDE_ENABLE {
	MSA_MISC0_OVERRIDE_DISABLE                       = 0x0,
	MSA_MISC0_OVERRIDE_ENABLE                        = 0x1,
} DP_MSA_MISC0_OVERRIDE_ENABLE;
typedef enum DP_UDI_LANES {
	DP_UDI_1_LANE                                    = 0x0,
	DP_UDI_2_LANES                                   = 0x1,
	DP_UDI_LANES_RESERVED                            = 0x2,
	DP_UDI_4_LANES                                   = 0x3,
} DP_UDI_LANES;
typedef enum DP_VID_STREAM_DIS_DEFER {
	DP_VID_STREAM_DIS_NO_DEFER                       = 0x0,
	DP_VID_STREAM_DIS_DEFER_TO_HBLANK                = 0x1,
	DP_VID_STREAM_DIS_DEFER_TO_VBLANK                = 0x2,
} DP_VID_STREAM_DIS_DEFER;
typedef enum DP_STEER_OVERFLOW_ACK {
	DP_STEER_OVERFLOW_ACK_NO_EFFECT                  = 0x0,
	DP_STEER_OVERFLOW_ACK_CLR_INTERRUPT              = 0x1,
} DP_STEER_OVERFLOW_ACK;
typedef enum DP_STEER_OVERFLOW_MASK {
	DP_STEER_OVERFLOW_MASKED                         = 0x0,
	DP_STEER_OVERFLOW_UNMASK                         = 0x1,
} DP_STEER_OVERFLOW_MASK;
typedef enum DP_TU_OVERFLOW_ACK {
	DP_TU_OVERFLOW_ACK_NO_EFFECT                     = 0x0,
	DP_TU_OVERFLOW_ACK_CLR_INTERRUPT                 = 0x1,
} DP_TU_OVERFLOW_ACK;
typedef enum DP_VID_TIMING_MODE {
	DP_VID_TIMING_MODE_ASYNC                         = 0x0,
	DP_VID_TIMING_MODE_SYNC                          = 0x1,
} DP_VID_TIMING_MODE;
typedef enum DP_VID_M_N_DOUBLE_BUFFER_MODE {
	DP_VID_M_N_DOUBLE_BUFFER_AFTER_VID_M_UPDATE      = 0x0,
	DP_VID_M_N_DOUBLE_BUFFER_AT_FRAME_START          = 0x1,
} DP_VID_M_N_DOUBLE_BUFFER_MODE;
typedef enum DP_VID_M_N_GEN_EN {
	DP_VID_M_N_PROGRAMMED_VIA_REG                    = 0x0,
	DP_VID_M_N_CALC_AUTO                             = 0x1,
} DP_VID_M_N_GEN_EN;
typedef enum DP_VID_ENHANCED_FRAME_MODE {
	VID_NORMAL_FRAME_MODE                            = 0x0,
	VID_ENHANCED_MODE                                = 0x1,
} DP_VID_ENHANCED_FRAME_MODE;
typedef enum DP_VID_MSA_TOP_FIELD_MODE {
	DP_TOP_FIELD_ONLY                                = 0x0,
	DP_TOP_PLUS_BOTTOM_FIELD                         = 0x1,
} DP_VID_MSA_TOP_FIELD_MODE;
typedef enum DP_VID_VBID_FIELD_POL {
	DP_VID_VBID_FIELD_POL_NORMAL                     = 0x0,
	DP_VID_VBID_FIELD_POL_INV                        = 0x1,
} DP_VID_VBID_FIELD_POL;
typedef enum DP_VID_STREAM_DISABLE_ACK {
	ID_STREAM_DISABLE_NO_ACK                         = 0x0,
	ID_STREAM_DISABLE_ACKED                          = 0x1,
} DP_VID_STREAM_DISABLE_ACK;
typedef enum DP_VID_STREAM_DISABLE_MASK {
	VID_STREAM_DISABLE_MASKED                        = 0x0,
	VID_STREAM_DISABLE_UNMASK                        = 0x1,
} DP_VID_STREAM_DISABLE_MASK;
typedef enum DPHY_ATEST_SEL_LANE0 {
	DPHY_ATEST_LANE0_PRBS_PATTERN                    = 0x0,
	DPHY_ATEST_LANE0_REG_PATTERN                     = 0x1,
} DPHY_ATEST_SEL_LANE0;
typedef enum DPHY_ATEST_SEL_LANE1 {
	DPHY_ATEST_LANE1_PRBS_PATTERN                    = 0x0,
	DPHY_ATEST_LANE1_REG_PATTERN                     = 0x1,
} DPHY_ATEST_SEL_LANE1;
typedef enum DPHY_ATEST_SEL_LANE2 {
	DPHY_ATEST_LANE2_PRBS_PATTERN                    = 0x0,
	DPHY_ATEST_LANE2_REG_PATTERN                     = 0x1,
} DPHY_ATEST_SEL_LANE2;
typedef enum DPHY_ATEST_SEL_LANE3 {
	DPHY_ATEST_LANE3_PRBS_PATTERN                    = 0x0,
	DPHY_ATEST_LANE3_REG_PATTERN                     = 0x1,
} DPHY_ATEST_SEL_LANE3;
typedef enum DPHY_BYPASS {
	DPHY_8B10B_OUTPUT                                = 0x0,
	DPHY_DBG_OUTPUT                                  = 0x1,
} DPHY_BYPASS;
typedef enum DPHY_SKEW_BYPASS {
	DPHY_WITH_SKEW                                   = 0x0,
	DPHY_NO_SKEW                                     = 0x1,
} DPHY_SKEW_BYPASS;
typedef enum DPHY_TRAINING_PATTERN_SEL {
	DPHY_TRAINING_PATTERN_1                          = 0x0,
	DPHY_TRAINING_PATTERN_2                          = 0x1,
	DPHY_TRAINING_PATTERN_3                          = 0x2,
} DPHY_TRAINING_PATTERN_SEL;
typedef enum DPHY_8B10B_RESET {
	DPHY_8B10B_NOT_RESET                             = 0x0,
	DPHY_8B10B_RESETET                               = 0x1,
} DPHY_8B10B_RESET;
typedef enum DP_DPHY_8B10B_EXT_DISP {
	DP_DPHY_8B10B_EXT_DISP_ZERO                      = 0x0,
	DP_DPHY_8B10B_EXT_DISP_ONE                       = 0x1,
} DP_DPHY_8B10B_EXT_DISP;
typedef enum DPHY_8B10B_CUR_DISP {
	DPHY_8B10B_CUR_DISP_ZERO                         = 0x0,
	DPHY_8B10B_CUR_DISP_ONE                          = 0x1,
} DPHY_8B10B_CUR_DISP;
typedef enum DPHY_PRBS_EN {
	DPHY_PRBS_DISABLE                                = 0x0,
	DPHY_PRBS_ENABLE                                 = 0x1,
} DPHY_PRBS_EN;
typedef enum DPHY_PRBS_SEL {
	DPHY_PRBS7_SELECTED                              = 0x0,
	DPHY_PRBS23_SELECTED                             = 0x1,
	DPHY_PRBS11_SELECTED                             = 0x2,
} DPHY_PRBS_SEL;
typedef enum DPHY_LOAD_BS_COUNT_START {
	DPHY_LOAD_BS_COUNT_STARTED                       = 0x0,
	DPHY_LOAD_BS_COUNT_NOT_STARTED                   = 0x1,
} DPHY_LOAD_BS_COUNT_START;
typedef enum DPHY_CRC_EN {
	DPHY_CRC_DISABLED                                = 0x0,
	DPHY_CRC_ENABLED                                 = 0x1,
} DPHY_CRC_EN;
typedef enum DPHY_CRC_CONT_EN {
	DPHY_CRC_ONE_SHOT                                = 0x0,
	DPHY_CRC_CONTINUOUS                              = 0x1,
} DPHY_CRC_CONT_EN;
typedef enum DPHY_CRC_FIELD {
	DPHY_CRC_START_FROM_TOP_FIELD                    = 0x0,
	DPHY_CRC_START_FROM_BOTTOM_FIELD                 = 0x1,
} DPHY_CRC_FIELD;
typedef enum DPHY_CRC_SEL {
	DPHY_CRC_LANE0_SELECTED                          = 0x0,
	DPHY_CRC_LANE1_SELECTED                          = 0x1,
	DPHY_CRC_LANE2_SELECTED                          = 0x2,
	DPHY_CRC_LANE3_SELECTED                          = 0x3,
} DPHY_CRC_SEL;
typedef enum DPHY_RX_FAST_TRAINING_CAPABLE {
	DPHY_FAST_TRAINING_NOT_CAPABLE_0                 = 0x0,
	DPHY_FAST_TRAINING_CAPABLE                       = 0x1,
} DPHY_RX_FAST_TRAINING_CAPABLE;
typedef enum DP_SEC_COLLISION_ACK {
	DP_SEC_COLLISION_ACK_NO_EFFECT                   = 0x0,
	DP_SEC_COLLISION_ACK_CLR_FLAG                    = 0x1,
} DP_SEC_COLLISION_ACK;
typedef enum DP_SEC_AUDIO_MUTE {
	DP_SEC_AUDIO_MUTE_HW_CTRL                        = 0x0,
	DP_SEC_AUDIO_MUTE_SW_CTRL                        = 0x1,
} DP_SEC_AUDIO_MUTE;
typedef enum DP_SEC_TIMESTAMP_MODE {
	DP_SEC_TIMESTAMP_PROGRAMMABLE_MODE               = 0x0,
	DP_SEC_TIMESTAMP_AUTO_CALC_MODE                  = 0x1,
} DP_SEC_TIMESTAMP_MODE;
typedef enum DP_SEC_ASP_PRIORITY {
	DP_SEC_ASP_LOW_PRIORITY                          = 0x0,
	DP_SEC_ASP_HIGH_PRIORITY                         = 0x1,
} DP_SEC_ASP_PRIORITY;
typedef enum DP_SEC_ASP_CHANNEL_COUNT_OVERRIDE {
	DP_SEC_ASP_CHANNEL_COUNT_FROM_AZ                 = 0x0,
	DP_SEC_ASP_CHANNEL_COUNT_OVERRIDE_ENABLED        = 0x1,
} DP_SEC_ASP_CHANNEL_COUNT_OVERRIDE;
typedef enum DP_MSE_SAT_UPDATE_ACT {
	DP_MSE_SAT_UPDATE_NO_ACTION                      = 0x0,
	DP_MSE_SAT_UPDATE_WITH_TRIGGER                   = 0x1,
	DP_MSE_SAT_UPDATE_WITHOUT_TRIGGER                = 0x2,
} DP_MSE_SAT_UPDATE_ACT;
typedef enum DP_MSE_LINK_LINE {
	DP_MSE_LINK_LINE_32_MTP_LONG                     = 0x0,
	DP_MSE_LINK_LINE_64_MTP_LONG                     = 0x1,
	DP_MSE_LINK_LINE_128_MTP_LONG                    = 0x2,
	DP_MSE_LINK_LINE_256_MTP_LONG                    = 0x3,
} DP_MSE_LINK_LINE;
typedef enum DP_MSE_BLANK_CODE {
	DP_MSE_BLANK_CODE_SF_FILLED                      = 0x0,
	DP_MSE_BLANK_CODE_ZERO_FILLED                    = 0x1,
} DP_MSE_BLANK_CODE;
typedef enum DP_MSE_TIMESTAMP_MODE {
	DP_MSE_TIMESTAMP_CALC_BASED_ON_LINK_RATE         = 0x0,
	DP_MSE_TIMESTAMP_CALC_BASED_ON_VC_RATE           = 0x1,
} DP_MSE_TIMESTAMP_MODE;
typedef enum DP_MSE_ZERO_ENCODER {
	DP_MSE_NOT_ZERO_FE_ENCODER                       = 0x0,
	DP_MSE_ZERO_FE_ENCODER                           = 0x1,
} DP_MSE_ZERO_ENCODER;
typedef enum DP_MSE_OUTPUT_DPDBG_DATA {
	DP_MSE_OUTPUT_DPDBG_DATA_DIS                     = 0x0,
	DP_MSE_OUTPUT_DPDBG_DATA_EN                      = 0x1,
} DP_MSE_OUTPUT_DPDBG_DATA;
typedef enum DP_DPHY_HBR2_PATTERN_CONTROL_MODE {
	DP_DPHY_HBR2_PASS_THROUGH                        = 0x0,
	DP_DPHY_HBR2_PATTERN_1                           = 0x1,
	DP_DPHY_HBR2_PATTERN_2_NEG                       = 0x2,
	DP_DPHY_HBR2_PATTERN_3                           = 0x3,
	DP_DPHY_HBR2_PATTERN_2_POS                       = 0x6,
} DP_DPHY_HBR2_PATTERN_CONTROL_MODE;
typedef enum DPHY_CRC_MST_PHASE_ERROR_ACK {
	DPHY_CRC_MST_PHASE_ERROR_NO_ACK                  = 0x0,
	DPHY_CRC_MST_PHASE_ERROR_ACKED                   = 0x1,
} DPHY_CRC_MST_PHASE_ERROR_ACK;
typedef enum DPHY_SW_FAST_TRAINING_START {
	DPHY_SW_FAST_TRAINING_NOT_STARTED                = 0x0,
	DPHY_SW_FAST_TRAINING_STARTED                    = 0x1,
} DPHY_SW_FAST_TRAINING_START;
typedef enum DP_DPHY_FAST_TRAINING_VBLANK_EDGE_DETECT_EN {
	DP_DPHY_FAST_TRAINING_VBLANK_EDGE_DETECT_DISABLED= 0x0,
	DP_DPHY_FAST_TRAINING_VBLANK_EDGE_DETECT_ENABLED = 0x1,
} DP_DPHY_FAST_TRAINING_VBLANK_EDGE_DETECT_EN;
typedef enum DP_DPHY_FAST_TRAINING_COMPLETE_MASK {
	DP_DPHY_FAST_TRAINING_COMPLETE_MASKED            = 0x0,
	DP_DPHY_FAST_TRAINING_COMPLETE_NOT_MASKED        = 0x1,
} DP_DPHY_FAST_TRAINING_COMPLETE_MASK;
typedef enum DP_DPHY_FAST_TRAINING_COMPLETE_ACK {
	DP_DPHY_FAST_TRAINING_COMPLETE_NOT_ACKED         = 0x0,
	DP_DPHY_FAST_TRAINING_COMPLETE_ACKED             = 0x1,
} DP_DPHY_FAST_TRAINING_COMPLETE_ACK;
typedef enum DP_MSA_V_TIMING_OVERRIDE_EN {
	MSA_V_TIMING_OVERRIDE_DISABLED                   = 0x0,
	MSA_V_TIMING_OVERRIDE_ENABLED                    = 0x1,
} DP_MSA_V_TIMING_OVERRIDE_EN;
typedef enum DP_SEC_GSP0_PRIORITY {
	SEC_GSP0_PRIORITY_LOW                            = 0x0,
	SEC_GSP0_PRIORITY_HIGH                           = 0x1,
} DP_SEC_GSP0_PRIORITY;
typedef enum DP_SEC_GSP0_SEND {
	NOT_SENT                                         = 0x0,
	FORCE_SENT                                       = 0x1,
} DP_SEC_GSP0_SEND;
typedef enum DP_AUX_CONTROL_HPD_SEL {
	DP_AUX_CONTROL_HPD1_SELECTED                     = 0x0,
	DP_AUX_CONTROL_HPD2_SELECTED                     = 0x1,
	DP_AUX_CONTROL_HPD3_SELECTED                     = 0x2,
	DP_AUX_CONTROL_HPD4_SELECTED                     = 0x3,
	DP_AUX_CONTROL_HPD5_SELECTED                     = 0x4,
	DP_AUX_CONTROL_HPD6_SELECTED                     = 0x5,
} DP_AUX_CONTROL_HPD_SEL;
typedef enum DP_AUX_CONTROL_TEST_MODE {
	DP_AUX_CONTROL_TEST_MODE_DISABLE                 = 0x0,
	DP_AUX_CONTROL_TEST_MODE_ENABLE                  = 0x1,
} DP_AUX_CONTROL_TEST_MODE;
typedef enum DP_AUX_SW_CONTROL_SW_GO {
	DP_AUX_SW_CONTROL_SW__NOT_GO                     = 0x0,
	DP_AUX_SW_CONTROL_SW__GO                         = 0x1,
} DP_AUX_SW_CONTROL_SW_GO;
typedef enum DP_AUX_SW_CONTROL_LS_READ_TRIG {
	DP_AUX_SW_CONTROL_LS_READ__NOT_TRIG              = 0x0,
	DP_AUX_SW_CONTROL_LS_READ__TRIG                  = 0x1,
} DP_AUX_SW_CONTROL_LS_READ_TRIG;
typedef enum DP_AUX_ARB_CONTROL_ARB_PRIORITY {
	DP_AUX_ARB_CONTROL_ARB_PRIORITY__GTC_LS_SW       = 0x0,
	DP_AUX_ARB_CONTROL_ARB_PRIORITY__LS_GTC_SW       = 0x1,
	DP_AUX_ARB_CONTROL_ARB_PRIORITY__SW_LS_GTC       = 0x2,
	DP_AUX_ARB_CONTROL_ARB_PRIORITY__SW_GTC_LS       = 0x3,
} DP_AUX_ARB_CONTROL_ARB_PRIORITY;
typedef enum DP_AUX_ARB_CONTROL_USE_AUX_REG_REQ {
	DP_AUX_ARB_CONTROL__NOT_USE_AUX_REG_REQ          = 0x0,
	DP_AUX_ARB_CONTROL__USE_AUX_REG_REQ              = 0x1,
} DP_AUX_ARB_CONTROL_USE_AUX_REG_REQ;
typedef enum DP_AUX_ARB_CONTROL_DONE_USING_AUX_REG {
	DP_AUX_ARB_CONTROL__DONE_NOT_USING_AUX_REG       = 0x0,
	DP_AUX_ARB_CONTROL__DONE_USING_AUX_REG           = 0x1,
} DP_AUX_ARB_CONTROL_DONE_USING_AUX_REG;
typedef enum DP_AUX_INT_ACK {
	DP_AUX_INT__NOT_ACK                              = 0x0,
	DP_AUX_INT__ACK                                  = 0x1,
} DP_AUX_INT_ACK;
typedef enum DP_AUX_LS_UPDATE_ACK {
	DP_AUX_INT_LS_UPDATE_NOT_ACK                     = 0x0,
	DP_AUX_INT_LS_UPDATE_ACK                         = 0x1,
} DP_AUX_LS_UPDATE_ACK;
typedef enum DP_AUX_DPHY_TX_REF_CONTROL_TX_REF_SEL {
	DP_AUX_DPHY_TX_REF_CONTROL_TX_REF_SEL__DIVIDED_SYM_CLK= 0x0,
	DP_AUX_DPHY_TX_REF_CONTROL_TX_REF_SEL__FROM_DCCG_MICROSECOND_REF= 0x1,
} DP_AUX_DPHY_TX_REF_CONTROL_TX_REF_SEL;
typedef enum DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE {
	DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE__1MHZ         = 0x0,
	DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE__2MHZ         = 0x1,
	DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE__4MHZ         = 0x2,
	DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE__8MHZ         = 0x3,
} DP_AUX_DPHY_TX_REF_CONTROL_TX_RATE;
typedef enum DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN {
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__0US        = 0x0,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__8US        = 0x1,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__16US       = 0x2,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__24US       = 0x3,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__32US       = 0x4,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__40US       = 0x5,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__48US       = 0x6,
	DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN__56US       = 0x7,
} DP_AUX_DPHY_TX_CONTROL_PRECHARGE_LEN;
typedef enum DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY {
	DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY__0   = 0x0,
	DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY__16US= 0x1,
	DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY__32US= 0x2,
	DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY__64US= 0x3,
	DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY__128US= 0x4,
	DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY__256US= 0x5,
} DP_AUX_DPHY_TX_CONTROL_MODE_DET_CHECK_DELAY;
typedef enum DP_AUX_DPHY_RX_CONTROL_START_WINDOW {
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO2_PERIOD = 0x0,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO4_PERIOD = 0x1,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO8_PERIOD = 0x2,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO16_PERIOD= 0x3,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO32_PERIOD= 0x4,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO64_PERIOD= 0x5,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO128_PERIOD= 0x6,
	DP_AUX_DPHY_RX_CONTROL_START_WINDOW__1TO256_PERIOD= 0x7,
} DP_AUX_DPHY_RX_CONTROL_START_WINDOW;
typedef enum DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW {
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO2_PERIOD= 0x0,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO4_PERIOD= 0x1,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO8_PERIOD= 0x2,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO16_PERIOD= 0x3,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO32_PERIOD= 0x4,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO64_PERIOD= 0x5,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO128_PERIOD= 0x6,
	DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW__1TO256_PERIOD= 0x7,
} DP_AUX_DPHY_RX_CONTROL_RECEIVE_WINDOW;
typedef enum DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN {
	DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN__6_EDGES= 0x0,
	DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN__10_EDGES= 0x1,
	DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN__18_EDGES= 0x2,
	DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN__RESERVED= 0x3,
} DP_AUX_DPHY_RX_CONTROL_HALF_SYM_DETECT_LEN;
typedef enum DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_PHASE_DETECT {
	DP_AUX_DPHY_RX_CONTROL__NOT_ALLOW_BELOW_THRESHOLD_PHASE_DETECT= 0x0,
	DP_AUX_DPHY_RX_CONTROL__ALLOW_BELOW_THRESHOLD_PHASE_DETECT= 0x1,
} DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_PHASE_DETECT;
typedef enum DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_START {
	DP_AUX_DPHY_RX_CONTROL__NOT_ALLOW_BELOW_THRESHOLD_START= 0x0,
	DP_AUX_DPHY_RX_CONTROL__ALLOW_BELOW_THRESHOLD_START= 0x1,
} DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_START;
typedef enum DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_STOP {
	DP_AUX_DPHY_RX_CONTROL__NOT_ALLOW_BELOW_THRESHOLD_STOP= 0x0,
	DP_AUX_DPHY_RX_CONTROL__ALLOW_BELOW_THRESHOLD_STOP= 0x1,
} DP_AUX_DPHY_RX_CONTROL_ALLOW_BELOW_THRESHOLD_STOP;
typedef enum DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN {
	DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN__2_HALF_SYMBOLS= 0x0,
	DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN__4_HALF_SYMBOLS= 0x1,
	DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN__6_HALF_SYMBOLS= 0x2,
	DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN__8_HALF_SYMBOLS= 0x3,
} DP_AUX_DPHY_RX_CONTROL_PHASE_DETECT_LEN;
typedef enum DP_AUX_DPHY_RX_CONTROL_TIMEOUT_LEN {
	DP_AUX_DPHY_RX_CONTROL_TIMEOUT_LEN_450US         = 0x0,
	DP_AUX_DPHY_RX_CONTROL_TIMEOUT_LEN_500US         = 0x1,
	DP_AUX_DPHY_RX_CONTROL_TIMEOUT_LEN_550US      