                       0x1749
#define mmBPHYC_PLL2_PPLL_DIV_UPDATE_DEBUG                                      0x1773
#define mmPPLL_STATUS_DEBUG                                                     0x1720
#define mmBPHYC_PLL0_PPLL_STATUS_DEBUG                                          0x1720
#define mmBPHYC_PLL1_PPLL_STATUS_DEBUG                                          0x174a
#define mmBPHYC_PLL2_PPLL_STATUS_DEBUG                                          0x1774
#define mmPPLL_DEBUG_MUX_CNTL                                                   0x1721
#define mmBPHYC_PLL0_PPLL_DEBUG_MUX_CNTL                                        0x1721
#define mmBPHYC_PLL1_PPLL_DEBUG_MUX_CNTL                                        0x174b
#define mmBPHYC_PLL2_PPLL_DEBUG_MUX_CNTL                                        0x1775
#define mmPPLL_SPARE0                                                           0x1722
#define mmBPHYC_PLL0_PPLL_SPARE0                                                0x1722
#define mmBPHYC_PLL1_PPLL_SPARE0                                                0x174c
#define mmBPHYC_PLL2_PPLL_SPARE0                                                0x1776
#define mmPPLL_SPARE1                                                           0x1723
#define mmBPHYC_PLL0_PPLL_SPARE1                                                0x1723
#define mmBPHYC_PLL1_PPLL_SPARE1                                                0x174d
#define mmBPHYC_PLL2_PPLL_SPARE1                                                0x1777
#define mmUNIPHY_TX_CONTROL1                                                    0x48c0
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL1                                      0x48c0
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL1                                      0x48e0
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL1                                      0x4900
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL1                                      0x4920
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL1                                      0x4940
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL1                                      0x4960
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL1                                      0x4980
#define mmBPHYC_UNIPHY7_UNIPHY_TX_CONTROL1                                      0x49c0
#define mmBPHYC_UNIPHY8_UNIPHY_TX_CONTROL1                                      0x49e0
#define mmUNIPHY_TX_CONTROL2                                                    0x48c1
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL2                                      0x48c1
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL2                                      0x48e1
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL2                                      0x4901
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL2                                      0x4921
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL2                                      0x4941
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL2                                      0x4961
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL2                                      0x4981
#define mmBPHYC_UNIPHY7_UNIPHY_TX_CONTROL2                                      0x49c1
#define mmBPHYC_UNIPHY8_UNIPHY_TX_CONTROL2                                      0x49e1
#define mmUNIPHY_TX_CONTROL3                                                    0x48c2
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL3                                      0x48c2
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL3                                      0x48e2
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL3                                      0x4902
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL3                                      0x4922
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL3                                      0x4942
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL3                                      0x4962
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL3                                      0x4982
#define mmBPHYC_UNIPHY7_UNIPHY_TX_CONTROL3                                      0x49c2
#define mmBPHYC_UNIPHY8_UNIPHY_TX_CONTROL3                                      0x49e2
#define mmUNIPHY_TX_CONTROL4                                                    0x48c3
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL4                                      0x48c3
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL4                                      0x48e3
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL4                                      0x4903
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL4                                      0x4923
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL4                                      0x4943
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL4                                      0x4963
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL4                                      0x4983
#define mmBPHYC_UNIPHY7_UNIPHY_TX_CONTROL4                                      0x49c3
#define mmBPHYC_UNIPHY8_UNIPHY_TX_CONTROL4                                      0x49e3
#define mmUNIPHY_POWER_CONTROL                                                  0x48c4
#define mmBPHYC_UNIPHY0_UNIPHY_POWER_CONTROL                                    0x48c4
#define mmBPHYC_UNIPHY1_UNIPHY_POWER_CONTROL                                    0x48e4
#define mmBPHYC_UNIPHY2_UNIPHY_POWER_CONTROL                                    0x4904
#define mmBPHYC_UNIPHY3_UNIPHY_POWER_CONTROL                                    0x4924
#define mmBPHYC_UNIPHY4_UNIPHY_POWER_CONTROL                                    0x4944
#define mmBPHYC_UNIPHY5_UNIPHY_POWER_CONTROL                                    0x4964
#define mmBPHYC_UNIPHY6_UNIPHY_POWER_CONTROL                                    0x4984
#define mmBPHYC_UNIPHY7_UNIPHY_POWER_CONTROL                                    0x49c4
#define mmBPHYC_UNIPHY8_UNIPHY_POWER_CONTROL                                    0x49e4
#define mmUNIPHY_PLL_FBDIV                                                      0x48c5
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_FBDIV                                        0x48c5
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_FBDIV                                        0x48e5
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_FBDIV                                        0x4905
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_FBDIV                                        0x4925
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_FBDIV                                        0x4945
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_FBDIV                                        0x4965
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_FBDIV                                        0x4985
#define mmBPHYC_UNIPHY7_UNIPHY_PLL_FBDIV                                        0x49c5
#define mmBPHYC_UNIPHY8_UNIPHY_PLL_FBDIV                                        0x49e5
#define mmUNIPHY_PLL_CONTROL1                                                   0x48c6
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_CONTROL1                                     0x48c6
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_CONTROL1                                     0x48e6
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_CONTROL1                                     0x4906
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_CONTROL1                                     0x4926
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_CONTROL1                                     0x4946
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_CONTROL1                                     0x4966
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_CONTROL1                                     0x4986
#define mmBPHYC_UNIPHY7_UNIPHY_PLL_CONTROL1                                     0x49c6
#define mmBPHYC_UNIPHY8_UNIPHY_PLL_CONTROL1                                     0x49e6
#define mmUNIPHY_PLL_CONTROL2                                                   0x48c7
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_CONTROL2                                     0x48c7
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_CONTROL2                                     0x48e7
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_CONTROL2                                     0x4907
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_CONTROL2                                     0x4927
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_CONTROL2                                     0x4947
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_CONTROL2                                     0x4967
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_CONTROL2                                     0x4987
#define mmBPHYC_UNIPHY7_UNIPHY_PLL_CONTROL2                                     0x49c7
#define mmBPHYC_UNIPHY8_UNIPHY_PLL_CONTROL2                                     0x49e7
#define mmUNIPHY_PLL_SS_STEP_SIZE                                               0x48c8
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_SS_STEP_SIZE                                 0x48c8
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_SS_STEP_SIZE                                 0x48e8
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_SS_STEP_SIZE                                 0x4908
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_SS_STEP_SIZE                                 0x4928
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_SS_STEP_SIZE                                 0x4948
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_SS_STEP_SIZE                                 0x4968
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_SS_STEP_SIZE                                 0x4988
#define mmBPHYC_UNIPHY7_UNIPHY_PLL_SS_STEP_SIZE                                 0x49c8
#define mmBPHYC_UNIPHY8_UNIPHY_PLL_SS_STEP_SIZE                                 0x49e8
#define mmUNIPHY_PLL_SS_CNTL                                                    0x48c9
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_SS_CNTL                                      0x48c9
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_SS_CNTL                                      0x48e9
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_SS_CNTL                                      0x4909
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_SS_CNTL                                      0x4929
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_SS_CNTL                                      0x4949
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_SS_CNTL                                      0x4969
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_SS_CNTL                                      0x4989
#define mmBPHYC_UNIPHY7_UNIPHY_PLL_SS_CNTL                                      0x49c9
#define mmBPHYC_UNIPHY8_UNIPHY_PLL_SS_CNTL                                      0x49e9
#define mmUNIPHY_DATA_SYNCHRONIZATION                                           0x48ca
#define mmBPHYC_UNIPHY0_UNIPHY_DATA_SYNCHRONIZATION                             0x48ca
#define mmBPHYC_UNIPHY1_UNIPHY_DATA_SYNCHRONIZATION                             0x48ea
#define mmBPHYC_UNIPHY2_UNIPHY_DATA_SYNCHRONIZATION                             0x490a
#define mmBPHYC_UNIPHY3_UNIPHY_DATA_SYNCHRONIZATION                             0x492a
#define mmBPHYC_UNIPHY4_UNIPHY_DATA_SYNCHRONIZATION                             0x494a
#define mmBPHYC_UNIPHY5_UNIPHY_DATA_SYNCHRONIZATION                             0x496a
#define mmBPHYC_UNIPHY6_UNIPHY_DATA_SYNCHRONIZATION                             0x498a
#define mmBPHYC_UNIPHY7_UNIPHY_DATA_SYNCHRONIZATION                             0x49ca
#define mmBPHYC_UNIPHY8_UNIPHY_DATA_SYNCHRONIZATION                             0x49ea
#define mmUNIPHY_REG_TEST_OUTPUT                                                0x48cb
#define mmBPHYC_UNIPHY0_UNIPHY_REG_TEST_OUTPUT                                  0x48cb
#define mmBPHYC_UNIPHY1_UNIPHY_REG_TEST_OUTPUT                                  0x48eb
#define mmBPHYC_UNIPHY2_UNIPHY_REG_TEST_OUTPUT                                  0x490b
#define mmBPHYC_UNIPHY3_UNIPHY_REG_TEST_OUTPUT                                  0x492b
#define mmBPHYC_UNIPHY4_UNIPHY_REG_TEST_OUTPUT                                  0x494b
#define mmBPHYC_UNIPHY5_UNIPHY_REG_TEST_OUTPUT                                  0x496b
#define mmBPHYC_UNIPHY6_UNIPHY_REG_TEST_OUTPUT                                  0x498b
#define mmBPHYC_UNIPHY7_UNIPHY_REG_TEST_OUTPUT                                  0x49cb
#define mmBPHYC_UNIPHY8_UNIPHY_REG_TEST_OUTPUT                                  0x49eb
#define mmUNIPHY_ANG_BIST_CNTL                                                  0x48cc
#define mmBPHYC_UNIPHY0_UNIPHY_ANG_BIST_CNTL                                    0x48cc
#define mmBPHYC_UNIPHY1_UNIPHY_ANG_BIST_CNTL                                    0x48ec
#define mmBPHYC_UNIPHY2_UNIPHY_ANG_BIST_CNTL                                    0x490c
#define mmBPHYC_UNIPHY3_UNIPHY_ANG_BIST_CNTL                                    0x492c
#define mmBPHYC_UNIPHY4_UNIPHY_ANG_BIST_CNTL                                    0x494c
#define mmBPHYC_UNIPHY5_UNIPHY_ANG_BIST_CNTL                                    0x496c
#define mmBPHYC_UNIPHY6_UNIPHY_ANG_BIST_CNTL                                    0x498c
#define mmBPHYC_UNIPHY7_UNIPHY_ANG_BIST_CNTL                                    0x49cc
#define mmBPHYC_UNIPHY8_UNIPHY_ANG_BIST_CNTL                                    0x49ec
#define mmUNIPHY_REG_TEST_OUTPUT2                                               0x48cd
#define mmBPHYC_UNIPHY0_UNIPHY_REG_TEST_OUTPUT2                                 0x48cd
#define mmBPHYC_UNIPHY1_UNIPHY_REG_TEST_OUTPUT2                                 0x48ed
#define mmBPHYC_UNIPHY2_UNIPHY_REG_TEST_OUTPUT2                                 0x490d
#define mmBPHYC_UNIPHY3_UNIPHY_REG_TEST_OUTPUT2                                 0x492d
#define mmBPHYC_UNIPHY4_UNIPHY_REG_TEST_OUTPUT2                                 0x494d
#define mmBPHYC_UNIPHY5_UNIPHY_REG_TEST_OUTPUT2                                 0x496d
#define mmBPHYC_UNIPHY6_UNIPHY_REG_TEST_OUTPUT2                                 0x498d
#define mmBPHYC_UNIPHY7_UNIPHY_REG_TEST_OUTPUT2                                 0x49cd
#define mmBPHYC_UNIPHY8_UNIPHY_REG_TEST_OUTPUT2                                 0x49ed
#define mmUNIPHY_TMDP_REG0                                                      0x48ce
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG0                                        0x48ce
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG0                                        0x48ee
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG0                                        0x490e
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG0                                        0x492e
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG0                                        0x494e
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG0                                        0x496e
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG0                                        0x498e
#define mmBPHYC_UNIPHY7_UNIPHY_TMDP_REG0                                        0x49ce
#define mmBPHYC_UNIPHY8_UNIPHY_TMDP_REG0                                        0x49ee
#define mmUNIPHY_TMDP_REG1                                                      0x48cf
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG1                                        0x48cf
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG1                                        0x48ef
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG1                                        0x490f
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG1                                        0x492f
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG1                                        0x49