_ARBITRATION_CONTROL                                              0x2f9
#define mmPIPE0_ARBITRATION_CONTROL3                                            0x2fa
#define mmPIPE1_ARBITRATION_CONTROL3                                            0x2fb
#define mmPIPE2_ARBITRATION_CONTROL3                                            0x2fc
#define mmPIPE3_ARBITRATION_CONTROL3                                            0x2fd
#define mmPIPE4_ARBITRATION_CONTROL3                                            0x2fe
#define mmPIPE5_ARBITRATION_CONTROL3                                            0x2ff
#define mmPIPE6_ARBITRATION_CONTROL3                                            0x32a
#define mmPIPE7_ARBITRATION_CONTROL3                                            0x32b
#define mmDMIF_P_VMID                                                           0x300
#define mmDMIF_URG_OVERRIDE                                                     0x329
#define mmDMIF_TEST_DEBUG_INDEX                                                 0x301
#define mmDMIF_TEST_DEBUG_DATA                                                  0x302
#define ixDMIF_DEBUG02_CORE0                                                    0x2
#define ixDMIF_DEBUG02_CORE1                                                    0xa
#define mmDMIF_ADDR_CALC                                                        0x303
#define mmDMIF_STATUS2                                                          0x304
#define mmPIPE0_MAX_REQUESTS                                                    0x305
#define mmPIPE1_MAX_REQUESTS                                                    0x306
#define mmPIPE2_MAX_REQUESTS                                                    0x307
#define mmPIPE3_MAX_REQUESTS                                                    0x308
#define mmPIPE4_MAX_REQUESTS                                                    0x309
#define mmPIPE5_MAX_REQUESTS                                                    0x30a
#define mmPIPE6_MAX_REQUESTS                                                    0x32c
#define mmPIPE7_MAX_REQUESTS                                                    0x32d
#define mmLOW_POWER_TILING_CONTROL                                              0x30b
#define mmMCIF_CONTROL                                                          0x30c
#define mmMCIF_WRITE_COMBINE_CONTROL                                            0x30d
#define mmMCIF_TEST_DEBUG_INDEX                                                 0x30e
#define mmMCIF_TEST_DEBUG_DATA                                                  0x30f
#define ixIDDCCIF02_DBG_DCCIF_C                                                 0x9
#define ixIDDCCIF04_DBG_DCCIF_E                                                 0xb
#define ixIDDCCIF05_DBG_DCCIF_F                                                 0xc
#define mmMCIF_VMID                                                             0x310
#define mmMCIF_MEM_CONTROL                                                      0x311
#define mmCC_DC_PIPE_DIS                                                        0x312
#define mmMC_DC_INTERFACE_NACK_STATUS                                           0x313
#define mmRBBMIF_TIMEOUT                                                        0x314
#define mmRBBMIF_STATUS                                                         0x315
#define mmRBBMIF_TIMEOUT_DIS                                                    0x316
#define mmRBBMIF_STATUS_FLAG                                                    0x327
#define mmDCI_MEM_PWR_STATUS                                                    0x317
#define mmDCI_MEM_PWR_STATUS2                                                   0x318
#define mmDCI_CLK_CNTL                                                          0x319
#define mmDCI_MEM_PWR_CNTL                                                      0x31b
#define mmDCI_MEM_PWR_CNTL2                                                     0x31c
#define mmDCI_MEM_PWR_CNTL3                                                     0x31d
#define mmDCI_SOFT_RESET                                                        0x328
#define mmDCI_TEST_DEBUG_INDEX                                                  0x31e
#define mmDCI_TEST_DEBUG_DATA                                                   0x31f
#define mmDCI_DEBUG_CONFIG                                                      0x320
#define mmPIPE0_DMIF_BUFFER_CONTROL                                             0x321
#define mmPIPE1_DMIF_BUFFER_CONTROL                                             0x322
#define mmPIPE2_DMIF_BUFFER_CONTROL                                             0x323
#define mmPIPE3_DMIF_BUFFER_CONTROL                                             0x324
#define mmPIPE4_DMIF_BUFFER_CONTROL                                             0x325
#define mmPIPE5_DMIF_BUFFER_CONTROL                                             0x326
#define mmDC_GENERICA                                                           0x4800
#define mmDC_GENERICB                                                           0x4801
#define mmDC_PAD_EXTERN_SIG                                                     0x4802
#define mmDC_REF_CLK_CNTL                                                       0x4803
#define mmDC_GPIO_DEBUG                                                         0x4804
#define mmUNIPHYA_LINK_CNTL                                                     0x4805
#define mmUNIPHYA_CHANNEL_XBAR_CNTL                                             0x4806
#define mmUNIPHYB_LINK_CNTL                                                     0x4807
#define mmUNIPHYB_CHANNEL_XBAR_CNTL                                             0x4808
#define mmUNIPHYC_LINK_CNTL                                                     0x4809
#define mmUNIPHYC_CHANNEL_XBAR_CNTL                                             0x480a
#define mmUNIPHYD_LINK_CNTL                                                     0x480b
#define mmUNIPHYD_CHANNEL_XBAR_CNTL                                             0x480c
#define mmUNIPHYE_LINK_CNTL                                                     0x480d
#define mmUNIPHYE_CHANNEL_XBAR_CNTL                                             0x480e
#define mmUNIPHYF_LINK_CNTL                                                     0x480f
#define mmUNIPHYF_CHANNEL_XBAR_CNTL                                             0x4810
#define mmUNIPHYG_LINK_CNTL                                                     0x4811
#define mmUNIPHYG_CHANNEL_XBAR_CNTL                                             0x4812
#define mmUNIPHY_IMPCAL_LINKA                                                   0x4838
#define mmUNIPHY_IMPCAL_LINKB                                                   0x4839
#define mmUNIPHY_IMPCAL_LINKC                                                   0x483f
#define mmUNIPHY_IMPCAL_LINKD                                                   0x4840
#define mmUNIPHY_IMPCAL_LINKE                                                   0x4843
#define mmUNIPHY_IMPCAL_LINKF                                                   0x4844
#define mmUNIPHY_IMPCAL_PERIOD                                                  0x483a
#define mmAUXP_IMPCAL                                                           0x483b
#define mmAUXN_IMPCAL                                                           0x483c
#define mmDCIO_IMPCAL_CNTL                                                      0x483d
#define mmUNIPHY_IMPCAL_PSW_AB                                                  0x483e
#define mmDCIO_IMPCAL_CNTL_CD                                                   0x4841
#define mmUNIPHY_IMPCAL_PSW_CD                                                  0x4842
#define mmDCIO_IMPCAL_CNTL_EF                                                   0x4845
#define mmUNIPHY_IMPCAL_PSW_EF                                                  0x4846
#define mmDCIO_WRCMD_DELAY                                                      0x4816
#define mmDC_PINSTRAPS                                                          0x4818
#define mmDC_DVODATA_CONFIG                                                     0x481a
#define mmLVTMA_PWRSEQ_CNTL                                                     0x481b
#define mmLVTMA_PWRSEQ_STATE                                                    0x481c
#define mmLVTMA_PWRS