                                    0x1638
#define mmDC_ABM1_IPCSC_COEFF_SEL                                               0x1639
#define mmDC_ABM1_ACE_OFFSET_SLOPE_0                                            0x163a
#define mmDC_ABM1_ACE_OFFSET_SLOPE_1                                            0x163b
#define mmDC_ABM1_ACE_OFFSET_SLOPE_2                                            0x163c
#define mmDC_ABM1_ACE_OFFSET_SLOPE_3                                            0x163d
#define mmDC_ABM1_ACE_OFFSET_SLOPE_4                                            0x163e
#define mmDC_ABM1_ACE_THRES_12                                                  0x163f
#define mmDC_ABM1_ACE_THRES_34                                                  0x1640
#define mmDC_ABM1_ACE_CNTL_MISC                                                 0x1641
#define mmDC_ABM1_DEBUG_MISC                                                    0x1649
#define mmDC_ABM1_HGLS_REG_READ_PROGRESS                                        0x164a
#define mmDC_ABM1_HG_MISC_CTRL                                                  0x164b
#define mmDC_ABM1_LS_SUM_OF_LUMA                                                0x164c
#define mmDC_ABM1_LS_MIN_MAX_LUMA                                               0x164d
#define mmDC_ABM1_LS_FILTERED_MIN_MAX_LUMA                                      0x164e
#define mmDC_ABM1_LS_PIXEL_COUNT                                                0x164f
#define mmDC_ABM1_LS_OVR_SCAN_BIN                                               0x1650
#define mmDC_ABM1_LS_MIN_MAX_PIXEL_VALUE_THRES                                  0x1651
#define mmDC_ABM1_LS_MIN_PIXEL_VALUE_COUNT                                      0x1652
#define mmDC_ABM1_LS_MAX_PIXEL_VALUE_COUNT                                      0x1653
#define mmDC_ABM1_HG_SAMPLE_RATE                                                0x1654
#define mmDC_ABM1_LS_SAMPLE_RATE                                                0x1655
#define mmDC_ABM1_HG_BIN_1_32_SHIFT_FLAG                                        0x1656
#define mmDC_ABM1_HG_BIN_1_8_SHIFT_INDEX                                        0x1657
#define mmDC_ABM1_HG_BIN_9_16_SHIFT_INDEX                                       0x1658
#define mmDC_ABM1_HG_BIN_17_24_SHIFT_INDEX                                      0x1659
#define mmDC_ABM1_HG_BIN_25_32_SHIFT_INDEX                                      0x165a
#define mmDC_ABM1_HG_RESULT_1                                                   0x165b
#define mmDC_ABM1_HG_RESULT_2                                                   0x165c
#define mmDC_ABM1_HG_RESULT_3                                                   0x165d
#define mmDC_ABM1_HG_RESULT_4                                                   0x165e
#define mmDC_ABM1_HG_RESULT_5                                                   0x165f
#define mmDC_ABM1_HG_RESULT_6                                                   0x1660
#define mmDC_ABM1_HG_RESULT_7                                                   0x1661
#define mmDC_ABM1_HG_RESULT_8                                                   0x1662
#define mmDC_ABM1_HG_RESULT_9                                                   0x1663
#define mmDC_ABM1_HG_RESULT_10                                                  0x1664
#define mmDC_ABM1_HG_RESULT_11                                                  0x1665
#define mmDC_ABM1_HG_RESULT_12                                                  0x1666
#define mmDC_ABM1_HG_RESULT_13                                                  0x1667
#define mmDC_ABM1_HG_RESULT_14                                                  0x1668
#define mmDC_ABM1_HG_RESULT_15                                                  0x1669
#define mmDC_ABM1_HG_RESULT_16                                                  0x166a
#define mmDC_ABM1_HG_RESULT_17                                                  0x166b
#define mmDC_ABM1_HG_RESULT_18                                                  0x166c
#define mmDC_ABM1_HG_RESULT_19                                                  0x166d
#define mmDC_ABM1_HG_RESULT_20                                                  0x166e
#define mmDC_ABM1_HG_RESULT_21                                                  0x166f
#define mmDC_ABM1_HG_RESULT_22                                                  0x1670
#define mmDC_ABM1_HG_RESULT_23                                                  0x1671
#define mmDC_ABM1_HG_RESULT_24                                                  0x1672
#define mmDC_ABM1_OVERSCAN_PIXEL_VALUE                                          0x169b
#define mmDC_ABM1_BL_MASTER_LOCK                                                0x169c
#define mmABM_TEST_DEBUG_INDEX                                                  0x169e
#define mmABM_TEST_DEBUG_DATA                                                   0x169f
#define mmCRTC_DCFE_CLOCK_CONTROL                                               0x1b7c
#define mmCRTC0_CRTC_DCFE_CLOCK_CONTROL                                         0x1b7c
#define mmCRTC1_CRTC_DCFE_CLOCK_CONTROL                                         0x1d7c
#define mmCRTC2_CRTC_DCFE_CLOCK_CONTROL                                         0x1f7c
#define mmCRTC3_CRTC_DCFE_CLOCK_CONTROL                                         0x417c
#define mmCRTC4_CRTC_DCFE_CLOCK_CONTROL                                         0x437c
#define mmCRTC5_CRTC_DCFE_CLOCK_CONTROL                                         0x457c
#define mmCRTC6_CRTC_DCFE_CLOCK_CONTROL                                         0x477c
#define mmCRTC_H_BLANK_EARLY_NUM                                                0x1b7d
#define mmCRTC0_CRTC_H_BLANK_EARLY_NUM                                          0x1b7d
#define mmCRTC1_CRTC_H_BLANK_EARLY_NUM                                          0x1d7d
#define mmCRTC2_CRTC_H_BLANK_EARLY_NUM                                          0x1f7d
#define mmCRTC3_CRTC_H_BLANK_EARLY_NUM                                          0x417d
#define mmCRTC4_CRTC_H_BLANK_EARLY_NUM                                          0x437d
#define mmCRTC5_CRTC_H_BLANK_EARLY_NUM                                          0x457d
#define mmCRTC6_CRTC_H_BLANK_EARLY_NUM                                          0x477d
#define mmDCFE_DBG_SEL                                                          0x1b7e
#define mmCRTC0_DCFE_DBG_SEL                                                    0x1b7e
#define mmCRTC1_DCFE_DBG_SEL                                                    0x1d7e
#define mmCRTC2_DCFE_DBG_SEL                                                    0x1f7e
#define mmCRTC3_DCFE_DBG_SEL                                                    0x417e
#define mmCRTC4_DCFE_DBG_SEL                                                    0x437e
#define mmCRTC5_DCFE_DBG_SEL                                                    0x457e
#define mmCRTC6_DCFE_DBG_SEL                                                    0x477e
#define mmDCFE_MEM_PWR_CTRL                                                     0x1b7f
#define mmCRTC0_DCFE_MEM_PWR_CTRL                                               0x1b7f
#define mmCRTC1_DCFE_MEM_PWR_CTRL                                               0x1d7f
#define mmCRTC2_DCFE_MEM_PWR_CTRL                                               0x1f7f
#define mmCRTC3_DCFE_MEM_PWR_CTRL                                               0x417f
#define mmCRTC4_DCFE_MEM_PWR_CTRL                                               0x437f
#define mmCRTC5_DCFE_MEM_PWR_CTRL                                               0x457f
#define mmCRTC6_DCFE_MEM_PWR_CTRL                                               0x477f
#define mmDCFE_MEM_PWR_CTRL2                                                    0x1bb8
#define mmCRTC0_DCFE_MEM_PWR_CTRL2                                              0x1bb8
#define mmCRTC1_DCFE_MEM_PWR_CTRL2                                              0x1db8
#define mmCRTC2_DCFE_MEM_PWR_CTRL2                                              0x1fb8
#define mmCRTC3_DCFE_MEM_PWR_CTRL2                                              0x41b8
#define mmCRTC4_DCFE_MEM_PWR_CTRL2                                              0x43b8
#define mmCRTC5_DCFE_MEM_PWR_CTRL2                                              0x45b8
#define mmCRTC6_DCFE_MEM_PWR_CTRL2                                              0x47b8
#define mmDCFE_MEM_PWR_STATUS                                                   0x1bb9
#define mmCRTC0_DCFE_MEM_PWR_STATUS                                             0x1bb9
#define mmCRTC1_DCFE_MEM_PWR_STATUS                                             0x1db9
#define mmCRTC2_DCFE_MEM_PWR_STATUS                                             0x1fb9
#define mmCRTC3_DCFE_MEM_PWR_STATUS                                             0x41b9
#define mmCRTC4_DCFE_MEM_PWR_STATUS                                             0x43b9
#define mmCRTC5_DCFE_MEM_PWR_STATUS                                             0x45b9
#define mmCRTC6_DCFE_MEM_PWR_STATUS                                             0x47b9
#define mmCRTC_H_TOTAL                                                          0x1b80
#define mmCRTC0_CRTC_H_TOTAL                                                    0x1b80
#define mmCRTC1_CRTC_H_TOTAL                                                    0x1d80
#define mmCRTC2_CRTC_H_TOTAL                                                    0x1f80
#define mmCRTC3_CRTC_H_TOTAL                                                    0x4180
#define mmCRTC4_CRTC_H_TOTAL                                                    0x4380
#define mmCRTC5_CRTC_H_TOTAL                                                    0x4580
#define mmCRTC6_CRTC_H_TOTAL                                                    0x4780
#define mmCRTC_H_BLANK_START_END                                                0x1b81
#define mmCRTC0_CRTC_H_BLANK_START_END                                          0x1b81
#define mmCRTC1_CRTC_H_BLANK_START_END                                          0x1d81
#define mmCRTC2_CRTC_H_BLANK_START_END                                          0x1f81
#define mmCRTC3_CRTC_H_BLANK_START_END                                          0x4181
#define mmCRTC4_CRTC_H_BLANK_START_END                                          0x4381
#define mmCRTC5_CRTC_H_BLANK_START_END                                          0x4581
#define mmCRTC6_CRTC_H_BLANK_START_END                                          0x4781
#define mmCRTC_H_SYNC_A                                                         0x1b82
#define mmCRTC0_CRTC_H_SYNC_A                                                   0x1b82
#define mmCRTC1_CRTC_H_SYNC_A                                                   0x1d82
#define mmCRTC2_CRTC_H_SYNC_A                                                   0x1f82
#define mmCRTC3_CRTC_H_SYNC_A                                                   0x4182
#define mmCRTC4_CRTC_H_SYNC_A                                                   0x4382
#define mmCRTC5_CRTC_H_SYNC_A                                                   0x4582
#define mmCRTC6_CRTC_H_SYNC_A                                                   0x4782
#define mmCRTC_H_SYNC_A_CNTL                                                    0x1b83
#define mmCRTC0_CRTC_H_SYNC_A_CNTL                                              0x1b83
#define mmCRTC1_CRTC_H_SYNC_A_CNTL                                              0x1d83
#define mmCRTC2_CRTC_H_SYNC_A_CNTL                                              0x1f83
#define mmCRTC3_CRTC_H_SYNC_A_CNTL                                              0x4183
#define mmCRTC4_CRTC_H_SYNC_A_CNTL                                              0x4383
#define mmCRTC5_CRTC_H_SYNC_A_CNTL                                              0x4583
#define mmCRTC6_CRTC_H_SYNC_A_CNTL                                              0x4783
#define mmCRTC_H_SYNC_B                                                         0x1b84
#define mmCRTC0_CRTC_H_SYNC_B                                                   0x1b84
#define mmCRTC1_CRTC_H_SYNC_B                                                   0x1d84
#define mmCRTC2_CRTC_H_SYNC_B                                                   0x1f84
#define mmCRTC3_CRTC_H_SYNC_B                                                   0x4184
#define mmCRTC4_CRTC_H_SYNC_B                                                   0x4384
#define mmCRTC5_CRTC_H_SYNC_B                                                   0x4584
#define mmCRTC6_CRTC_H_SYNC_B                                                   0x4784
#define mmCRTC_H_SYNC_B_CNTL                                                    0x1b85
#define mmCRTC0_CRTC_H_SYNC_B_CNTL                                              0x1b85
#define mmCRTC1_CRTC_H_SYNC_B_CNTL                                              0x1d85
#define mmCRTC2_CRTC_H_SYNC_B_CNTL                                              0x1f85
#define mmCRTC3_CRTC_H_SYNC_B_CNTL                                              0x4185