173f
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED21                                   0x1769
#define mmPLL_MACRO_CNTL_RESERVED22                                             0x1716
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED22                                   0x1716
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED22                                   0x1740
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED22                                   0x176a
#define mmPLL_MACRO_CNTL_RESERVED23                                             0x1717
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED23                                   0x1717
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED23                                   0x1741
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED23                                   0x176b
#define mmPLL_MACRO_CNTL_RESERVED24                                             0x1718
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED24                                   0x1718
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED24                                   0x1742
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED24                                   0x176c
#define mmPLL_MACRO_CNTL_RESERVED25                                             0x1719
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED25                                   0x1719
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED25                                   0x1743
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED25                                   0x176d
#define mmPLL_MACRO_CNTL_RESERVED26                                             0x171a
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED26                                   0x171a
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED26                                   0x1744
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED26                                   0x176e
#define mmPLL_MACRO_CNTL_RESERVED27                                             0x171b
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED27                                   0x171b
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED27                                   0x1745
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED27                                   0x176f
#define mmPLL_MACRO_CNTL_RESERVED28                                             0x171c
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED28                                   0x171c
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED28                                   0x1746
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED28                                   0x1770
#define mmPLL_MACRO_CNTL_RESERVED29                                             0x171d
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED29                                   0x171d
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED29                                   0x1747
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED29                                   0x1771
#define mmPLL_MACRO_CNTL_RESERVED30                                             0x171e
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED30                                   0x171e
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED30                                   0x1748
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED30                                   0x1772
#define mmPLL_MACRO_CNTL_RESERVED31                                             0x171f
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED31                                   0x171f
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED31                                   0x1749
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED31                                   0x1773
#define mmPLL_MACRO_CNTL_RESERVED32                                             0x1720
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED32                                   0x1720
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED32                                   0x174a
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED32                                   0x1774
#define mmPLL_MACRO_CNTL_RESERVED33                                             0x1721
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED33                                   0x1721
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED33                                   0x174b
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED33                                   0x1775
#define mmPLL_MACRO_CNTL_RESERVED34                                             0x1722
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED34                                   0x1722
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED34                                   0x174c
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED34                                   0x1776
#define mmPLL_MACRO_CNTL_RESERVED35                                             0x1723
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED35                                   0x1723
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED35                                   0x174d
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED35                                   0x1777
#define mmPLL_MACRO_CNTL_RESERVED36                                             0x1724
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED36                                   0x1724
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED36                                   0x174e
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED36                                   0x1778
#define mmPLL_MACRO_CNTL_RESERVED37                                             0x1725
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED37                                   0x1725
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED37                                   0x174f
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED37                                   0x1779
#define mmPLL_MACRO_CNTL_RESERVED38                                             0x1726
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED38                                   0x1726
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED38                                   0x1750
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED38                                   0x177a
#define mmPLL_MACRO_CNTL_RESERVED39                                             0x1727
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED39                                   0x1727
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED39                                   0x1751
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED39                                   0x177b
#define mmPLL_MACRO_CNTL_RESERVED40                                             0x1728
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED40                                   0x1728
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED40                                 