                                    0x5e2b
#define mmCNV_TEST_CNTL                                                         0x5e2c
#define mmCNV_TEST_CRC_RED                                                      0x5e2d
#define mmCNV_TEST_CRC_GREEN                                                    0x5e2e
#define mmCNV_TEST_CRC_BLUE                                                     0x5e2f
#define mmWB_DEBUG_CTRL                                                         0x5e30
#define mmWB_DBG_MODE                                                           0x5e31
#define mmWB_HW_DEBUG                                                           0x5e32
#define mmCNV_INPUT_SELECT                                                      0x5e33
#define mmWB_SOFT_RESET                                                         0x5e36
#define mmCNV_TEST_DEBUG_INDEX                                                  0x5e34
#define mmCNV_TEST_DEBUG_DATA                                                   0x5e35
#define mmDCFE_CLOCK_CONTROL                                                    0x1b00
#define mmDCFE0_DCFE_CLOCK_CONTROL                                              0x1b00
#define mmDCFE1_DCFE_CLOCK_CONTROL                                              0x1d00
#define mmDCFE2_DCFE_CLOCK_CONTROL                                              0x1f00
#define mmDCFE3_DCFE_CLOCK_CONTROL                                              0x4100
#define mmDCFE4_DCFE_CLOCK_CONTROL                                              0x4300
#define mmDCFE5_DCFE_CLOCK_CONTROL                                              0x4500
#define mmDCFE_SOFT_RESET                                                       0x1b01
#define mmDCFE0_DCFE_SOFT_RESET                                                 0x1b01
#define mmDCFE1_DCFE_SOFT_RESET                                                 0x1d01
#define mmDCFE2_DCFE_SOFT_RESET                                                 0x1f01
#define mmDCFE3_DCFE_SOFT_RESET                                                 0x4101
#define mmDCFE4_DCFE_SOFT_RESET                                                 0x4301
#define mmDCFE5_DCFE_SOFT_RESET                                                 0x4501
#define mmDCFE_DBG_CONFIG                                                       0x1b02
#define mmDCFE0_DCFE_DBG_CONFIG                                                 0x1b02
#define mmDCFE1_DCFE_DBG_CONFIG                                                 0x1d02
#define mmDCFE2_DCFE_DBG_CONFIG                                                 0x1f02
#define mmDCFE3_DCFE_DBG_CONFIG                                                 0x4102
#define mmDCFE4_DCFE_DBG_CONFIG                                                 0x4302
#define mmDCFE5_DCFE_DBG_CONFIG                                                 0x4502
#define mmDCFEV_CLOCK_CONTROL                                                   0x46f4
#define mmDCFEV_SOFT_RESET                                                      0x46f5
#define mmDCFEV_DMIFV_CLOCK_CONTROL                                             0x46f6
#define mmDCFEV_DBG_CONFIG                                                      0x46f7
#define mmDCFEV_DMIFV_MEM_PWR_CTRL                                              0x46f8
#define mmDCFEV_DMIFV_MEM_PWR_STATUS                                            0x46f9
#define mmDC_HPD_INT_STATUS                                                     0x1898
#define mmHPD0_DC_HPD_INT_STATUS                                                0x1898
#define mmHPD1_DC_HPD_INT_STATUS                                                0x18a0
#define mmHPD2_DC_HPD_INT_STATUS                                                0x18a8
#define mmHPD3_DC_HPD_INT_STATUS                                                0x18b0
#define mmHPD4_DC_HPD_INT_STATUS                                                0x18b8
#define mmHPD5_DC_HPD_INT_STATUS                                                0x18c0
#define mmDC_HPD_INT_CONTROL                                                    0x1899
#define mmHPD0_DC_HPD_INT_CONTROL                                               0x1899
#define mmHPD1_DC_HPD_INT_CONTROL                                               0x18a1
#define mmHPD2_DC_HPD_INT_CONTROL                                               0x18a9
#define mmHPD3_DC_HPD_INT_CONTROL                                               0x18b1
#define mmHPD4_DC_HPD_INT_CONTROL                                               0x18b9
#define mmHPD5_DC_HPD_INT_CONTROL                                               0x18c1
#define mmDC_HPD_CONTROL                                                        0x189a
#define mmHPD0_DC_HPD_CONTROL                                                   0x189a
#define mmHPD1_DC_HPD_CONTROL                                                   0x18a2
#define mmHPD2_DC_HPD_CONTROL                                                   0x18aa
#define mmHPD3_DC_HPD_CONTROL                                                   0x18b2
#define mmHPD4_DC_HPD_CONTROL                                                   0x18ba
#define mmHPD5_DC_HPD_CONTROL                                                   0x18c2
#define mmDC_HPD_FAST_TRAIN_CNTL                                                0x189b
#define mmHPD0_DC_HPD_FAST_TRAIN_CNTL                                           0x189b
#define mmHPD1_DC_HPD_FAST_TRAIN_CNTL                                           0x18a3
#define mmHPD2_DC_HPD_FAST_TRAIN_CNTL                                           0x18ab
#define mmHPD3_DC_HPD_FAST_TRAIN_CNTL                                           0x18b3