       0x5
#define ixCRT06                                                                 0x6
#define ixCRT07                                                                 0x7
#define ixCRT08                                                                 0x8
#define ixCRT09                                                                 0x9
#define ixCRT0A                                                                 0xa
#define ixCRT0B                                                                 0xb
#define ixCRT0C                                                                 0xc
#define ixCRT0D                                                                 0xd
#define ixCRT0E                                                                 0xe
#define ixCRT0F                                                                 0xf
#define ixCRT10                                                                 0x10
#define ixCRT11                                                                 0x11
#define ixCRT12                                                                 0x12
#define ixCRT13                                                                 0x13
#define ixCRT14                                                                 0x14
#define ixCRT15                                                                 0x15
#define ixCRT16                                                                 0x16
#define ixCRT17                                                                 0x17
#define ixCRT18                                                                 0x18
#define ixCRT1E                                                                 0x1e
#define ixCRT1F                                                                 0x1f
#define ixCRT22                                                                 0x22
#define mmGRPH8_IDX                                                             0xf3
#define mmGRPH8_DATA                                                            0xf3
#define ixGRA00                                                                 0x0
#define ixGRA01                                                                 0x1
#define ixGRA02                                                                 0x2
#define ixGRA03                                                                 0x3
#define ixGRA04                                                                 0x4
#define ixGRA05                                                                 0x5
#define ixGRA06                                                                 0x6
#define ixGRA07                                                                 0x7
#define ixGRA08                                                                 0x8
#define mmATTRX                                                                 0xf0
#define mmATTRDW                                                                0xf0
#define mmATTRDR                                                                0xf0
#define ixATTR00                                                                0x0
#define ixATTR01                                                                0x1
#define ixATTR02                                                                0x2
#define ixATTR03                                                                0x3
#define ixATTR04                                                                0x4
#define ixATTR05                                                                0x5
#define ixATTR06                                                                0x6
#define ixATTR07                                                                0x7
#define ixATTR08                                                                0x8
#define ixATTR09                                                                0x9
#define ixATTR0A                                                                0xa
#define ixATTR0B                                                                0xb
#define ixATTR0C                                                                0xc
#define ixATTR0D                                                                0xd
#define ixATTR0E                                                                0xe
#define ixATTR0F                                                                0xf
#define ixATTR10                                                                0x10
#define ixATTR11                                                                0x11
#define ixATTR12                                                                0x12
#define ixATTR13                                                                0x13
#define ixATTR14                                                                0x14
#define mmVGA_RENDER_CONTROL                                                    0xc0
#define mmVGA_SOURCE_SELECT                                                     0xfc
#define mmVGA_SEQUENCER_RESET_CONTROL                                           0xc1
#define mmVGA_MODE_CONTROL                                                      0xc2
#define mmVGA_SURFACE_PITCH_SELECT                                              0xc3
#define mmVGA_MEMORY_BASE_ADDRESS                                               0xc4
#define mmVGA_MEMORY_BASE_ADDRESS_HIGH                                          0xc9
#define mmVGA_DISPBUF1_SURFACE_ADDR                                             0xc6
#define mmVGA_DISPBUF2_SURFACE_ADDR                                             0xc8
#define mmVGA_HDP_CONTROL                                                       0xca
#define mmVGA_CACHE_CONTROL                                                     0xcb
#define mmD1VGA_CONTROL                                                         0xcc
#define mmD2VGA_CONTROL                                                         0xce
#define mmD3VGA_CONTROL                                                         0xf8
#define mmD4VGA_CONTROL                                                         0xf9
#define mmD5VGA_CONTROL                                                         0xfa
#define mmD6VGA_CONTROL                                                         0xfb
#define mmVGA_HW_DEBUG                                                          0xcf
#define mmVGA_STATUS                                                            0xd0
#define mmVGA_INTERRUPT_CONTROL                                                 0xd1
#define mmVGA_STATUS_CLEAR                                                      0xd2
#define mmVGA_INTERRUPT_STATUS                                                  0xd3
#define mmVGA_MAIN_CONTROL                                                      0xd4
#define mmVGA_TEST_CONTROL                                                      0xd5
#define mmVGA_DEBUG_READBACK_INDEX                                              0xd6
#define mmVGA_DEBUG_READBACK_DATA                                               0xd7
#define mmVGA_MEM_WRITE_PAGE_ADDR                                               0x12
#define mmVGA_MEM_READ_PAGE_ADDR                                                0x13
#define mmVGA_TEST_DEBUG_INDEX                                                  0xc5
#define mmVGA_TEST_DEBUG_DATA                                                   0xc7
#define ixVGADCC_DBG_DCCIF_C                                                    0x7e
#define mmBPHYC_DAC_MACRO_CNTL                                                  0x48b9
#define mmBPHYC_DAC_AUTO_CALIB_CONTROL                                          0x48ba
#define mmPLL_REF_DIV                                                           0x1700
#define mmBPHYC_PLL0_PLL_REF_DIV                                                0x1700
#define mmBPHYC_PLL1_PLL_REF_DIV                                                0x172a
#define mmBPHYC_PLL2_PLL_REF_DIV                                                0x1754
#define mmPLL_FB_DIV                                                            0x1701
#define mmBPHYC_PLL0_PLL_FB_DIV                                                 0x1701
#define mmBPHYC_PLL1_PLL_FB_DIV                                                 0x172b
#define mmBPHYC_PLL2_PLL_FB_DIV                                                 0x1755
#define mmPLL_POST_DIV                                                          0x1702
#define mmBPHYC_PLL0_PLL_POST_DIV                                               0x1702
#define mmBPHYC_PLL1_PLL_POST_DIV                                               0x172c
#define mmBPHYC_PLL2_PLL_POST_DIV                                               0x1756
#define mmPLL_SS_AMOUNT_DSFRAC                                                  0x1703
#define mmBPHYC_PLL0_PLL_SS_AMOUNT_DSFRAC                                       0x1703
#define mmBPHYC_PLL1_PLL_SS_AMOUNT_DSFRAC                                       0x172d
#define mmBPHYC_PLL2_PLL_SS_AMOUNT_DSFRAC                                       0x1757
#define mmPLL_SS_CNTL                                                           0x1704
#define mmBPHYC_PLL0_PLL_SS_CNTL                                                0x1704
#define mmBPHYC_PLL1_PLL_SS_CNTL                                                0x172e
#define mmBPHYC_PLL2_PLL_SS_CNTL                                                0x1758
#define mmPLL_DS_CNTL                                                           0x1705
#define mmBPHYC_PLL0_PLL_DS_CNTL                                                0x1705
#define mmBPHYC_PLL1_PLL_DS_CNTL                                                0x172f
#define mmBPHYC_PLL2_PLL_DS_CNTL                                                0x1759
#define mmPLL_IDCLK_CNTL                                                        0x1706
#define mmBPHYC_PLL0_PLL_IDCLK_CNTL                                             0x1706
#define mmBPHYC_PLL1_PLL_IDCLK_CNTL                                             0x1730
#define mmBPHYC_PLL2_PLL_IDCLK_CNTL                                             0x175a
#define mmPLL_CNTL                                                              0x1707
#define mmBPHYC_PLL0_PLL_CNTL                                                   0x1707
#define mmBPHYC_PLL1_PLL_CNTL                                                   0x1731
#define mmBPHYC_PLL2_PLL_CNTL                                                   0x175b
#define mmPLL_ANALOG                                                            0x1708
#define mmBPHYC_PLL0_PLL_ANALOG                                                 0x1708
#define mmBPHYC_PLL1_PLL_ANALOG                                                 0x1732
#define mmBPHYC_PLL2_PLL_ANALOG                                                 0x175c
#define mmPLL_VREG_CNTL                                                         0x1709
#define mmBPHYC_PLL0_PLL_VREG_CNTL                                              0x1709
#define mmBPHYC_PLL1_PLL_VREG_CNTL                                              0x1733
#define mmBPHYC_PLL2_PLL_VREG_CNTL                                              0x175d
#define mmPLL_UNLOCK_DETECT_CNTL                                                0x170a
#define mmBPHYC_PLL0_PLL_UNLOCK_DETECT_CNTL                                     0x170a
#define mmBPHYC_PLL1_PLL_UNLOCK_DETECT_CNTL                                     0x1734
#define mmBPHYC_PLL2_PLL_UNLOCK_DETECT_CNTL                                     0x175e
#define mmPLL_DEBUG_CNTL                                                        0x170b
#define mmBPHYC_PLL0_PLL_DEBUG_CNTL                                             0x170b
#define mmBPHYC_PLL1_PLL_DEBUG_CNTL                                             0x1735
#define mmBPHYC_PLL2_PLL_DEBUG_CNTL                                             0x175f
#define mmPLL_UPDATE_LOCK                                                       0x170c
#define mmBPHYC_PLL0_PLL_UPDATE_LOCK                                            0x170c
#define mmBPHYC_PLL1_PLL_UPDATE_LOCK                                            0x1736
#define mmBPHYC_PLL2_PLL_UPDATE_LOCK                                            0x1760
#define mmPLL_UPDATE_CNTL                                                       0x170d
#define mmBPHYC_PLL0_PLL_UPDATE_CNTL                                            0x170d
#define mmBPHYC_PLL1_PLL_UPDATE_CNTL                                            0x1737
#define mmBPHYC_PLL2_PLL_UPDATE_CNTL                                            0x1761
#define mmPLL_XOR_LOCK                                                          0x1710
#define mmBPHYC_PLL0_PLL_XOR_LOCK                                               0x1710
#define mmBPHYC_PLL1_PLL_XOR_LOCK                                               0x173a
#define mmBPHYC_PLL2_PLL_XOR_LOCK                                               0x1764
#define mmPLL_ANALOG_CNTL                                                       0x1711
#define mmBPHYC_PLL0_PLL_ANALOG_CNTL                                            0x1711
#define mmBPHYC_PLL1_PLL_ANALOG_CNTL                                            0x173b
#define mmBPHYC_PLL2_PLL_ANALOG_CNTL                                            0x1765
#define mmVGA25_PPLL_REF_DIV                                                    0x1712
#define mmBPHYC_PLL0_VGA25_PPLL_REF_DIV                                         0x1712
#define mmBPHYC_PLL1_VGA25_PPLL_REF_DIV                                         0x173c
#define mmBPHYC_PLL2_VGA25_PPLL_REF_DIV                                         0x1766
#define mmVGA28_PPLL_REF_DIV                                                    0x1713
#define mmBPHYC_PLL0_VGA28_PPLL_REF_DIV                                         0x1713
#define mmBPHYC_PLL1_VGA28_PPLL_REF_DIV                                         0x173d
#define mmBPHYC_PLL2_VGA28_PPLL_REF_DIV                                         0x1767
#define mmVGA41_PPLL_REF_DIV                                                    0x1714
#define mmBPHYC_PLL0_VGA41_PPLL_REF_DIV                                         0x1714
#define mmBPHYC_PLL1_VGA41_PPLL_REF_DIV                                         0x173e
#define mmBPHYC_PLL2_VGA41_PPLL_REF_DIV                                         0x1768
#define mmVGA25_PPLL_FB_DIV                                                     0x1715
#define mmBPHYC_PLL0_VGA25_PPLL_FB_DIV                                          0x1715
#define mmBPHYC_PLL1_VGA25_PPLL_FB_DIV                                          0x173f
#define mmBPHYC_PLL2_VGA25_PPLL_FB_DIV                                          0x1769
#define mmVGA28_PPLL_FB_DIV                                                     0x1716
#define mmBPHYC_PLL0_VGA28_PPLL_FB_DIV                                          0x1716
#define mmBPHYC_PLL1_VGA28_PPLL_FB_DIV                                          0x1740
#define mmBPHYC_PLL2_VGA28_PPLL_FB_DIV                                          0x176a
#define mmVGA41_PPLL_FB_DIV                                                     0x1717
#define mmBPHYC_PLL0_VGA41_PPLL_FB_DIV                                          0x1717
#define mmBPHYC_PLL1_VGA41_PPLL_FB_DIV                                          0x1741
#define mmBPHYC_PLL2_VGA41_PPLL_FB_DIV                                          0x176b
#define mmVGA25_PPLL_POST_DIV                                                   0x1718
#define mmBPHYC_PLL0_VGA25_PPLL_POST_DIV                                        0x1718
#define mmBPHYC_PLL1_VGA25_PPLL_POST_DIV                                        0x1742
#define mmBPHYC_PLL2_VGA25_PPLL_POST_DIV                                        0x176c
#define mmVGA28_PPLL_POST_DIV                                                   0x1719
#define mmBPHYC_PLL0_VGA28_PPLL_POST_DIV                                        0x1719
#define mmBPHYC_PLL1_VGA28_PPLL_POST_DIV                                        0x1743
#define mmBPHYC_PLL2_VGA28_PPLL_POST_DIV                                        0x176d
#define mmVGA41_PPLL_POST_DIV                                                   0x171a
#define mmBPHYC_PLL0_VGA41_PPLL_POST_DIV                                        0x171a
#define mmBPHYC_PLL1_VGA41_PPLL_POST_DIV                                        0x1744
#define mmBPHYC_PLL2_VGA41_PPLL_POST_DIV                                        0x176e
#define mmVGA25_PPLL_ANALOG                                                     0x171b
#define mmBPHYC_PLL0_VGA25_PPLL_ANALOG                                          0x171b
#define mmBPHYC_PLL1_VGA25_PPLL_ANALOG                                          0x1745
#define mmBPHYC_PLL2_VGA25_PPLL_ANALOG                                          0x176f
#define mmVGA28_PPLL_ANALOG                                                     0x171c
#define mmBPHYC_PLL0_VGA28_PPLL_ANALOG                                          0x171c
#define mmBPHYC_PLL1_VGA28_PPLL_ANALOG                                          0x1746
#define mmBPHYC_PLL2_VGA28_PPLL_ANALOG                                          0x1770
#define mmVGA41_PPLL_ANALOG                                                     0x171d
#define mmBPHYC_PLL0_VGA41_PPLL_ANALOG                                          0x171d
#define mmBPHYC_PLL1_VGA41_PPLL_ANALOG                                          0x1747
#define mmBPHYC_PLL2_VGA41_PPLL_ANALOG                                          0x1771
#define mmDISPPLL_BG_CNTL                                                       0x171e
#define mmBPHYC_PLL0_DISPPLL_BG_CNTL                                            0x171e
#define mmBPHYC_PLL1_DISPPLL_BG_CNTL                                            0x1748
#define mmBPHYC_PLL2_DISPPLL_BG_CNTL                                            0x1772
#define mmPPLL_DIV_UPDATE_DEBUG                                                 0x171f
#define mmBPHYC_PLL0_PPLL_DIV_UPDATE_DEBUG                                      0x171f
#define mmBPHYC_PLL1_PPLL_DIV_UPDATE_DEBUG                                      0x1749
#define mmBPHYC_PLL2_PPLL_DIV_UPDATE_DEBUG                                      0x1773
#define mmPPLL_STATUS_DEBUG                                                     0x1720
#define mmBPHYC_PLL0_PPLL_STATUS_DEBUG                                          0x1720
#define mmBPHYC_PLL1_PPLL_STATUS_DEBUG                                          0x174a
#define mmBPHYC_PLL2_PPLL_STATUS_DEBUG                                          0x1774
#define mmPPLL_DEBUG_MUX_CNTL                                                   0x1721
#define mmBPHYC_PLL0_PPLL_DEBUG_MUX_CNTL                                        0x1721
#define mmBPHYC_PLL1_PPLL_DEBUG_MUX_CNTL                                        0x174b
#define mmBPHYC_PLL2_PPLL_DEBUG_MUX_CNTL                                        0x1775
#define mmPPLL_SPARE0                                                           0x1722
#define mmBPHYC_PLL0_PPLL_SPARE0                                                0x1722
#define mmBPHYC_PLL1_PPLL_SPARE0                                                0x174c
#define mmBPHYC_PLL2_PPLL_SPARE0                                                0x1776
#define mmPPLL_SPARE1                                                           0x1723
#define mmBPHYC_PLL0_PPLL_SPARE1                                                0x1723
#define mmBPHYC_PLL1_PPLL_SPARE1                                                0x174d
#define mmBPHYC_PLL2_PPLL_SPARE1                                                0x1777
#define mmUNIPHY_TX_CONTROL1                                                    0x48c0
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL1                                      0x48c0
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL1                                      0x48e0
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL1                                      0x4900
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL1                                      0x4920
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL1                                      0x4940
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL1                                      0x4960
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL1                                      0x4980
#define mmUNIPHY_TX_CONTROL2                                                    0x48c1
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL2                                      0x48c1
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL2                                      0x48e1
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL2                                      0x4901
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL2                                      0x4921
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL2                                      0x4941
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL2                                      0x4961
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL2                                      0x4981
#define mmUNIPHY_TX_CONTROL3                                                    0x48c2
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL3                                      0x48c2
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL3                                      0x48e2
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL3                                      0x4902
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL3                                      0x4922
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL3                                      0x4942
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL3                                      0x4962
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL3                                      0x4982
#define mmUNIPHY_TX_CONTROL4                                                    0x48c3
#define mmBPHYC_UNIPHY0_UNIPHY_TX_CONTROL4                                      0x48c3
#define mmBPHYC_UNIPHY1_UNIPHY_TX_CONTROL4                                      0x48e3
#define mmBPHYC_UNIPHY2_UNIPHY_TX_CONTROL4                                      0x4903
#define mmBPHYC_UNIPHY3_UNIPHY_TX_CONTROL4                                      0x4923
#define mmBPHYC_UNIPHY4_UNIPHY_TX_CONTROL4                                      0x4943
#define mmBPHYC_UNIPHY5_UNIPHY_TX_CONTROL4                                      0x4963
#define mmBPHYC_UNIPHY6_UNIPHY_TX_CONTROL4                                      0x4983
#define mmUNIPHY_POWER_CONTROL                                                  0x48c4
#define mmBPHYC_UNIPHY0_UNIPHY_POWER_CONTROL                                    0x48c4
#define mmBPHYC_UNIPHY1_UNIPHY_POWER_CONTROL                                    0x48e4
#define mmBPHYC_UNIPHY2_UNIPHY_POWER_CONTROL                                    0x4904
#define mmBPHYC_UNIPHY3_UNIPHY_POWER_CONTROL                                    0x4924
#define mmBPHYC_UNIPHY4_UNIPHY_POWER_CONTROL                                    0x4944
#define mmBPHYC_UNIPHY5_UNIPHY_POWER_CONTROL                                    0x4964
#define mmBPHYC_UNIPHY6_UNIPHY_POWER_CONTROL                                    0x4984
#define mmUNIPHY_PLL_FBDIV                                                      0x48c5
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_FBDIV                                        0x48c5
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_FBDIV                                        0x48e5
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_FBDIV                                        0x4905
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_FBDIV                                        0x4925
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_FBDIV                                        0x4945
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_FBDIV                                        0x4965
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_FBDIV                                        0x4985
#define mmUNIPHY_PLL_CONTROL1                                                   0x48c6
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_CONTROL1                                     0x48c6
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_CONTROL1                                     0x48e6
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_CONTROL1                                     0x4906
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_CONTROL1                                     0x4926
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_CONTROL1                                     0x4946
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_CONTROL1                                     0x4966
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_CONTROL1                                     0x4986
#define mmUNIPHY_PLL_CONTROL2                                                   0x48c7
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_CONTROL2                                     0x48c7
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_CONTROL2                                     0x48e7
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_CONTROL2                                     0x4907
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_CONTROL2                                     0x4927
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_CONTROL2                                     0x4947
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_CONTROL2                                     0x4967
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_CONTROL2                                     0x4987
#define mmUNIPHY_PLL_SS_STEP_SIZE                                               0x48c8
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_SS_STEP_SIZE                                 0x48c8
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_SS_STEP_SIZE                                 0x48e8
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_SS_STEP_SIZE                                 0x4908
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_SS_STEP_SIZE                                 0x4928
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_SS_STEP_SIZE                                 0x4948
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_SS_STEP_SIZE                                 0x4968
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_SS_STEP_SIZE                                 0x4988
#define mmUNIPHY_PLL_SS_CNTL                                                    0x48c9
#define mmBPHYC_UNIPHY0_UNIPHY_PLL_SS_CNTL                                      0x48c9
#define mmBPHYC_UNIPHY1_UNIPHY_PLL_SS_CNTL                                      0x48e9
#define mmBPHYC_UNIPHY2_UNIPHY_PLL_SS_CNTL                                      0x4909
#define mmBPHYC_UNIPHY3_UNIPHY_PLL_SS_CNTL                                      0x4929
#define mmBPHYC_UNIPHY4_UNIPHY_PLL_SS_CNTL                                      0x4949
#define mmBPHYC_UNIPHY5_UNIPHY_PLL_SS_CNTL                                      0x4969
#define mmBPHYC_UNIPHY6_UNIPHY_PLL_SS_CNTL                                      0x4989
#define mmUNIPHY_DATA_SYNCHRONIZATION                                           0x48ca
#define mmBPHYC_UNIPHY0_UNIPHY_DATA_SYNCHRONIZATION                             0x48ca
#define mmBPHYC_UNIPHY1_UNIPHY_DATA_SYNCHRONIZATION                             0x48ea
#define mmBPHYC_UNIPHY2_UNIPHY_DATA_SYNCHRONIZATION                             0x490a
#define mmBPHYC_UNIPHY3_UNIPHY_DATA_SYNCHRONIZATION                             0x492a
#define mmBPHYC_UNIPHY4_UNIPHY_DATA_SYNCHRONIZATION                             0x494a
#define mmBPHYC_UNIPHY5_UNIPHY_DATA_SYNCHRONIZATION                             0x496a
#define mmBPHYC_UNIPHY6_UNIPHY_DATA_SYNCHRONIZATION                             0x498a
#define mmUNIPHY_REG_TEST_OUTPUT                                                0x48cb
#define mmBPHYC_UNIPHY0_UNIPHY_REG_TEST_OUTPUT                                  0x48cb
#define mmBPHYC_UNIPHY1_UNIPHY_REG_TEST_OUTPUT                                  0x48eb
#define mmBPHYC_UNIPHY2_UNIPHY_REG_TEST_OUTPUT                                  0x490b
#define mmBPHYC_UNIPHY3_UNIPHY_REG_TEST_OUTPUT                                  0x492b
#define mmBPHYC_UNIPHY4_UNIPHY_REG_TEST_OUTPUT                                  0x494b
#define mmBPHYC_UNIPHY5_UNIPHY_REG_TEST_OUTPUT                                  0x496b
#define mmBPHYC_UNIPHY6_UNIPHY_REG_TEST_OUTPUT                                  0x498b
#define mmUNIPHY_ANG_BIST_CNTL                                                  0x48cc
#define mmBPHYC_UNIPHY0_UNIPHY_ANG_BIST_CNTL                                    0x48cc
#define mmBPHYC_UNIPHY1_UNIPHY_ANG_BIST_CNTL                                    0x48ec
#define mmBPHYC_UNIPHY2_UNIPHY_ANG_BIST_CNTL                                    0x490c
#define mmBPHYC_UNIPHY3_UNIPHY_ANG_BIST_CNTL                                    0x492c
#define mmBPHYC_UNIPHY4_UNIPHY_ANG_BIST_CNTL                                    0x494c
#define mmBPHYC_UNIPHY5_UNIPHY_ANG_BIST_CNTL                                    0x496c
#define mmBPHYC_UNIPHY6_UNIPHY_ANG_BIST_CNTL                                    0x498c
#define mmUNIPHY_REG_TEST_OUTPUT2                                               0x48cd
#define mmBPHYC_UNIPHY0_UNIPHY_REG_TEST_OUTPUT2                                 0x48cd
#define mmBPHYC_UNIPHY1_UNIPHY_REG_TEST_OUTPUT2                                 0x48ed
#define mmBPHYC_UNIPHY2_UNIPHY_REG_TEST_OUTPUT2                                 0x490d
#define mmBPHYC_UNIPHY3_UNIPHY_REG_TEST_OUTPUT2                                 0x492d
#define mmBPHYC_UNIPHY4_UNIPHY_REG_TEST_OUTPUT2                                 0x494d
#define mmBPHYC_UNIPHY5_UNIPHY_REG_TEST_OUTPUT2                                 0x496d
#define mmBPHYC_UNIPHY6_UNIPHY_REG_TEST_OUTPUT2                                 0x498d
#define mmUNIPHY_TMDP_REG0                                                      0x48ce
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG0                                        0x48ce
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG0                                        0x48ee
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG0                                        0x490e
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG0                                        0x492e
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG0                                        0x494e
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG0                                        0x496e
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG0                                        0x498e
#define mmUNIPHY_TMDP_REG1                                                      0x48cf
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG1                                        0x48cf
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG1                                        0x48ef
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG1                                        0x490f
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG1                                        0x492f
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG1                                        0x494f
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG1                                        0x496f
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG1                                        0x498f
#define mmUNIPHY_TMDP_REG2                                                      0x48d0
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG2                                        0x48d0
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG2                                        0x48f0
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG2                                        0x4910
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG2                                        0x4930
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG2                                        0x4950
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG2                                        0x4970
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG2                                        0x4990
#define mmUNIPHY_TMDP_REG3                                                      0x48d1
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG3                                        0x48d1
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG3                                        0x48f1
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG3                                        0x4911
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG3                                        0x4931
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG3                                        0x4951
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG3                                        0x4971
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG3                                        0x4991
#define mmUNIPHY_TMDP_REG4                                                      0x48d2
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG4                                        0x48d2
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG4                                        0x48f2
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG4                                        0x4912
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG4                                        0x4932
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG4                                        0x4952
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG4                                        0x4972
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG4                                        0x4992
#define mmUNIPHY_TMDP_REG5                                                      0x48d3
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG5                                        0x48d3
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG5                                        0x48f3
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG5                                        0x4913
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG5                                        0x4933
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG5                                        0x4953
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG5                                        0x4973
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG5                                        0x4993
#define mmUNIPHY_TMDP_REG6                                                      0x48d4
#define mmBPHYC_UNIPHY0_UNIPHY_TMDP_REG6                                        0x48d4
#define mmBPHYC_UNIPHY1_UNIPHY_TMDP_REG6                                        0x48f4
#define mmBPHYC_UNIPHY2_UNIPHY_TMDP_REG6                                        0x4914
#define mmBPHYC_UNIPHY3_UNIPHY_TMDP_REG6                                        0x4934
#define mmBPHYC_UNIPHY4_UNIPHY_TMDP_REG6                                        0x4954
#define mmBPHYC_UNIPHY5_UNIPHY_TMDP_REG6                                        0x4974
#define mmBPHYC_UNIPHY6_UNIPHY_TMDP_REG6                                        0x4994
#define mmUNIPHY_TPG_CONTROL                                                    0x48d5
#define mmBPHYC_UNIPHY0_UNIPHY_TPG_CONTROL                                      0x48d5
#define mmBPHYC_UNIPHY1_UNIPHY_TPG_CONTROL                                      0x48f5
#define mmBPHYC_UNIPHY2_UNIPHY_TPG_CONTROL                                      0x4915
#define mmBPHYC_UNIPHY3_UNIPHY_TPG_CONTROL                                      0x4935
#define mmBPHYC_UNIPHY4_UNIPHY_TPG_CONTROL                                      0x4955
#define mmBPHYC_UNIPHY5_UNIPHY_TPG_CONTROL                                      0x4975
#define mmBPHYC_UNIPHY6_UNIPHY_TPG_CONTROL                                      0x4995
#define mmUNIPHY_TPG_SEED                                                       0x48d6
#define mmBPHYC_UNIPHY0_UNIPHY_TPG_SEED                                         0x48d6
#define mmBPHYC_UNIPHY1_UNIPHY_TPG_SEED                                         0x48f6
#define mmBPHYC_UNIPHY2_UNIPHY_TPG_SEED                                         0x4916
#define mmBPHYC_UNIPHY3_UNIPHY_TPG_SEED                                         0x4936
#define mmBPHYC_UNIPHY4_UNIPHY_TPG_SEED                                         0x4956
#define mmBPHYC_UNIPHY5_UNIPHY_TPG_SEED                                         0x4976
#define mmBPHYC_UNIPHY6_UNIPHY_TPG_SEED                                         0x4996
#define mmUNIPHY_DEBUG                                                          0x48d7
#define mmBPHYC_UNIPHY0_UNIPHY_DEBUG                                            0x48d7
#define mmBPHYC_UNIPHY1_UNIPHY_DEBUG                                            0x48f7
#define mmBPHYC_UNIPHY2_UNIPHY_DEBUG                                            0x4917
#define mmBPHYC_UNIPHY3_UNIPHY_DEBUG                                            0x4937
#define mmBPHYC_UNIPHY4_UNIPHY_DEBUG                                            0x4957
#define mmBPHYC_UNIPHY5_UNIPHY_DEBUG                                            0x4977
#define mmBPHYC_UNIPHY6_UNIPHY_DEBUG                                            0x4997
#define mmDPG_PIPE_ARBITRATION_CONTROL1                                         0x1b30
#define mmDMIF_PG0_DPG_PIPE_ARBITRATION_CONTROL1                                0x1b30
#define mmDMIF_PG1_DPG_PIPE_ARBITRATION_CONTROL1                                0x1d30
#define mmDMIF_PG2_DPG_PIPE_ARBITRATION_CONTROL1                                0x1f30
#define mmDMIF_PG3_DPG_PIPE_ARBITRATION_CONTROL1                                0x4130
#define mmDMIF_PG4_DPG_PIPE_ARBITRATION_CONTROL1                                0x4330
#define mmDMIF_PG5_DPG_PIPE_ARBITRATION_CONTROL1                                0x4530
#define mmDMIF_PG6_DPG_PIPE_ARBITRATION_CONTROL1                                0x4730
#define mmDPG_PIPE_ARBITRATION_CONTROL2                                         0x1b31
#define mmDMIF_PG0_DPG_PIPE_ARBITRATION_CONTROL2                                0x1b31
#define mmDMIF_PG1_DPG_PIPE_ARBITRATION_CONTROL2                                0x1d31
#define mmDMIF_PG2_DPG_PIPE_ARBITRATION_CONTROL2                                0x1f31
#define mmDMIF_PG3_DPG_PIPE_ARBITRATION_CONTROL2                                0x4131
#define mmDMIF_PG4_DPG_PIPE_ARBITRATION_CONTROL2                                0x4331
#define mmDMIF_PG5_DPG_PIPE_ARBITRATION_CONTROL2                                0x4531
#define mmDMIF_PG6_DPG_PIPE_ARBITRATION_CONTROL2                                0x4731
#define mmDPG_WATERMARK_MASK_CONTROL                                            0x1b32
#define mmDMIF_PG0_DPG_WATERMARK_MASK_CONTROL                                   0x1b32
#define mmDMIF_PG1_DPG_WATERMARK_MASK_CONTROL                                   0x1d32
#define mmDMIF_PG2_DPG_WATERMARK_MASK_CONTROL                                   0x1f32
#define mmDMIF_PG3_DPG_WATERMARK_MASK_CONTROL                                   0x4132
#define mmDMIF_PG4_DPG_WATERMARK_MASK_CONTROL                                   0x4332
#define mmDMIF_PG5_DPG_WATERMARK_MASK_CONTROL                                   0x4532
#define mmDMIF_PG6_DPG_WATERMARK_MASK_CONTROL                                   0x4732
#define mmDPG_PIPE_URGENCY_CONTROL                                              0x1b33
#define mmDMIF_PG0_DPG_PIPE_URGENCY_CONTROL                                     0x1b33
#define mmDMIF_PG1_DPG_PIPE_URGENCY_CONTROL                                     0x1d33
#define mmDMIF_PG2_DPG_PIPE_URGENCY_CONTROL                                     0x1f33
#define mmDMIF_PG3_DPG_PIPE_URGENCY_CONTROL                                     0x4133
#define mmDMIF_PG4_DPG_PIPE_URGENCY_CONTROL                                     0x4333
#define mmDMIF_PG5_DPG_PIPE_URGENCY_CONTROL                                     0x4533
#define mmDMIF_PG6_DPG_PIPE_URGENCY_CONTROL                                     0x4733
#define mmDPG_PIPE_DPM_CONTROL                                                  0x1b34
#define mmDMIF_PG0_DPG_PIPE_DPM_CONTROL                                         0x1b34
#define mmDMIF_PG1_DPG_PIPE_DPM_CONTROL                                         0x1d34
#define mmDMIF_PG2_DPG_PIPE_DPM_CONTROL                                         0x1f34
#define mmDMIF_PG3_DPG_PIPE_DPM_CONTROL                                         0x4134
#define mmDMIF_PG4_DPG_PIPE_DPM_CONTROL                                         0x4334
#define mmDMIF_PG5_DPG_PIPE_DPM_CONTROL                           