INUSE                                       0x1a13
#define mmDCP1_GRPH_SURFACE_ADDRESS_INUSE                                       0x1c13
#define mmDCP2_GRPH_SURFACE_ADDRESS_INUSE                                       0x1e13
#define mmDCP3_GRPH_SURFACE_ADDRESS_INUSE                                       0x4013
#define mmDCP4_GRPH_SURFACE_ADDRESS_INUSE                                       0x4213
#define mmDCP5_GRPH_SURFACE_ADDRESS_INUSE                                       0x4413
#define mmGRPH_DFQ_CONTROL                                                      0x1a14
#define mmDCP0_GRPH_DFQ_CONTROL                                                 0x1a14
#define mmDCP1_GRPH_DFQ_CONTROL                                                 0x1c14
#define mmDCP2_GRPH_DFQ_CONTROL                                                 0x1e14
#define mmDCP3_GRPH_DFQ_CONTROL                                                 0x4014
#define mmDCP4_GRPH_DFQ_CONTROL                                                 0x4214
#define mmDCP5_GRPH_DFQ_CONTROL                                                 0x4414
#define mmGRPH_DFQ_STATUS                                                       0x1a15
#define mmDCP0_GRPH_DFQ_STATUS                                                  0x1a15
#define mmDCP1_GRPH_DFQ_STATUS                                                  0x1c15
#define mmDCP2_GRPH_DFQ_STATUS                                                  0x1e15
#define mmDCP3_GRPH_DFQ_STATUS                                                  0x4015
#define mmDCP4_GRPH_DFQ_STATUS                                                  0x4215
#define mmDCP5_GRPH_DFQ_STATUS                                                  0x4415
#define mmGRPH_INTERRUPT_STATUS                                                 0x1a16
#define mmDCP0_GRPH_INTERRUPT_STATUS                                            0x1a16
#define mmDCP1_GRPH_INTERRUPT_STATUS                                            0x1c16
#define mmDCP2_GRPH_INTERRUPT_STATUS                                            0x1e16
#define mmDCP3_GRPH_INTERRUPT_STATUS                                            0x4016
#define mmDCP4_GRPH_INTERRUPT_STATUS                                            0x4216
#define mmDCP5_GRPH_INTERRUPT_STATUS                                            0x4416
#define mmGRPH_INTERRUPT_CONTROL                                                0x1a17
#define mmDCP0_GRPH_INTERRUPT_CONTROL                                           0x1a17
#define mmDCP1_GRPH_INTERRUPT_CONTROL                                           0x1c17
#define mmDCP2_GRPH_INTERRUPT_CONTROL                                           0x1e17
#define mmDCP3_GRPH_INTERRUPT_CONTROL                                           0x4017
#define mmDCP4_GRPH_INTERRUPT_CONTROL                                           0x4217
#define mmDCP5_GRPH_INTERRUPT_CONTROL                                           0x4417
#define mmGRPH_SURFACE_ADDRESS_HIGH_INUSE                                       0x1a18
#define mmDCP0_GRPH_SURFACE_ADDRESS_HIGH_INUSE                                  0x1a18
#define mmDCP1_GRPH_SURFACE_ADDRESS_HIGH_INUSE                                  0x1c18
#define mmDCP2_GRPH_SURFACE_ADDRESS_HIGH_INUSE                                  0x1e18
#define mmDCP3_GRPH_SURFACE_ADDRESS_HIGH_INUSE                                  0x4018
#define mmDCP4_GRPH_SURFACE_ADDRESS_HIGH_INUSE                                  0x4218
#define mmDCP5_GRPH_SURFACE_ADDRESS_HIGH_INUSE                                  0x4418
#define mmGRPH_COMPRESS_SURFACE_ADDRESS                                         0x1a19
#define mmDCP0_GRPH_COMPRESS_SURFACE_ADDRESS                                    0x1a19
#define mmDCP1_GRPH_COMPRESS_SURFACE_ADDRESS                                    0x1c19
#define mmDCP2_GRPH_COMPRESS_SURFACE_ADDRESS                                    0x1e19
#define mmDCP3_GRPH_COMPRESS_SURFACE_ADDRESS                                    0x4019
#define mmDCP4_GRPH_COMPRESS_SURFACE_ADDRESS                                    0x4219
#define mmDCP5_GRPH_COMPRESS_SURFACE_ADDRESS                                    0x4419
#define mmGRPH_COMPRESS_PITCH                                                   0x1a1a
#define mmDCP0_GRPH_COMPRESS_PITCH                                              0x1a1a
#define mmDCP1_GRPH_COMPRESS_PITCH                                              0x1c1a
#define mmDCP2_GRPH_COMPRESS_PITCH                                              0x1e1a
#define mmDCP3_GRPH_COMPRESS_PITCH                                              0x401a
#define mmDCP4_GRPH_COMPRESS_PITCH                                              0x421a
#define mmDCP5_GRPH_COMPRESS_PITCH                                              0x441a
#define mmGRPH_COMPRESS_SURFACE_ADDRESS_HIGH                                    0x1a1b
#define mmDCP0_GRPH_COMPRESS_SURFACE_ADDRESS_HIGH                               0x1a1b
#define mmDCP1_GRPH_COMPRESS_SURFACE_ADDRESS_HIGH                               0x1c1b
#define mmDCP2_GRPH_COMPRESS_SURFACE_ADDRESS_HIGH                               0x1e1b
#define mmDCP3_GRPH_COMPRESS_SURFACE_ADDRESS_HIGH                               0x401b
#define mmDCP4_GRPH_COMPRESS_SURFACE_ADDRESS_HIGH                               0x421b
#define mmDCP5_GRPH_COMPRESS_SURFACE_ADDRESS_HIGH                               0x441b
#define mmOVL_ENABLE                                                            0x1a1c
#define mmDCP0_OVL_ENABLE                                                       0x1a1c
#define mmDCP1_OVL_ENABLE                                                       0x1c1c
#define mmDCP2_OVL_ENABLE                                                       0x1e1c
#define mmDCP3_OVL_ENABLE                                                       0x401c
#define mmDCP4_OVL_ENABLE                                                       0x421c
#define mmDCP5_OVL_ENABLE                                                       0x441c
#define mmOVL_CONTROL1                                                          0x1a1d
#define mmDCP0_OVL_CONTROL1                                                     0x1a1d
#define mmDCP1_OVL_CONTROL1                                                     0x1c1d
#define mmDCP2_OVL_CONTROL1                                                     0x1e1d
#define mmDCP3_OVL_CONTROL1                                                     0x401d
#define mmDCP4_OVL_CONTROL1                                                     0x421d
#define mmDCP5_OVL_CONTROL1                                                     0x441d
#define mmOVL_CONTROL2                                                          0x1a1e
#define mmDCP0_OVL_CONTROL2                                                     0x1a1e
#define mmDCP1_OVL_CONTROL2                                                     0x1c1e
#define mmDCP2_OVL_CONTROL2                                                     0x1e1e
#define mmDCP3_OVL_CONTROL2                                                     0x401e
#define mmDCP4_OVL_CONTROL2                                                     0x421e
#define mmDCP5_OVL_CONTROL2                                                     0x441e
#define mmOVL_SWAP_CNTL                                                         0x1a1f
