x1dea
#define mmFMT2_FMT_CLAMP_COMPONENT_B                                            0x1fea
#define mmFMT3_FMT_CLAMP_COMPONENT_B                                            0x41ea
#define mmFMT4_FMT_CLAMP_COMPONENT_B                                            0x43ea
#define mmFMT5_FMT_CLAMP_COMPONENT_B                                            0x45ea
#define mmFMT_DYNAMIC_EXP_CNTL                                                  0x1bed
#define mmFMT0_FMT_DYNAMIC_EXP_CNTL                                             0x1bed
#define mmFMT1_FMT_DYNAMIC_EXP_CNTL                                             0x1ded
#define mmFMT2_FMT_DYNAMIC_EXP_CNTL                                             0x1fed
#define mmFMT3_FMT_DYNAMIC_EXP_CNTL                                             0x41ed
#define mmFMT4_FMT_DYNAMIC_EXP_CNTL                                             0x43ed
#define mmFMT5_FMT_DYNAMIC_EXP_CNTL                                             0x45ed
#define mmFMT_CONTROL                                                           0x1bee
#define mmFMT0_FMT_CONTROL                                                      0x1bee
#define mmFMT1_FMT_CONTROL                                                      0x1dee
#define mmFMT2_FMT_CONTROL                                                      0x1fee
#define mmFMT3_FMT_CONTROL                                                      0x41ee
#define mmFMT4_FMT_CONTROL                                                      0x43ee
#define mmFMT5_FMT_CONTROL                                                      0x45ee
#define mmFMT_FORCE_OUTPUT_CNTL                                                 0x1bef
#define mmFMT0_FMT_FORCE_OUTPUT_CNTL                                            0x1bef
#define mmFMT1_FMT_FORCE_OUTPUT_CNTL                                            0x1def
#define mmFMT2_FMT_FORCE_OUTPUT_CNTL                                            0x1fef
#define mmFMT3_FMT_FORCE_OUTPUT_CNTL                                            0x41ef
#define mmFMT4_FMT_FORCE_OUTPUT_CNTL                                            0x43ef
#define mmFMT5_FMT_FORCE_OUTPUT_CNTL                                            0x45ef
#define mmFMT_FORCE_DATA_0_1                                                    0x1bf0
#define mmFMT0_FMT_FORCE_DATA_0_1                                               0x1bf0
#define mmFMT1_FMT_FORCE_DATA_0_1                                               0x1df0
#define mmFMT2_FMT_FORCE_DATA_0_1                                               0x1ff0
#define mmFMT3_FMT_FORCE_DATA_0_1                                               0x41f0
#define mmFMT4_FMT_FORCE_DATA_0_1                                               0x43f0
#define mmFMT5_FMT_FORCE_DATA_0_1                                               0x45f0
#define mmFMT_FORCE_DATA_2_3                                                    0x1bf1
#define mmFMT0_FMT_FORCE_DATA_2_3                                               0x1bf1
#define mmFMT1_FMT_FORCE_DATA_2_3                                               0x1df1
#define mmFMT2_FMT_FORCE_DATA_2_3                                               0x1ff1
#define mmFMT3_FMT_FORCE_DATA_2_3                                               0x41f1
#define mmFMT4_FMT_FORCE_DATA_2_3                                               0x43f1
#define mmFMT5_FMT_FORCE_DATA_2_3                                               0x45f1
#define mmFMT_BIT_DEPTH_CONTROL                                                 0x1bf2
#define mmFMT0_FMT_BIT_DEPTH_CONTROL                                            0x1bf2
#define mmFMT1_FMT_BIT_DEPTH_CONTROL                                            0x1df2
#define mmFMT2_FMT_BIT_DEPTH_CONTROL                                            0x1ff2
#define mmFMT3_FMT_BIT_DEPTH_CONTROL                                            0x41f2
#define mmFMT4_FMT_BIT_DEPTH_CONTROL                                            0x43f2
#define mmFMT5_FMT_BIT_DEPTH_CONTROL                                            0x45f2
#define mmFMT_DITHER_RAND_R_SEED                                                0x1bf3
#define mmFMT0_FMT_DITHER_RAND_R_SEED                                           0x1bf3
#define mmFMT1_FMT_DITHER_RAND_R_SEED                                           0x1df3
#define mmFMT2_FMT_DITHER_RAND_R_SEED                                           0x1ff3
#define mmFMT3_FMT_DITHER_RAND_R_SEED                                           0x41f3
#define mmFMT4_FMT_DITHER_RAND_R_SEED                                           0x43f3
#define mmFMT5_FMT_DITHER_RAND_R_SEED                                           0x45f3
#define mmFMT_DITHER_RAND_G_SEED                                                0x1bf4
#define mmFMT0_FMT_DITHER_RAND_G_SEED                                           0x1bf4
#define mmFMT1_FMT_DITHER_RAND_G_SEED                                           0x1df4
#define mmFMT2_FMT_DITHER_RAND_G_SEED                                           0x1ff4
#define mmFMT3_FMT_DITHER_RAND_G_SEED                                           0x41f4
#define mmFMT4_FMT_DITHER_RAND_G_SEED                                           0x43f4
#define mmFMT5_FMT_DITHER_RAND_G_SEED                                           0x45f4
#define mmFMT_DITHER_RAND_B_SEED                                                0x1bf5
#define mmFMT0_FMT_DITHER_RAND_B_SEED                                           0x1bf5
#define mmFMT1_FMT_DITHER_RAND_B_SEED                                           0x1df5
#define mmFMT2_FMT_DITHER_RAND_B_SEED                                           0x1ff5
#define mmFMT3_FMT_DITHER_RAND_B_SEED                                           0x41f5
#define mmFMT4_FMT_DITHER_RAND_B_SEED                                           0x43f5
#define mmFMT5_FMT_DITHER_RAND_B_SEED                                           0x45f5
#define mmFMT_TEMPORAL_DITHER_PATTERN_CONTROL                                   0x1bf6
#define mmFMT0_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x1bf6
#define mmFMT1_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x1df6
#define mmFMT2_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x1ff6
#define mmFMT3_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x41f6
#define mmFMT4_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x43f6
#define mmFMT5_FMT_TEMPORAL_DITHER_PATTERN_CONTROL                              0x45f6
#define mmFMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                     0x1bf7
#define mmFMT0_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x1bf7
#define mmFMT1_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x1df7
#define mmFMT2_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x1ff7
#define mmFMT3_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x41f7
#define mmFMT4_FMT_TEMPORAL_DITHER_PROGRAMMABLE_PATTERN_S_MATRIX                0x43f7
#define mmFMT5_FMT_TEM