ERFCOUNTER_STATE                                         0x1f25
#define mmDC_PERFMON6_PERFCOUNTER_STATE                                         0x4125
#define mmDC_PERFMON7_PERFCOUNTER_STATE                                         0x4325
#define mmDC_PERFMON8_PERFCOUNTER_STATE                                         0x4525
#define mmDC_PERFMON9_PERFCOUNTER_STATE                                         0x4725
#define mmDC_PERFMON10_PERFCOUNTER_STATE                                        0x59a1
#define mmDC_PERFMON11_PERFCOUNTER_STATE                                        0x5f69
#define mmPERFMON_CNTL                                                          0x173
#define mmDC_PERFMON0_PERFMON_CNTL                                              0x173
#define mmDC_PERFMON1_PERFMON_CNTL                                              0x367
#define mmDC_PERFMON2_PERFMON_CNTL                                              0x18cb
#define mmDC_PERFMON3_PERFMON_CNTL                                              0x1b27
#define mmDC_PERFMON4_PERFMON_CNTL                                              0x1d27
#define mmDC_PERFMON5_PERFMON_CNTL                                              0x1f27
#define mmDC_PERFMON6_PERFMON_CNTL                                              0x4127
#define mmDC_PERFMON7_PERFMON_CNTL                                              0x4327
#define mmDC_PERFMON8_PERFMON_CNTL                                              0x4527
#define mmDC_PERFMON9_PERFMON_CNTL                                              0x4727
#define mmDC_PERFMON10_PERFMON_CNTL                                             0x59a3
#define mmDC_PERFMON11_PERFMON_CNTL                                             0x5f6b
#define mmPERFMON_CNTL2                                                         0x17a
#define mmDC_PERFMON0_PERFMON_CNTL2                                             0x17a
#define mmDC_PERFMON1_PERFMON_CNTL2                                             0x36e
#define mmDC_PERFMON2_PERFMON_CNTL2                                             0x18d2
#define mmDC_PERFMON3_PERFMON_CNTL2                                             0x1b2e
#define mmDC_PERFMON4_PERFMON_CNTL2                                             0x1d2e
#define mmDC_PERFMON5_PERFMON_CNTL2                                             0x1f2e
#define mmDC_PERFMON6_PERFMON_CNTL2                                             0x412e
#define mmDC_PERFMON7_PERFMON_CNTL2                                             0x432e
#define mmDC_PERFMON8_PERFMON_CNTL2                                             0x452e
#define mmDC_PERFMON9_PERFMON_CNTL2                                             0x472e
#define mmDC_PERFMON10_PERFMON_CNTL2                                            0x59aa
#define mmDC_PERFMON11_PERFMON_CNTL2                                            0x5f72
#define mmPERFMON_CVALUE_INT_MISC                                               0x172
#define mmDC_PERFMON0_PERFMON_CVALUE_INT_MISC                                   0x172
#define mmDC_PERFMON1_PERFMON_CVALUE_INT_MISC                                   0x366
#define mmDC_PERFMON2_PERFMON_CVALUE_INT_MISC                                   0x18ca
#define mmDC_PERFMON3_PERFMON_CVALUE_INT_MISC                                   0x1b26
#define mmDC_PERFMON4_PERFMON_CVALUE_INT_MISC                                   0x1d26
#define mmDC_PERFMON5_PERFMON_CVALUE_INT_MISC                                   0x1f26
#define mmDC_PERFMON6_PERFMON_CVALUE_INT_MISC                                   0x4126
#define mmDC_PERFMON7_PERFMON_CVALUE_INT_MISC                                   0x4326
#define mmDC_PERFMON8_PERFMON_CVALUE_INT_MISC                                   0x4526
#define mmDC_PERFMON9_PERFMON_CVALUE_INT_MISC                                   0x4726
#define mmDC_PERFMON10_PERFMON_CVALUE_INT_MISC                                  0x59a2
#define mmDC_PERFMON11_PERFMON_CVALUE_INT_MISC                                  0x5f6a
#define mmPERFMON_CVALUE_LOW                                                    0x174
#define mmDC_PERFMON0_PERFMON_CVALUE_LOW                                        0x174
#define mmDC_PERFMON1_PERFMON_CVALUE_LOW                                        0x368
#define mmDC_PERFMON2_PERFMON_CVALUE_LOW                                        0x18cc
#define mmDC_PERFMON3_PERFMON_CVALUE_LOW                                        0x1b28
#define mmDC_PERFMON4_PERFMON_CVALUE_LOW                                        0x1d28
#define mmDC_PERFMON5_PERFMON_CVALUE_LOW                                        0x1f28
#define mmDC_PERFMON6_PERFMON_CVALUE_LOW                                        0x4128
#define mmDC_PERFMON7_PERFMON_CVALUE_LOW                                        0x4328
#define mmDC_PERFMON8_PERFMON_CVALUE_LOW                                        0x4528
#define mmDC_PERFMON9_PERFMON_CVALUE_LOW                                        0x4728
#define mmDC_PERFMON10_PERFMON_CVALUE_LOW                                       0x59a4
#define mmDC_PERFMON11_PERFMON_CVALUE_LOW                                       0x5f6c
#define mmPERFMON_HI                                                            0x175
#define mmDC_PERFMON0_PERFMON_HI                                                0x175
#define mmDC_PERFMON1_PERFMON_HI                                                0x369
#define mmDC_PERFMON2_PERFMON_HI                                                0x18cd
#define mmDC_PERFMON3_PERFMON_HI                                                0x1b29
#define mmDC_PERFMON4_PERFMON_HI                                                0x1d29
#define mmDC_PERFMON5_PERFMON_HI                                                0x1f29
#define mmDC_PERFMON6_PERFMON_HI                                                0x4129
#define mmDC_PERFMON7_PERFMON_HI                                                0x4329
#define mmDC_PERFMON8_PERFMON_HI                                                0x4529
#define mmDC_PERFMON9_PERFMON_HI                                                0x4729
#define mmDC_PERFMON10_PERFMON_HI                                               0x59a5
#define mmDC_PERFMON11_PERFMON_HI                                               0x5f6d
#define mmPERFMON_LOW                                                           0x176
#define mmDC_PERFMON0_PERFMON_LOW                                               0x176
#define mmDC_PERFMON1_PERFMON_LOW                                               0x36a
#define mmDC_PERFMON2_PERFMON_LOW                                               0x18ce
#define mmDC_PERFMON3_PERFMON_LOW                                               0x1b2a
#define mmDC_PERFMON4_PERFMON_LOW                                               0x1d2a
#define mmDC_PERFMON5_PERFMON_LOW                                               0x1f2a
#define mmDC_PERFMON6_PERFMON_LOW                                               0x412a
#define mmDC_PERFMON7_PERFMON_LOW                                               0x432a
#define mmDC_PERFMON8_PERFMON_LOW                                               0x452a
#define mmDC_PERFMON9_PERFMON_LOW                                               0x472a
#define mmDC_PERFMON10_PERFMON_LOW                                              0x59a6
#define mmDC_PERFMON11_PERFMON_LOW                                              0x5f6e
#define mmPERFMON_TEST_DEBUG_INDEX                                              0x177
#define mmDC_PERFMON0_PERFMON_TEST_DEBUG_INDEX                                  0x177
#define mmDC_PERFMON1_PERFMON_TEST_DEBUG_INDEX                                  0x36b
#define mmDC_PERFMON2_PERFMON_TEST_DEBUG_INDEX                                  0x18cf
#define mmDC_PERFMON3_PERFMON_TEST_DEBUG_INDEX                                  0x1b2b
#define mmDC_PERFMON4_PERFMON_TEST_DEBUG_INDEX                                  0x1d2b
#define mmDC_PERFMON5_PERFMON_TEST_DEBUG_INDEX                                  0x1f2b
#define mmDC_PERFMON6_PERFMON_TEST_DEBUG_INDEX                                  0x412b
#define mmDC_PERFMON7_PERFMON_TEST_DEBUG_INDEX                                  0x432b
#define mmDC_PERFMON8_PERFMON_TEST_DEBUG_INDEX                                  0x452b
#define mmDC_PERFMON9_PERFMON_TEST_DEBUG_INDEX                                  0x472b
#define mmDC_PERFMON10_PERFMON_TEST_DEBUG_INDEX                                 0x59a7
#define mmDC_PERFMON11_PERFMON_TEST_DEBUG_INDEX                                 0x5f6f
#define mmPERFMON_TEST_DEBUG_DATA                                               0x178
#define mmDC_PERFMON0_PERFMON_TEST_DEBUG_DATA                     