                      0x1862
#define mmDCO_MEM_PWR_CTRL2                                                     0x1863
#define mmDCO_CLK_CNTL                                                          0x1864
#define mmDCO_CLK_RAMP_CNTL                                                     0x1865
#define mmDPDBG_CNTL                                                            0x1866
#define mmDPDBG_INTERRUPT                                                       0x1867
#define mmDCO_POWER_MANAGEMENT_CNTL                                             0x1868
#define mmDCO_SOFT_RESET                                                        0x1871
#define mmDIG_SOFT_RESET                                                        0x1872
#define mmDCO_STEREOSYNC_SEL                                                    0x186e
#define mmDCO_TEST_DEBUG_INDEX                                                  0x186f
#define mmDCO_TEST_DEBUG_DATA                                                   0x1870
#define mmDC_I2C_CONTROL                                                        0x16d4
#define mmDC_I2C_ARBITRATION                                                    0x16d5
#define mmDC_I2C_INTERRUPT_CONTROL                                              0x16d6
#define mmDC_I2C_SW_STATUS                                                      0x16d7
#define mmDC_I2C_DDC1_HW_STATUS                                                 0x16d8
#define mmDC_I2C_DDC2_HW_STATUS                                                 0x16d9
#define mmDC_I2C_DDC3_HW_STATUS                                                 0x16da
#define mmDC_I2C_DDC4_HW_STATUS                                                 0x16db
#define mmDC_I2C_DDC5_HW_STATUS                                                 0x16dc
#define mmDC_I2C_DDC6_HW_STATUS                                                 0x16dd
#define mmDC_I2C_DDC1_SPEED                                                     0x16de
#define mmDC_I2C_DDC1_SETUP                                                     0x16df
#define mmDC_I2C_DDC2_SPEED                                                     0x16e0
#define mmDC_I2C_DDC2_SETUP                                                     0x16e1
#define mmDC_I2C_DDC3_SPEED                                                     0x16e2
#define mmDC_I2C_DDC3_SETUP                                                     0x16e3
#define mmDC_I2C_DDC4_SPEED                                                     0x16e4
#define mmDC_I2C_DDC4_SETUP                                                     0x16e5
#define mmDC_I2C_DDC5_SPEED                                                     0x16e6
#define mmDC_I2C_DDC5_SETUP                                                     0x16e7
#define mmDC_I2C_DDC6_SPEED                                                     0x16e8
#define mmDC_I2C_DDC6_SETUP                                                     0x16e9
#define mmDC_I2C_TRANSACTION0                                                   0x16ea
#define mmDC_I2C_TRANSACTION1                                                   0x16eb
#define mmDC_I2C_TRANSACTION2                                                   0x16ec
#define mmDC_I2C_TRANSACTION3                                                   0x16ed
#define mmDC_I2C_DATA                                                           0x16ee
#define mmDC_I2C_DDCVGA_HW_STATUS                                               0x16ef
#define mmDC_I2C_DDCVGA_SPEED                                                   0x16f0
#define mmDC_I2C_DDCVGA_SETUP                                                   0x16f1
#define mmDC_I2C_EDID_DETECT_CTRL                                               0x16f2
#define mmDC_I2C_READ_REQUEST_INTERRUPT                                         0x16f3
#define mmGENERIC_I2C_CONTROL                                                   0x16f4
#define mmGENERIC_I2C_INTERRUPT_CONTROL                                         0x16f5
#define mmGENERIC_I2C_STATUS                                                    0x16f6
#define mmGENERIC_I2C_SPEED                                                     0x16f7
#define mmGENERIC_I2C_SETUP                                                     0x16f8
#define mmGENERIC_I2C_TRANSACTION                                               0x16f9
#define mmGENERIC_I2C_DATA                                                      0x16fa
#define mmGENERIC_I2C_PIN_SELECTION                                             0x16fb
#define mmGENERIC_I2C_PIN_DEBUG                                                 0x16fc
#define mmXDMA_MC_PCIE_CLIENT_CONFIG                                            0x3e0
#define mmXDMA_LOCAL_SURFACE_TILING1                                            0x3e1
#define mmXDMA_LOCAL_SURFACE_TILING2                                            0x3e2
#define mmXDMA_INTERRUPT                                                        0x3e3
#define mmXDMA_CLOCK_GATING_CNTL                                                0x3e4
#define mmXDMA_MEM_POWER_CNTL                                                   0x3e6
#define mmXDMA_IF_BIF_STATUS                                                    0x3e7
#define mmXDMA_PERF_MEAS_STATUS                                                 0x3e8
#define mmXDMA_IF_STATUS                                                        0x3e9
#define mmXDMA_TEST_DEBUG_INDEX                                                 0x3ea
#define mmXDMA_TEST_DEBUG_DATA                                                  0x3eb
#define mmXDMA_RBBMIF_RDWR_CNTL                                                 0x3f8
#define mmXDMA_PG_CONTROL                                                       0x3f9
#define mmXDMA_PG_WDATA                                                         0x3fa
#define mmXDMA_PG_STATUS                                                        0x3fb
#define mmXDMA_AON_TEST_DEBUG_INDEX                                             0x3fc
#define mmXDMA_AON_TEST_DEBUG_DATA                                              0x3fd
#define mmXDMA_MSTR_CNTL                                                        0x3ec
#define mmXDMA_MSTR_STATUS                                                      0x3ed
#define mmXDMA_MSTR_MEM_CLIENT_CONFIG            