                                                  0x436d
#define mmBLND5_BLND_CONTROL                                                    0x456d
#define mmBLND6_BLND_CONTROL                                                    0x476d
#define mmSM_CONTROL2                                                           0x1b6e
#define mmBLND0_SM_CONTROL2                                                     0x1b6e
#define mmBLND1_SM_CONTROL2                                                     0x1d6e
#define mmBLND2_SM_CONTROL2                                                     0x1f6e
#define mmBLND3_SM_CONTROL2                                                     0x416e
#define mmBLND4_SM_CONTROL2                                                     0x436e
#define mmBLND5_SM_CONTROL2                                                     0x456e
#define mmBLND6_SM_CONTROL2                                                     0x476e
#define mmBLND_CONTROL2                                                         0x1b6f
#define mmBLND0_BLND_CONTROL2                                                   0x1b6f
#define mmBLND1_BLND_CONTROL2                                                   0x1d6f
#define mmBLND2_BLND_CONTROL2                                                   0x1f6f
#define mmBLND3_BLND_CONTROL2                                                   0x416f
#define mmBLND4_BLND_CONTROL2                                                   0x436f
#define mmBLND5_BLND_CONTROL2                                                   0x456f
#define mmBLND6_BLND_CONTROL2                                                   0x476f
#define mmBLND_UPDATE                                                           0x1b70
#define mmBLND0_BLND_UPDATE                                                     0x1b70
#define mmBLND1_BLND_UPDATE                                                     0x1d70
#define mmBLND2_BLND_UPDATE                                                     0x1f70
#define mmBLND3_BLND_UPDATE                                                     0x4170
#define mmBLND4_BLND_UPDATE                                                     0x4370
#define mmBLND5_BLND_UPDATE                                                     0x4570
#define mmBLND6_BLND_UPDATE                                                     0x4770
#define mmBLND_UNDERFLOW_INTERRUPT                                              0x1b71
#define mmBLND0_BLND_UNDERFLOW_INTERRUPT                                        0x1b71
#define mmBLND1_BLND_UNDERFLOW_INTERRUPT                                        0x1d71
#define mmBLND2_BLND_UNDERFLOW_INTERRUPT                                        0x1f71
#define mmBLND3_BLND_UNDERFLOW_INTERRUPT                                        0x4171
#define mmBLND4_BLND_UNDERFLOW_INTERRUPT                                        0x4371
#define mmBLND5_BLND_UNDERFLOW_INTERRUPT                                        0x4571
#define mmBLND6_BLND_UNDERFLOW_INTERRUPT                                        0x4771
#define mmBLND_V_UPDATE_LOCK                                                    0x1b73
#define mmBLND0_BLND_V_UPDATE_LOCK                                              0x1b73
#define mmBLND1_BLND_V_UPDATE_LOCK                                              0x1d73
#define mmBLND2_BLND_V_UPDATE_LOCK                                              0x1f73
#define mmBLND3_BLND_V_UPDATE_LOCK                                              0x4173
#define mmBLND4_BLND_V_UPDATE_LOCK                                              0x4373
#define mmBLND5_BLND_V_UPDATE_LOCK                                              0x4573
#define mmBLND6_BLND_V_UPDATE_LOCK                                              0x4773
#define mmBLND_REG_UPDATE_STATUS                                                0x1b77
#define mmBLND0_BLND_REG_UPDATE_STATUS                                          0x1b77
#define mmBLND1_BLND_REG_UPDATE_STATUS                                          0x1d77
#define mmBLND2_BLND_REG_UPDATE_STATUS                                          0x1f77
#define mmBLND3_BLND_REG_UPDATE_STATUS                                          0x4177
#define mmBLND4_BLND_REG_UPDATE_STATUS                                          0x4377
#define mmBLND5_BLND_REG_UPDATE_STATUS                                          0x4577
#define mmBLND6_BLND_REG_UPDATE_STATUS                                          0x4777
#define mmBLND_DEBUG                                                            0x1b74
#define mmBLND0_BLND_DEBUG              