                                        0x406c
#define mmDCP4_CUR_COLOR1                                                       0x426c
#define mmDCP5_CUR_COLOR1                                                       0x446c
#define mmCUR_COLOR2                                                            0x1a6d
#define mmDCP0_CUR_COLOR2                                                       0x1a6d
#define mmDCP1_CUR_COLOR2                                                       0x1c6d
#define mmDCP2_CUR_COLOR2                                                       0x1e6d
#define mmDCP3_CUR_COLOR2                                                       0x406d
#define mmDCP4_CUR_COLOR2                                                       0x426d
#define mmDCP5_CUR_COLOR2                                                       0x446d
#define mmCUR_UPDATE                                                            0x1a6e
#define mmDCP0_CUR_UPDATE                                                       0x1a6e
#define mmDCP1_CUR_UPDATE                                                       0x1c6e
#define mmDCP2_CUR_UPDATE                                                       0x1e6e
#define mmDCP3_CUR_UPDATE                                                       0x406e
#define mmDCP4_CUR_UPDATE                                                       0x426e
#define mmDCP5_CUR_UPDATE                                                       0x446e
#define mmCUR_REQUEST_FILTER_CNTL                                               0x1a99
#define mmDCP0_CUR_REQUEST_FILTER_CNTL                                          0x1a99
#define mmDCP1_CUR_REQUEST_FILTER_CNTL                                          0x1c99
#define mmDCP2_CUR_REQUEST_FILTER_CNTL                                          0x1e99
#define mmDCP3_CUR_REQUEST_FILTER_CNTL                                          0x4099
#define mmDCP4_CUR_REQUEST_FILTER_CNTL                                          0x4299
#define mmDCP5_CUR_REQUEST_FILTER_CNTL                                          0x4499
#define mmCUR_STEREO_CONTROL                                                    0x1a9a
#define mmDCP0_CUR_STEREO_CONTROL                                               0x1a9a
#define mmDCP1_CUR_STEREO_CONTROL                                               0x1c9a
#define mmDCP2_CUR_STEREO_CONTROL                                               0x1e9a
#define mmDCP3_CUR_STEREO_CONTROL                                               0x409a
#define mmDCP4_CUR_STEREO_CONTROL                                               0x429a
#define mmDCP5_CUR_STEREO_CONTROL                                               0x449a
#define mmDC_LUT_RW_MODE                                                        0x1a78
#define mmDCP0_DC_LUT_RW_MODE                                                   0x1a78
#define mmDCP1_DC_LUT_RW_MODE                                                   0x1c78
#define mmDCP2_DC_LUT_RW_MODE                                                   0x1e78
#define mmDCP3_DC_LUT_RW_MODE                                                   0x4078
#define mmDCP4_DC_LUT_RW_MODE                                                   0x4278
#define mmDCP5_DC_LUT_RW_MODE                                                   0x4478
#define mmDC_LUT_RW_INDEX                                                       0x1a79
#define mmDCP0_DC_LUT_RW_INDEX                                                  0x1a79
#define mmDCP1_DC_LUT_RW_INDEX                                                  0x1c79
#define mmDCP2_DC_LUT_RW_INDEX                                                  0x1e79
#define mmDCP3_DC_LUT_RW_INDEX                                                  0x4079
#define mmDCP4_DC_LUT_RW_INDEX                                                  0x4279
#define mmDCP5_DC_LUT_RW_INDEX                                                  0x4479
#define mmDC_LUT_SEQ_COLOR                                                      0x1a7a
#define mmDCP0_DC_LUT_SEQ_COLOR                                                 0x1a7a
#define mmDCP1_DC_LUT_SEQ_COLOR                                                 0x1c7a
#define mmDCP2_DC_LUT_SEQ_COLOR                                                 0x1e7a
#define mmDCP3_DC_LUT_SEQ_COLOR                                                 0x407a
#define mmDCP4_DC_LUT_SEQ_COLOR                                                 0x427a
#define mmDCP5_DC_LUT_SEQ_COLOR                                                 0x447a
#define mmDC_LUT_PWL_DATA                                                       0x1a7b
#define mmDCP0_DC_LUT_PWL_DATA                                                  0x1a7b
#define mmDCP1_DC_LUT_PWL_DATA                                                  0x1c7b
#define mmDCP2_DC_LUT_PWL_DATA                                                  0x1e7b
#define mmDCP3_DC_LUT_PWL_DATA                                                  0x407b
#define mmDCP4_DC_LUT_PWL_DATA                                                  0x427b
#define mmDCP5_DC_LUT_PWL_DATA                                                  0x447b
#define mmDC_LUT_30_COLOR                                                       0x1a7c
#define mmDCP0_DC_LUT_30_COLOR                                                  0x1a7c
#define mmDCP1_DC_LUT_30_COLOR                                                  0x1c7c
#define mmDCP2_DC_LUT_30_COLOR                                                  0x1e7c
#define mmDCP3_DC_LUT_30_COLOR                                                  0x407c
#define mmDCP4_DC_LUT_30_COLOR                                                  0x427c
#define mmDCP5_DC_LUT_30_COLOR                                                  0x447c
#define mmDC_LUT_VGA_ACCESS_ENABLE                                              0x1a7d
#define mmDCP0_DC_LUT_VGA_ACCESS_ENABLE                                         0x1a7d
#define mmDCP1_DC_LUT_VGA_ACCESS_ENABLE                                         0x1c7d
#define mmDCP2_DC_LUT_VGA_ACCESS_ENABLE                                         0x1e7d
#define mmDCP3_DC_LUT_VGA_ACCESS_ENABLE                                         0x407d
#define mmDCP4_DC_LUT_VGA_ACCESS_ENABLE                                         0x427d
#define mmDCP5_DC_LUT_VGA_ACCESS_ENABLE                                         0x447d
#define mmDC_LUT_WRITE_EN_MASK                                                  0x1a7e
#define mmDCP0_DC_LUT_WRITE_EN_MASK                                             0x1a7e
#define mmDCP1_DC_LUT_WRITE_EN_MASK                                             0x1c7e
#define mmDCP2_DC_LUT_WRITE_EN_MASK                                             0x1e7e
#define mmDCP3_DC_LUT_WRITE_EN_MASK                                             0x407e
#define mmDCP4_DC_LUT_WRITE_EN_MASK                                             0x427e
#define mmDCP5_DC_LUT_WRITE_EN_MASK                                             0x447e
#define mmDC_LUT_AUTOFILL                                                       0x1a7f
#define mmDCP0_DC_LUT_AUTOFILL                                                  0x1a7f
#define mmDCP1_DC_LUT_AUTOFILL                                                  0x1c7f
#define mmDCP2_DC_LUT_AUTOFILL                                                  0x1e7f
#define mmDCP3_DC_LUT_AUTOFILL                                                  0x407f
#define mmDCP4_DC_LUT_AUTOFILL                                                  0x427f
#define mmDCP5_DC_LUT_AUTOFILL                                                  0x447f
#define mmDC_LUT_CONTROL                                                        0x1a80
#define mmDCP0_DC_LUT_CONTROL                                                   0x1a80
#define mmDCP1_DC_LUT_CONTROL                                                   0x1c80
#define mmDCP2_DC_LUT_CONTROL                                                   0x1e80
#define mmDCP3_DC_LUT_CONTROL                                                   0x4080
#define mmDCP4_DC_LUT_CONTROL                                                   0x4280
#define mmDCP5_DC_LUT_CONTROL                                                   0x4480
#define mmDC_LUT_BLACK_OFFSET_BLUE                                              0x1a81
#define mmDCP0_DC_LUT_BLACK_OFFSET_BLUE                                         0x1a81
#define mmDCP1_DC_LUT_BLACK_OFFSET_BLUE                                         0x1c81
#define mmDCP2_DC_LUT_BLACK_OFFSET_BLUE                                         0x1e81
#define mmDCP3_DC_LUT_BLACK_OFFSET_BLUE                                         0x4081
#define mmDCP4_DC_LUT_BLACK_OFFSET_BLUE                                         0x4281
#define mmDCP5_DC_LUT_BLACK_OFFSET_BLUE                                         0x4481
#define mmDC_LUT_BLACK_OFFSET_GREEN                                             0x1a82
#define mmDCP0_DC_LUT_BLACK_OFFSET_GREEN                                        0x1a82
#define mmDCP1_DC_LUT_BLACK_OFFSET_GREEN                                        0x1c82
#define mmDCP2_DC_LUT_BLACK_OFFSET_GREEN                                        0x1e82
#define mmDCP3_DC_LUT_BLACK_OFFSET_GREEN                                        0x4082
#define mmDCP4_DC_LUT_BLACK_OFFSET_GREEN                                        0x4282
#define mmDCP5_DC_LUT_BLACK_OFFSET_GREEN                                        0x4482
#define mmDC_LUT_BLACK_OFFSET_RED                                               0x1a83
#define mmDCP0_DC_LUT_BLACK_OFFSET_RED                                          0x1a83
#define mmDCP1_DC_LUT_BLACK_OFFSET_RED                                          0x1c83
#define mmDCP2_DC_LUT_BLACK_OFFSET_RED                                          0x1e83
#define mmDCP3_DC_LUT_BLACK_OFFSET_RED                                          0x4083
#define mmDCP4_DC_LUT_BLACK_OFFSET_RED                                          0x4283
#define mmDCP5_DC_LUT_BLACK_OFFSET_RED                                          0x4483
#define mmDC_LUT_WHITE_OFFSET_BLUE                                              0x1a84
#define mmDCP0_DC_LUT_WHITE_OFFSET_BLUE                                         0x1a84
#define mmDCP1_DC_LUT_WHITE_OFFSET_BLUE                                         0x1c84
#define mmDCP2_DC_LUT_WHITE_OFFSET_BLUE                                         0x1e84
#define mmDCP3_DC_LUT_WHITE_OFFSET_BLUE                                         0x4084
#define mmDCP4_DC_LUT_WHITE_OFFSET_BLUE                                         0x4284
#define mmDCP5_DC_LUT_WHITE_OFFSET_BLUE                                         0x4484
#define mmDC_LUT_WHITE_OFFSET_GREEN                                             0x1a85
#define mmDCP0_DC_LUT_WHITE_OFFSET_GREEN                                        0x1a85
#define mmDCP1_DC_LUT_WHITE_OFFSET_GREEN                                        0x1c85
#define mmDCP2_DC_LUT_WHITE_OFFSET_GREEN                                        0x1e85
#define mmDCP3_DC_LUT_WHITE_OFFSET_GREEN                                        0x4085
#define mmDCP4_DC_LUT_WHITE_OFFSET_GREEN                                        0x4285
#define mmDCP5_DC_LUT_WHITE_OFFSET_GREEN                                        0x4485
#define mmDC_LUT_WHITE_OFFSET_RED                                               0x1a86
#define mmDCP0_DC_LUT_WHITE_OFFSET_RED                                          0x1a86
#define mmDCP1_DC_LUT_WHITE_OFFSET_RED                                          0x1c86
#define mmDCP2_DC_LUT_WHITE_OFFSET_RED                                          0x1e86
#define mmDCP3_DC_LUT_WHITE_OFFSET_RED                                          0x4086
#define mmDCP4_DC_LUT_WHITE_OFFSET_RED                                          0x4286
#define mmDCP5_DC_LUT_WHITE_OFFSET_RED                                          0x4486
#define mmDCP_CRC_CONTROL                                                       0x1a87
#define mmDCP0_DCP_CRC_CONTROL                                                  0x1a87
#define mmDCP1_DCP_CRC_CONTROL                                                  0x1c87
#define mmDCP2_DCP_CRC_CONTROL                                                  0x1e87
#define mmDCP3_DCP_CRC_CONTROL                                                  0x4087
#define mmDCP4_DCP_CRC_CONTROL                                                  0x4287
#define mmDCP5_DCP_CRC_CONTROL                                                  0x4487
#define mmDCP_CRC_MASK                                                          0x1a88
#define mmDCP0_DCP_CRC_MASK                                                     0x1a88
#define mmDCP1_DCP_CRC_MASK                                                     0x1c88
#define mmDCP2_DCP_CRC_MASK                                                     0x1e88
#define mmDCP3_DCP_CRC_MASK                                                     0x4088
#define mmDCP4_DCP_CRC_MASK                                                     0x4288
#define mmDCP5_DCP_CRC_MASK                                                     0x4488
#define mmDCP_CRC_CURRENT                                                       0x1a89
#define mmDCP0_DCP_CRC_CURRENT                                                  0x1a89
#define mmDCP1_DCP_CRC_CURRENT                                                  0x1c89
#define mmDCP2_DCP_CRC_CURRENT                                                  0x1e89
#define mmDCP3_DCP_CRC_CURRENT                                                  0x4089
#define mmDCP4_DCP_CRC_CURRENT                                                  0x4289
#define mmDCP5_DCP_CRC_CURRENT                                                  0x4489
#define mmDCP_CRC_LAST                                                          0x1a8b
#define mmDCP0_DCP_CRC_LAST                                                     0x1a8b
#define mmDCP1_DCP_CRC_LAST                                                     0x1c8b
#define mmDCP2_DCP_CRC_LAST                                                     0x1e8b
#define mmDCP3_DCP_CRC_LAST                                                     0x408b
#define mmDCP4_DCP_CRC_LAST                                                     0x428b
#define mmDCP5_DCP_CRC_LAST                                                     0x448b
#define mmDCP_DEBUG                                                             0x1a8d
#define mmDCP0_DCP_DEBUG                                                        0x1a8d
#define mmDCP1_DCP_DEBUG                                                        0x1c8d
#define mmDCP2_DCP_DEBUG                                                        0x1e8d
#define mmDCP3_DCP_DEBUG                                                        0x408d
#define mmDCP4_DCP_DEBUG                                                        0x428d
#define mmDCP5_DCP_DEBUG                                                        0x448d
#define mmGRPH_FLIP_RATE_CNTL                                                   0x1a8e
#define mmDCP0_GRPH_FLIP_RATE_CNTL                                              0x1a8e
#define mmDCP1_GRPH_FLIP_RATE_CNTL                                              0x1c8e
#define mmDCP2_GRPH_FLIP_RATE_CNTL                                              0x1e8e
#define mmDCP3_GRPH_FLIP_RATE_CNTL                                              0x408e
#define mmDCP4_GRPH_FLIP_RATE_CNTL                                              0x428e
#define mmDCP5_GRPH_FLIP_RATE_CNTL                                              0x448e
#define mmDCP_GSL_CONTROL                                                       0x1a90
#define mmDCP0_DCP_GSL_CONTROL                                                  0x1a90
#define mmDCP1_DCP_GSL_CONTROL                                                  0x1c90
#define mmDCP2_DCP_GSL_CONTROL                                                  0x1e90
#define mmDCP3_DCP_GSL_CONTROL                                                  0x4090
#define mmDCP4_DCP_GSL_CONTROL                                                  0x4290
#define mmDCP5_DCP_GSL_CONTROL                                                  0x4490
#define mmDCP_LB_DATA_GAP_BETWEEN_CHUNK                                         0x1a91
#define mmDCP0_DCP_LB_DATA_GAP_BETWEEN_CHUNK                                    0x1a91
#define mmDCP1_DCP_LB_DATA_GAP_BETWEEN_CHUNK                                    0x1c91
#define mmDCP2_DCP_LB_DATA_GAP_BETWEEN_CHUNK                                    0x1e91
#define mmDCP3_DCP_LB_DATA_GAP_BETWEEN_CHUNK                                    0x4091
#define mmDCP4_DCP_LB_DATA_GAP_BETWEEN_CHUNK                                    0x4291
#define mmDCP5_DCP_LB_DATA_GAP_BETWEEN_CHUNK                                    0x4491
#define mmOVL_SECONDARY_SURFACE_ADDRESS                                         0x1a92
#define mmDCP0_OVL_SECONDARY_SURFACE_ADDRESS                                    0x1a92
#define mmDCP1_OVL_SECONDARY_SURFACE_ADDRESS                                    0x1c92
#define mmDCP2_OVL_SECONDARY_SURFACE_ADDRESS                                    0x1e92
#define mmDCP3_OVL_SECONDARY_SURFACE_ADDRESS                                    0x4092
#define mmDCP4_OVL_SECONDARY_SURFACE_ADDRESS                                    0x4292
#define mmDCP5_OVL_SECONDARY_SURFACE_ADDRESS                                    0x4492
#define mmOVL_STEREOSYNC_FLIP                                                   0x1a93
#define mmDCP0_OVL_STEREOSYNC_FLIP                                              0x1a93
#define mmDCP1_OVL_STEREOSYNC_FLIP                                              0x1c93
#define mmDCP2_OVL_STEREOSYNC_FLIP                                              0x1e93
#define mmDCP3_OVL_STEREOSYNC_FLIP                                              0x4093
#define mmDCP4_OVL_STEREOSYNC_FLIP                                              0x4293
#define mmDCP5_OVL_STEREOSYNC_FLIP                                              0x4493
#define mmOVL_SECONDARY_SURFACE_ADDRESS_HIGH                                    0x1a94
#define mmDCP0_OVL_SECONDARY_SURFACE_ADDRESS_HIGH                               0x1a94
#define mmDCP1_OVL_SECONDARY_SURFACE_ADDRESS_HIGH                               0x1c94
#define mmDCP2_OVL_SECONDARY_SURFACE_ADDRESS_HIGH                               0x1e94
#define mmDCP3_OVL_SECONDARY_SURFACE_ADDRESS_HIGH                               0x4094
#define mmDCP4_OVL_SECONDARY_SURFACE_ADDRESS_HIGH                               0x4294
#define mmDCP5_OVL_SECONDARY_SURFACE_ADDRESS_HIGH                               0x4494
#define mmDCP_TEST_DEBUG_INDEX                                                  0x1a95
#define mmDCP0_DCP_TEST_DEBUG_INDEX                                             0x1a95
#define mmDCP1_DCP_TEST_DEBUG_INDEX                                             0x1c95
#define mmDCP2_DCP_TEST_DEBUG_INDEX                                             0x1e95
#define mmDCP3_DCP_TEST_DEBUG_INDEX                                             0x4095
#define mmDCP4_DCP_TEST_DEBUG_INDEX                                             0x4295
#define mmDCP5_DCP_TEST_DEBUG_INDEX                                             0x4495
#define mmDCP_TEST_DEBUG_DATA                                                   0x1a96
#define mmDCP0_DCP_TEST_DEBUG_DATA                                              0x1a96
#define mmDCP1_DCP_TEST_DEBUG_DATA                                              0x1c96
#define mmDCP2_DCP_TEST_DEBUG_DATA                                              0x1e96
#define mmDCP3_DCP_TEST_DEBUG_DATA                                              0x4096
#define mmDCP4_DCP_TEST_DEBUG_DATA                                              0x4296
#define mmDCP5_DCP_TEST_DEBUG_DATA                                              0x4496
#define mmGRPH_STEREOSYNC_FLIP                                                  0x1a97
#define mmDCP0_GRPH_STEREOSYNC_FLIP                                             0x1a97
#define mmDCP1_GRPH_STEREOSYNC_FLIP                                             0x1c97
#define mmDCP2_GRPH_STEREOSYNC_FLIP                                             0x1e97
#define mmDCP3_GRPH_STEREOSYNC_FLIP                                             0x4097
#define mmDCP4_GRPH_STEREOSYNC_FLIP                                             0x4297
#define mmDCP5_GRPH_STEREOSYNC_FLIP                                             0x4497
#define mmDCP_DEBUG2                                                            0x1a98
#define mmDCP0_DCP_DEBUG2                                                       0x1a98
#define mmDCP1_DCP_DEBUG2                                                       0x1c98
#define mmDCP2_DCP_DEBUG2                                                       0x1e98
#define mmDCP3_DCP_DEBUG2                                                       0x4098
#define mmDCP4_DCP_DEBUG2                                                       0x4298
#define mmDCP5_DCP_DEBUG2                                                       0x4498
#define mmHW_ROTATION                                                           0x1a9e
#define mmDCP0_HW_ROTATION                                                      0x1a9e
#define mmDCP1_HW_ROTATION                                                      0x1c9e
#define mmDCP2_HW_ROTATION                                                      0x1e9e
#define mmDCP3_HW_ROTATION                                                      0x409e
#define mmDCP4_HW_ROTATION                                                      0x429e
#define mmDCP5_HW_ROTATION                                                      0x449e
#define mmGRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                                    0x1a9f
#define mmDCP0_GRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                               0x1a9f
#define mmDCP1_GRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                               0x1c9f
#define mmDCP2_GRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                               0x1e9f
#define mmDCP3_GRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                               0x409f
#define mmDCP4_GRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                               0x429f
#define mmDCP5_GRPH_XDMA_CACHE_UNDERFLOW_DET_CNTL                               0x449f
#define mmREGAMMA_CONTROL                                                       0x1aa0
#define mmDCP0_REGAMMA_CONTROL                                                  0x1aa0
#define mmDCP1_REGAMMA_CONTROL                                                  0x1ca0
#define mmDCP2_REGAMMA_CONTROL                                                  0x1ea0
#define mmDCP3_REGAMMA_CONTROL                                                  0x40a0
#define mmDCP4_REGAMMA_CONTROL                                                  0x42a0
#define mmDCP5_REGAMMA_CONTROL                                                  0x44a0
#define mmREGAMMA_LUT_INDEX                                                     0x1aa1
#define mmDCP0_REGAMMA_LUT_INDEX                                                0x1aa1
#define mmDCP1_REGAMMA_LUT_INDEX                                                0x1ca1
#define mmDCP2_REGAMMA_LUT_INDEX                                                0x1ea1
#define mmDCP3_REGAMMA_LUT_INDEX                                                0x40a1
#define mmDCP4_REGAMMA_LUT_INDEX                                                0x42a1
#define mmDCP5_REGAMMA_LUT_INDEX                                                0x44a1
#define mmREGAMMA_LUT_DATA                                                      0x1aa2
#define mmDCP0_REGAMMA_LUT_DATA                                                 0x1aa2
#define mmDCP1_REGAMMA_LUT_DATA                                                 0x1ca2
#define mmDCP2_REGAMMA_LUT_DATA                                                 0x1ea2
#define mmDCP3_REGAMMA_LUT_DATA                                                 0x40a2
#define mmDCP4_REGAMMA_LUT_DATA                                                 0x42a2
#define mmDCP5_REGAMMA_LUT_DATA                                                 0x44a2
#define mmREGAMMA_LUT_WRITE_EN_MASK                                             0x1aa3
#define mmDCP0_REGAMMA_LUT_WRITE_EN_MASK                                        0x1aa3
#define mmDCP1_REGAMMA_LUT_WRITE_EN_MASK                                        0x1ca3
#define mmDCP2_REGAMMA_LUT_WRITE_EN_MASK                                        0x1ea3
#define mmDCP3_REGAMMA_LUT_WRITE_EN_MASK                                        0x40a3
#define mmDCP4_REGAMMA_LUT_WRITE_EN_MASK                                        0x42a3
#define mmDCP5_REGAMMA_LUT_WRITE_EN_MASK                                        0x44a3
#define mmREGAMMA_CNTLA_START_CNTL                                              0x1aa4
#define mmDCP0_REGAMMA_CNTLA_START_CNTL                                         0x1aa4
#define mmDCP1_REGAMMA_CNTLA_START_CNTL                                         0x1ca4
#define mmDCP2_REGAMMA_CNTLA_START_CNTL                                         0x1ea4
#define mmDCP3_REGAMMA_CNTLA_START_CNTL                                         0x40a4
#define mmDCP4_REGAMMA_CNTLA_START_CNTL                                         0x42a4
#define mmDCP5_REGAMMA_CNTLA_START_CNTL                                         0x44a4
#define mmREGAMMA_CNTLA_SLOPE_CNTL                                              0x1aa5
#define mmDCP0_REGAMMA_CNTLA_SLOPE_CNTL                                         0x1aa5
#define mmDCP1_REGAMMA_CNTLA_SLOPE_CNTL                                         0x1ca5
#define mmDCP2_REGAMMA_CNTLA_SLOPE_CNTL                                         0x1ea5
#define mmDCP3_REGAMMA_CNTLA_SLOPE_CNTL                                         0x40a5
#define mmDCP4_REGAMMA_CNTLA_SLOPE_CNTL                                         0x42a5
#define mmDCP5_REGAMMA_CNTLA_SLOPE_CNTL                                         0x44a5
#define mmREGAMMA_CNTLA_END_CNTL1                                               0x1aa6
#define mmDCP0_REGAMMA_CNTLA_END_CNTL1                                          0x1aa6
#define mmDCP1_REGAMMA_CNTLA_END_CNTL1                                          0x1ca6
#define mmDCP2_REGAMMA_CNTLA_END_CNTL1                                          0x1ea6
#define mmDCP3_REGAMMA_CNTLA_END_CNTL1                                          0x40a6
#define mmDCP4_REGAMMA_CNTLA_END_CNTL1                                          0x42a6
#define mmDCP5_REGAMMA_CNTLA_END_CNTL1                                          0x44a6
#define mmREGAMMA_CNTLA_END_CNTL2                                               0x1aa7
#define mmDCP0_REGAMMA_CNTLA_END_CNTL2                                          0x1aa7
#define mmDCP1_REGAMMA_CNTLA_END_CNTL2                                          0x1ca7
#define mmDCP2_REGAMMA_CNTLA_END_CNTL2                                          0x1ea7
#define mmDCP3_REGAMMA_CNTLA_END_CNTL2                                          0x40a7
#define mmDCP4_REGAMMA_CNTLA_END_CNTL2                                          0x42a7
#define mmDCP5_REGAMMA_CNTLA_END_CNTL2                                          0x44a7
#define mmREGAMMA_CNTLA_REGION_0_1                                              0x1aa8
#define mmDCP0_REGAMMA_CNTLA_REGION_0_1                                         0x1aa8
#define mmDCP1_REGAMMA_CNTLA_REGION_0_1                                         0x1ca8
#define mmDCP2_REGAMMA_CNTLA_REGION_0_1                                         0x1ea8
#define mmDCP3_REGAMMA_CNTLA_REGION_0_1                                         0x40a8
#define mmDCP4_REGAMMA_CNTLA_REGION_0_1                                         0x42a8
#define mmDCP5_REGAMMA_CNTLA_REGION_0_1                                         0x44a8
#define mmREGAMMA_CNTLA_REGION_2_3                                              0x1aa9
#define mmDCP0_REGAMMA_CNTLA_REGION_2_3                                         0x1aa9
#define mmDCP1_REGAMMA_CNTLA_REGION_2_3                                         0x1ca9
#define mmDCP2_REGAMMA_CNTLA_REGION_2_3                                         0x1ea9
#define mmDCP3_REGAMMA_CNTLA_REGION_2_3                                         0x40a9
#define mmDCP4_REGAMMA_CNTLA_REGION_2_3                                         0x42a9
#define mmDCP5_REGAMMA_CNTLA_REGION_2_3                                         0x44a9
#define mmREGAMMA_CNTLA_REGION_4_5                                              0x1aaa
#define mmDCP0_REGAMMA_CNTLA_REGION_4_5                                         0x1aaa
#define mmDCP1_REGAMMA_CNTLA_REGION_4_5                                         0x1caa
#define mmDCP2_REGAMMA_CNTLA_REGION_4_5                                         0x1eaa
#define mmDCP3_REGAMMA_CNTLA_REGION_4_5                                         0x40aa
#define mmDCP4_REGAMMA_CNTLA_REGION_4_5                                         0x42aa
#define mmDCP5_REGAMMA_CNTLA_REGION_4_5                                         0x44aa
#define mmREGAMMA_CNTLA_REGION_6_7                                              0x1aab
#define mmDCP0_REGAMMA_CNTLA_REGION_6_7                                         0x1aab
#define mmDCP1_REGAMMA_CNTLA_REGION_6_7                                         0x1cab
#define mmDCP2_REGAMMA_CNTLA_REGION_6_7                                         0x1eab
#define mmDCP3_REGAMMA_CNTLA_REGION_6_7                                         0x40ab
#define mmDCP4_REGAMMA_CNTLA_REGION_6_7                                         0x42ab
#define mmDCP5_REGAMMA_CNTLA_REGION_6_7                                         0x44ab
#define mmREGAMMA_CNTLA_REGION_8_9                                              0x1aac
#define mmDCP0_REGAMMA_CNTLA_REGION_8_9                                         0x1aac
#define mmDCP1_REGAMMA_CNTLA_REGION_8_9                                         0x1cac
#define mmDCP2_REGAMMA_CNTLA_REGION_8_9                                         0x1eac
#define mmDCP3_REGAMMA_CNTLA_REGION_8_9                                         0x40ac
#define mmDCP4_REGAMMA_CNTLA_REGION_8_9                                         0x42ac
#define mmDCP5_REGAMMA_CNTLA_REGION_8_9                                         0x44ac
#define mmREGAMMA_CNTLA_REGION_10_11                                            0x1aad
#define mmDCP0_REGAMMA_CNTLA_REGION_10_11                                       0x1aad
#define mmDCP1_REGAMMA_CNTLA_REGION_10_11                                       0x1cad
#define mmDCP2_REGAMMA_CNTLA_REGION_10_11                                       0x1ead
#define mmDCP3_REGAMMA_CNTLA_REGION_10_11                                       0x40ad
#define mmDCP4_REGAMMA_CNTLA_REGION_10_11                                       0x42ad
#define mmDCP5_REGAMMA_CNTLA_REGION_10_11                                       0x44ad
#define mmREGAMMA_CNTLA_REGION_12_13                                            0x1aae
#define mmDCP0_REGAMMA_CNTLA_REGION_12_13                                       0x1aae
#define mmDCP1_REGAMMA_CNTLA_REGION_12_13                                       0x1cae
#define mmDCP2_REGAMMA_CNTLA_REGION_12_13                                       0x1eae
#define mmDCP3_REGAMMA_CNTLA_REGION_12_13                                       0x40ae
#define mmDCP4_REGAMMA_CNTLA_REGION_12_13                                       0x42ae
#define mmDCP5_REGAMMA_CNTLA_REGION_12_13                                       0x44ae
#define mmREGAMMA_CNTLA_REGION_14_15                                            0x1aaf
#define mmDCP0_REGAMMA_CNTLA_REGION_14_15                                       0x1aaf
#define mmDCP1_REGAMMA_CNTLA_REGION_14_15                                       0x1caf
#define mmDCP2_REGAMMA_CNTLA_REGION_14_15                                       0x1eaf
#define mmDCP3_REGAMMA_CNTLA_REGION_14_15                                       0x40af
#define mmDCP4_REGAMMA_CNTLA_REGION_14_15                                       0x42af
#define mmDCP5_REGAMMA_CNTLA_REGION_14_15                                       0x44af
#define mmREGAMMA_CNTLB_START_CNTL                                              0x1ab0
#define mmDCP0_REGAMMA_CNTLB_START_CNTL                                         0x1ab0
#define mmDCP1_REGAMMA_CNTLB_START_CNTL                                         0x1cb0
#define mmDCP2_REGAMMA_CNTLB_START_CNTL                                         0x1eb0
#define mmDCP3_REGAMMA_CNTLB_START_CNTL                                         0x40b0
#define mmDCP4_REGAMMA_CNTLB_START_CNTL                                         0x42b0
#define mmDCP5_REGAMMA_CNTLB_START_CNTL                                         0x44b0
#define mmREGAMMA_CNTLB_SLOPE_CNTL                                              0x1ab1
#define mmDCP0_REGAMMA_CNTLB_SLOPE_CNTL                                         0x1ab1
#define mmDCP1_REGAMMA_CNTLB_SLOPE_CNTL                                         0x1cb1
#define mmDCP2_REGAMMA_CNTLB_SLOPE_CNTL                                         0x1eb1
#define mmDCP3_REGAMMA_CNTLB_SLOPE_CNTL                                         0x40b1
#define mmDCP4_REGAMMA_CNTLB_SLOPE_CNTL                                         0x42b1
#define mmDCP5_REGAMMA_CNTLB_SLOPE_CNTL                                         0x44b1
#define mmREGAMMA_CNTLB_END_CNTL1                                               0x1ab2
#define mmDCP0_REGAMMA_CNTLB_END_CNTL1                                          0x1ab2
#define mmDCP1_REGAMMA_CNTLB_END_CNTL1                                          0x1cb2
#define mmDCP2_REGAMMA_CNTLB_END_CNTL1                                          0x1eb2
#define mmDCP3_REGAMMA_CNTLB_END_CNTL1                                          0x40b2
#define mmDCP4_REGAMMA_CNTLB_END_CNTL1                                          0x42b2
#define mmDCP5_REGAMMA_CNTLB_END_CNTL1                                          0x44b2
#define mmREGAMMA_CNTLB_END_CNTL2                                               0x1ab3
#define mmDCP0_REGAMMA_CNTLB_END_CNTL2                                          0x1ab3
#define mmDCP1_REGAMMA_CNTLB_END_CNTL2                                          0x1cb3
#define mmDCP2_REGAMMA_CNTLB_END_CNTL2                                          0x1eb3
#define mmDCP3_REGAMMA_CNTLB_END_CNTL2                                          0x40b3
#define mmDCP4_REGAMMA_CNTLB_END_CNTL2                                          0x42b3
#define mmDCP5_REGAMMA_CNTLB_END_CNTL2                                          0x44b3
#define mmREGAMMA_CNTLB_REGION_0_1                                              0x1ab4
#define mmDCP0_REGAMMA_CNTLB_REGION_0_1                                         0x1ab4
#define mmDCP1_REGAMMA_CNTLB_REGION_0_1                                         0x1cb4
#define mmDCP2_REGAMMA_CNTLB_REGION_0_1                                         0x1eb4
#define mmDCP3_REGAMMA_CNTLB_REGION_0_1                                         0x40b4
#define mmDCP4_REGAMMA_CNTLB_REGION_0_1                                         0x42b4
#define mmDCP5_REGAMMA_CNTLB_REGION_0_1                                         0x44b4
#define mmREGAMMA_CNTLB_REGION_2_3                                              0x1ab5
#define mmDCP0_REGAMMA_CNTLB_REGION_2_3                                         0x1ab5
#define mmDCP1_REGAMMA_CNTLB_REGION_2_3                                         0x1cb5
#define mmDCP2_REGAMMA_CNTLB_REGION_2_3                                         0x1eb5
#define mmDCP3_REGAMMA_CNTLB_REGION_2_3                                         0x40b5
#define mmDCP4_REGAMMA_CNTLB_REGION_2_3                                         0x42b5
#define mmDCP5_REGAMMA_CNTLB_REGION_2_3                                         0x44b5
#define mmREGAMMA_CNTLB_REGION_4_5                                              0x1ab6
#define mmDCP0_REGAMMA_CNTLB_REGION_4_5                                         0x1ab6
#define mmDCP1_REGAMMA_CNTLB_REGION_4_5                                         0x1cb6
#define mmDCP2_REGAMMA_CNTLB_REGION_4_5                                         0x1eb6
#define mmDCP3_REGAMMA_CNTLB_REGION_4_5                                         0x40b6
#define mmDCP4_REGAMMA_CNTLB_REGION_4_5                                         0x42b6
#define mmDCP5_REGAMMA_CNTLB_REGION_4_5                                         0x44b6
#define mmREGAMMA_CNTLB_REGION_6_7                                              0x1ab7
#define mmDCP0_REGAMMA_CNTLB_REGION_6_7                                         0x1ab7
#define mmDCP1_REGAMMA_CNTLB_REGION_6_7                                         0x1cb7
#define mmDCP2_REGAMMA_CNTLB_REGION_6_7                                         0x1eb7
#define mmDCP3_REGAMMA_CNTLB_REGION_6_7                                         0x40b7
#define mmDCP4_REGAMMA_CNTLB_REGION_6_7                                         0x42b7
#define mmDCP5_REGAMMA_CNTLB_REGION_6_7                                         0x44b7
#define mmREGAMMA_CNTLB_REGION_8_9                                              0x1ab8
#define mmDCP0_REGAMMA_CNTLB_REGION_8_9                                         0x1ab8
#define mmDCP1_REGAMMA_CNTLB_REGION_8_9                                         0x1cb8
#define mmDCP2_REGAMMA_CNTLB_REGION_8_9                                         0x1eb8
#define mmDCP3_REGAMMA_CNTLB_REGION_8_9                                         0x40b8
#define mmDCP4_REGAMMA_CNTLB_REGION_8_9                                         0x42b8
#define mmDCP5_REGAMMA_CNTLB_REGION_8_9                                         0x44b8
#define mmREGAMMA_CNTLB_REGION_10_11                                            0x1ab9
#define mmDCP0_REGAMMA_CNTLB_REGION_10_11                                       0x1ab9
#define mmDCP1_R