                                    0x4e10
#define mmDIG5_HDMI_GENERIC_PACKET_CONTROL0                                     0x4f10
#define mmDIG6_HDMI_GENERIC_PACKET_CONTROL0                                     0x5410
#define mmAFMT_INTERRUPT_STATUS                                                 0x4a11
#define mmDIG0_AFMT_INTERRUPT_STATUS                                            0x4a11
#define mmDIG1_AFMT_INTERRUPT_STATUS                                            0x4b11
#define mmDIG2_AFMT_INTERRUPT_STATUS                                            0x4c11
#define mmDIG3_AFMT_INTERRUPT_STATUS                                            0x4d11
#define mmDIG4_AFMT_INTERRUPT_STATUS                                            0x4e11
#define mmDIG5_AFMT_INTERRUPT_STATUS                                            0x4f11
#define mmDIG6_AFMT_INTERRUPT_STATUS                                            0x5411
#define mmHDMI_GC                                                               0x4a13
#define mmDIG0_HDMI_GC                                                          0x4a13
#define mmDIG1_HDMI_GC                                                          0x4b13
#define mmDIG2_HDMI_GC                                                          0x4c13
#define mmDIG3_HDMI_GC                                                          0x4d13
#define mmDIG4_HDMI_GC                                                          0x4e13
#define mmDIG5_HDMI_GC                                                          0x4f13
#define mmDIG6_HDMI_GC                                                          0x5413
#define mmAFMT_AUDIO_PACKET_CONTROL2                                            0x4a14
#define mmDIG0_AFMT_AUDIO_PACKET_CONTROL2                                       0x4a14
#define mmDIG1_AFMT_AUDIO_PACKET_CONTROL2                                       0x4b14
#define mmDIG2_AFMT_AUDIO_PACKET_CONTROL2                                       0x4c14
#define mmDIG3_AFMT_AUDIO_PACKET_CONTROL2                                       0x4d14
#define mmDIG4_AFMT_AUDIO_PACKET_CONTROL2                                       0x4e14
#define mmDIG5_AFMT_AUDIO_PACKET_CONTROL2                                       0x4f14
#define mmDIG6_AFMT_AUDIO_PACKET_CONTROL2                                       0x5414
#define mmAFMT_ISRC1_0                                                          0x4a15
#define mmDIG0_AFMT_ISRC1_0                                                     0x4a15
#define mmDIG1_AFMT_ISRC1_0                                                     0x4b15
#define mmDIG2_AFMT_ISRC1_0                                                     0x4c15
#define mmDIG3_AFMT_ISRC1_0                                                     0x4d15
#define mmDIG4_AFMT_ISRC1_0                                                     0x4e15
#define mmDIG5_AFMT_ISRC1_0                                                     0x4f15
#define mmDIG6_AFMT_ISRC1_0                                                     0x5415
#define mmAFMT_ISRC1_1                                                          0x4a16
#define mmDIG0_AFMT_ISRC1_1                                                     0x4a16
#define mmDIG1_AFMT_ISRC1_1                                                     0x4b16
#define mmDIG2_AFMT_ISRC1_1                                                     0x4c16
#define mmDIG3_AFMT_ISRC1_1                                                     0x4d16
#define mmDIG4_AFMT_ISRC1_1                                                     0x4e16
#define mmDIG5_AFMT_ISRC1_1                                                     0x4f16
#define mmDIG6_AFMT_ISRC1_1                                                     0x5416
#define mmAFMT_ISRC1_2                                                          0x4a17
#define mmDIG0_AFMT_ISRC1_2                                                     0x4a17
#define mmDIG1_AFMT_ISRC1_2                                                     0x4b17
#define mmDIG2_AFMT_ISRC1_2                                                     0x4c17
#define mmDIG3_AFMT_ISRC1_2                                                     0x4d17
#define mmDIG4_AFMT_ISRC1_2                                                     0x4e17
#define mmDIG5_AFMT_ISRC1_2                                                     0x4f17
#define mmDIG6_AFMT_ISRC1_2                                                     0x5417
#define mmAFMT_ISRC1_3                                                          0x4a18
#define mmDIG0_AFMT_ISRC1_3                                                     0x4a18
#define mmDIG1_AFMT_ISRC1_3                                                     0x4b18
#define mmDIG2_AFMT_ISRC1_3                                                     0x4c18
#define mmDIG3_AFMT_ISRC1_3                                                     0x4d18
#define mmDIG4_AFMT_ISRC1_3                                                     0x4e18
#define mmDIG5_AFMT_ISRC1_3                                                     0x4f18
#define mmDIG6_AFMT_ISRC1_3                                                     0x5418
#define mmAFMT_ISRC1_4                                                          0x4a19
#define mmDIG0_AFMT_ISRC1_4                                                     0x4a19
#define mmDIG1_AFMT_ISRC1_