mDMIF_PG6_DPG_PIPE_NB_PSTATE_CHANGE_CONTROL                            0x4736
#define mmDPG_PIPE_STUTTER_CONTROL_NONLPTCH                                     0x1b37
#define mmDMIF_PG0_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x1b37
#define mmDMIF_PG1_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x1d37
#define mmDMIF_PG2_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x1f37
#define mmDMIF_PG3_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4137
#define mmDMIF_PG4_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4337
#define mmDMIF_PG5_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4537
#define mmDMIF_PG6_DPG_PIPE_STUTTER_CONTROL_NONLPTCH                            0x4737
#define mmDPG_REPEATER_PROGRAM                                                  0x1b3a
#define mmDMIF_PG0_DPG_REPEATER_PROGRAM                                         0x1b3a
#define mmDMIF_PG1_DPG_REPEATER_PROGRAM                                         0x1d3a
#define mmDMIF_PG2_DPG_REPEATER_PROGRAM                                         0x1f3a
#define mmDMIF_PG3_DPG_REPEATER_PROGRAM                                         0x413a
#define mmDMIF_PG4_DPG_REPEATER_PROGRAM                                         0x433a
#define mmDMIF_PG5_DPG_REPEATER_PROGRAM                                         0x453a
#define mmDMIF_PG6_DPG_REPEATER_PROGRAM                                         0x473a
#define mmDPG_HW_DEBUG_A                                                        0x1b3b
#define mmDMIF_PG0_DPG_HW_DEBUG_A                                               0x1b3b
#define mmDMIF_PG1_DPG_HW_DEBUG_A                                               0x1d3b
#define mmDMIF_PG2_DPG_HW_DEBUG_A                                               0x1f3b
#define mmDMIF_PG3_DPG_HW_DEBUG_A                                               0x413b
#define mmDMIF_PG4_DPG_HW_DEBUG_A                                               0x433b
#define mmDMIF_PG5_DPG_HW_DEBUG_A                                               0x453b
#define mmDMIF_PG6_DPG_HW_DEBUG_A                                               0x473b
#define mmDPG_HW_DEBUG_B                                                        0x1b3c
#define mmDMIF_PG0_DPG_HW_DEBUG_B                                               0x1b3c
#define mmDMIF_PG1_DPG_HW_DEBUG_B                                               0x1d3c
#define mmDMIF_PG2_DPG_HW_DEBUG_B                                               0x1f3c
#define mmDMIF_PG3_DPG_HW_DEBUG_B                                               0x413c
#define mmDMIF_PG4_DPG_HW_DEBUG_B                                               0x433c
#define mmDMIF_PG5_DPG_HW_DEBUG_B                                               0x453c
#define mmDMIF_PG6_DPG_HW_DEBUG_B                                               0x473c
#define mmDPG_HW_DEBUG_11                                                       0x1b3d
#define mmDMIF_PG0_DPG_HW_DEBUG_11                                              0x1b3d
#define mmDMIF_PG1_DPG_HW_DEBUG_11                                              0x1d3d
#define mmDMIF_PG2_DPG_HW_DEBUG_11                                              0x1f3d
#define mmDMIF_PG3_DPG_HW_DEBUG_11                                              0x413d
#define mmDMIF_PG4_DPG_HW_DEBUG_11                                              0x433d
#define mmDMIF_PG5_DPG_HW_DEBUG_11                                              0x453d
#define mmDMIF_PG6_DPG_HW_DEBUG_11                                              0x473d
#define mmDPG_TEST_DEBUG_INDEX                                                  0x1b38
#define mmDMIF_PG0_DPG_TEST_DEBUG_INDEX                                         0x1b38
#define mmDMIF_PG1_DPG_TEST_DEBUG_INDEX                                         0x1d38
#define mmDMIF_PG2_DPG_TEST_DEBUG_INDEX                                         0x1f38
#define mmDMIF_PG3_DPG_TEST_DEBUG_INDEX                                         0x4138
#define mmDMIF_PG4_DPG_TEST_DEBUG_INDEX                                         0x4338
#define mmDMIF_PG5_DPG_TEST_DEBUG_INDEX                                         0x4538
#define mmDMIF_PG6_DPG_TEST_DEBUG_INDEX                                         0x4738
#define mmDPG_TEST_DEBUG_DATA                                                   0x1b39
#define mmDMIF_PG0_DPG_TEST_DEBUG_DATA                                          0x1b39
#define mmDMIF_PG1_DPG_TEST_DEBUG_DATA                                          0x1d39
#define mmDMIF_PG2_DPG_TEST_DEBUG_DATA                                          0x1f39
#define mmDMIF_PG3_DPG_TEST_DEBUG_DATA                                          0x4139
#define mmDMIF_PG4_DPG_TEST_DEBUG_DATA                                          0x4339
#define mmDMIF_PG5_DPG_TEST_DEBUG_DATA                                          0x4539
#define mmDMIF_PG6_DPG_TEST_DEBUG_DATA                                          0x4739
#define mmAZROOT_IMMEDIATE_COMMAND_OUTPUT_INTERFACE_INDEX                       0x18
#define mmAZROOT_IMMEDIATE_COMMAND_OUTPUT_INTERFACE_DATA                        0x18
#define ixAZALIA_F2_CODEC_ROOT_PARAMETER_VENDOR_AND_DEVICE_ID                   0xf00
#define ixAZALIA_F2_CODEC_ROOT_PARAMETER_REVISION_ID                            0xf02
#define ixAZALIA_F2_CODEC_ROOT_PARAMETER_SUBORDINATE_NODE_COUNT                 0xf04
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_SUBORDINATE_NODE_COUNT             0x1f04
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_GROUP_TYPE                         0x1f05
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_SUPPORTED_SIZE_RATES               0x1f0a
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_STREAM_FORMATS                     0x1f0b
#define ixAZALIA_F2_CODEC_FUNCTION_PARAMETER_POWER_STATES                       0x1f0f
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_POWER_STATE                          0x1705
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESET                                0x17ff
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID                0x1720
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID_2              0x1721
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID_3              0x1722
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID_4              0x1723
#define ixAZALIA_F2_CODEC_FUNCTION_CONTROL_CONVERTER_SYNCHRONIZATION            0x1770
#define mmAZALIA_F0_CODEC_ROOT_PARAMETER_VENDOR_AND_DEVICE_ID                   0x1828
#define mmAZALIA_F0_CODEC_ROOT_PARAMETER_REVISION_ID                            0x1829
#define mmAZALIA_F0_CODEC_CHANNEL_COUNT_CONTROL                                 0x182a
#define mmAZALIA_F0_CODEC_RESYNC_FIFO_CONTROL                                   0x182b
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_GROUP_TYPE                         0x182c
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_SUPPORTED_SIZE_RATES               0x182d
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_STREAM_FORMATS                     0x182e
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_POWER_STATES                       0x182f
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_POWER_STATE                          0x1830
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_RESET                                0x1831
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_RESPONSE_SUBSYSTEM_ID                0x1832
#define mmAZALIA_F0_CODEC_FUNCTION_CONTROL_CONVERTER_SYNCHRONIZATION            0x1833
#define mmCC_RCU_DC_AUDIO_PORT_CONNECTIVITY                                     0x1834
#define mmCC_RCU_DC_AUDIO_INPUT_PORT_CONNECTIVITY                               0x1835
#define mmAZALIA_F0_CODEC_DEBUG                                                 0x1836
#define mmAZALIA_F0_GTC_GROUP_OFFSET0                                           0x1837
#define mmAZALIA_F0_GTC_GROUP_OFFSET1                                           0x1838
#define mmAZALIA_F0_GTC_GROUP_OFFSET2                                           0x1839
#define mmAZALIA_F0_GTC_GROUP_OFFSET3                                           0x183a
#define mmAZALIA_F0_GTC_GROUP_OFFSET4                                           0x183b
#define mmAZALIA_F0_GTC_GROUP_OFFSET5                                           0x183c
#define mmAZALIA_F0_GTC_GROUP_OFFSET6                                           0x183d
#define mmGLOBAL_CAPABILITIES                                                   0x0
#define mmMINOR_VERSION                                                         0x0
#define mmMAJOR_VERSION                                                         0x0
#define mmOUTPUT_PAYLOAD_CAPABILITY                                             0x1
#define mmINPUT_PAYLOAD_CAPABILITY              