mmFMT5_FMT_CLAMP_CNTL                                                   0x45f9
#define mmFMT_CRC_CNTL                                                          0x1bfa
#define mmFMT0_FMT_CRC_CNTL                                                     0x1bfa
#define mmFMT1_FMT_CRC_CNTL                                                     0x1dfa
#define mmFMT2_FMT_CRC_CNTL                                                     0x1ffa
#define mmFMT3_FMT_CRC_CNTL                                                     0x41fa
#define mmFMT4_FMT_CRC_CNTL                                                     0x43fa
#define mmFMT5_FMT_CRC_CNTL                                                     0x45fa
#define mmFMT_CRC_SIG_RED_GREEN_MASK                                            0x1bfb
#define mmFMT0_FMT_CRC_SIG_RED_GREEN_MASK                                       0x1bfb
#define mmFMT1_FMT_CRC_SIG_RED_GREEN_MASK                                       0x1dfb
#define mmFMT2_FMT_CRC_SIG_RED_GREEN_MASK                                       0x1ffb
#define mmFMT3_FMT_CRC_SIG_RED_GREEN_MASK                                       0x41fb
#define mmFMT4_FMT_CRC_SIG_RED_GREEN_MASK                                       0x43fb
#define mmFMT5_FMT_CRC_SIG_RED_GREEN_MASK                                       0x45fb
#define mmFMT_CRC_SIG_BLUE_CONTROL_MASK                                         0x1bfc
#define mmFMT0_FMT_CRC_SIG_BLUE_CONTROL_MASK                                    0x1bfc
#define mmFMT1_FMT_CRC_SIG_BLUE_CONTROL_MASK                                    0x1dfc
#define mmFMT2_FMT_CRC_SIG_BLUE_CONTROL_MASK                                    0x1ffc
#define mmFMT3_FMT_CRC_SIG_BLUE_CONTROL_MASK                                    0x41fc
#define mmFMT4_FMT_CRC_SIG_BLUE_CONTROL_MASK                                    0x43fc
#define mmFMT5_FMT_CRC_SIG_BLUE_CONTROL_MASK                                    0x45fc
#define mmFMT_CRC_SIG_RED_GREEN                                                 0x1bfd
#define mmFMT0_FMT_CRC_SIG_RED_GREEN                                            0x1bfd
#define mmFMT1_FMT_CRC_SIG_RED_GREEN                                            0x1dfd
#define mmFMT2_FMT_CRC_SIG_RED_GREEN                                            0x1ffd
#define mmFMT3_FMT_CRC_SIG_RED_GREEN                                            0x41fd
#define mmFMT4_FMT_CRC_SIG_RED_GREEN                                            0x43fd
#define mmFMT5_FMT_CRC_SIG_RED_GREEN                                            0x45fd
#define mmFMT_CRC_SIG_BLUE_CONTROL                                              0x1bfe
#define mmFMT0_FMT_CRC_SIG_BLUE_CONTROL                                         0x1bfe
#define mmFMT1_FMT_CRC_SIG_BLUE_CONTROL                                         0x1dfe
#define mmFMT2_FMT_CRC_SIG_BLUE_CONTROL                                         0x1ffe
#define mmFMT3_FMT_CRC_SIG_BLUE_CONTROL                                         0x41fe
#define mmFMT4_FMT_CRC_SIG_BLUE_CONTROL                                         0x43fe
#define mmFMT5_FMT_CRC_SIG_BLUE_CONTROL                                         0x45fe
#define mmFMT_DEBUG_CNTL                                                        0x1bff
#define mmFMT0_FMT_DEBUG_CNTL                                                   0x1bff
#define mmFMT1_FMT_DEBUG_CNTL                                                   0x1dff
#define mmFMT2_FMT_DEBUG_CNTL                                                   0x1fff
#define mmFMT3_FMT_DEBUG_CNTL                                                   0x41ff
#define mmFMT4_FMT_DEBUG_CNTL                                                   0x43ff
#define mmFMT5_FMT_DEBUG_CNTL                                                   0x45ff
#define mmFMT_TEST_DEBUG_INDEX                                                  0x1beb
#define mmFMT0_FMT_TEST_DEBUG_INDEX                                             0x1beb
#define mmFMT1_FMT_TEST_DEBUG_INDEX                                             0x1deb
#define mmFMT2_FMT_TEST_DEBUG_INDEX                                             0x1feb
#define mmFMT3_FMT_TEST_DEBUG_INDEX                                             0x41eb
#define mmFMT4_FMT_TEST_DEBUG_INDEX                                             0x43eb
#define mmFMT5_FMT_TEST_DEBUG_INDEX                                             0x45eb
#define mmFMT_TEST_DEBUG_DATA                                                   0x1bec
#define mmFMT0_FMT_TEST_DEBUG_DATA                                              0x1bec
#define mmFMT1_FMT_TEST_DEBUG_DATA                                              0x1dec
#define mmFMT2_FMT_TEST_DEBUG_DATA                                              0x1fec
#define mmFMT3_FMT_TEST_DEBUG_DATA                                              0x41ec
#define mmFMT4_FMT_TEST_DEBUG_DATA                                              0x43ec
#define mmFMT5_FMT_TEST_DEBUG_DATA                                              0x45ec
#define ixFMT_DEBUG0                                                            0x1
#define ixFMT_DEBUG1                                                            0x2
#define ixFMT_DEBUG2                                                            0x3
#define ixFMT_DEBUG_ID                                                          0x0
#define mmLB_DATA_FORMAT                                                        0x1ac0
#define mmLB0_LB_DATA_FORMAT                                                    0x1ac0
#define mmLB1_LB_DATA_FORMAT                                                    0x1cc0
#define mmLB2_LB_DATA_FORMAT                                                    0x1ec0
#define mmLB3_LB_DATA_FORMAT                                                    0x40c0
#define mmLB4_LB_DATA_FORMAT                                                    0x42c0
#define mmLB5_LB_DATA_FORMAT                                                    0x44c0
#define mmLB_MEMORY_CTRL                                                        0x1ac1
#define mmLB0_LB_MEMORY_CTRL                                                    0x1ac1
#define mmLB1_LB_MEMORY_CTRL                                                    0x1cc1
#define mmLB2_LB_MEMORY_CTRL                                                    0x1ec1
#define mmLB3_LB_MEMORY_CTRL                                                    0x40c1
#define mmLB4_LB_MEMORY_CTRL                                                    0x42c1
#define mmLB5_LB_MEMORY_CTRL                                                    0x44c1
#define mmLB_MEMORY_SIZE_STATUS                                                 0x1ac2
#define mmLB0_LB_MEMORY_SIZE_STATUS                                             0x1ac2
#define mmLB1_LB_MEMORY_SIZE_STATUS                                             0x1cc2
#define mmLB2_LB_MEMORY_SIZE_STATUS                                             0x1ec2
#define mmLB3_LB_MEMORY_SIZE_STATUS                                             0x40c2
#define mmLB4_LB_MEMORY_SIZE_STATUS                                             0x42c2
#define mmLB5_LB_MEMORY_SIZE_STATUS                                             0x44c2
#define mmLB_DESKTOP_HEIGHT                                                     0x1ac3
#define mmLB0_LB_DESKTOP_HEIGHT                                                 0x1ac3
#define mmLB1_LB_DESKTOP_HEIGHT                                                 0x1cc3
#define mmLB2_LB_DESKTOP_HEIGHT                                                 0x1ec3
#define mmLB3_LB_DESKTOP_HEIGHT                                                 0x40c3
#define mmLB4_LB_DESKTOP_HEIGHT                                                 0x42c3
#define mmLB5_LB_DESKTOP_HEIGHT                                                 0x44c3
#define mmLB_VLINE_START_END                                                    0x1ac4
#define mmLB0_LB_VLINE_START_END                                                0x1ac4
#define mmLB1_LB_VLINE_START_END                                                0x1cc4
#define mmLB2_LB_VLINE_START_END                                                0x1ec4
#define mmLB3_LB_VLINE_START_END                                                0x40c4
#define mmLB4_LB_VLINE_START_END                                                0x42c4
#define mmLB5_LB_VLINE_START_END                                                0x44c4
#define mmLB_VLINE2_START_END                                                   0x1ac5
#define mmLB0_LB_VLINE2_START_END                                               0x1ac5
#define mmLB1_LB_VLINE2_START_END                                               0x1cc5
#define mmLB2_LB_VLINE2_START_END                                               0x1ec5
#define mmLB3_LB_VLINE2_START_END                                               0x40c5
#define mmLB4_LB_VLINE2_START_END                                               0x42c5
#define mmLB5_LB_VLINE2_START_END                                               0x44c5
#define mmLB_V_COUNTER                                                          0x1ac6
#define mmLB0_LB_V_COUNTER                                                      0x1ac6
#define mmLB1_LB_V_COUNTER                                                      0x1cc6
#define mmLB2_LB_V_COUNTER                                                      0x1ec6
#define mmLB3_LB_V_COUNTER                                                      0x40c6
#define mmLB4_LB_V_COUNTER                                                      0x42c6
#define mmLB5_LB_V_COUNTER                                                      0x44c6
#define mmLB_SNAPSHOT_V_COUNTER                                                 0x1ac7
#define mmLB0_LB_SNAPSHOT_V_COUNTER                                             0x1ac7
#define mmLB1_LB_SNAPSHOT_V_COUNTER                                             0x1cc7
#define mmLB2_LB_SNAPSHOT_V_COUNTER                                             0x1ec7
#define mmLB3_LB_SNAPSHOT_V_COUNTER                                             0x40c7
#define mmLB4_LB_SNAPSHOT_V_COUNTER                                             0x42c7
#define mmLB5_LB_SNAPSHOT_V_COUNTER                                             0x44c7
#define mmLB_INTERRUPT_MASK                                                     0x1ac8
#define mmLB0_LB_INTERRUPT_MASK                                                 0x1ac8
#define mmLB1_LB_INTERRUPT_MASK                                                 0x1cc8
#define mmLB2_LB_INTERRUPT_MASK                                                 0x1ec8
#define mmLB3_LB_INTERRUPT_MASK                                                 0x40c8
#define mmLB4_LB_INTERRUPT_MASK                                                 0x42c8
#define mmLB5_LB_INTERRUPT_MASK                                                 0x44c8
#define mmLB_VLINE_STATUS                                                       0x1ac9
#define mmLB0_LB_VLINE_STATUS                                                   0x1ac9
#define mmLB1_LB_VLINE_STATUS                                                   0x1cc9
#define mmLB2_LB_VLINE_STATUS                                                   0x1ec9
#define mmLB3_LB_VLINE_STATUS                                                   0x40c9
#define mmLB4_LB_VLINE_STATUS                                                   0x42c9
#define mmLB5_LB_VLINE_STATUS                                                   0x44c9
#define mmLB_VLINE2_STATUS                                                      0x1aca
#define mmLB0_LB_VLINE2_STATUS                                                  0x1aca
#define mmLB1_LB_VLINE2_STATUS                                                  0x1cca
#define mmLB2_LB_VLINE2_STATUS                                                  0x1eca
#define mmLB3_LB_VLINE2_STATUS                                                  0x40ca
#define mmLB4_LB_VLINE2_STATUS                                                  0x42ca
#define mmLB5_LB_VLINE2_STATUS                                                  0x44ca
#define mmLB_VBLANK_STATUS                                                      0x1acb
#define mmLB0_LB_VBLANK_STATUS                                                  0x1acb
#define mmLB1_LB_VBLANK_STATUS                                                  0x1ccb
#define mmLB2_LB_VBLANK_STATUS                                                  0x1ecb
#define mmLB3_LB_VBLANK_STATUS                                                  0x40cb
#define mmLB4_LB_VBLANK_STATUS                                                  0x42cb
#define mmLB5_LB_VBLANK_STATUS                                                  0x44cb
#define mmLB_SYNC_RESET_SEL                                                     0x1acc
#define mmLB0_LB_SYNC_RESET_SEL                                                 0x1acc
#define mmLB1_LB_SYNC_RESET_SEL                                                 0x1ccc
#define mmLB2_LB_SYNC_RESET_SEL                                                 0x1ecc
#define mmLB3_LB_SYNC_RESET_SEL                                                 0x40cc
#define mmLB4_LB_SYNC_RESET_SEL                                                 0x42cc
#define mmLB5_LB_SYNC_RESET_SEL                                                 0x44cc
#define mmLB_BLACK_KEYER_R_CR                                                   0x1acd
#define mmLB0_LB_BLACK_KEYER_R_CR                                               0x1acd
#define mmLB1_LB_BLACK_KEYER_R_CR                                               0x1ccd
#define mmLB2_LB_BLACK_KEYER_R_CR                                               0x1ecd
#define mmLB3_LB_BLACK_KEYER_R_CR                                               0x40cd
#define mmLB4_LB_BLACK_KEYER_R_CR                                               0x42cd
#define mmLB5_LB_BLACK_KEYER_R_CR                                               0x44cd
#define mmLB_BLACK_KEYER_G_Y                                                    0x1ace
#define mmLB0_LB_BLACK_KEYER_G_Y                                                0x1ace
#define mmLB1_LB_BLACK_KEYER_G_Y                                                0x1cce
#define mmLB2_LB_BLACK_KEYER_G_Y                                                0x1ece
#define mmLB3_LB_BLACK_KEYER_G_Y                                                0x40ce
#define mmLB4_LB_BLACK_KEYER_G_Y                                                0x42ce
#define mmLB5_LB_BLACK_KEYER_G_Y                                                0x44ce
#define mmLB_BLACK_KEYER_B_CB                                                   0x1acf
#define mmLB0_LB_BLACK_KEYER_B_CB                                               0x1acf
#define mmLB1_LB_BLACK_KEYER_B_CB                                               0x1ccf
#define mmLB2_LB_BLACK_KEYER_B_CB                                               0x1ecf
#define mmLB3_LB_BLACK_KEYER_B_CB                                               0x40cf
#define mmLB4_LB_BLACK_KEYER_B_CB                                               0x42cf
#define mmLB5_LB_BLACK_KEYER_B_CB                                               0x44cf
#define mmLB_KEYER_COLOR_CTRL                                                   0x1ad0
#define mmLB0_LB_KEYER_COLOR_CTRL                                               0x1ad0
#define mmLB1_LB_KEYER_COLOR_CTRL                                               0x1cd0
#define mmLB2_LB_KEYER_COLOR_CTRL                                               0x1ed0
#define mmLB3_LB_KEYER_COLOR_CTRL                                               0x40d0
#define mmLB4_LB_KEYER_COLOR_CTRL                                               0x42d0
#define mmLB5_LB_KEYER_COLOR_CTRL                                               0x44d0
#define mmLB_KEYER_COLOR_R_CR                                                   0x1ad1
#define mmLB0_LB_KEYER_COLOR_R_CR                                               0x1ad1
#define mmLB1_LB_KEYER_COLOR_R_CR                                               0x1cd1
#define mmLB2_LB_KEYER_COLOR_R_CR                                               0x1ed1
#define mmLB3_LB_KEYER_COLOR_R_CR                                               0x40d1
#define mmLB4_LB_KEYER_COLOR_R_CR                                               0x42d1
#define mmLB5_LB_KEYER_COLOR_R_CR                                               0x44d1
#define mmLB_KEYER_COLOR_G_Y                                                    0x1ad2
#define mmLB0_LB_KEYER_COLOR_G_Y                                                0x1ad2
#define mmLB1_LB_KEYER_COLOR_G_Y                                                0x1cd2
#define mmLB2_LB_KEYER_COLOR_G_Y                                                0x1ed2
#define mmLB3_LB_KEYER_COLOR_G_Y                                                0x40d2
#define mmLB4_LB_KEYER_COLOR_G_Y                                                0x42d2
#define mmLB5_LB_KEYER_COLOR_G_Y                                                0x44d2
#define mmLB_KEYER_COLOR_B_CB                                                   0x1ad3
#define mmLB0_LB_KEYER_COLOR_B_CB                                               0x1ad3
#define mmLB1_LB_KEYER_COLOR_B_CB                                               0x1cd3
#define mmLB2_LB_KEYER_COLOR_B_CB                                               0x1ed3
#define mmLB3_LB_KEYER_COLOR_B_CB                                               0x40d3
#define mmLB4_LB_KEYER_COLOR_B_CB                                               0x42d3
#define mmLB5_LB_KEYER_COLOR_B_CB                                               0x44d3
#define mmLB_KEYER_COLOR_REP_R_CR                                               0x1ad4
#define mmLB0_LB_KEYER_COLOR_REP_R_CR                                           0x1ad4
#define mmLB1_LB_KEYER_COLOR_REP_R_CR                                           0x1cd4
#define mmLB2_LB_KEYER_COLOR_REP_R_CR                                           0x1ed4
#define mmLB3_LB_KEYER_COLOR_REP_R_CR                                           0x40d4
#define mmLB4_LB_KEYER_COLOR_REP_R_CR                                           0x42d4
#define mmLB5_LB_KEYER_COLOR_REP_R_CR                                           0x44d4
#define mmLB_KEYER_COLOR_REP_G_Y                                                0x1ad5
#define mmLB0_LB_KEYER_COLOR_REP_G_Y                                            0x1ad5
#define mmLB1_LB_KEYER_COLOR_REP_G_Y                                            0x1cd5
#define mmLB2_LB_KEYER_COLOR_REP_G_Y                                            0x1ed5
#define mmLB3_LB_KEYER_COLOR_REP_G_Y                                            0x40d5
#define mmLB4_LB_KEYER_COLOR_REP_G_Y                                            0x42d5
#define mmLB5_LB_KEYER_COLOR_REP_G_Y                                            0x44d5
#define mmLB_KEYER_COLOR_REP_B_CB                                               0x1ad6
#define mmLB0_LB_KEYER_COLOR_REP_B_CB                                           0x1ad6
#define mmLB1_LB_KEYER_COLOR_REP_B_CB                                           0x1cd6
#define mmLB2_LB_KEYER_COLOR_REP_B_CB                                           0x1ed6
#define mmLB3_LB_KEYER_COLOR_REP_B_CB                                           0x40d6
#define mmLB4_LB_KEYER_COLOR_REP_B_CB                                           0x42d6
#define mmLB5_LB_KEYER_COLOR_REP_B_CB                                           0x44d6
#define mmLB_BUFFER_LEVEL_STATUS                                                0x1ad7
#define mmLB0_LB_BUFFER_LEVEL_STATUS                                            0x1ad7
#define mmLB1_LB_BUFFER_LEVEL_STATUS                                            0x1cd7
#define mmLB2_LB_BUFFER_LEVE