                         0x1fca
#define mmCRTC3_CRTC_BLANK_DATA_COLOR                                           0x41ca
#define mmCRTC4_CRTC_BLANK_DATA_COLOR                                           0x43ca
#define mmCRTC5_CRTC_BLANK_DATA_COLOR                                           0x45ca
#define mmCRTC6_CRTC_BLANK_DATA_COLOR                                           0x47ca
#define mmCRTC_BLANK_DATA_COLOR_EXT                                             0x1bcb
#define mmCRTC0_CRTC_BLANK_DATA_COLOR_EXT                                       0x1bcb
#define mmCRTC1_CRTC_BLANK_DATA_COLOR_EXT                                       0x1dcb
#define mmCRTC2_CRTC_BLANK_DATA_COLOR_EXT                                       0x1fcb
#define mmCRTC3_CRTC_BLANK_DATA_COLOR_EXT                                       0x41cb
#define mmCRTC4_CRTC_BLANK_DATA_COLOR_EXT                                       0x43cb
#define mmCRTC5_CRTC_BLANK_DATA_COLOR_EXT                                       0x45cb
#define mmCRTC6_CRTC_BLANK_DATA_COLOR_EXT                                       0x47cb
#define mmCRTC_BLACK_COLOR                                                      0x1bcc
#define mmCRTC0_CRTC_BLACK_COLOR                                                0x1bcc
#define mmCRTC1_CRTC_BLACK_COLOR                                                0x1dcc
#define mmCRTC2_CRTC_BLACK_COLOR                                                0x1fcc
#define mmCRTC3_CRTC_BLACK_COLOR                                                0x41cc
#define mmCRTC4_CRTC_BLACK_COLOR                                                0x43cc
#define mmCRTC5_CRTC_BLACK_COLOR                                                0x45cc
#define mmCRTC6_CRTC_BLACK_COLOR                                                0x47cc
#define mmCRTC_BLACK_COLOR_EXT                                                  0x1bcd
#define mmCRTC0_CRTC_BLACK_COLOR_EXT                                            0x1bcd
#define mmCRTC1_CRTC_BLACK_COLOR_EXT                                            0x1dcd
#define mmCRTC2_CRTC_BLACK_COLOR_EXT                                            0x1fcd
#define mmCRTC3_CRTC_BLACK_COLOR_EXT                                            0x41cd
#define mmCRTC4_CRTC_BLACK_COLOR_EXT                                            0x43cd
#define mmCRTC5_CRTC_BLACK_COLOR_EXT                                            0x45cd
#define mmCRTC6_CRTC_BLACK_COLOR_EXT                                            0x47cd
#define mmCRTC_VERTICAL_INTERRUPT0_POSITION                                     0x1bce
#define mmCRTC0_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x1bce
#define mmCRTC1_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x1dce
#define mmCRTC2_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x1fce
#define mmCRTC3_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x41ce
#define mmCRTC4_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x43ce
#define mmCRTC5_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x45ce
#define mmCRTC6_CRTC_VERTICAL_INTERRUPT0_POSITION                               0x47ce
#define mmCRTC_VERTICAL_INTERRUPT0_CONTROL                                      0x1bcf
#define mmCRTC0_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x1bcf
#define mmCRTC1_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x1dcf
#define mmCRTC2_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x1fcf
#define mmCRTC3_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x41cf
#define mmCRTC4_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x43cf
#define mmCRTC5_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x45cf
#define mmCRTC6_CRTC_VERTICAL_INTERRUPT0_CONTROL                                0x47cf
#define mmCRTC_VERTICAL_INTERRUPT1_POSITION                                     0x1bd0
#define mmCRTC0_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x1bd0
#define mmCRTC1_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x1dd0
#define mmCRTC2_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x1fd0
#define mmCRTC3_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x41d0
#define mmCRTC4_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x43d0
#define mmCRTC5_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x45d0
#define mmCRTC6_CRTC_VERTICAL_INTERRUPT1_POSITION                               0x47d0
#define mmCRTC_VERTICAL_INTERRUPT1_CONTROL                                      0x1bd1
#define mmCRTC0_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x1bd1
#define mmCRTC1_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x1dd1
#define mmCRTC2_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x1fd1
#define mmCRTC3_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x41d1
#define mmCRTC4_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x43d1
#define mmCRTC5_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x45d1
#define mmCRTC6_CRTC_VERTICAL_INTERRUPT1_CONTROL                                0x47d1
#define mmCRTC_VERTICAL_INTERRUPT2_POSITION                                     0x1bd2
#define mmCRTC0_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x1bd2
#define mmCRTC1_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x1dd2
#define mmCRTC2_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x1fd2
#define mmCRTC3_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x41d2
#define mmCRTC4_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x43d2
#define mmCRTC5_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x45d2
#define mmCRTC6_CRTC_VERTICAL_INTERRUPT2_POSITION                               0x47d2
#define mmCRTC_VERTICAL_INTERRUPT2_CONTROL                                      0x1bd3
#define mmCRTC0_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x1bd3
#define mmCRTC1_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x1dd3
#define mmCRTC2_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x1fd3
#define mmCRTC3_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x41d3
#define mmCRTC4_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x43d3
#define mmCRTC5_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x45d3
#define mmCRTC6_CRTC_VERTICAL_INTERRUPT2_CONTROL                                0x47d3
#define mmCRTC_CRC_CNTL                                                         0x1bd4
#define mmCRTC0_CRTC_CRC_CNTL                                                   0x1bd4
#define mmCRTC1_CRTC_CRC_CNTL                                                   0x1dd4
#define mmCRTC2_CRTC_CRC_CNTL                                                   0x1fd4
#define mmCRTC3_CRTC_CRC_CNTL                                                   0x41d4
#define mmCRTC4_CRTC_CRC_CNTL                                                   0x43d4
#define mmCRTC5_CRTC_CRC_CNTL                                                   0x45d4
#define mmCRTC6_CRTC_CRC_CNTL                                                   0x47d4
#define mmCRTC_CRC0_WINDOWA_X_CONTROL                                           0x1bd5
#define mmCRTC0_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x1bd5
#define mmCRTC1_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x1dd5
#define mmCRTC2_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x1fd5
#define mmCRTC3_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x41d5
#define mmCRTC4_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x43d5
#define mmCRTC5_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x45d5
#define mmCRTC6_CRTC_CRC0_WINDOWA_X_CONTROL                                     0x47d5
#define mmCRTC_CRC0_WINDOWA_Y_CONTROL                                           0x1bd6
#define mmCRTC0_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x1bd6
#define mmCRTC1_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x1dd6
#define mmCRTC2_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x1fd6
#define mmCRTC3_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x41d6
#define mmCRTC4_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x43d6
#define mmCRTC5_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x45d6
#define mmCRTC6_CRTC_CRC0_WINDOWA_Y_CONTROL                                     0x47d6
#define mmCRTC_CRC0_WINDOWB_X_CONTROL                                           0x1bd7
#define mmCRTC0_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x1bd7
#define mmCRTC1_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x1dd7
#define mmCRTC2_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x1fd7
#define mmCRTC3_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x41d7
#define mmCRTC4_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x43d7
#define mmCRTC5_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x45d7
#define mmCRTC6_CRTC_CRC0_WINDOWB_X_CONTROL                                     0x47d7
#define mmCRTC_CRC0_WINDOWB_Y_CONTROL                                           0x1bd8
#define mmCRTC0_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x1bd8
#define mmCRTC1_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x1dd8
#define mmCRTC2_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x1fd8
#define mmCRTC3_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x41d8
#define mmCRTC4_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x43d8
#define mmCRTC5_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x45d8
#define mmCRTC6_CRTC_CRC0_WINDOWB_Y_CONTROL                                     0x47d8
#define mmCRTC_CRC0_DATA_RG                                                     0x1bd9
#define mmCRTC0_CRTC_CRC0_DATA_RG                                               0x1bd9
#define mmCRTC1_CRTC_CRC0_DATA_RG                                               0x1dd9
#define mmCRTC2_CRTC_CRC0_DATA_RG                                               0x1fd9
#define mmCRTC3_CRTC_CRC0_DATA_RG                                               0x41d9
#define mmCRTC4_CRTC_CRC0_DATA_RG                                               0x43d9
#define mmCRTC5_CRTC_CRC0_DATA_RG                                               0x45d9
#define mmCRTC6_CRTC_CRC0_DATA_RG                                               0x47d9
#define mmCRTC_CRC0_DATA_B                                                      0x1bda
#define mmCRTC0_CRTC_CRC0_DATA_B                                                0x1bda
#define mmCRTC1_CRTC_CRC0_DATA_B                                                0x1dda
#define mmCRTC2_CRTC_CRC0_DATA_B                                                0x1fda
#define mmCRTC3_CRTC_CRC0_DATA_B                                                0x41da
#define mmCRTC4_CRTC_CRC0_DATA_B                                                0x43da
#define mmCRTC5_CRTC_CRC0_DATA_B                                                0x45da
#define mmCRTC6_CRTC_CRC0_DATA_B                                                0x47da
#define mmCRTC_CRC1_WINDOWA_X_CONTROL                                           0x1bdb
#define mmCRTC0_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x1bdb
#define mmCRTC1_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x1ddb
#define mmCRTC2_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x1fdb
#define mmCRTC3_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x41db
#define mmCRTC4_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x43db
#define mmCRTC5_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x45db
#define mmCRTC6_CRTC_CRC1_WINDOWA_X_CONTROL                                     0x47db
#define mmCRTC_CRC1_WINDOWA_Y_CONTROL                                           0x1bdc
#define mmCRTC0_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x1bdc
#define mmCRTC1_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x1ddc
#define mmCRTC2_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x1fdc
#define mmCRTC3_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x41dc
#define mmCRTC4_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x43dc
#define mmCRTC5_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x45dc
#define mmCRTC6_CRTC_CRC1_WINDOWA_Y_CONTROL                                     0x47dc
#define mmCRTC_CRC1_WINDOWB_X_CONTROL                                           0x1bdd
#define mmCRTC0_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x1bdd
#define mmCRTC1_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x1ddd
#define mmCRTC2_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x1fdd
#define mmCRTC3_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x41dd
#define mmCRTC4_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x43dd
#define mmCRTC5_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x45dd
#define mmCRTC6_CRTC_CRC1_WINDOWB_X_CONTROL                                     0x47dd
#define mmCRTC_CRC1_WINDOWB_Y_CONTROL                                           0x1bde
#define mmCRTC0_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x1bde
#define mmCRTC1_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x1dde
#define mmCRTC2_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x1fde
#define mmCRTC3_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x41de
#define mmCRTC4_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x43de
#define mmCRTC5_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x45de
#define mmCRTC6_CRTC_CRC1_WINDOWB_Y_CONTROL                                     0x47de
#define mmCRTC_CRC1_DATA_RG                                                     0x1bdf
#define mmCRTC0_CRTC_CRC1_DATA_RG                                               0x1bdf
#define mmCRTC1_CRTC_CRC1_DATA_RG                                               0x1ddf
#define mmCRTC2_CRTC_CRC1_DATA_RG                                               0x1fdf
#define mmCRTC3_CRTC_CRC1_DATA_RG                                               0x41df
#define mmCRTC4_CRTC_CRC1_DATA_RG                                               0x43df
#define mmCRTC5_CRTC_CRC1_DATA_RG                                               0x45df
#define mmCRTC6_CRTC_CRC1_DATA_RG                                               0x47df
#define mmCRTC_CRC1_DATA_B                                                      0x1be0
#define mmCRTC0_CRTC_CRC1_DATA_B                                                0x1be0
#define mmCRTC1_CRTC_CRC1_DATA_B                                                0x1de0
#define mmCRTC2_CRTC_CRC1_DATA_B                                                0x1fe0
#define mmCRTC3_CRTC_CRC1_DATA_B                                                0x41e0
#define mmCRTC4_CRTC_CRC1_DATA_B                                                0x43e0
#define mmCRTC5_CRTC_CRC1_DATA_B                                                0x45e0
#define mmCRTC6_CRTC_CRC1_DATA_B                                                0x47e0
#define mmCRTC_EXT_TIMING_SYNC_CONTROL                                          0x1be1
#define mmCRTC0_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x1be1
#define mmCRTC1_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x1de1
#define mmCRTC2_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x1fe1
#define mmCRTC3_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x41e1
#define mmCRTC4_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x43e1
#define mmCRTC5_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x45e1
#define mmCRTC6_CRTC_EXT_TIMING_SYNC_CONTROL                                    0x47e1
#define mmCRTC_EXT_TIMING_SYNC_WINDOW_START                                     0x1be2
#define mmCRTC0_CRTC_EXT_TIMING_SYNC_WINDOW_START                               0x1be2
#define mmCRTC1_CRTC_EXT_TIMING_SYNC_WINDOW_START                               0x1de2
#define mmCRTC2_CRTC_EXT_TIMING_SYNC_WINDOW_START                               0x1fe2
#define mmCRTC3_CRTC_EXT_TIMING_SYNC_WINDOW_START                               0x41e2
#define mmCRTC4_CRTC_EXT_TIMING_SYNC_WINDOW_START                               0x43e2
#define