 0x1f90
#define mmCRTC3_CRTC_V_SYNC_B                                                   0x4190
#define mmCRTC4_CRTC_V_SYNC_B                                                   0x4390
#define mmCRTC5_CRTC_V_SYNC_B                                                   0x4590
#define mmCRTC6_CRTC_V_SYNC_B                                                   0x4790
#define mmCRTC_V_SYNC_B_CNTL                                                    0x1b91
#define mmCRTC0_CRTC_V_SYNC_B_CNTL                                              0x1b91
#define mmCRTC1_CRTC_V_SYNC_B_CNTL                                              0x1d91
#define mmCRTC2_CRTC_V_SYNC_B_CNTL                                              0x1f91
#define mmCRTC3_CRTC_V_SYNC_B_CNTL                                              0x4191
#define mmCRTC4_CRTC_V_SYNC_B_CNTL                                              0x4391
#define mmCRTC5_CRTC_V_SYNC_B_CNTL                                              0x4591
#define mmCRTC6_CRTC_V_SYNC_B_CNTL                                              0x4791
#define mmCRTC_DTMTEST_CNTL                                                     0x1b92
#define mmCRTC0_CRTC_DTMTEST_CNTL                                               0x1b92
#define mmCRTC1_CRTC_DTMTEST_CNTL                                               0x1d92
#define mmCRTC2_CRTC_DTMTEST_CNTL                                               0x1f92
#define mmCRTC3_CRTC_DTMTEST_CNTL                                               0x4192
#define mmCRTC4_CRTC_DTMTEST_CNTL                                               0x4392
#define mmCRTC5_CRTC_DTMTEST_CNTL                                               0x4592
#define mmCRTC6_CRTC_DTMTEST_CNTL                                               0x4792
#define mmCRTC_DTMTEST_STATUS_POSITION                                          0x1b93
#define mmCRTC0_CRTC_DTMTEST_STATUS_POSITION                                    0x1b93
#define mmCRTC1_CRTC_DTMTEST_STATUS_POSITION                                    0x1d93
#define mmCRTC2_CRTC_DTMTEST_STATUS_POSITION                                    0x1f93
#define mmCRTC3_CRTC_DTMTEST_STATUS_POSITION                                    0x4193
#define mmCRTC4_CRTC_DTMTEST_STATUS_POSITION                                    0x4393
#define mmCRTC5_CRTC_DTMTEST_STATUS_POSITION                                    0x4593
#define mmCRTC6_CRTC_DTMTEST_STATUS_POSITION                                    0x4793
#define mmCRTC_TRIGA_CNTL                                                       0x1b94
#define mmCRTC0_CRTC_TRIGA_CNTL                                                 0x1b94
#define mmCRTC1_CRTC_TRIGA_CNTL                                                 0x1d94
#define mmCRTC2_CRTC_TRIGA_CNTL                                                 0x1f94
#define mmCRTC3_CRTC_TRIGA_CNTL                                                 0x4194
#define mmCRTC4_CRTC_TRIGA_CNTL                                                 0x4394
#define mmCRTC5_CRTC_TRIGA_CNTL                                                 0x4594
#define mmCRTC6_CRTC_TRIGA_CNTL                                                 0x4794
#define mmCRTC_TRIGA_MANUAL_TRIG                                                0x1b95
#define mmCRTC0_CRTC_TRIGA_MANUAL_TRIG                                          0x1b95
#define mmCRTC1_CRTC_TRIGA_MANUAL_TRIG                                          0x1d95
#define mmCRTC2_CRTC_TRIGA_MANUAL_TRIG                                          0x1f95
#define mmCRTC3_CRTC_TRIGA_MANUAL_TRIG                                          0x4195
#define mmCRTC4_CRTC_TRIGA_MANUAL_TRIG                                          0x4395
#define mmCRTC5_CRTC_TRIGA_MANUAL_TRIG                                          0x4595
#define mmCRTC6_CRTC_TRIGA_MANUAL_TRIG                                          0x4795
#define mmCRTC_TRIGB_CNTL                                                       0x1b96
#define mmCRTC0_CRTC_TRIGB_CNTL                                                 0x1b96
#define mmCRTC1_CRTC_TRIGB_CNTL                                                 0x1d96
#define mmCRTC2_CRTC_TRIGB_CNTL                                                 0x1f96
#define mmCRTC3_CRTC_TRIGB_CNTL                                                 0x4196
#define mmCRTC4_CRTC_TRIGB_CNTL                                                 0x4396
#define mmCRTC5_CRTC_TRIGB_CNTL                                                 0x4596
#define mmCRTC6_CRTC_TRIGB_CNTL                                                 0x4796
#define mmCRTC_TRIGB_MANUAL_TRIG                                                0x1b97
#define mmCRTC0_CRTC_TRIGB_MANUAL_TRIG                                          0x1b97
#define mmCRTC1_CRTC_TRIGB_MANUAL_TRIG                                          0x1d97
#define mmCRTC2_CRTC_TRIGB_MANUAL_TRIG                                          0x1f97
#define mmCRTC3_CRTC_TRIGB_MANUAL_TRIG                                          0x4197
#define mmCRTC4_CRTC_TRIGB_MANUAL_TRIG                                          0x4397
#define mmCRTC5_CRTC_TRIGB_MANUAL_TRIG                                          0x4597
#define mmCRTC6_CRTC_TRIGB_MANUAL_TRIG                                          0x4797
#define mmCRTC_FORCE_COUNT_NOW_CNTL                                             0x1b98
#define mmCRTC0_CRTC_FORCE_COUNT_NOW_CNTL                                       0x1b98
#define mmCRTC1_CRTC_FORCE_COUNT_NOW_CNTL                                       0x1d98
#define mmCRTC2_CRTC_FORCE_COUNT_NOW_CNTL                                       0x1f98
#define mmCRTC3_CRTC_FORCE_COUNT_NOW_CNTL                                       0x4198
#define mmCRTC4_CRTC_FORCE_COUNT_NOW_CNTL                                       0x4398
#define mmCRTC5_CRTC_FORCE_COUNT_NOW_CNTL                                       0x4598
#define mmCRTC6_CRTC_FORCE_COUNT_NOW_CNTL                                       0x4798
#define mmCRTC_FLOW_CONTROL                                                     0x1b99
#define mmCRTC0_CRTC_FLOW_CONTROL                                               0x1b99
#define mmCRTC1_CRTC_FLOW_CONTROL                                               0x1d99
#define mmCRTC2_CRTC_FLOW_CONTROL                                               0x1f99
#define mmCRTC3_CRTC_FLOW_CONTROL                                               0x4199
#define mmCRTC4_CRTC_FLOW_CONTROL                                               0x4399
#define mmCRTC5_CRTC_FLOW_CONTROL                                               0x4599
#define mmCRTC6_CRTC_FLOW_CONTROL                                               0x4799
#define mmCRTC_STEREO_FORCE_NEXT_EYE                                            0x1b9a
#define mmCRTC0_CRTC_STEREO_FORCE_NEXT_EYE                                      0x1b9a
#define mmCRTC1_CRTC_STEREO_FORCE_NEXT_EYE                                      0x1d9a
#define mmCRTC2_CRTC_STEREO_FORCE_NEXT_EYE                                      0x1f9a
#define mmCRTC3_CRTC_STEREO_FORCE_NEXT_EYE                                      0x419a
#define mmCRTC4_CRTC_STEREO_FORCE_NEXT_EYE                                      0x439a
#define mmCRTC5_CRTC_STEREO_FORCE_NEXT_EYE                                      0x459a
#define mmCRTC6_CRTC_STEREO_FORCE_NEXT_EYE                                      0x479a
#define mmCRTC_AVSYNC_COUNTER                                                   0x1b9b
#define mmCRTC0_CRTC_AVSYNC_COUNTER                                             0x1b9b
#define mmCRTC1_CRTC_AVSYNC_COUNTER                                             0x1d9b
#define mmCRTC2_CRTC_AVSYNC_COUNTER                                             0x1f9b
#define mmCRTC3_CRTC_AVSYNC_COUNTER                                             0x419b
#define mmCRTC4_CRTC_AVSYNC_COUNTER                                             0x439b
#define mmCRTC5_CRTC_AVSYNC_COUNTER                                             0x459b
#define mmCRTC6_CRTC_AVSYNC_COUNTER                                             0x479b
#define mmCRTC_CONTROL                                                          0x1b9c
#define mmCRTC0_CRTC_CONTROL                                                    0x1b9c
#define mmCRTC1_CRTC_CONTROL                                                    0x1d9c
#define mmCRTC2_CRTC_CONTROL                                                    0x1f9c
#define mmCRTC3_CRTC_CONTROL                                                    0x419c
#define mmCRTC4_CRTC_CONTROL                                                    0x439c
#define mmCRTC5_CRTC_CONTROL                                                    0x459c
#define mmCRTC6_CRTC_CONTROL                                                    0x479c
#define mmCRTC_BLANK_CONTROL                                                    0x1b9d
#define mmCRTC0_CRTC_BLANK_CONTROL                                              0x1b9d
#define mmCRTC1_CRTC_BLANK_CONTROL                                              0x1d9d
#define mmCRTC2_CRTC_BLANK_CONTROL                                              0x1f9d
#define mmCRTC3_CRTC_BLANK_CONTROL                                              0x419d
#define mmCRTC4_CRTC_BLANK_CONTROL                                              0x439d
#define mmCRTC5_CRTC_BLANK_CONTROL                                              0x459d
#define mmCRTC6_CRTC_BLANK_CONTROL                                              0x479d
#define mmCRTC_INTERLACE_CONTROL                                                0x1b9e
#define mmCRTC0_CRTC_INTERLACE_CONTROL                                          0x1b9e
#define mmCRTC1_CRTC_INTERLACE_CONTROL                                          0x1d9e
#define mmCRTC2_CRTC_INTERLACE_CONTROL                                          0x1f9e
#define mmCRTC3_CRTC_INTERLACE_CONTROL                                          0x419e
#define mmCRTC4_CRTC_INTERLACE_CONTROL                                          0x439e
#define mmCRTC5_CRTC_INTERLACE_CONTROL                                          0x459e
#define mmCRTC6_CRTC_INTERLACE_CONTROL                                          0x479e
#define mmCRTC_INTERLACE_STATUS                                                 0x1b9f
#define mmCRTC0_CRTC_INTERLACE_STATUS                                           0x1b9f
#define mmCRTC1_CRTC_INTERLACE_STATUS                                           0x1d9f
#define mmCRTC2_CRTC_INTERLACE_STATUS                                           0x1f9f
#define mmCRTC3_CRTC_INTERLACE_STATUS                                           0x419f
#define mmCRTC4_CRTC_INTERLACE_STATUS                                           0x439f
#define mmCRTC5_CRTC_INTERLACE_STATUS                                           0x459f
#define mmCRTC6_CRTC_INTERLACE_STATUS                                           0x479f
#define mmCRTC_FIELD_INDICATION_CONTROL                                         0x1ba0
#define mmCRTC0_CRTC_FIELD_INDICATION_CONTROL                                   0x1ba0
#define mmCRTC1_CRTC_FIELD_INDICATION_CONTROL                                   0x1da0
#define mmCRTC2_CRTC_FIELD_INDICATION_CONTROL                                   0x1fa0
#define mmCRTC3_CRTC_FIELD_INDICATION_CONTROL                                   0x41a0
#define mmCRTC4_CRTC_FIELD_INDICATION_CONTROL                                   0x43a0
#define mmCRTC5_CRTC_FIELD_INDICATION_CONTROL                                   0x45a0
#define mmCRTC6_CRTC_FIELD_INDICATION_CONTROL                                   0x47a0
#define mmCRTC_PIXEL_DATA_READBACK0                                             0x1ba1
#define mmCRTC0_CRTC_PIXEL_DATA_READBACK0                                       0x1ba1
#define mmCRTC1_CRTC_PIXEL_DATA_READBACK0                                       0x1da1
#define mmCRTC2_CRTC_PIXEL_DATA_READBACK0                                       0x1fa1
#define mmCRTC3_CRTC_PIXEL_DATA_READBACK0                                       0x41a1
#define mmCRTC4_CRTC_PIXEL_DATA_READBACK0                                       0x43a1
#define mmCRTC5_CRTC_PIXEL_DATA_READBACK0                                       0x45a1
#define mmCRTC6_CRTC_PIXEL_DATA_READBACK0                                       0x47a1
#define mmCRTC_PIXEL_DATA_READBACK1                                             0x1ba2
#define mmCRTC0_CRTC_PIXEL_DATA_READBACK1                                       0x1ba2
#define mmCRTC1_CRTC_PIXEL_DATA_READBACK1                                       0x1da2
#define mmCRTC2_CRTC_PIXEL_DATA_READBACK1                                       0x1fa2
#define mmCRTC3_CRTC_PIXEL_DATA_READBACK1                                       0x41a2
#define mmCRTC4_CRTC_PIXEL_DATA_READBACK1                                       0x43a2
#define mmCRTC5_CRTC_PIXEL_DATA_READBACK1                                       0x45a2
#define mmCRTC6_CRTC_PIXEL_DATA_READBACK1                                       0x47a2
#define mmCRTC_STATUS                                                           0x1ba3
#define mmCRTC0_CRTC_STATUS                                                     0x1ba3
#define mmCRTC1_CRTC_STATUS                                                     0x1da3
#define mmCRTC2_CRTC_STATUS                                                     0x1fa3
#define mmCRTC3_CRTC_STATUS                                                     0x41a3
#define mmCRTC4_CRTC_STATUS                                                     0x43a3
#define mmCRTC5_CRTC_STATUS                                                     0x45a3
#define mmCRTC6_CRTC_STATUS                                                     0x47a3
#define mmCRTC_STATUS_POSITION                                                  0x1ba4
#define mmCRTC0_CRTC_STATUS_POSITION                                            0x1ba4
#define mmCRTC1_CRTC_STATUS_POSITION                                            0x1da4
#define mmCRTC2_CRTC_STATUS_POSITION                                            0x1fa4
#define mmCRTC3_CRTC_STATUS_POSITION                                            0x41a4
#define mmCRTC4_CRTC_STATUS_POSITION                                            0x43a4
#define mmCRTC5_CRTC_STATUS_POSITION                                            0x45a4
#define mmCRTC6_CRTC_STATUS_POSITION                                            0x47a4
#define mmCRTC_NOM_VERT_POSITION                                                0x1ba5
#define mmCRTC0_CRTC_NOM_VERT_POSITION                                          0x1ba5
#define mmCRTC1_CRTC_NOM_VERT_POSITION                                          0x1da5
#define mmCRTC2_CRTC_NOM_VERT_POSITION                                          0x1fa5
#define mmCRTC3_CRTC_NOM_VERT_POSITION                                          0x41a5
#define mmCRTC4_CRTC_NOM_VERT_POSITION                                          0x43a5
#define mmCRTC5_CRTC_NOM_VERT_POSITION                                          0x45a5
#define mmCRTC6_CRTC_NOM_VERT_POSITION                                          0x47a5
#define mmCRTC_STATUS_FRAME_COUNT                                               0x1ba6
#define mmCRTC0_CRTC_STATUS_FRAME_COUNT                                         0x1ba6
#define mmCRTC1_CRTC_STATUS_FRAME_COUNT                                         0x1da6
#define mmCRTC2_CRTC_STATUS_FRAME_COUNT                                         0x1fa6
#define mmCRTC3_CRTC_STATUS_FRAME_COUNT                                         0x41a6
#define mmCRTC4_CRTC_STATUS_FRAME_COUNT                                         0x43a6
#define mmCRTC5_CRTC_STATUS_FRAME_COUNT                                         0x45a6
#define mmCRTC6_CRTC_STATUS_FRAME_COUNT                                         0x47a6
#define mmCRTC_STATUS_VF_COUNT                                                  0x1ba7
#define mmCRTC0_CRTC_STATUS_VF_COUNT                                            0x1ba7
#define mmCRTC1_CRTC_STATUS_VF_COUNT                                            0x1da7
#define mmCRTC2_CRTC_STATUS_VF_COUNT                                            0x1fa7
#define mmCRTC3_CRTC_STATUS_VF_COUNT                                            0x41a7
#define mmCRTC4_CRTC_STATUS_VF_COUNT                                            0x43a7
#define mmCRTC5_CRTC_STATUS_VF_COUNT                                            0x45a7
#define mmCRTC6_CRTC_STATUS_VF_COUNT                                            0x47a7
#define mmCRTC_STATUS_HV_COUNT                                                  0x1ba8
#define mmCRTC0_CRTC_STATUS_HV_COUNT                                            0x1ba8
#define mmCRTC1_CRTC_STATUS_HV_COUNT                                            0x1da8
#define mmCRTC2_CRTC_STATUS_HV_COUNT                                            0x1fa8
#define mmCRTC3_CRTC_STATUS_HV_COUNT                                            0x41a8
#define mmCRTC4_CRTC_STATUS_HV_COUNT                                            0x43a8
#define mmCRTC5_CRTC_STATUS_HV_COUNT                                            0x45a8
#define mmCRTC6_CRTC_STATUS_HV_COUNT                                            0x47a8
#define mmCRTC_COUNT_CONTROL                                                    0x1ba9
#define mmCRTC0_CRTC_COUNT_CONTROL                                              0x1ba9
#define mmCRTC1_CRTC_COUNT_CONTROL                                              0x1da9
#define mmCRTC2_CRTC_COUNT_CONTROL                                              0x1fa9
#define mmCRTC3_CRTC_COUNT_CONTROL                                              0x41a9
#define mmCRTC4_CRTC_COUNT_CONTROL                                              0x43a9
#define mmCRTC5_CRTC_COUNT_CONTROL                                              0x45a9
#define mmCRTC6_CRTC_COUNT_CONTROL                                              0x47a9
#define mmCRTC_COUNT_RESET                                                      0x1baa
#define mmCRTC0_CRTC_COUNT_RESET                                                0x1baa
#define mmCRTC1_CRTC_COUNT_RESET                                                0x1daa
#define mmCRTC2_CRTC_COUNT_RESET                                                0x1faa
#define mmCRTC3_CRTC_COUNT_RESET                                                0x41aa
#define mmCRTC4_CRTC_COUNT_RESET                                                0x43aa
#define mmCRTC5_CRTC_COUNT_RESET                                                0x45aa
#define mmCRTC6_CRTC_COUNT_RESET                                                0x47aa
#define mmCRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                                     0x1bab
#define mmCRTC0_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x1bab
#define mmCRTC1_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x1dab
#define mmCRTC2_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x1fab
#define mmCRTC3_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x41ab
#define mmCRTC4_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x43ab
#define mmCRTC5_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x45ab
#define mmCRTC6_CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE                               0x47ab
#define mmCRTC_VERT_SYNC_CONTROL                                                0x1bac
#define mmCRTC0_CRTC_VERT_SYNC_CONTROL                                          0x1bac
#define mmCRTC1_CRTC_VERT_SYNC_CONTROL                                          0x1dac
#define mmCRTC2_CRTC_VERT_SYNC_CONTROL                                          0x1fac
#define mmCRTC3_CRTC_VERT_SYNC_CONTROL                                          0x41ac
#define mmCRTC4_CRTC_VERT_SYNC_CONTROL                                          0x43ac
#define mmCRTC5_CRTC_VERT_SYNC_CONTROL                                          0x45ac
#define mmCRTC6_CRTC_VERT_SYNC_CONTROL                                          0x47ac
#define mmCRTC_STEREO_STATUS                                                    0x1bad
#define mmCRTC0_CRTC_STEREO_STATUS                                              0x1bad
#define mmCRTC1_CRTC_STEREO_STATUS                                              0x1dad
#define mmCRTC2_CRTC_STEREO_STATUS                                              0x1fad
#define mmCRTC3_CRTC_STEREO_STATUS                                              0x41ad
#define mmCRTC4_CRTC_STEREO_STATUS                                              0x43ad
#define mmCRTC5_CRTC_STEREO_STATUS                                              0x45ad
#define mmCRTC6_CRTC_STEREO_STATUS                                              0x47ad
#define mmCRTC_STEREO_CONTROL                                                   0x1bae
#define mmCRTC0_CRTC_STEREO_CONTROL                                             0x1bae
#define mmCRTC1_CRTC_STEREO_CONTROL                                             0x1dae
#define mmCRTC2_CRTC_STEREO_CONTROL                                             0x1fae
#define mmCRTC3_CRTC_STEREO_CONTROL                                             0x41ae
#define mmCRTC4_CRTC_STEREO_CONTROL                                             0x43ae
#define mmCRTC5_CRTC_STEREO_CONTROL                                             0x45ae
#define mmCRTC6_CRTC_STEREO_CONTROL                                             0x47ae
#define mmCRTC_SNAPSHOT_STATUS                                                  0x1baf
#define mmCRTC0_CRTC_SNAPSHOT_STATUS                                            0x1baf
#define mmCRTC1_CRTC_SNAPSHOT_STATUS                                            0x1daf
#define mmCRTC2_CRTC_SNAPSHOT_STATUS                                            0x1faf
#define mmCRTC3_CRTC_SNAPSHOT_STATUS                                            0x41af
#define mmCRTC4_CRTC_SNAPSHOT_STATUS                                            0x43af
#define mmCRTC5_CRTC_SNAPSHOT_STATUS                                            0x45af
#define mmCRTC6_CRTC_SNAPSHOT_STATUS                                            0x47af
#define mmCRTC_SNAPSHOT_CONTROL                                                 0x1bb0
#define mmCRTC0_CRTC_SNAPSHOT_CONTROL                                           0x1bb0
#define mmCRTC1_CRTC_SNAPSHOT_CONTROL                                           0x1db0
#define mmCRTC2_CRTC_SNAPSHOT_CONTROL                                           0x1fb0
#define mmCRTC3_CRTC_SNAPSHOT_CONTROL                                           0x41b0
#define mmCRTC4_CRTC_SNAPSHOT_CONTROL                                           0x43b0
#define mmCRTC5_CRTC_SNAPSHOT_CONTROL                                           0x45b0
#define mmCRTC6_CRTC_SNAPSHOT_CONTROL                                           0x47b0
#define mmCRTC_SNAPSHOT_POSITION                                                0x1bb1
#define mmCRTC0_CRTC_SNAPSHOT_POSITION                                          0x1bb1
#define mmCRTC1_CRTC_SNAPSHOT_POSITION                                          0x1db1
#define mmCRTC2_CRTC_SNAPSHOT_POSITION                                          0x1fb1
#define mmCRTC3_CRTC_SNAPSHOT_POSITION                                          0x41b1
#define mmCRTC4_CRTC_SNAPSHOT_POSITION                                          0x43b1
#define mmCRTC5_CRTC_SNAPSHOT_POSITION                                          0x45b1
#define mmCRTC6_CRTC_SNAPSHOT_POSITION                                          0x47b1
#define mmCRTC_SNAPSHOT_FRAME                                                   0x1bb2
#define mmCRTC0_CRTC_SNAPSHOT_FRAME                                             0x1bb2
#define mmCRTC1_CRTC_SNAPSHOT_FRAME                                             0x1db2
#define mmCRTC2_CRTC_SNAPSHOT_FRAME                                             0x1fb2
#define mmCRTC3_CRTC_SNAPSHOT_FRAME                                             0x41b2
#define mmCRTC4_CRTC_SNAPSHOT_FRAME                                             0x43b2
#define mmCRTC5_CRTC_SNAPSHOT_FRAME                                             0x45b2
#define mmCRTC6_CRTC_SNAPSHOT_FRAME                                             0x47b2
#define mmCRTC_START_LINE_CONTROL                                               0x1bb3
#define mmCRTC0_CRTC_START_LINE_CONTROL                                         0x1bb3
#define mmCRTC1_CRTC_START_LINE_CONTROL                                         0x1db3
#define mmCRTC2_CRTC_START_LINE_CONTROL                                         0x1fb3
#define mmCRTC3_CRTC_START_LINE_CONTROL                                         0x41b3
#define mmCRTC4_CRTC_START_LINE_CONTROL                                         0x43b3
#define mmCRTC5_CRTC_START_LINE_CONTROL                                         0x45b3
#define mmCRTC6_CRTC_START_LINE_CONTROL                                         0x47b3
#define mmCRTC_INTERRUPT_CONTROL                                                0x1bb4
#define mmCRTC0_CRTC_INTERRUPT_CONTROL                                          0x1bb4
#define mmCRTC1_CRTC_INTERRUPT_CONTROL                                          0x1db4
#define mmCRTC2_CRTC_INTERRUPT_CONTROL                                          0x1fb4
#define mmCRTC3_CRTC_INTERRUPT_CONTROL                                          0x41b4
#define mmCRTC4_CRTC_INTERRUPT_CONTROL                                          0x43b4
#define mmCRTC5_CRTC_INTERRUPT_CONTROL                                          0x45b4
#define mmCRTC6_CRTC_INTERRUPT_CONTROL                                          0x47b4
#define mmCRTC_UPDATE_LOCK                                                      0x1bb5
#define mmCRTC0_CRTC_UPDATE_LOCK                                                0x1bb5
#define mmCRTC1_CRTC_UPDATE_LOCK                                                0x1db5
#define mmCRTC2_CRTC_UPDATE_LOCK                                                0x1fb5
#define mmCRTC3_CRTC_UPDATE_LOCK                                                0x41b5
#define mmCRTC4_CRTC_UPDATE_LOCK                                                0x43b5
#define mmCRTC5_CRTC_UPDATE_LOCK                                                0x45b5
#define mmCRTC6_CRTC_UPDATE_LOCK                                                0x47b5
#define mmCRTC_DOUBLE_BUFFER_CONTROL                                            0x1bb6
#define mmCRTC0_CRTC_DOUBLE_BUFFER_CONTROL                                      0x1bb6
#define mmCRTC1_CRTC_DOUBLE_BUFFER_CONTROL                                      0x1db6
#define mmCRTC2_CRTC_DOUBLE_BUFFER_CONTROL                                      0x1fb6
#define mmCRTC3_CRTC_DOUBLE_BUFFER_CONTROL                                      0x41b6
#define mmCRTC4_CRTC_DOUBLE_BUFFER_CONTROL                                      0x43b6
#define mmCRTC5_CRTC_DOUBLE_BUFFER_CONTROL                                      0x45b6
#define mmCRTC6_CRTC_DOUBLE_BUFFER_CONTROL                                      0x47b6
#define mmCRTC_VGA_PARAMETER_CAPTURE_MODE                                       0x1bb7
#define mmCRTC0_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x1bb7
#define mmCRTC1_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x1db7
#define mmCRTC2_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x1fb7
#define mmCRTC3_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x41b7
#define mmCRTC4_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x43b7
#define mmCRTC5_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x45b7
#define mmCRTC6_CRTC_VGA_PARAMETER_CAPTURE_MODE                                 0x47b7
#define mmCRTC_TEST_PATTERN_CONTROL                                             0x1bba
#define mmCRTC0_CRTC_TEST_PATTERN_CONTROL                                       0x1bba
#define mmCRTC1_CRTC_TEST_PATTERN_CONTROL                                       0x1dba
#define mmCRTC2_CRTC_TEST_PATTERN_CONTROL                                       0x1fba
#define mmCRTC3_CRTC_TEST_PATTERN_CONTROL                                       0x41ba
#define mmCRTC4_CRTC_TEST_PATTERN_CONTROL                                       0x43ba
#define mmCRTC5_CRTC_TEST_PATTERN_CONTROL                                       0x45ba
#define mmCRTC6_CRTC_TEST_PATTERN_CONTROL                                       0x47ba
#define mmCRTC_TEST_PATTERN_PARAMETERS                                          0x1bbb
#define mmCRTC0_CRTC_TEST_PATTERN_PARAMETERS                                    0x1bbb
#define mmCRTC1_CRTC_TEST_PATTERN_PARAMETERS                                    0x1dbb
#define mmCRTC2_CRTC_TEST_PATTERN_PARAMETERS                                    0x1fbb
#define mmCRTC3_CRTC_TEST_PATTERN_PARAMETERS                                    0x41bb
#define mmCRTC4_CRTC_TEST_PATTERN_PARAMETERS                                    0x43bb
#define mmCRTC5_CRTC_TEST_PATTERN_PARAMETERS                                    0x45bb
#define mmCRTC6_CRTC_TEST_PATTERN_PARAMETERS                                    0x47bb
#define mmCRTC_TEST_PATTERN_COLOR                                               0x1bbc
#define mmCRTC0_CRTC_TEST_PATTERN_COLOR                                         0x1bbc
#define mmCRTC1_CRTC_TEST_PATTERN_COLOR                                         0x1dbc
#define mmCRTC2_CRTC_TEST_PATTERN_COLOR                                         0x1fbc
#define mmCRTC3_CRTC_TEST_PATTERN_COLOR                                         0x41bc
#define mmCRTC4_CRTC_TEST_PATTERN_COLOR                                         0x43bc
#define mmCRTC5_CRTC_TEST_PATTERN_COLOR                                         0x45bc
#define mmCRTC6_CRTC_TEST_PATTERN_COLOR                                         0x47bc
#define mmMASTER_UPDATE_LOCK                                                    0x1bbd
#define mmCRTC0_MASTER_UPDATE_LOCK                                              0x1bbd
#define mmCRTC1_MASTER_UPDATE_LOCK                                              0x1dbd
#define mmCRTC2_MASTER_UPDATE_LOCK                                              0x1fbd
#define mmCRTC3_MASTER_UPDATE_LOCK                                              0x41bd
#define mmCRTC4_MASTER_UPDATE_LOCK                                              0x43bd
#define mmCRTC5_MASTER_UPDATE_LOCK                                              0x45bd
#define mmCRTC6_MASTER_UPDATE_LOCK                                              0x47bd
#define mmMASTER_UPDATE_MODE                                                    0x1bbe
#define mmCRTC0_MASTER_UPDATE_MODE                                              0x1bbe
#define mmCRTC1_MASTER_UPDATE_MODE                                              0x1dbe
#define mmCRTC2_MASTER_UPDATE_MODE                                              0x1fbe
#define mmCRTC3_MASTER_UPDATE_MODE                                              0x41be
#define mmCRTC4_MASTER_UPDATE_MODE                                              0x43be
#define mmCRTC5_MASTER_UPDATE_MODE                                              0x45be
#define mmCRTC6_MASTER_UPDATE_MODE                                              0x47be
#define mmCRTC_MVP_INBAND_CNTL_INSERT                                           0x1bbf
#define mmCRTC0_CRTC_MVP_INBAND_CNTL_INSERT                              