                              0x4020
#define mmDCP4_OVL_SURFACE_ADDRESS                                              0x4220
#define mmDCP5_OVL_SURFACE_ADDRESS                                              0x4420
#define mmOVL_PITCH                                                             0x1a21
#define mmDCP0_OVL_PITCH                                                        0x1a21
#define mmDCP1_OVL_PITCH                                                        0x1c21
#define mmDCP2_OVL_PITCH                                                        0x1e21
#define mmDCP3_OVL_PITCH                                                        0x4021
#define mmDCP4_OVL_PITCH                                                        0x4221
#define mmDCP5_OVL_PITCH                                                        0x4421
#define mmOVL_SURFACE_ADDRESS_HIGH                                              0x1a22
#define mmDCP0_OVL_SURFACE_ADDRESS_HIGH                                         0x1a22
#define mmDCP1_OVL_SURFACE_ADDRESS_HIGH                                         0x1c22
#define mmDCP2_OVL_SURFACE_ADDRESS_HIGH                                         0x1e22
#define mmDCP3_OVL_SURFACE_ADDRESS_HIGH                                         0x4022
#define mmDCP4_OVL_SURFACE_ADDRESS_HIGH                                         0x4222
#define mmDCP5_OVL_SURFACE_ADDRESS_HIGH                                         0x4422
#define mmOVL_SURFACE_OFFSET_X                                                  0x1a23
#define mmDCP0_OVL_SURFACE_OFFSET_X                                             0x1a23
#define mmDCP1_OVL_SURFACE_OFFSET_X                                             0x1c23
#define mmDCP2_OVL_SURFACE_OFFSET_X                                             0x1e23
#define mmDCP3_OVL_SURFACE_OFFSET_X                                             0x4023
#define mmDCP4_OVL_SURFACE_OFFSET_X                                             0x4223
#define mmDCP5_OVL_SURFACE_OFFSET_X                                             0x4423
#define mmOVL_SURFACE_OFFSET_Y                                                  0x1a24
#define mmDCP0_OVL_SURFACE_OFFSET_Y                                             0x1a24
#define mmDCP1_OVL_SURFACE_OFFSET_Y                                             0x1c24
#define mmDCP2_OVL_SURFACE_OFFSET_Y                                             0x1e24
#define mmDCP3_OVL_SURFACE_OFFSET_Y                                             0x4024
#define mmDCP4_OVL_SURFACE_OFFSET_Y                                             0x4224
#define mmDCP5_OVL_SURFACE_OFFSET_Y                                             0x4424
#define mmOVL_START                                                             0x1a25
#define mmDCP0_OVL_START                                                        0x1a25
#define mmDCP1_OVL_START                                                        0x1c25
#define mmDCP2_OVL_START                                                        0x1e25
#define mmDCP3_OVL_START                                                        0x4025
#define mmDCP4_OVL_START                                                        0x4225
#define mmDCP5_OVL_START                                                        0x4425
#define mmOVL_END                                                               0x1a26
#define mmDCP0_OVL_END                                                          0x1a26
#define mmDCP1_OVL_END                                                          0x1c26
#define mmDCP2_OVL_END                                                          0x1e26
#define mmDCP3_OVL_END                                                          0x4026
#define mmDCP4_OVL_END                                                          0x4226
#define mmDCP5_OVL_END                                                          0x4426
#define mmOVL_UPDATE                                                            0x1a27
#define mmDCP0_OVL_UPDATE                                                       0x1a27
#define mmDCP1_OVL_UPDATE                                                       0x1c27
#define mmDCP2_OVL_UPDATE                                                       0x1e27
#define mmDCP3_OVL_UPDATE                                                       0x4027
#define mmDCP4_OVL_UPDATE                                                       0x4227
#define mmDCP5_OVL_UPDATE                                                       0x4427
#define mmOVL_SURFACE_ADDRESS_INUSE                                             0x1a28
#define mmDCP0_OVL_SURFACE_ADDRESS_INUSE                                        0x1a28
#define mmDCP1_OVL_SURFACE_ADDRESS_INUSE                                        0x1c28
#define mmDCP2_OVL_SURFACE_ADDRESS_INUSE                                        0x1e28
#define mmDCP3_OVL_SURFACE_ADDRESS_INUSE                                        0x4028
#define mmDCP4_OVL_SURFACE_ADDRESS_INUSE                                        0x4228
#define mmDCP5_OVL_SURFACE_ADDRESS_INUSE                                        0x4428
#define mmOVL_DFQ_CONTROL                                                       0x1a29
#define mmDCP0_OVL_DFQ_CONTROL                                                  0x1a29
#define mmDCP1_OVL_DFQ_CONTROL                                  