                         0x44d8
#define mmLB_BUFFER_URGENCY_STATUS                                              0x1ad9
#define mmLB0_LB_BUFFER_URGENCY_STATUS                                          0x1ad9
#define mmLB1_LB_BUFFER_URGENCY_STATUS                                          0x1cd9
#define mmLB2_LB_BUFFER_URGENCY_STATUS                                          0x1ed9
#define mmLB3_LB_BUFFER_URGENCY_STATUS                                          0x40d9
#define mmLB4_LB_BUFFER_URGENCY_STATUS                                          0x42d9
#define mmLB5_LB_BUFFER_URGENCY_STATUS                                          0x44d9
#define mmLB_BUFFER_STATUS                                                      0x1ada
#define mmLB0_LB_BUFFER_STATUS                                                  0x1ada
#define mmLB1_LB_BUFFER_STATUS                                                  0x1cda
#define mmLB2_LB_BUFFER_STATUS                                                  0x1eda
#define mmLB3_LB_BUFFER_STATUS                                                  0x40da
#define mmLB4_LB_BUFFER_STATUS                                                  0x42da
#define mmLB5_LB_BUFFER_STATUS                                                  0x44da
#define mmLB_NO_OUTSTANDING_REQ_STATUS                                          0x1adc
#define mmLB0_LB_NO_OUTSTANDING_REQ_STATUS                                      0x1adc
#define mmLB1_LB_NO_OUTSTANDING_REQ_STATUS                                      0x1cdc
#define mmLB2_LB_NO_OUTSTANDING_REQ_STATUS                                      0x1edc
#define mmLB3_LB_NO_OUTSTANDING_REQ_STATUS                                      0x40dc
#define mmLB4_LB_NO_OUTSTANDING_REQ_STATUS                                      0x42dc
#define mmLB5_LB_NO_OUTSTANDING_REQ_STATUS                                      0x44dc
#define mmMVP_AFR_FLIP_MODE                                                     0x1ae0
#define mmLB0_MVP_AFR_FLIP_MODE                                                 0x1ae0
#define mmLB1_MVP_AFR_FLIP_MODE                                                 0x1ce0
#define mmLB2_MVP_AFR_FLIP_MODE                                                 0x1ee0
#define mmLB3_MVP_AFR_FLIP_MODE                                                 0x40e0
#define mmLB4_MVP_AFR_FLIP_MODE                                                 0x42e0
#define mmLB5_MVP_AFR_FLIP_MODE                                                 0x44e0
#define mmMVP_AFR_FLIP_FIFO_CNTL                                                0x1ae1
#define mmLB0_MVP_AFR_FLIP_FIFO_CNTL                                            0x1ae1
#define mmLB1_MVP_AFR_FLIP_FIFO_CNTL                                            0x1ce1
#define mmLB2_MVP_AFR_FLIP_FIFO_CNTL                                            0x1ee1
#define mmLB3_MVP_AFR_FLIP_FIFO_CNTL                                            0x40e1
#define mmLB4_MVP_AFR_FLIP_FIFO_CNTL                                            0x42e1
#define mmLB5_MVP_AFR_FLIP_FIFO_CNTL                                            0x44e1
#define mmMVP_FLIP_LINE_NUM_INSERT                                              0x1ae2
#define mmLB0_MVP_FLIP_LINE_NUM_INSERT                                          0x1ae2
#define mmLB1_MVP_FLIP_LINE_NUM_INSERT                                          0x1ce2
#define mmLB2_MVP_FLIP_LINE_NUM_INSERT                                          0x1ee2
#define mmLB3_MVP_FLIP_LINE_NUM_INSERT                                          0x40e2
#define mmLB4_MVP_FLIP_LINE_NUM_INSERT                                          0x42e2
#define mmLB5_MVP_FLIP_LINE_NUM_INSERT                                          0x44e2
#define mmDC_MVP_LB_CONTROL                                                     0x1ae3
#define mmLB0_DC_MVP_LB_CONTROL                                                 0x1ae3
#define mmLB1_DC_MVP_LB_CONTROL                                                 0x1ce3
#define mmLB2_DC_MVP_LB_CONTROL                                                 0x1ee3
#define mmLB3_DC_MVP_LB_CONTROL                                                 0x40e3
#define mmLB4_DC_MVP_LB_CONTROL                                                 0x42e3
#define mmLB5_DC_MVP_LB_CONTROL                                                 0x44e3
#define mmLB_DEBUG                                                              0x1ae4
#define mmLB0_LB_DEBUG                                                          0x1ae4
#define mmLB1_LB_DEBUG                                                          0x1ce4
#define mmLB2_LB_DEBUG                                                          0x1ee4
#define mmLB3_LB_DEBUG                                                          0x40e4
#define mmLB4_LB_DEBUG                                                          0x42e4
#define mmLB5_LB_DEBUG                                                          0x44e4
#define mmLB_DEBUG2                                                             0x1ae5
#define mmLB0_LB_DEBUG2                                                         0x1ae5
#define mmLB1_LB_DEBUG2                                                         0x1ce5
#define mmLB2_LB_DEBUG2                                                         0x1ee5
#define mmLB3_LB_DEBUG2                                                         0x40e5
#define mmLB4_LB_DEBUG2                                                   