
#define mmHDMI_ACR_STATUS_1                                                     0x4a35
#define mmDIG0_HDMI_ACR_STATUS_1                                                0x4a35
#define mmDIG1_HDMI_ACR_STATUS_1                                                0x4b35
#define mmDIG2_HDMI_ACR_STATUS_1                                                0x4c35
#define mmDIG3_HDMI_ACR_STATUS_1                                                0x4d35
#define mmDIG4_HDMI_ACR_STATUS_1                                                0x4e35
#define mmDIG5_HDMI_ACR_STATUS_1                                                0x4f35
#define mmDIG6_HDMI_ACR_STATUS_1                                                0x5435
#define mmAFMT_AUDIO_INFO0                                                      0x4a36
#define mmDIG0_AFMT_AUDIO_INFO0                                                 0x4a36
#define mmDIG1_AFMT_AUDIO_INFO0                                                 0x4b36
#define mmDIG2_AFMT_AUDIO_INFO0                                                 0x4c36
#define mmDIG3_AFMT_AUDIO_INFO0                                                 0x4d36
#define mmDIG4_AFMT_AUDIO_INFO0                                                 0x4e36
#define mmDIG5_AFMT_AUDIO_INFO0                                                 0x4f36
#define mmDIG6_AFMT_AUDIO_INFO0                                                 0x5436
#define mmAFMT_AUDIO_INFO1                                                      0x4a37
#define mmDIG0_AFMT_AUDIO_INFO1                                                 0x4a37
#define mmDIG1_AFMT_AUDIO_INFO1                                                 0x4b37
#define mmDIG2_AFMT_AUDIO_INFO1                                                 0x4c37
#define mmDIG3_AFMT_AUDIO_INFO1                                                 0x4d37
#define mmDIG4_AFMT_AUDIO_INFO1                                                 0x4e37
#define mmDIG5_AFMT_AUDIO_INFO1                                                 0x4f37
#define mmDIG6_AFMT_AUDIO_INFO1                                                 0x5437
#define mmAFMT_60958_0                                                          0x4a38
#define mmDIG0_AFMT_60958_0                                                     0x4a38
#define mmDIG1_AFMT_60958_0                                                     0x4b38
#define mmDIG2_AFMT_60958_0                                                     0x4c38
#define mmDIG3_AFMT_60958_0                                                     0x4d38
#define mmDIG4_AFMT_60958_0                                                     0x4e38
#define mmDIG5_AFMT_60958_0                                                     0x4f38
#define mmDIG6_AFMT_60958_0                                                     0x5438
#define mmAFMT_60958_1                                                          0x4a39
#define mmDIG0_AFMT_60958_1                                                     0x4a39
#define mmDIG1_AFMT_60958_1                                                     0x4b39
#define mmDIG2_AFMT_60958_1                                                     0x4c39
#define mmDIG3_AFMT_60958_1                                                     0x4d39
#define mmDIG4_AFMT_60958_1                                                     0x4e39
#define mmDIG5_AFMT_60958_1                                                     0x4f39
#define mmDIG6_AFMT_60958_1                                                     0x5439
#define mmAFMT_AUDIO_CRC_CONTROL                                                0x4a3a
#define mmDIG0_AFMT_AUDIO_CRC_CONTROL                                           0x4a3a
#define mmDIG1_AFMT_AUDIO_CRC_CONTROL                                           0x4b3a
#define mmDIG2_AFMT_AUDIO_CRC_CONTROL                                           0x4c3a
#define mmDIG3_AFMT_AUDIO_CRC_CONTROL                                           0x4d3a
#define mmDIG4_AFMT_AUDIO_CRC_CONTROL                                           0x4e3a
#define mmDIG5_AFMT_AUDIO_CRC_CONTROL                                           0x4f3a
#define mmDIG6_AFMT_AUDIO_CRC_CONTROL                                           0x543a
#define mmAFMT_RAMP_CONTROL0                                                    0x4a3b
#define mmDIG0_AFMT_RAMP_CONTROL0                                               0x4a3b
#define mmDIG1_AFMT_RAMP_CONTROL0                                               0x4b3b
#define mmDIG2_AFMT_RAMP_CONTROL0                                               0x4c3b
#define mmDIG3_AFMT_RAMP_CONTROL0                                               0x4d3b
#define mmDIG4_AFMT_RAMP_CONTROL0                                               0x4e3b
#define mmDIG5_AFMT_RAMP_CONTROL0                                               0x4f3b
#define mmDIG6_AFMT_RAMP_CONTROL0                                               0x543b
#define mmAFMT_RAMP_CONTROL1                                                    0x4a3c
#define mmDIG0_AFMT_RAMP_CONTROL1                                               0x4a3c
#define mmDIG1_AFMT_RAMP_CONTROL1                                               0x4b3c
#define mmDIG2_AFMT_RAMP_CONTROL1                                               0x4c3c
#define mmDIG3_AFMT_RAMP_CONTROL1                                               0x4d3c
#define mmDIG4_AFMT_RAMP_CONTROL1                                               0x4e3c
#define mmDIG5_AFMT_RAMP_CONTROL1                                               0x4f3c
#define mmDIG6_AFMT_RAMP_CONTROL1                                               0x543c
#define mmAFMT_RAMP_CONTROL2                                                    0x4a3d
#define mmDIG0_AFMT_RAMP_CONTROL2                                               0x4a3d
#define mmDIG1_AFMT_RAMP_CONTROL2                                               0x4b3d
#define mmDIG2_AFMT_RAMP_CONTROL2                                               0x4c3d
#define mmDIG3_AFMT_RAMP_CONTROL2                                               0x4d3d
#define mmDIG4_AFMT_RAMP_CONTROL2                                               0x4e3d
#define mmDIG5_AFMT_RAMP_CONTROL2                                               0x4f3d
#define mmDIG6_AFMT_RAMP_CONTROL2                                               0x543d
#define mmAFMT_RAMP_CONTROL3                                                    0x4a3e
#define mmDIG0_AFMT_RAMP_CONTROL3                                               0x4a3e
#define mmDIG1_AFMT_RAMP_CONTROL3                                               0x4b3e
#define mmDIG2_AFMT_RAMP_CONTROL3                                               0x4c3e
#define mmDIG3_AFMT_RAMP_CONTROL3                                               0x4d3e
#define mmDIG4_AFMT_RAMP_CONTROL3                                               0x4e3e
#define mmDIG5_AFMT_RAMP_CONTROL3                                               0x4f3e
#define mmDIG6_AFMT_RAMP_CONTROL3                                               0x543e
#define mmAFMT_60958_2                                                          0x4a3f
#define mmDIG0_AFMT_60958_2                                                     0x4a3f
#define mmDIG1_AFMT_60958_2                                                     0x4b3f
#define mmDIG2_AFMT_60958_2                                                     0x4c3f
#define mmDIG3_AFMT_60958_2                                                     0x4d3f
#define mmDIG4_AFMT_60958_2                                                     0x4e3f
#define mmDIG5_AFMT_60958_2                                                     0x4f3f
#define mmDIG6_AFMT_60958_2                                                     0x543f
#define mmAFMT_AUDIO_CRC_RESULT                                                 0x4a40
#define mmDIG0_AFMT_AUDIO_CRC_RESULT                                            0x4a40
#define mmDIG1_AFMT_AUDIO_CRC_RESULT                                            0x4b40
#define mmDIG2_AFMT_AUDIO_CRC_RESULT                                            0x4c40
#define mmDIG3_AFMT_AUDIO_CRC_RESULT                                            0x4d40
#define mmDIG4_AFMT_AUDIO_CRC_RESULT                                            0x4e40
#define mmDIG5_AFMT_AUDIO_CRC_RESULT                                            0x4f40
#define mmDIG6_AFMT_AUDIO_CRC_RESULT                                            0x5440
#define mmAFMT_STATUS                                                           0x4a41
#define mmDIG0_AFMT_STATUS                                                      0x4a41
#define mmDIG1_AFMT_STATUS                                                      0x4b41
#define mmDIG2_AFMT_STATUS                                                      0x4c41
#define mmDIG3_AFMT_STATUS                                                      0x4d41
#define mmDIG4_AFMT_STATUS                                                      0x4e41
#define mmDIG5_AFMT_STATUS                                                      0x4f41
#define mmDIG6_AFMT_STATUS                                                      0x5441
#define mmAFMT_AUDIO_PACKET_CONTROL                                             0x4a42
#define mmDIG0_AFMT_AUDIO_PACKET_CONTROL                                        0x4a42
#define mmDIG1_AFMT_AUDIO_PACKET_CONTROL                                        0x4b42
#define mmDIG2_AFMT_AUDIO_PACKET_CONTROL                    