                                         0x5a8a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED7                                         0x5a8b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED8                                         0x5a8c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED9                                         0x5a8d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED10                                        0x5a8e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED11                                        0x5a8f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED12                                        0x5a90
#define mmDCRX_PHY_MACRO_CNTL_RESERVED13                                        0x5a91
#define mmDCRX_PHY_MACRO_CNTL_RESERVED14                                        0x5a92
#define mmDCRX_PHY_MACRO_CNTL_RESERVED15                                        0x5a93
#define mmDCRX_PHY_MACRO_CNTL_RESERVED16                                        0x5a94
#define mmDCRX_PHY_MACRO_CNTL_RESERVED17                                        0x5a95
#define mmDCRX_PHY_MACRO_CNTL_RESERVED18                                        0x5a96
#define mmDCRX_PHY_MACRO_CNTL_RESERVED19                                        0x5a97
#define mmDCRX_PHY_MACRO_CNTL_RESERVED20                                        0x5a98
#define mmDCRX_PHY_MACRO_CNTL_RESERVED21                                        0x5a99
#define mmDCRX_PHY_MACRO_CNTL_RESERVED22                                        0x5a9a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED23                                        0x5a9b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED24                                        0x5a9c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED25                                        0x5a9d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED26                                        0x5a9e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED27                                        0x5a9f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED28                                        0x5aa0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED29                                        0x5aa1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED30                                        0x5aa2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED31                                        0x5aa3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED32                                        0x5aa4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED33                                        0x5aa5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED34                                        0x5aa6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED35                                        0x5aa7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED36                                        0x5aa8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED37                                        0x5aa9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED38                                        0x5aaa
#define mmDCRX_PHY_MACRO_CNTL_RESERVED39                                        0x5aab
#define mmDCRX_PHY_MACRO_CNTL_RESERVED40                                        0x5aac
#define mmDCRX_PHY_MACRO_CNTL_RESERVED41                                        0x5aad
#define mmDCRX_PHY_MACRO_CNTL_RESERVED42                                        0x5aae
#define mmDCRX_PHY_MACRO_CNTL_RESERVED43                                        0x5aaf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED44                                        0x5ab0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED45                                        0x5ab1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED46                                        0x5ab2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED47                                        0x5ab3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED48                                        0x5ab4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED49                                        0x5ab5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED50                                        0x5ab6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED51                                        0x5ab7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED52                                        0x5ab8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED53                                        0x5ab9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED54                                        0x5aba
#define mmDCRX_PHY_MACRO_CNTL_RESERVED55                                        0x5abb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED56                                        0x5abc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED57                                        0x5abd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED58                                        0x5abe
#define mmDCRX_PHY_MACRO_CNTL_RESERVED59                                        0x5abf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED60                                        0x5ac0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED61                                        0x5ac1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED62                                        0x5ac2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED63                                        0x5ac3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED64                                        0x5ac4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED65                                        0x5ac5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED66                                        0x5ac6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED67                                        0x5ac7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED68                                        0x5ac8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED69                                        0x5ac9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED70                                        0x5aca
#define mmDCRX_PHY_MACRO_CNTL_RESERVED71                                        0x5acb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED72                                        0x5acc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED73                                        0x5acd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED74                                        0x5ace
#define mmDCRX_PHY_MACRO_CNTL_RESERVED75                                        0x5acf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED76                                        0x5ad0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED77                                        0x5ad1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED78                                        0x5ad2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED79                                        0x5ad3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED80                                        0x5ad4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED81                                        0x5ad5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED82                                        0x5ad6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED83                                        0x5ad7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED84                                        0x5ad8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED85                                        0x5ad9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED86                                        0x5ada
#define mmDCRX_PHY_MACRO_CNTL_RESERVED87                                        0x5adb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED88                                        0x5adc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED89                                        0x5add
#define mmDCRX_PHY_MACRO_CNTL_RESERVED90                                        0x5ade
#define mmDCRX_PHY_MACRO_CNTL_RESERVED91                                        0x5adf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED92                                        0x5ae0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED93                                        0x5ae1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED94                                        0x5ae2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED95                                        0x5ae3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED96                                        0x5ae4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED97            