MACRO_CNTL_RESERVED50                                            0x5dca
#define mmDPHY_MACRO_CNTL_RESERVED51                                            0x5dcb
#define mmDPHY_MACRO_CNTL_RESERVED52                                            0x5dcc
#define mmDPHY_MACRO_CNTL_RESERVED53                                            0x5dcd
#define mmDPHY_MACRO_CNTL_RESERVED54                                            0x5dce
#define mmDPHY_MACRO_CNTL_RESERVED55                                            0x5dcf
#define mmDPHY_MACRO_CNTL_RESERVED56                                            0x5dd0
#define mmDPHY_MACRO_CNTL_RESERVED57                                            0x5dd1
#define mmDPHY_MACRO_CNTL_RESERVED58                                            0x5dd2
#define mmDPHY_MACRO_CNTL_RESERVED59                                            0x5dd3
#define mmDPHY_MACRO_CNTL_RESERVED60                                            0x5dd4
#define mmDPHY_MACRO_CNTL_RESERVED61                                            0x5dd5
#define mmDPHY_MACRO_CNTL_RESERVED62                                            0x5dd6
#define mmDPHY_MACRO_CNTL_RESERVED63                                            0x5dd7
#define mmGRPH_ENABLE                                                           0x1a00
#define mmDCP0_GRPH_ENABLE                                                      0x1a00
#define mmDCP1_GRPH_ENABLE                                                      0x1c00
#define mmDCP2_GRPH_ENABLE                                                      0x1e00
#define mmDCP3_GRPH_ENABLE                                                      0x4000
#define mmDCP4_GRPH_ENABLE                                                      0x4200
#define mmDCP5_GRPH_ENABLE                                                      0x4400
#define mmGRPH_CONTROL                                                          0x1a01
#define mmDCP0_GRPH_CONTROL                                                     0x1a01
#define mmDCP1_GRPH_CONTROL                                                     0x1c01
#define mmDCP2_GRPH_CONTROL                                                     0x1e01
#define mmDCP3_GRPH_CONTROL                                                     0x4001
#define mmDCP4_GRPH_CONTROL                                                     0x4201
#define mmDCP5_GRPH_CONTROL                                                     0x4401
#define mmGRPH_LUT_10BIT_BYPASS                                                 0x1a02
#define mmDCP0_GRPH_LUT_10BIT_BYPASS                                            0x1a02
#define mmDCP1_GRPH_LUT_10BIT_BYPASS                                            0x1c02
#define mmDCP2_GRPH_LUT_10BIT_BYPASS                                            0x1e02
#define mmDCP3_GRPH_LUT_10BIT_BYPASS                                            0x4002
#define mmDCP4_GRPH_LUT_10BIT_BYPASS                                            0x4202
#define mmDCP5_GRPH_LUT_10BIT_BYPASS                                            0x4402
#define mmGRPH_SWAP_CNTL                                                        0x1a03
#define mmDCP0_GRPH_SWAP_CNTL                                                   0x1a03
#define mmDCP1_GRPH_SWAP_CNTL                                                   0x1c03
#define mmDCP2_GRPH_SWAP_CNTL                                                   0x1e03
#define mmDCP3_GRPH_SWAP_CNTL                                                   0x4003
#define mmDCP4_GRPH_SWAP_CNTL                                                   0x4203
#define mmDCP5_GRPH_SWAP_CNTL                                                   0x4403
#define mmGRPH_PRIMARY_SURFACE_ADDRESS                                          0x1a04
#define mmDCP0_GRPH_PRIMARY_SURFACE_ADDRESS                                     0x1a04
#define mmDCP1_GRPH_PRIMARY_SURFACE_ADDRESS                                     0x1c04
#define mmDCP2_GRPH_PRIMARY_SURFACE_ADDRESS                                     0x1e04
#define mmDCP3_GRPH_PRIMARY_SURFACE_ADDRESS                                     0x4004
#define mmDCP4_GRPH_PRIMARY_SURFACE_ADDRESS                                     0x4204
#define mmDCP5_GRPH_PRIMARY_SURFACE_ADDRESS                                     0x4404
#define mmGRPH_SECONDARY_SURFACE_ADDRESS                                        0x1a05
#define mmDCP0_GRPH_SECONDARY_SURFACE_ADDRESS                                   0x1a05
#define mmDCP1_GRPH_SECONDARY_SURFACE_ADDRESS                                   0x1c05
#define mmDCP2_GRPH_SECONDARY_SURFACE_ADDRESS                                   0x1e05
#define mmDCP3_GRPH_SECONDARY_SURFACE_ADDRESS                                   0x4005
#define mmDCP4_GRPH_SECONDARY_SURFACE_ADDRESS                                   0x4205
#define mmDCP5_GRPH_SECONDARY_SURFACE_ADDRESS                                   0x4405
#define mmGRPH_PITCH                                                            0x1a06
#define mmDCP0_GRPH_PITCH                                                       0x1a06
#define mmDCP1_GRPH_PITCH                                                       0x1c06
#define mmDCP2_GRPH_PITCH                                                       0x1e06
#define mmDCP3_GRPH_PITCH                                                       0x4006
#define mmDCP4_GRPH_PITCH                                                       0x4206
#define mmDCP5_GRPH_PITCH                                                       0x4406
#define mmGRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                     0x1a07
#define mmDCP0_GRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                0x1a07
#define mmDCP1_GRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                0x1c07
#define mmDCP2_GRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                0x1e07
#define mmDCP3_GRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                0x4007
#define mmDCP4_GRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                0x4207
#define mmDCP5_GRPH_PRIMARY_SURFACE_ADDRESS_HIGH                                0x4407
#define mmGRPH_SECONDARY_SURFACE_ADDRESS_HIGH                                   0x1a08
#define mmDCP0_GRPH_SECONDARY_SURFACE_ADDRESS_HIGH                              0x1a08
#define mmDCP1_GRPH_SECONDARY_SURFACE_ADDRESS_HIGH                              0x1c08
#define mmDCP2_GRPH_SECONDARY_SURFACE_ADDRESS_HIGH                              0x1e08
#define mmDCP3_GRPH_SECONDARY_SURFACE_ADDRESS_HIGH                              0x4008
#define mmDCP4_GRPH_SECONDARY_SURFACE_ADDRESS_HIGH                              0x4208
#define mmDCP5_GRPH_SECONDARY_SURFACE_ADDRESS_HIGH                              0x4408
#define mmGRPH_SURFACE_OFFSET_X                                                 0x1a09
#define mmDCP0_GRPH_SURFACE_OFFSET_X                                            0x1a09
#define mmDCP1_GRPH_SURFACE_OFFSET_X                                            0x1c09
#define mmDCP2_GRPH_SURFACE_OFFSET_X                                            0x1e09
#define mmDCP3_GRPH_SURFACE_OFFSET_X                                            0x4009
#define mmDCP4_GRPH_SURFACE_OFFSET_X                                            0x4209
#define mmDCP5_GRPH_SURFACE_OFFSET_X                                            0x4409
#define mmGRPH_SURFACE_OFFSET_Y                                                 0x1a0a
#define mmDCP0_GRPH_SURFACE_OFFSET_Y                                            0x1a0a
#define mmDCP1_GRPH_SURFACE_OFFSET_Y                                            0x1c0a
#define mmDCP2_GRPH_SURFACE_OFFSET_Y                                            0x1e0a
#define mmDCP3_GRPH_SURFACE_OFFSET_Y                                            0x400a
#define mmDCP4_GRPH_SURFACE_OFFSET_Y                                            0x420a
#define mmDCP5_GRPH_SURFACE_OFFSET_Y                                            0x440a
#define mmGRPH_X_START                                                          0x1a0b
#define mmDCP0_GRPH_X_START                                                     0x1a0b
#define mmDCP1_GRPH_X_START                                                     0x1c0b
#define mmDCP2_GRPH_X_START                                                     0x1e0b
#define mmDCP3_GRPH_X_START                                                     0x400b
#define mmDCP4_GRPH_X_START                                                     0x420b
#define mmDCP5_GRPH_X_START                                                     0x440b
#define mmGRPH_Y_START                                                          0x1a0c
#define mmDCP0_GRPH_Y_START                                                     0x1a0c
#define mmDCP1_GRPH_Y_START                                                     0x1c0c
#define mmDCP2_GRPH_Y_START                                                     0x1e0c
#define mmDCP3_GRPH_Y_START                                                     0x400c
#define mmDCP4_GRPH_Y_START                                                     0x420c
#define mmDCP5_GRPH_Y_START                                                     0x440c
#define mmGRPH_X_END                                                            0x1a0d
#define mmDCP0_GRPH_X_END                                                       0x1a0d
#define mmDCP1_GRPH_X_END                                                       0x1c0d
#define mmDCP2_GRPH_X_END                                                       0x1e0d
#define mmDCP3_GRPH_X_END                                                       0x400d
#define mmDCP4_GRPH_X_END                                                       0x420d
#define mmDCP5_GRPH_X_END            