         0x4a7b
#define mmDIG0_DIG_TEST_DEBUG_DATA                                              0x4a7b
#define mmDIG1_DIG_TEST_DEBUG_DATA                                              0x4b7b
#define mmDIG2_DIG_TEST_DEBUG_DATA                                              0x4c7b
#define mmDIG3_DIG_TEST_DEBUG_DATA                                              0x4d7b
#define mmDIG4_DIG_TEST_DEBUG_DATA                                              0x4e7b
#define mmDIG5_DIG_TEST_DEBUG_DATA                                              0x4f7b
#define mmDIG6_DIG_TEST_DEBUG_DATA                                              0x547b
#define mmDIG_FE_TEST_DEBUG_INDEX                                               0x4a7c
#define mmDIG0_DIG_FE_TEST_DEBUG_INDEX                                          0x4a7c
#define mmDIG1_DIG_FE_TEST_DEBUG_INDEX                                          0x4b7c
#define mmDIG2_DIG_FE_TEST_DEBUG_INDEX                                          0x4c7c
#define mmDIG3_DIG_FE_TEST_DEBUG_INDEX                                          0x4d7c
#define mmDIG4_DIG_FE_TEST_DEBUG_INDEX                                          0x4e7c
#define mmDIG5_DIG_FE_TEST_DEBUG_INDEX                                          0x4f7c
#define mmDIG6_DIG_FE_TEST_DEBUG_INDEX                                          0x547c
#define mmDIG_FE_TEST_DEBUG_DATA                                                0x4a7d
#define mmDIG0_DIG_FE_TEST_DEBUG_DATA                                           0x4a7d
#define mmDIG1_DIG_FE_TEST_DEBUG_DATA                                           0x4b7d
#define mmDIG2_DIG_FE_TEST_DEBUG_DATA                                           0x4c7d
#define mmDIG3_DIG_FE_TEST_DEBUG_DATA                                           0x4d7d
#define mmDIG4_DIG_FE_TEST_DEBUG_DATA                                           0x4e7d
#define mmDIG5_DIG_FE_TEST_DEBUG_DATA                                           0x4f7d
#define mmDIG6_DIG_FE_TEST_DEBUG_DATA                                           0x547d
#define mmDMCU_CTRL                                                             0x1600
#define mmDMCU_STATUS                                                           0x1601
#define mmDMCU_PC_START_ADDR                                                    0x1602
#define mmDMCU_FW_START_ADDR                                                    0x1603
#define mmDMCU_FW_END_ADDR                                                      0x1604
#define mmDMCU_FW_ISR_START_ADDR                                                0x1605
#define mmDMCU_FW_CS_HI                                                         0x1606
#define mmDMCU_FW_CS_LO                                                         0x1607
#define mmDMCU_RAM_ACCESS_CTRL                                                  0x1608
#define mmDMCU_ERAM_WR_CTRL                                                     0x1609
#define mmDMCU_ERAM_WR_DATA                                                     0x160a
#define mmDMCU_ERAM_RD_CTRL                                                     0x160b
#define mmDMCU_ERAM_RD_DATA                                                     0x160c
#define mmDMCU_IRAM_WR_CTRL                                                     0x160d
#define mmDMCU_IRAM_WR_DATA                                                     0x160e
#define mmDMCU_IRAM_RD_CTRL                                                     0x160f
#define mmDMCU_IRAM_RD_DATA                                                     0x1610
#define mmDMCU_EVENT_TRIGGER                                                    0x1611
#define mmDMCU_UC_INTERNAL_INT_STATUS                                           0x1612
#define mmDMCU_SS_INTERRUPT_CNTL_STATUS                                         0x1613
#define mmDMCU_INTERRUPT_STATUS                                                 0x1614
#define mmDMCU_INTERRUPT_TO_HOST_EN_MASK                                        0x1615
#define mmDMCU_INTERRUPT_TO_UC_EN_MASK                                          0x1616
#define mmDMCU_INTERRUPT_TO_UC_XIRQ_IRQ_SEL                                     0x1617
#define mmDC_DMCU_SCRATCH                                                       0x1618
#define mmDMCU_INT_CNT                                                          0x1619
#define mmDMCU_FW_CHECKSUM_SMPL_BYTE_POS                                        0x161a
#define mmDMCU_UC_CLK_GATING_CNTL                                               0x161b
#define mmMASTER_COMM_DATA_REG1                                                 0x161c
#define mmMASTER_COMM_DATA_REG2                                                 0x161d
#define mmMASTER_COMM_DATA_REG3                                                 0x161e
#define mmMASTER_COMM_CMD_REG                                                   0x161f
#define mmMASTER_COMM_CNTL_REG                                                  0x1620
#define mmSLAVE_COMM_DATA_REG1                                                  0x1621
#define mmSLAVE_COMM_DATA_REG2                                                  0x1622
#define mmSLAVE_COMM_DATA_REG3                                                  0x1623
#define mmSLAVE_COMM_CMD_REG                                                    0x1624
#define mmSLAVE_COMM_CNTL_REG                                                   0x1625
#define mmDMCU_TEST_DEBUG_INDEX                                                 0x1626
#define mmDMCU_TEST_DEBUG_DATA                                                  0x1627
#define mmDMCU_PERFMON_INTERRUPT_STATUS1                                        0x1644
#define mmDMCU_PERFMON_INTERRUPT_STATUS2                                        0x1645
#define mmDMCU_PERFMON_INTERRUPT_STATUS3                                        0x1646
#define mmDMCU_PERFMON_INTERRUPT_STATUS4                                        0x1647
#define mmDMCU_PERFMON_INTERRUPT_STATUS5                                        0x1642
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK1                                 0x1674
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK2                                 0x1675
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK3                                 0x1676
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK4                                 0x1677
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_EN_MASK5                                 0x1643
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL1                            0x1678
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL2                            0x1679
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL3                            0x167a
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL4                            0x167b
#define mmDMCU_PERFMON_INTERRUPT_TO_UC_XIRQ_IRQ_SEL5                            0x1673
#define mmDMCU_PERFMON_INTERRUPT_TO_HOST_EN_MASK1                               0x167c
#define mmDMCU_PERFMON_INTERRUPT_TO_HOST_EN_MASK2                               0x167d
#define mmDMCU_PERFMON_INTERRUPT_TO_HOST_EN_MASK3                               0x167e
#define mmDMCU_PERFMON_INTERRUPT_TO_HOST_EN_MASK4                               0x167f
#define mmDMCU_PERFMON_INTERRUPT_TO_HOST_EN_MASK5                               0x1633
#define mmDMCU_DPRX_INTERRUPT_STATUS1                                           0x1634
#define mmDMCU_DPRX_INTERRUPT_TO_UC_EN_MASK1                                    0x1635
#define mmDMCU_DPRX_INTERRUPT_TO_UC_XIRQ_IRQ_SEL1                               0x1636
#define mmDP_LINK_CNTL                                                          0x4aa0
#define mmDP0_DP_LINK_CNTL                                                      0x4aa0
#define mmDP1_DP_LINK_CNTL                                                      0x4ba0
#define mmDP2_DP_LINK_CNTL                                                      0x4ca0
#define mmDP3_DP_LINK_CNTL                                                      0x4da0
#define mmDP4_DP_LINK_CNTL                                                      0x4ea0
#define mmDP5_DP_LINK_CNTL                                                      0x4fa0
#define mmDP6_DP_LINK_CNTL                                                      0x54a0
#define mmDP_PIXEL_FORMAT                                                       0x4aa1
#define mmDP0_DP_PIXEL_FORMAT                                                   0x4aa1
#define mmDP1_DP_PIXEL_FORMAT                                                   0x4ba1
#define mmDP2_DP_PIXEL_FORMAT                                                   0x4ca1
#define mmDP3_DP_PIXEL_FORMAT                                                   0x4da1
#define mmDP4_DP_PIXEL_FORMAT                                                   0x4ea1
#define mmDP5_DP_PIXEL_FORMAT                                                   0x4fa1
#define mmDP6_DP_PIXEL_FORMAT                                                   0x54a1
#define mmDP_MSA_COLORIMETRY                                                    0x4aa2
#define mmDP0_DP_MSA_COLORIMETRY                                                0x4aa2
#define mmDP1_DP_MSA_COLORIMETRY                                                0x4ba2
#define mmDP2_DP_MSA_COLORIMETRY                                                0x4ca2
#define mmDP3_DP_MSA_COLORIMETRY                                                0x4da2
#define mmDP4_DP_MSA_COLORIMETRY                                                0x4ea2
#define mmDP5_DP_MSA_COLORIMETRY                                                0x4fa2
#define mmDP6_DP_MSA_COLORIMETRY                                                0x54a2
#define mmDP_CONFIG                                                             0x4aa3
#define mmDP0_DP_CONFIG                                                         0x4aa3
#define mmDP1_DP_CONFIG                                                         0x4ba3
#define mmDP2_DP_CONFIG                                                         0x4ca3
#define mmDP3_DP_CONFIG                                                         0x4da3
#define mmDP4_DP_CONFIG                                                         0x4ea3
#define mmDP5_DP_CONFIG                                                         0x4fa3
#define mmDP6_DP_CONFIG                                                         0x54a3
#define mmDP_VID_STREAM_CNTL                                                    0x4aa4
#define mmDP0_DP_VID_STREAM_CNTL                                                0x4aa4
#define mmDP1_DP_VID_STREAM_CNTL                                                0x4ba4
#define mmDP2_DP_VID_STREAM_CNTL                                                0x4ca4
#define mmDP3_DP_VID_STREAM_CNTL                                                0x4da4
#define mmDP4_DP_VID_STREAM_CNTL                                                0x4ea4
#define mmDP5_DP_VID_STREAM_CNTL                                                0x4fa4
#define mmDP6_DP_VID_STREAM_CNTL                                                0x54a4
#define mmDP_STEER_FIFO                                                         0x4aa5
#define mmDP0_DP_STEER_FIFO                                                     0x4aa5
#define mmDP1_DP_STEER_FIFO                                                     0x4ba5
#define mmDP2_DP_STEER_FIFO                                                     0x4ca5
#define mmDP3_DP_STEER_FIFO                                                     0x4da5
#define mmDP4_DP_STEER_FIFO                                                     0x4ea5
#define mmDP5_DP_STEER_FIFO                                                     0x4fa5
#define mmDP6_DP_STEER_FIFO                                                     0x54a5
#define mmDP_MSA_MISC                                                           0x4aa6
#define mmDP0_DP_MSA_MISC                                                       0x4aa6
#define mmDP1_DP_MSA_MISC                                                       0x4ba6
#define mmDP2_DP_MSA_MISC                                                       0x4ca6
#define mmDP3_DP_MSA_MISC                                                       0x4da6
#define mmDP4_DP_MSA_MISC                                                       0x4ea6
#define mmDP5_DP_MSA_MISC                                                       0x4fa6
#define mmDP6_DP_MSA_MISC                                                       0x54a6
#define mmDP_VID_TIMING                                                         0x4aa8
#define mmDP0_DP_VID_TIMING                                                     0x4aa8
#define mmDP1_DP_VID_TIMING                                                     0x4ba8
#define mmDP2_DP_VID_TIMING                                                     0x4ca8
#define mmDP3_DP_VID_TIMING                                                     0x4da8
#define mmDP4_DP_VID_TIMING                                                     0x4ea8
#define mmDP5_DP_VID_TIMING                                                     0x4fa8
#define mmDP6_DP_VID_TIMING                                                     0x54a8
#define mmDP_VID_N                                                              0x4aa9
#define mmDP0_DP_VID_N                                                          0x4aa9
#define mmDP1_DP_VID_N                                                          0x4ba9
#define mmDP2_DP_VID_N                                                          0x4ca9
#define mmDP3_DP_VID_N                                                          0x4da9
#define mmDP4_DP_VID_N                                                          0x4ea9
#define mmDP5_DP_VID_N                                                          0x4fa9
#define mmDP6_DP_VID_N                                                          0x54a9
#define mmDP_VID_M                                                              0x4aaa
#define mmDP0_DP_VID_M                                                          0x4aaa
#define mmDP1_DP_VID_M                                                          0x4baa
#define mmDP2_DP_VID_M                                                          0x4caa
#define mmDP3_DP_VID_M                                                          0x4daa
#define mmDP4_DP_VID_M                                                          0x4eaa
#define mmDP5_DP_VID_M                                                          0x4faa
#define mmDP6_DP_VID_M                                                          0x54aa
#define mmDP_LINK_FRAMING_CNTL                                                  0x4aab
#define mmDP0_DP_LINK_FRAMING_CNTL                                              0x4aab
#define mmDP1_DP_LINK_FRAMING_CNTL                                              0x4bab
#define mmDP2_DP_LINK_FRAMING_CNTL                                              0x4cab
#define mmDP3_DP_LINK_FRAMING_CNTL                                              0x4dab
#define mmDP4_DP_LINK_FRAMING_CNTL                                              0x4eab
#define mmDP5_DP_LINK_FRAMING_CNTL                                              0x4fab
#define mmDP6_DP_LINK_FRAMING_CNTL                                              0x54ab
#define mmDP_HBR2_EYE_PATTERN                                                   0x4aac
#define mmDP0_DP_HBR2_EYE_PATTERN                                               0x4aac
#define mmDP1_DP_HBR2_EYE_PATTERN                                               0x4bac
#define mmDP2_DP_HBR2_EYE_PATTERN                                               0x4cac
#define mmDP3_DP_HBR2_EYE_PATTERN                                               0x4dac
#define mmDP4_DP_HBR2_EYE_PATTERN                                               0x4eac
#define mmDP5_DP_HBR2_EYE_PATTERN                                               0x4fac
#define mmDP6_DP_HBR2_EYE_PATTERN                                               0x54ac
#define mmDP_VID_MSA_VBID                                                       0x4aad
#define mmDP0_DP_VID_MSA_VBID                                                   0x4aad
#define mmDP1_DP_VID_MSA_VBID                                                   0x4bad
#define mmDP2_DP_VID_MSA_VBID                                                   0x4cad
#define mmDP3_DP_VID_MSA_VBID                                                   0x4dad
#define mmDP4_DP_VID_MSA_VBID                                                   0x4ead
#define mmDP5_DP_VID_MSA_VBID                                                   0x4fad
#define mmDP6_DP_VID_MSA_VBID                                                   0x54ad
#define mmDP_VID_INTERRUPT_CNTL                                                 0x4aae
#define mmDP0_DP_VID_INTERRUPT_CNTL                                             0x4aae
#define mmDP1_DP_VID_INTERRUPT_CNTL                                             0x4bae
#define mmDP2_DP_VID_INTERRUPT_CNTL                                             0x4cae
#define mmDP3_DP_VID_INTERRUPT_CNTL                                             0x4dae
#define mmDP4_DP_VID_INTERRUPT_CNTL                                             0x4eae
#define mmDP5_DP_VID_INTERRUPT_CNTL                                             0x4fae
#define mmDP6_DP_VID_INTERRUPT_CNTL                                             0x54ae
#define mmDP_DPHY_CNTL                                                          0x4aaf
#define mmDP0_DP_DPHY_CNTL                                                      0x4aaf
#define mmDP1_DP_DPHY_CNTL                                                      0x4baf
#define mmDP2_DP_DPHY_CNTL                                                      0x4caf
#define mmDP3_DP_DPHY_CNTL                                                      0x4daf
#define mmDP4_DP_DPHY_CNTL                                                      0x4eaf
#define mmDP5_DP_DPHY_CNTL                                                      0x4faf
#define mmDP6_DP_DPHY_CNTL                                                      0x54af
#define mmDP_DPHY_TRAINING_PATTERN_SEL                                          0x4ab0
#define mmDP0_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4ab0
#define mmDP1_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4bb0
#define mmDP2_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4cb0
#define mmDP3_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4db0
#define mmDP4_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4eb0
#define mmDP5_DP_DPHY_TRAINING_PATTERN_SEL                                      0x4fb0
#define mmDP6_DP_DPHY_TRAINING_PATTERN_SEL                                      0x54b0
#define mmDP_DPHY_SYM0                                                          0x4ab1
#define mmDP0_DP_DPHY_SYM0                                                      0x4ab1
#define mmDP1_DP_DPHY_SYM0                                                      0x4bb1
#define mmDP2_DP_DPHY_SYM0                                                      0x4cb1
#define mmDP3_DP_DPHY_SYM0                                                      0x4db1
#define mmDP4_DP_DPHY_SYM0                                                      0x4eb1
#define mmDP5_DP_DPHY_SYM0                                                      0x4fb1
#define mmDP6_DP_DPHY_SYM0                                                      0x54b1
#define mmDP_DPHY_SYM1                                                          0x4ab2
#define mmDP0_DP_DPHY_SYM1                                                      0x4ab2
#define mmDP1_DP_DPHY_SYM1                                                      0x4bb2
#define mmDP2_DP_DPHY_SYM1                                                      0x4cb2
#define mmDP3_DP_DPHY_SYM1                                                      0x4db2
#define mmDP4_DP_DPHY_SYM1                                                      0x4eb2
#define mmDP5_DP_DPHY_SYM1                                                      0x4fb2
#define mmDP6_DP_DPHY_SYM1                                                      0x54b2
#define mmDP_DPHY_SYM2                                                          0x4ab3
#define mmDP0_DP_DPHY_SYM2                                                      0x4ab3
#define mmDP1_DP_DPHY_SYM2                                                      0x4bb3
#define mmDP2_DP_DPHY_SYM2                                                      0x4cb3
#define mmDP3_DP_DPHY_SYM2                                                      0x4db3
#define mmDP4_DP_DPHY_SYM2                                                      0x4eb3
#define mmDP5_DP_DPHY_SYM2                                                      0x4fb3
#define mmDP6_DP_DPHY_SYM2                                                      0x54b3
#define mmDP_DPHY_8B10B_CNTL                                                    0x4ab4
#define mmDP0_DP_DPHY_8B10B_CNTL                                                0x4ab4
#define mmDP1_DP_DPHY_8B10B_CNTL                                                0x4bb4
#define mmDP2_DP_DPHY_8B10B_CNTL                                                0x4cb4
#define mmDP3_DP_DPHY_8B10B_CNTL                                                0x4db4
#define mmDP4_DP_DPHY_8B10B_CNTL                                                0x4eb4
#define mmDP5_DP_DPHY_8B10B_CNTL                                                0x4fb4
#define mmDP6_DP_DPHY_8B10B_CNTL                                                0x54b4
#define mmDP_DPHY_PRBS_CNTL                                                     0x4ab5
#define mmDP0_DP_DPHY_PRBS_CNTL                                                 0x4ab5
#define mmDP1_DP_DPHY_PRBS_CNTL                                                 0x4bb5
#define mmDP2_DP_DPHY_PRBS_CNTL                                                 0x4cb5
#define mmDP3_DP_DPHY_PRBS_CNTL                                                 0x4db5
#define mmDP4_DP_DPHY_PRBS_CNTL                                                 0x4eb5
#define mmDP5_DP_DPHY_PRBS_CNTL                                                 0x4fb5
#define mmDP6_DP_DPHY_PRBS_CNTL                                                 0x54b5
#define mmDP_DPHY_CRC_EN                                                        0x4ab7
#define mmDP0_DP_DPHY_CRC_EN                                                    0x4ab7
#define mmDP1_DP_DPHY_CRC_EN                                                    0x4bb7
#define mmDP2_DP_DPHY_CRC_EN                                                    0x4cb7
#define mmDP3_DP_DPHY_CRC_EN                                                    0x4db7
#define mmDP4_DP_DPHY_CRC_EN                                                    0x4eb7
#define mmDP5_DP_DPHY_CRC_EN                                                    0x4fb7
#define mmDP6_DP_DPHY_CRC_EN                                                    0x54b7
#define mmDP_DPHY_CRC_CNTL                                                      0x4ab8
#define mmDP0_DP_DPHY_CRC_CNTL                                                  0x4ab8
#define mmDP1_DP_DPHY_CRC_CNTL                                                  0x4bb8
#define mmDP2_DP_DPHY_CRC_CNTL                                                  0x4cb8
#define mmDP3_DP_DPHY_CRC_CNTL                                                  0x4db8
#define mmDP4_DP_DPHY_CRC_CNTL                                                  0x4eb8
#define mmDP5_DP_DPHY_CRC_CNTL                                                  0x4fb8
#define mmDP6_DP_DPHY_CRC_CNTL                                                  0x54b8
#define mmDP_DPHY_CRC_RESULT                                                    0x4ab9
#define mmDP0_DP_DPHY_CRC_RESULT                                                0x4ab9
#define mmDP1_DP_DPHY_CRC_RESULT                                                0x4bb9
#define mmDP2_DP_DPHY_CRC_RESULT                                                0x4cb9
#define mmDP3_DP_DPHY_CRC_RESULT                                                0x4db9
#define mmDP4_DP_DPHY_CRC_RESULT                                                0x4eb9
#define mmDP5_DP_DPHY_CRC_RESULT                                                0x4fb9
#define mmDP6_DP_DPHY_CRC_RESULT                                                0x54b9
#define mmDP_DPHY_CRC_MST_CNTL                                                  0x4aba
#define mmDP0_DP_DPHY_CRC_MST_CNTL                                              0x4aba
#define mmDP1_DP_DPHY_CRC_MST_CNTL                                              0x4bba
#define mmDP2_DP_DPHY_CRC_MST_CNTL                                              0x4cba
#define mmDP3_DP_DPHY_CRC_MST_CNTL                                              0x4dba
#define mmDP4_DP_DPHY_CRC_MST_CNTL                                              0x4eba
#define mmDP5_DP_DPHY_CRC_MST_CNTL                                              0x4fba
#define mmDP6_DP_DPHY_CRC_MST_CNTL                                              0x54ba
#define mmDP_DPHY_CRC_MST_STATUS                                                0x4abb
#define mmDP0_DP_DPHY_CRC_MST_STATUS                                            0x4abb
#define mmDP1_DP_DPHY_CRC_MST_STATUS                                            0x4bbb
#define mmDP2_DP_DPHY_CRC_MST_STATUS                                            0x4cbb
#define mmDP3_DP_DPHY_CRC_MST_STATUS                                            0x4dbb
#define mmDP4_DP_DPHY_CRC_MST_STATUS                                            0x4ebb
#define mmDP5_DP_DPHY_CRC_MST_STATUS                                            0x4fbb
#define mmDP6_DP_DPHY_CRC_MST_STATUS                                            0x54bb
#define mmDP_DPHY_FAST_TRAINING                                                 0x4abc
#define mmDP0_DP_DPHY_FAST_TRAINING                                             0x4abc
#define mmDP1_DP_DPHY_FAST_TRAINING                                             0x4bbc
#define mmDP2_DP_DPHY_FAST_TRAINING                                             0x4cbc
#define mmDP3_DP_DPHY_FAST_TRAINING                                             0x4dbc
#define mmDP4_DP_DPHY_FAST_TRAINING                                             0x4ebc
#define mmDP5_DP_DPHY_FAST_TRAINING                                             0x4fbc
#define mmDP6_DP_DPHY_FAST_TRAINING                                             0x54bc
#define mmDP_DPHY_FAST_TRAINING_STATUS                                          0x4abd
#define mmDP0_DP_DPHY_FAST_TRAINING_STATUS                                      0x4abd
#define mmDP1_DP_DPHY_FAST_TRAINING_STATUS                                      0x4bbd
#define mmDP2_DP_DPHY_FAST_TRAINING_STATUS                                      0x4cbd
#define mmDP3_DP_DPHY_FAST_TRAINING_STATUS                                      0x4dbd
#define mmDP4_DP_DPHY_FAST_TRAINING_STATUS                                      0x4ebd
#define mmDP5_DP_DPHY_FAST_TRAINING_STATUS                                      0x4fbd
#define mmDP6_DP_DPHY_FAST_TRAINING_STATUS                                      0x54bd
#define mmDP_MSA_V_TIMING_OVERRIDE1                                             0x4abe
#define mmDP0_DP_MSA_V_TIMING_OVERRIDE1                                         0x4abe
#define mmDP1_DP_MSA_V_TIMING_OVERRIDE1                                         0x4bbe
#define mmDP2_DP_MSA_V_TIMING_OVERRIDE1                                         0x4cbe
#define mmDP3_DP_MSA_V_TIMING_OVERRIDE1                                         0x4dbe
#define mmDP4_DP_MSA_V_TIMING_OVERRIDE1                                         0x4ebe
#define mmDP5_DP_MSA_V_TIMING_OVERRIDE1                                         0x4fbe
#define mmDP6_DP_MSA_V_TIMING_OVERRIDE1                                         0x54be
#define mmDP_MSA_V_TIMING_OVERRIDE2                                             0x4abf
#define mmDP0_DP_MSA_V_TIMING_OVERRIDE2                                         0x4abf
#define mmDP1_DP_MSA_V_TIMING_OVERRIDE2                                         0x4bbf
#define mmDP2_DP_MSA_V_TIMING_OVERRIDE2                                         0x4cbf
#define mmDP3_DP_MSA_V_TIMING_OVERRIDE2                                         0x4dbf
#define mmDP4_DP_MSA_V_TIMING_OVERRIDE2                                         0x4ebf
#define mmDP5_DP_MSA_V_TIMING_OVERRIDE2                                         0x4fbf
#define mmDP6_DP_MSA_V_TIMING_OVERRIDE2                                         0x54bf
#define mmDP_SEC_CNTL                                                           0x4ac3
#define mmDP0_DP_SEC_CNTL                                                       0x4ac3
#define mmDP1_DP_SEC_CNTL                                                       0x4bc3
#define mmDP2_DP_SEC_CNTL                                                       0x4cc3
#define mmDP3_DP_SEC_CNTL                                                       0x4dc3
#define mmDP4_DP_SEC_CNTL                                                       0x4ec3
#define mmDP5_DP_SEC_CNTL                                                       0x4fc3
#define mmDP6_DP_SEC_CNTL                                                       0x54c3
#define mmDP_SEC_CNTL1                                                          0x4ac4
#define mmDP0_DP_SEC_CNTL1                                                      0x4ac4
#define mmDP1_DP_SEC_CNTL1                                                      0x4bc4
#define mmDP2_DP_SEC_CNTL1                                                      0x4cc4
#define mmDP3_DP_SEC_CNTL1                                                      0x4dc4
#define mmDP4_DP_SEC_CNTL1                                                      0x4ec4
#define mmDP5_DP_SEC_CNTL1                                                      0x4fc4
#define mmDP6_DP_SEC_CNTL1                                                      0x54c4
#define mmDP_SEC_FRAMING1                                                       0x4ac5
#define mmDP0_DP_SEC_FRAMING1                                                   0x4ac5
#define mmDP1_DP_SEC_FRAMING1                                                   0x4bc5
#define mmDP2_DP_SEC_FRAMING1                                                   0x4cc5
#define mmDP3_DP_SEC_FRAMING1                                                   0x4dc5
#define mmDP4_DP_SEC_FRAMING1                                                   0x4ec5
#define mmDP5_DP_SEC_FRAMING1                                                   0x4fc5
#define mmDP6_DP_SEC_FRAMING1                                                   0x54c5
#define mmDP_SEC_FRAMING2                                                       0x4ac6
#define mmDP0_DP_SEC_FRAMING2                                                   0x4ac6
#define mmDP1_DP_SEC_FRAMING2                                                   0x4bc6
#define mmDP2_DP_SEC_FRAMING2                                                   0x4cc6
#define mmDP3_DP_SEC_FRAMING2                                                   0x4dc6
#define mmDP4_DP_SEC_FRAMING2                                                   0x4ec6
#define mmDP5_DP_SEC_FRAMING2                                                   0x4fc6
#define mmDP6_DP_SEC_FRAMING2                                                   0x54c6
#define mmDP_SEC_FRAMING3                                                       0x4ac7
#define mmDP0_DP_SEC_FRAMING3                                                   0x4ac7
#define mmDP1_DP_SEC_FRAMING3                                                   0x4bc7
#define mmDP2_DP_SEC_FRAMING3                                                   0x4cc7
#define mmDP3_DP_SEC_FRAMING3                                                   0x4dc7
#define mmDP4_DP_SEC_FRAMING3                                                   0x4ec7
#define mmDP5_DP_SEC_FRAMING3                                                   0x4fc7
#define mmDP6_DP_SEC_FRAMING3                                                   0x54c7
#define mmDP_SEC_FRAMING4                                                       0x4ac8
#define mmDP0_DP_SEC_FRAMING4                                                   0x4ac8
#define mmDP1_DP_SEC_FRAMING4                                                   0x4bc8
#define mmDP2_DP_SEC_FRAMING4                                                   0x4cc8
#define mmDP3_DP_SEC_FRAMING4                                                   0x4dc8
#define mmDP4_DP_SEC_FRAMING4                                                   0x4ec8
#define mmDP5_DP_SEC_FRAMING4                                                   0x4fc8
#define mmDP6_DP_SEC_FRAMING4                                                   0x54c8
#define mmDP_SEC_AUD_N                                                          0x4ac9
#define mmDP0_DP_SEC_AUD_N                                                      0x4ac9
#define mmDP1_DP_SEC_AUD_N                                                      0x4bc9
#define mmDP2_DP_SEC_AUD_N                                                      0x4cc9
#define mmDP3_DP_SEC_AUD_N                                                      0x4dc9
#define mmDP4_DP_SEC_AUD_N                                                      0x4ec9
#define mmDP5_DP_SEC_AUD_N                                                      0x4fc9
#define mmDP6_DP_SEC_AUD_N                                                      0x54c9
#define mmDP_SEC_AUD_N_READBACK                                                 0x4aca
#define mmDP0_DP_SEC_AUD_N_READBACK                                             0x4aca
#define mmDP1_DP_SEC_AUD_N_READBACK                                             0x4bca
#define mmDP2_DP_SEC_AUD_N_READBACK                                             0x4cca
#define mmDP3_DP_SEC_AUD_N_READBACK                                             0x4dca
#define mmDP4_DP_SEC_AUD_N_READBACK                                             0x4eca
#define mmDP5_DP_SEC_AUD_N_READBACK                                             0x4fca
#define mmDP6_DP_SEC_AUD_N_READBACK                                             0x54ca
#define mmDP_SEC_AUD_M                                                          0x4acb
#define mmDP0_DP_SEC_AUD_M                                                      0x4acb
#define mmDP1_DP_SEC_AUD_M                                                      0x4bcb
#define mmDP2_DP_SEC_AUD_M                                                      0x4ccb
#define mmDP3_DP_SEC_AUD_M                                                      0x4dcb
#define mmDP4_DP_SEC_AUD_M                                                      0x4ecb
#define mmDP5_DP_SEC_AUD_M                                                      0x4fcb
#define mmDP6_DP_SEC_AUD_M                                                      0x54cb
#define mmDP_SEC_AUD_M_READBACK                                                 0x4acc
#define mmDP0_DP_SEC_AUD_M_READBACK                                             0x4acc
#define mmDP1_DP_SEC_AUD_M_READBACK                                             0x4bcc
#define mmDP2_DP_SEC_AUD_M_READBACK                                             0x4ccc
#define mmDP3_DP_SEC_AUD_M_READBACK                                             0x4dcc
#define mmDP4_DP_SEC_AUD_M_READBACK                                             0x4ecc
#define mmDP5_DP_SEC_AUD_M_READBACK                                             0x4fcc
#define mmDP6_DP_SEC_AUD_M_READBACK                                             0x54cc
#define mmDP_SEC_TIMESTAMP                                                      0x4acd
#define mmDP0_DP_SEC_TIMESTAMP                                                  0x4acd
#define mmDP1_DP_SEC_TIMESTAMP                                                  0x4bcd
#define mmDP2_DP_SEC_TIMESTAMP                                                  0x4ccd
#define mmDP3_DP_SEC_TIMESTAMP                                                  0x4dcd
#define mmDP4_DP_SEC_TIMESTAMP                                                  0x4ecd
#define mmDP5_DP_SEC_TIMESTAMP                                                  0x4fcd
#define mmDP6_DP_SEC_TIMESTAMP                                                  0x54cd
#define mmDP_SEC_PACKET_CNTL                                                    0x4ace
#define mmDP0_DP_SEC_PACKET_CNTL                                                0x4ace
#define mmDP1_DP_SEC_PACKET_CNTL                                                0x4bce
#define mmDP2_DP_SEC_PACKET_CNTL                                                0x4cce
#define mmDP3_DP_SEC_PACKET_CNTL                                                0x4dce
#define mmDP4_DP_SEC_PACKET_CNTL                                                0x4ece
#define mmDP5_DP_SEC_PACKET_CNTL                                                0x4fce
#define mmDP6_DP_SEC_PACKET_CNTL                                                0x54ce
#define mmDP_MSE_RATE_CNTL                                                      0x4acf
#define mmDP0_DP_MSE_RATE_CNTL                                                  0x4acf
#define mmDP1_DP_MSE_RATE_CNTL                                                  0x4bcf
#define mmDP2_DP_MSE_RATE_CNTL                                                  0x4ccf
#define mmDP3_DP_MSE_RATE_CNTL                                                  0x4dcf
#define mmDP4_DP_MSE_RATE_CNTL                                                  0x4ecf
#define mmDP5_DP_MSE_RATE_CNTL                                                  0x4fcf
#define mmDP6_DP_MSE_RATE_CNTL                                                  0x54cf
#define mmDP_MSE_RATE_UPDATE                                                    0x4ad1
#define mmDP0_DP_MSE_RATE_UPDATE                                                0x4ad1
#define mmDP1_DP_MSE_RATE_UPDATE                                                0x4bd1
#define mmDP2_DP_MSE_RATE_UPDATE                                                0x4cd1
#define mmDP3_DP_MSE_RATE_UPDATE                                                0x4dd1
#define mmDP4_DP_MSE_RATE_UPDATE                                                0x4ed1
#define mmDP5_DP_MSE_RATE_UPDATE                                                0x4fd1
#define mmDP6_DP_MSE_RATE_UPDATE                                                0x54d1
#define mmDP_MSE_SAT0                                                           0x4ad2
#define mmDP0_DP_MSE_SAT0                                                       0x4ad2
#define mmDP1_DP_MSE_SAT0                                                       0x4bd2
#define mmDP2_DP_MSE_SAT0                                                       0x4cd2
#define mmDP3_DP_MSE_SAT0                                                       0x4dd2
#define mmDP4_DP_MSE_SAT0                                                       0x4ed2
#define mmDP5_DP_MSE_SAT0                                                       0x4fd2
#define mmDP6_DP_MSE_SAT0                                                       0x54d2
#define mmDP_MSE_SAT1                                                           0x4ad3
#define mmDP0_DP_MSE_SAT1                                                       0x4ad3
#define mmDP1_DP_MSE_SAT1                                                       0x4bd3
#define mmDP2_DP_MSE_SAT1                                                       0x4cd3
#define mmDP3_DP_MSE_SAT1                                                       0x4dd3
#define mmDP4_DP_MSE_SAT1                                                       0x4ed3
#define mmDP5_DP_MSE_SAT1                                                       0x4fd3
#define mmDP6_DP_MSE_SAT1                                                       0x54d3
#define mmDP_MSE_SAT2                                                           0x4ad4
#define mmDP0_DP_MSE_SAT2                                                       0x4ad4
#define mmDP1_DP_MSE_SAT2                                                       0x4bd4
#define mmDP2_DP_MSE_SAT2                                                       0x4cd4
#define mmDP3_DP_MSE_SAT2                                                       0x4dd4
#define mmDP4_DP_MSE_SAT2                                                       0x4ed4
#define mmDP5_DP_MSE_SAT2                                                       0x4fd4
#define mmDP6_DP_MSE_SAT2                                                       0x54d4
#define mmDP_MSE_SAT_UPDATE                                                     0x4ad5
#define mmDP0_DP_MSE_SAT_UPDATE                                                 0x4ad5
#define mmDP1_DP_MSE_SAT_UPDATE                                                 0x4bd5
#define mmDP2_DP_MSE_SAT_UPDATE                                                 0x4cd5
#define mmDP3_DP_MSE_SAT_UPDATE                                                 0x4dd5
#define mmDP4_DP_MSE_SAT_UPDATE                                                 0x4ed5
#define mmDP5_DP_MSE_SAT_UPDATE                                                 0x4fd5
#define mmDP6_DP_MSE_SAT_UPDATE                                                 0x54d5
#define mmDP_MSE_LINK_TIMING                                                    0x4ad6
#define mmDP0_DP_MSE_LINK_TIMING                                                0x4ad6
#define mmDP1_DP_MSE_LINK_TIMING                                                0x4bd6
#define mmDP2_DP_MSE_LINK_TIMING                                                0x4cd6
#define mmDP3_DP_MSE_LINK_TIMING                                                0x4dd6
#define mmDP4_DP_MSE_LINK_TIMING                                                0x4ed6
#define mmDP5_DP_MSE_LINK_TIMING                                                0x4fd6
#define mmDP6_DP_MSE_LINK_TIMING                                                0x54d6
#define mmDP_MSE_MISC_CNTL                                                      0x4ad7
#define mmDP0_DP_MSE_MISC_CNTL                                                  0x4ad7
#define mmDP1_DP_MSE_MISC_CNTL                                                  0x4bd7
#define mmDP2_DP_MSE_MISC_CNTL                                                  0x4cd7
#define mmDP3_DP_MSE_MISC_CNTL                                                  0x4dd7
#define mmDP4_DP_MSE_MISC_CNTL                                                  0x4ed7
#define mmDP5_DP_MSE_MISC_CNTL                                                  0x4fd7
#define mmDP6_DP_MSE_MISC_CNTL                                                  0x54d7
#define mmDP_TEST_DEBUG_INDEX                                                   0x4ad8
#define mmDP0_DP_TEST_DEBUG_INDEX                                               0x4ad8
#define mmDP1_DP_TEST_DEBUG_INDEX                                               0x4bd8
#define mmDP2_DP_TEST_DEBUG_INDEX                                               0x4cd8
#define mmDP3_DP_TEST_DEBUG_INDEX                                               0x4dd8
#define mmDP4_DP_TEST_DEBUG_INDEX                                               0x4ed8
#define mmDP5_DP_TEST_DEBUG_INDEX                                               0x4fd8
#define mmDP6_DP_TEST_DEBUG_INDEX                                               0x54d8
#define mmDP_TEST_DEBUG_DATA                                                    0x4ad9
#define mmDP0_DP_TEST_DEBUG_DATA                                                0x4ad9
#define mmDP1_DP_TEST_DEBUG_DATA                                                0x4bd9
#define mmDP2_DP_TEST_DEBUG_DATA                                                0x4cd9
#define mmDP3_DP_TEST_DEBUG_DATA                                                0x4dd9
#define mmDP4_DP_TEST_DEBUG_DATA                                                0x4ed9
#define mmDP5_DP_TEST_DEBUG_DATA                                                0x4fd9
#define mmDP6_DP_TEST_DEBUG_DATA                                                0x54d9
#define mmDP_FE_TEST_DEBUG_INDEX                                                0x4ada
#define mmDP0_DP_FE_TEST_DEBUG_INDEX                                            0x4ada
#define mmDP1_DP_FE_TEST_DEBUG_INDEX                                            0x4bda
#define mmDP2_DP_FE_TEST_DEBUG_INDEX                                            0x4cda
#define mmDP3_DP_FE_TEST_DEBUG_INDEX                                            0x4dda
#define mmDP4_DP_FE_TEST_DEBUG_INDEX                                            0x4eda
#define mmDP5_DP_FE_TEST_DEBUG_INDEX                                            0x4fda
#define mmDP6_DP_FE_TEST_DEBUG_INDEX                                            0x54da
#define mmDP_FE_TEST_DEBUG_DATA                                                 0x4adb
#define mmDP0_DP_FE_TEST_DEBUG_DATA                                             0x4adb
#define mmDP1_DP_FE_TEST_DEBUG_DATA                                             0x4bdb
#define mmDP2_DP_FE_TEST_DEBUG_DATA                                             0x4cdb
#define mmDP3_DP_FE_TEST_DEBUG_DATA                                             0x4ddb
#define mmDP4_DP_FE_TEST_DEBUG_DATA                                             0x4edb
#define mmDP5_DP_FE_TEST_DEBUG_DATA                                             0x4fdb
#define mmDP6_DP_FE_TEST_DEBUG_DATA                                             0x54db
#define mmAUX_CONTROL                                                           0x5c00
#define mmDP_AUX0_AUX_CONTROL                                                   0x5c00
#define mmDP_AUX1_AUX_CONTROL                                                   0x5c1c
#define mmDP_AUX2_AUX_CONTROL                                                   0x5c38
#define mmDP_AUX3_AUX_CONTROL                                                   0x5c54
#define mmDP_AUX4_AUX_CONTROL                                                   0x5c70
#define mmDP_AUX5_AUX_CONTROL                                                   0x5c8c
#define mmAUX_SW_CONTROL                                                        0x5c01
#define mmDP_AUX0_AUX_SW_CONTROL                                                0x5c01
#define mmDP_AUX1_AUX_SW_CONTROL                                                0x5c1d
#define mmDP_AUX2_AUX_SW_CONTROL                                                0x5c39
#define mmDP_AUX3_AUX_SW_CONTROL                                                0x5c55
#define mmDP_AUX4_AUX_SW_CONTROL                                                0x5c71
#define mmDP_AUX5_AUX_SW_CONTROL                                                0x5c8d
#define mmAUX_ARB_CONTROL                                                       0x5c02
#define mmDP_AUX0_AUX_ARB_CONTROL                                               0x5c02
#define mmDP_AUX1_AUX_ARB_CONTROL                                               0x5c1e
#define mmDP_AUX2_AUX_ARB_CONTROL                                               0x5c3a
#define mmDP_AUX3_AUX_ARB_CONTROL                                               0x5c56
#define mmDP_AUX4_AUX_ARB_CONTROL                                               0x5c72
#define mmDP_AUX5_AUX_ARB_CONTROL                                               0x5c8e
#define mmAUX_INTERRUPT_CONTROL                                                 0x5c03
#define mmDP_AUX0_AUX_INTERRUPT_CONTROL                                         0x5c03
#define mmDP_AUX1_AUX_INTERRUPT_CONTROL                                         0x5c1f
#define mmDP_AUX2_AUX_INTERRUPT_CONTROL                                         0x5c3b
#define mmDP_AUX3_AUX_INTERRUPT_CONTROL                                         0x5c57
#define mmDP_AUX4_AUX_INTERRUPT_CONTROL                                         0x5c73
#define mmDP_AUX5_AUX_INTERRUPT_CONTROL                                         0x5c8f
#define mmAUX_SW_STATUS                                                         0x5c04
#define mmDP_AUX0_AUX_SW_STATUS                                                 0x5c04
#define mmDP_AUX1_AUX_SW_STATUS                                                 0x5c20
#define mmDP_AUX2_AUX_SW_STATUS                                                 0x5c3c
#define mmDP_AUX3_AUX_SW_STATUS                                                 0x5c58
#define mmDP_AUX4_AUX_SW_STATUS                                                 0x5c74
#define mmDP_AUX5_AUX_SW_STATUS                                                 0x5c90
#define mmAUX_LS_STATUS                                                         0x5c05
#define mmDP_AUX0_AUX_LS_STATUS                                                 0x5c05
#define mmDP_AUX1_AUX_LS_STATUS                                                 0x5c21
#define mmDP_AUX2_AUX_LS_STATUS                                                 0x5c3d
#define mmDP_AUX3_AUX_LS_STATUS                                                 0x5c59
#define mmDP_AUX4_AUX_LS_STATUS                                                 0x5c75
#define mmDP_AUX5_AUX_LS_STATUS                                                 0x5c91
#define mmAUX_SW_DATA                                                           0x5c06
#define mmDP_AUX0_AUX_SW_DATA                                                   0x5c06
#define mmDP_AUX1_AUX_SW_DATA                                                   0x5c22
#define mmDP_AUX2_AUX_SW_DATA                                                   0x5c3e
#define mmDP_AUX3_AUX_SW_DATA                                                   0x5c5a
#define mmDP_AUX4_AUX_SW_DATA                                                   0x5c76
#define mmDP_AUX5_AUX_SW_DATA                                                   0x5c92
#define mmAUX_LS_DATA                                                           0x5c07
#define mmDP_AUX0_AUX_LS_DATA                                                   0x5c07
#define mmDP_AUX1_AUX_LS_DATA                                                   0x5c23
#define mmDP_AUX2_AUX_LS_DATA                                                   0x5c3f
#define mmDP_AUX3_AUX_LS_DATA                                                   0x5c5b
#define mmDP_AUX4_AUX_LS_DATA                                                   0x5c77
#define mmDP_AUX5_AUX_LS_DATA                                                   0x5c93
#define mmAUX_DPHY_TX_REF_CONTROL                                               0x5c08
#define mmDP_AUX0_AUX_DPHY_TX_REF_CONTROL                                       0x5c08
#define mmDP_AUX1_AUX_DPHY_TX_REF_CONTROL                                       0x5c24
#define mmDP_AUX2_AUX_DPHY_TX_REF_CONTROL                                       0x5c40
#define mmDP_AUX3_AUX_DPHY_TX_REF_CONTROL                                       0x5c5c
#define mmDP_AUX4_AUX_DPHY_TX_REF_CONTROL                                       0x5c78
#define mmDP_AUX5_AUX_DPHY_TX_REF_CONTROL                                       0x5c94
#define mmAUX_DPHY_TX_CONTROL                                                   0x5c09
#define mmDP_AUX0_AUX_DPHY_TX_CONTROL                                           0x5c09
#define mmDP_AUX1_AUX_DPHY_TX_CONTROL                                           0x5c25
#define mmDP_AUX2_AUX_DPHY_TX_CONTROL                                           0x5c41
#define mmDP_AUX3_AUX_DPHY_TX_CONTROL                                           0x5c5d
#define mmDP_AUX4_AUX_DPHY_TX_CONTROL                                           0x5c79
#define mmDP_AUX5_AUX_DPHY_TX_CONTROL                                           0x5c95
#define mmAUX_DPHY_RX_CONTROL0                                                  0x5c0a
#define mmDP_AUX0_AUX_DPHY_RX_CONTROL0                                          0x5c0a
#define mmDP_AUX1_AUX_DPHY_RX_CONTROL0                                          0x5c26
#define mmDP_AUX2_AUX_DPHY_RX_CONTROL0                                          0x5c42
#define mmDP_AUX3_AUX_DPHY_RX_CONTROL0                                          0x5c5e
#define mmDP_AUX4_AUX_DPHY_RX_CONTROL0                                          0x5c7a
#define mmDP_AUX5_AUX_DPHY_RX_CONTROL0                                          0x5c96
#define mmAUX_DPHY_RX_CONTROL1                                                  0x5c0b
#define mmDP_AUX0_AUX_DPHY_RX_CONTROL1                                          0x5c0b
#define mmDP_AUX1_AUX_DPHY_RX_CONTROL1                                          0x5c27
#define mmDP_AUX2_AUX_DPHY_RX_CONTROL1                                          0x5c43
#define mmDP_AUX3_AUX_DPHY_RX_CONTROL1                                          0x5c5f
#define mmDP_AUX4_AUX_DPHY_RX_CONTROL1                                          0x5c7b
#define mmDP_AUX5_AUX_DPHY_RX_CONTROL1                                          0x5c97
#define mmAUX_DPHY_TX_STATUS                                                    0x5c0c
#define mmDP_AUX0_AUX_DPHY_TX_STATUS                                            0x5c0c
#define mmDP_AUX1_AUX_DPHY_TX_STATUS                                            0x5c28
#define mmDP_AUX2_AUX_DPHY_TX_STATUS                                            0x5c44
#define mmDP_AUX3_AUX_DPHY_TX_STATUS                                            0x5c60
#define mmDP_AUX4_AUX_DPHY_TX_STATUS                                            0x5c7c
#define mmDP_AUX5_AUX_DPHY_TX_STATUS                                            0x5c98
#define mmAUX_DPHY_RX_STATUS                                                    0x5c0d
#define mmDP_AUX0_AUX_DPHY_RX_STATUS                                            0x5c0d
#define mmDP_AUX1_AUX_DPHY_RX_STATUS                                            0x5c29
#define mmDP_AUX2_AUX_DPHY_RX_STATUS                                            0x5c45
#define mmDP_AUX3_AUX_DPHY_RX_STATUS                                            0x5c61
#define mmDP_AUX4_AUX_DPHY_RX_STATUS                                            0x5c7d
#define mmDP_AUX5_AUX_DPHY_RX_STATUS                                            0x5c99
#define mmAUX_GTC_SYNC_CONTROL                                                  0x5c0e
#define mmDP_AUX0_AUX_GTC_SYNC_CONTROL                                          0x5c0e
#define mmDP_AUX1_AUX_GTC_SYNC_CONTROL                                          0x5c2a
#define mmDP_AUX2_AUX_GTC_SYNC_CONTROL                                          0x5c46
#define mmDP_AUX3_AUX_GTC_SYNC_CONTROL                                          0x5c62
#define mmDP_AUX4_AUX_GTC_SYNC_CONTROL                                          0x5c7e
#define mmDP_AUX5_AUX_GTC_SYNC_CONTROL                                          0x5c9a
#define mmAUX_GTC_SYNC_ERROR_CONTROL                                            0x5c0f
#define mmDP_AUX0_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c0f
#define mmDP_AUX1_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c2b
#define mmDP_AUX2_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c47
#define mmDP_AUX3_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c63
#define mmDP_AUX4_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c7f
#define mmDP_AUX5_AUX_GTC_SYNC_ERROR_CONTROL                                    0x5c9b
#define mmAUX_GTC_SYNC_CONTROLLER_STATUS                                        0x5c10
#define mmDP_AUX0_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c10
#define mmDP_AUX1_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c2c
#define mmDP_AUX2_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c48
#define mmDP_AUX3_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c64
#define mmDP_AUX4_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c80
#define mmDP_AUX5_AUX_GTC_SYNC_CONTROLLER_STATUS                                0x5c9c
#define mmAUX_GTC_SYNC_STATUS                                                   0x5c11
#define mmDP_AUX0_AUX_GTC_SYNC_STATUS                                           0x5c11
#define mmDP_AUX1_AUX_GTC_SYNC_STATUS                                           0x5c2d
#define mmDP_AUX2_AUX_GTC_SYNC_STATUS                                           0x5c49
#define mmDP_AUX3_AUX_GTC_SYNC_STATUS                                           0x5c65
#define mmDP_AUX4_AUX_GTC_SYNC_STATUS                                           0x5c81
#define mmDP_AUX5_AUX_GTC_SYNC_STATUS                                           0x5c9d
#define mmAUX_GTC_SYNC_DATA                                                     0x5c12
#define mmDP_AUX0_AUX_GTC_SYNC_DATA                                             0x5c12
#define mmDP_AUX1_AUX_GTC_SYNC_DATA                                             0x5c2e
#define mmDP_AUX2_AUX_GTC_SYNC_DATA                                             0x5c4a
#define mmDP_AUX3_AUX_GTC_SYNC_DATA                                             0x5c66
#define mmDP_AUX4_AUX_GTC_SYNC_DATA                                             0x5c82
#define mmDP_AUX5_AUX_GTC_SYNC_DATA                                             0x5c9e
#define mmAUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                                    0x5c13
#define mmDP_AUX0_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c13
#define mmDP_AUX1_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c2f
#define mmDP_AUX2_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c4b
#define mmDP_AUX3_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c67
#define mmDP_AUX4_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c83
#define mmDP_AUX5_AUX_GTC_SYNC_PHASE_OFFSET_OVERRIDE                            0x5c9f
#define mmAUX_TEST_DEBUG_INDEX                                                  0x5c14
#define mmDP_AUX0_AUX_TEST_DEBUG_INDEX                                          0x5c14
#define mmDP_AUX1_AUX_TEST_DEBUG_INDEX                                          0x5c30
#define mmDP_AUX2_AUX_TEST_DEBUG_INDEX                                          0x5c4c
#define mmDP_AUX3_AUX_TEST_DEBUG_INDEX                                          0x5c68
#define mmDP_AUX4_AUX_TEST_DEBUG_INDEX                                          0x5c84
#define mmDP_AUX5_AUX_TEST_DEBUG_INDEX                                          0x5ca0
#define mmAUX_TEST_DEBUG_DATA                                                   0x5c15
#define mmDP_AUX0_AUX_TEST_DEBUG_DATA                                           0x5c15
#define mmDP_AUX1_AUX_TEST_DEBUG_DATA                                           0x5c31
#define mmDP_AUX2_AUX_TEST_DEBUG_DATA                                           0x5c4d
#define mmDP_AUX3_AUX_TEST_DEBUG_DATA                                           0x5c69
#define mmDP_AUX4_AUX_TEST_DEBUG_DATA                                           0x5c85
#define mmDP_AUX5_AUX_TEST_DEBUG_DATA                                           0x5ca1
#define ixDP_AUX_DEBUG_A                                                        0x10
#define ixDP_AUX_DEBUG_B                                                        0x11
#define ixDP_AUX_DEBUG_C                                                        0x12
#define ixDP_AUX_DEBUG_D                                                        0x13
#define ixDP_AUX_DEBUG_E                                                        0x14
#define ixDP_AUX_DEBUG_F                                                        0x15
#define ixDP_AUX_DEBUG_G                                                        0x16
#define ixDP_AUX_DEBUG_H                                                        0x17
#define ixDP_AUX_DEBUG_I                                                        0x18
#define ixDP_AUX_DEBUG_J                                                        0x19
#define ixDP_AUX_DEBUG_K                                                        0x1a
#define ixDP_AUX_DEBUG_L                                                        0x1b
#define ixDP_AUX_DEBUG_M                                                        0x1c
#define ixDP_AUX_DEBUG_N                                                        0x1d
#define ixDP_AUX_DEBUG_O                                                        0x1e
#define ixDP_AUX_DEBUG_P                                                        0x1f
#define ixDP_AUX_DEBUG_Q                                                        0x20
#define mmDVO_ENABLE                                                            0x16a0
#define mmDVO_SOURCE_SELECT                                                     0x16a1
#define mmDVO_OUTPUT                                                            0x16a2
#define mmDVO_CONTROL                                                           0x16a3
#define mmDVO_CRC_EN                                                            0x16a4
#define mmDVO_CRC2_SIG_MASK                                                     0x16a5
#define mmDVO_CRC2_SIG_RESULT                                                   0x16a6
#define mmDVO_FIFO_ERROR_STATUS                                                 0x16a7
#define mmDVO_TEST_DEBUG_INDEX                                                  0x16a8
#define mmDVO_TEST_DEBUG_DATA                                                   0x16a9
#define mmFBC_CNTL                                                              0x280
#define mmFBC_IDLE_MASK                                                         0x281
#define mmFBC_IDLE_FORCE_CLEAR_MASK                                             0x282
#define mmFBC_START_STOP_DELAY                                                  0x283
#define mmFBC_COMP_CNTL                                                         0x284
#define mmFBC_COMP_MODE                                                         0x285
#define mmFBC_DEBUG0                                                            0x286
#define mmFBC_DEBUG1                                                            0x287
#define mmFBC_DEBUG2                                                            0x288
#define mmFBC_IND_LUT0                                                          0x289
#define mmFBC_IND_LUT1                                                          0x28a
#define mmFBC_IND_LUT2                                                          0x28b
#define mmFBC_IND_LUT3                                                          0x28c
#define mmFBC_IND_LUT4                                                          0x28d
#define mmFBC_IND_LUT5                                                          0x28e
#define mmFBC_IND_LUT6                                                          0x28f
#define mmFBC_IND_LUT7                                                          0x290
#define mmFBC_IND_LUT8                                                          0x291
#define mmFBC_IND_LUT9                                                          0x292
#define mmFBC_IND_LUT10                                                         0x293
#define mmFBC_IND_LUT11                                                         0x294
#define mmFBC_IND_LUT12                                                         0x295
#define mmFBC_IND_LUT13                                                         0x296
#define mmFBC_IND_LUT14                                                         0x297
#define mmFBC_IND_LUT15                                                         0x298
#define mmFBC_CSM_REGION_OFFSET_01                                              0x299
#define mmFBC_CSM_REGION_OFFSET_23                                              0x29a
#define mmFBC_CLIENT_REGION_MASK                                                0x29b
#define mmFBC_DEBUG_COMP                                                        0x29c
#define mmFBC_DEBUG_CSR                                                         0x29d
#define mmFBC_DEBUG_CSR_RDATA                                                   0x29e
#define mmFBC_DEBUG_CSR_WDATA                                                   0x29f
#define mmFBC_DEBUG_CSR_RDATA_HI                                                0x2a0
#define mmFBC_DEBUG_CSR_WDATA_HI                                                0x2a1
#define mmFBC_MISC                                                              0x2a2
#define mmFBC_STATUS                                                            0x2a3
#define mmFBC_TEST_DEBUG_INDEX                                                  0x2a4
#define mmFBC_TEST_DEBUG_DATA                                                   0x2a5
#define mmFMT_CLAMP_COMPONENT_R                                                 0x1be8
#define mmFMT0_FMT_CLAMP_COMPONENT_R                                            0x1be8
#define mmFMT1_FMT_CLAMP_COMPONENT_R                                            0x1de8
#define mmFMT2_FMT_CLAMP_COMPONENT_R                                            0x1fe8
#define mmFMT3_FMT_CLAMP_COMPONENT_R                                            0x41e8
#define mmFMT4_FMT_CLAMP_COMPONENT_R                                            0x43e8
#define mmFMT5_FMT_CLAMP_COMPONENT_R             