                      0x4c1d
#define mmDIG3_AFMT_ISRC2_3                                                     0x4d1d
#define mmDIG4_AFMT_ISRC2_3                                                     0x4e1d
#define mmDIG5_AFMT_ISRC2_3                                                     0x4f1d
#define mmDIG6_AFMT_ISRC2_3                                                     0x541d
#define mmAFMT_AVI_INFO0                                                        0x4a1e
#define mmDIG0_AFMT_AVI_INFO0                                                   0x4a1e
#define mmDIG1_AFMT_AVI_INFO0                                                   0x4b1e
#define mmDIG2_AFMT_AVI_INFO0                                                   0x4c1e
#define mmDIG3_AFMT_AVI_INFO0                                                   0x4d1e
#define mmDIG4_AFMT_AVI_INFO0                                                   0x4e1e
#define mmDIG5_AFMT_AVI_INFO0                                                   0x4f1e
#define mmDIG6_AFMT_AVI_INFO0                                                   0x541e
#define mmAFMT_AVI_INFO1                                                        0x4a1f
#define mmDIG0_AFMT_AVI_INFO1                                                   0x4a1f
#define mmDIG1_AFMT_AVI_INFO1                                                   0x4b1f
#define mmDIG2_AFMT_AVI_INFO1                                                   0x4c1f
#define mmDIG3_AFMT_AVI_INFO1                                                   0x4d1f
#define mmDIG4_AFMT_AVI_INFO1                                                   0x4e1f
#define mmDIG5_AFMT_AVI_INFO1                                                   0x4f1f
#define mmDIG6_AFMT_AVI_INFO1                                                   0x541f
#define mmAFMT_AVI_INFO2                                                        0x4a20
#define mmDIG0_AFMT_AVI_INFO2                                                   0x4a20
#define mmDIG1_AFMT_AVI_INFO2                                                   0x4b20
#define mmDIG2_AFMT_AVI_INFO2                                                   0x4c20
#define mmDIG3_AFMT_AVI_INFO2                                                   0x4d20
#define mmDIG4_AFMT_AVI_INFO2                                                   0x4e20
#define mmDIG5_AFMT_AVI_INFO2                                                   0x4f20
#define mmDIG6_AFMT_AVI_INFO2                                                   0x5420
#define mmAFMT_AVI_INFO3                                                        0x4a21
#define mmDIG0_AFMT_AVI_INFO3                                                   0x4a21
#define mmDIG1_AFMT_AVI_INFO3                                                   0x4b21
#define mmDIG2_AFMT_AVI_INFO3                                                   0x4c21
#define mmDIG3_AFMT_AVI_INFO3                                                   0x4d21
#define mmDIG4_AFMT_AVI_INFO3                                                   0x4e21
#define mmDIG5_AFMT_AVI_INFO3                                                   0x4f21
#define mmDIG6_AFMT_AVI_INFO3                                                   0x5421
#define mmAFMT_MPEG_INFO0                                                       0x4a22
#define mmDIG0_AFMT_MPEG_INFO0                                                  0x4a22
#define mmDIG1_AFMT_MPEG_INFO0                                                  0x4b22
#define mmDIG2_AFMT_MPEG_INFO0                                                  0x4c22
#define mmDIG3_AFMT_MPEG_INFO0                                                  0x4d22
#define mmDIG4_AFMT_MPEG_INFO0                                                  0x4e22
#define mmDIG5_AFMT_MPEG_INFO0                                                  0x4f22
#define mmDIG6_AFMT_MPEG_INFO0                                                  0x5422
#define mmAFMT_MPEG_INFO1                                                       0x4a23
#define mmDIG0_AFMT_MPEG_INFO1                                                  0x4a23
#define mmDIG1_AFMT_MPEG_INFO1                                                  0x4b23
#define mmDIG2_AFMT_MPEG_INFO1                                                  0x4c23
#define mmDIG3_AFMT_MPEG_INFO1                                                  0x4d23
#define mmDIG4_AFMT_MPEG_INFO1                                                  0x4e23
#define mmDIG5_AFMT_MPEG_INFO1                                                  0x4f23
#define mmDIG6_AFMT_MPEG_INFO1                                                  0x5423
#define mmAFMT_GENERIC_HDR                                                      0x4a24
#define mmDIG0_AFMT_GENERIC_HDR                                                 0x4a24
#define mmDIG1_AFMT_GENERIC_HDR                                                 0x4b24
#define mmDIG2_AFMT_GENERIC_HDR                                                 0x4c24
#define mmDIG3_AFMT_GENERIC_HDR                                                 0x4d24
#define mmDIG4_AFMT_GENERIC_HDR                                                 0x4e24
#define mmDIG5_AFMT_GENERIC_HDR                                                 0x4f24
#define mmDIG6_AFMT_GENERIC_HDR                                                 0x5424
#define mmAFMT_GENERIC_0                                                        0x4a25
#define mmDIG0_AFMT_GENERIC_0                                                   0x4a25
#define mmDIG1_AFMT_GENERIC_0                                                   0x4b25
#define mmDIG2_AFMT_GENERIC_0                                                   0x4c25
#define mmDIG3_AFMT_GENERIC_0                                                   0x4d25
#define mmDIG4_AFMT_GENERIC_0                                                   0x4e25
#define mmDIG5_AFMT_GENERIC_0                                                   0x4f25
#define mmDIG6_AFMT_GENERIC_0                                                   0x5425
#define mmAFMT_GENERIC_1                                                        0x4a26
#define mmDIG0_AFMT_GENERIC_1                                                   0x4a26
#define mmDIG1_AFMT_GENERIC_1                                                   0x4b26
#define mmDIG2_AFMT_GENERIC_1                                                   0x4c26
#define mmDIG3_AFMT_GENERIC_1                                                   0x4d26
#define mmDIG4_AFMT_GENERIC_1                                                   0x4e26
#define mmDIG5_AFMT_GENERIC_1                                                   0x4f26
#define mmDIG6_AFMT_GENERIC_1                                                   0x5426
#define mmAFMT_GENERIC_2                                                        0x4a27
#define mmDIG0_AFMT_GENERIC_2                                                   0x4a27
#define mmDIG1_AFMT_GENERIC_2                                                   0x4b27
#define mmDIG2_AFMT_GENERIC_2                                                   0x4c27
#define mmDIG3_AFMT_GENERIC_2                                                   0x4d27
#define mmDIG4_AFMT_GENERIC_2                                                   0x4e27
#define mmDIG5_AFMT_GENERIC_2                                                   0x4f27
#define mmDIG6_AFMT_GENERIC_2                                                   0x5427
#define mmAFMT_GENERIC_3                                                        0x4a28
#define mmDIG0_AFMT_GENERIC_3                                                   0x4a28
#define mmDIG1_AFMT_GENERIC_3                                                   0x4b28
#define mmDIG2_AFMT_GENERIC_3                                                   0x4c28
#define mmDIG3_AFMT_GENERIC_3                                                   0x4d28
#define mmDIG4_AFMT_GENERIC_3                                                   0x4e28
#define mmDIG5_AFMT_GENERIC_3                                                   0x4f28
#define mmDIG6_AFMT_GENERIC_3                                                   0x5428
#define mmAFMT_GENERIC_4                                                        0x4a29
#define mmDIG0_AFMT_GENERIC_4                                                   0x4a29
#define mmDIG1_AFMT_GENERIC_4                                                   0x4b29
#define mmDIG2_AFMT_GENERIC_4                                                   0x4c29
#define mmDIG3_AFMT_GENERIC_4                                                   0x4d29
#define mmDIG4_AFMT_GENERIC_4                                                   0x4e29
#define mmDIG5_AFMT_GENERIC_4                                                   0x4f29
#define mmDIG6_AFMT_GENERIC_4                                                   0x5429
#define mmAFMT_GENERIC_5                                                        0x4a2a
#define mmDIG0_AFMT_GENERIC_5                                                   0x4a2a
#define mmDIG1_AFMT_GENERIC_5                                                   0x4b2a
#define mmDIG2_AFMT_GENERIC_5                                                   0x4c2a
#define mmDIG3_AFMT_GENERIC_5                                                   0x4d2a
#define mmDIG4_AFMT_GENERIC_5                                                   0x4e2a
#define mmDIG5_AFMT_GENERIC_5                                                   0x4f2a
#define mmDIG6_AFMT_GENERIC_5                                                   0x542a
#define mmAFMT_GENERIC_6                                                        0x4a2b
#define mmDIG0_AFMT_GENERIC_6                                                   0x4a2b
#define mmDIG1_AFMT_GENERIC_6                                                   0x4b2b
#define mmDIG2_AFMT_GENERIC_6                                                   0x4c2b
#define mmDIG3_AFMT_GENERIC_6                                                   0x4d2b
#define mmDIG4_AFMT_GENERIC_6                                                   0x4e2b
#define mmDIG5_AFMT_GENERIC_6                                                   0x4f2b
#define mmDIG6_AFMT_GENERIC_6                                                   0x542b
#define mmAFMT_GENERIC_7                                                        0x4a2c
#define mmDIG0_AFMT_GENERIC_7                                                   0x4a2c
#define mmDIG1_AFMT_GENERIC_7                                                   0x4b2c
#define mmDIG2_AFMT_GENERIC_7                                                   0x4c2c
#define mmDIG3_AFMT_GENERIC_7                                                   0x4d2c
#define mmDIG4_AFMT_GENERIC_7                                                   0x4e2c
#define mmDIG5_AFMT_GENERIC_7                                                   0x4f2c
#define mmDIG6_AFMT_GENERIC_7                                                   0x542c
#define mmHDMI_GENERIC_PACKET_CONTROL1                                          0x4a2d
#define mmDIG0_HDMI_GENERIC_PACKET_CONTROL1                                     0x4a2d
#define mmDIG1_HDMI_GENERIC_PACKET_CONTROL1                                     0x4b2d
#define mmDIG2_HDMI_GENERIC_PACKET_CONTROL1                                     0x4c2d
#define mmDIG3_HDMI_GENERIC_PACKET_CONTROL1                                     0x4d2d
#define mmDIG4_HDMI_GENERIC_PACKET_CONTROL1                                     0x4e2d
#define mmDIG5_HDMI_GENERIC_PACKET_CONTROL1                                     0x4f2d
#define mmDIG6_HDMI_GENERIC_PACKET_CONTROL1                                     0x542d
#define mmHDMI_ACR_32_0                                                         0x4a2e
#define mmDIG0_HDMI_ACR_32_0                                                    0x4a2e
#define mmDIG1_HDMI_ACR_32_0                                                    0x4b2e
#define mmDIG2_HDMI_ACR_32_0                                                    0x4c2e
#define mmDIG3_HDMI_ACR_32_0                                                    0x4d2e
#define mmDIG4_HDMI_ACR_32_0                                                    0x4e2e
#define mmDIG5_HDMI_ACR_32_0                                                    0x4f2e
#define mmDIG6_HDMI_ACR_32_0                                                    0x542e
#define mmHDMI_ACR_32_1                                                         0x4a2f
#define mmDIG0_HDMI_ACR_32_1                                                    0x4a2f
#define mmDIG1_HDMI_ACR_32_1                                                    0x4b2f
#define mmDIG2_HDMI_ACR_32_1                                                    0x4c2f
#define mmDIG3_HDMI_ACR_32_1                                                    0x4d2f
#define mmDIG4_HDMI_ACR_32_1                                                    0x4e2f
#define mmDIG5_HDMI_ACR_32_1                                                    0x4f2f
#define mmDIG6_HDMI_ACR_32_1                                                    0x542f
#define mmHDMI_ACR_44_0                                                         0x4a30
#define mmDIG0_HDMI_ACR_44_0                                                    0x4a30
#define mmDIG1_HDMI_ACR_44_0                                                    0x4b30
#define mmDIG2_HDMI_ACR_44_0                                                    0x4c30
#define mmDIG3_HDMI_ACR_44_0                                                    0x4d30
#define mmDIG4_HDMI_ACR_44_0                                                    0x4e30
#define mmDIG5_HDMI_ACR_44_0                                                    0x4f30
#define mmDIG6_HDMI_ACR_44_0                                                    0x5430
#define mmHDMI_ACR_44_1                                                         0x4a31
#define mmDIG0_HDMI_ACR_44_1                                                    0x4a31
#define mmDIG1_HDMI_ACR_44_1                                                    0x4b31
#define mmDIG2_HDMI_ACR_44_1                                                    0x4c31
#define mmDIG3_HDMI_ACR_44_1                                                    0x4d31
#define mmDIG4_HDMI_ACR_44_1                                                    0x4e31
#define mmDIG5_HDMI_ACR_44_1                                                    0x4f31
#define mmDIG6_HDMI_ACR_44_1                                                    0x5431
#define mmHDMI_ACR_48_0                                                         0x4a32
#define mmDIG0_HDMI_ACR_48_0                                                    0x4a32
#define mmDIG1_HDMI_ACR_48_0                                                    0x4b32
#define mmDIG2_HDMI_ACR_48_0                                                    0x4c32
#define mmDIG3_HDMI_ACR_48_0                                                    0x4d32
#define mmDIG4_HDMI_ACR_48_0                                                    0x4e32
#define mmDIG5_HDMI_ACR_48_0                                                    0x4f32
#define mmDIG6_HDMI_ACR_48_0                                                    0x5432
#define mmHDMI_ACR_48_1                                                         0x4a33
#define mmDIG0_HDMI_ACR_48_1                                                    0x4a33
#define mmDIG1_HDMI_ACR_48_1                                                    0x4b33
#define mmDIG2_HDMI_ACR_48_1                                                    0x4c33
#define mmDIG3_HDMI_ACR_48_1                                                    0x4d33
#define mmDIG4_HDMI_ACR_48_1                                                    0x4e33
#define mmDIG5_HDMI_ACR_48_1                                                    0x4f33
#define mmDIG6_HDMI_ACR_48_1                                                    0x5433
#define mmHDMI_ACR_STATUS_0                                                     0x4a34
#define mmDIG0_HDMI_ACR_STATUS_0                                                0x4a34
#define mmDIG1_HDMI_ACR_STATUS_0                                                0x4b34
#define mmDIG2_HDMI_ACR_STATUS_0                                                0x4c34
#define mmDIG3_HDMI_ACR_STATUS_0                                                0x4d34
#define mmDIG4_HDMI_ACR_STATUS_0                                           