        0x418a
#define mmCRTC4_CRTC_V_TOTAL_CONTROL                                            0x438a
#define mmCRTC5_CRTC_V_TOTAL_CONTROL                                            0x458a
#define mmCRTC6_CRTC_V_TOTAL_CONTROL                                            0x478a
#define mmCRTC_V_TOTAL_INT_STATUS                                               0x1b8b
#define mmCRTC0_CRTC_V_TOTAL_INT_STATUS                                         0x1b8b
#define mmCRTC1_CRTC_V_TOTAL_INT_STATUS                                         0x1d8b
#define mmCRTC2_CRTC_V_TOTAL_INT_STATUS                                         0x1f8b
#define mmCRTC3_CRTC_V_TOTAL_INT_STATUS                                         0x418b
#define mmCRTC4_CRTC_V_TOTAL_INT_STATUS                                         0x438b
#define mmCRTC5_CRTC_V_TOTAL_INT_STATUS                                         0x458b
#define mmCRTC6_CRTC_V_TOTAL_INT_STATUS                                         0x478b
#define mmCRTC_VSYNC_NOM_INT_STATUS                                             0x1b8c
#define mmCRTC0_CRTC_VSYNC_NOM_INT_STATUS                                       0x1b8c
#define mmCRTC1_CRTC_VSYNC_NOM_INT_STATUS                                       0x1d8c
#define mmCRTC2_CRTC_VSYNC_NOM_INT_STATUS                                       0x1f8c
#define mmCRTC3_CRTC_VSYNC_NOM_INT_STATUS                                       0x418c
#define mmCRTC4_CRTC_VSYNC_NOM_INT_STATUS                                       0x438c
#define mmCRTC5_CRTC_VSYNC_NOM_INT_STATUS                                       0x458c
#define mmCRTC6_CRTC_VSYNC_NOM_INT_STATUS                                       0x478c
#define mmCRTC_V_BLANK_START_END                                                0x1b8d
#define mmCRTC0_CRTC_V_BLANK_START_END                                          0x1b8d
#define mmCRTC1_CRTC_V_BLANK_START_END                                          0x1d8d
#define mmCRTC2_CRTC_V_BLANK_START_END                                          0x1f8d
#define mmCRTC3_CRTC_V_BLANK_START_END                                          0x418d
#define mmCRTC4_CRTC_V_BLANK_START_END                                          0x438d
#define mmCRTC5_CRTC_V_BLANK_START_END                                          0x458d
#define mmCRTC6_CRTC_V_BLANK_START_END                                          0x478d
#define mmCRTC_V_SYNC_A                                                         0x1b8e
#define mmCRTC0_CRTC_V_SYNC_A                                                   0x1b8e
#define mmCRTC1_CRTC_V_SYNC_A                                                   0x1d8e
#define mmCRTC2_CRTC_V_SYNC_A                                                   0x1f8e
#define mmCRTC3_CRTC_V_SYNC_A                                                   0x418e
#define mmCRTC4_CRTC_V_SYNC_A                                                   0x438e
#define mmCRTC5_CRTC_V_SYNC_A                                                   0x458e
#define mmCRTC6_CRTC_V_SYNC_A                                                   0x478e
#define mmCRTC_V_SYNC_A_CNTL                                                    0x1b8f
#define mmCRTC0_CRTC_V_SYNC_A_CNTL                                              0x1b8f
#define mmCRTC1_CRTC_V_SYNC_A_CNTL                                              0x1d8f
#define mmCRTC2_CRTC_V_SYNC_A_CNTL                                              0x1f8f
#define mmCRTC3_CRTC_V_SYNC_A_CNTL                                              0x418f
#define mmCRTC4_CRTC_V_SYNC_A_CNTL                                              0x438f
#define mmCRTC5_CRTC_V_SYNC_A_CNTL                                              0x458f
#define mmCRTC6_CRTC_V_SYNC_A_CNTL                                              0x478f
#define mmCRTC_V_SYNC_B                                                         0x1b90
#define mmCRTC0_CRTC_V_SYNC_B      