                           0x5ae8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED101                                       0x5ae9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED102                                       0x5aea
#define mmDCRX_PHY_MACRO_CNTL_RESERVED103                                       0x5aeb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED104                                       0x5aec
#define mmDCRX_PHY_MACRO_CNTL_RESERVED105                                       0x5aed
#define mmDCRX_PHY_MACRO_CNTL_RESERVED106                                       0x5aee
#define mmDCRX_PHY_MACRO_CNTL_RESERVED107                                       0x5aef
#define mmDCRX_PHY_MACRO_CNTL_RESERVED108                                       0x5af0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED109                                       0x5af1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED110                                       0x5af2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED111                                       0x5af3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED112                                       0x5af4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED113                                       0x5af5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED114                                       0x5af6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED115                                       0x5af7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED116                                       0x5af8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED117                                       0x5af9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED118                                       0x5afa
#define mmDCRX_PHY_MACRO_CNTL_RESERVED119                                       0x5afb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED120                                       0x5afc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED121                                       0x5afd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED122                                       0x5afe
#define mmDCRX_PHY_MACRO_CNTL_RESERVED123                                       0x5aff
#define mmDCRX_PHY_MACRO_CNTL_RESERVED124                                       0x5b00
#define mmDCRX_PHY_MACRO_CNTL_RESERVED125                                       0x5b01
#define mmDCRX_PHY_MACRO_CNTL_RESERVED126                                       0x5b02
#define mmDCRX_PHY_MACRO_CNTL_RESERVED127                                       0x5b03
#define mmDCRX_PHY_MACRO_CNTL_RESERVED128                                       0x5b04
#define mmDCRX_PHY_MACRO_CNTL_RESERVED129                                       0x5b05
#define mmDCRX_PHY_MACRO_CNTL_RESERVED130                                       0x5b06
#define mmDCRX_PHY_MACRO_CNTL_RESERVED131                                       0x5b07
#define mmDCRX_PHY_MACRO_CNTL_RESERVED132                                       0x5b08
#define mmDCRX_PHY_MACRO_CNTL_RESERVED133                                       0x5b09
#define mmDCRX_PHY_MACRO_CNTL_RESERVED134                                       0x5b0a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED135                                       0x5b0b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED136                                       0x5b0c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED137                                       0x5b0d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED138                                       0x5b0e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED139                                       0x5b0f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED140                                       0x5b10
#define mmDCRX_PHY_MACRO_CNTL_RESERVED141                                       0x5b11
#define mmDCRX_PHY_MACRO_CNTL_RESERVED142                                       0x5b12
#define mmDCRX_PHY_MACRO_CNTL_RESERVED143                                       0x5b13
#define mmDCRX_PHY_MACRO_CNTL_RESERVED144                                       0x5b14
#define mmDCRX_PHY_MACRO_CNTL_RESERVED145                                       0x5b15
#define mmDCRX_PHY_MACRO_CNTL_RESERVED146                                       0x5b16
#define mmDCRX_PHY_MACRO_CNTL_RESERVED147                                       0x5b17
#define mmDCRX_PHY_MACRO_CNTL_RESERVED148                                       0x5b18
#define mmDCRX_PHY_MACRO_CNTL_RESERVED149                                       0x5b19
#define mmDCRX_PHY_MACRO_CNTL_RESERVED150                                       0x5b1a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED151                                       0x5b1b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED152                                       0x5b1c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED153                                       0x5b1d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED154                                       0x5b1e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED155                                       0x5b1f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED156                                       0x5b20
#define mmDCRX_PHY_MACRO_CNTL_RESERVED157                                       0x5b21
#define mmDCRX_PHY_MACRO_CNTL_RESERVED158                                       0x5b22
#define mmDCRX_PHY_MACRO_CNTL_RESERVED159                                       0x5b23
#define mmDCRX_PHY_MACRO_CNTL_RESERVED160                                       0x5b24
#define mmDCRX_PHY_MACRO_CNTL_RESERVED161                                       0x5b25
#define mmDCRX_PHY_MACRO_CNTL_RESERVED162                                       0x5b26
#define mmDCRX_PHY_MACRO_CNTL_RESERVED163                                       0x5b27
#define mmDCRX_PHY_MACRO_CNTL_RESERVED164                                       0x5b28
#define mmDCRX_PHY_MACRO_CNTL_RESERVED165                                       0x5b29
#define mmDCRX_PHY_MACRO_CNTL_RESERVED166                                       0x5b2a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED167                                       0x5b2b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED168                                       0x5b2c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED169                                       0x5b2d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED170                                       0x5b2e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED171                                       0x5b2f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED172                                       0x5b30
#define mmDCRX_PHY_MACRO_CNTL_RESERVED173                                       0x5b31
#define mmDCRX_PHY_MACRO_CNTL_RESERVED174                                       0x5b32
#define mmDCRX_PHY_MACRO_CNTL_RESERVED175                                       0x5b33
#define mmDCRX_PHY_MACRO_CNTL_RESERVED176                                       0x5b34
#define mmDCRX_PHY_MACRO_CNTL_RESERVED177                                       0x5b35
#define mmDCRX_PHY_MACRO_CNTL_RESERVED178                                       0x5b36
#define mmDCRX_PHY_MACRO_CNTL_RESERVED179                                       0x5b37
#define mmDCRX_PHY_MACRO_CNTL_RESERVED180                                       0x5b38
#define mmDCRX_PHY_MACRO_CNTL_RESERVED181                                       0x5b39
#define mmDCRX_PHY_MACRO_CNTL_RESERVED182                                       0x5b3a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED183                                       0x5b3b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED184                                       0x5b3c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED185                                       0x5b3d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED186                                       0x5b3e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED187                                       0x5b3f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED188                                       0x5b40
#define mmDCRX_PHY_MACRO_CNTL_RESERVED189                                       0x5b41
#define mmDCRX_PHY_MACRO_CNTL_RESERVED190                                       0x5b42
#define mmDCRX_PHY_MACRO_CNTL_RESERVED191                                       0x5b43
#define mmDCRX_PHY_MACRO_CNTL_RESERVED192                                       0x5b44
#define mmDCRX_PHY_MACRO_CNTL_RESERVED193                                       0x5b45
#define mmDCRX_PHY_MACRO_CNTL_RESERVED194                                       0x5b46
#define mmDCRX_PHY_MACRO_CNTL_RESERVED195                                       0x5b47
#define mmDCRX_PHY_MACRO_CNTL_RESERVED196                                       0x5b48
#define mmDCRX_PHY_MACRO_CNTL_RESERVED197                                       0x5b49
#define mmDCRX_PHY_MACRO_CNTL_RESERVED198                                       0x5b4a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED199                                       0x5b4b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED200                                       0x5b4c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED201                                       0x5b4d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED202                                       0x5b4e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED203                                       0x5b4f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED204                                       0x5b50
#define mmDCRX_PHY_MACRO_CNTL_RESERVED205                                       0x5b51
#define mmDCRX_PHY_MACRO_CNTL_RESERVED206                                       0x5b52
#define mmDCRX_PHY_MACRO_CNTL_RESERVED207                                       0x5b53
#define mmDCRX_PHY_MACRO_CNTL_RESERVED208                                       0x5b54
#define mmDCRX_PHY_MACRO_CNTL_RESERVED209                                       0x5b55
#define mmDCRX_PHY_MACRO_CNTL_RESERVED210                                       0x5b56
#define mmDCRX_PHY_MACRO_CNTL_RESERVED211                                       0x5b57
#define mmDCRX_PHY_MACRO_CNTL_RESERVED212                                       0x5b58
#define mmDCRX_PHY_MACRO_CNTL_RESERVED213                                       0x5b59
#define mmDCRX_PHY_MACRO_CNTL_RESERVED214                                       0x5b5a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED215                                       0x5b5b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED216                                       0x5b5c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED217                                       0x5b5d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED218                                       0x5b5e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED219                                       0x5b5f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED220                                       0x5b60
#define mmDCRX_PHY_MACRO_CNTL_RESERVED221                                       0x5b61
#define mmDCRX_PHY_MACRO_CNTL_RESERVED222                                       0x5b62
#define mmDCRX_PHY_MACRO_CNTL_RESERVED223                                       0x5b63
#define mmDCRX_PHY_MACRO_CNTL_RESERVED224                                       0x5b64
#define mmDCRX_PHY_MACRO_CNTL_RESERVED225                                       0x5b65
#define mmDCRX_PHY_MACRO_CNTL_RESERVED226                                       0x5b66
#define mmDCRX_PHY_MACRO_CNTL_RESERVED227                                       0x5b67
#define mmDCRX_PHY_MACRO_CNTL_RESERVED228                                       0x5b68
#define mmDCRX_PHY_MACRO_CNTL_RESERVED229                                       0x5b69
#define mmDCRX_PHY_MACRO_CNTL_RESERVED230                                       0x5b6a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED231                                       0x5b6b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED232                                       0x5b6c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED233                                       0x5b6d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED234                                       0x5b6e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED235                                       0x5b6f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED236                                       0x5b70
#define mmDCRX_PHY_MACRO_CNTL_RESERVED237                                       0x5b71
#define mmDCRX_PHY_MACRO_CNTL_RESERVED238                                       0x5b72
#define mmDCRX_PHY_MACRO_CNTL_RESERVED239                                       0x5b73
#define mmDCRX_PHY_MACRO_CNTL_RESERVED240                                       0x5b74
#define mmDCRX_PHY_MACRO_CNTL_RESERVED241                                       0x5b75
#define mmDCRX_PHY_MACRO_CNTL_RESERVED242                                       0x5b76
#define mmDCRX_PHY_MACRO_CNTL_RESERVED243                                       0x5b77
#define mmDCRX_PHY_MACRO_CNTL_RESERVED244                                       0x5b78
#define mmDCRX_PHY_MACRO_CNTL_RESERVED245                                       0x5b79
#define mmDCRX_PHY_MACRO_CNTL_RESERVED246                                       0x5b7a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED247                                       0x5b7b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED248                                       0x5b7c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED249                                       0x5b7d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED250                                       0x5b7e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED251                                       0x5b7f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED252                                       0x5b80
#define mmDCRX_PHY_MACRO_CNTL_RESERVED253                                       0x5b81
#define mmDCRX_PHY_MACRO_CNTL_RESERVED254                                       0x5b82
#define mmDCRX_PHY_MACRO_CNTL_RESERVED255                                       0x5b83
#define mmDCRX_PHY_MACRO_CNTL_RESERVED256                                       0x5b84
#define mmDCRX_PHY_MACRO_CNTL_RESERVED257                                       0x5b85
#define mmDCRX_PHY_MACRO_CNTL_RESERVED258                                       0x5b86
#define mmDCRX_PHY_MACRO_CNTL_RESERVED259                                       0x5b87
#define mmDCRX_PHY_MACRO_CNTL_RESERVED260                                       0x5b88
#define mmDCRX_PHY_MACRO_CNTL_RESERVED261                                       0x5b89
#define mmDCRX_PHY_MACRO_CNTL_RESERVED262                                       0x5b8a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED263                                       0x5b8b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED264                                       0x5b8c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED265                                       0x5b8d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED266                                       0x5b8e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED267                                       0x5b8f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED268                                       0x5b90
#define mmDCRX_PHY_MACRO_CNTL_RESERVED269                                       0x5b91
#define mmDCRX_PHY_MACRO_CNTL_RESERVED270                                       0x5b92
#define mmDCRX_PHY_MACRO_CNTL_RESERVED271                                       0x5b93
#define mmDCRX_PHY_MACRO_CNTL_RESERVED272                                       0x5b94
#define mmDCRX_PHY_MACRO_CNTL_RESERVED273                                       0x5b95
#define mmDCRX_PHY_MACRO_CNTL_RESERVED274                                       0x5b96
#define mmDCRX_PHY_MACRO_CNTL_RESERVED275                                       0x5b97
#define mmDCRX_PHY_MACRO_CNTL_RESERVED276                                       0x5b98
#define mmDCRX_PHY_MACRO_CNTL_RESERVED277                                       0x5b99
#define mmDCRX_PHY_MACRO_CNTL_RESERVED278                                       0x5b9a
#define mmDCRX_PHY_MACRO_CNTL_RESERVED279                                       0x5b9b
#define mmDCRX_PHY_MACRO_CNTL_RESERVED280                                       0x5b9c
#define mmDCRX_PHY_MACRO_CNTL_RESERVED281                                       0x5b9d
#define mmDCRX_PHY_MACRO_CNTL_RESERVED282                                       0x5b9e
#define mmDCRX_PHY_MACRO_CNTL_RESERVED283                                       0x5b9f
#define mmDCRX_PHY_MACRO_CNTL_RESERVED284                                       0x5ba0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED285                                       0x5ba1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED286                                       0x5ba2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED287                                       0x5ba3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED288                                       0x5ba4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED289                                       0x5ba5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED290                                       0x5ba6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED291                                       0x5ba7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED292                                       0x5ba8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED293                                       0x5ba9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED294                                       0x5baa
#define mmDCRX_PHY_MACRO_CNTL_RESERVED295                                       0x5bab
#define mmDCRX_PHY_MACRO_CNTL_RESERVED296                                       0x5bac
#define mmDCRX_PHY_MACRO_CNTL_RESERVED297                                       0x5bad
#define mmDCRX_PHY_MACRO_CNTL_RESERVED298                                       0x5bae
#define mmDCRX_PHY_MACRO_CNTL_RESERVED299                                       0x5baf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED300                                       0x5bb0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED301                                       0x5bb1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED302                                       0x5bb2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED303                                       0x5bb3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED304                                       0x5bb4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED305                                       0x5bb5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED306                                       0x5bb6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED307                                       0x5bb7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED308                                       0x5bb8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED309                                       0x5bb9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED310                                       0x5bba
#define mmDCRX_PHY_MACRO_CNTL_RESERVED311                                       0x5bbb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED312                                       0x5bbc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED313                                       0x5bbd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED314                                       0x5bbe
#define mmDCRX_PHY_MACRO_CNTL_RESERVED315                                       0x5bbf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED316                                       0x5bc0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED317                                       0x5bc1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED318                                       0x5bc2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED319                                       0x5bc3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED320                                       0x5bc4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED321                                       0x5bc5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED322                                       0x5bc6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED323                                       0x5bc7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED324                                       0x5bc8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED325                                       0x5bc9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED326                                       0x5bca
#define mmDCRX_PHY_MACRO_CNTL_RESERVED327                                       0x5bcb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED328                                       0x5bcc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED329                                       0x5bcd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED330                                       0x5bce
#define mmDCRX_PHY_MACRO_CNTL_RESERVED331                                       0x5bcf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED332                                       0x5bd0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED333                                       0x5bd1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED334                                       0x5bd2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED335                                       0x5bd3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED336                                       0x5bd4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED337                                       0x5bd5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED338                                       0x5bd6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED339                                       0x5bd7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED340                                       0x5bd8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED341                                       0x5bd9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED342                                       0x5bda
#define mmDCRX_PHY_MACRO_CNTL_RESERVED343                                       0x5bdb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED344                                       0x5bdc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED345                                       0x5bdd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED346                                       0x5bde
#define mmDCRX_PHY_MACRO_CNTL_RESERVED347                                       0x5bdf
#define mmDCRX_PHY_MACRO_CNTL_RESERVED348                                       0x5be0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED349                                       0x5be1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED350                                       0x5be2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED351                                       0x5be3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED352                                       0x5be4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED353                                       0x5be5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED354                                       0x5be6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED355                                       0x5be7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED356                                       0x5be8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED357                                       0x5be9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED358                                       0x5bea
#define mmDCRX_PHY_MACRO_CNTL_RESERVED359                                       0x5beb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED360                                       0x5bec
#define mmDCRX_PHY_MACRO_CNTL_RESERVED361                                       0x5bed
#define mmDCRX_PHY_MACRO_CNTL_RESERVED362                                       0x5bee
#define mmDCRX_PHY_MACRO_CNTL_RESERVED363                                       0x5bef
#define mmDCRX_PHY_MACRO_CNTL_RESERVED364                                       0x5bf0
#define mmDCRX_PHY_MACRO_CNTL_RESERVED365                                       0x5bf1
#define mmDCRX_PHY_MACRO_CNTL_RESERVED366                                       0x5bf2
#define mmDCRX_PHY_MACRO_CNTL_RESERVED367                                       0x5bf3
#define mmDCRX_PHY_MACRO_CNTL_RESERVED368                                       0x5bf4
#define mmDCRX_PHY_MACRO_CNTL_RESERVED369                                       0x5bf5
#define mmDCRX_PHY_MACRO_CNTL_RESERVED370                                       0x5bf6
#define mmDCRX_PHY_MACRO_CNTL_RESERVED371                                       0x5bf7
#define mmDCRX_PHY_MACRO_CNTL_RESERVED372                                       0x5bf8
#define mmDCRX_PHY_MACRO_CNTL_RESERVED373                                       0x5bf9
#define mmDCRX_PHY_MACRO_CNTL_RESERVED374                                       0x5bfa
#define mmDCRX_PHY_MACRO_CNTL_RESERVED375                                       0x5bfb
#define mmDCRX_PHY_MACRO_CNTL_RESERVED376                                       0x5bfc
#define mmDCRX_PHY_MACRO_CNTL_RESERVED377                                       0x5bfd
#define mmDCRX_PHY_MACRO_CNTL_RESERVED378                                       0x5bfe
#define mmDCRX_PHY_MACRO_CNTL_RESERVED379                                       0x5bff
#define mmDPHY_MACRO_CNTL_RESERVED0                                             0x5d98
#define mmDPHY_MACRO_CNTL_RESERVED1                                             0x5d99
#define mmDPHY_MACRO_CNTL_RESERVED2                                             0x5d9a
#define mmDPHY_MACRO_CNTL_RESERVED3                                             0x5d9b
#define mmDPHY_MACRO_CNTL_RESERVED4                                             0x5d9c
#define mmDPHY_MACRO_CNTL_RESERVED5                                             0x5d9d
#define mmDPHY_MACRO_CNTL_RESERVED6                                             0x5d9e
#define mmDPHY_MACRO_CNTL_RESERVED7                                             0x5d9f
#define mmDPHY_MACRO_CNTL_RESERVED8                                             0x5da0
#define mmDPHY_MACRO_CNTL_RESERVED9                                             0x5da1
#define mmDPHY_MACRO_CNTL_RESERVED10                                            0x5da2
#define mmDPHY_MACRO_CNTL_RESERVED11                                            0x5da3
#define mmDPHY_MACRO_CNTL_RESERVED12                                            0x5da4
#define mmDPHY_MACRO_CNTL_RESERVED13                                            0x5da5
#define mmDPHY_MACRO_CNTL_RESERVED14                                            0x5da6
#define mmDPHY_MACRO_CNTL_RESERVED15                                            0x5da7
#define mmDPHY_MACRO_CNTL_RESERVED16                                            0x5da8
#define mmDPHY_MACRO_CNTL_RESERVED17                                            