A_RECOVERY_SURFACE_ADDRESS_HIGH                          0x44be
#define mmGRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                                  0x1abf
#define mmDCP0_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x1abf
#define mmDCP1_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x1cbf
#define mmDCP2_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x1ebf
#define mmDCP3_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x40bf
#define mmDCP4_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x42bf
#define mmDCP5_GRPH_XDMA_CACHE_UNDERFLOW_DET_STATUS                             0x44bf
#define mmDIG_FE_CNTL                                                           0x4a00
#define mmDIG0_DIG_FE_CNTL                                                      0x4a00
#define mmDIG1_DIG_FE_CNTL                                                      0x4b00
#define mmDIG2_DIG_FE_CNTL                                                      0x4c00
#define mmDIG3_DIG_FE_CNTL                                                      0x4d00
#define mmDIG4_DIG_FE_CNTL                                                      0x4e00
#define mmDIG5_DIG_FE_CNTL                                                      0x4f00
#define mmDIG6_DIG_FE_CNTL                                                      0x5400
#define mmDIG_OUTPUT_CRC_CNTL                                                   0x4a01
#define mmDIG0_DIG_OUTPUT_CRC_CNTL                                              0x4a01
#define mmDIG1_DIG_OUTPUT_CRC_CNTL                                              0x4b01
#define mmDIG2_DIG_OUTPUT_CRC_CNTL                                              0x4c01
#define mmDIG3_DIG_OUTPUT_CRC_CNTL                                              0x4d01
#define mmDIG4_DIG_OUTPUT_CRC_CNTL                                              0x4e01
#define mmDIG5_DIG_OUTPUT_CRC_CNTL                                              0x4f01
#define mmDIG6_DIG_OUTPUT_CRC_CNTL                                              0x5401
#define mmDIG_OUTPUT_CRC_RESULT                                                 0x4a02
#define mmDIG0_DIG_OUTPUT_CRC_RESULT                                            0x4a02
#define mmDIG1_DIG_OUTPUT_CRC_RESULT                                            0x4b02
#define mmDIG2_DIG_OUTPUT_CRC_RESULT                                            0x4c02
#define mmDIG3_DIG_OUTPUT_CRC_RESULT                                            0x4d02
#define mmDIG4_DIG_OUTPUT_CRC_RESULT                                            0x4e02
#define mmDIG5_DIG_OUTPUT_CRC_RESULT                                            0x4f02
#define mmDIG6_DIG_OUTPUT_CRC_RESULT                                            0x5402
#define mmDIG_CLOCK_PATTERN                                                     0x4a03
#define mmDIG0_DIG_CLOCK_PATTERN                                                0x4a03
#define mmDIG1_DIG_CLOCK_PATTERN                                                0x4b03
#define mmDIG2_DIG_CLOCK_PATTERN                                                0x4c03
#define mmDIG3_DIG_CLOCK_PATTERN                                                0x4d03
#define mmDIG4_DIG_CLOCK_PATTERN                                                0x4e03
#define mmDIG5_DIG_CLOCK_PATTERN                                                0x4f03
#define mmDIG6_DIG_CLOCK_PATTERN                                                0x5403
#define mmDIG_TEST_PATTERN                                                      0x4a04
#define mmDIG0_DIG_TEST_PATTERN                                                 0x4a04
#define mmDIG1_DIG_TEST_PATTERN                                                 0x4b04
#define mmDIG2_DIG_TEST_PATTERN                                                 0x4c04
#define mmDIG3_DIG_TEST_PATTERN                                                 0x4d04
#define mmDIG4_DIG_TEST_PATTERN                                                 0x4e04
#define mmDIG5_DIG_TEST_PATTERN                                                 0x4f04
#define mmDIG6_DIG_TEST_PATTERN                                                 0x5404
#define mmDIG_RANDOM_PATTERN_SEED                                               0x4a05
#define mmDIG0_DIG_RANDOM_PATTERN_SEED                                          0x4a05
#define mmDIG1_DIG_RANDOM_PATTERN_SEED                                          0x4b05
#define mmDIG2_DIG_RANDOM_PATTERN_SEED                                          0x4c05
#define mmDIG3_DIG_RANDOM_PATTERN_SEED                                          0x4d05
#define mmDIG4_DIG_RANDOM_PATTERN_SEED                                          0x4e05
#define mmDIG5_DIG_RANDOM_PATTERN_SEED                                          0x4f05
#define mmDIG6_DIG_RANDOM_PATTERN_SEED                                          0x5405
#define mmDIG_FIFO_STATUS                                                       0x4a06
#define mmDIG0_DIG_FIFO_STATUS                                                  0x4a06
#define mmDIG1_DIG_FIFO_STATUS                                                  0x4b06
#define mmDIG2_DIG_FIFO_STATUS                                                  0x4c06
#define mmDIG3_DIG_FIFO_STATUS                                                  0x4d06
#define mmDIG4_DIG_FIFO_STATUS                                                  0x4e06
#define mmDIG5_DIG_FIFO_STATUS                                                  0x4f06
#define mmDIG6_DIG_FIFO_STATUS                                                  0x5406
#define mmDIG_DISPCLK_SWITCH_CNTL                                               0x4a07
#define mmDIG0_DIG_DISPCLK_SWITCH_CNTL                                          0x4a07
#define mmDIG1_DIG_DISPCLK_SWITCH_CNTL                                          0x4b07
#define mmDIG2_DIG_DISPCLK_SWITCH_CNTL                                          0x4c07
#define mmDIG3_DIG_DISPCLK_SWITCH_CNTL                                          0x4d07
#define mmDIG4_DIG_DISPCLK_SWITCH_CNTL                                          0x4e07
#define mmDIG5_DIG_DISPCLK_SWITCH_CNTL                                          0x4f07
#define mmDIG6_DIG_DISPCLK_SWITCH_CNTL                                          0x5407
#define mmDIG_DISPCLK_SWITCH_STATUS                                             0x4a08
#define mmDIG0_DIG_DISPCLK_SWITCH_STATUS                                        0x4a08
#define mmDIG1_DIG_DISPCLK_SWITCH_STATUS                                        0x4b08
#define mmDIG2_DIG_DISPCLK_SWITCH_STATUS                                        0x4c08
#define mmDIG3_DIG_DISPCLK_SWITCH_STATUS                                        0x4d08
#define mmDIG4_DIG_DISPCLK_SWITCH_STATUS                                        0x4e08
#define mmDIG5_DIG_DISPCLK_SWITCH_STATUS                                        0x4f08
#define mmDIG6_DIG_DISPCLK_SWITCH_STATUS                                        0x5408
#define mmHDMI_CONTROL                                                          0x4a09
#define mmDIG0_HDMI_CONTROL                                                     0x4a09
#define mmDIG1_HDMI_CONTROL                                                     0x4b09
#define mmDIG2_HDMI_CONTROL                                                     0x4c09
#define mmDIG3_HDMI_CONTROL                                                     0x4d09
#define mmDIG4_HDMI_CONTROL                                                     0x4e09
#define mmDIG5_HDMI_CONTROL                                                     0x4f09
#define mmDIG6_HDMI_CONTROL                                                     0x5409
#define mmHDMI_STATUS                                                           0x4a0a
#define mmDIG0_HDMI_STATUS                                                      0x4a0a
#define mmDIG1_HDMI_STATUS                                                      0x4b0a
#define mmDIG2_HDMI_STATUS                                                      0x4c0a
#define mmDIG3_HDMI_STATUS                                                      0x4d0a
#define mmDIG4_HDMI_STATUS                                                      0x4e0a
#define mmDIG5_HDMI_STATUS                                                      0x4f0a
#define mmDIG6_HDMI_STATUS                                                      0x540a
#define mmHDMI_AUDIO_PACKET_CONTROL                                             0x4a0b
#define mmDIG0_HDMI_AUDIO_PACKET_CONTROL                                        0x4a0b
#define mmDIG1_HDMI_AUDIO_PACKET_CONTROL                                        0x4b0b
#define mmDIG2_HDMI_AUDIO_PACKET_CONTROL                                        0x4c0b
#define mmDIG3_HDMI_AUDIO_PACKET_CONTROL                                        0x4d0b
#define mmDIG4_HDMI_AUDIO_PACKET_CONTROL                                        0x4e0b
#define mmDIG5_HDMI_AUDIO_PACKET_CONTROL                                        0x4f0b
#define mmDIG6_HDMI_AUDIO_PACKET_CONTROL                                        0x540b
#define mmHDMI_ACR_PACKET_CONTROL                                               0x4a0c
#define mmDIG0_HDMI_ACR_PACKET_CONTROL                                          0x4a0c
#define mmDIG1_HDMI_ACR_PACKET_CONTROL                                          0x4b0c
#define mmDIG2_HDMI_ACR_PACKET_CONTROL                                          0x4c0c
#define mmDIG3_HDMI_ACR_PACKET_CONTROL                                          0x4d0c
#define mmDIG4_HDMI_ACR_PACKET_CONTROL                                          0x4e0c
#define mmDIG5_HDMI_ACR_PACKET_CONTROL                                          0x4f0c
#define mmDIG6_HDMI_ACR_PACKET_CONTROL                                          0x540c
#define mmHDMI_VBI_PACKET_CONTROL                                               0x4a0d
#define mmDIG0_HDMI_VBI_PACKET_CONTROL                                          0x4a0d
#define mmDIG1_HDMI_VBI_PACKET_CONTROL                                          0x4b0d
#define mmDIG2_HDMI_VBI_PACKET_CONTROL                                          0x4c0d
#define mmDIG3_HDMI_VBI_PACKET_CONTROL                                          0x4d0d
#define mmDIG4_HDMI_VBI_PACKET_CONTROL                                          0x4e0d
#define mmDIG5_HDMI_VBI_PACKET_CONTROL                                          0x4f0d
#define mmDIG6_HDMI_VBI_PACKET_CONTROL                                          0x540d
#define mmHDMI_INFOFRAME_CONTROL0                                               0x4a0e
#define mmDIG0_HDMI_INFOFRAME_CONTROL0                                          0x4a0e
#define mmDIG1_HDMI_INFOFRAME_CONTROL0                                          0x4b0e
#define mmDIG2_HDMI_INFOFRAME_CONTROL0                                          0x4c0e
#define mmDIG3_HDMI_INFOFRAME_CONTROL0                                          0x4d0e
#define mmDIG4_HDMI_INFOFRAME_CONTROL0                                          0x4e0e
#define mmDIG5_HDMI_INFOFRAME_CONTROL0                                          0x4f0e
#define mmDIG6_HDMI_INFOFRAME_CONTROL0                                          0x540e
#define mmHDMI_INFOFRAME_CONTROL1                                               0x4a0f
#define mmDIG0_HDMI_INFOFRAME_CONTROL1                                          0x4a0f
#define mmDIG1_HDMI_INFOFRAME_CONTROL1                                          0x4b0f
#define mmDIG2_HDMI_INFOFRAME_CONTROL1                        