        0x16
#define ixDCIO_DEBUG_ID                                                         0x0
#define mmDC_GPIO_GENERIC_MASK                                                  0x4860
#define mmDC_GPIO_GENERIC_A                                                     0x4861
#define mmDC_GPIO_GENERIC_EN                                                    0x4862
#define mmDC_GPIO_GENERIC_Y                                                     0x4863
#define mmDC_GPIO_DVODATA_MASK                                                  0x4864
#define mmDC_GPIO_DVODATA_A                                                     0x4865
#define mmDC_GPIO_DVODATA_EN                                                    0x4866
#define mmDC_GPIO_DVODATA_Y                                                     0x4867
#define mmDC_GPIO_DDC1_MASK                                                     0x4868
#define mmDC_GPIO_DDC1_A                                                        0x4869
#define mmDC_GPIO_DDC1_EN                                                       0x486a
#define mmDC_GPIO_DDC1_Y                                                        0x486b
#define mmDC_GPIO_DDC2_MASK                                                     0x486c
#define mmDC_GPIO_DDC2_A                                                        0x486d
#define mmDC_GPIO_DDC2_EN                                                       0x486e
#define mmDC_GPIO_DDC2_Y                                                        0x486f
#define mmDC_GPIO_DDC3_MASK                                                     0x4870
#define mmDC_GPIO_DDC3_A                                                        0x4871
#define mmDC_GPIO_DDC3_EN                                                       0x4872
#define mmDC_GPIO_DDC3_Y                                                        0x4873
#define mmDC_GPIO_DDC4_MASK                                                     0x4874
#define mmDC_GPIO_DDC4_A                                                        0x4875
#define mmDC_GPIO_DDC4_EN                                                       0x4876
#define mmDC_GPIO_DDC4_Y                                                        0x4877
#define mmDC_GPIO_DDC5_MASK                                                     0x4878
#define mmDC_GPIO_DDC5_A                                                        0x4879
#define mmDC_GPIO_DDC5_EN                                                       0x487a
#define mmDC_GPIO_DDC5_Y                                                        0x487b
#define mmDC_GPIO_DDC6_MASK                                                     0x487c
#define mmDC_GPIO_DDC6_A                                                        0x487d
#define mmDC_GPIO_DDC6_EN                                                       0x487e
#define mmDC_GPIO_DDC6_Y                                                        0x487f
#define mmDC_GPIO_DDCVGA_MASK                                                   0x4880
#define mmDC_GPIO_DDCVGA_A                                                      0x4881
#define mmDC_GPIO_DDCVGA_EN                                                     0x4882
#define mmDC_GPIO_DDCVGA_Y                                                      0x4883
#define mmDC_GPIO_SYNCA_MASK                                                    0x4884
#define mmDC_GPIO_SYNCA_A                                                       0x4885
#define mmDC_GPIO_SYNCA_EN                                                      0x4886
#define mmDC_GPIO_SYNCA_Y                                                       0x4887
#define mmDC_GPIO_GENLK_MASK                                                    0x4888
#define mmDC_GPIO_GENLK_A                                                       0x4889
#define mmDC_GPIO_GENLK_EN                                                      0x488a
#define mmDC_GPIO_GENLK_Y                                                       0x488b
#define mmDC_GPIO_HPD_MASK                                                      0x488c
#define mmDC_GPIO_HPD_A                                                         0x488d
#define mmDC_GPIO_HPD_EN                                                        0x488e
#define mmDC_GPIO_HPD_Y                                                         0x488f
#define mmDC_GPIO_PWRSEQ_MASK                                                   0x4890
#define mmDC_GPIO_PWRSEQ_A                                                      0x4891
#define mmDC_GPIO_PWRSEQ_EN                                                     0x4892
#define mmDC_GPIO_PWRSEQ_Y                                                      0x4893
#define mmDC_GPIO_PAD_STRENGTH_1                                                0x4894
#define mmDC_GPIO_PAD_STRENGTH_2                                                0x4895
#define mmPHY_AUX_CNTL                                                          0x4897
#define mmDC_GPIO_I2CPAD_A                                                      0x4899
#define mmDC_GPIO_I2CPAD_EN                                                     0x489a
#define mmDC_GPIO_I2CPAD_Y                                                      0x489b
#define mmDC_GPIO_I2CPAD_STRENGTH                                               0x489c
#define mmDVO_STRENGTH_CONTROL                                                  0x489d
#define mmDVO_VREF_CONTROL                                                      0x489e
#define mmDVO_SKEW_ADJUST                                                       0x489f
#define mmDAC_MACRO_CNTL_RESERVED0                                              0x48b8
#define mmDAC_MACRO_CNTL_RESERVED1                                              0x48b9
#define mmDAC_MACRO_CNTL_RESERVED2                                              0x48ba
#define mmDAC_MACRO_CNTL_RESERVED3                                              0x48bb
#define mmUNIPHY_MACRO_CNTL_RESERVED0                                           0x48c0
#define mmDCIO_UNIPHY0_UNIPHY_MACRO_CNTL_RESERVED0                              0x48c0
#define mmDCIO_UNIPHY1_UNIPHY_MACRO_CNTL_RESERVED0                              0x48e0
#define mmDCIO_UNIPHY2_UNIPHY_MACRO_CNTL_RESERVED0                              0x4900
#define mmDCIO_UNIPHY3_UNIPHY_MACRO_CNTL_RESERVED0                              0x4920
#define mmDCIO_UNIPHY4_UNIPHY_MACRO_CNTL_RESERVED0                              0x4940
#define mmDCIO_UNIPHY5_UNIPHY_MACRO_CNTL_RESERVED0                              0x4960
#define mmDCIO_UNIPHY6_UNIPHY_MACRO_CNTL_RESERVED0                              0x4980
#define mmUNIPHY_MACRO_CNTL_RESERVED1                                           0x48c1
#define mmDCIO_UNIPHY0_UNIPHY_MACRO_CNTL_RESERVED1                              0x48c1
#define mmDCIO_UNIPHY1_UNIPHY_MACRO_CNTL_RESERVED1                              0x48e1
#define mmDCIO_UNIPHY2_UNIPHY_MACRO_CNTL_RESERVED1                              0x4901
#define mmDCIO_UNIPHY3_UNIPHY_MACRO_CNTL_RESERVED1                              0x4921
#define mmDCIO_UNIPHY4_UNIPHY_MACRO_CNTL_RESERVED1                              0x4941
#define mmDCIO_UNIPHY5_UNIPHY_MACRO_CNTL_RESERVED1                              0x4961
#define mmDCIO_UNIPHY6_UNIPHY_MACRO_CNTL_RESERVED1                              0x4981
#define mmUNIPHY_MACRO_CNTL_RESERVED2                                           0x48c2
#define mmDCIO_UNIPHY0_UNIPHY_MACRO_CNTL_RESERVED2                              0x48c2
#define mmDCIO_UNIPHY1_UNIPHY_MACRO_CNTL_RESERVED2                              0x48e2
#define mmDCIO_UNIPHY2_UNIPHY_MACRO_CNTL_RESERVED2                              0x4902
#define mmDCIO_UNIPHY3_UNIPHY_MACRO_CNTL_RESERVED2                              0x4922
#define mmDCIO_UNIPHY4_UNIPHY_MACRO_CNTL_RESERVED2                              0x4942
#define mmDCIO_UNIPHY5_UNIPHY_MACRO_CNTL_RESERVED2                              0x4962
#define mmDCIO_UNIPHY6_UNIPHY_MACRO_CNTL_RESERVED2                              0x4982
#define mmUNIPHY_MACRO_CNTL_RESERVED3                                           0x48c3
#define mmDCIO_UNIPHY0_UNIPHY_MACRO_CNTL_RESERVED3                              0x48c3
#define mmDCIO_UNIPHY1_UNIPHY_MACRO_CNTL_RESERVED3                              0x48e3
#define mmDCIO_UNIPHY2_UNIPHY_MACRO_CNTL_RESERVED3                              0x4903
#define mmDCIO_UNIPHY3_UNIPHY_MACRO_CNTL_RESERVED3                              0x4923
#define mmDCIO_UNIPHY4_UNIPHY_MACRO_CNTL_RESERVED3                              0x4943
#define mmDCIO_UNIPHY5_UNIPHY_MACRO_CNTL_RESERVED3                              0x4963
#define mmDCIO_UNIPHY6_UNIPHY_MACRO_CNTL_RESERVED3                              0x4983
#define mmUNIPHY_MACRO_CNTL_RESERVED4                                           0x48c4
#define mmDCIO_UNIPHY0_UNIPHY_MACRO_CNTL_RESERVED4                              0x48c4
#define mmDCIO_UNIPHY1_UNIPHY_MACRO_CNTL_RESERVED4                              0x48e4
#define mmDCIO_UNIPHY2_UNIPHY_MACRO_CNTL_RESERVED4                              0x4904
#define mmDCIO_UNIPHY3_UNIPHY_MACRO_CNTL_RESERVED4                              0x4924
#define mmDCIO_UNIPHY4_UNIPHY_MACRO_CNTL_RESERVED4                              0x4944
#define mmDCIO_UNIPHY5_UNIPHY_MACRO_CNTL_RESERVED4                              0x4964
#define mmDCIO_UNIPHY6_UNIPHY_MA