            0x5fe6
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED10                                 0x5ff2
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED10                                 0x5ffe
#define mmCPLL_MACRO_CNTL_RESERVED11                                            0x5fdb
#define mmDCCG_CPLL0_CPLL_MACRO_CNTL_RESERVED11                                 0x5fdb
#define mmDCCG_CPLL1_CPLL_MACRO_CNTL_RESERVED11                                 0x5fe7
#define mmDCCG_CPLL2_CPLL_MACRO_CNTL_RESERVED11                                 0x5ff3
#define mmDCCG_CPLL3_CPLL_MACRO_CNTL_RESERVED11                                 0x5fff
#define mmPLL_MACRO_CNTL_RESERVED0                                              0x1700
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED0                                    0x1700
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED0                                    0x172a
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED0                                    0x1754
#define mmPLL_MACRO_CNTL_RESERVED1                                              0x1701
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED1                                    0x1701
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED1                                    0x172b
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED1                                    0x1755
#define mmPLL_MACRO_CNTL_RESERVED2                                              0x1702
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED2                                    0x1702
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED2                                    0x172c
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED2                                    0x1756
#define mmPLL_MACRO_CNTL_RESERVED3                                              0x1703
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED3                                    0x1703
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED3                                    0x172d
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED3                                    0x1757
#define mmPLL_MACRO_CNTL_RESERVED4                                              0x1704
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED4                                    0x1704
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED4                                    0x172e
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED4                                    0x1758
#define mmPLL_MACRO_CNTL_RESERVED5                                              0x1705
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED5                                    0x1705
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED5                                    0x172f
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED5                                    0x1759
#define mmPLL_MACRO_CNTL_RESERVED6                                              0x1706
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED6                                    0x1706
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED6                                    0x1730
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED6                                    0x175a
#define mmPLL_MACRO_CNTL_RESERVED7                                              0x1707
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED7                                    0x1707
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED7                                    0x1731
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED7                                    0x175b
#define mmPLL_MACRO_CNTL_RESERVED8                                              0x1708
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED8                                    0x1708
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED8                                    0x1732
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED8                                    0x175c
#define mmPLL_MACRO_CNTL_RESERVED9                                              0x1709
#define mmDCCG_PLL0_PLL_MACRO_CNTL_RESERVED9                                    0x1709
#define mmDCCG_PLL1_PLL_MACRO_CNTL_RESERVED9                                    0x1733
#define mmDCCG_PLL2_PLL_MACRO_CNTL_RESERVED9                                    0x175d
#define 