/*
 * OSS_3_0 Register documentation
 *
 * Copyright (C) 2014  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef OSS_3_0_SH_MASK_H
#define OSS_3_0_SH_MASK_H

#define IH_VMID_0_LUT__PASID_MASK 0xffff
#define IH_VMID_0_LUT__PASID__SHIFT 0x0
#define IH_VMID_1_LUT__PASID_MASK 0xffff
#define IH_VMID_1_LUT__PASID__SHIFT 0x0
#define IH_VMID_2_LUT__PASID_MASK 0xffff
#define IH_VMID_2_LUT__PASID__SHIFT 0x0
#define IH_VMID_3_LUT__PASID_MASK 0xffff
#define IH_VMID_3_LUT__PASID__SHIFT 0x0
#define IH_VMID_4_LUT__PASID_MASK 0xffff
#define IH_VMID_4_LUT__PASID__SHIFT 0x0
#define IH_VMID_5_LUT__PASID_MASK 0xffff
#define IH_VMID_5_LUT__PASID__SHIFT 0x0
#define IH_VMID_6_LUT__PASID_MASK 0xffff
#define IH_VMID_6_LUT__PASID__SHIFT 0x0
#define IH_VMID_7_LUT__PASID_MASK 0xffff
#define IH_VMID_7_LUT__PASID__SHIFT 0x0
#define IH_VMID_8_LUT__PASID_MASK 0xffff
#define IH_VMID_8_LUT__PASID__SHIFT 0x0
#define IH_VMID_9_LUT__PASID_MASK 0xffff
#define IH_VMID_9_LUT__PASID__SHIFT 0x0
#define IH_VMID_10_LUT__PASID_MASK 0xffff
#define IH_VMID_10_LUT__PASID__SHIFT 0x0
#define IH_VMID_11_LUT__PASID_MASK 0xffff
#define IH_VMID_11_LUT__PASID__SHIFT 0x0
#define IH_VMID_12_LUT__PASID_MASK 0xffff
#define IH_VMID_12_LUT__PASID__SHIFT 0x0
#define IH_VMID_13_LUT__PASID_MASK 0xffff
#define IH_VMID_13_LUT__PASID__SHIFT 0x0
#define IH_VMID_14_LUT__PASID_MASK 0xffff
#define IH_VMID_14_LUT__PASID__SHIFT 0x0
#define IH_VMID_15_LUT__PASID_MASK 0xffff
#define IH_VMID_15_LUT__PASID__SHIFT 0x0
#define IH_RB_CNTL__RB_ENABLE_MASK 0x1
#define IH_RB_CNTL__RB_ENABLE__SHIFT 0x0
#define IH_RB_CNTL__RB_SIZE_MASK 0x3e
#define IH_RB_CNTL__RB_SIZE__SHIFT 0x1
#define IH_RB_CNTL__RB_GPU_TS_ENABLE_MASK 0x80
#define IH_RB_CNTL__RB_GPU_TS_ENABLE__SHIFT 0x7
#define IH_RB_CNTL__WPTR_WRITEBACK_ENABLE_MASK 0x100
#define IH_RB_CNTL__WPTR_WRITEBACK_ENABLE__SHIFT 0x8
#define IH_RB_CNTL__ENABLE_INTR_MASK 0x20000
#define IH_RB_CNTL__ENABLE_INTR__SHIFT 0x11
#define IH_RB_CNTL__MC_SWAP_MASK 0xc0000
#define IH_RB_CNTL__MC_SWAP__SHIFT 0x12
#define IH_RB_CNTL__RPTR_REARM_MASK 0x200000
#define IH_RB_CNTL__RPTR_REARM__SHIFT 0x15
#define IH_RB_CNTL__MC_VMID_MASK 0xf000000
#define IH_RB_CNTL__MC_VMID__SHIFT 0x18
#define IH_RB_CNTL__WPTR_OVERFLOW_CLEAR_MASK 0x80000000
#define IH_RB_CNTL__WPTR_OVERFLOW_CLEAR__SHIFT 0x1f
#define IH_RB_BASE__ADDR_MASK 0xffffffff
#define IH_RB_BASE__ADDR__SHIFT 0x0
#define IH_RB_RPTR__OFFSET_MASK 0x3fffc
#define IH_RB_RPTR__OFFSET__SHIFT 0x2
#define IH_RB_WPTR__RB_OVERFLOW_MASK 0x1
#define IH_RB_WPTR__RB_OVERFLOW__SHIFT 0x0
#define IH_RB_WPTR__OFFSET_MASK 0x3fffc
#define IH_RB_WPTR__OFFSET__SHIFT 0x2
#define IH_RB_WPTR__RB_LEFT_NONE_MASK 0x40000
#define IH_RB_WPTR__RB_LEFT_NONE__SHIFT 0x12
#define IH_RB_WPTR__RB_MAY_OVERFLOW_MASK 0x80000
#define IH_RB_WPTR__RB_MAY_OVERFLOW__SHIFT 0x13
#define IH_RB_WPTR_ADDR_HI__ADDR_MASK 0xff
#define IH_RB_WPTR_ADDR_HI__ADDR__SHIFT 0x0
#define IH_RB_WPTR_ADDR_LO__ADDR_MASK 0xfffffffc
#define IH_RB_WPTR_ADDR_LO__ADDR__SHIFT 0x2
#define IH_CNTL__WPTR_WRITEBACK_TIMER_MASK 0x1f
#define IH_CNTL__WPTR_WRITEBACK_TIMER__SHIFT 0x0
#define IH_CNTL__CLIENT_FIFO_HIGHWATER_MASK 0x300
#define IH_CNTL__CLIENT_FIFO_HIGHWATER__SHIFT 0x8
#define IH_CNTL__MC_FIFO_HIGHWATER_MASK 0x7c00
#define IH_CNTL__MC_FIFO_HIGHWATER__SHIFT 0xa
#define IH_CNTL__MC_WRREQ_CREDIT_MASK 0xf8000
#define IH_CNTL__MC_WRREQ_CREDIT__SHIFT 0xf
#define IH_CNTL__MC_WR_CLEAN_CNT_MASK 0x1f00000
#define IH_CNTL__MC_WR_CLEAN_CNT__SHIFT 0x14
#define IH_LEVEL_STATUS__DC_STATUS_MASK 0x1
#define IH_LEVEL_STATUS__DC_STATUS__SHIFT 0x0
#define IH_LEVEL_STATUS__ROM_STATUS_MASK 0x4
#define IH_LEVEL_STATUS__ROM_STATUS__SHIFT 0x2
#define IH_LEVEL_STATUS__SRBM_STATUS_MASK 0x8
#define IH_LEVEL_STATUS__SRBM_STATUS__SHIFT 0x3
#define IH_LEVEL_STATUS__BIF_STATUS_MASK 0x10
#define IH_LEVEL_STATUS__BIF_STATUS__SHIFT 0x4
#define IH_LEVEL_STATUS__XDMA_STATUS_MASK 0x20
#define IH_LEVEL_STATUS__XDMA_STATUS__SHIFT 0x5
#define IH_STATUS__IDLE_MASK 0x1
#define IH_STATUS__IDLE__SHIFT 0x0
#define IH_STATUS__INPUT_IDLE_MASK 0x2
#define IH_STATUS__INPUT_IDLE__SHIFT 0x1
#define IH_STATUS__RB_IDLE_MASK 0x4
#define IH_STATUS__RB_IDLE__SHIFT 0x2
#define IH_STATUS__RB_FULL_MASK 0x8
#define IH_STATUS__RB_FULL__SHIFT 0x3
#define IH_STATUS__RB_FULL_DRAIN_MASK 0x10
#define IH_STATUS__RB_FULL_DRAIN__SHIFT 0x4
#define IH_STATUS__RB_OVERFLOW_MASK 0x20
#define IH_STATUS__RB_OVERFLOW__SHIFT 0x5
#define IH_STATUS__MC_WR_IDLE_MASK 0x40
#define IH_STATUS__MC_WR_IDLE__SHIFT 0x6
#define IH_STATUS__MC_WR_STALL_MASK 0x80
#define IH_STATUS__MC_WR_STALL__SHIFT 0x7
#define IH_STATUS__MC_WR_CLEAN_PENDING_MASK 0x100
#define IH_STATUS__MC_WR_CLEAN_PENDING__SHIFT 0x8
#define IH_STATUS__MC_WR_CLEAN_STALL_MASK 0x200
#define IH_STATUS__MC_WR_CLEAN_STALL__SHIFT 0x9
#define IH_STATUS__BIF_INTERRUPT_LINE_MASK 0x400
#define IH_STATUS__BIF_INTERRUPT_LINE__SHIFT 0xa
#define IH_STATUS__SWITCH_READY_MASK 0x800
#define IH_STATUS__SWITCH_READY__SHIFT 0xb
#define IH_PERFMON_CNTL__ENABLE0_MASK 0x1
#define IH_PERFMON_CNTL__ENABLE0__SHIFT 0x0
#define IH_PERFMON_CNTL__CLEAR0_MASK 0x2
#define IH_PERFMON_CNTL__CLEAR0__SHIFT 0x1
#define IH_PERFMON_CNTL__PERF_SEL0_MASK 0x3fc
#define IH_PERFMON_CNTL__PERF_SEL0__SHIFT 0x2
#define IH_PERFMON_CNTL__ENABLE1_MASK 0x400
#define IH_PERFMON_CNTL__ENABLE1__SHIFT 0xa
#define IH_PERFMON_CNTL__CLEAR1_MASK 0x800
#define IH_PERFMON_CNTL__CLEAR1__SHIFT 0xb
#define IH_PERFMON_CNTL__PERF_SEL1_MASK 0xff000
#define IH_PERFMON_CNTL__PERF_SEL1__SHIFT 0xc
#define IH_PERFCOUNTER0_RESULT__PERF_COUNT_MASK 0xffffffff
#define IH_PERFCOUNTER0_RESULT__PERF_COUNT__SHIFT 0x0
#define IH_PERFCOUNTER1_RESULT__PERF_COUNT_MASK 0xffffffff
#define IH_PERFCOUNTER1_RESULT__PERF_COUNT__SHIFT 0x0
#define IH_DEBUG__RB_FULL_DRAIN_ENABLE_MASK 0x1
#define IH_DEBUG__RB_FULL_DRAIN_ENABLE__SHIFT 0x0
#define IH_DEBUG__WPTR_OVERFLOW_ENABLE_MASK 0x2
#define IH_DEBUG__WPTR_OVERFLOW_ENABLE__SHIFT 0x1
#define IH_DEBUG__MC_WR_FIFO_BLOCK_ENABLE_MASK 0x4
#define IH_DEBUG__MC_WR_FIFO_BLOCK_ENABLE__SHIFT 0x2
#define IH_DSM_MATCH_VALUE_BIT_31_0__VALUE_MASK 0xffffffff
#define IH_DSM_MATCH_VALUE_BIT_31_0__VALUE__SHIFT 0x0
#define IH_DSM_MATCH_VALUE_BIT_63_32__VALUE_MASK 0xffffffff
#define IH_DSM_MATCH_VALUE_BIT_63_32__VALUE__SHIFT 0x0
#define IH_DSM_MATCH_VALUE_BIT_95_64__VALUE_MASK 0xffffffff
#define IH_DSM_MATCH_VALUE_BIT_95_64__VALUE__SHIFT 0x0
#define IH_DSM_MATCH_FIELD_CONTROL__SRC_EN_MASK 0x1
#define IH_DSM_MATCH_FIELD_CONTROL__SRC_EN__SHIFT 0x0
#define IH_DSM_MATCH_FIELD_CONTROL__FCNID_EN_MASK 0x2
#define IH_DSM_MATCH_FIELD_CONTROL__FCNID_EN__SHIFT 0x1
#define IH_DSM_MATCH_FIELD_CONTROL__TIMESTAMP_EN_MASK 0x4
#define IH_DSM_MATCH_FIELD_CONTROL__TIMESTAMP_EN__SHIFT 0x2
#define IH_DSM_MATCH_FIELD_CONTROL__RINGID_EN_MASK 0x8
#define IH_DSM_MATCH_FIELD_CONTROL__RINGID_EN__SHIFT 0x3
#define IH_DSM_MATCH_FIELD_CONTROL__VMID_EN_MASK 0x10
#define IH_DSM_MATCH_FIELD_CONTROL__VMID_EN__SHIFT 0x4
#define IH_DSM_MATCH_FIELD_CONTROL__PASID_EN_MASK 0x20
#define IH_DSM_MATCH_FIELD_CONTROL__PASID_EN__SHIFT 0x5
#define IH_DSM_MATCH_DATA_CONTROL__VALUE_MASK 0xfffffff
#define IH_DSM_MATCH_DATA_CONTROL__VALUE__SHIFT 0x0
#define IH_DOORBELL_RPTR__OFFSET_MASK 0x1fffff
#define IH_DOORBELL_RPTR__OFFSET__SHIFT 0x0
#define IH_DOORBELL_RPTR__ENABLE_MASK 0x10000000
#define IH_DOORBELL_RPTR__ENABLE__SHIFT 0x1c
#define IH_DOORBELL_RPTR__CAPTURED_MASK 0x40000000
#define IH_DOORBELL_RPTR__CAPTURED__SHIFT 0x1e
#define IH_ACTIVE_FCN_ID__VF_ID_MASK 0xf
#define IH_ACTIVE_FCN_ID__VF_ID__SHIFT 0x0
#define IH_ACTIVE_FCN_ID__RESERVED_MASK 0x7ffffff0
#define IH_ACTIVE_FCN_ID__RESERVED__SHIFT 0x4
#define IH_ACTIVE_FCN_ID__PF_VF_MASK 0x80000000
#define IH_ACTIVE_FCN_ID__PF_VF__SHIFT 0x1f
#define IH_VF_RB_STATUS__RB_FULL_DRAIN_VF_MASK 0xffff
#define IH_VF_RB_STATUS__RB_FULL_DRAIN_VF__SHIFT 0x0
#define IH_VF_RB_STATUS__RB_OVERFLOW_VF_MASK 0xffff0000
#define IH_VF_RB_STATUS__RB_OVERFLOW_VF__SHIFT 0x10
#define IH_VF_ENABLE__VALUE_MASK 0x1
#define IH_VF_ENABLE__VALUE__SHIFT 0x0
#define IH_VIRT_RESET_REQ__VF_MASK 0xffff
#define IH_VIRT_RESET_REQ__VF__SHIFT 0x0
#define IH_VIRT_RESET_REQ__PF_MASK 0x80000000
#define IH_VIRT_RESET_REQ__PF__SHIFT 0x1f
#define IH_VF_RB_BIF_STATUS__RB_FULL_VF_MASK 0xffff
#define IH_VF_RB_BIF_STATUS__RB_FULL_VF__SHIFT 0x0
#define IH_VF_RB_BIF_STATUS__BIF_INTERRUPT_LINE_VF_MASK 0xffff0000
#define IH_VF_RB_BIF_STATUS__BIF_INTERRUPT_LINE_VF__SHIFT 0x10
#define IH_VERSION__VALUE_MASK 0xfff
#define IH_VERSION__VALUE__SHIFT 0x0
#define IH_LEVEL_INTR_MASK__MASK_MASK 0x1
#define IH_LEVEL_INTR_MASK__MASK__SHIFT 0x0
#define IH_RESET_INCOMPLETE_INT_CNTL__CG_MASK 0x1
#define IH_RESET_INCOMPLETE_INT_CNTL__CG__SHIFT 0x0
#define IH_RESET_INCOMPLETE_INT_CNTL__DC_MASK 0x2
#define IH_RESET_INCOMPLETE_INT_CNTL__DC__SHIFT 0x1
#define IH_RESET_INCOMPLETE_INT_CNTL__SAMMSP_MASK 0x8
#define IH_RESET_INCOMPLETE_INT_CNTL__SAMMSP__SHIFT 0x3
#define IH_RESET_INCOMPLETE_INT_CNTL__RLC_MASK 0x10
#define IH_RESET_INCOMPLETE_INT_CNTL__RLC__SHIFT 0x4
#define IH_RESET_INCOMPLETE_INT_CNTL__ROM_MASK 0x20
#define IH_RESET_INCOMPLETE_INT_CNTL__ROM__SHIFT 0x5
#define IH_RESET_INCOMPLETE_INT_CNTL__SRBM_MASK 0x40
#define IH_RESET_INCOMPLETE_INT_CNTL__SRBM__SHIFT 0x6
#define IH_RESET_INCOMPLETE_INT_CNTL__VMC_MASK 0x80
#define IH_RESET_INCOMPLETE_INT_CNTL__VMC__SHIFT 0x7
#define IH_RESET_INCOMPLETE_INT_CNTL__UVD_MASK 0x100
#define IH_RESET_INCOMPLETE_INT_CNTL__UVD__SHIFT 0x8
#define IH_RESET_INCOMPLETE_INT_CNTL__BIF_MASK 0x200
#define IH_RESET_INCOMPLETE_INT_CNTL__BIF__SHIFT 0x9
#define IH_RESET_INCOMPLETE_INT_CNTL__SDMA0_MASK 0x400
#define IH_RESET_INCOMPLETE_INT_CNTL__SDMA0__SHIFT 0xa
#define IH_RESET_INCOMPLETE_INT_CNTL__SDMA1_MASK 0x800
#define IH_RESET_INCOMPLETE_INT_CNTL__SDMA1__SHIFT 0xb
#define IH_RESET_INCOMPLETE_INT_CNTL__ISP_MASK 0x1000
#define IH_RESET_INCOMPLETE_INT_CNTL__ISP__SHIFT 0xc
#define IH_RESET_INCOMPLETE_INT_CNTL__VCE0_MASK 0x2000
#define IH_RESET_INCOMPLETE_INT_CNTL__VCE0__SHIFT 0xd
#define IH_RESET_INCOMPLETE_INT_CNTL__VCE1_MASK 0x4000
#define IH_RESET_INCOMPLETE_INT_CNTL__VCE1__SHIF