_RX_CNTL                                                     0x70
#define ixD3F3_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD3F3_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD3F3_PCIE_RX_CNTL3                                                    0x74
#define ixD3F3_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD3F3_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD3F3_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD3F3_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD3F3_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD3F3_PCIE_LC_CNTL                                                     0xa0
#define ixD3F3_PCIE_LC_CNTL2                                                    0xb1
#define ixD3F3_PCIE_LC_CNTL3                                                    0xb5
#define ixD3F3_PCIE_LC_CNTL4                                                    0xb6
#define ixD3F3_PCIE_LC_CNTL5                                                    0xb7
#define ixD3F3_PCIE_LC_CNTL6                                                    0xbb
#define ixD3F3_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD3F3_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD3F3_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD3F3_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD3F3_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD3F3_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD3F3_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD3F3_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD3F3_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD3F3_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD3F3_PCIE_LC_STATE0                                                   0xa5
#define ixD3F3_PCIE_LC_STATE1                                                   0xa6
#define ixD3F3_PCIE_LC_STATE2                                                   0xa7
#define ixD3F3_PCIE_LC_STATE3                                                   0xa8
#define ixD3F3_PCIE_LC_STATE4                                                   0xa9
#define ixD3F3_PCIE_LC_STATE5                                                   0xaa
#define ixD3F3_PCIEP_STRAP_LC                                                   0xc0
#define ixD3F3_PCIEP_STRAP_MISC                                                 0xc1
#define ixD3F3_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD3F3_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD3F3_PCIEP_HPGI                                                       0xda
#define ixD3F3_VENDOR_ID                                                        0x9000000
#define ixD3F3_DEVICE_ID                                                        0x9000000
#define ixD3F3_COMMAND                                                          0x9000001
#define ixD3F3_STATUS                                                           0x9000001
#define ixD3F3_REVISION_ID                                                      0x9000002
#define ixD3F3_PROG_INTERFACE                                                   0x9000002
#define ixD3F3_SUB_CLASS                                                        0x9000002
#define ixD3F3_BASE_CLASS                                                       0x9000002
#define ixD3F3_CACHE_LINE                                                       0x9000003
#define ixD3F3_LATENCY                                                          0x9000003
#define ixD3F3_HEADER                                                           0x9000003
#define ixD3F3_BIST                                                             0x9000003
#define ixD3F3_SUB_BUS_NUMBER_LATENCY                                           0x9000006
#define ixD3F3_IO_BASE_LIMIT                                                    0x9000007
#define ixD3F3_SECONDARY_STATUS                                                 0x9000007
#define ixD3F3_MEM_BASE_LIMIT                                                   0x9000008
#define ixD3F3_PREF_BASE_LIMIT                                                  0x9000009
#define ixD3F3_PREF_BASE_UPPER                                                  0x900000a
#define ixD3F3_PREF_LIMIT_UPPER                                                 0x900000b
#define ixD3F3_IO_BASE_LIMIT_HI                                                 0x900000c
#define ixD3F3_IRQ_BRIDGE_CNTL                                                  0x900000f
#define ixD3F3_CAP_PTR                                                          0x900000d
#define ixD3F3_INTERRUPT_LINE                                                   0x900000f
#define ixD3F3_INTERRUPT_PIN                                                    0x900000f
#define ixD3F3_EXT_BRIDGE_CNTL                                                  0x9000010
#define ixD3F3_PMI_CAP_LIST                                                     0x9000014
#define ixD3F3_PMI_CAP                                                          0x9000014
#define ixD3F3_PMI_STATUS_CNTL                                                  0x9000015
#define ixD3F3_PCIE_CAP_LIST                                                    0x9000016
#define ixD3F3_PCIE_CAP                                                         0x9000016
#define ixD3F3_DEVICE_CAP                                                       0x9000017
#define ixD3F3_DEVICE_CNTL                                                      0x9000018
#define ixD3F3_DEVICE_STATUS                                                    0x9000018
#define ixD3F3_LINK_CAP                                                         0x9000019
#define ixD3F3_LINK_CNTL                                                        0x900001a
#define ixD3F3_LINK_STATUS                                                      0x900001a
#define ixD3F3_SLOT_CAP                                                         0x900001b
#define ixD3F3_SLOT_CNTL                                                        0x900001c
#define ixD3F3_SLOT_STATUS                                                      0x900001c
#define ixD3F3_ROOT_CNTL                                                        0x900001d
#define ixD3F3_ROOT_CAP                                                         0x900001d
#define ixD3F3_ROOT_STATUS                                                      0x900001e
#define ixD3F3_DEVICE_CAP2                                                      0x900001f
#define ixD3F3_DEVICE_CNTL2                                                     0x9000020
#define ixD3F3_DEVICE_STATUS2                                                   0x9000020
#define ixD3F3_LINK_CAP2                                                        0x9000021
#define ixD3F3_LINK_CNTL2                                                       0x9000022
#define ixD3F3_LINK_STATUS2                                                     0x9000022
#define ixD3F3_SLOT_CAP2                                                        0x9000023
#define ixD3F3_SLOT_CNTL2                                                       0x9000024
#define ixD3F3_SLOT_STATUS2                                                     0x9000024
#define ixD3F3_MSI_CAP_LIST                                                     0x9000028
#define ixD3F3_MSI_MSG_CNTL                                                     0x9000028
#define ixD3F3_MSI_MSG_ADDR_LO                                                  0x9000029
#define ixD3F3_MSI_MSG_ADDR_HI                                                  0x900002a
#define ixD3F3_MSI_MSG_DATA_64                                                  0x900002b
#define ixD3F3_MSI_MSG_DATA                                                     0x900002a
#define ixD3F3_SSID_CAP_LIST                                                    0x9000030
#define ixD3F3_SSID_CAP                                                         0x9000031
#define ixD3F3_MSI_MAP_CAP_LIST                                                 0x9000032
#define ixD3F3_MSI_MAP_CAP                                                      0x9000032
#define ixD3F3_MSI_MAP_ADDR_LO                                                  0x9000033
#define ixD3F3_MSI_MAP_ADDR_HI                                                  0x9000034
#define ixD3F3_PCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                0x9000040
#define ixD3F3_PCIE_VENDOR_SPECIFIC_HDR                                         0x9000041
#define ixD3F3_PCIE_VENDOR_SPECIFIC1                                            0x9000042
#define ixD3F3_PCIE_VENDOR_SPECIFIC2                                            0x9000043
#define ixD3F3_PCIE_VC_ENH_CAP_LIST                                             0x9000044
#define ixD3F3_PCIE_PORT_VC_CAP_REG1                                            0x9000045
#define ixD3F3_PCIE_PORT_VC_CAP_REG2                                            0x9000046
#define ixD3F3_PCIE_PORT_VC_CNTL                                                0x9000047
#define ixD3F3_PCIE_PORT_VC_STATUS                                              0x9000047
#define ixD3F3_PCIE_VC0_RESOURCE_CAP                                            0x9000048
#define ixD3F3_PCIE_VC0_RESOURCE_CNTL                                           0x9000049
#define ixD3F3_PCIE_VC0_RESOURCE_STATUS                                         0x900004a
#define ixD3F3_PCIE_VC1_RESOURCE_CAP                                            0x900004b
#define ixD3F3_PCIE_VC1_RESOURCE_CNTL                                           0x900004c
#define ixD3F3_PCIE_VC1_RESOURCE_STATUS                                         0x900004d
#define ixD3F3_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0x9000050
#define ixD3F3_PCIE_DEV_SERIAL_NUM_DW1                                          0x9000051
#define ixD3F3_PCIE_DEV_SERIAL_NUM_DW2                                          0x9000052
#define ixD3F3_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0x9000054
#define ixD3F3_PCIE_UNCORR_ERR_STATUS                                           0x9000055
#define ixD3F3_PCIE_UNCORR_ERR_MASK                                             0x9000056
#define ixD3F3_PCIE_UNCORR_ERR_SEVERITY                                         0x9000057
#define ixD3F3_PCIE_CORR_ERR_STATUS                                             0x9000058
#define ixD3F3_PCIE_CORR_ERR_MASK                                               0x9000059
#define ixD3F3_PCIE_ADV_ERR_CAP_CNTL                                            0x900005a
#define ixD3F3_PCIE_HDR_LOG0                                                    0x900005b
#define ixD3F3_PCIE_HDR_LOG1                                                    0x900005c
#define ixD3F3_PCIE_HDR_LOG2                                                    0x900005d
#define ixD3F3_PCIE_HDR_LOG3                                                    0x900005e
#define ixD3F3_PCIE_ROOT_ERR_CMD                                                0x900005f
#define ixD3F3_PCIE_ROOT_ERR_STATUS                                             0x9000060
#define ixD3F3_PCIE_ERR_SRC_ID                                                  0x9000061
#define ixD3F3_PCIE_TLP_PREFIX_LOG0                                             0x9000062
#define ixD3F3_PCIE_TLP_PREFIX_LOG1                                             0x9000063
#define ixD3F3_PCIE_TLP_PREFIX_LOG2                                             0x9000064
#define ixD3F3_PCIE_TLP_PREFIX_LOG3                                             0x9000065
#define ixD3F3_PCIE_SECONDARY_ENH_CAP_LIST                                      0x900009c
#define ixD3F3_PCIE_LINK_CNTL3                                                  0x900009d
#define ixD3F3_PCIE_LANE_ERROR_STATUS                                           0x900009e
#define ixD3F3_PCIE_LANE_0_EQUALIZATION_CNTL                                    0x900009f
#define ixD3F3_PCIE_LANE_1_EQUALIZATION_CNTL                                    0x900009f
#define ixD3F3_PCIE_LANE_2_EQUALIZATION_CNTL                                    0x90000a0
#define ixD3F3_PCIE_LANE_3_EQUALIZATION_CNTL                                    0x90000a0
#define ixD3F3_PCIE_LANE_4_EQUALIZATION_CNTL                                    0x90000a1
#define ixD3F3_PCIE_LANE_5_EQUALIZATION_CNTL                                    0x90000a1
#define ixD3F3_PCIE_LANE_6_EQUALIZATION_CNTL                                    0x90000a2
#define ixD3F3_PCIE_LANE_7_EQUALIZATION_CNTL                                    0x90000a2
#define ixD3F3_PCIE_LANE_8_EQUALIZATION_CNTL                                    0x90000a3
#define ixD3F3_PCIE_LANE_9_EQUALIZATION_CNTL                                    0x90000a3
#define ixD3F3_PCIE_LANE_10_EQUALIZATION_CNTL                                   0x90000a4
#define ixD3F3_PCIE_LANE_11_EQUALIZATION_CNTL                                   0x90000a4
#define ixD3F3_PCIE_LANE_12_EQUALIZATION_CNTL                                   0x90000a5
#define ixD3F3_PCIE_LANE_13_EQUALIZATION_CNTL                                   0x90000a5
#define ixD3F3_PCIE_LANE_14_EQUALIZATION_CNTL                                   0x90000a6
#define ixD3F3_PCIE_LANE_15_EQUALIZATION_CNTL                                   0x90000a6
#define ixD3F3_PCIE_ACS_ENH_CAP_LIST                                            0x90000a8
#define ixD3F3_PCIE_ACS_CAP                                                     0x90000a9
#define ixD3F3_PCIE_ACS_CNTL                                                    0x90000a9
#define ixD3F3_PCIE_MC_ENH_CAP_LIST                                             0x90000bc
#define ixD3F3_PCIE_MC_CAP                                                      0x90000bd
#define ixD3F3_PCIE_MC_CNTL                                                     0x90000bd
#define ixD3F3_PCIE_MC_ADDR0                                                    0x90000be
#define ixD3F3_PCIE_MC_ADDR1                                                    0x90000bf
#define ixD3F3_PCIE_MC_RCV0                                                     0x90000c0
#define ixD3F3_PCIE_MC_RCV1                                                     0x90000c1
#define ixD3F3_PCIE_MC_BLOCK_ALL0                                               0x90000c2
#define ixD3F3_PCIE_MC_BLOCK_ALL1                                               0x90000c3
#define ixD3F3_PCIE_MC_BLOCK_UNTRANSLATED_0                                     0x90000c4
#define ixD3F3_PCIE_MC_BLOCK_UNTRANSLATED_1                                     0x90000c5
#define ixD3F3_PCIE_MC_OVERLAY_BAR0                                             0x90000c6
#define ixD3F3_PCIE_MC_OVERLAY_BAR1                                             0x90000c7
#define ixD3F4_PCIE_PORT_INDEX                                                  0xa000038
#define ixD3F4_PCIE_PORT_DATA                                                   0xa000039
#define ixD3F4_PCIEP_RESERVED                                                   0x0
#define ixD3F4_PCIEP_SCRATCH                                                    0x1
#define ixD3F4_PCIEP_HW_DEBUG                                                   0x2
#define ixD3F4_PCIEP_PORT_CNTL                                                  0x10
#define ixD3F4_PCIE_TX_CNTL                                                     0x20
#define ixD3F4_PCIE_TX_REQUESTER_ID                                             0x21
#define ixD3F4_PCIE_TX_VENDOR_SPECIFIC                                          0x22
#define ixD3F4_PCIE_TX_REQUEST_NUM_CNTL                                         0x23
#define ixD3F4_PCIE_TX_SEQ                                                      0x24
#define ixD3F4_PCIE_TX_REPLAY                                                   0x25
#define ixD3F4_PCIE_TX_ACK_LATENCY_LIMIT                                        0x26
#define ixD3F4_PCIE_TX_CREDITS_ADVT_P                                           0x30
#define ixD3F4_PCIE_TX_CREDITS_ADVT_NP                                          0x31
#define ixD3F4_PCIE_TX_CREDITS_ADVT_CPL                                         0x32
#define ixD3F4_PCIE_TX_CREDITS_INIT_P                                           0x33
#define ixD3F4_PCIE_TX_CREDITS_INIT_NP                                          0x34
#define ixD3F4_PCIE_TX_CREDITS_INIT_CPL                                         0x35
#define ixD3F4_PCIE_TX_CREDITS_STATUS                                           0x36
#define ixD3F4_PCIE_TX_CREDITS_FCU_THRESHOLD                                    0x37
#define ixD3F4_PCIE_P_PORT_LANE_STATUS                                          0x50
#define ixD3F4_PCIE_FC_P                                                        0x60
#define ixD3F4_PCIE_FC_NP                                                       0x61
#define ixD3F4_PCIE_FC_CPL                                                      0x62
#define ixD3F4_PCIE_ERR_CNTL                                                    0x6a
#define ixD3F4_PCIE_RX_CNTL                                                     0x70
#define ixD3F4_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD3F4_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD3F4_PCIE_RX_CNTL3                                                    0x74
#define ixD3F4_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD3F4_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD3F4_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD3F4_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD3F4_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD3F4_PCIE_LC_CNTL                                                     0xa0
#define ixD3F4_PCIE_LC_CNTL2                                                    0xb1
#define ixD3F4_PCIE_LC_CNTL3                                                    0xb5
#define ixD3F4_PCIE_LC_CNTL4                                                    0xb6
#define ixD3F4_PCIE_LC_CNTL5                                                    0xb7
#define ixD3F4_PCIE_LC_CNTL6                                                    0xbb
#define ixD3F4_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD3F4_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD3F4_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD3F4_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD3F4_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD3F4_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD3F4_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD3F4_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD3F4_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD3F4_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD3F4_PCIE_LC_STATE0                                                   0xa5
#define ixD3F4_PCIE_LC_STATE1                                                   0xa6
#define ixD3F4_PCIE_LC_STATE2                                                   0xa7
#define ixD3F4_PCIE_LC_STATE3                                                   0xa8
#define ixD3F4_PCIE_LC_STATE4                                                   0xa9
#define ixD3F4_PCIE_LC_STATE5                                                   0xaa
#define ixD3F4_PCIEP_STRAP_LC                                                   0xc0
#define ixD3F4_PCIEP_STRAP_MISC                                                 0xc1
#define ixD3F4_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD3F4_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD3F4_PCIEP_HPGI                                                       0xda
#define ixD3F4_VENDOR_ID                                                        0xa000000
#define ixD3F4_DEVICE_ID                                                        0xa000000
#define ixD3F4_COMMAND                                                          0xa000001
#define ixD3F4_STATUS                                                           0xa000001
#define ixD3F4_REVISION_ID                                                      0xa000002
#define ixD3F4_PROG_INTERFACE                                                   0xa000002
#define ixD3F4_SUB_CLASS                                                        0xa000002
#define ixD3F4_BASE_CLASS                                                       0xa000002
#define ixD3F4_CACHE_LINE                                                       0xa000003
#define ixD3F4_LATENCY                                                          0xa000003
#define ixD3F4_HEADER                                                           0xa000003
#define ixD3F4_BIST                                                             0xa000003
#define ixD3F4_SUB_BUS_NUMBER_LATENCY                                           0xa000006
#define ixD3F4_IO_BASE_LIMIT                                                    0xa000007
#define ixD3F4_SECONDARY_STATUS                                                 0xa000007
#define ixD3F4_MEM_BASE_LIMIT                                                   0xa000008
#define ixD3F4_PREF_BASE_LIMIT                                                  0xa000009
#define ixD3F4_PREF_BASE_UPPER                                                  0xa00000a
#define ixD3F4_PREF_LIMIT_UPPER                                                 0xa00000b
#define ixD3F4_IO_BASE_LIMIT_HI                                                 0xa00000c
#define ixD3F4_IRQ_BRIDGE_CNTL                                                  0xa00000f
#define ixD3F4_CAP_PTR                                                          0xa00000d
#define ixD3F4_INTERRUPT_LINE                                                   0xa00000f
#define ixD3F4_INTERRUPT_PIN                                                    0xa00000f
#define ixD3F4_EXT_BRIDGE_CNTL                                                  0xa000010
#define ixD3F4_PMI_CAP_LIST                                                     0xa000014
#define ixD3F4_PMI_CAP                                                          0xa000014
#define ixD3F4_PMI_STATUS_CNTL                                                  0xa000015
#define ixD3F4_PCIE_CAP_LIST                                                    0xa000016
#define ixD3F4_PCIE_CAP                                                         0xa000016
#define ixD3F4_DEVICE_CAP                                                       0xa000017
#define ixD3F4_DEVICE_CNTL                                                      0xa000018
#define ixD3F4_DEVICE_STATUS                                                    0xa000018
#define ixD3F4_LINK_CAP                                                         0xa000019
#define ixD3F4_LINK_CNTL                                                        0xa00001a
#define ixD3F4_LINK_STATUS                                                      0xa00001a
#define ixD3F4_SLOT_CAP                                                         0xa00001b
#define ixD3F4_SLOT_CNTL                                                        0xa00001c
#define ixD3F4_SLOT_STATUS                                                      0xa00001c
#define ixD3F4_ROOT_CNTL                                                        0xa00001d
#define ixD3F4_ROOT_CAP                                                         0xa00001d
#define ixD3F4_ROOT_STATUS                                                      0xa00001e
#define ixD3F4_DEVICE_CAP2                                                      0xa00001f
#define ixD3F4_DEVICE_CNTL2                                                     0xa000020
#define ixD3F4_DEVICE_STATUS2                                                   0xa000020
#define ixD3F4_LINK_CAP2                                                        0xa000021
#define ixD3F4_LINK_CNTL2                                                       0xa000022
#define ixD3F4_LINK_STATUS2                                                     0xa000022
#define ixD3F4_SLOT_CAP2                                                        0xa000023
#define ixD3F4_SLOT_CNTL2                                                       0xa000024
#define ixD3F4_SLOT_STATUS2                                                     0xa000024
#define ixD3F4_MSI_CAP_LIST                                                     0xa000028
#define ixD3F4_MSI_MSG_CNTL                                                     0xa000028
#define ixD3F4_MSI_MSG_ADDR_LO                                                  0xa000029
#define ixD3F4_MSI_MSG_ADDR_HI                                                  0xa00002a
#define ixD3F4_MSI_MSG_DATA_64                                                  0xa00002b
#define ixD3F4_MSI_MSG_DATA                                                     0xa00002a
#define ixD3F4_SSID_CAP_LIST                                                    0xa000030
#define ixD3F4_SSID_CAP                                                         0xa000031
#define ixD3F4_MSI_MAP_CAP_LIST                                                 0xa000032
#define ixD3F4_MSI_MAP_CAP                                                      0xa000032
#define ixD3F4_MSI_MAP_ADDR_LO                                                  0xa000033
#define ixD3F4_MSI_MAP_ADDR_HI                                                  0xa000034
#define ixD3F4_PCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                0xa000040
#define ixD3F4_PCIE_VENDOR_SPECIFIC_HDR                                         0xa000041
#define ixD3F4_PCIE_VENDOR_SPECIFIC1                                            0xa000042
#define ixD3F4_PCIE_VENDOR_SPECIFIC2                                            0xa000043
#define ixD3F4_PCIE_VC_ENH_CAP_LIST                                             0xa000044
#define ixD3F4_PCIE_PORT_VC_CAP_REG1                                            0xa000045
#define ixD3F4_PCIE_PORT_VC_CAP_REG2                                            0xa000046
#define ixD3F4_PCIE_PORT_VC_CNTL                                                0xa000047
#define ixD3F4_PCIE_PORT_VC_STATUS                                              0xa000047
#define ixD3F4_PCIE_VC0_RESOURCE_CAP                                            0xa000048
#define ixD3F4_PCIE_VC0_RESOURCE_CNTL                                           0xa000049
#define ixD3F4_PCIE_VC0_RESOURCE_STATUS                                         0xa00004a
#define ixD3F4_PCIE_VC1_RESOURCE_CAP                                            0xa00004b
#define ixD3F4_PCIE_VC1_RESOURCE_CNTL                                           0xa00004c
#define ixD3F4_PCIE_VC1_RESOURCE_STATUS                                         0xa00004d
#define ixD3F4_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0xa000050
#define ixD3F4_PCIE_DEV_SERIAL_NUM_DW1                                          0xa000051
#define ixD3F4_PCIE_DEV_SERIAL_NUM_DW2                                          0xa000052
#define ixD3F4_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0xa000054
#define ixD3F4_PCIE_UNCORR_ERR_STATUS                                           0xa000055
#define ixD3F4_PCIE_UNCORR_ERR_MASK                                             0xa000056
#define ixD3F4_PCIE_UNCORR_ERR_SEVERITY                                         0xa000057
#define ixD3F4_PCIE_CORR_ERR_STATUS                                             0xa000058
#define ixD3F4_PCIE_CORR_ERR_MASK                                               0xa000059
#define ixD3F4_PCIE_ADV_ERR_CAP_CNTL                                            0xa00005a
#define ixD3F4_PCIE_HDR_LOG0                                                    0xa00005b
#define ixD3F4_PCIE_HDR_LOG1                                                    0xa00005c
#define ixD3F4_PCIE_HDR_LOG2                                                    0xa00005d
#define ixD3F4_PCIE_HDR_LOG3                                                    0xa00005e
#define ixD3F4_PCIE_ROOT_ERR_CMD                                                0xa00005f
#define ixD3F4_PCIE_ROOT_ERR_STATUS                                             0xa000060
#define ixD3F4_PCIE_ERR_SRC_ID                                                  0xa000061
#define ixD3F4_PCIE_TLP_PREFIX_LOG0                                             0xa000062
#define ixD3F4_PCIE_TLP_PREFIX_LOG1                                             0xa000063
#define ixD3F4_PCIE_TLP_PREFIX_LOG2                                             0xa000064
#define ixD3F4_PCIE_TLP_PREFIX_LOG3                                             0xa000065
#define ixD3F4_PCIE_SECONDARY_ENH_CAP_LIST                                      0xa00009c
#define ixD3F4_PCIE_LINK_CNTL3                                                  0xa00009d
#define ixD3F4_PCIE_LANE_ERROR_STATUS                                           0xa00009e
#define ixD3F4_PCIE_LANE_0_EQUALIZATION_CNTL                                    0xa00009f
#define ixD3F4_PCIE_LANE_1_EQUALIZATION_CNTL                                    0xa00009f
#define ixD3F4_PCIE_LANE_2_EQUALIZATION_CNTL                                    0xa0000a0
#define ixD3F4_PCIE_LANE_3_EQUALIZATION_CNTL                                    0xa0000a0
#define ixD3F4_PCIE_LANE_4_EQUALIZATION_CNTL                                    0xa0000a1
#define ixD3F4_PCIE_LANE_5_EQUALIZATION_CNTL                                    0xa0000a1
#define ixD3F4_PCIE_LANE_6_EQUALIZATION_CNTL                                    0xa0000a2
#define ixD3F4_PCIE_LANE_7_EQUALIZATION_CNTL                                    0xa0000a2
#define ixD3F4_PCIE_LANE_8_EQUALIZATION_CNTL                                    0xa0000a3
#define ixD3F4_PCIE_LANE_9_EQUALIZATION_CNTL                                    0xa0000a3
#define ixD3F4_PCIE_LANE_10_EQUALIZATION_CNTL                                   0xa0000a4
#define ixD3F4_PCIE_LANE_11_EQUALIZATION_CNTL                                   0xa0000a4
#define ixD3F4_PCIE_LANE_12_EQUALIZATION_CNTL                                   0xa0000a5
#define ixD3F4_PCIE_LANE_13_EQUALIZATION_CNTL                                   0xa0000a5
#define ixD3F4_PCIE_LANE_14_EQUALIZATION_CNTL                                   0xa0000a6
#define ixD3F4_PCIE_LANE_15_EQUALIZATION_CNTL                                   0xa0000a6
#define ixD3F4_PCIE_ACS_ENH_CAP_LIST                                            0xa0000a8
#define ixD3F4_PCIE_ACS_CAP                                                     0xa0000a9
#define ixD3F4_PCIE_ACS_CNTL                                                    0xa0000a9
#define ixD3F4_PCIE_MC_ENH_CAP_LIST                                             0xa0000bc
#define ixD3F4_PCIE_MC_CAP                                                      0xa0000bd
#define ixD3F4_PCIE_MC_CNTL                                                     0xa0000bd
#define ixD3F4_PCIE_MC_ADDR0                                                    0xa0000be
#define ixD3F4_PCIE_MC_ADDR1                                                    0xa0000bf
#define ixD3F4_PCIE_MC_RCV0                                                     0xa0000c0
#define ixD3F4_PCIE_MC_RCV1                                                     0xa0000c1
#define ixD3F4_PCIE_MC_BLOCK_ALL0                                               0xa0000c2
#define ixD3F4_PCIE_MC_BLOCK_ALL1                                               0xa0000c3
#define ixD3F4_PCIE_MC_BLOCK_UNTRANSLATED_0                                     0xa0000c4
#define ixD3F4_PCIE_MC_BLOCK_UNTRANSLATED_1                                     0xa0000c5
#define ixD3F4_PCIE_MC_OVERLAY_BAR0                                             0xa0000c6
#define ixD3F4_PCIE_MC_OVERLAY_BAR1                                             0xa0000c7
#define ixD3F5_PCIE_PORT_INDEX                                                  0xb000038
#define ixD3F5_PCIE_PORT_DATA                                                   0xb000039
#define ixD3F5_PCIEP_RESERVED                                                   0x0
#define ixD3F5_PCIEP_SCRATCH                                                    0x1
#define ixD3F5_PCIEP_HW_DEBUG                                                   0x2
#define ixD3F5_PCIEP_PORT_CNTL                                                  0x10
#define ixD3F5_PCIE_TX_CNTL                                                     0x20
#define ixD3F5_PCIE_TX_REQUESTER_ID                                             0x21
#define ixD3F5_PCIE_TX_VENDOR_SPECIFIC                                          0x22
#define ixD3F5_PCIE_TX_REQUEST_NUM_CNTL                                         0x23
#define ixD3F5_PCIE_TX_SEQ                                                      0x24
#define ixD3F5_PCIE_TX_REPLAY                                                   0x25
#define ixD3F5_PCIE_TX_ACK_LATENCY_LIMIT                                        0x26
#define ixD3F5_PCIE_TX_CREDITS_ADVT_P                                           0x30
#define ixD3F5_PCIE_TX_CREDITS_ADVT_NP                                          0x31
#define ixD3F5_PCIE_TX_CREDITS_ADVT_CPL                                         0x32
#define ixD3F5_PCIE_TX_CREDITS_INIT_P                                           0x33
#define ixD3F5_PCIE_TX_CREDITS_INIT_NP                                          0x34
#define ixD3F5_PCIE_TX_CREDITS_INIT_CPL                                         0x35
#define ixD3F5_PCIE_TX_CREDITS_STATUS                                           0x36
#define ixD3F5_PCIE_TX_CREDITS_FCU_THRESHOLD                                