
#define ixD3F5_PCIE_LC_STATE1                                                   0xa6
#define ixD3F5_PCIE_LC_STATE2                                                   0xa7
#define ixD3F5_PCIE_LC_STATE3                                                   0xa8
#define ixD3F5_PCIE_LC_STATE4                                                   0xa9
#define ixD3F5_PCIE_LC_STATE5                                                   0xaa
#define ixD3F5_PCIEP_STRAP_LC                                                   0xc0
#define ixD3F5_PCIEP_STRAP_MISC                                                 0xc1
#define ixD3F5_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD3F5_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD3F5_PCIEP_HPGI                                                       0xda
#define ixD3F5_VENDOR_ID                                                        0xb000000
#define ixD3F5_DEVICE_ID                                                        0xb000000
#define ixD3F5_COMMAND                                                          0xb000001
#define ixD3F5_STATUS                                                           0xb000001
#define ixD3F5_REVISION_ID                                                      0xb000002
#define ixD3F5_PROG_INTERFACE                                                   0xb000002
#define ixD3F5_SUB_CLASS                                                        0xb000002
#define ixD3F5_BASE_CLA