     0x60
#define ixD2F4_PCIE_FC_NP                                                       0x61
#define ixD2F4_PCIE_FC_CPL                                                      0x62
#define ixD2F4_PCIE_ERR_CNTL                                                    0x6a
#define ixD2F4_PCIE_RX_CNTL                                                     0x70
#define ixD2F4_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD2F4_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD2F4_PCIE_RX_CNTL3                                                    0x74
#define ixD2F4_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD2F4_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD2F4_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD2F4_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD2F4_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD2F4_PCIE_LC_CNTL                                                     0xa0
#define ixD2F4_PCIE_LC_CNTL2                                                    0xb1
#define ixD2F4_PCIE_LC_CNTL3                                                    0xb5
#define ixD2F4_PCIE_LC_CNTL4                                                    0xb6
#define ixD2F4_PCIE_LC_CNTL5                                                    0xb7
#define ixD2F4_PCIE_LC_CNTL6                                                    0xbb
#define ixD2F4_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD2F4_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD2F4_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD2F4_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD2F4_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD2F4_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD2F4_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD2F4_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD2F4_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD2F4_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD2F4_PCIE_LC_STATE0                                                   0xa5
#define ixD2F4_PCIE_LC_STATE1                                                   0xa6
#define ixD2F4_PCIE_LC_STATE2                                                   0xa7
#define ixD2F4_PCIE_LC_STATE3                                                   0xa8
#define ixD2F4_PCIE_LC_STATE4                                                   0xa9
#define ixD2F4_PCIE_LC_STATE5                                                   0xaa
#define ixD2F4_PCIEP_STRAP_LC                                                   0xc0
#define ixD2F4_PCIEP_STRAP_MISC                                                 0xc1
#define ixD2F4_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD2F4_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD2F4_PCIEP_HPGI                                                       0xda
#define ixD2F4_VENDOR_ID                                                        0x5000000
#define ixD2F4_DEVICE_ID                                                        0x5000000
#define ixD2F4_COMMAND                                                          0x5000001
#define ixD2F4_STATUS                                                           0x5000001
#define ixD2F4_REVISION_ID                                                      0x5000002
#define ixD2F4_PROG_INTERFACE                                                   0x5000002
#define ixD2F4_SUB_CLASS                                                        0x5000002
#define ixD2F4_BASE_CLASS                                                       0x5000002
#define ixD2F4_CACHE_LINE                                                       0x5000003
#define ixD2F4_LATENCY                                                          0x5000003
#define ixD2F4_HEADER                                                           0x5000003
#define ixD2F4_BIST                                                             0x5000003
#define ixD2F4_SUB_BUS_NUMBER_LATENCY                                           0x5000006
#define ixD2F4_IO_BASE_LIMIT                                                    0x5000007
#define ixD2F4_SECONDARY_STATUS                                                 0x5000007
#define ixD2F4_MEM_BASE_LIMIT                                                   0x5000008
#define ixD2F4_PREF_BASE_LIMIT                                                  0x5000009
#define ixD2F4_PREF_BASE_UPPER                                                  0x500000a
#define ixD2F4_PREF_LIMIT_UPPER                                                 0x500000b
#define ixD2F4_IO_BASE_LIMIT_HI                                                 0x500000c
#define ixD2F4_IRQ_BRIDGE_CNTL                                                  0x500000f
#define ixD2F4_CAP_PTR                                                          0x500000d
#define ixD2F4_INTERRUPT_LINE                                                   0x500000f
#define ixD2F4_INTERRUPT_PIN                                                    0x500000f
#define ixD2F4_EXT_BRIDGE_CNTL                                                  0x5000010
#define ixD2F4_PMI_CAP_LIST                                                     0x5000014
#define ixD2F4_PMI_CAP                                                          0x5000014
#define ixD2F4_PMI_STATUS_CNTL                                                  0x5000015
#define ixD2F4_PCIE_CAP_LIST                                                    0x5000016
#define ixD2F4_PCIE_CAP                                                         0x5000016
#define ixD2F4_DEVICE_CAP                                      