       0xd0
#define ixD2F5_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD2F5_PCIEP_HPGI                                                       0xda
#define ixD2F5_VENDOR_ID                                                        0x6000000
#define ixD2F5_DEVICE_ID                                                        0x6000000
#define ixD2F5_COMMAND                                                          0x6000001
#define ixD2F5_STATUS                                                           0x6000001
#define ixD2F5_REVISION_ID                                                      0x6000002
#define ixD2F5_PROG_INTERFACE                                                   0x6000002
#define ixD2F5_SUB_CLASS                                                        0x6000002
#define ixD2F5_BASE_CLASS                                                       0x6000002
#define ixD2F5_CACHE_LINE                                                       0x6000003
#define ixD2F5_LATENCY                                                          0x6000003
#define ixD2F5_HEADER                                                           0x6000003
#define ixD2F5_BIST                                                             0x6000003
#define ixD2F5_SUB_BUS_NUMBER_LATENCY                                           0x6000006
#define ixD2F5_IO_BASE_LIMIT                                                    0x6000007
#define ixD2F5_SECONDARY_STATUS                                                 0x6000007
#define ixD2F5_MEM_BASE_LIMIT                                                   0x6000008
#define ixD2F5_PREF_BASE_LIMIT                                                  0x6000009
#define ixD2F5_PREF_BASE_UPPER                                                  0x600000a
#define ixD2F5_PREF_LIMIT_UPPER                                                 0x600000b
#define ixD2F5_IO_BASE_LIMIT_HI                                                 0x600000c
#define ixD2F5_IRQ_BRIDGE_CNTL                                                  0x600000f
#define ixD2F5_CAP_PTR                                                          0x600000d
#define ixD2F5_INTERRUPT_LINE                                                   0x600000f
#define ixD2F5_INTERRUPT_PIN                                                    0x600000f
#define ixD2F5_EXT_BRIDGE_CNTL                                                  0x6000010
#define ixD2F5_PMI_CAP_LIST                                                     0x6000014
#define ixD2F5_PMI_CAP                                                          0x6000014
#define ixD2F5_PMI_STATUS_CNTL                                                  0x6000015
#define ixD2F5_PCIE_CAP_LIST                                                    0x6000016
#define ixD2F5_PCIE_CAP                                                         0x6000016
#define ixD2F5_DEVICE_CAP                                                       0x6000017
#define ixD2F5_DEVICE_CNTL                                                      0x6000018
#define ixD2F5_DEVICE_STATUS                                                    0x6000018
#define ixD2F5_LINK_CAP                                                         0x6000019
#define ixD2F5_LINK_CNTL                                                        0x600001a
#define ixD2F5_LINK_STATUS                                                      0x600001a
#define ixD2F5_SLOT_CAP                                                         0x600001b
#define ixD2F5_SLOT_CNTL                                                        0x600001c
#define ixD2F5_SLOT_STATUS                                                      0x600001c
#define ixD2F5_ROOT_CNTL                                                        0x600001d
#define ixD2F5_ROOT_CAP                                                         0x600001d
#define ixD2F5_ROOT_STATUS                                                      0x600001e
#define ixD2F5_DEVICE_CAP2                                                      0x600001f
#define ixD2F5_DEVICE_CNTL2                                                     0x6000020
#define ixD2F5_DEVICE_STATUS2                                                   0x6000020
#define ixD2F5_LINK_CAP2                                                        0x6000021
#define ixD2F5_LINK_CNTL2                                                       0x6000022
#define ixD2F5_LINK_STATUS2                                                     0x6000022
#define ixD2F5_SLOT_CAP2                                                        0x6000023
#define ixD2F5_SLOT_CNTL2                                                       0x6000024
#define ixD2F5_SLOT_STATUS2                                                     0x6000024
#define ixD2F5_MSI_CAP_LIST                                                     0x6000028
#define ixD2F5_MSI_MSG_CNTL                                                     0x6000028
#define ixD2F5_MSI_MSG_ADDR_LO                                                  0x6000029
#define ixD2F5_MSI_MSG_ADDR_HI                                                  0x600002a
#define ixD2F5_MSI_MSG_DATA_64                                                  0x600002b
#define ixD2F5_MSI_MSG_DATA                                                     0x600002a
#define ixD2F5_SSID_CAP_LIST                                                    0x6000030
#define ixD2F5_SSID_CAP                                                         0x6000031
#define ixD2F5_MSI_MAP_CAP_LIST                                                 0x6000032
#define ixD2F5_MSI_MAP_CAP                                                      0x6000032
#define ixD2F5_MSI_MAP_ADDR_LO                                                  0x6000033
#define ixD2F5_MSI_MAP_ADDR_HI                                                  0x6000034
#define ixD2F5_PCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                0x6000040
#define ixD2F5_PCIE_VENDOR_SPECIFIC_HDR                                         0x6000041
#define ixD2F5_PCIE_VENDOR_SPECIFIC1                                            0x6000042
#define ixD2F5_PCIE_VENDOR_SPECIFIC2                                            0x6000043
#define ixD2F5_PCIE_VC_ENH_CAP_LIST                                             0x6000044
#define ixD2F5_PCIE_PORT_VC_CAP_REG1                                            0x6000045
#define ixD2F5_PCIE_PORT_VC_CAP_REG2                                            0x6000046
#define ixD2F5_PCIE_PORT_VC_CNTL                                                0x6000047
#define ixD2F5_PCIE_PORT_VC_STATUS                                              0x6000047
#define ixD2F5_PCIE_VC0_RESOURCE_CAP                                            0x6000048
#define ixD2F5_PCIE_VC0_RESOURCE_CNTL                                           0x6000049
#define ixD2F5_PCIE_VC0_RESOURCE_STATUS                                         0x600004a
#define ixD2F5_PCIE_VC1_RESOURCE_CAP                                            0x600004b
#define ixD2F5_PCIE_VC1_RESOURCE_CNTL                                           0x600004c
#define ixD2F5_PCIE_VC1_RESOURCE_STATUS                                         0x600004d
#define ixD2F5_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0x6000050
#define ixD2F5_PCIE_DEV_SERIAL_NUM_DW1                                          0x6000051
#define ixD2F5_PCIE_DEV_SERIAL_NUM_DW2                                          0x6000052
#define ixD2F5_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0x6000054
#define ixD2F5_PCIE_UNCORR_ERR_STATUS                                           0x6000055
#define ixD2F5_PCIE_UNCORR_ERR_MASK                                             0x6000056
#define ixD2F5_PCIE_UNCORR_ERR_SEVERITY                                         0x6000057
#define ixD2F5_PCIE_CORR_ERR_STATUS                                             0x6000058
#define ixD2F5_PCIE_CORR_ERR_MASK                                               0x6000059
#define ixD2F5_PCIE_ADV_ERR_CAP_CNTL                                            0x600005a
#define ixD2F5_PCIE_HDR_LOG0                                                    0x600005b
#define ixD2F5_PCIE_HDR_LOG1                                                    0x600005c
#define ixD2F5_PCIE_HDR_LOG2                                                    0x600005d
#define ixD2F5_PCIE_HDR_LOG3                                                    0x600005e
#define ixD2F5_PCIE_ROOT_ERR_CMD                                                0x600005f
#define ixD2F5_PCIE_ROOT_ERR_STATUS                                             0x6000060
#define ixD2F5_PCIE_ERR_SRC_ID                                                  0x6000061
#define ixD2F5_PCIE_TLP_PREFIX_LOG0                                             0x6000062
#define ixD2F5_PCIE_TLP_PREFIX_LOG1                                             0x6000063
#define ixD2F5_PCIE_TLP_PREFIX_LOG2                                             0x6000064
#define ixD2F5_PCIE_TLP_PREFIX_LOG3                                             0x6000065
#define ixD2F5_PCIE_SECONDARY_ENH_CAP_LIST                                      0x600009c
#define ixD2F5_PCIE_LINK_CNTL3                                                  0x600009d
#define ixD2F5_PCIE_LANE_ERROR_STATUS                                           0x600009e
#define ixD2F5_PCIE_LANE_0_EQUALIZATION_CNTL                                    0x600009f
#define ixD2F5_PCIE_LANE_1_EQUALIZATION_CNTL                                    0x600009f
#define ixD2F5_PCIE_LANE_2_EQUALIZATION_CNTL                                    0x60000a0
#define ixD2F5_PCIE_LANE_3_EQUALIZATION_CNTL                                    0x60000a0
#define ixD2F5_PCIE_LANE_4_EQUALIZATION_CNTL                                    0x60000a1
#define ixD2F5_PCIE_LANE_5_EQUALIZATION_CNTL                                    0x60000a1
#define ixD2F5_PCIE_LANE_6_EQUALIZATION_CNTL                                    0x60000a2
#define ixD2F5_PCIE_LANE_7_EQUALIZATION_CNTL                                    0x60000a2
#define ixD2F5_PCIE_LANE_8_EQUALIZATION_CNTL                                    0x60000a3
#define ixD2F5_PCIE_LANE_9_EQUALIZATION_CNTL                                    0x60000a3
#define ixD2F5_PCIE_LANE_10_EQUALIZATION_CNTL                                   0x60000a4
#define ixD2F5_PCIE_LANE_11_EQUALIZATION_CNTL                                   0x60000a4
#define ixD2F5_PCIE_LANE_12_EQUALIZATION_CNTL                                   0x60000a5
#define ixD2F5_PCIE_LANE_13_EQUALIZATION_CNTL                                   0x60000a5
#define ixD2F5_PCIE_LANE_14_EQUALIZATION_CNTL                                   0x60000a6
#define ixD2F5_PCIE_LANE_15_EQUALIZATION_CNTL                                   0x60000a6
#define ixD2F5_PCIE_ACS_ENH_CAP_LIST                                            0x60000a8
#define ixD2F5_PCIE_ACS_CAP                                                     0x60000a9
#define ixD2F5_PCIE_ACS_CNTL                                                    0x60000a9
#define ixD2F5_PCIE_MC_ENH_CAP_LIST                                             0x60000bc
#define ixD2F5_PCIE_MC_CAP                                                      0x60000bd
#define ixD2F5_PCIE_MC_CNTL                                                     0x60000bd
#define ixD2F5_PCIE_MC_ADDR0                                                    0x60000be
#define ixD2F5_PCIE_MC_ADDR1                                                    0x60000bf
#define ixD2F5_PCIE_MC_RCV0                                                     0x60000c0
#define ixD2F5_PCIE_MC_RCV1                                                     0x60000c1
#define ixD2F5_PCIE_MC_BLOCK_ALL0                                               0x60000c2
#define ixD2F5_PCIE_MC_BLOCK_ALL1                                               0x60000c3
#define ixD2F5_PCIE_MC_BLOCK_UNTRANSLATED_0                                     0x60000c4
#define ixD2F5_PCIE_MC_BLOCK_UNTRANSLATED_1                                     0x60000c5
#define ixD2F5_PCIE_MC_OVERLAY_BAR0                                             0x60000c6
#define ixD2F5_PCIE_MC_OVERLAY_BAR1                                             0x60000c7
#define ixD3F1_PCIE_PORT_INDEX                                                  0x7000038
#define ixD3F1_PCIE_PORT_DATA                                                   0x7000039
#define ixD3F1_PCIEP_RESERVED                                                   0x0
#define ixD3F1_PCIEP_SCRATCH                                                    0x1
#define ixD3F1_PCIEP_HW_DEBUG                                                   0x2
#define ixD3F1_PCIEP_PORT_CNTL                                                  0x10
#define ixD3F1_PCIE_TX_CNTL                                                     0x20
#define ixD3F1_PCIE_TX_REQUESTER_ID                                             0x21
#define ixD3F1_PCIE_TX_VENDOR_SPECIFIC                                          0x22
#define ixD3F1_PCIE_TX_REQUEST_NUM_CNTL                                         0x23
#define ixD3F1_PCIE_TX_SEQ                                                      0x24
#define ixD3F1_PCIE_TX_REPLAY                                                   0x25
#define ixD3F1_PCIE_TX_ACK_LATENCY_LIMIT                                        0x26
#define ixD3F1_PCIE_TX_CREDITS_ADVT_P                                           0x30
#define ixD3F1_PCIE_TX_CREDITS_ADVT_NP                                          0x31
#define ixD3F1_PCIE_TX_CREDITS_ADVT_CPL                                         0x32
#define ixD3F1_PCIE_TX_CREDITS_INIT_P                                           0x33
#define ixD3F1_PCIE_TX_CREDITS_INIT_NP                                          0x34
#define ixD3F1_PCIE_TX_CREDITS_INIT_CPL                                         0x35
#define ixD3F1_PCIE_TX_CREDITS_STATUS                                           0x36
#define ixD3F1_PCIE_TX_CREDITS_FCU_THRESHOLD                                    0x37
#define ixD3F1_PCIE_P_PORT_LANE_STATUS                                          0x50
#define ixD3F1_PCIE_FC_P                                                        0x60
#define ixD3F1_PCIE_FC_NP                                                       0x61
#define ixD3F1_PCIE_FC_CPL                                                      0x62
#define ixD3F1_PCIE_ERR_CNTL                                                    0x6a
#define ixD3F1_PCIE_RX_CNTL                                                     0x70
#define ixD3F1_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD3F1_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD3F1_PCIE_RX_CNTL3                                                    0x74
#define ixD3F1_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD3F1_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD3F1_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD3F1_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD3F1_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD3F1_PCIE_LC_CNTL                                                     0xa0
#define ixD3F1_PCIE_LC_CNTL2                                                    0xb1
#define ixD3F1_PCIE_LC_CNTL3                                                    0xb5
#define ixD3F1_PCIE_LC_CNTL4                                                    0xb6
#define ixD3F1_PCIE_LC_CNTL5                                                    0xb7
#define ixD3F1_PCIE_LC_CNTL6                                                    0xbb
#define ixD3F1_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD3F1_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD3F1_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD3F1_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD3F1_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD3F1_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD3F1_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD3F1_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD3F1_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD3F1_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD3F1_PCIE_LC_STATE0                                                   0xa5
#define ixD3F1_PCIE_LC_STATE1                                                   0xa6
#define ixD3F1_PCIE_LC_STATE2                                                   0xa7
#define ixD3F1_PCIE_LC_STATE3                                                   0xa8
#define ixD3F1_PCIE_LC_STATE4                                                   0xa9
#define ixD3F1_PCIE_LC_STATE5                                                   0xaa
#define ixD3F1_PCIEP_STRAP_LC                                                   0xc0
#define ixD3F1_PCIEP_STRAP_MISC                                                 0xc1
#define ixD3F1_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD3F1_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD3F1_PCIEP_HPGI                                                       0xda
#define ixD3F1_VENDOR_ID                                                        0x7000000
#define ixD3F1_DEVICE_ID                                                        0x7000000
#define ixD3F1_COMMAND                                                          0x7000001
#define ixD3F1_STATUS                                                           0x7000001
#define ixD3F1_REVISION_ID                                                      0x7000002
#define ixD3F1_PROG_INTERFACE                                                   0x7000002
#define ixD3F1_SUB_CLASS                                                        0x7000002
#define ixD3F1_BASE_CLASS                                                       0x7000002
#define ixD3F1_CACHE_LINE                                                       0x7000003
#define ixD3F1_LATENCY                                                          0x7000003
#define ixD3F1_HEADER                                                           0x7000003
#define ixD3F1_BIST                                                             0x7000003
#define ixD3F1_SUB_BUS_NUMBER_LATENCY                                           0x7000006
#define ixD3F1_IO_BASE_LIMIT                                                    0x7000007
#define ixD3F1_SECONDARY_STATUS                                                 0x7000007
#define ixD3F1_MEM_BASE_LIMIT                                                   0x7000008
#define ixD3F1_PREF_BASE_LIMIT                                                  0x7000009
#define ixD3F1_PREF_BASE_UPPER                                                  0x700000a
#define ixD3F1_PREF_LIMIT_UPPER                                                 0x700000b
#define ixD3F1_IO_BASE_LIMIT_HI                                                 0x700000c
#define ixD3F1_IRQ_BRIDGE_CNTL                                                  0x700000f
#define ixD3F1_CAP_PTR                                                          0x700000d
#define ixD3F1_INTERRUPT_LINE                                                   0x700000f
#define ixD3F1_INTERRUPT_PIN                                                    0x700000f
#define ixD3F1_EXT_BRIDGE_CNTL                                                  0x7000010
#define ixD3F1_PMI_CAP_LIST                                                     0x7000014
#define ixD3F1_PMI_CAP                                                          0x7000014
#define ixD3F1_PMI_STATUS_CNTL                                                  0x7000015
#define ixD3F1_PCIE_CAP_LIST                                                    0x7000016
#define ixD3F1_PCIE_CAP                                                         0x7000016
#define ixD3F1_DEVICE_CAP                                                       0x7000017
#define ixD3F1_DEVICE_CNTL                                                      0x7000018
#define ixD3F1_DEVICE_STATUS                                                    0x7000018
#define ixD3F1_LINK_CAP                                                         0x7000019
#define ixD3F1_LINK_CNTL                                                        0x700001a
#define ixD3F1_LINK_STATUS                                                      0x700001a
#define ixD3F1_SLOT_CAP                                                         0x700001b
#define ixD3F1_SLOT_CNTL                                                        0x700001c
#define ixD3F1_SLOT_STATUS                                                      0x700001c
#define ixD3F1_ROOT_CNTL                                                        0x700001d
#define ixD3F1_ROOT_CAP                                                         0x700001d
#define ixD3F1_ROOT_STATUS                                                      0x700001e
#define ixD3F1_DEVICE_CAP2                                                      0x700001f
#define ixD3F1_DEVICE_CNTL2                                                     0x7000020
#define ixD3F1_DEVICE_STATUS2                                                   0x7000020
#define ixD3F1_LINK_CAP2                                                        0x7000021
#define ixD3F1_LINK_CNTL2                                                       0x7000022
#define ixD3F1_LINK_STATUS2                                                     0x7000022
#define ixD3F1_SLOT_CAP2                                                        0x7000023
#define ixD3F1_SLOT_CNTL2                                                       0x7000024
#define ixD3F1_SLOT_STATUS2                                                     0x7000024
#define ixD3F1_MSI_CAP_LIST                                                     0x7000028
#define ixD3F1_MSI_MSG_CNTL                                                     0x7000028
#define ixD3F1_MSI_MSG_ADDR_LO                                                  0x7000029
#define ixD3F1_MSI_MSG_ADDR_HI                                                  0x700002a
#define ixD3F1_MSI_MSG_DATA_64                                                  0x700002b
#define ixD3F1_MSI_MSG_DATA                                                     0x700002a
#define ixD3F1_SSID_CAP_LIST                                                    0x7000030
#define ixD3F1_SSID_CAP                                                         0x7000031
#define ixD3F1_MSI_MAP_CAP_LIST                                                 0x7000032
#define ixD3F1_MSI_MAP_CAP                                                      0x7000032
#define ixD3F1_MSI_MAP_ADDR_LO                                                  0x7000033
#define ixD3F1_MSI_MAP_ADDR_HI                                                  0x7000034
#define ixD3F1_PCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                0x7000040
#define ixD3F1_PCIE_VENDOR_SPECIFIC_HDR                                         0x7000041
#define ixD3F1_PCIE_VENDOR_SPECIFIC1                                            0x7000042
#define ixD3F1_PCIE_VENDOR_SPECIFIC2                                            0x7000043
#define ixD3F1_PCIE_VC_ENH_CAP_LIST                                             0x7000044
#define ixD3F1_PCIE_PORT_VC_CAP_REG1                                            0x7000045
#define ixD3F1_PCIE_PORT_VC_CAP_REG2                                            0x7000046
#define ixD3F1_PCIE_PORT_VC_CNTL                                                0x7000047
#define ixD3F1_PCIE_PORT_VC_STATUS                                              0x7000047
#define ixD3F1_PCIE_VC0_RESOURCE_CAP                                            0x7000048
#define ixD3F1_PCIE_VC0_RESOURCE_CNTL                                           0x7000049
#define ixD3F1_PCIE_VC0_RESOURCE_STATUS                                         0x700004a
#define ixD3F1_PCIE_VC1_RESOURCE_CAP                                            0x700004b
#define ixD3F1_PCIE_VC1_RESOURCE_CNTL                                           0x700004c
#define ixD3F1_PCIE_VC1_RESOURCE_STATUS                                         0x700004d
#define ixD3F1_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0x7000050
#define ixD3F1_PCIE_DEV_SERIAL_NUM_DW1                                          0x7000051
#define ixD3F1_PCIE_DEV_SERIAL_NUM_DW2                                          0x7000052
#define ixD3F1_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0x7000054
#define ixD3F1_PCIE_UNCORR_ERR_STATUS                                           0x7000055
#define ixD3F1_PCIE_UNCORR_ERR_MASK                                             0x7000056
#define ixD3F1_PCIE_UNCORR_ERR_SEVERITY                                         0x7000057
#define ixD3F1_PCIE_CORR_ERR_STATUS                                             0x7000058
#define ixD3F1_PCIE_CORR_ERR_MASK                                               0x7000059
#define ixD3F1_PCIE_ADV_ERR_CAP_CNTL                                            0x700005a
#define ixD3F1_PCIE_HDR_LOG0                                                    0x700005b
#define ixD3F1_PCIE_HDR_LOG1                                                    0x700005c
#define ixD3F1_PCIE_HDR_LOG2                                                    0x700005d
#define ixD3F1_PCIE_HDR_LOG3                                                    0x700005e
#define ixD3F1_PCIE_ROOT_ERR_CMD                                                0x700005f
#define ixD3F1_PCIE_ROOT_ERR_STATUS                                             0x7000060
#define ixD3F1_PCIE_ERR_SRC_ID                                                  0x7000061
#define ixD3F1_PCIE_TLP_PREFIX_LOG0                                             0x7000062
#define ixD3F1_PCIE_TLP_PREFIX_LOG1                                             0x7000063
#define ixD3F1_PCIE_TLP_PREFIX_LOG2                                             0x7000064
#define ixD3F1_PCIE_TLP_PREFIX_LOG3                                             0x7000065
#define ixD3F1_PCIE_SECONDARY_ENH_CAP_LIST                                      0x700009c
#define ixD3F1_PCIE_LINK_CNTL3                                                  0x700009d
#define ixD3F1_PCIE_LANE_ERROR_STATUS                                           0x700009e
#define ixD3F1_PCIE_LANE_0_EQUALIZATION_CNTL                                    0x700009f
#define ixD3F1_PCIE_LANE_1_EQUALIZATION_CNTL                                    0x700009f
#define ixD3F1_PCIE_LANE_2_EQUALIZATION_CNTL                                    0x70000a0
#define ixD3F1_PCIE_LANE_3_EQUALIZATION_CNTL                                    0x70000a0
#define ixD3F1_PCIE_LANE_4_EQUALIZATION_CNTL                                    0x70000a1
#define ixD3F1_PCIE_LANE_5_EQUALIZATION_CNTL                                    0x70000a1
#define ixD3F1_PCIE_LANE_6_EQUALIZATION_CNTL                                    0x70000a2
#define ixD3F1_PCIE_LANE_7_EQUALIZATION_CNTL                                    0x70000a2
#define ixD3F1_PCIE_LANE_8_EQUALIZATION_CNTL                                    0x70000a3
#define ixD3F1_PCIE_LANE_9_EQUALIZATION_CNTL                                    0x70000a3
#define ixD3F1_PCIE_LANE_10_EQUALIZATION_CNTL                                   0x70000a4
#define ixD3F1_PCIE_LANE_11_EQUALIZATION_CNTL                                   0x70000a4
#define ixD3F1_PCIE_LANE_12_EQUALIZATION_CNTL                                   0x70000a5
#define ixD3F1_PCIE_LANE_13_EQUALIZATION_CNTL                                   0x70000a5
#define ixD3F1_PCIE_LANE_14_EQUALIZATION_CNTL                                   0x70000a6
#define ixD3F1_PCIE_LANE_15_EQUALIZATION_CNTL                                   0x70000a6
#define ixD3F1_PCIE_ACS_ENH_CAP_LIST                                            0x70000a8
#define ixD3F1_PCIE_ACS_CAP                                                     0x70000a9
#define ixD3F1_PCIE_ACS_CNTL                                                    0x70000a9
#define ixD3F1_PCIE_MC_ENH_CAP_LIST                                             0x70000bc
#define ixD3F1_PCIE_MC_CAP                                                      0x70000bd
#define ixD3F1_PCIE_MC_CNTL                                                     0x70000bd
#define ixD3F1_PCIE_MC_ADDR0                                                    0x70000be
#define ixD3F1_PCIE_MC_ADDR1                                                    0x70000bf
#define ixD3F1_PCIE_MC_RCV0                                                     0x70000c0
#define ixD3F1_PCIE_MC_RCV1                                                     0x70000c1
#define ixD3F1_PCIE_MC_BLOCK_ALL0                                               0x70000c2
#define ixD3F1_PCIE_MC_BLOCK_ALL1                                               0x70000c3
#define ixD3F1_PCIE_MC_BLOCK_UNTRANSLATED_0                                     0x70000c4
#define ixD3F1_PCIE_MC_BLOCK_UNTRANSLATED_1                                     0x70000c5
#define ixD3F1_PCIE_MC_OVERLAY_BAR0                                             0x70000c6
#define ixD3F1_PCIE_MC_OVERLAY_BAR1                                             0x70000c7
#define ixD3F2_PCIE_PORT_INDEX                                                  0x8000038
#define ixD3F2_PCIE_PORT_DATA                                                   0x8000039
#define ixD3F2_PCIEP_RESERVED                                                   0x0
#define ixD3F2_PCIEP_SCRATCH                                                    0x1
#define ixD3F2_PCIEP_HW_DEBUG                                                   0x2
#define ixD3F2_PCIEP_PORT_CNTL                                                  0x10
#define ixD3F2_PCIE_TX_CNTL                                                     0x20
#define ixD3F2_PCIE_TX_REQUESTER_ID                                             0x21
#define ixD3F2_PCIE_TX_VENDOR_SPECIFIC                                          0x22
#define ixD3F2_PCIE_TX_REQUEST_NUM_CNTL                                         0x23
#define ixD3F2_PCIE_TX_SEQ                                                      0x24
#define ixD3F2_PCIE_TX_REPLAY                                                   0x25
#define ixD3F2_PCIE_TX_ACK_LATENCY_LIMIT                                        0x26
#define ixD3F2_PCIE_TX_CREDITS_ADVT_P                                           0x30
#define ixD3F2_PCIE_TX_CREDITS_ADVT_NP                                          0x31
#define ixD3F2_PCIE_TX_CREDITS_ADVT_CPL                                         0x32
#define ixD3F2_PCIE_TX_CREDITS_INIT_P                                           0x33
#define ixD3F2_PCIE_TX_CREDITS_INIT_NP                                          0x34
#define ixD3F2_PCIE_TX_CREDITS_INIT_CPL                                         0x35
#define ixD3F2_PCIE_TX_CREDITS_STATUS                                           0x36
#define ixD3F2_PCIE_TX_CREDITS_FCU_THRESHOLD                                    0x37
#define ixD3F2_PCIE_P_PORT_LANE_STATUS                                          0x50
#define ixD3F2_PCIE_FC_P                                                        0x60
#define ixD3F2_PCIE_FC_NP                                                       0x61
#define ixD3F2_PCIE_FC_CPL                                                      0x62
#define ixD3F2_PCIE_ERR_CNTL                                                    0x6a
#define ixD3F2_PCIE_RX_CNTL                                                     0x70
#define ixD3F2_PCIE_RX_EXPECTED_SEQNUM                                          0x71
#define ixD3F2_PCIE_RX_VENDOR_SPECIFIC                                          0x72
#define ixD3F2_PCIE_RX_CNTL3                                                    0x74
#define ixD3F2_PCIE_RX_CREDITS_ALLOCATED_P                                      0x80
#define ixD3F2_PCIE_RX_CREDITS_ALLOCATED_NP                                     0x81
#define ixD3F2_PCIE_RX_CREDITS_ALLOCATED_CPL                                    0x82
#define ixD3F2_PCIEP_ERROR_INJECT_PHYSICAL                                      0x83
#define ixD3F2_PCIEP_ERROR_INJECT_TRANSACTION                                   0x84
#define ixD3F2_PCIE_LC_CNTL                                                     0xa0
#define ixD3F2_PCIE_LC_CNTL2                                                    0xb1
#define ixD3F2_PCIE_LC_CNTL3                                                    0xb5
#define ixD3F2_PCIE_LC_CNTL4                                                    0xb6
#define ixD3F2_PCIE_LC_CNTL5                                                    0xb7
#define ixD3F2_PCIE_LC_CNTL6                                                    0xbb
#define ixD3F2_PCIE_LC_BW_CHANGE_CNTL                                           0xb2
#define ixD3F2_PCIE_LC_TRAINING_CNTL                                            0xa1
#define ixD3F2_PCIE_LC_LINK_WIDTH_CNTL                                          0xa2
#define ixD3F2_PCIE_LC_N_FTS_CNTL                                               0xa3
#define ixD3F2_PCIE_LC_SPEED_CNTL                                               0xa4
#define ixD3F2_PCIE_LC_CDR_CNTL                                                 0xb3
#define ixD3F2_PCIE_LC_LANE_CNTL                                                0xb4
#define ixD3F2_PCIE_LC_FORCE_COEFF                                              0xb8
#define ixD3F2_PCIE_LC_BEST_EQ_SETTINGS                                         0xb9
#define ixD3F2_PCIE_LC_FORCE_EQ_REQ_COEFF                                       0xba
#define ixD3F2_PCIE_LC_STATE0                                                   0xa5
#define ixD3F2_PCIE_LC_STATE1                                                   0xa6
#define ixD3F2_PCIE_LC_STATE2                                                   0xa7
#define ixD3F2_PCIE_LC_STATE3                                                   0xa8
#define ixD3F2_PCIE_LC_STATE4                                                   0xa9
#define ixD3F2_PCIE_LC_STATE5                                                   0xaa
#define ixD3F2_PCIEP_STRAP_LC                                                   0xc0
#define ixD3F2_PCIEP_STRAP_MISC                                                 0xc1
#define ixD3F2_PCIEP_BCH_ECC_CNTL                                               0xd0
#define ixD3F2_PCIEP_HPGI_PRIVATE                                               0xd2
#define ixD3F2_PCIEP_HPGI                                                       0xda
#define ixD3F2_VENDOR_ID                                                        0x8000000
#define ixD3F2_DEVICE_ID                                                        0x8000000
#define ixD3F2_COMMAND                                                          0x8000001
#define ixD3F2_STATUS                                                           0x8000001
#define ixD3F2_REVISION_ID                                                      0x8000002
#define ixD3F2_PROG_INTERFACE                                                   0x8000002
#define ixD3F2_SUB_CLASS                                                        0x8000002
#define ixD3F2_BASE_CLASS                                                       0x8000002
#define ixD3F2_CACHE_LINE                                                       0x8000003
#define ixD3F2_LATENCY                                                          0x8000003
#define ixD3F2_HEADER                                                           0x8000003
#define ixD3F2_BIST                                                             0x8000003
#define ixD3F2_SUB_BUS_NUMBER_LATENCY                                           0x8000006
#define ixD3F2_IO_BASE_LIMIT                                                    0x8000007
#define ixD3F2_SECONDARY_STATUS                                                 0x8000007
#define ixD3F2_MEM_BASE_LIMIT                                                   0x8000008
#define ixD3F2_PREF_BASE_LIMIT                                                  0x8000009
#define ixD3F2_PREF_BASE_UPPER                                                  0x800000a
#define ixD3F2_PREF_LIMIT_UPPER                                                 0x800000b
#define ixD3F2_IO_BASE_LIMIT_HI                                                 0x800000c
#define ixD3F2_IRQ_BRIDGE_CNTL                                                  0x800000f
#define ixD3F2_CAP_PTR                                                          0x800000d
#define ixD3F2_INTERRUPT_LINE                                                   0x800000f
#define ixD3F2_INTERRUPT_PIN                                                    0x800000f
#define ixD3F2_EXT_BRIDGE_CNTL                                                  0x8000010
#define ixD3F2_PMI_CAP_LIST                                                     0x8000014
#define ixD3F2_PMI_CAP                                                          0x8000014
#define ixD3F2_PMI_STATUS_CNTL                                                  0x8000015
#define ixD3F2_PCIE_CAP_LIST                                                    0x8000016
#define ixD3F2_PCIE_CAP                                                         0x8000016
#define ixD3F2_DEVICE_CAP                                                       0x8000017
#define ixD3F2_DEVICE_CNTL                                                      0x8000018
#define ixD3F2_DEVICE_STATUS                                                    0x8000018
#define ixD3F2_LINK_CAP                                                         0x8000019
#define ixD3F2_LINK_CNTL                                                        0x800001a
#define ixD3F2_LINK_STATUS                                                      0x800001a
#define ixD3F2_SLOT_CAP                                                         0x800001b
#define ixD3F2_SLOT_CNTL                                                        0x800001c
#define ixD3F2_SLOT_STATUS                                                      0x800001c
#define ixD3F2_ROOT_CNTL                                                        0x800001d
#define ixD3F2_ROOT_CAP                                                         0x800001d
#define ixD3F2_ROOT_STATUS                                                      0x800001e
#define ixD3F2_DEVICE_CAP2                                                      0x800001f
#define ixD3F2_DEVICE_CNTL2                                                     0x8000020
#define ixD3F2_DEVICE_STATUS2                                                   0x8000020
#define ixD3F2_LINK_CAP2                                                        0x8000021
#define ixD3F2_LINK_CNTL2                                                       0x8000022
#define ixD3F2_LINK_STATUS2                                                     0x8000022
#define ixD3F2_SLOT_CAP2                                                        0x8000023
#define ixD3F2_SLOT_CNTL2                                                       0x8000024
#define ixD3F2_SLOT_STATUS2                                                     0x8000024
#define ixD3F2_MSI_CAP_LIST                                                     0x8000028
#define ixD3F2_MSI_MSG_CNTL                                                     0x8000028
#define ixD3F2_MSI_MSG_ADDR_LO                                                  0x8000029
#define ixD3F2_MSI_MSG_ADDR_HI                                                  0x800002a
#define ixD3F2_MSI_MSG_DATA_64                                                  0x800002b
#define ixD3F2_MSI_MSG_DATA                                                     0x800002a
#define ixD3F2_SSID_CAP_LIST                                                    0x8000030
#define ixD3F2_SSID_CAP                                                         0x8000031
#define ixD3F2_MSI_MAP_CAP_LIST                                                 0x8000032
#define ixD3F2_MSI_MAP_CAP                                                      0x8000032
#define ixD3F2_MSI_MAP_ADDR_LO                                                  0x8000033
#define ixD3F2_MSI_MAP_ADDR_HI                                                  0x8000034
#define ixD3F2_PCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                0x8000040
#define ixD3F2_PCIE_VENDOR_SPECIFIC_HDR                                         0x8000041
#define ixD3F2_PCIE_VENDOR_SPECIFIC1                                            0x8000042
#define ixD3F2_PCIE_VENDOR_SPECIFIC2                                            0x8000043
#define ixD3F2_PCIE_VC_ENH_CAP_LIST                                             0x8000044
#define ixD3F2_PCIE_PORT_VC_CAP_REG1                                            0x8000045
#define ixD3F2_PCIE_PORT_VC_CAP_REG2                                            0x8000046
#define ixD3F2_PCIE_PORT_VC_CNTL                                                0x8000047
#define ixD3F2_PCIE_PORT_VC_STATUS                                              0x8000047
#define ixD3F2_PCIE_VC0_RESOURCE_CAP                                            0x8000048
#define ixD3F2_PCIE_VC0_RESOURCE_CNTL                                           0x8000049
#define ixD3F2_PCIE_VC0_RESOURCE_STATUS                                         0x800004a
#define ixD3F2_PCIE_VC1_RESOURCE_CAP                                            0x800004b
#define ixD3F2_PCIE_VC1_RESOURCE_CNTL                                           0x800004c
#define ixD3F2_PCIE_VC1_RESOURCE_STATUS                                         0x800004d
#define ixD3F2_PCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                 0x8000050
#define ixD3F2_PCIE_DEV_SERIAL_NUM_DW1                                          0x8000051
#define ixD3F2_PCIE_DEV_SERIAL_NUM_DW2                                          0x8000052
#define ixD3F2_PCIE_ADV_ERR_RPT_ENH_CAP_LIST                                    0x8000054
#define ixD3F2_PCIE_UNCORR_ERR_STATUS                                           0x8000055
#define ixD3F2_PCIE_UNCORR_ERR_MASK                                             0x8000056
#define ixD3F2_PCIE_UNCORR_ERR_SEVERITY                                         0x8000057
#define ixD3F2_PCIE_CORR_ERR_STATUS                                             0x8000058
#define ixD3F2_PCIE_CORR_ERR_MASK                                               0x8000059
#define ixD3F2_PCIE_ADV_ERR_CAP_CNTL                                            0x800005a
#define ixD3F2_PCIE_HDR_LOG0                                                    0x800005b
#define ixD3F2_PCIE_HDR_LOG1                                                    0x800005c
#define ixD3F2_PCIE_HDR_LOG2                                                    0x800005d
#define ixD3F2_PCIE_HDR_LOG3                                                    0x800005e
#define ixD3F2_PCIE_ROOT_ERR_CMD                                                0x800005f
#define ixD3F2_PCIE_ROOT_ERR_STATUS                                             0x8000060
#define ixD3F2_PCIE_ERR_SRC_ID                                                  0x8000061
#define ixD3F2_PCIE_TLP_PREFIX_LOG0                                             0x8000062
#define ixD3F2_PCIE_TLP_PREFIX_LOG1                                             0x8000063
#define ixD3F2_PCIE_TLP_PREFIX_LOG2                                             0x8000064
#define ixD3F2_PCIE_TLP_PREFIX_LOG3                                             0x8000065
#define ixD3F2_PCIE_SECONDARY_ENH_CAP_LIST                                      0x800009c
#define ixD3F2_PCIE_LINK_CNTL3                                                  0x800009d
#define ixD3F2_PCIE_LANE_ERROR_STATUS                                           0x800009e
#define ixD3F2_PCIE_LANE_0_EQUALIZATION_CNTL                                    0x800009f
#define ixD3F2_PCIE_LANE_1_EQUALIZATION_CNTL                                    0x800009f
#define ixD3F2_PCIE_LANE_2_EQUALIZATION_CNTL                                    0x80000a0
#define ixD3F2_PCIE_LANE_3_EQUALIZATION_CNTL                                    0x80000a0
#define ixD3F2_PCIE_LANE_4_EQUALIZATION_CNTL                                    0x80000a1
#define ixD3F2_PCIE_LANE_5_EQUALIZATION_CNTL                                    0x80000a1
#define ixD3F2_PCIE_LANE_6_EQUALIZATION_CNTL                                    0x80000a2
#define ixD3F2_PCIE_LANE_7_EQUALIZATION_CNTL                                    0x80000a2
#define ixD3F2_PCIE_LANE_8_EQUALIZATION_CNTL                                    0x80000a3
#define ixD3F2_PCIE_LANE_9_EQUALIZATION_CNTL                                    0x80000a3
#define ixD3F2_PCIE_LANE_10_EQUALIZATION_CNTL                                   0x80000a4
#define ixD3F2_PCIE_LANE_11_EQUALIZATION_CNTL                                   0x80000a4
#define ixD3F2_PCIE_LANE_12_EQUALIZATION_CNTL                                   0x80000a5
#define ixD3F2_PCIE_LANE_13_EQUALIZATION_CNTL                                   0x80000a5
#define ixD3F2_PCIE_LANE_14_EQUALIZATION_CNTL                                   0x80000a6
#define ixD3F2_PCIE_LANE_15_EQUALIZATION_CNTL                                   0x80000a6
#define ixD3F2_PCIE_ACS_ENH_CAP_LIST                                            0x80000a8
#define ixD3F2_PCIE_ACS_CAP                                                     0x80000a9
#define ixD3F2_PCIE_ACS_CNTL                                                    0x80000a9
#define ixD3F2_PCIE_MC_ENH_CAP_LIST                                             0x80000bc
#define ixD3F2_PCIE_MC_CAP                                                      0x80000bd
#define ixD3F2_PCIE_MC_CNTL            