name: Kernel Builder Action (A30s)

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install -y \
          build-essential bc zip curl git \
          libncurses5-dev flex bison \
          python-is-python3 ca-certificates unzip ccache

    - name: Checkout repo
      uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Symlink libmpfr
      run: |
        LIB_PATH=$(ldconfig -p | grep libmpfr.so.6 | head -n1 | awk '{print $NF}')
        if [ -f "$LIB_PATH" ]; then
          sudo ln -sf "$LIB_PATH" /usr/lib/x86_64-linux-gnu/libmpfr.so.4
          echo "Symlinked libmpfr.so.4 -> $LIB_PATH"
        else
          echo "libmpfr.so.6 not found, aborting."
          exit 1
        fi

    - name: Download and setup toolchain
      run: |
        wget "$(curl -s https://raw.githubusercontent.com/XSans0/WeebX-Clang/main/main/link.txt)" -O "clang.tar.gz"
        trap 'rm -rf clang.tar.gz' EXIT
        mkdir -p toolchain/ && tar -xvf clang.tar.gz -C toolchain/

    - name: Make defconfig
      run: |
        echo "Building defconfig"
        make O=out ARCH=arm64 exynos7885-a30s_defconfig -j$(nproc)

    - name: Make kernel
      run: |
        echo "Building kernel"
        PATH="${{ github.workspace }}/toolchain/bin:${{ github.workspace }}/toolchain/bin:${PATH}" make -j$(nproc) O=out ARCH=arm64 ANDROID_MAJOR_VERSION=r LLVM_DIS=llvm-dis AR=llvm-ar NM=llvm-nm LD=ld.lld OBJDUMP=llvm-objdump STRIP=llvm-strip CC=clang LD_LIBRARY_PATH="${{ github.workspace }}/toolchain/lib:$LD_LIBRARY_PATH" CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- Image

    - name: Build DTB
      run: |
        echo "Building DTB"
        PATH="${{ github.workspace }}/toolchain/bin:${{ github.workspace }}/toolchain/bin:${PATH}" make -j$(nproc) O=out ARCH=arm64 ANDROID_MAJOR_VERSION=r LLVM_DIS=llvm-dis AR=llvm-ar NM=llvm-nm LD=ld.lld OBJDUMP=llvm-objdump STRIP=llvm-strip CC=clang LD_LIBRARY_PATH="${{ github.workspace }}/toolchain/lib:$LD_LIBRARY_PATH" CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- dtb.img
        cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img

    - name: Zip kernel
      shell: bash
      run: |
        if [ ! -f out/arch/arm64/boot/Image ]; then
          echo "Build failed: Image not found"
          exit 1
        fi

        cp out/arch/arm64/boot/Image AnyKernel3/Image

        FILES=(
          "Image"
          "version"
          "META-INF/com/google/android/update-binary"
          "META-INF/com/google/android/updater-script"
          "tools/ak3-core.sh"
          "tools/busybox"
          "tools/magiskboot"
          "tools/tweaks.zip"
          "anykernel.sh"
        )

        [ -f "AnyKernel3/dtb.img" ] && FILES+=("dtb.img")

        git submodule update --init

        cd AnyKernel3
        DEVICE="A30s"
        KERNEL_VERSION="$(grep UTS_RELEASE ${{ github.workspace }}/out/include/generated/utsrelease.h"
        echo "kernel_version=${KERNEL_VERSION}" >> $GITHUB_ENV
        ZIP_NAME="${DEVICE}_${KERNEL_VERSION}"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r9 "../${ZIP_NAME}.zip" "${FILES[@]}"
        cd ..

    - name: Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: "v${{ env.kernel_version }}"
      run: |
        if git tag | grep -q "^${TAG_NAME}$"; then
          echo "Tag '${TAG_NAME}' already exists locally."
        else
          echo "Creating and pushing tag '${TAG_NAME}'"
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG_NAME" -m "GitHub Actions automated release: $TAG_NAME"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin "$TAG_NAME"
        fi
        git checkout --force "$TAG_NAME"

    - name: Upload
      uses: softprops/action-gh-release@v2.6.1
      with:
        tag_name: "v${{ env.kernel_version }}"
        files: "${{ env.ZIP_NAME }}.zip"
        body: "Built from commit ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: false
