0174
#define ixTHM_TMON0_RDIR14_DATA                                                 0xc0300178
#define ixTHM_TMON0_RDIR15_DATA                                                 0xc030017c
#define ixTHM_TMON1_RDIL0_DATA                                                  0xc0300180
#define ixTHM_TMON1_RDIL1_DATA                                                  0xc0300184
#define ixTHM_TMON1_RDIL2_DATA                                                  0xc0300188
#define ixTHM_TMON1_RDIL3_DATA                                                  0xc030018c
#define ixTHM_TMON1_RDIL4_DATA                                                  0xc0300190
#define ixTHM_TMON1_RDIL5_DATA                                                  0xc0300194
#define ixTHM_TMON1_RDIL6_DATA                                                  0xc0300198
#define ixTHM_TMON1_RDIL7_DATA                                                  0xc030019c
#define ixTHM_TMON1_RDIL8_DATA                                                  0xc03001a0
#define ixTHM_TMON1_RDIL9_DATA                                                  0xc03001a4
#define ixTHM_TMON1_RDIL10_DATA                                                 0xc03001a8
#define ixTHM_TMON1_RDIL11_DATA                                                 0xc03001ac
#define ixTHM_TMON1_RDIL12_DATA                                                 0xc03001b0
#define ixTHM_TMON1_RDIL13_DATA                                                 0xc03001b4
#define ixTHM_TMON1_RDIL14_DATA                                                 0xc03001b8
#define ixTHM_TMON1_RDIL15_DATA                                                 0xc03001bc
#define ixTHM_TMON1_RDIR0_DATA                                                  0xc03001c0
#define ixTHM_TMON1_RDIR1_DATA                                                  0xc03001c4
#define ixTHM_TMON1_RDIR2_DATA                                                  0xc03001c8
#define ixTHM_TMON1_RDIR3_DATA                                                  0xc03001cc
#define ixTHM_TMON1_RDIR4_DATA                                                  0xc03001d0
#define ixTHM_TMON1_RDIR5_DATA                                                  0xc03001d4
#define ixTHM_TMON1_RDIR6_DATA                                                  0xc03001d8
#define ixTHM_TMON1_RDIR7_DATA                                                  0xc03001dc
#define ixTHM_TMON1_RDIR8_DATA                                                  0xc03001e0
#define ixTHM_TMON1_RDIR9_DATA                                                  0xc03001e4
#define ixTHM_TMON1_RDIR10_DATA                                                 0xc03001e8
#define ixTHM_TMON1_RDIR11_DATA                                                 0xc03001ec
#define ixTHM_TMON1_RDIR12_DATA                                                 0xc03001f0
#define ixTHM_TMON1_RDIR13_DATA                                                 0xc03001f4
#define ixTHM_TMON1_RDIR14_DATA                                                 0xc03001f8
#define ixTHM_TMON1_RDIR15_DATA                                                 0xc03001fc
#define ixTHM_TMON0_INT_DATA                                                    0xc0300300
#define ixTHM_TMON1_INT_DATA                                                    0xc0300304
#define ixTHM_TMON0_DEBUG                                                       0xc0300310
#define ixTHM_TMON1_DEBUG                                                       0xc0300314
#define ixGENERAL_PWRMGT                                                        0xc0200000
#define ixCNB_PWRMGT_CNTL                                                       0xc0200004
#define ixSCLK_PWRMGT_CNTL                                                      0xc0200008
#define ixTARGET_AND_CURRENT_PROFILE_INDEX                                      0xc0200014
#define ixCG_FREQ_TRAN_VOTING_0                                                 0xc02001a8
#define ixCG_FREQ_TRAN_VOTING_1                                                 0xc02001ac
#define ixCG_FREQ_TRAN_VOTING_2                                                 0xc02001b0
#define ixCG_FREQ_TRAN_VOTING_3                                                 0xc02001b4
#define ixCG_FREQ_TRAN_VOTING_4                                                 0xc02001b8
#define ixCG_FREQ_TRAN_VOTING_5                                                 0xc02001bc
#define ixCG_FREQ_TRAN_VOTING_6                                                 0xc02001c0
#define ixCG_FREQ_TRAN_VOTING_7                                                 0xc02001c4
#define ixPLL_TEST_CNTL                                                         0xc020003c
#define ixCG_STATIC_SCREEN_PARAMETER                                            0xc0200044
#define ixCG_DISPLAY_GAP_CNTL                                                   0xc0200060
#define ixCG_DISPLAY_GAP_CNTL2                                                  0xc0200230
#define ixCG_ACPI_CNTL                                                          0xc0200064
#define ixSCLK_DEEP_SLEEP_CNTL                                                  0xc0200080
#define ixSCLK_DEEP_SLEEP_CNTL2                                                 0xc0200084
#define ixSCLK_DEEP_SLEEP_CNTL3                                                 0xc020009c
#define ixSCLK_DEEP_SLEEP_MISC_CNTL                                             0xc0200088
#define ixLCLK_DEEP_SLEEP_CNTL                                                  0xc020008c
#define ixLCLK_DEEP_SLEEP_CNTL2                                                 0xc0200310
#define ixTARGET_AND_CURRENT_PROFILE_INDEX_1                                    0xc02000f0
#define ixCG_ULV_PARAMETER                                                      0xc020015c
#define ixSCLK_MIN_DIV                                                          0xc0200308
#define ixLCAC_SX0_CNTL                                                         0xc0400d00
#define ixLCAC_SX0_OVR_SEL                                                      0xc0400d04
#define ixLCAC_SX0_OVR_VAL                                                      0xc0400d08
#define ixLCAC_MC0_CNTL                                                         0xc0400d30
#define ixLCAC_MC0_OVR_SEL                                                      0xc0400d34
#define ixLCAC_MC0_OVR_VAL                                                      0xc0400d38
#define ixLCAC_MC1_CNTL                                                         0xc0400d3c
#define ixLCAC_MC1_OVR_SEL                                                      0xc0400d40
#define ixLCAC_MC1_OVR_VAL                                                      0xc0400d44
#define ixLCAC_MC2_CNTL                                                         0xc0400d48
#define ixLCAC_MC2_OVR_SEL                                                      0xc0400d4c
#define ixLCAC_MC2_OVR_VAL                                                      0xc0400d50
#define ixLCAC_MC3_CNTL                                                         0xc0400d54
#define ixLCAC_MC3_OVR_SEL                                                      0xc0400d58
#define ixLCAC_MC3_OVR_VAL                                                      0xc0400d5c
#define ixLCAC_CPL_CNTL                                                         0xc0400d80
#define ixLCAC_CPL_OVR_SEL                                                      0xc0400d84
#define ixLCAC_CPL_OVR_VAL                                                      0xc0400d88
#define mmROM_SMC_IND_INDEX                                                     0x80
#define mmROM0_ROM_SMC_IND_INDEX                                                0x80
#define mmROM1_ROM_SMC_IND_INDEX                                                0x82
#define mmROM2_ROM_SMC_IND_INDEX                                                0x84
#define mmROM3_ROM_SMC_IND_INDEX                                                0x86
#define mmROM_SMC_IND_DATA                                                      0x81
#define mmROM0_ROM_SMC_IND_DATA                                                 0x81
#define mmROM1_ROM_SMC_IND_DATA                                                 0x83
#define mmROM2_ROM_SMC_IND_DATA                                                 0x85
#define mmROM3_ROM_SMC_IND_DATA                                                 0x87
#define ixROM_CNTL                                                              0xc0600000
#define ixPAGE_MIRROR_CNTL                                                      0xc0600004
#define ixROM_STATUS                                                            0xc0600008
#define ixCGTT_ROM_CLK_CTRL0                                                    0xc060000c
#define ixROM_INDEX                                                             0xc0600010
#define ixROM_DATA                                                              0xc0600014
#define ixROM_START                                                             0xc0600018
#define ixROM_SW_CNTL                                                           0xc060001c
#define ixROM_SW_STATUS                                                         0xc0600020
#define ixROM_SW_COMMAND                                                        0xc0600024
#define ixROM_SW_DATA_1                                                         0xc0600028
#define ixROM_SW_DATA_2                                                         0xc060002c
#define ixROM_SW_DATA_3                                                         0xc0600030
#define ixROM_SW_DATA_4                                                         0xc0600034
#define ixROM_SW_DATA_5                                                         0xc0600038
#define ixROM_SW_DATA_6                                                         0xc060003c
#define ixROM_SW_DATA_7                                                         0xc0600040
#define ixROM_SW_DATA_8                                                         0xc0600044
#define ixROM_SW_DATA_9                                                         0xc0600048
#define ixROM_SW_DATA_10                                                        0xc060004c
#define ixROM_SW_DATA_11                                                        0xc0600050
#define ixROM_SW_DATA_12                                                        0xc0600054
#define ixROM_SW_DATA_13                                                        0xc0600058
#define ixROM_SW_DATA_14                                                        0xc060005c
#define ixROM_SW_DATA_15                                                        0xc0600060
#define ixROM_SW_DATA_16                                                        0xc0600064
#define ixROM_SW_DATA_17                                                        0xc0600068
#define ixROM_SW_DATA_18                                                        0xc060006c
#define ixROM_SW_DATA_19                                                        0xc0600070
#define ixROM_SW_DATA_20                                                        0xc0600074
#define ixROM_SW_DATA_21                                                        0xc0600078
#define ixROM_SW_DATA_22                                                        0xc060007c
#define ixROM_SW_DATA_23                                                        0xc0600080
#define ixROM_SW_DATA_24                                                        0xc0600084
#define ixROM_SW_DATA_25                                                        0xc0600088
#define ixROM_SW_DATA_26                                                        0xc060008c
#define ixROM_SW_DATA_27                                                        0xc0600090
#define ixROM_SW_DATA_28                                                        0xc0600094
#define ixROM_SW_DATA_29                                                        0xc0600098
#define ixROM_SW_DATA_30                                                        0xc060009c
#define ixROM_SW_DATA_31                                                        0xc06000a0
#define ixROM_SW_DATA_32                                                        0xc06000a4
#define ixROM_SW_DATA_33                                                        0xc06000a8
#define ixROM_SW_DATA_34                                                        0xc06000ac
#define ixROM_SW_DATA_35                                                        0xc06000b0
#define ixROM_SW_DATA_36                                                        0xc06000b4
#define ixROM_SW_DATA_37                                                        0xc06000b8
#define ixROM_SW_DATA_38                                                        0xc06000bc
#define ixROM_SW_DATA_39                                                        0xc06000c0
#define ixROM_SW_DATA_40                                                        0xc06000c4
#define ixROM_SW_DATA_41                                                        0xc06000c8
#define ixROM_SW_DATA_42                                                        0xc06000cc
#define ixROM_SW_DATA_43                                                        0xc06000d0
#define ixROM_SW_DATA_44                                                        0xc06000d4
#define ixROM_SW_DATA_45                                                        0xc06000d8
#define ixROM_SW_DATA_46                                                        0xc06000dc
#define ixROM_SW_DATA_47                                                        0xc06000e0
#define ixROM_SW_DATA_48                                                        0xc06000e4
#define ixROM_SW_DATA_49  